[WIP] Key verification using QR codes
matrix-org/matrix-doc pull request #1544
Opened 2018-08-20 19:38 UTC by uhoreg

Rendered: https://github.com/uhoreg/matrix-doc/blob/qr_key_verification/proposals/1543-qr_code_key_verification.md

2018-08-21 01:26 UTC, ara4n submitted a review, later dismissed

2018-08-21 11:35 UTC, non-Jedi commented on proposals/1543-qr_code_key_verification.md
> +   <device-id> <device-signing-public-key>`.  (This format matches the
(Why is this a threaded comment? One of the key takeaways from discussions around #1426 and #1421 was that a single thread of comments on the main issue was easier to follow for discussions of substance than inline comments on GH or gdoc. Has there been new consensus against that conclusion?)

As when using matrix.to as a namespace has been suggested in the past, I have to strongly object to the idea. While any particular client using matrix.to for this purpose would be completely fine, having the spec depend on a single point of failure that can be owned by a single entity just isn't the right way of doing things.

I understand that in the world being described matrix.to would be a namespace first and a URL second, but the fact of the matter is that it's still a URL. If the only thing the URLs on matrix.to were supposed to be used for were a namespace, we could pick much simpler namespacing schemes.

2018-08-21 16:17 UTC, richvdh commented on proposals/1543-qr_code_key_verification.md
> +   <device-id> <device-signing-public-key>`.  (This format matches the
> (Why is this a threaded comment? One of the key takeaways from discussions around #1426 and #1421 was that a single thread of comments on the main issue was easier to follow

PLEASE NO. A single stream of consciousness with no clue as to what is still relevant and what is not is *awful* to follow.

2018-09-08 03:43 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +5. Alice's device sends a `m.key.verification.reciprocate` message (see below)
Maybe use `m.key.verification.start`, using the same event type as in [MSC1267](https://github.com/matrix-org/matrix-doc/issues/1267), but with a different `method`.

2018-12-11 15:30 UTC, erikjohnston commented
Can we not reuse the "Interactive Key Verification" method, and simply have the QR code used to set the user and device that is being verified?

2018-12-11 18:10 UTC, uhoreg commented
> Can we not reuse the "Interactive Key Verification" method, and simply have the QR code used to set the user and device that is being verified?

Possibly, but if we're scanning a QR code, it doesn't inconvenience the user to also throw in the key data.  Also, the interactive key verification is more complicated, and so people may implement this before implementing the other.

2018-12-12 11:36 UTC, erikjohnston commented
> > Can we not reuse the "Interactive Key Verification" method, and simply have the QR code used to set the user and device that is being verified?
> 
> Possibly, but if we're scanning a QR code, it doesn't inconvenience the user to also throw in the key data. Also, the interactive key verification is more complicated, and so people may implement this before implementing the other.

My main concern is basically being able to reuse the same method for other QR code style mechanisms, but I take your point. I was hoping that we could split up IKV into two steps or something, so that you could reuse some of it when you already had a shared secret

2019-01-09 08:17 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +`https://matrix.to/#/<user-id>?device=<device-id>&action=verify&key_<keyid>=<key-in-base64>...`
the idea is that arbitrary apps and OSes will be able to scan the QR code and do something useful with it (ie redirect over to a matrix client), aiui

2019-01-09 09:39 UTC, jryans commented on proposals/1543-qr_code_key_verification.md
> +`https://matrix.to/#/<user-id>?device=<device-id>&action=verify&key_<keyid>=<key-in-base64>...`
Ah, thanks. I see there was a previous discussion thread about this above. (I was on mobile before, where it was apparently hidden from me... 😭)

2020-01-18 01:16 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +`https://matrix.to/#/<user-id>?&action=verify&key_<keyid>=<key-in-base64>...`
```suggestion
`https://matrix.to/#/<user-id>?action=verify&key_<keyid>=<key-in-base64>...`
```

2020-01-18 02:43 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +`https://matrix.to/#/<user-id>?request=<event-id>&action=verify&key_<keyid>=<key-in-base64>...&verification_algorithms=<algorithm>&verification_key=<random-key-in-base64>&other_user_key=<master-key-i
where do the verification_algorithms and verification_key come from?

2020-01-22 15:48 UTC, bmarty commented on proposals/1543-qr_code_key_verification.md
> +- `secret`: is a random single-use shared secret in unpadded base64. It must be
`secret` is actually `random-key-in-base64` isn't?

2020-01-22 15:48 UTC, bmarty commented on proposals/1543-qr_code_key_verification.md
> +`https://matrix.to/#/<user-id>?request=<event-id>&action=verify&key_<keyid>=<key-in-base64>...&verification_algorithms=<algorithm>&verification_key=<random-key-in-base64>&other_user_key=<master-key-i
Why a `s` in `verification_algorithms`? Is it a list?

2020-01-22 16:59 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +`https://matrix.to/#/<user-id>?request=<event-id>&action=verify&key_<keyid>=<key-in-base64>...&verification_algorithms=<algorithm>&verification_key=<random-key-in-base64>&other_user_key=<master-key-i
They come from a previous version of the proposal, and I apparently didn't update the string when I changed the way it works.

```suggestion
`https://matrix.to/#/<user-id>?request=<event-id>&action=verify&key_<keyid>=<key-in-base64>...&secret=<shared-secret>&other_user_key=<master-key-in-base64>`
```

2020-01-22 17:00 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +- `secret`: is a random single-use shared secret in unpadded base64. It must be
I've updated the URL example to be actually correct.

2020-01-24 07:15 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +3. Alice's client displays a QR code that Bob is able to scan, and an option to
it'd be super useful (for understanding how this works) to enumerate the items encoded in the QR code at this point, rather than having to skip to the end to find out.

2020-01-24 07:16 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +   If any of these checks fail, Alice's device displays an error message.
what should the error message(s) say?

2020-01-24 07:16 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +   to `m.reciprocate.v1` to Bob (see below).
for understanding the flow, it would be useful to spell out what the payload of the reciprocate message is (presumably just Bob's `secret`, which Alice is sending back to him?)

2020-01-24 07:17 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +8. Upon receipt of the `m.key.verification.start` message, Bob's device
Before this happens, doesn't Bob need to confirm that the `secret` in the reciprocate matches his one?

2020-01-24 07:19 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +7. Alice's device sends a `m.key.verification.start` message with `method` set
Is this encrypted or signed to stop the sender being spoofed?

2020-01-24 07:22 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +9. Bob sees Alice's device confirm that the key matches, and presses the button
If the m.key.verification.start isn't encrypted, isn't there an attack where an evil HS admin called Eve shouldersurfs Bob's QR code and then MITMs the reciprocate msg?

 * Bob shows his QR code
 * Eve scans it.
 * Alice scans it, and sends the reciprocate msg to Bob
 * Eve intercepts the reciprocate msg, dropping Alice's and replacing it with her own (using the same secret)
 * Bob confirms that Alice has indeed scanned him successfully
 * Bob trusts Eve.

I think there's also a variation of this where Eve doesn't MITM the reciprocate but just sends her own - but times it right so that Bob gets confused and thinks Alice did scan him when it was actually Eve, and hits the "confirm" button (to Eve's horror) and gets pwned.

2020-01-24 07:29 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +generated by Bob's device.  The QR code will encode both Bob's key as well as what Bob
I second @erikjohnston's concerns from https://github.com/matrix-org/matrix-doc/pull/1544#issuecomment-446244070 that it might be nicer to support interactive verification instead.
I think the advantages are:
 * We already have the code everywhere for emojis
 * The data encoded in the QR code is way smaller (the URLs proposed here are massive, creating large ugly QR codes)
 * It simplifies understanding of the proposal
I think the disadvantage is:
 * You can't print out QR codes on business cards, as the code will be dynamically produced every time.

2020-01-24 07:32 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +generated by Bob's device.  The QR code will encode both Bob's key as well as what Bob
However, the QR code on business card use-case is quite a nice one, so perhaps we might want both in time.

2020-01-24 16:02 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +generated by Bob's device.  The QR code will encode both Bob's key as well as what Bob
The reasons why we're doing it this way for QR code is that

- we can have a similar format for in-person verification and for business cards, and
- this method requires less communication between devices, so will be quicker to do (with the SAS verification, there can be a significant delay before the SAS shows up)

2020-01-24 16:05 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +   If any of these checks fail, Alice's device displays an error message.
Depending on how alarming we want to be, it should say something along the lines of "The server gave you the wrong keys for Bob.  You shouldn't trust your server."

2020-01-24 16:11 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +9. Bob sees Alice's device confirm that the key matches, and presses the button
The reciprocate message doesn't affect what key that Bob trusts.  The only way that Bob would trust Eve is if Bob's server sent Eve's key to Bob when he asks for Alice's key.  In this case, the QR code that Bob shows to Alice will contain Eve's key rather than Alice's key.  But then, when Alice scans the QR code, she will notice that the QR code has the wrong key, and her device will display an error message.  Unless Alice manages to move her device away from in front of Bob's device faster than her device can compare a few strings (i.e. within a couple milliseconds), her device will display an error before Bob can react to his devices prompting him to verify.

2020-01-24 16:12 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +   device says that things match.
Need to also note that there should be a button for him to press in the event that Alice's device says that things don't match, or if Alice has not scanned yet.

2020-01-24 16:18 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +8. Upon receipt of the `m.key.verification.start` message, Bob's device
Yes.  Will add

2020-01-24 16:32 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +generated by Bob's device.  The QR code will encode both Bob's key as well as what Bob
Another reason why it was originally done this way was that we didn't know which device you're verifying against, so you don't know where to send the SAS handshake messages to.  Though now that we have the `ready` message, that may not be applicable any more?

2020-01-24 17:23 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +7. Alice's device sends a `m.key.verification.start` message with `method` set
It doesn't have to be encrypted or signed.  At this point, Bob doesn't know what key should be trusted to sign anyways.

2020-01-24 17:58 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +3. Alice's client displays a QR code that Bob is able to scan, and an option to
Have added below

2020-01-24 20:21 UTC, ara4n commented on proposals/1543-qr_code_key_verification.md
> +9. Bob sees Alice's device confirm that the key matches, and presses the button
oh right - the penny finally dropped; for my notes (and anyone else ever reading this): we're just confirming that Bob's copy of the keys matches Alice's copy of the keys, by sending them out-of-band via QR from Bob to Alice, having Alice compare them, and then if Alice says she's happy, Bob infers he must be happy too.  The `secret` is just there to make it harder for Eve to spoof a reciprocate message to try to cause confusion (although if she colludes with the HS admin, she can MITM the secret anyway).  (@uhoreg, is this right?)

So the actual worst-case scenario attack here is:

 * Eve makes Bob's server send him Eve's keys rather than Alice's
 * Bob shows his QR code
 * Eve shoulder-surfs it to get the secret
 * Alice is faffing around trying to scan Bob's QR code
 * Eve spoofs the reciprocate message with that secret from Alice to Bob 
 * Bob sees a big green button appear, assumes that Alice must have scanned it successfully, yanks his phone away before Alice can protest, and blindly hits 'ok', trusts Eve, who immediately keyshare requests all his megolm keys.
 * ...or... Alice's phone manages to scan the compromised code, shows a big red "you're under attack" warning, but this races with the spoofed reciprocate message to Bob, who sees a big green button and hits "ok", before he registers Alice's panicking noises.

The fact they can know they've been pwned and revoke Eve is not much use if she's already stolen history or SSSS keys etc.

It feels like there's a concrete risk of this attack being viable.

Assuming i've got it right, this time, is there an equivalent attack for SAS verif?   If not, this feels like another slight advantage in favour of showing SAS codes in QR rather than the blunt keys.

2020-01-25 10:17 UTC, nadonomy commented on proposals/1543-qr_code_key_verification.md
> +generated by Bob's device.  The QR code will encode both Bob's key as well as what Bob
@ara4n @uhoreg I would **_very strongly_** advocate for us to leave the 'business card' use case on the shelf right now and concentrate on the interactive verification use case. Or, just not design it out of the protocol for future.

The user goals for this case are totally different, and raise their own set of concerns we'd need to lay before implementing it. Users wouldn't naturally reach to do this through the UX, so for  discoverability it would be better served by a new one. We haven't validated all of the user concerns that could impact the technical decisions— if I'm committing a QR code to print, what happens if I lose or add a new device? Or change my keys/recovery method, etc? What other things haven't we thought about or validated?

We should be super crystal clear on how the user goals impact the technical implementations before this use case is factoring greatly into decision making. Right now it very much feels like a distraction, both (a) how it's informing the implementation details meaning we're delivering a worse UX for interactive verification & (b) the opportunity cost of us spending time on this now.

2020-01-27 16:22 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +9. Bob sees Alice's device confirm that the key matches, and presses the button
SAS-over-QR would have a similar issue.  With SAS, Alice and Bob both need to check that the emoji match, and they need to hit the confirm button.  With SAS-over-QR, Alice would be in charge of making sure that the QR code matches what's expected, and then telling Bob whether to hit the OK or the Panic button, so if we're worried about Bob hitting the OK button before Alice says whether it's OK or not, then we get the same thing.

Perhaps instead of presenting it as a "Confirm" or "Panic", we can have Bob's device, when it receives the "reciprocate" message, say "Did Alice successfully scan the code? Yes/No", which at least will indicate that Bob should ask Alice for the verdict rather than just blindly hitting "OK".

2020-01-28 04:37 UTC, ara4n commented
the clarifications are great, but i’m worried that the core misunderstanding that bit me and erik is still missing: that the reciprocate message is just an untrusted ack to tell the verifiee that the verifer claims now to have trusted them (and so they should trust the verifiee too):

> oh right - the penny finally dropped; for my notes (and anyone else ever reading this): we're just confirming that Bob's copy of the keys matches Alice's copy of the keys, by sending them out-of-band via QR from Bob to Alice, having Alice compare them, and then if Alice says she's happy, Bob infers he must be happy too. The secret is just there to make it harder for Eve to spoof a reciprocate message to try to cause confusion (although if she colludes with the HS admin, she can MITM the secret anyway). (@uhoreg, is this right?)

There’s still something that feels a bit weird though about the verifiee trusting the verifier based on the contents of a single untrusted bit. But I guess the point is that the “you can trust me” bit travels over both OOB via QR as well as over Matrix, which provides multi-factor auth (and means the bit doesn’t need to be signed somehow).

This is sufficiently counterintuitive that we should really spell it explicitly out, imo.

2020-01-30 13:36 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
>  - `request`: is the event ID of the associated verification request event.
This would need to be optional for self-verification given it is over to_device?

2020-02-19 20:06 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +#### Binary format
for future/current readers: this is the format being preferred at the moment.

2020-02-19 20:58 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +- one byte indicating the QR code verification mode.  May be one of the
Do we need the mode? What purpose does it serve?

2020-02-19 22:59 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +  - if `0x00` or `0x01`, then the user's own master cross-signing public key
```suggestion
  - if `0x00` or `0x01`, then the current user's own master cross-signing public key
```

2020-02-27 16:37 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +- a random shared secret, as a byte string.  It is suggested to use a secret
can we pick an encoding? JS for instance doesn't seem to really like just arbitrary byte strings and would really like it if you provided an encoding.

For now, I'll assume utf-8

2020-02-27 17:04 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +- a random shared secret, as a byte string.  It is suggested to use a secret
turns out riot-web just encodes it as binary and nothing to do with a string

2020-02-27 17:23 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +- one byte indicating the QR code verification mode.  May be one of the
It's mostly a sanity check to make sure that the scanner and the scannee agree on what mode they're doing.  So that, for example, if you scan your own device, and neither of them have trusted the cross-signing key yet, it can display something sensible.

2020-03-30 11:53 UTC, bwindels commented on proposals/1543-qr_code_key_verification.md
> +9. Upon receipt of the `m.key.verification.start` message, Bob's device ensures
If this message is unencrypted (AFAIK there is no assumption verification runs over an encrypted channel atm), wouldn't an malicious homeserver admin be able to intercept the shared secret and be able to get Bob to sign the wrong key for Alice by dropping Alice's `.start` event and sending their own?

2020-03-30 12:05 UTC, bwindels commented on proposals/1543-qr_code_key_verification.md
> +9. Upon receipt of the `m.key.verification.start` message, Bob's device ensures
Hmm, I guess not as the QR code contains the cross-signing key Bob has for Alice, and she would've cancelled the request if it didn't match her own key. That might have gotten intercepted by the HS as well, but her device would have shown a big error, which is why the reciprocate is so important I guess :bulb:

Makes me wonder why we have the shared secret at all though?

2020-03-30 14:28 UTC, bwindels commented on proposals/1543-qr_code_key_verification.md
> +9. Upon receipt of the `m.key.verification.start` message, Bob's device ensures
*sigh*, Matthew already commented the exactly same though [1](https://github.com/matrix-org/matrix-doc/pull/1544#discussion_r370500052), [2](https://github.com/matrix-org/matrix-doc/pull/1544#issuecomment-579076398) :) Never mind ...

2020-03-31 09:03 UTC, bwindels commented on proposals/1543-qr_code_key_verification.md
> +10. Bob sees Alice's device confirm that the key matches, and presses the button
The Riot UX shows a "Yes" / "No" button to confirm Alice scanned the QR code. What cancellation code should be used for the `.cancel` event sent when "No" is pressed?

2020-03-31 09:56 UTC, bwindels commented on proposals/1543-qr_code_key_verification.md
> +   - what Bob thinks Alice's master cross-signing public key is,
I guess it's important to keep around a copy of this key in memory for when to time comes to cross-sign it, and not just take whatever key we have stored for the user at the time we're ready to sign, otherwise a malicious homeserver admin could, with a well-timed attack, forge a cross-signing identity reset for Alice between the `.ready` and `.start` event and have Bob sign the new keys instead of the keys that were in the QR code. Am I correct in thinking this could be a possible attack?

I'm adding this as I just noticed Riot web wasn't doing it and was wondering if it's a sufficient pitfall to mention it here.

2020-03-31 10:34 UTC, dbkr commented on proposals/1543-qr_code_key_verification.md
> +   - what Bob thinks Alice's master cross-signing public key is,
yeah, I think this may be a good point actually, in that we have to be careful not to just get the key out of the device list again when it comes to signing it.

2020-03-31 21:15 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +10. Bob sees Alice's device confirm that the key matches, and presses the button
Good question.  If we want to use an existing error code, I think `m.user` would make the most sense.  Or maybe `m.unexpected_message`.

2020-04-02 10:26 UTC, bwindels commented on proposals/1543-qr_code_key_verification.md
> +10. Bob sees Alice's device confirm that the key matches, and presses the button
Going with `m.user` :+1:

2020-04-21 02:31 UTC, turt2live commented
I've reassigned this to 1544 instead of 1543 to reduce confusion in the MSC numbers. Please consider renaming the file.

2020-04-22 20:24 UTC, uhoreg commented
@mscbot fcp merge

2020-05-22 08:08 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
Unfortunately soru sees several issues with how this proposal is currently layed out:

1st: It does not seem to be in-line with the current spec. Sending `m.key.verification.start` is supposed to *start* the verification process, here QR codes are displayed (and thus the verification process started) *before* that is sent.
2nd: If both sides of the verification advertise as being able to be able to both scan and display a QR code, we get a problem: As there is no additional message exchanged on what was agreed to verify with, it could happen that both get a QR code displayed or both get a camera to scan the others code. While a button could be introduced in the UI to switch between scan and display, this scenario will likely leave many people baffled and "meh, this is broken" and then not verify each other
3rd: There is no real way to do SAS instead of QR code verification: As QR codes are displayed / scanned after receiving `m.key.verification.ready`, it is impossible to pick e.g. SAS instead of QR code verification. While a button could be introduced for "Oh no, I actually want to do SAS" this is bad UX.
4th: This is not future-proof: Let's say in the future an even more seemless verification method is introduced (background bluetooth/NFC or something between two phones?), how should this be started? Also before sending `m.key.verification.start`? What if both can do the new method and QR code? What if one displays the QR code and the other one expects to do the new method? The user is likely to think that the verification process is broken, even if there is a button to switch between different methods.
5th: This diminishes a big advantage of #2366 : One point of #2366 was to introduce `m.key.verification.ready` so that both parties can pick which verification method to use, if e.g. one of them is more tech savvy and uses a more tech savvy client. As verification starts prior sending `m.key.verification.start` this becomes impossible, diminishing its affects.

All these points seem to be fixed by not displaying / scanning QR codes until *after* an `m.key.verification.start` is sent, with the method (`m.reciprocate.v2` (v2 as v1 is already implemented in many and this is a breaking change to this proposal)) and what the other person should do, based on their capabilities (`m.qr_code.show.v1`, `m.qr_code.scan.v1`). Then, after scanning a new message is sent (`m.key.verification.reciprocate`?) which contains the information currently in `m.key.verification.start`. With that, all the mentioned issues are solved.

A client can still automatically pick QR code over SAS, for example, but, as the clients *agree* on what to verify with prior to verifying we diminish the situation that, e.g. in the future, if there is let's say bluetooth verification, and both clients can do QR, bluetooth and SAS, one will pick to do QR and one will pick to do bluetooth. Explicitly stating what is to be done in `m.key.verification.start` is appropriate here.

2020-05-22 08:10 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +already set up, and the other one (Dynabook) having just logged in.
How do we know which device just logged in and which one not?

2020-05-26 17:24 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +already set up, and the other one (Dynabook) having just logged in.
The one that has not yet been signed by the cross-signing key is the one that just logged in.

2020-08-27 12:04 UTC, richvdh commented on proposals/1543-qr_code_key_verification.md
> +Note: only one of the following will be supported.  They are all being
Shouldn't we pick one?

2020-08-28 15:29 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +generated by Bob's device.  The QR code will encode both Bob's key as well as what Bob
The current version now ignores the business-card use case and only focuses on interactive verification.

2020-08-28 15:51 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +Note: only one of the following will be supported.  They are all being
We're going with the Binary format.  I haven't updated the MSC yet to remove the other options.

2020-10-06 14:39 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
Re-visiting this a bit later, soru would propose the following flow to decide which key verification method to use:

1. A `request` and `ready` is exchanged like before
2. Clients *can* then auto-pick a method (sas, reciprocate, etc.), sending a `start`. If a client does this automatically, it *should* only do so if it was also the one initiating the request.
3. Any other client can also send a `start`.
4. `start` gets a new, optional, attribute, `priority`. This is an integer. Higher integer means higher priority. A missing priority is assumed to be 0.
5. The `start` with the highest priority is picked. If two have the same priority, then the current methods for determening whos start to use are being used
6. It does not matter if the `start`'s pick different methods.

This way it is always clear which verification method to display, in addition to allowing the flexibility a pro-user might want.

In most cases, clients would just auto-pick a method, without sending a `priority` at all. For the QR code scanning, the "Use emojis instead" would then send a `start` with a priority of 1.

A pro-user could just override whatever method the person they are trying to verify with automatically picked.

2020-10-19 19:25 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
Sorry for not responding earlier.  The intended UX for this is that, once verification is accepted, the client displays a screen that shows the QR code and offers to scan a QR code or verify by emoji instead.  This is similar to (and probably inspired by) [Signal's "Verify safety numbers" screen](https://signal.org/blog/safety-number-updates/) which shows a QR code, allows the user to scan a QR code, and displays the safety numbers for users to read out.  I think that by immediately showing the QR code, this makes it easier for people to verify each other.

> 1st: It does not seem to be in-line with the current spec. Sending m.key.verification.start is supposed to start the verification process, here QR codes are displayed (and thus the verification process started) before that is sent.

The wording in the spec is maybe slightly inaccurate.  `m.key.verification.start` is the first message sent in a key verification.  QR code scanning doesn't need messages to be exchanged, so it doesn't send an `m.key.verification.start`.  I can add a note in this MSC about this.  But if a verification method doesn't need Matrix messages to be sent, then we should avoid sending unnecessary messages.

> 2nd: If both sides of the verification advertise as being able to be able to both scan and display a QR code, we get a problem: As there is no additional message exchanged on what was agreed to verify with, it could happen that both get a QR code displayed or both get a camera to scan the others code.

The idea is that both sides will automatically show the QR code, and offer to scan instead.

> 3rd: There is no real way to do SAS instead of QR code verification: As QR codes are displayed / scanned after receiving m.key.verification.ready, it is impossible to pick e.g. SAS instead of QR code verification. While a button could be introduced for "Oh no, I actually want to do SAS" this is bad UX.

I disagree that "Oh no, I actually want to do SAS" is bad UX with the way this is intended to work.  If you prompt the user for what method to use before doing anything, then you display three things: a button saying "show QR code", a button saying "scan QR code", and a button saying "verify by emoji".  If you immediately show the QR code without waiting for interaction, you display three things: the QR code, a button saying "scan QR code", and a button saying "verify by emoji".  So the only difference is that you show a QR code instead of a button, which means that the QR code is immediately accessible, and the user only has two buttons to read instead of three.

> 4th: This is not future-proof: Let's say in the future an even more seemless verification method is introduced (background bluetooth/NFC or something between two phones?), how should this be started?

It would depend on the exact verification method.  If it's some sort of wireless thing, the devices could immediately start broadcasting without exchanging Matrix messages.  Devices should be capable of broadcasting a wireless signal, displaying a QR code, and showing a couple buttons at the same time.

One thing to note is that even if a client displays a QR code, it is not committed to using the QR code to verify.  All the other methods are still available until the `m.key.verification.start` is actually sent.

2020-10-20 06:01 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
> I disagree that "Oh no, I actually want to do SAS" is bad UX with the way this is intended to work. If you prompt the user for what method to use before doing anything, then you display three things: a button saying "show QR code", a button saying "scan QR code", and a button saying "verify by emoji". If you immediately show the QR code without waiting for interaction, you display three things: the QR code, a button saying "scan QR code", and a button saying "verify by emoji". So the only difference is that you show a QR code instead of a button, which means that the QR code is immediately accessible, and the user only has two buttons to read instead of three.

The problem is that with QR code (and possible future methods) the other party does not know what the first party selected, due to no data being transmitted. Clients *will* inevitebly just show a QR code with a button "ohno, i want to use emojis instead", such as....element-android already does.

What about sorus suggestion of 14 days ago which solves all these issues by transmitting packages of what is actually happening?

2020-10-26 19:51 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
> The problem is that with QR code (and possible future methods) the other party does not know what the first party selected, due to no data being transmitted.

The point is that the first party did not "select" anything.  It is just presenting a QR code that is available to be scanned, but does not need to be.

> Clients _will_ inevitebly just show a QR code with a button "ohno, i want to use emojis instead", such as....element-android already does.

That's basically how it's intended to operate.  Except that it isn't really an "ohno, I want to use emojis instead".  It's "you have a choice between having the other person scan this QR code that's already displayed, or scanning their QR code, or starting an emoji-based verification."  Though I suppose it's just a matter of opinion how it's viewed.

> What about sorus suggestion of 14 days ago which solves all these issues by transmitting packages of what is actually happening?

We don't want to automatically "pick" anything.  And sending messages when they're not needed will just increase latency.

> As it stands, without advertising to display / scan QR codes we are blocking any future method which could just be automatically started in the future. We will always have to show a QR code by default.

I think that it's unlikely that we're going to add many more verification methods.  Maybe one or two more, and it's unlikely that it's something that would collide with showing a QR code.  I think having one method (emoji/decimal) for low-tech or not-in-person verifications, one method (QR) for more capable devices is sufficient.  *Maybe* we might add some fancy wireless thing (NFC) but we're getting into diminishing returns territory as I'm not sure what practical benefit that would have over QR codes.

2020-11-13 15:15 UTC, anoadragon453 approved these changes

2020-11-13 15:15 UTC, anoadragon453 commented on proposals/1543-qr_code_key_verification.md
> +    "event_id": "!event_id_of_verification_request"
Event IDs start with `$` :)

2020-11-13 15:15 UTC, anoadragon453 commented on proposals/1543-qr_code_key_verification.md
> +the request from event "!ABCD...", her cross-signing key is
likewise

2020-11-20 17:30 UTC, Sorunome requested changes

2020-11-20 17:30 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
While soru knows that she isn't part of the spec core team she is concerned that this isn't addressed properly. Without having more ping-pong game going around to actually *know* what is going on key verification is not future-proof for when new methods come around.

Soru has discussed alternatives of how the exact same UX could be implemented, with the only difference being that, well, it is future proof.

Just re-iterating this as the SMC is enting FCP and that is something that the spec core team should probably take into consideration.

2020-11-21 05:41 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
it seems like there's mostly a misunderstanding going on here and less so a technical issue with the MSC. The MSC doesn't mandate that a client show a QR code instead of SAS or other verification methods, but rather that *if* a client is to display a QR code that it'd be displayed *adjacent* to the QR code.

The QR code is able to be shown ahead of the `start` and SAS attempts because of the nature of its contents. The reason the QR code is even shown at all is because a capabilities (methods) exchange happens where each end says that it can handle the sort of thing. If one end supports scanning and the other showing, it means that when the user scans the other user's QR code it sends a `start` going down that flow. Similarly, either party can decide that QR codes are too difficult and go down the path of emoji or decimal or whatever - just because a QR code is present doesn't mean you're locked into that flow.

Element implemented this MSC ages ago for FOSDEM 2020 and has the "scan QR code *or* click here to start emoji" dialog wired up appropriately, if it helps.

On the requirement that clients are required to show QR codes: they aren't as far as I'm aware (which is a good thing, imo). Some devices might simply be unable to show/generate the QR code, so they'd look at the proposed methods by the other end and pick one it is comfortable with, such as emoji.

2020-11-21 07:45 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
The issue with not knowing if you want to show or scan a QR code was only one of the issues soru mentions, which, while she does not agree with, she feels has been properly addressed. (She has seen it multiple times IRL people being confused when they start verification that both sides just render a QR code, and they needed external help to find the button to switch to scan. An indication that clients *could* follow here to default to scan (with switch button) instead of show (with switch button) would already help greatly)

The bigger issue is that this isn't future-proof: What if, in the future, some new method comes around that, in theory, also does not need any data exchange to start showing / doing stuff? It won't ever be able to be picked as default due QR code being the default according to this msc.

Soru proposed to add explicit signaling that, well, QR code is *actually* used prior to displaying/scanning. Then, (this would require modification of the `m.key.verification.ready` MSC) a new `start` could be sent which switches to emoji verification, if the user taps that button in the UI. This ensures that both parties *know* what verification method they are doing and thus future-proofs the entire thing. This is the bigger part that soru feels is not properly addressed and, if soru read travis comment correctly, he also did not address.

2020-11-21 07:56 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
A disadvantage of explicit signaling that uhoreg mentioned is that the qr code would take longer to be displayed, but that is also incorrect. After exchanging `request` and `ready` clients could already show the qr code like it currently does, while still doing the explicit signaling in the background, and thus ensuring that the key verification flow is future-proof.

2020-11-21 15:53 UTC, uhoreg commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
> The bigger issue is that this isn't future-proof: What if, in the future, some new method comes around that, in theory, also does not need any data exchange to start showing / doing stuff? It won't ever be able to be picked as default due QR code being the default according to this msc.

There is no "default".  If, in the future, some other method doesn't need any data exchange to start doing stuff, then it can begin right away too.  Showing a QR code won't get in the way of another method starting automatically either.  This was already addressed in the second-last paragraph of https://github.com/matrix-org/matrix-doc/pull/1544#discussion_r508007451

Your proposal does not allow for the same UI: if the initiator's client has auto-picked QR code, then there is no way for the initiator to switch to emoji.  Also, I believe your proposal would result in only one client auto-showing the QR code, rather than both doing so, and will cause one client to automatically turn on its camera, which would probably be considered bad behaviour.

> Point 5 of the original comment also plays a role here, that the advantage of #2366 seems to be diminished: a tech-savvy user can't force qr code verification.

I think that auto-displaying the QR code makes up for the inability to force QR code verification.  If two users want to verify by QR code, it's likely that they are in person (or at the very least, can see each others' screens), so the tech-savvy user is more able to help the non-tech-savvy user if necessary.  Forcing a verification method is more important for emoji verification, where the users might only have an audio channel, and doing rounds of "What buttons to you see on your screen now?  ... OK, click the button that says 'foo bar'." can be time consuming.

2020-11-21 16:00 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
> There is no "default". If, in the future, some other method doesn't need any data exchange to start doing stuff, then it can begin right away too. Showing a QR code won't get in the way of another method starting automatically either. This was already addressed in the second-last paragraph of #1544 (comment)

That's the issue, though: In the future when there are *multiple* such things that can immidiately show it will be non-clear which one to show. If one client then wants to force the other client to actually still use the other method, they can't, due to no explicit signaling. This method (like the MSC does it) is very limited and not future proof.

> Your proposal does not allow for the same UI: if the initiator's client has auto-picked QR code, then there is no way for the initiator to switch to emoji. 

Sorus proposal is to also change the #2366 MSC slightly: Allow multiple `start`'s of different types to be sent and add an integer increase to take greater priority over those with a lower number. With that, you can get the same UX

> Also, I believe your proposal would result in only one client auto-showing the QR code, rather than both doing so, and will cause one client to automatically turn on its camera, which would probably be considered bad behaviour.

That is debateable, as soru just mentioned, she has seen people confused with both phones showing the qr code and not knowing what to do, becasue of that. Signaling which client should scan and which one should show is a different issue, though, maybe we should split that off into a separate thread?

> I think that auto-displaying the QR code makes up for the inability to force QR code verification. If two users want to verify by QR code, it's likely that they are in person (or at the very least, can see each others' screens), so the tech-savvy user is more able to help the non-tech-savvy user if necessary. Forcing a verification method is more important for emoji verification, where the users might only have an audio channel, and doing rounds of "What buttons to you see on your screen now? ... OK, click the button that says 'foo bar'." can be time consuming.

And if you implement explicit signaling you get the same UX only that you don't have such arbitrary limitations....

2020-11-21 21:34 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
This spec is future proof - the clients can come up with UX that suits them. If we were to add another method that gets displayed before the start event like QR codes, clients could show their favourite option and have a button for "show QR code instead". Clients could also stop advertising support for QR codes in their methods, thus indicating that they *really* don't want a QR code.

The signaling of which client is supposed to scan vs show is largely a UX problem for the clients themselves. The verification flows do not care which person scans, so one of the clients is failing to represent its UX properly.

Additional signaling feels more like piling onto a problem than solving one, unfortunately. Clients will end up implementing it wrong or be overly confused as to why they have to stack rank two sets of capabilities.

2020-11-21 21:37 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
> This spec is future proof

Not with this MSC. As soon as another verification method is added that can be displayed etc. before any signaling, there will be some clients that disagree if they should display a qr code or the new method. For that you need explicit signaling. And, with explicit signaling under the hood, you can have still exactly the same UX for clients, only with the added benifit that you actually *know* what is going on. The client will reply to the ready with a start already, with whatever it picked as default. Both sides can still display "use method xyz" instead. the UX is the same, only that you are *actually* future-proof then.

2020-11-21 21:42 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
It doesn't sound like you're reading the comments we're posting or trying to understand why the system is proposed as it is, and instead repeating the same argument over and over which has been responded to over and over. As such, I'm personally not convinced that this thread is in a state to block FCP on.

2020-11-21 21:44 UTC, Sorunome commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
To soru it sounds exactly the same way, as if you aren't reading or trying to understand her comments.

So it sounds like there is some bad misscommunication here. If it helps, soru'd be willing to hop in a voicecall or something to explain better.

2020-11-25 20:24 UTC, turt2live commented on proposals/1543-qr_code_key_verification.md
> +Bi-directional Key verification using QR codes
We've discussed this extensively in #matrix-spec:matrix.org and are largely concluding this thread as it currently stands. There's far too many points to cover in a summary comment like this, but the short version is that this MSC is going ahead regardless of this thread and this thread will continue through manifestation of a different MSC which revamps the verification process as a whole. Currently that discussion is being held on an issue until someone has a chance to convert the ideas to an MSC: https://github.com/matrix-org/matrix-doc/issues/2879

2020-11-25 20:26 UTC, turt2live commented
This has finished FCP and we've talked about the contentious points extensively in the #matrix-spec:matrix.org room - see those threads for details on their conclusion.

As such, this MSC is landing as-is though can't be converted to spec until https://github.com/matrix-org/matrix-doc/pull/2366 also lands. It is my intention to propose 2366 for the spec core team's focus for the coming week.

We don't really have a label state for this sort of case, so I'm just going to leave it in finished-fcp until 2366 is landed too.

2020-11-25 20:26 UTC, merged

2021-04-28 20:22 UTC, uhoreg commented
Merged! :tada: