WIPish: MSC1772: Groups as rooms (v2)
matrix-org/matrix-doc pull request #1772
Opened 2019-01-03 18:49 UTC by ara4n

2019-01-06 11:32 UTC, Half-Shot commented on proposals/1772-groups-as-rooms.md
> +The flair image for a group is given by the room avatar.
I'd argue this needs to be done anyway for rooms, and should be part of another proposal. It's a good idea, but not limited to groups.

2019-01-06 11:36 UTC, Half-Shot commented on proposals/1772-groups-as-rooms.md
> +Clients peek in rooms (recursing into subgroups as needed) in order to determine
I assume the proposal plans to fix peeking over federation, though I cannot remember if that was a problem limited to synapse or the spec.

2019-01-06 11:37 UTC, jcgruenhage commented on proposals/1772-groups-as-rooms.md
> +Clients peek in rooms (recursing into subgroups as needed) in order to determine
There is a separate proposal for that

2019-01-06 11:38 UTC, jcgruenhage commented on proposals/1772-groups-as-rooms.md
> +The flair image for a group is given by the room avatar.
Where do you have tiny favicon style room avatars?

2019-01-06 11:49 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +Clients peek in rooms (recursing into subgroups as needed) in order to determine
#1777

2019-01-06 13:51 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +groups and doesn't have to be edited atomically.
i've added an example of how this could look.

2019-01-06 13:52 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +The flair image for a group is given by the room avatar.
it's very plausible for a client to want dedicated favicon-style icons for both room & group avatars. however, i think this is a job in general for the media repository to let users specify custom resolution thumbnails for an image (and is pretty OT for this MSC)

2019-01-06 13:55 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +The flair image for a group is given by the room avatar.
have opened an issue to track it at https://github.com/matrix-org/matrix-doc/issues/1778

2019-01-06 13:56 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +Of these, option 3 feels best?
it's a trade-off between special cases and performance. i think the performance hit and complexity of clients having to peek in arbitrary group-rooms every time they need to validate the flair of some random user popping up in their timeline would be catastrophic, relative to having the server handling that transparently for them.

2019-01-11 15:59 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +Of these, option 3 feels best?
hm, if m.flair's auth events included the membership event of the group, it still wouldn't tell you if subsequently the membership had elapsed...

2019-01-11 16:17 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +## ACLs
hm. so the equivalent of a private room which invites +group:server such that only +group:server (and other explicitly invited groups and users) participate?

2019-01-11 17:14 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +XXX: is there a use case today for having a group where users are unaware of the
hm, so you're worried about your members leaking their MXIDs to one another from a spam/privacy perspective? i guess this is fair enough (but probably doesn't need to be here from the outset)

2019-01-11 17:21 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +XXX: is there a use case today for having a group where users are unaware of the
mostly from a privacy standpoint and less of a spam standpoint (there are easier avenues to spam people than going through a group). Definitely not for this proposal, but wanted to highlight that there is in fact a use case/desire for this functionality.

2019-01-11 19:24 UTC, Half-Shot commented
A high level question: Where does this leave bridges, which currently automatically pool users matching a regex into a group. Would the bridges need to start joining their users to this group and potentially start adding cost to calculating a group?

2019-02-01 23:20 UTC, aaronraimist commented on proposals/1772-groups-as-rooms.md
> +group memnbership as room membership (nesting if required).
```suggestion
group membership as room membership (nesting if required).
```

2019-03-19 11:16 UTC, ludgerh commented on proposals/1772-groups-as-rooms.md
> +## ACLs
Syncing the group membership through the hierarchy of groups and rooms would be essential for other use cases. Actually, coming from a Joomla environment I assumed this is how it works in Matrix right now when starting to build a bridge to a Joomla/Kunena/CBuilder - System. >>> [https://github.com/ludgerh/kdbridge](url)
(Kunena Categories --> Matrix Groups, Kunena Topics --> Matrix Rooms, ...)
The bridge is now testing and I am doing the sync of memberships through the JS-API, which is quite time-consuming (1 transaction every 5 seconds...).

2019-09-03 05:19 UTC, auscompgeek commented
Something that would be extremely useful which seems to be missing here would be the ability to give a PL to a group (or maybe inheriting room PLs from groups?). I suppose that could warrant its own proposal though given it'd change the auth rules, which this looks like it's trying to avoid.

2019-09-03 09:41 UTC, Sorunome commented
It might be worth considering keeping just `+` as a prefix, instead of `#+` as with the later prefixes just start getting more confusing for the user.

2019-09-08 15:55 UTC, KamNull commented
Great work guys. Will this remove or obsolete current communities, or will the transition be smooth?

I'm moving away from Discord, and would like to make my community ASAP, but I'm not sure if it's best to wait for the rewrite to be released first.

2020-01-28 00:31 UTC, BloodyIron commented
Considering the terminology Groups vs Communities, if we expose LDAP/AD Groups/OUs (in addition to Users) to the matrix 3PID ecosystem, how exactly does that line up?

I ask because I really would like to use LDAP/AD group membership to delegate admin/mod/other permissions to a private (non-federated) matrix/riot setup across the whole environment (multiple rooms, etc). And I am curious how these aspects would work going forward with the new communities stuff.

2020-02-21 21:56 UTC, anoadragon453 commented
@KamNull 

> Will this remove or obsolete current communities, or will the transition be smooth?

The migration path isn't currently defined, though I don't currently foresee any technical reasons why an automatic migration couldn't be done (unless the shape changes drastically).

> Considering the terminology Groups vs Communities, if we expose LDAP/AD Groups/OUs (in addition to Users) to the matrix 3PID ecosystem, how exactly does that line up?

External group and matrix group syncing is out of scope for this proposal, but there's no reason a homeserver implementation or integration couldn't sync them up in some way once groups v2 are stable.

2020-04-06 22:31 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +behave as a group - i.e. the rooms which it groups together, and any subgroups
What would happen if `"rooms"` contained a room that is a group? Would this be treated as a `"subgroup"` (so all members would be added to the group) or would it allow organizing groups within other groups without combining the member lists?

2020-04-06 22:40 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +## ACLs
If this were to be added, would it be possible to add members to a room (with `synced_membership: true`) that are _not_ members of the parent group?

2020-04-09 03:19 UTC, Alch-Emi commented on proposals/1772-groups-as-rooms.md
> +for group `+test:example.com` is `#+test:example.com`.
Do you think we could just drop the + prefix altogether?  I'd argue that it's not super necessary.  Clients are able to determine if a room represents a group by either

a) checking if it's listed as a subgroup of another group (if in the appropriate context

or b) checking if there's a `m.room.groups`/`m.room.group` set

and users would be able to tell by the difference in the UI for the two.  Adding the plus also kinda creates two grey areas when the presence of a `m.room.groups` conflicts with the presence of a plus, which might either complicate the spec or create inconsistent behavior in clients.

If we didn't require the plus at all, clients could very simply just add a "Linked Rooms" menu to the UI, and put the lobby chat below that, without needing to care about whether or not the room is technically a group or not.  In this way, rooms and groups become even closer in terms of implementation.

I could see this being a bit of a difference when it comes to a user seeing a link to a matrix room without knowing what kind of room that room is.  A plus /would/ clarify this to them, but I'd argue that it might even be better to leave it out.

Let's say a group is advertising their matrix room with a message like, "Come chat with us on Matrix!  #+coolpeople:our.server".  In this case, the user doesn't care too much about whether or not their joining a single room or a hub room.  That's something they'd find out when they got there, but they were going to open it anyway.  

But, seeing two different kinds of links might make things ever so slightly more complex from their perspective.  They don't know what a +room:server.com is or why it's different than a #room:server.com and it makes Matrix seem big and scary and confusing, even if that's something that they'd figure out pretty quick.

Having a simple and consistent way to refer to and join rooms removes unnecessary complications from the end user, and special cases from client implementors.  Thoughts?

2020-04-09 03:28 UTC, Alch-Emi commented on proposals/1772-groups-as-rooms.md
> +for group `+test:example.com` is `#+test:example.com`.
Oop that came out longer than I thought it would.  Also wanted to note that this affects:

KB1RD's comment directly above, as clients wouldn't peek a room unless it was listed as a subgroup, simplifying things slightly

Soru's comment on #+ vs +, since there would be only #

2020-04-18 16:02 UTC, squarepupil commented
> Normal messages within the room could be showed and used as a 'lobby' area for the given group.

I propose that if a room contains rooms, then it should contain no messages. That is, groups should not have lobbies.

I think that having a "lobby" made up of the normal message events establishes the lobby as a privileged room within the group, which I think would be undesirable for many use cases. If a lobby is displayed upon a user opening a group, then its function as an announcements (or other high level purpose like access control, rules, or welcome) room is difficult to avoid. I think a lobby would end up containing user interactions, by virtue of it being front-and-center, that a group might have already designated other rooms or systems for handling. In any event, groups should be able to decide what, if any, room is displayed by default when first "entering" a group. If a group does want a lobby, they could create one themselves.

The concept of a lobby also breaks up the recursive schema of groups being "rooms of rooms" because, hierarchically, the messages in a lobby would sit higher up than the messages of the other rooms within the group. This makes for a half-step within the recursive concept which does not need to exist, in my opinion. As I said before, if a group wishes a particular room to be privileged so as to be viewed on initially entering the group, that could be accomplished by a parameter rather than including a particular privileged set of message events.

This _would_ end up with "group" rooms having no message events, but I think this would make the organizational concept more clear to users: groups are to rooms as rooms are to messages. If the goal is to make the underlying "room of rooms" definition of a group transparent to the user (which I think it should be), then having groups also contain messages interrupts that. It introduces a one-off style of room (the lobby) whose contents cannot be easily moved around like other rooms because then all of the rest of the contents of the group (i.e., all of the other rooms contained within it) would also have to be moved too.

2020-04-19 14:06 UTC, squarepupil commented on proposals/1772-groups-as-rooms.md
> +the given group.
Sorry if this should have been marked as just a "comment". I'm new to collaborating on github and am still trying to fully understand the systems and etiquette.

2020-04-19 14:06 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +for group `+test:example.com` is `#+test:example.com`.
> or b) checking if there's a m.room.groups/m.room.group set

or if this MSC finally gets merged it'll be trivial to detect all kind of special rooms in the future https://github.com/matrix-org/matrix-doc/pull/1840

2020-04-24 19:56 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +the given group.
It is a fair point that it is awkward to control lobbies in groups if messages can be sent to the group. However, I would argue that there is a use case for allowing *events* to groups. Right now, Zoom has a feature that can create breakout rooms. It may be useful to take an existing "normal" chat and add subrooms or subgroups to it since this could allow clients to create such breakout rooms. The same could be said for applications that use Matrix as a DB. However, I would agree that group "lobbies" should be separate, specially marked rooms -- I just think this should be because of the use case for the group and that a limitation should not be built into the protocol. This does create the problem of how to mark "normal" (non-message) groups from other custom event groups, but #1840 could help with this. Power levels could also be updated accordingly on group creation. The main problem I see would be what a client should do if it encounters messages in a group that isn't supposed to have them.

2020-05-20 08:30 UTC, MurzNN commented
Together with this change (and https://github.com/matrix-org/matrix-doc/pull/1769) maybe rename base entity `room` to something more relevant, like `node`?

2020-06-03 09:36 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
As this MSC should be blocked by #1840 unless we want clients to have to have hacky work-arounds / fixes forever, either this MSC should be changed to kind:feature or that MSC to kind:core

2020-06-29 08:42 UTC, joepie91 commented
> Together with this change (and #1769) maybe good time to rename base Matrix entity `room` to something more relevant, like `node`?

I think that's too generic a term, and makes it too difficult to understand how things relate. I think something like `feed` or `timeline` would probably work better, as it is essentially a feed/timeline of events?

2020-06-29 11:23 UTC, lboklin commented
> > Together with this change (and #1769) maybe good time to rename base Matrix entity `room` to something more relevant, like `node`?
> 
> I think that's too generic a term, and makes it too difficult to understand how things relate. I think something like `feed` or `timeline` would probably work better, as it is essentially a feed/timeline of events?

I propose "space". It works with anything I can think of: profile space; space with one or more (sub)space(s); general discussion space; status-update space; safe space for [some group]...

2020-10-06 17:17 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +    as current, then the `m.flair` is decorated as being confirmed.
Which server would be peeked if the peeking server knows nothing about the group & user?

2020-10-06 17:52 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +                "autojoin": true
What if the group and #room2:example.com are on different servers? I'm assuming that the membership of #room2 would be determined by peeking. In that case, which servers would be peeked? Or is it somehow "pushed" to downstream servers?

2020-10-19 20:58 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +## Dependencies
can we also stick this section somewhere?

```
## Unstable prefix

While this proposal is not in a published version of the specification, implementations should 
use `org.matrix.msc1772` to represent the `m` namespace. For example, `m.room.subgroup` 
becomes `org.matrix.msc1772.room.subgroup`. Alternatively, a room version of `org.matrix.msc1772`
can be used to make namespacing easier (though a room version is not necessarily required
for this MSC).
```

2020-10-20 01:23 UTC, cloudrac3r commented
Is this expected to be spec'd and implemented in Element sometime within the next couple of months? I'm planning an unofficial alternative implementation for rooms as groups and I wouldn't like my work to go to waste if 1772 is implemented the very next day

2020-10-20 01:34 UTC, turt2live commented
The idea is to implement this, or some form of it, extremely quickly. If you have thoughts then please leave them on the MSC via threads for review.

2020-10-20 05:30 UTC, Sorunome commented
Wonders if you all are aware of the matrix room discussing groups-as-rooms where a lot of ideas have been tossed around: #groupsasrooms:kb1rd.net

2020-10-20 06:25 UTC, cloudrac3r requested changes
I'm writing from the perspective of a client developer using the C/S API.

In addition to my other review comments, I think there are several features that are missing from this proposal, but would be useful for a community of people who want to use rooms to organise their discussions by topic (e.g. group name "Friend Zone", rooms "chat", "gaming", "art", "comics").

- An option to force synchronise group-room membership. If the client joins the group they must also join all its rooms. If they leave a room or the group they must also leave all its other rooms.
- An option to synchronise moderators, permissions, and bans. If you ban someone from one room of the community you most likely want to ban them from all rooms. If you deny invite permissions for PL0 on one room of the community you might want to deny it for all rooms.
- Static ordering of the rooms list. A community might want to specify their own "natural" order for the rooms to be displayed in, such as rules at the top, then general chat, then more specialised rooms below it. (It's up to the client whether whey want to use that suggested order.)

In summary, while this proposal definitely _improves_ the situation over current groups as outlined in the problems section, I think it still misses out on a lot of useful features, leaving gaps that would have to either later be filled with more MSCs or addressed in a 3rd-party client which adds features like synchronised bans.

Let me know if I made mistakes or missed anything obvious. I'd specifically really like clarification regarding the "expected" UX for subgroups.

2020-10-20 06:25 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +would be needed to distinguish from a deleted state event. Something like:
I like the state key idea better. It feels similar to how member events are sent to the client, with m.room.member and the user ID.

2020-10-20 06:25 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +the given group.
I agree, I think it makes the most sense for group to not be able to contain messages directly.

2020-10-20 06:25 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +useful for normal rooms.
I think hidden membership would be better as a separate feature for any room, and not required for this MSC to go through.

2020-10-20 06:25 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +XXX: how do we stop cycles & recursion abuse of the subgroups?
This is very important to figure out. Even if cycles are out, I suspect a 1000-deep tree of subgroups would still present problems to clients and servers trying to process it.

2020-10-20 06:25 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +defined.
I think subgroups need more thought put into them. From the perspective of a client developer, they seem overengineered and very flawed. I don't know how all the features mentioned here could be implemented in a way that makes sense for people using an IM app.

As I understand it, all these patterns of group joins are possible:

- `#+some_group:server.tld`
- `#+some_group:server.tld` and `#+a_subgroup:server.tld`
- `#+a_subgroup:server.tld`

In other words, a person may be in a subgroup without being in the parent group.

If we keep similar UX to Element's groups bar where all groups are in one display list and can be re-ordered by the user, we have no way to represent the hierarchy of subgroups or allow users to take advantage of that hierarchy.

Subgroups also cannot be displayed as sections within the list (like how favourites, directs, rooms, and low priority) are currently displayed, because this only supports one level of hierarchy. In addition, if just the subgroup is joined, I don't understand how this state could be represented with this design.

Arranging groups into a tree like Discord's categories but with multiple layers still has the above problem of how to represent the inner layers if a subgroup is joined alone.

What's the _expected_ UX that people had in mind while writing this proposal?

2020-10-20 06:30 UTC, Sorunome commented
> An option to force synchronise group-room membership. If the client joins the group they must also join all its rooms. If they leave a room or the group they must also leave all its other rooms.

In sorus opinion this could be on a per-room basis:

1. Having a room be a required room: if you join the group, you *must* also join this room
2. Having a room be exclusive: you can only join this room if you are pat of the group

If all rooms are both required and exclusive you get the described behaviour, but there is practical use for only using them individually. E.g. you might want to make some vent room of a community exclusive, but not required.

You might want to make a room of a group also neither exclusive nor required: E.g. some hacking community having a general help room. Not everyone asking for help cares about all the contents of the group.

2020-10-20 10:50 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +behave as a group - i.e. the rooms which it groups together, and any subgroups
This is defined and discussed at https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r508233777.

2020-10-20 10:52 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## Dependencies
I think a room version is going to complicate this.

2020-10-20 10:54 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +XXX: how do we stop cycles & recursion abuse of the subgroups?
indeed.

2020-10-20 10:56 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +the given group.
This could be fiddly to enforce at the protocol level though. Possibly we could just recommend against sending messages to group-rooms.

2020-10-20 10:58 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +would be needed to distinguish from a deleted state event. Something like:
agreed. for now I'm going to drop the "one big event" proposal from the document.

2020-10-20 11:08 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +it may be overengineered.
I am completely failing to grok these paragraphs. Are they saying that the group server restricts who can join/peek into the grouproom? (True, at least until the grouproom becomes federated to a second server. Is that a problem? Is it "overengineered"?)

Or are they saying that a group server can hide the membership of some users from other users? (Also true, at least as long as the second set of users are peeking rather than formally joining. Again, I'm not clear why this is "overengineered": it's just something that falls out of the architecture.)

Or something else?

2020-10-20 11:10 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +Of these, option 3 feels best?
I'm somewhat inclined to park discussions on flair until we have some of the other pieces in place.

2020-10-20 11:13 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +XXX: is there a use case today for having a group where users are unaware of the
clarified that this is out of scope for now.

2020-10-20 11:16 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## ACLs
> If this were to be added, would it be possible to add members to a room (with synced_membership: true) that are not members of the parent group?

isn't this exactly the opposite of what is requested? or am I misunderstanding?

2020-10-20 11:21 UTC, richvdh commented
Folks, please remember to use comments on the document itself (https://github.com/matrix-org/matrix-doc/pull/1772/files) rather than comments on the PR, to help with threading and tracking which comments have been addressed. I'm going to ignore any comments that have been made on the PR, because it is too hard to follow the discussion, so if you have points that you feel need addressing, please re-make them as comments on the document.

2020-10-20 11:29 UTC, Sorunome reviewed
Re-posting as thread instead.

2020-10-20 11:29 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +
> Folks, please remember to use comments on the document itself (https://github.com/matrix-org/matrix-doc/pull/1772/files) rather than comments on the PR, to help with threading and tracking which comments have been addressed. I'm going to ignore any comments that have been made on the PR, because it is too hard to follow the discussion, so if you have points that you feel need addressing, please re-make them as comments on the document.

Perhaps it'd be best to switch to https://gitlab.matrix.org/ since this issue plops up on *every* MSC with some discussion? Gitlab allows to reply to comments in a thread, github does not.

2020-10-20 11:29 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +This obsoletes [MSC1215](https://github.com/matrix-org/matrix-doc/issues/1215).
> I'm writing from the perspective of a client developer using the C/S API.
> 
> In addition to my other review comments, I think there are several features that are missing from this proposal, but would be useful for a community of people who want to use rooms to organise their discussions by topic (e.g. group name "Friend Zone", rooms "chat", "gaming", "art", "comics").
> 
>     * An option to force synchronise group-room membership. If the client joins the group they must also join all its rooms. If they leave a room or the group they must also leave all its other rooms.
> 
>     * An option to synchronise moderators, permissions, and bans. If you ban someone from one room of the community you most likely want to ban them from all rooms. If you deny invite permissions for PL0 on one room of the community you might want to deny it for all rooms.
> 
>     * Static ordering of the rooms list. A community might want to specify their own "natural" order for the rooms to be displayed in, such as rules at the top, then general chat, then more specialised rooms below it. (It's up to the client whether whey want to use that suggested order.)
> 
> 
> In summary, while this proposal definitely _improves_ the situation over current groups as outlined in the problems section, I think it still misses out on a lot of useful features, leaving gaps that would have to either later be filled with more MSCs or addressed in a 3rd-party client which adds features like synchronised bans.
> 
> Let me know if I made mistakes or missed anything obvious. I'd specifically really like clarification regarding the "expected" UX for subgroups.

 
In sorus opinion this could be on a per-room basis:

1. Having a room be a required room: if you join the group, you _must_ also join this room
2. Having a room be exclusive: you can only join this room if you are pat of the group

If all rooms are both required and exclusive you get the described behaviour, but there is practical use for only using them individually. E.g. you might want to make some vent room of a community exclusive, but not required.

You might want to make a room of a group also neither exclusive nor required: E.g. some hacking community having a general help room. Not everyone asking for help cares about all the contents of the group.

2020-10-20 11:30 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +
currently our gitlab doesn't have open signup. So maybe, but let's not discuss it further here.

2020-10-20 11:33 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +This obsoletes [MSC1215](https://github.com/matrix-org/matrix-doc/issues/1215).
Thanks for copying that for me. Your response, _if implemented,_ would happily address the first bullet point.

2020-10-20 11:36 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    }
I'm somewhat unclear why we need a separate type of event for this. What is the difference between adding a group as a  `m.room.subgroup` and adding a grouproom as an `m.room.group`?

2020-10-20 11:37 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    "type": "m.room.group",
does anybody else feel like this name is misleading? It's a room within a group, not the other way around. Shouldn't it be `m.group.room`? Or conceivably `m.room.group.room`?

2020-10-20 11:43 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +used for rooms as well as groups.
how does this differ from `m.room.topic` ?

2020-10-20 11:49 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## ACLs
also, how is this related to ACLs? is it a request to modify the rules for group membership across subrooms, as defined at https://github.com/matrix-org/matrix-doc/pull/1772/files#diff-cdaa2b5bfe73f40db1903d17b1d242d8caa54d4af81e78e0396a369bcd9a1b90R85-R89?

2020-10-20 11:54 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
starting a thread here for "what do we call this thing". Synapse currently has a thing called "groups", which Element-Web calls "communities". Another name that has been suggested includes "space".  A mix of names is confusing, and a big problem with the term "group" is that people tend to conflate it with a "room".

2020-10-20 19:10 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
It might be worthwhile to make a distinction between membership inheritance and groups themselves, in which case, groups would just be rooms with membership inheritance and a few special state events.

2020-10-20 19:57 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +XXX: how do we stop cycles & recursion abuse of the subgroups?
There are two issues with this: There's a UI issue (how to represent cyclical membership?) and there's a protocol issue (how to prevent/handle cyclical membership?).

On the prevention aspect of things... Matrix is eventually consistent, so it's impossible to ensure that two servers specifying a particular "parent" group actually know if on some other server, the child room is already a parent of the intended parent room. This means that it's impossible to ensure that a room tree has no way to form a cycle *if the room's parent can be changed after creation.* Consider this example: There are rooms A and B, as well as servers 1 and 2. Federation is interrupted between the servers. On server 1, room A is added to room (now group) B. On server 2, room B is added to room (now group) A. Now which room is a subroom of which?

Let's assume that we *don't* consider this an issue. Membership of room A would be determined by taking the union of *user* membership in room A and the membership set of group B (and the same steps for room B), so it doesn't look like there's a need for the server to get stuck in some kind of recursive loop, so long as each room is only traversed once. If a user joins one of the rooms, that's the same as joining both (assuming membership is synced). Now the problem is how to *present* this to the user of a client?

So it looks to me like their are two options: Make it impossible to change a room's parent once created or find a way to present recursive cycles to the user. So which is *less* bad?

2020-10-20 20:00 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +group membership.
What about invite-only subrooms? AFAIK, this would require a change to authorization rules (to allow/reject invites based on the parent room state) and thus a new room version to implement.

2020-10-20 20:02 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +group membership.
Also, what about parent groups with private membership? This would require some way to authenticate via peeking or changes to federation to ensure that membership stays private.

2020-10-20 20:17 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +                "autojoin": true
I'm assuming that `example.com` would be peeked if the peeking server has no knowledge of the group. This effectively centralizes groups again. While this may be OK for groups on well-established servers, it has a few drawbacks:
1. If the server owning the alias goes offline, the group becomes unpeekable and new participants will not see full membership
2. The server owning the alias effectively has full control. They can claim that the room at that alias is different and, using this, control the membership for servers that are not peeking elsewhere.
This effectively bikesheds any P2P groups, private groups, or invite-only subrooms.

2020-10-21 01:31 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
...or alternatively #2773. agreed it needs one or the other to be nice.

2020-10-21 01:38 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
> I think I'd just use the terms parent, child, ancestor and descendant on a spec level and let each client decide how to implement and name groups/communities implemented on top of that.

I think this would cause massive UX fragmentation.  This MSC is intended to represent a hierarchy of groups of users/rooms for defining communities of users.

> It might be worthwhile to make a distinction between membership inheritance and groups themselves, in which case, groups would just be rooms with membership inheritance and a few special state events.

I don't think there's any plan for state inheritance here (which would probably be a nightmare in terms of introducing dependencies between state resolution in different rooms).

> starting a thread here for "what do we call this thing".

It's really confusing when we have a different name for something in the protocol and the recommended UI.  My suggestion would be 'communities' to differentiate from the doomed '/groups' API and the confusion that some people think group === room.  I'm unsure about 'spaces' because that focuses on the rooms element rather than the users element, whereas communities spans both.

Rather than bikeshedding the name here, i suggest I work it through with @nadonomy offline.

2020-10-21 01:41 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +for group `+test:example.com` is `#+test:example.com`.
i could get behind just using a # syntax for them, to avoid the scary factor, and telling people to `/join #mygroup:matrix.org` if they want to participate in a given hierarchy of rooms.

2020-10-21 01:45 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    "type": "m.room.group",
the only reason for `m.room` is for consistency in namespacing it alongside `m.room.message` and other "events which happen in rooms".  however, given #1767 proposes we rename `m.room.message` as `m.message` when we sprout extensible events, then we could do the same trick here and just call this an `m.group`.  I think the `.room` suffix is unnecessary though - what would the `m.group` event be describing if not a room?

2020-10-21 01:47 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    }
i think it was just in case it helped the client lay things out, knowing the difference between leaf & branch children without having to sniff prefixes or look at state events within those rooms.  agreed it looks weird, and very happy to kill with 🔥

2020-10-21 01:50 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +used for rooms as well as groups.
I'm thinking of a Slack-style community/room description - typically a paragraph or two of rich text which gives lots of details about the intended use of the community/room.  Currently they look like this sort of thing for the old /groups API:

<img width="989" alt="Screenshot 2020-10-21 at 02 49 12" src="https://user-images.githubusercontent.com/1294269/96663158-0822bf00-1348-11eb-871f-2bbc8da85b00.png">

An alternative could be to use pinned messages, if we had those (which is nice because you can then have a hierarchy of descriptions set by different levels of admins/mods as the current noticeboard for that community)

2020-10-21 02:01 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +defined.
> I think subgroups need more thought put into them. 

Agreed; this is the weakest bit of the proposal.  For the first cut in Element we're not going to implement them, but the hope is to define them in the MSC to set things headed in the right direction.

> What's the expected UX that people had in mind while writing this proposal?

We haven't finalised the UX for Element yet, but the last iteration we had on this (which is several years old, sadly - we've been wanting to get to this for *ages*) is:

<img width="954" alt="Screenshot 2020-10-21 at 02 54 32" src="https://user-images.githubusercontent.com/1294269/96663572-d3633780-1348-11eb-8c2c-8b20a87f08e7.png">

In other words you'd probably let users pin whatever communities from any hierarchy at the LLP, given it's a way to switch between views of the world.  For instance, I might want to switch from the overall NV group filter to just looking at the NV Management group filter by hitting the right icon in the LLP, despite one being a subgroup of the other.

But this is To Be Determined (cc @nadonomy)

2020-10-21 02:05 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +it may be overengineered.
These paragraphs are/were a critique of the current /groups API implementation, where the server hosting a given group can completely lie about the membership of the group to different inspecting users, and back the group membership with a random dataset which doesn't need to be synchronised with a room.

2020-10-21 02:06 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    as current, then the `m.flair` is decorated as being confirmed.
that's a question for MSC #1769 - iirc it says that `@matthew:matrix.org`'s profile has to exist at `#@matthew:matrix.org` iirc, so you'd go peek matrix.org.

2020-10-21 02:10 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +## ACLs
Somewhere near here we should spell out that to manage group membership effectively, we need to support force-joins so that group admins can force-join users to subgroups.  The initial join to the main group would need to be consensual of course, but we should support letting the user then consent to being unilaterally joined to rooms and subgroups for that group, in the interests of good UX (i.e. autojoining all the right rooms).

2020-10-21 10:14 UTC, Cadair commented on proposals/1772-groups-as-rooms.md
> +## ACLs
You could have synapse auto-join you to a group and the group do the rest :)

2020-10-21 10:21 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +the given group.
> <@Pestdoktor > That would make messagerooms and communityrooms exclusive subsets of rooms.

what would?

2020-10-21 10:39 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +defined.
> Agreed; this is the weakest bit of the proposal. For the first cut in Element we're not going to implement them, but the hope is to define them in the MSC to set things headed in the right direction.

If you need to get groups-as-rooms out by the end of the year, and you're not going to implement subgroups in Element on the first pass, it may be beneficial to write the spec as "subgroups are a thing that exists but they don't have defined behaviour yet" and then follow that up in a future MSC for subgroups? To me, it seems likely to me that the behaviour of subgroups will need to be revised as you plan the implementation details.

I think this should be considered carefully, because hastily writing problematic subgroups into the spec and then needing to change them later would be even worse.

2020-10-21 11:20 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +This obsoletes [MSC1215](https://github.com/matrix-org/matrix-doc/issues/1215).
> A way to do the first two bullet points could be state inheritance, meaning the member and PL/role objects of all parents a user is subscribed to would be merged to a room if it doesn't have one of its own.

and if it does have an own one? Only have the PLs be overrides? How does this fit in with permission roles?

2020-10-21 11:22 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
In discord they are called at API-level `guild` and at UI-level `server` (please not server...but guild is worth considering?)

Slack calls them `team` or `workspace`

2020-10-21 14:44 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +it may be overengineered.
ah, that wasn't clear to me. I'll try to update the text to clarify.

2020-10-22 14:53 UTC, Pestdoktor commented on proposals/1772-groups-as-rooms.md
> +the given group.
referring to
> I suggest that if a room contains rooms, then it should contain no messages.

I.e. I think community/parent rooms should still function as regular rooms

2020-10-22 17:04 UTC, Pestdoktor commented on proposals/1772-groups-as-rooms.md
> +This obsoletes [MSC1215](https://github.com/matrix-org/matrix-doc/issues/1215).
as @ara4n said,
> I don't think there's any plan for state inheritance here (which would probably be a nightmare in terms of introducing dependencies between state resolution in different rooms).

so i'd actually prefer a combination of `recursive` flag and cross-room auth

but for clarification:

> and if it does have an own one?

the idea was that only state types not present in the child get merged to enable both subrooms with and  without shared membership.

another way of thinking about it is that when not finding expected state in a room, you'd walk its tree of known ancestors until you find a branch containing the desired state. (e.g. a branch where the user is joined and their PL is higher than the PL required for sending a message)

> Only have the PLs be overrides?

i think doing this on the entire state could enable building addressable threads on top of this

> How does this fit in with permission roles?

it works the same, 
`state[m.room.power_levels][events][m.room.message] >= state[m.room.power_levels][users][$user]`
just becomes
`|state[m.room.roles][events][m.room.message] ∩ state[m.room.roles][users][$user]| > 0`

actually, in a state-inheritance world those should probably be
`state[m.room.power_levels][events][m.room.message] >= state[m.room.membership][$user][power_level]`
and
`|state[m.room.roles][events][m.room.message] ∩ state[m.room.membership][$user][roles]| > 0`

2020-10-23 00:37 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
> I don't think there's any plan for state inheritance here (which would probably be a nightmare in terms of introducing dependencies between state resolution in different rooms).

Sorry, I was not suggesting that the state resolution algorithm be changed. I was suggesting changing the meaning of the state after it's resolved; i.e, to change the `auth_events` to allow cross-room references and update the auth rules to recognize membership in another room, provided that the current room has some state saying that the "other room" is a parent group. I would also argue that it's best to separate the UI/UX of groups from the protocol idea of membership inheritance if such an idea was implemented, which what I was trying to say.
That seems to be a more fundamental (and more complicated!) protocol change than what the core spec team seems to be gravitating towards, though, so it may not be relevant.

2020-10-27 11:09 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    "type": "m.room.group",
> what would the `m.group` event be describing if not a room?

well, intuitively based on the name, a group. Sure, on reflection, you might realise that it "must" be a room, but you definitely have to stop and think about it, and it will confuse everyone.

On further thought, this should probably be `m.group.child`, which would include both rooms and subgroups-as-rooms

2020-10-27 11:52 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
Current thinking within the team is that we will use `space` to describe this concept (hence, this MSC will be 'spaces-as-rooms` :). )

Reasoning includes:
 * "groups" are easily conflated with "rooms"
 * "community" does not all the usecases we have in mind here (eg: private lists of rooms; teams within a company)
 * "space" is a real-world analogy to a "building" which can contain multiple rooms
 * "space" is also used to refer to an area of business: "I'm in the Nuclear Physics space"
 * "space" is like a "workspace" (thanks Slack!) but not necessarily for work :)

It doesn't *have* to match the terms used in the UI, but we are keen to avoid a situation where the protocol and UI use the same word to use different things, which is massively confusing for everyone.

2020-10-27 12:08 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +This obsoletes [MSC1215](https://github.com/matrix-org/matrix-doc/issues/1215).
making the event auth rules dependent on state from other rooms (ie, cross-room auth) would be *hugely* complicated, as doing so will require rethinking the state resolution algorithm, which is more than hairy enough as it is. We'll need to find ways to deliver the functionality we want in other ways.

2020-10-27 12:55 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +This obsoletes [MSC1215](https://github.com/matrix-org/matrix-doc/issues/1215).
> ` state[m.room.power_levels][events][m.room.message] >= state[m.room.membership][$user][power_level]`

Then you couldn't override someone having less permissions, only more?

2020-10-27 12:56 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +This obsoletes [MSC1215](https://github.com/matrix-org/matrix-doc/issues/1215).
> We'll need to find ways to deliver the functionality we want in other ways.

From a pure information perspective: We want permissions in room 2 depend on room 1. Permissions are in the state. So we want the state of room 2 depend on the state of room 1.

2020-10-27 14:49 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    "state_key": "#room1:example.com",
are we sure we want this to be an alias to the room rather than the ID? Using an alias implies that the rooms within a group can change without updating the state within the group. It also raises the question of what happens when a room is listed twice (via different aliases) with conflicting options.

2020-10-27 16:01 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +the given group.
fine. I'm just going to recommend against sending messages to grouprooms for now.

2020-10-27 16:42 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
wait. Why is #1840 actually needed?

2020-10-27 16:42 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
(or #2773 for that matter)

2020-10-27 17:04 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +to a centralised group server.  However, group data can already be stale as we
why would we want to delegate group lookups through to a centralised group server ?

2020-10-27 17:04 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +fix for bridged rooms in general too, however.
is fixing it for bridged rooms something we are ever likely to fix?

2020-10-27 17:05 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## ACLs
> < @Cadair >  You could have synapse auto-join you to a group and the group do the rest :)

I don't understand what you mean by this.

2020-10-27 17:14 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +[MSC1228](https://github.com/matrix-org/matrix-doc/issues/1228) (removing MXIDs)?
no idea. Surely we're not blocking it on that?

2020-10-27 17:16 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +to a centralised group server.  However, group data can already be stale as we
say you have an LDAP server with millions of users in it, or you have some opaque group server which doesn't let you enumerate group membership but only lets you query it.  You might want to try to keep a single source of truth of the group membership in that centralised group server, rather than mirroring/bridging it into a Matrix room (which in turn may get out of sync between the participating Matrix servers).

2020-10-27 17:26 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +to a centralised group server.  However, group data can already be stale as we
:+1: completely failed to grok that "group server" in this case referred to something outside Matrix.

2020-10-27 17:31 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    "state_key": "#room1:example.com",
so my rationale was that you don't want the group to break when someone upgrades a room. however I agree that it comes with other problems. i'm indifferent; if we switch to using a room ID, we'll need to include via params too (cc @kegsay for a similar problem we were discussing earlier)

2020-10-27 17:35 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +fix for bridged rooms in general too, however.
yes, i think so: reasons we might want to fix it for bridging rooms in general include:
 * joining a massive auditorium room (e.g. a twitter timeline with 10M followers) without wanting to sync or leak who's in the audience
 * speeding up group joins by lazy loading in members on demand (c.f. #2775)

2020-10-27 17:36 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +[MSC1228](https://github.com/matrix-org/matrix-doc/issues/1228) (removing MXIDs)?
we're not (especially as #1228 is evolving over at #2787); just trying to keep it on the periphery of the radar.

2020-10-27 18:12 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    "state_key": "#room1:example.com",
(using room id would raise the problem of "how do I join it", but maybe we could also include "via" servers in the `contents` ?)

2020-10-27 18:19 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    "state_key": "#room1:example.com",
(thanks github for hiding your reply from me...)

2020-10-27 18:20 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +deprecated and removed outright.
made this explicit.

2020-10-27 18:21 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +for group `+test:example.com` is `#+test:example.com`.
I've dropped the proposal for the prefix for now. We'll see how it works out.

2020-10-27 18:22 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +                "autojoin": true
I'm not really following what the question is here.

2020-10-27 18:23 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +defined.
have made subspaces explicitly an area for future extension.

2020-10-27 18:24 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    }
:fire:

2020-10-27 18:26 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +group membership.
we're emphatically not changing the auth rules.

2020-10-27 18:39 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +fix for bridged rooms in general too, however.
> joining a massive auditorium room (e.g. a twitter timeline with 10M followers) without wanting to sync or leak who's in the audience

If the objective is to hide the membership from Matrix users, then we simply don't map the membership onto Matrix state, and instead keep that state internal to the bridging server. That applies to both bridges and Spaces-for-access-control.

> speeding up group joins by lazy loading in members on demand (c.f. #2775)

This is presumably a mitigation to huge membership lists, rather than either a reason that we need to fix it for bridges or a way to avoid having those huge membership lists in the first place.

2020-10-27 18:40 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +[MSC1228](https://github.com/matrix-org/matrix-doc/issues/1228) (removing MXIDs)?
ack. Will remove it from here to avoid confusion.

2020-10-27 18:42 UTC, richvdh commented
I've updated the document to reflect new terminology, to add some clarifications, etc, but I'm still working on it.

2020-10-27 19:27 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +We introduce an `m.space.child` state event type, which defines the rooms
Something that came up when working on UX with @nadonomy today: what if we want some of the children of the space to be secret? for instance, a company might have a company-wide space, and want to nest some teams and their rooms within it that you should only know about on a need-to-know basis.  Can it be sufficient for the space and room to point to its parent, without its parent pointing to the children?

2020-10-27 19:34 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +        "autojoin": true   # TODO: what does this mean?
the idea was to encourage clients to autojoin the child if they join the parent.

in practice, I think we need richer autojoin semantics - a space admin should be able to force a user to join rooms and subspaces, if that user has joined the parent space.

2020-10-28 02:23 UTC, jfrederickson commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
So chat clients have a way to avoid showing all the not-chat rooms, right?

2020-10-29 23:54 UTC, 0hq commented
> I'm writing from the perspective of a client developer using the C/S API.
> 
> In addition to my other review comments, I think there are several features that are missing from this proposal, but would be useful for a community of people who want to use rooms to organise their discussions by topic (e.g. group name "Friend Zone", rooms "chat", "gaming", "art", "comics").
> 
> * An option to force synchronise group-room membership. If the client joins the group they must also join all its rooms. If they leave a room or the group they must also leave all its other rooms.
> * An option to synchronise moderators, permissions, and bans. If you ban someone from one room of the community you most likely want to ban them from all rooms. If you deny invite permissions for PL0 on one room of the community you might want to deny it for all rooms.
> * Static ordering of the rooms list. A community might want to specify their own "natural" order for the rooms to be displayed in, such as rules at the top, then general chat, then more specialised rooms below it. (It's up to the client whether whey want to use that suggested order.)
> 
> In summary, while this proposal definitely _improves_ the situation over current groups as outlined in the problems section, I think it still misses out on a lot of useful features, leaving gaps that would have to either later be filled with more MSCs or addressed in a 3rd-party client which adds features like synchronised bans.
> 
> Let me know if I made mistakes or missed anything obvious. I'd specifically really like clarification regarding the "expected" UX for subgroups.

Absolutely. All of these features are near vital for Matrix.

2020-10-29 23:56 UTC, 0hq commented on proposals/1772-groups-as-rooms.md
> +We introduce an `m.space.child` state event type, which defines the rooms
This is absolutely vital when it comes to modern usage in chat platforms like Slack and Discord where you need these types of channels. If Matrix can bring in these core features, it has potential to migrate many of their users who haven't been able to find a self-hosted or secure alternative.

2020-10-30 00:47 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +        "present": true
Something that @cloudrac3r raised in https://github.com/matrix-org/matrix-doc/pull/1772#pullrequestreview-512353597 which is missing from the proposal is the ability for the space's admin to specify a static ordering of the space's children.   This is definitely desirable from an ergonomics perspective (and for parity with Discord & chums).  Might specifying an `order` param which gives a string used for lexicographic ordering be sufficient?

2020-10-30 00:50 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +XXX: how do we stop cycles & recursion abuse of the subgroups?
There's a third option: don't inherit membership to children, at which point parent/child relationships are just for building a tree view in your room list.  Any cycles (or obnoxiously large depths) can then be detected and eliminated clientside.

2020-10-30 00:54 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +[MSC1840](https://github.com/matrix-org/matrix-doc/pull/1840)). XXX nobody has
I think the concern is that you might want to mark certain rooms as "this type of room is for data, not IM", and this is the way of doing so.  I'm ambivalent on whether users are allowed to talk in space-rooms though, and if they're given names like #space:matrix.org i'd kinda expect to have the option to talk there (unless the admins make it read only, and thus just a container for child rooms/spaces)

2020-10-30 00:55 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +the room list, what happens when the alias gets repointed and we don't know
i guess the client could cache the alias and re-resolve it occasionally?

2020-10-30 00:57 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +XXX We also want to be have "secret" rooms within a heirarchy: do this with
```suggestion
+ XXX We also want to be have "secret" rooms within a hierarchy: do this with
```

2020-10-30 00:59 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +either a "parent" state in the child, or possibly by hashing the room id?
n.b. that if a room is to be secret within multiple spaces, it needs to support multiple parents.  only one of these would be the canonical parent though (the space you get teleported into if you /join or /peek that room)

2020-10-30 01:02 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> + * Push-based:
```suggestion
* Push-based options:
```

2020-10-30 01:04 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +     Problem: Bob may not want to be a member of all such rooms.
I think this is the least magical one, and most familiar one today. If a human wants to enforce permissions on rooms in a space, then they should be in those rooms to enforce them.  They can always use an admin role user if they don't want a human to do so, and said role user could then (e.g.) also be used as an audit bot if needed, etc.  The problem of "omg our admin turned off his server" is then a social one to fix; it's up to the humans to assign enough admins and pass the admin torch around as needed.

2020-10-30 01:05 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +   Problem: What do you do if the admin who sets ip the PL relationship
```suggestion
Problem: What do you do if the admin who sets up the PL relationship
```

2020-10-30 01:09 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +     and members of any child rooms.
I don't think this is specific to child rooms - we could be trying to push changes to any room which is using this space to define an ACL.

2020-10-30 01:18 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +### Automated joins
We should probably have automated kicks too. "ex-staff members should automatically leave all the rooms of that company when they leave the company".  This could be done symmetrically to automated joins - i'd shove "force-join: true" and "force_part: true" on the `m.space.child` in question.

We then warn the user that joining this space will mean they'll get force-join/parted around the place.  Their server would then autoaccept the resulting invites.

2020-10-30 01:20 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +### Automated joins
oh, i now see that "membership restrictions" was trying to cover that. perhaps it should be renamed "Automated parts"?

2020-10-30 01:20 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +        "present": true
I think that's a good way of doing it. If some rooms have `order`, then the client should order them based on the value of the string, and rooms without `order` go to the bottom. If no rooms in the group have `order`, then the client can use any ordering that it deems appropriate.

2020-10-30 01:22 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +XXX seems we need to un-de-scope this.
My hunch is that we can avoid propagating access controls from parents to children or vice versa.  Instead rooms should be set up with whatever explicit access controls they require (leveraging spaces if needed).

2020-10-30 01:23 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +the room list, what happens when the alias gets repointed and we don't know
I think we should use room IDs, it would make so much more sense. A group should contain a specific room, not a pointer to some room at the other end of an alias. Using aliases would also mean that unexpected people could edit which rooms are in a group by repointing their aliases, even when those people don't have permission to change the state on the group room.

2020-10-30 10:56 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +[MSC1840](https://github.com/matrix-org/matrix-doc/pull/1840)). XXX nobody has
> I think the concern is that you might want to mark certain rooms as "this type of room is for data, not IM"

the question is what you (as a client or server) would do with this information.

2020-10-30 11:15 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    "state_key": "#room1:example.com",
resolving this thread in favour of https://github.com/matrix-org/matrix-doc/pull/1772/files#r514648501

2020-10-30 11:16 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +the room list, what happens when the alias gets repointed and we don't know
I'm minded to agree with @cloudrac3r here. Everything is much better defined with room ids, even if we end up having to jump over some hurdles to support room upgrades.

2020-10-30 11:46 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +     and members of any child rooms.
sorry yes, I was using "child rooms" loosely to mean "any room which is somehow subscribing to a space for PL updates" here. Will attempt to clarify.

2020-10-31 15:37 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    ordering of of `order` vales; rooms with no `order` come last. `order`s
```suggestion
    ordering of `order` values; rooms with no `order` come last. `order`s
```

plus we probably need to specify a max length, and how to handle collisions.

2020-10-31 15:38 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    XXX do we need an "order" in this direction too?
nope

2020-10-31 15:39 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    XXX how do we avoid abuse where randoms claim that their room is part of a
one option is to only honour `m.room.parent` if the parent room shares an admin user with this room, which would have permission to set `m.room.parent`.

2020-10-31 15:48 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    XXX do we need an "order" in this direction too?
although i guess it could conceivably include an order param which could be used by the parent to put a hidden child in the 'right' place among its siblings.  this feels like a bit of an edge case though, especially if users can order it manually themselves.

2020-10-31 15:51 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +   of the heirarchy of that space for those in the know.
```suggestion
   of the hierarchy of that space for those in the know.
```

2020-10-31 15:54 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +This structure means that rooms can end up with multiple parents. This implies
I still think we need a way of marking one of the parents as canonical, unfortunately. As @nadonomy pointed out on when talking this through yesterday (Fri Oct 30th), the best practice for most client UX will be to show a room in the context of a single space.  Therefore even if the protocol supports multiple parents (which is definitely desirable for flexibility), we still need to make sure clients which need to tiebreak between the parents are consistent in the one they pick.

2020-11-02 12:03 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +     and performs the necessary copying actions.
So if I've got this right, it would be a mysterious opaque bot accessing the world as a client and it's responsible for synchronising power levels from spaces to rooms? So it would need room admin in all the rooms it controls, so it can set new power levels state?

I think this is a terrible idea: Who can run a bot? Who would maintain the bot's code? What happens if we end up with one public space admin bot that almost everybody uses across the entire matrix network, which makes its way into hundreds of thousands of rooms as a room admin, and then the bot decides it's time to turn evil?

Can you make the homeserver(s) do it instead? This seems like a task that the homeserver(s) should solve rather than requiring clients to correctly implement a very important synchronisation operation and not break the world in the case of a network failure partway through.

2020-11-04 11:09 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "#room1:example.com",
Why not allow both an alias or a room ID for child (parent) identifiers?

In work we are wanting to use spaces for this one new feature, but we have a bot dynamically add and remove short-lived rooms. In our specific usecase room IDs would make more sense, since the room will die before an update is needed anyways.

2020-11-04 11:09 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
Also how will this work with role-based permissions? https://github.com/matrix-org/matrix-doc/pull/2812

2020-11-04 11:09 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +
Either soru missed it, or the changes don't touch exclusive rooms yet, where exclusive is that if you want to be able to join said room you *have* to be in a space.

Exclusive and required make sense separately. A room may be required but not exclusive, and a room may be exclusive but not required. Or a room may be both exclusive and required.

2020-11-09 11:54 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +controls whether membership of the space is required to view the room list,
I'm pretty sure `history_visibitity` is the relevant setting here.

2020-11-09 11:55 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "#room1:example.com",
that sounds unnecessarily complicated.

2020-11-09 12:02 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "#room1:example.com",
Aliases have an extra lookup step, so aliases are more complicated than room IDs.

And, in fact, raw room IDs are *very* necessary: Not every room in a space may have an alias. Heck, so that spaces can replace tags what was one of the ideas, it is a hard requirement that rooms without aliases must be able to be added, too.

2020-11-09 12:02 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "#room1:example.com",
And soru literally described another usecase that plopped up in her work for needing only room IDs for spaces

2020-11-09 12:03 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +contains a `msgtype` and possibly `formatted_body`).
sure

2020-11-09 12:03 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +XXX: do we need force-joins, where users may not leave a room they autojoined?
it's hard to enforce over federation. I am minded to descope for now.

2020-11-09 12:04 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
Don't really follow what this means.

2020-11-09 12:04 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
I don't think we need to resolve that right now.

2020-11-09 12:06 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +     and performs the necessary copying actions.
the "bot" would be part of the homeserver implementation.

2020-11-09 12:06 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
Alice gets PL 50 in the space. Now, there are three sub-rooms, 1, 2 and 3. Due to PL inheritance alice *would* have PL 50 in all of them.

However, Bob, the admin, says an override for alice in sub-room 1 to have PL 99 and in sub-room 2 to have PL 0. As sub-room 3 does not have an override for alice specifically, alice still have PL 50 there.

This simple example shows that we can't just take "highest powerlevel", as else alice would have PL 50 in sub-room 2.

2020-11-09 12:07 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +
> if you want to be able to join said room you have to be in a space.

this is exactly what this section is aiming to discuss.

2020-11-09 12:07 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +XXX: do we need force-joins, where users may not leave a room they autojoined?
We already have somewhat broken communities, wasn't the point of spaces to do them *correctly*? If you scroll up and read the other comments on this MSC or the discussion room, it has been a much-requested feature, showing that there *is* both desire and use for this.

2020-11-09 12:33 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "#room1:example.com",
yes, so let's just use room IDs.

2020-11-09 12:35 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +This structure means that rooms can end up with multiple parents. This implies
I am *still* struggling to grasp the value of listing a "non-canonical" parent.

2020-11-09 12:37 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +XXX: do we need force-joins, where users may not leave a room they autojoined?
I reject the assertion that we need to fix everything at once.

2020-11-09 12:38 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
> Due to PL inheritance alice would have PL 50 in all of them

this seems like a poor assumption. It depends how we choose to represent the mappings?

2020-11-09 12:42 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## ACLs
I'm confused what this thread is asking for, and no clarification has been forthcoming, so marking it resolved.

2020-11-09 12:45 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
Clients will need to be aware of the spacerooms and show the heirarchy appropriately in their room lists anyway. I'm unclear how a room type helps with that.

2020-11-09 12:45 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +                "autojoin": true
I'm confused what this thread is asking for, and no clarification has been forthcoming, so marking it resolved.

2020-11-09 12:48 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## ACLs
This is now available in the form of "default" children.

2020-11-09 12:48 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +We introduce an `m.space.child` state event type, which defines the rooms
secret children are now covered in the proposal.

2020-11-09 12:49 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +        "present": true
`order` is now covered in the proposal.

2020-11-09 12:51 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +### Automated joins
I think this is adequately covered in "Membership restrictions".

2020-11-09 12:54 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "#room1:example.com",
resolving this in favour of the existing thread about room IDs vs room aliases at https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r514648501.

2020-11-09 12:55 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
Is that not what PL inheritence is suppossed to mean? It sounds like this MSC needs some clarification on that, then

2020-11-09 12:56 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +the room list, what happens when the alias gets repointed and we don't know
To add to the discussion, not every room might have an alias that you want to add to the space. For example, if the room is short-lived, or you only want the space as a whole discoverable, or if you want to replace tags with spaces, you gotta add rooms to a space by id, rather than alias.

2020-11-09 13:04 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    XXX how do we avoid abuse where randoms claim that their room is part of a
so something like: only honour the `parent` relationship if there is at least one user who has the required power levels to send both an `m.space.parent` in the child *and* an `m.space.child` in the parent?

I'm worried that will just lead to randoms who want their room to appear as part of a space fiddling the PLs in their room to make it match. (eg, by lowering the PL needed to send an `m.space.parent`, or by granting a high PL to space admins who don't really want it).

2020-11-09 13:07 UTC, cloudrac3r commented on proposals/1772-groups-as-rooms.md
> +    The `order` key is a string which is used to provide a default ordering of
It's a bit weird that `order` here is a string but on user tags is a floating point number. There's nothing _wrong_ with this, it's just weird.

2020-11-09 13:10 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
well, the first paragraph of the section (after "XXX: this section still in progress"...) tries to explain what it's meant to mean. I didn't think that there was any implication that PLs were expected to be the same everywhere, but if you have suggestions for a clearer title, that would be appreciated.

2020-11-09 13:11 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +#### Representing the mapping from spaces to power levels
in fact this is clearly spelt out as a problem in some of the proposed solutions: 

> Problem 2: No scope for nuance, where different rooms have slightly different PLs.

2020-11-09 13:21 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    The `order` key is a string which is used to provide a default ordering of
the use of floats on user tags is generally seen as a bug (cf https://github.com/vector-im/element-web/issues/3280).

2020-11-09 19:30 UTC, Sanqui commented on proposals/1772-groups-as-rooms.md
> +
To somebody unfamiliar with flairs (hi), they may imply endorsement rather than mere membership, which may be problematic for communities that are spaces which anybody to join.  Perhaps there should be a requirement for a certain role/permission in the space to allow wielding its flair.

2020-11-09 20:16 UTC, eras commented on proposals/1772-groups-as-rooms.md
> +
I agree and I see two ways to solve this:
1) Do nothing, no spec change required: Instead of having one space, have multiple, and assign flairs to the spaces that require administrative operation to join. However, this hierarchy may be unclear to users unfamiliar with it.
2) Add support for multiple flairs (multiple avatars?) per room and ability to associate flairs to users (via administrative action)

Seems like there could be more overhead in the second solution (for implementations) while the first solution could have more administrative overhead.

Multiple avatars per room could work with an "additional avatar" list that associates identifiers to images, and then a room-specific way to associate its member to zero, one, or more flairs.

2020-11-10 12:58 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +
I'm not quite clear on the situation you are envisaging (or indeed, if you are both envisaging the same situation). My instinct is that we would use separate spaces for complex situations like this, but if one of you could give an example scenario, that might help confirm if we're on the same page.

2020-11-10 12:59 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +the room list, what happens when the alias gets repointed and we don't know
the proposal now uses room ids everywhere.

2020-11-10 13:00 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +XXX: how do we stop cycles & recursion abuse of the subgroups?
we're not inheriting membership, so basically we're doing what matthew said here.

2020-11-10 13:01 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +[MSC1840](https://github.com/matrix-org/matrix-doc/pull/1840)). XXX nobody has
resolving this thread in favour of https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r434438269

2020-11-10 15:25 UTC, Sanqui commented on proposals/1772-groups-as-rooms.md
> +
I suppose this is more a general consideration for flairs, but I think it's relevant.  I imagine the room avatar for a space would be some sort of logo or identifier for the community.  Seeing such a logo next to a person's name in any chat implies association, if not straight up endorsement.  For a publicly-joinable space, it's a concern if anybody can wield its flair.  Feels to me like this should be typically reserved for moderators.

2020-11-10 19:08 UTC, Half-Shot commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
A high level question: Where does this leave bridges, which currently automatically pool users matching a regex into a group via the registration file. Would the bridges need to start joining their users to a space room, which might end up being massively complex due to including every freenode nick evar into the room?

One idea might be to include a state event by the admin which just says "users matching this regex are part of this space, even thought they may not be joined"

2020-11-11 15:58 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
what is the purpose of that group? for flair?

2020-11-11 17:11 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +
in this situation you'd use different spaces for moderators and regular users.

2020-11-11 17:11 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
yup.

2020-11-11 18:43 UTC, Sanqui commented on proposals/1772-groups-as-rooms.md
> +
1. If I'm the owner of a public space, and find it undesirable for members to wield a flair with the space's avatar, can I disable it?
2. This is minor, but it's not very useful for a flair that says "Community X moderators" to lead to an inaccessible/invite-only space when clicked, as opposed to the public "Community X" space.

2020-11-11 19:51 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +
I think you're confusing "this is one way we might implement this feature in the future" with "we have all the answers and it will definitely be like this".

2020-11-12 18:46 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
Right, yes.

> One idea might be to include a state event by the admin which just says "users matching this regex are part of this space, even thought they may not be joined"

this seems like a nice solution here.

(an alternative might be a way to say "you can peek individual state events, but not peek the whole state")

2020-11-13 08:20 UTC, PureTryOut commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
Do note that it's not just used for the flair. In case of the Telegram and WhatsApp bridge by tulir it's also used to sort the bridged rooms and chats and make them easy to find and filter. By pressing just one button I can now see all my WhatsApp chats, I'd like to keep that feature.

2020-11-14 21:08 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +        "content": {
We seem to have lost the `auto_join` flag, which is pretty important in terms of provisioning new users into a hierarchy of rooms for a space (e.g. a new Element employee getting force-joined to various important rooms)?

2020-11-15 22:01 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +        "content": {
we decided there was no need to distinguish between auto-join and `default`.

2020-11-17 13:44 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +localpart `@:example.com`.
Why make that specific choice ? This is [explicitly disallowed](https://matrix.org/docs/spec/appendices#user-identifiers) at the beginning of the spec:
> The localpart of a user ID is an opaque identifier for that user. It MUST NOT be empty, and MUST contain only the characters `a-z`, `0-9`, `.`, `_`, `=`, `-`, and `/`.

Moreover, some users named like this [seem to have appeared](https://github.com/matrix-org/synapse/issues/3832#issuecomment-728930581), which can spell trouble for spec-compliant implementations.

I can also make the case that this username:
- isn't obvious to a user, even an advanced one inspecting room state if clients decide to hide it
- is terrible to look up, in the spec on on the Internet.

Why not make it something:
* Obvious
* Searchable
* Allowed in the spec

Maybe carve a section of identifiers reserved for future use in the spec, like `@_matrix_*:example.com`, or `mx`. This could then be `@_mx_spaces:example.com`.

2020-11-17 13:57 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +
There are definitely use-cases for flairs without endorsement. I've seen some support rooms rely a bit on it in cases like: "Oh, that user has an f-droid flair, they probably installed it from F-droid".

For a more specific example, the #pinephone:matrix.org room has flairs for:
* +team:postmarketos.org
* +postmarketos:matrix.org

With slightly different logos. The first identifies the core team and is invitation-only, the second identifies the rest of the community and users, and is freely joignable.

Currently, room admins get to pick which flairs are shown next to the username, which is a good solution IMO. Clients could elect to display other flairs in some cases, like hovering over a profile picture.

2020-11-17 15:44 UTC, grinapo commented on proposals/1772-groups-as-rooms.md
> +children.
This would be better called `auto_join`, which also suggest there could be other automatically_happening_on_join events happening. (I am not sure at the moment what these events would be.) 
For example the space may flag various rooms for room state event egalisation, like anyone joining the space getting a specific minimal state in the rooms, like power level or flair; or flag rooms getting space-wide settings like bans.

It would a different approach to make it the reverse direction, eg. the room can set that parent is allowed for state spreading: it depends how a room admin can allow or reject a room to be a member of a space, and how the space admin can do the same. (Right now I would say room admins have power over their rooms and shall enable spaces supervision, rather than the reverse, but I may be wrong.)

For me word "default" rather suggests the "main" room, visually top of the room list, where the "main" discussion of the space takes place, and may or may not be automatically joined; kind of a space lobby.

2020-11-17 16:02 UTC, grinapo commented on proposals/1772-groups-as-rooms.md
> +Things that were considered and dismissed:
I have read the above and dismissed ideas but I am not sure whether the following was in:

The space has an automatically existing user, like @_space_whatever:example.com, which joins all member rooms (unless forbidden). 
The specific room admins may or may not assign an elevated power level to this user. (This may be a part of the room joining the space, or acknowledging it.) (It is advised not to give space_user a level equal to the room creator/highest level user.)

This space_user would act on space defined states, like
- if the space defines a room as user_level_inheriting, then tries to set space userlevel for a user in the room, too.
- if ban_inheriting, .... same. 
And same for whatever event we have.

Space admins who have power to set events in the space room may do that, and space_user would reflect these in rooms it has the power to (and possibly the room member events in the space room define as).

If a room admin disagrees with the space admin s/he kickbans the space user.

This machanism may let all and any events reflected in the member rooms without the need to tell _now_ what these events may be in the future.

2020-11-17 16:44 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +localpart `@:example.com`.
> Maybe carve a section of identifiers reserved for future use in the spec, like @_matrix_*:example.com, or mx. This could then be @_mx_spaces:example.com.

This is probably a good idea to be future proof.

2020-11-18 18:13 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
Is this the power level at the time the event is set or at the time of checking the power level?

2020-11-19 10:21 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
Can we use an immutable type set in `m.room.create` here rather?

The effort in a client to support a space being converted into a conversation room can go from trivial to quite complicated depending on how a client is implemented. For spaces (or any key-value store room type really) in Hydrogen, I would imagine a storage model that doesn't even look at non-state events at all and doesn't allocate fragments, deal with gaps, historical display names ... and just stores key value pairs.
Other parts of a conversation room, like the room summary are stored denormalized, and would require extra effort to build up given it is partially based on information that previously was discarded while the room was still a space.

In short: this is quite annoying for clients that want to store things in a denormalized state (which is not an uncommon strategy to make clients fast).

2020-11-19 10:30 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
I also imagine this could be a source of common bugs, as the scenario for supporting this kind of switch would easily end up untested. If somebody discovers a bug, it might be usable for DDOSing.

2020-11-19 10:55 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
I was thinking of the latter: the PL at the time of checking.

2020-11-19 12:20 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
This would indeed be easiest for clients to implement, and seems sensible :+1:

2020-11-19 12:24 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
For completeness, [a similar discussion](https://github.com/matrix-org/matrix-doc/pull/1840#discussion_r508562513) on #1840, although we might want to resolve the issue here independently of that MSC to unblock things.

2020-11-19 13:03 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +localpart `@:example.com`.
> this is explicitly disallowed at the beginning of the spec:

for what it's worth, I don't see why we should be bound by what the spec currently says in a Matrix Spec *Change* proposal.

As for what we actually call the special user id in question: I think it's a bit of a bikeshed question.

2020-11-19 13:36 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +localpart `@:example.com`.
That's a fair point. But in my opinion, disruptive spec changes should be avoided as much as possible. There is a difference between extending the spec and breaking compatibility. Breaking changes are sometimes necessary, IMO they should be versioned if possible.

If the spec has breaking changes with every MSC, being spec-compliant will be very hard. Not to mention that this MSC will likely be implemented before the spec is released, **making servers implementing it non-compliant with released spec versions**.

That issue might not be breaking synapse or Element. I haven't checked Dendrite or , but at least construct is affected in a bad way. Being spec-compliant, it rejects these events, thus the room state can diverge from synapse. I haven't tried how clients behave with this, but it wouldn't surprise me if they were to break.

In this case, the breaking change easy to avoid, so it should be avoided IMO. This is not bikeshedding.

What's bikeshedding is selecting a spec-compliant user id. I leave that to others, namely the MSC author(s), and merely offered a possible way and a few concerns, but I don't feel strongly about it.

This is not meant as a personal attack, I just pointed out a spec incompatibility, that's what reviews are for :) You are free to ignore it, but I'd like you not to.

2020-11-19 14:56 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
So what about this:
* T: a user had right to add a room to a space, and did it
* T+1: the user's rights are removed
* T+1: the room is removed from the space too?

Maybe the space's admin wanted to reject this user admin rights but not remove the room from the space.

2020-11-20 09:38 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
Hmm, the power level checking does seem a bit error prone ... how about supporting secret rooms by adding a hash of the room id to the space and not faff around with power levels at all? This way you can test for room membership if you just know about the room id though and are not a member.

If that would be a requirement, we could instead set a shared secret in a a state event in both the room and space, with the state event in the room also containing the space id.

2020-11-20 10:07 UTC, jryans commented on proposals/1772-groups-as-rooms.md
> +add an `auto_users` key:
Who or what is responsible for editing `auto_users`? I don't see it mentioned in the rest of this proposal.

2020-11-20 10:17 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +add an `auto_users` key:
That's explained in the "Implementing the mapping" section. A bot (implemented by the HS) looks at spaces and fills `auto_users`.

This could probably be more explicit.

2020-11-20 10:19 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +changes.
Related to [this comment](https://github.com/matrix-org/matrix-doc/pull/1772/files/39af7f32494b849880ddf1cc0bfe5a93313d2ab1#r527584873), it could be specified here that the bot must fill the `auto_users` part of the `m.room.power_levels` event.

2020-11-20 13:16 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +
I'm going to resolve this thread for now, since flair is explicitly out of scope.

2020-11-20 13:18 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
> how about supporting secret rooms by adding a hash of the room id to the space and not faff around with power levels at all?

we considered that. I think @ara4n didn't want to even leak the presence of the secret room.

> If that would be a requirement, 

sorry, if *what* would be a requirement?

2020-11-20 13:22 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +add an `auto_users` key:
have tried to clarify; thanks.

2020-11-20 13:24 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +changes.
done; thanks.

2020-11-20 13:29 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +Things that were considered and dismissed:
we did consider a pseudo-user-per-space, but it felt a bit redundant. What would be the advantage over having a single pseudo-user which can work on all spaces?

Beyond the userid, I'm not clear how your suggestion differs from our existing proposal?

2020-11-23 11:15 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
> sorry, if _what_ would be a requirement?

Not being able to test for space membership without being a member of the room ... but you've already answered that given we don't want to leak the presence of the secret room

2020-11-23 12:18 UTC, grinapo commented on proposals/1772-groups-as-rooms.md
> +Things that were considered and dismissed:
> we did consider a pseudo-user-per-space, but it felt a bit redundant. What would be the advantage over having a single pseudo-user which can work on all spaces?

_Why a "normal" [looking] user?_ 
Handled as a normal user: have to join the room to be there, have to possess levels to do actions, can be kicked or banned. This machanism is already in place and requires no additional spec.

_Why multiple users?_ 
Since a room can be a part of multiple spaces (as far as I understand) there would be no way to allow SpaceX but reject SpaceY in a specific room to make actions when the room is included in both.

> Beyond the userid, I'm not clear how your suggestion differs from our existing proposal?

It was not clear to me how the proposal handles the possible differences (or power split) between space admin(s) and room admin(s).
Also I'd kind of prefer not to create _more_ spec than necessary, and reuse already existing functions. If the proposal just does that then I was mistaken and superfluous.

2020-11-23 12:20 UTC, grinapo commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
Is there a reason behind making spaces visually indistinguishable from rooms? (Both looking hashmark+string.)

2020-11-23 13:36 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
So to summarize:
* we want to support secret rooms, i.e. rooms that declare a space in their state but which are not declared in the space
* we want to check that the user as the right to add a room to a space

But checking the right to add a room is a complex task. The rule is "a m.room.parent" event is OK if the user has the right to send a "m.space.child" event in the specified space. This implies to get the power levels state _at the time_ the "m.room.parent" was sent. If we don't keep this "at the time" constraint, it could behaves in unexpected ways. Doing this check at the client level would add a lot of complexity into clients (and a lot of new ways to misbehave).

I get that this MSC tries to minimize the server work, but I think the only good solution here is to check the rights when the event is sent, and not when a client read it. Which means that the server has to do it. And so the clients can just blindly trust "m.room.parent" events.

As this MSC actually already need some work to be done by the server (the admin bot), adding this check when sending a "m.room.parent" event does seem to be a big issue to me (but I don't develop any HS ^^').

2020-11-23 13:46 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
I if understand the MSC correctly, bridges should:
* create an invite only room, declaring it as a space
* invite the bridge user in it
* declare in the space the room it creates
* and declare in the room the relation to the space

The feature "pressing a button to show only those space's rooms" is a feature that clients would have to implement.

About the flair (which is useful too, mostly to distinguish irc users in portal rooms), I don't know how it works today, and I don't know how it could work with this MSC.

2020-11-23 14:05 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +This structure means that rooms can end up with multiple parents. This implies
isn't the canonical parent just declared with `m.room.parent`?

2020-11-23 14:25 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
Hmm I now see a potential issue with my proposal. Imagine that a user added a room to a space by sending a `m.room.parent` event, the rights are ok. Now this user removed from the space and the fun begins.

If we check rights at the time the event is sent, the room is still in the space. But what if a space admin want to remove the room from the space **and** there is not more space admins which are also admins in the room? (and no mapping does that)

If we just check the rights at the time of reading the event it is ok. The room is removed from the space, which still feels weird but an admin can add it again (a space's admin or a room's admin). Maybe this is the best solution…

2020-11-26 11:06 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +    expanding the wole list, so that servers have a way to check if they are
```suggestion
    expanding the whole list, so that servers have a way to check if they are
```

2020-11-26 11:27 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
So given that the admin bot is operated by the homeserver of the space-room admin which added the room to the space-room, wouldn't that mean massive inconsistency if the admin-ship of the space-room is spread amongst multiple servers and if one of those servers went down then partial/total permissions sync breakage with no proposed recovery?

2020-11-26 11:27 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +separate software to be installed.)
Presuming this means room and not space-room, it should probably account for existing rooms being added to a space-room

2020-11-26 13:34 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
I think the admin bot is operated by the room which created the room, as it is said line 273.

2020-11-26 13:43 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
How would that work given

+ existing rooms can be added to Spaces, those rooms may originate from servers which no longer exist
+ the server which creates the room can still cease to exist and thus that room now being broken

2020-11-26 14:42 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
Good questions, I have no idea :D

No matter where the bot is heberged, it could go down. I think we need a way for room's admin to setup a new one. This is actually just inviting the bot and giving it a power level 100. You could invite the one on your HS (assuming you trust your own HS).

Maybe this whole HS's admin bot should be specified alongside this one.

2020-11-26 18:10 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
Another problem with checking for "PL at the time the event was sent" is that, in a distributed system, we cannot tell what the state in one room was when an event happened in another.

Generally I'm pretty convinced we just want to check the *current* PL in the space is. I agree it might feel a bit odd if a room is removed from a space as a side-effect of a user's PL changing, but I don't think it's that bad, and it's a bit of an edge-case.

2020-11-26 18:14 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
@grinapo: there's a previous thread on this at https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r405933637. If you feel strongly that having rooms and spaces use the same alias format is a bad idea, please could you open a separate thread giving your reasons.

2020-11-26 18:31 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
as @erdnaxeli says, the admin bot is part of the HS of the room creator.

and yes, if that server goes away, we have a problem. The solution probably amounts to having more than one admin bot in the room, which in turn means having good answers to "how do they decide which one should actually do the work". Whether the extra bots get automatically added whenever a user on another server is granted PL100, or requiring an explicit operation as @erdnaxeli suggests, is open to debate.

(I also think, though it's not written here, that the idea was that if the room creator left the room, so would the admin bot, to avoid accumulating rooms on the server where there are no real users.)

2020-11-26 18:32 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +separate software to be installed.)
sorry, what do you mean?

2020-11-26 18:35 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +separate software to be installed.)
If you create a room, assign me admin, then leave/your server dies. I then add that room to a Space. I can't make your server's space-bot manage it for me. The paragraph only states the case for new rooms being put into Spaces, not for existing rooms.

2020-11-26 19:50 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +separate software to be installed.)
note that a room being "in" the space is orthogonal to having access controls based on that space (neither necessarily implies the other).

beyond that: yes, but isn't this the same discussion as https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r530962239?

2020-11-26 20:15 UTC, ashkitten commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
it seems to me that there is no good way to actually synchronize the permissions and room state across multiple rooms, but maybe we should rethink if that's actually necessary. would it work to simply introduce inheritance so that when looking up permissions and power levels it would defer to the parent room (with the ability to override that per child room)?

2020-11-26 22:24 UTC, grinapo commented on proposals/1772-groups-as-rooms.md
> +for group `+test:example.com` is `#+test:example.com`.
Right now it is visually unambiguous whether a string means a #room or a +group or a !room_id or maybe $an_event. In case of simple clients too, where the client both inputs and presents messages as plaintext. Users probably prefer to know what `/join #whatever` will do beforehand instead of figuring out later that they have joined a space instead of a single room. 

I agree that without specific (and optional!) client support it is virtually impossible to tell whether it's a room, or a space, or anything else. (While it's true that this may be moot if #1840 gets standardised.) 
Also I disagree that people don't care whether they get a group, a room or a space, or something else, and that it would confuse them that completely different objects have different looking names (but i's true that I'm a geek so sigils are kind of natural, while it *may* be different for mortals).

2020-11-27 11:43 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
@ashkitten I'm not quite sure what you're suggesting, but it sounds a bit like the dismissed idea at https://github.com/matrix-org/matrix-doc/pull/1772/files#diff-cdaa2b5bfe73f40db1903d17b1d242d8caa54d4af81e78e0396a369bcd9a1b90R304-R312?

2020-11-27 17:08 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> +`m.room.description` should probably be a separate MSC.
There is an MSC for that now (started separately): https://github.com/matrix-org/matrix-doc/pull/2875

2020-11-27 17:08 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> +should be moved to a separate MSC.
I do agree there. I think the general design of this MSC looks pretty good, until you get to power_levels. I would prefer it, if that part could be worked on independently and that one could submit competing proposals, so that the merits of one over the other can be discussed independently.

2020-11-27 17:16 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
One of the biggest issues with current groups is, that they are bound to a specific server. spaces via rooms was supposed to fix that, at least someone may have said that at some point. Binding the power_level manipulation to a single server again, sounds like a step in the wrong direction. When you add multiple bots on multiple servers, you then run into the issue, that you need to do conflict resolution. Which means you are basically implementing state res a level above normal state res. I think it would be much more natural to extend state res to work across multiple rooms instead in a few specific cases. Yes, that is complicated, but it gives you a lot more tools to work with and can be useful for community only join rules as well. Otherwise you don't really need the bot user, you could just as well implement all of this clientside without reserving special IDs (well, for the most part, admins would need to join all rooms).

2020-11-27 17:47 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
> I think it would be much more natural to extend state res to work across multiple rooms instead in a few specific cases. 

natural maybe, but would absolutely annihilate our chances of landing this feature within the next year. Seriously, I'm pretty sure getting state-res working across rooms would be an entire PhD thesis in its own right.

If people want to take on that research, I would be very interested to read the outcome. Meanwhile, I'm not prepared to block Spaces on a feature that would take *months* of research. We need to work with the tools we have available today and that absolutely excludes cross-room state-res/event-auth. This is simply not up for debate.

In any case, this suggestion is off-topic for this comment thread, which is about "where does the bot run", not "how can we completely change the proposal so you don't need a bot".

2020-11-27 17:56 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> +            "@spaceuser1:example.org": 50
While so far this hasn't been an issue, I think with spaces you will run into event size limits here. Just adding a community with 10 000 members to the mapping will add 10 000 userids here. Quoting the spec:

> The complete event MUST NOT be larger than 65535 bytes

So if each user has a 4 char mxid, this will put us over the limit. I think spaces should scale to 100 000 users.

2020-11-27 17:56 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> +spaces, `!mods` takes priority because that is listed first.
This basically implements role based permissions via group membership. This means you will needs separate spaces to define different groups of users instead of being able to define permissions inside the group, by assigning everyone a role/powerlevel. I would prefer it, if I could assign who is admin or not on the space level and inherit that to all children. I don't think I see that listed in alternatives?

2020-11-27 17:56 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> +key which is an ordered list, for example:
Is that event sent in the child room or in the space?

2020-12-02 12:58 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
Element Web's WIP is using `"type": "m.space"` in the `m.room.create` event

2020-12-02 15:25 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +Join rules, invites and 3PID invites work as for a normal room.
`invite_state` sent along with Invites should be amended to include the event containing the type `m.space` to allow clients to discern whether an invite is to a space-room.

2020-12-02 15:26 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +Join rules, invites and 3PID invites work as for a normal room.
potentially other metadata too, like what rooms are in the space maybe.

2020-12-05 13:31 UTC, Biep commented
There are many ways people may want to organise messages and users.  Rooms are currently paramount, but threads and (decent) communities are often asked.
It would be wrong to create ad-hoc implementations for such - we cannot foresee what other use cases may pop up, and it reduplicates work.
There ought to be one single organising unit - why not (generalised) rooms, and interfaces can then use those in various ways.  So if rooms can intersect (in the model - we may want to make this impossible in certain cases in practice for efficiency reasons), we can have rooms within rooms, where the user can decide to see the higher room as a community, or the lower one as a thread.
Crossposting will then automatically be supported: one simply posts in the union of the rooms one wants to address, and no-one will see the message (as unread) more than once.
A user may decide only to read messages in the intersection of two rooms, e.g. Linux and Synapse - and is thus able to carve out a precise area of interest.
And so on.

Implementing partial solutions will only prevent this simple model from ever becoming reality.

2020-12-07 10:20 UTC, deepbluev7 commented
@Biep Could you post that as a line comment, so that others can reply to it?

2020-12-07 11:14 UTC, Biep commented
> @Biep Could you post that as a line comment, so that others can reply to it?

Not quite sure what a "line comment" is, but I'll copy it as a comment to some of the lines of code..

2020-12-07 11:17 UTC, Biep commented on proposals/1772-groups-as-rooms.md
> +Join rules, invites and 3PID invites work as for a normal room.
Copied here in answer to @deepbluev7's request - I hope this is what (s)he meant..

There are many ways people may want to organise messages and users. Rooms are currently paramount, but threads and (decent) communities are often asked.
It would be wrong to create ad-hoc implementations for such - we cannot foresee what other use cases may pop up, and it reduplicates work.
There ought to be one single organising unit - why not (generalised) rooms, and interfaces can then use those in various ways. So if rooms can intersect (in the model - we may want to make this impossible in certain cases in practice for efficiency reasons), we can have rooms within rooms, where the user can decide to see the higher room as a community, or the lower one as a thread.
Crossposting will then automatically be supported: one simply posts in the union of the rooms one wants to address, and no-one will see the message (as unread) more than once.
A user may decide only to read messages in the intersection of two rooms, e.g. Linux and Synapse - and is thus able to carve out a precise area of interest.
And so on.
Spaces would then be pointers to rooms, and adding a room R to a space S would basically mean a new assignment:
S <- S union R.

I am afraid that implementing partial solutions will only prevent this simple model from ever becoming reality.

Since in this model, a union of rooms is a room again, servers can describe to other servers the room they are interested in - the unions of the rooms the users are interested in. This description may be optimised by standard set-theoretic simplification rules (the union of A and A is simply A, and so on), and restrictions may be added to keep transfer of messages within that room feasible. If we see the empty room at the bottom, and the universal room at the top, there may be a horizontal line (corresponding to the current rooms) where rooms must be disjunct (corresponding to the current rooms). This is an executive restriction, not one on the model, and it may be relaxed or changed as efficient algorithms for dealing with lattices are found.

2020-12-07 14:43 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +Join rules, invites and 3PID invites work as for a normal room.
@Biep I'm not really following what you're asking for here, but I think it's unrelated to @t3chguy's point. please can you start a new thread by commenting on a line on https://github.com/matrix-org/matrix-doc/pull/1772/files? If your comment doesn't apply to any particular part of the MSC then you can just comment on the first line.

2020-12-18 14:37 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
Unstable Prefix `org.matrix.msc1772.type` in `m.room.create`'s content

2020-12-18 14:40 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
There are legitimate usecases for a mutable type, though (e.g. un-marking and re-marking a room as DM). The discussion is probably better done at that other MSC, though.

2020-12-26 11:19 UTC, cloudrac3r commented
I was asked to let you know how I think this MSC is going so far.

- It's still full of contradictions, e.g. "a room may have one parent" followed by "a room may have multiple parents".
- It's still full of TODOs and XXX which nobody seems to know how to work out.
- You're apparently going with the really terrible `@:homeserver` bot idea. Why do you need this?! Can't you do it IN the homeserver, with true federation, without exposing this to users, and without bricking the rooms if the original homeserver that created them dies? This whole `@:homeserver` bot thing smells strongly of a repeat of the `/r0/groups` situation where everyone will hate it and in 3 years you'll say "actually this was terrible let's try something else".
- Still trying to rush power levels and mappings and all this through with the main proposal, rather than (for example) having spaces actually exist, see how they are used, interview users, and design things that work how they'd expect.
- Still don't have linked membership, which is one of the main things users actually want from groups.

I'm developing a client and unless these TODOs and homeserver bots and power level mappings are made less terrible then I plan to implement my own, incompatible, namespaced form of groups which would be far less messy.

The core of this proposal, by which I mean groups as rooms, membership to many children, and membership back to a single parent, is sound and is a great idea. The rest of it? It gets more and more ridiculous the further down you go.

I think you should cut back on the features you want to include in this first draft, split them into their own MSCs, and just make this original thing include the core, simple functionality.

*Simplicity can be extended in the future to fit the real demands of users.*

Complexity and a botched proposal caused by ill-thought-out features that people didn't even want will be impossible to undo.

2020-12-26 12:06 UTC, Biep reviewed
> I think you should cut back on the features you want to include in this first draft, split them into their own MSCs, and just make this original thing include the core, simple functionality.

Very true - simple but general.  And a set-theoretic lattice offers precisely that.  Any future extension can be made within that framework, but one can start with a very restricted version, without compromising the simple, general model behind it.
For some reason my own comment about this has been pending for weeks now - no idea why or whether I can do anything about it.  I can't even get a link to it to give here, but at the moment I see it directly underneath this comment.  Must someone approve it first before it gets accepted?

Edit: I write this, and suddenly [my comment](https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r537890272) is accepted, a minute ago.  I wrote it weeks back..

2020-12-27 18:15 UTC, InfiniteWorldSoftware commented
@cloudrac3r Nice comment. I definitely agree with you that rooms should only be able to be part of _one_ space. Joining a room that is part of the space should join the entire space and all associated rooms. I think the focus of this MSC shouldn't be lost, as well as the wants and needs of the users who are interested in it- Discord-like groups. 
>membership to many children, and membership back to a single parent
Exactly. This should not be neglected, else we end up with the current Communities situation- but in spec with a new name.

2020-12-27 18:34 UTC, InfiniteWorldSoftware commented
Why not have PLs be **optionally** set in-space rather than in-room? For example, I create space `!programming:matrix.org` where I am PL100 and a few other users have arbitrary PLs- just like how people set PLs in-room. I create rooms that are members of the space. These rooms then inherit the PLs that I set in the Space.

Of course, this becomes complex when one wants to add existing rooms with existing PLs to a space.

2020-12-27 18:34 UTC, t3chguy commented
>  I definitely agree with you that rooms should only be able to be part of one space.

The ability for multiple spaces to claim a room lets users have personal spaces (collections) for the use of personal organisation. Like a user can have a personal grouping of "French" rooms/spaces they are in, and another personal grouping for "Gaming" and arrange any spaces/rooms they want inside.

> Joining a room that is part of the space should join the entire space and all associated rooms.

This is very restrictive, if a room is part of a 100-room space which I don't care about, I shouldn't be forced to join it.

2020-12-27 18:40 UTC, InfiniteWorldSoftware commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
> So given that the admin bot is operated by the homeserver of the space-room admin which added the room to the space-room, wouldn't that mean massive inconsistency if the admin-ship of the space-room is spread amongst multiple servers and if one of those servers went down then partial/total permissions sync breakage with no proposed recovery?

Probably, unless the bot would exist on all participating servers. The problem then would be: what happens if the bots disagree?

If the bots **don't** exist on all participating homeservers, MSC1772 is really nothing more than a more complex `/r0/groups` in the spec.

2020-12-27 19:07 UTC, SimonBrandner commented
I am a little concerned that implementing on a client in a way that isn't confusing to an average user may be very hard if not impossible. Maybe that is what @InfiniteWorldSoftware is trying to point out. It's just a guess.

I understand that this is mostly a client-side implementation concern, but maybe it should be mentioned here as well.

2020-12-27 20:45 UTC, InfiniteWorldSoftware commented
@SimonBrandner Yeah, you pretty much summed up what I wanted to say here. I think it's worth saying that Discord, for all its faults, does have an excellent implementation of groups and it's a huge turn-off for users switching off of that platform (its infuriating for those of us who try to get our friends off of Discord to have to explain why the current groups solution isn't really that useful, even if you're in a lot of rooms).

2020-12-28 01:37 UTC, TeknikalDomain commented
> The ability for multiple spaces to claim a room lets users have personal spaces (collections) for the use of personal organisation.

Quite frankly, I don't see why this is being lumped in here, that looks like something that could be done perfectly well client-side, or at least not melded into this. Spaces for public-facing groups of rooms, and spaces for private, personal-to-one-user collections for organization purposes, in my opinion, are similar enough *in theory* but definitely not enough *in nature* to warrant mixing the two together. The end result is going to be diminished on both sides. Maybe have "official" spaces for actually relevant rooms, and "unofficial" or "private" spaces for collections? Or, maybe, call them something different altogether, since that means, as I read it, this MSC is a somewhat confusing mess that's trying to take two mostly-dissimmilar use-cases and group them under the same umbrella.

> if a room is part of a 100-room space which I don't care about, I shouldn't be forced to join it.

Valid point. I think the option should be made available, but railroading a user into joining a bunch of rooms (and thus, the resulting homeserver load of syncing said rooms) sounds like something that will very quickly get old quick.
If, as it seems, a good portion of this revolves around "flexibility," then we should offer some flexibility to the users: let *them* decide what they do and don't want to join.

Various other points I'm not going to quote and highlight specifically before my laptop crashes and forgets this all:

- The MSC itself feels rather larged for the proposed goals, I know it's WIP, obviously, and it's discussed in a few places, but I think it would help implementations if it got fragmented into a few individual pieces that can build off each other, if implemented. For example, as discusses above, *power levels.*
- Using the same syntax (`#<name>:<homeserver>`) for spaces and rooms seems like it's bound for confusion, from a user perspective. Just looking at that, am I looking at a space? a room? a space-room? Having a separate character used (like we do currently, with communities) makes it a lot easier for the end-user to know what something is when they see it, before they click.
- To be completely frank, and at the risk of discrediting myself completely, as well as going back to bullet point no. 1, We're trying to do too much here - a lot of ideas, changes, behavior, and overall functionality is proposed, and it feels like, in an attempt to get this in, we're currently sitting a mile wide and an inch deep. Many features talked about, and many features with no real usage, or that many concrete takeaways that can be used to build, for lack of a better term here, something useful.

Just... reading over everything, and, once again, realizing that it's WIP and subject to change, at current rate, is something that at least I myself, would look at, consider implementing, and spend to long planning out the *how* to implement, that it wouldn't get done.

2020-12-28 04:15 UTC, InfiniteWorldSoftware commented
>Spaces for public-facing groups of rooms, and spaces for private, personal-to-one-user collections for organization purposes, in my opinion, are similar enough in theory but definitely not enough in nature to warrant mixing the two together.

This, the whole concept of a "group" or a community is less a concept of "groups with similar topics grouped together" and more a concept of "one community spread across multiple rooms with different topics, joined to each room, with an interface that makes it easier for different topics to be moved into the correct rooms" (The last part is definitely on the client UI side, but it is what most people will be seeing).

Currently, as a user, the "Communities" implementation is really good for "personal groupings" and terrible for what their name implies- communities.

2020-12-28 11:17 UTC, vberger commented
> Quite frankly, I don't see why this is being lumped in here, that looks like something that could be done perfectly well client-side, or at least not melded into this.

To add to this, there is already a mechanism that can be used to group rooms client-side: [room tagging](https://matrix.org/docs/spec/client_server/r0.6.1#room-tagging).

2020-12-28 11:24 UTC, Biep commented
Please let us not create a hundred special features for individual use cases.  Second-guessing what users want is bound to fail in the end.  We should have one, simple but general, organisation scheme, in terms of which any use cases can be expressed, and quickly implemented by a bit of UI sugar.

Finite set theory is extremely well thought out, and covers all.  If we have events, users, and sets (of events, users, and sets), we can express any specific use case.  Rooms are sets of users and events; likewise threads (which would be subsets of rooms).  Spaces would be sets of rooms, as would tags.  Cross-posting would be posting in the intersection of several rooms.  A room catalogue would be a set of rooms, and a space catalogue a set of sets of rooms.  A search result is a set of whatever has been searched for (messages, rooms, spaces, users, ..).  And so on.
(Sets would of course be ordered, and so on - I am trying to sketch the large picture here.)

Once the mechanism works and is reliable, specific UI presentations (spaces, threads, tags, ..) can be offered without having to care about the server side - because the server side work has already been done once for all.

2020-12-29 02:19 UTC, TeknikalDomain commented
> there is already a mechanism that can be used to group rooms client-side: [room tagging](https://matrix.org/docs/spec/client_server/r0.6.1#room-tagging).

Okay, seeing that's part of spec, makes *this* MSC now seem just a little bit more redundant, feature-wise.

2020-12-29 09:12 UTC, erdnaxeli commented
> > there is already a mechanism that can be used to group rooms client-side: [room tagging](https://matrix.org/docs/spec/client_server/r0.6.1#room-tagging).
> 
> Okay, seeing that's part of spec, makes _this_ MSC now seem just a little bit more redundant, feature-wise.

Tag and spaces are not exactly the same, though they overlap a bit. A tag is only a cosmetic thing in the client, for the user that sets it only. A space is a curated list of rooms that can be shared and used by many users. The two features are distincts.

> I definitely agree with you that rooms should only be able to be part of one space. Joining a room that is part of the space should join the entire space and all associated rooms.

I think this idea of "a space represents a community" + "a room is part of only one space" + "joining a space makes you join all the space's rooms" is just taking discord way of working and transposing it into matrix. But matrix isn't discord, and spaces aren't "replicating discord features into matrix", it's more than that.

2020-12-29 09:46 UTC, TeknikalDomain commented
> Tag and spaces are not exactly the same, though they overlap a bit. A tag is only a cosmetic thing in the client, for the user that sets it only. A space is a curated list of rooms that can be shared and used by many users. The two features are distincts.

Yes, but spaces for use as a *personal collection* of rooms (thus, likely, collections that might not get shared) can be done completely with tagging. Meaning less to think about right here. Other definitions and use-cases for spaces, okay fair, but for the one I was specifically referring to, adding that usage to spaces is crowding the functionality a little.

2020-12-29 09:49 UTC, t3chguy commented
> Yes, but spaces for use as a personal collection of rooms (thus, likely, collections that might not get shared) can be done completely with tagging.

No it can't, because Personal Spaces can also be used to organise other (nested) Spaces, not just rooms. And then can also be shared with other people. E.g you maintain a personal list of Gaming related rooms/spaces you think are high-value and share it with your friends "live"

2020-12-29 09:54 UTC, MurzNN commented
>  I definitely agree with you that rooms should only be able to be part of one space. Joining a room that is part of the space should join the entire space and all associated rooms. 

Not all users want to have Discord-like or Slack-like spaces, when simple action like adding interested space to your client (or join to this space) will automatically join you to all rooms in this space. In most cases users needs only several rooms of whole list of rooms in space, and will can join to needed ones manually. 

Solution for Discord-style spaces can be implemented via "Join to all rooms in space" button in Matrix client on Space homepage.

2020-12-29 10:08 UTC, TeknikalDomain commented
> No it can't, because Personal Spaces can also be used to organise other (nested) Spaces, not just rooms. And then can also be shared with other people. E.g you maintain a personal list of Gaming related rooms/spaces you think are high-value and share it with your friends "live"

Okay, let me take a step back a bit. I did say "that might not be shared", implying that organization that's likely happening local to *one* client doesn't need this. If spaces are, as my currently understand of the spec is true, implemented as a special type of room, then client-side tagging a room can therefore organize spaces as well. The only thing that can't be accomplished there is sharing with others, which is in violation of my assumption earlier: that collections you make for yourself aren't shared.

But at that point, it's no longer a group of rooms you're curating for yourself, it's a group that you're curating for yourself *and the benefit of others*, where, yes, *this* spec would fit that bill. Of course, as it seems we already have, there should be *some* level of distinction between "these are some things I'm organizing together" and "these are all rooms linked under one *officially created* space with things like syncronized power levels."

2020-12-29 10:34 UTC, eras commented
The current proposal does not seem to require clients to join rooms in a space, which is great, because e.g. in business context just because you are in the "company space" doesn't mean you want to be in all the company rooms (could be a very large number of rooms).

There is however support for "Default children" which would be joined automatically but an open question about if this should be implemented in the client or in the server. My view is: definitely on the client. This simplifies both the server (no need to consider the "default' flag at all) and indeed even the client (no unexpected "room joins" to handle at inopportune locations in the code; all room joins would be initiated by the client itself).

Now maybe this question actually meant if the client should be merely just invited to such default rooms: for that as well my view would be no, although not so vehement :). I guess there are some cases where it would be desirable, e.g. have a room that really reaches all the users in the community, and as specified the "space room" itself is not suitable for that. But how about bot users, do we want them as well to join such force-joined-rooms? To me it seems the more flexible option is to have the clients choose the behavior.

2020-12-29 10:38 UTC, t3chguy commented
> definitely on the client.

I disagree, this may result in a split where not all users joining a space will end up in the default rooms due to custom clients/whatnot which is likely not what the admins of the space intended.

> no unexpected "room joins" to handle at inopportune locations in the code; all room joins would be initiated by the client itself

Matrix clients must be able to handle this anyway because Matrix supports the use of multiple devices at the same time, so if you join the room from one client, all your other logged in clients must handle it sanely.

> But how about bot users, do we want them as well to join such force-joined-rooms?

There is little reason for bots to be in the space-room if they are not governing the space where they'd want to be in all its rooms anyhow. Github, Wikipedia, Google etc bots would have 0 function in the space-room.

2020-12-29 10:47 UTC, Sorunome commented
To chim into the current discussion: With two rather simple mechanisms all the proposed workflows would work:

1. Exclusive rooms: A room can only be joined if you are part of the space. The room is *exclusive* to the space.
2. Required rooms: A room *must* be joined if you are part of the space. The room is *required*.

If all rooms in a space are both exclusive and required we have discord-style guilds.
There are usecases for rooms in a space being both exclusive and required, just exclusive, just required, or neither.

2020-12-29 10:51 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +    of candidate servers that can be used to join the room. `present: true` key
An interesting idea for a future MSC: Some mechanism to completely delete a state / account data / room account data / whatever

2020-12-29 11:03 UTC, eras commented
> I disagree, this may result in a split where not all users joining a space will end up in the default rooms due to custom clients/whatnot which is likely not what the admins of the space intended.

The proposal says nothing of preventing clients leaving such rooms, so this can already happen.

> Matrix clients must be able to handle this anyway

Good point, though I think it can still enable better user experience to be easier to implement in the client, when the client is in control of the join sequence—which as we know can be slow. E.g. what happens if the join fails? The user is usually not usually actively monitoring the other devices during the join.

> There is little reason for bots to be in the space-room if they are not governing the space where they'd want to be in all its rooms anyhow. Github, Wikipedia, Google etc bots would have 0 function in the space-room.

I expect business use—and why not communities as well—would have a lot of usage for space-wide bots that would be in the space but not in its rooms (unless invited), providing visibility of their existence to other members of the space.

They would use the space for access control: 
- gain appropriate permissions for rooms in the space with the `power_levels` mechanism
- allow only members of the space to use it
- allow invites only to rooms that are children or sub-children of that space

while at the same time advertising "official approved bot" status by being a member of the space.

2020-12-29 16:35 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +    room or space, and the content should contain a `via` key which gives a list
So in the case of a new room being added to a space that list of via's will just be a single server, the one on which the user creating the room is. Is there going to be a mechanism to incrementally update all these `via`s as they could go stale.

2020-12-31 02:18 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
@biep this is an interesting idea (but please in future can you post on new threads rather than adding it to unrelated ones)?  the current threading approach used by cerulean building on MSC #2836 does model threads as rooms - and one could use this MSC to group said threads into a space, given it already supports generalised nested sets of rooms.

The idea of cross-posting by sending the same message somehow into an intersection of rooms feels orthogonal to how you'd actually define the spaces.  It's something that's come up a bunch on #2836, and the current proposal is to add a new MSC for symlinks to define messages which point cross-room to an origin message.  This is because entangling state resolution across unrelated rooms feels like a recipe for disaster (plus we want the ability to maintain separate metadata on the symlinks, given different rooms could have different visibility).  I suggest taking the "threads must be rooms!1!!" discussion to the threading MSC, if you must.

2020-12-31 02:21 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    of candidate servers that can be used to join the room. `present: true` key
please file unrelated stuff like this as separate GH issues rather than adding noise to an already overnoisey MSC...

2020-12-31 02:22 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    room or space, and the content should contain a `via` key which gives a list
this feels like a concrete advantage of using an alias rather than a room_id (as well as then getting room upgrades for free).

2020-12-31 02:30 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
`parents` or `parent`? the example JSON shows us only able to set a single parent on a room now (i assume that the idea is that this is the canonical parent for a space, and backlinks to other spaces which claim to have this space as a child could be maintained elsewhere, which is currently unspecified?)

2020-12-31 02:32 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +This structure means that rooms can end up with multiple parents. This implies
the current example given above implies rooms can only have one `m.room.parent` (and we would track any other "spaces which happen to have this space/room as a child" elsewhere).  So this paragraph is now confusing at best.

2020-12-31 02:34 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +children.
agreed.

2020-12-31 02:49 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
the bot is just used to keep PLs updated based on group memberships (which is a separate feature to the core spaces proposal anyway, and should be split out into a separate MSC - we only wrote it in one place to ensure it was considered when doing the core MSC).  To say that MSC1772 is "just `/groups`" if the PL-management bot sits on a single server is completely wrong (`/groups` doesn't even have PL management).

> When you add multiple bots on multiple servers, you then run into the issue, that you need to do conflict resolution. Which means you are basically implementing state res a level above normal state res.

Yes, if you end up with multiple servers doing PL-management, you need some way of conflict resolution.  However, this could be as simple as a social mechanism: if the admins of a room decide they want `@:matrix.org` rather than `@:example.com` to expand out the PLs, then they could make give the right bot power to do so.  This feels like a perfectly practical pragmatic solution that avoids us being sucked into the complexity of cross-room state res.

2020-12-31 02:53 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +localpart `@:example.com`.
the reason i proposed it as `@:example.com` is *because* it's currently explicitly disallowed as a valid matrix ID - and so we can steal it for the "user which represents a server" without risk of colliding with any other namespaces. Given the user may not even be exposed to clients, I don't think we should get too hung up on it.

2020-12-31 02:56 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +Things that were considered and dismissed:
per-space bots (or puppeting a real admin user for the space) is certainly interesting to just make the problem of "who is tweaking the PLs"? a purely social admin one - especially if you have multiple admins trying to compete for control of the same room, as per grin's example.

2020-12-31 03:04 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +  several thousand people), this membership has to copied entirely into the
```suggestion
  several thousand people), this membership has to be copied entirely into the
```

2020-12-31 03:25 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> +It is proposed that this "admin bot" use the special user ID with empty
>  However, this could be as simple as a social mechanism: if the admins of a room decide they want @:matrix.org rather than @:example.com to expand out the PLs, then they could make give the right bot power to do so. This feels like a perfectly practical pragmatic solution that avoids us being sucked into the complexity of cross-room state res.

I guess that is a good point. In theory, as long as an admin on server B still exists and they have admin capabilities in all rooms, they should be able to change the group bot in all rooms, even if server A goes down. It does have the annoying side-effects of permission managements across rooms being broken until you notice A is down and I'm not really fond of that. At the small server scale servers often go down and there is not really one reliable server you can trust, unless you add one of the bigger ones. Those cases are at least recoverable though, while multiple bots have a few unrecoverable edge cases. For the first iteration that is probably completely fine and if it turns out to be an issue, since it doesn't need a lot of invasive changes to implement, it should be replaceable with a better solution, if someone can come up with one.

2020-12-31 13:17 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +    room or space, and the content should contain a `via` key which gives a list
Agreed but both problems still stand for rooms without aliases, e.g private ones or ones which are created as part of Space creation in EleWeb where you are just asked for Room Names

2021-01-03 14:29 UTC, Biep commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
Thanks.
It is very related, though.
Instead of finding a solution for spaces (and then one for threads, and then one for cross-posting, and then one for tags, and then...) I propose:
- first to describe a good, simple and general model for structuring events and users,
- then to write an implementation for that,
- and finally to write simple front-ends for the various uses (here: spaces).

2021-01-03 18:07 UTC, joepie91 commented on proposals/1772-groups-as-rooms.md
> +# Proposal for groups as rooms (take 2)
Presumably to communicate that the space room is not meant to be used for regular messaging, and a UI with that purpose should not be presented to the user?

The mention of this already seems to be a part of the proposal since an Oct 27 commit (and the MSC1840 type updated accordingly), though, so I think this thread is resolved?

2021-01-04 00:29 UTC, joepie91 requested changes

2021-01-04 00:29 UTC, joepie91 commented on proposals/1772-groups-as-rooms.md
> +### Restricting room membership based on space membership
This also feels like something that should be punted off to a separate MSC? It doesn't seem like a dependency to the core Spaces mechanism.

2021-01-04 00:29 UTC, joepie91 commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
> One idea might be to include a state event by the admin which just says "users matching this regex are part of this space, even thought they may not be joined"

If we take this approach, we should probably be explicit about that variant of regex being the same as that used in AS prefix configuration ("POSIX extended regular expressions").

2021-01-04 13:34 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
each room can claim *a* parent

2021-01-04 13:52 UTC, ara4n commented
Folks, as per https://github.com/matrix-org/matrix-doc/pull/1772#issuecomment-712780558, **please thread your comments by commenting on the appropriate bit of the MSC (or the header if it's relevant to the whole thing)**.  It's a nightmare to untangle them otherwise.  Meanwhile, i'm going to split the access control side of this into a separate MSC (I think that pretty much all the unthreaded feedback above is talking about access controls, other than the "why do you need spaces when you have tags?" confusion), so please reopen discussion there **as threads**, once it's up.

2021-01-04 14:08 UTC, joepie91 commented on proposals/1772-groups-as-rooms.md
> +* To implemplement the mapping, we require any user who is an admin in the
The more I think about it, the more I feel that this - with some improvements - is a much better solution than the current proposal. It makes a lot of sense for powerlevel changes in rooms to be made by the person who *actually* made them in the space, much more sense than an anonymous bot user, IMO. It's also much easier to reason about.

It would also remove the need for spaces-as-roles from a powerlevels perspective (hopefully this can be eliminated for join rules in some way as well!), and make all the hard questions regarding whose homeserver is authorative for the bot user, completely obsolete.

Those authority questions in particular are not ones where I expect anyone to have a *good* answer any time soon, because - as I believe someone else pointed out in another thread - we will effectively just be reinventing a second layer of stateres there. I don't think that is desirable, especially considering the expressed desire to avoid changing the stateres algorithm due to its fragility.

An additional benefit of this approach, is that there is a semantically obvious way to copy over default powerlevel *requirements* too, not just user-powerlevel assignments. This doesn't seem to be part of the PL sync proposal yet, but IMO should be.

In terms of API design, a 'synchronized powerlevel change' can be expressed either as a regular powerlevel change on the space, or as a special operation / event type. I don't yet have a strong preference for either, and would be interested in arguments for/against either.

The situation of "cannot synchronize PLs to rooms that the person does not have access in" is IMO sufficiently handled by simply making it an error condition to apply synced PL changes to a space without having the necessary access in all child rooms, with an optional "then just do it for the rooms where it's possible" flag. This allows for eg. a "you do not have permission to update all rooms, do you want to continue anyway?" UI.

That having been said, once the PLs have been manually synchronized across rooms *once*, by each room's admins, it should from that point on be self-sustaining; any space-wide PL change that allows a new admin to change PLs, will also grant that new admin those permissions for rooms. Therefore, "cannot change in all rooms" should be a rare occurrence.

This also addresses the "what if someone is using it for a personal room collection" usecase, as in those circumstances the user simply won't be able to synchronize PL changes across those rooms *unless* they have the needed PL within those rooms; in which case they can still choose to do so "where possible", following the aforementioned UI.

To address the main objections here:

The problem of Bob not wanting to be a member of all such rooms, is pretty easy to to address: simply make "being a member of a room" not a prerequisite for setting powerlevels in a room *at all*. This requires a new room version, but only requires a change in authorization rules, *not* in the stateres algorithm, which makes it a low-risk change.

Likewise, since powerlevel and other permission changes are *already* gated by powerlevel restrictions anyway, and so would normally not be creatable by someone who doesn't have some sort of prior reputation in a room, permitting permission change events from non-joined users would be a safe change.

I'm thinking specifically of making the following change in the authorization rules, changing:

> If the sender's current membership state is not `join`, reject.

... to:

> If the sender's current membership is `join`, allow. If the sender's current membership is `leave` or `invite`, *and* type is `m.room.power_levels`, allow. Otherwise, reject.

(Further permission change events, like `m.room.history_visibility`, may also be worth rolling into this if synchronizing those is desirable too.)

The problem of Bob generating PLs every time someone comes and goes from the space... is this really a problem? Wouldn't the set of members with any non-default powerlevels at all normally be pretty limited, with those powerlevels being normally assigned? It does not seem necessary to me to specify powerlevels for every user which did not explicitly receive a special one.

The problem of people not being able to mirror a space - is that really true? As far as I can tell, that's precisely what this approach *would* allow for, and with sensible PL propagation semantics.

2021-01-05 03:17 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
can a room self-unsubscribe from a space by clearing its parent or changing it? This would create a situation where a space thinks it has a child but the child says it belongs to something else - does the parent->child link take precedence or do both events have to agree for it to be valid?

2021-01-05 08:20 UTC, erdnaxeli commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
That's not a problem, isn't? As anybody can create a space and puts rooms in it, this situation will happen a lot.

`m.space.child` does not implies `m.room.parent`, and vice versa. The relationship is one way only.

2021-01-07 11:08 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +`m.room.description` should probably be a separate MSC.
There is a separate MSC for this here: https://github.com/matrix-org/matrix-doc/pull/2875

2021-01-07 11:11 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +            "@spaceuser1:example.org": 50
How about leave out `users` (and `auto_users`) from the `m.room.power_level` state event, and then set an `m.room-power_level` with the state key the mxid and the content

```json
{
  "user": 100,
  "auto_user": 50
}
```

That way we make sure that we completely decouple the infinitly-growing object structure and thus truly allow rooms of unlimited sizes

2021-01-07 11:18 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
It is an edge-case that is bound to happen, cause confusion and lead to bad UX :/

Not sure what the best approach here is, either, but this does seem somewhat problematic.

Just to clarify: For personal category-spaces, you could have in the space multiple `m.space.shild` events without each child room having an `m.space.parent`, right?

2021-01-07 11:22 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
> It is an edge-case that is bound to happen, cause confusion and lead to bad UX :/

And probably not even that much an edge-case, but more a normal case. Imagine a larger community where over longer times. Admins are *bound* to cycle in and out, so it is only a matter of time this happens at larger scale and confuses people.

To fix non-secret rooms, it could be updated that of a space also claims the room as a child the parent event is valid either way, and the PL check is only happening if the space is *not* claiming the room as a child.

2021-01-07 11:29 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +spaces, `!mods` takes priority because that is listed first.
Sadly it are only fake role-based permissions, as it still underlyingly maps to PLs.

Perhaps it makes sense to look more closely at #2812 before continuing here much?

2021-01-07 11:36 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +        "allow": [
Again,  we might want to flesh out #2812 more, as, well, "access to a room" is a permission and we are re-implementing role-based permissions here by creating a bunch of empty rooms

2021-01-07 11:44 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +One problem here is that it will lead to users who joined via an invite being
This might actually be desirable. better kick, and if it was a mistake, bob can be re-invited

2021-01-07 11:46 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
What if the parent claimed is not a room of type `m.space`?

2021-01-07 11:50 UTC, deepbluev7 commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
Well, it may be `dev.neko.issue_tracker`. Not sure how it would be handled in that case, just saying that it may be useful with other types of rooms.

2021-01-08 00:00 UTC, MadLittleMods commented on proposals/1772-groups-as-rooms.md
> +  space, without having any particular control in that space (though it is
What does mirroring a space mean?

2021-01-08 02:18 UTC, MadLittleMods commented on proposals/1772-groups-as-rooms.md
> +implementation of `allow`.
This part feels weird to me. `m.room.join_rules` seems like it should govern joins, not existing room membership.

2021-01-08 11:19 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
Can we change it so that multiple parents can be claimed? At work usecases are already plopping up for just that (can elaborate, if wanted). The parent state event could then be anolog to the child state event, where the state key is the room id.

Are there any downsides to this? Why were multiple parents removed?

2021-01-08 11:33 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
The primary use case of parents in the Wireframes was which Space to show when peeking into a Room as its canonical parent which you are likely going to be interested in. E.g for Matrix HQ that'd be "Matrix Space" or whatever, what usecase would require multiple of these and how would a UX look for a Room which claims 100 spaces?

2021-01-08 13:57 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
The usecase that came up is if one room should be a hidden member of multiple spaces. Hidden membership is defined in this MSC by having a parent set, but the space not a child. So, to be a hidden member of multiple spaces you'd have to have multiple parents.

2021-01-08 17:57 UTC, niacdoial commented on proposals/1772-groups-as-rooms.md
> +    }
er... so, basically, you know which rooms were part of a given space, even if they were removed (redacted) from it? (say, the room owner decided to leave, or the room was banned, etc...)
Wouldn’t this cause issues on the privacy side of things?

I know how much rework would be needed to avoid that, sorry.

2021-01-08 18:32 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +    }
Given that the timeline history will contain everything anyhow I'm not sure how that's a concern, plus this is the parent->child side of the relationship which does not require any agreement from the child. Any user can spin up their own personal "collection" Space to organise rooms they are interested in (by creating these state events using room_ids they do not control)

2021-01-09 14:39 UTC, eras commented on proposals/1772-groups-as-rooms.md
> +XXX implement this on the client or server?
In my view leaving it to server to require participants of a space to be on the matching default rooms would open a big can of worms:
- Is this "default" a one-shot deal, only applicable when the user joins the space the first time? All these really questions really hinge on the answer to that question being "no, it's always enforced by the server". (If the answer is "yes", then the argument of "default" enforcement being a desirable property doesn't really hold, because it's not enforced.)
- When has the user joined a space? Before or after joining all default-join rooms? Note that this can sometimes take a considerable time.
- What happens if a join to any of the default room fail? Does the join to the space itself also fail? Does the user then automatically part from the rooms it joined successfully?
- Should user see any messages from any rooms before the join to the space has completed?
- What happens when a new room is set as default in the space?
- What happens when a user is removed from a room that is a default? Is it impossible, or does it automatically imply removal from the space as well? How do permissions to remove from a room/space relate to this? Also banning can happen per-room.

I feel it would be a lot smoother sailing spec- and implementation-wise if "default" was just informative to the user. Then the joining and parting default or non-default rooms would work the same way, except clients would manage the sequence of operations.

2021-01-12 10:31 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +server): user interfaces are not expected to have a way to enter or display
Should clients create rooms with events_default at PL100 or even greater to prevent the timeline being abused to spam clients of users in the space-room in a way which moderation would never catch but still yield a degreaded experience for those users now syncing possibly lots of additional data which their clients won't even render?

2021-01-14 01:28 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +            "@spaceuser1:example.org": 50
ooh, i like that.

2021-01-14 01:40 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +XXX implement this on the client or server?
we're doing it on the client, to let the client steer the process (using batch joins to speed things up if needed) as it sees fit, based on its UI requirements.

2021-01-14 01:45 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +  space, without having any particular control in that space (though it is
i'm unsure. @richvdh?

2021-01-14 01:47 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
True. i'd missed that use case. Fixing...

2021-01-14 02:03 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
done in 91fe7a79

2021-01-14 02:16 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> + 2. Separately, rooms can claim parents via the `m.room.parent` state
> Or is the room type merely used for cosmetic purposes to easily indicate the client on how to render / present that room?

this.

2021-01-14 02:26 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +key which is an ordered list, for example:
child

2021-01-14 10:17 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +  space, without having any particular control in that space (though it is
this thread now migrated to https://github.com/matrix-org/matrix-doc/pull/2962#discussion_r557000730

2021-01-14 10:21 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +            "@spaceuser1:example.org": 50
this thread now migrated to https://github.com/matrix-org/matrix-doc/pull/2962#discussion_r557004325

2021-01-14 10:41 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +            "present": true,
Given that `via` is used to determine removal, do we still need `present`?

2021-01-14 11:12 UTC, Cadair commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
I agree that this is really a long-term footgun for many open source projects adopting matrix, leaders of communities should be able to hand over their communities to people as they need to move on without having to worry about them giving up PL 100 will break the room tree for all the users.

> it could be updated that of a space also claims the room as a child the parent event is valid either way, and the PL check is only happening if the space is not claiming the room as a child

this suggestion seems very sensible to me, it mitigates the worst of the problem, and makes manually fixing it probably a lot easier for many people.

2021-01-14 11:13 UTC, Cadair commented on proposals/1772-groups-as-rooms.md
> +  `@evil_user:example.org`.
Is this still valid in the newly shrunk scope of this MSC or does it belong in #2962?

2021-01-14 11:15 UTC, Cadair commented on proposals/1772-groups-as-rooms.md
> +for a space to try to autojoin its members to more than 100 children (in total).
My main UX concern about this is actually related to the current default push rules behaviour. If you are auto-joined to even 5 of the most active rooms in a space, you are going to get bombarded with pushes until you manually go through and change them all to mentions only.

2021-01-22 16:48 UTC, KB1RD commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
It seems clear that a room needs a type of `m.space` to be recognized by *clients* as a space. But does it need a type to be recognized by servers as a space?

I would advocate for the type being a client-side only thing, since one may want to use spaces for things that should not be presented UI wise as a space. Ex, nested directories, or hidden rooms for protocol data (like Matrix Notepad events) inside a chat room.

2021-01-22 16:54 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
Yes it does for https://github.com/matrix-org/matrix-doc/pull/2946 to function

2021-01-22 19:00 UTC, Sorunome commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
Not if every room is seen as a space and "normal" rooms just happen to have zero children

2021-01-22 21:43 UTC, Biep commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
Precisely - that is part of [my proposal](https://github.com/matrix-org/matrix-doc/pull/1772/files/51aa5e2c40af2c69a58c4a2384dd9c3c75166d8f).  Simplify and generalise by abstracting from this specific usecase.

2021-01-25 14:56 UTC, Kegsay commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
> But does it need a type to be recognized by servers as a space?

No.

> Yes it does for #2946 to function

It doesn't rely on the room type. The room type is inserted in the response but the server will walk all children/parents regardless of what type of room it is. So it doesn't need it in order to function.

> Not if every room is seen as a space and "normal" rooms just happen to have zero children, the server could live without having to type spaces as such at all, making the type a purely cosmetic thing for clients

This is how #2946 treats spaces - it's a space if it has > 0 children.

2021-02-10 18:48 UTC, MayeulC reviewed
Interesting MSC.

Arbitrarily mandating lexicographic ordering in a few places seems like a faux pas to me.

If we're going to assume profiles-as-rooms, I think we can leverage this by using the exact same semantics for both rooms and profiles, when it comes to children, hidden rooms, flairs, etc.

Room flairs could be displayed when linking to a room, for instance, and signal stuff such as: "this is an official room of that community".

------
An interesting use-case for spaces that I haven't seen mentioned (admittedly, this might be out-of-socpe) is the ability to mention a space in a room to highlight its members. Imagine having spaces dedicated to synapse release announcements, or synapse dev team, that one (with sufficient power level) could highlight in a chat.

2021-02-10 18:48 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +    room ID, as determined via a lexicographic utf-8 ordering.
I am concerned this might be rather hard on some server implementations. Room IDs are opaque identifiers, couldn't they be ordered naïvely, by numerically ordering the strings? This would be deterministic as well, while being a lot simpler and cheaper in most languages.

2021-02-10 18:48 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +allow peeking; you have to be joined to see the members.
Couldn't this be harmonized with rooms ?

Profiles-as-rooms could have a parent, the same way rooms do. Likewise, rooms could be in #foo-private.

2021-02-10 18:48 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +   profile rooms of those users. (Ideally there would be an API to support
It could be another use-case for `m.space.parent`. Couldn't rooms have flairs too?

2021-02-10 18:48 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +    `\x20` (space) to `\x7F` (`~`), or consist of more than 50 characters, are
I get why ASCII characters, as those can be used as a substitute for arbitrary-precision integer (well, from 0 to 7.6945e+98 in that case). But then, why ask for lexicographic order instead of plain ASCII-based numerical ordering? Lexicographic ordering opens a few cans of worms. Here, I guess that by "lexical" you mean "alphabetical", and do not specify "ASCII order"? If you do mean "ASCII-ordered", it should be stated plainly.

An alternative is asking for a 64-bit-or-so integer. That ought to be enough for anybody.

I also agree with the other comment that non-conforming events should be rejected.

2021-02-14 12:56 UTC, erkinalp approved these changes

2021-02-17 17:26 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +## Proposal
```suggestion
## Proposal

First and foremost, all references to the communities/groups feature are removed from the spec.
```

There's a few misc mentions of groups in the current spec prose - just want a sentence somewhere in this MSC which makes the implicit removal explicit.

2021-03-02 14:56 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +            "present": true,
```suggestion
```

2021-03-09 09:58 UTC, t3chguy reviewed
Rough `suggested` changes

2021-03-10 11:02 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
I believe this is a lie. Spaces are distinguished by having `"org.matrix.msc1772.type": "org.matrix.msc1772.space"` (presumably, later, `type: space`) in the create event. 

(Aside: I am deeply unconvinced of the wisdom of using unstable identifiers here: it means that any spaces created before MSC1772 is finalised will turn into regular rooms at some point in the future once we drop support for the unstable identifiers)

2021-03-10 14:04 UTC, Biep commented
Well, they *ought* to regular rooms.  The only difference being that they contain rooms - as any room ought to be able to.
Ideally no identifyer would be needed at all - though one could be added for performance reasons, as long as nothing other than speed depends on it being there.
Now that rooms can contain other rooms as elements, all that is still needed is to allow rooms to contain other rooms as subsets - so that things such as threads can be implemented using the same mechanism.





---- Op wo, 10 mrt 2021 12:02:25 +0100 Richard van der Hoff ***@***.***> schreef ----




@richvdh commented on this pull request.


In https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r591361316:

> +This proposal suggests a new approach where spaces are themselves represented
+by rooms, rather than a custom first-class entity.  This requires few server
+changes, other than better support for peeking (see Dependencies below).
+
+The existing `/r0/groups` API would be deprecated in Synapse and remain
+unspecified.
+
+## Proposal
+
+Each space is represented by its own room, known as a "space-room". The rooms
+within the space are determined by state events within the space-room.
+
+Spaces are referred to primarily by their alias, for example
+`#foo:matrix.org`.
+
+Space-rooms are distinguished from regular messaging rooms by the `m.room.type`


I believe this is a lie. Spaces are distinguished by having "org.matrix.msc1772.type": "org.matrix.msc1772.space" (presumably, later, type: space) in the create event.

(Aside: I am deeply unconvinced of the wisdom of using unstable identifiers here: it means that any spaces created before MSC1772 is finalised will turn into regular rooms at some point in the future once we drop support for the unstable identifiers)

—
You are receiving this because you were mentioned.
Reply to this email directly, https://github.com/matrix-org/matrix-doc/pull/1772#pullrequestreview-608584851, or https://github.com/notifications/unsubscribe-auth/AC7CMHKOCWEZ3BZ2UIEZW3DTC5GUDANCNFSM4GNCLVWQ.

2021-03-11 19:10 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "!abcd:example.com",
It seems that both `!foo:bar` and `#foo:bar` are used in this document to describe spaces. I'm a bit confused at whether this was changed at some point or if they mean something different...or something else? If spaces are rooms, I'd expect `#foo:bar`.

2021-03-11 20:01 UTC, erkinalp requested changes
Trust issue wrt flairs

2021-03-11 20:01 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
```suggestion
 * The client and the user's homeserver must check that the user is *actually* a member of the advertised
```

2021-03-11 21:14 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "!abcd:example.com",
both `!` and `#` point to Rooms. `!` is the ID of a Room, it cannot change. `#` is a pointer to a room, it is mutable.
Using a mutable identifier here would allow for the rooms to change on the fly without the client knowing without polling the room directory periodically.

2021-03-12 13:57 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "!abcd:example.com",
Ah, duh! I think it isn't really clear in these examples that things like `abcd` is an ID vs. other bits being aliases, but not sure there's anything to "fix" there.

2021-03-13 18:26 UTC, erkinalp approved these changes

2021-03-13 18:26 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
Make it client-side undefined rather than forbidden.
```suggestion
    `\x20` (space) to `\x7F` (`~`), or consist of more than 50 characters have
    undefined client behaviour.)
```

2021-03-17 13:33 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +fix for bridged rooms in general too, however.
this wording was removed in 4040254001b94e02dee7a405e59d738ba7c0a116 so this thread is resolved

2021-03-17 15:53 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
I'm going to close this thread for now, because I'm trying to reduce the scope of this MSC to bear bones, and to reflect what we're actually doing. Extending spaces to support the bridge usecase is very much a project for the future.

2021-03-17 16:09 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    events unless their sender has a sufficient power-level to send an
> > it could be updated that of a space also claims the room as a child the parent event is valid either way, and the PL check is only happening if the space is not claiming the room as a child
> 
> this suggestion seems very sensible to me, it mitigates the worst of the problem, and makes manually fixing it probably a lot easier for many people.

Agreed. Done in 0bdbec23, and a note about the issue added in 6c9d469d.

I'm going to close this thread now, as I think we're basically agreed that it's as good as it's going to get.

2021-03-17 16:10 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +`m.room.description` should probably be a separate MSC.
thanks; removed this section in 469b64c5 since it's now orthogonal to spaces.

2021-03-17 16:23 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
@joepie wrote:

> Why should it be ignored, rather than the entry being rejected as 'invalid'?
> ...
> IMO it's much preferable to catch broken entries early by expecting clients to reject them,

The intention of this wording was to get as close as I could to preventing people going outside the spec. I'm not really following what you're suggesting here though: that the client completely ignore `m.room.child` events with an invalid `order`? I'm not sure that does much to prevent people inventing stuff for custom behaviour on custom clients?

2021-03-17 16:23 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +`m.room.description` should probably be a separate MSC.
indeed, removed in 469b64c5cdfa212c548b3594402cb4ea42744417

2021-03-17 16:24 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +  `@evil_user:example.org`.
I don't think so. Moved to #2962.

2021-03-17 16:25 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +for a space to try to autojoin its members to more than 100 children (in total).
we've deliberately descoped auto-join rooms for the initial MSC.

2021-03-17 16:26 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
I've tried to make it clear that this is just a display hint in 1cfe6bc0a.

2021-03-17 16:33 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    room ID, as determined via a lexicographic utf-8 ordering.
@MayeulC wrote:

> Room IDs are opaque identifiers, couldn't they be ordered naïvely, by numerically ordering the strings?

errrm, room IDs aren't numeric, and attempting to cast them to numbers so that you can sort them doesn't sound like a good algorithm.

I think there might be a misunderstanding here. Lexicographic ordering should be trivial for anything to implement: to be clear, it's just an extension of alphabetic sorting to utf-8. Can you explain why you feel that will be hard, and what exactly you are proposing instead?

2021-03-17 16:34 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +allow peeking; you have to be joined to see the members.
I'm afraid I don't understand this proposal.

2021-03-17 16:39 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +   profile rooms of those users. (Ideally there would be an API to support
@MayeulC wrote:

> It could be another use-case for `m.space.parent`. Couldn't rooms have flairs too?

Again I'm not really following the suggestion here. Are you proposing that we should have separate images for flair and avatar?

2021-03-17 17:11 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    room ID, as determined via a lexicographic utf-8 ordering.
ohhh I now see your comment below: it looks like you understand "lexicographic ordering" to mean "alphabetic sort, ignoring case". Which is not at all what we mean; but it seems this could do with clarifying.

"ASCII-ordered" is not strictly correct here, because room ID can include non-ASCII characters. (They shouldn't, but they currently can, and that's a separate topic).

How about:

```suggestion
    room ID, as determined via lexicographic ordering of the utf-8 code points in the room ID.
```

To us, "Lexicographic ordering" is the clearest way of describing the intended algorithm. [It's also worth noting that a byte-by-byte sort of (valid) UTF-8-encoded strings gives the same ordering as decoding those strings to (say) UTF-32 and then sorting code-point-by-code-point.]

2021-03-17 17:40 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    `\x20` (space) to `\x7F` (`~`), or consist of more than 50 characters, are
see [thread above](https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r596223581) about what "lexicographic ordering" means, and whether there is a better way to phrase this.

> An alternative is asking for a 64-bit-or-so integer. That ought to be enough for anybody.

our experience with [m.tag](https://spec.matrix.org/unstable/client-server-api/#mtag) was that you ran out of precision very quickly, and had to renumber everything (see https://github.com/vector-im/element-web/issues/3280). `m.tag` uses a float rather than an int, but the same argument would apply.

2021-03-17 17:41 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +            "present": true,
done 8a61ce9032dedc3bec881e97a14fcf98376c390c

2021-03-17 17:50 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +Space-rooms are distinguished from regular messaging rooms by the `m.room.type`
I'm still unconvinced of the wisdom of unstable identifiers, but the intention is that we will merge this MSC and switch to stable identifiers before moving this feature out of labs, and everybody will have to recreate any spaces they've made up to that point.

I've updated the text here in 1cfe6bc0.

2021-03-17 17:54 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
flair is pretty hypothetical currently, so this is moot, but: why dos the homeserver care?

2021-03-17 17:54 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
why?

2021-03-17 18:00 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
@ara4n why do you think this needs to be deterministic, and why does it need to be specified here?

2021-03-17 18:22 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +## Proposal
I thought the intention was that this replaces the groups system though? I don't think this would be a controversial hurdle...

2021-03-17 18:32 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## Proposal
well, I think as a first step, if we're talking about removing things from the spec, we need to be clear about what we're removing.

This MSC has already exceeded 400 comments, so my real goal is to keep a laser focus on what I *have* to have here, and punt everything out to a separate MSC. I was mostly hoping to avoid having any more bikesheds on this MSC than absolutely necessary... and yet here we are having a metabikeshed :/

2021-03-17 18:41 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +## Proposal
I'll split it out to its own MSC, but I would like to use the soapbox to say this feels like the wrong process.

2021-03-17 18:58 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +## Proposal
thanks.

2021-03-17 19:29 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
Because, otherwise you would end in Matrix equivalent of SFINAE.

2021-03-17 19:32 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
Some languages just require longer words in everyday speech, polysynthetic languages are even more so, and it is known that French, one of the most commonly spoken languages on Earth, is going polysynthetic.

2021-03-17 19:56 UTC, bwindels commented on proposals/1772-groups-as-rooms.md
> +`type: m.space` property in the `m.room.create` event. This allows clients to
perhaps clarify that this type field is in the event content, as it's obviously not the event type here.

2021-03-18 09:10 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
@erkinalp wrote:

> Some languages just require longer words in everyday speech

this is the `order` field. It is not intended to carry human-meaningful words. It's just an opaque sequence of characters.

2021-03-18 09:10 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
@erkinalp wrote:

> Because, otherwise you would end up in Matrix equivalent of SFINAE.

please can you expand on this? what do you mean?

2021-03-18 09:20 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
The proposal is clear that it is a sorting key. Why should I not use a human-readable sorting key?

2021-03-18 09:26 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
People will rely on the specific way that cycles are broken by servers.

My proposal for resolving cycles as follows: Place room creates and room parent/child settings in a list, and attempt to liinearise them as if they were regular message events in a single room. Parenting order will then be determined by the most-before-happened parent/child pointers for every room in that linearisation.

2021-03-18 10:39 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +`type: m.space` property in the `m.room.create` event. This allows clients to
@bwindels: you mean something like:

```suggestion
`type: m.space` property in the content of the `m.room.create` event. This allows clients to
```

?

2021-03-18 10:46 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
> Why should I not use a human-readable sorting key?

Because that's not its intended usage. I can't stop you abusing it by trying to stick words in, but I don't see why I should expand the character set to allow you to do so.

In any case, as @joepie91 points out in [another thread](https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r551045838), undefined behaviour is a recipe for people start doing non-standard behaviour in their clients, which introduces incompatibilities. The tech community has learnt many times over that unspecified behaviour leads to disasters later. I'm strongly opposed to leaving this undefined.

2021-03-18 10:56 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
> People will rely on the specific way that cycles are broken by servers.

There are no server-side changes proposed in this MSC, so I'm afraid I don't see how this is relevant here at all.

2021-03-18 10:58 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
To actually prevent advertising flairs that user does not possess.

2021-03-18 11:03 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
you're suggesting that the server be responsible for filtering any `m.flair` events in a user's profile, at the time that profile is served to clients? I think that could be problematic, because even if the user was in the space at the time that the profile was served to a client, they might have since left, and it would be difficult for servers to track that information and then send it on to clients.

In any case, it seems pointless that *both* servers and clients should do this check.

2021-03-18 11:05 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
> undefined behaviour is a recipe for people start doing non-standard behaviour in their clients, which introduces incompatibilities

Despite it is worded as undefined, there are very few sensible things you can do in this particular case: reject the long sorting key altogether, ignore the long sorting key, drop the long sorting key from listing and truncate the sorting key from either end.

2021-03-18 11:20 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
> it seems pointless that both servers and clients should do this check

That is deliberate, to prevent clients from trusting the servers beyond that is required by the security model, and servers from trusting the clients in any manner.

2021-03-18 11:27 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
if clients need to do the check anyway, what is the value of servers doing it too?

2021-03-18 12:10 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
Thanks for the suggestion, but I'm afraid you haven't convinced me that I should change this. I'm going to close this thread unless you have anything further to add.

2021-03-18 12:18 UTC, Biep commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
Theoretically one could use the hash of the key too - that would free the length at the expense of another layer of complexity.  If there are potential future use cases of long strings, it might just be worth it.

2021-03-18 12:18 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
One more use case: using it as a visual child room name that is different from room name.

2021-03-18 12:23 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
> Theoretically one could use the hash of the key too 

how? suppose a client wanted to insert a room between A and B. If A has `order: a`, and B has `order: b`, then the client would have to invent a value `c'` which lies between `hash(a)`  and `hash(b)`, and then *reverse the hash*. I think you've completely misunderstood how this field is intended to be used.

2021-03-18 12:24 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
> One more use case: using the sorting key it as a visual child room name that is different from room name.

If we wanted to do that, we would use a different property. The `order` property is intended to allow *manual* ordering of children.

2021-03-18 16:52 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
the original thread got hijacked, so once again:

@ara4n why do you think this needs to be deterministic, and why does it need to be specified here?

2021-03-18 16:56 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
If it isn't deterministic & specced then different clients will cut differently and thus show different "top level" spaces

E.g in an `A -> B -> A` space hierarchy, client A might show `A -> B`, the other `B -> A` and this would on the surface look very broken

2021-03-18 17:02 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
> E.g in an A -> B -> A space hierarchy, client A might show A -> B, the other B -> A and this would on the surface look very broken

right, yes. I don't think that the solution in MSC2946 (which is simply to stop walking once you find a repeat) is going to help here, because it all depends where you start from.

2021-03-18 17:04 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
The alternative seems to be to specify a way that clients can agree which is the rootmost space in a loop. For example, you might say "the lexicographical lowest room id in the loop is the root". But then you still encounter effects which look very broken when a space that was the root suddenly becomes several levels down the hierarchy because someone introduced a cycle.

2021-03-18 17:06 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
> the lexicographical lowest room id in the loop is the root

Yup, that is what was proposed internally at one point (and is what I implemented in EleWeb iirc)

2021-03-19 08:34 UTC, Biep commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
> I think you've completely misunderstood how this field is intended to be used.

You are completely right - I wrote that in a muddled mood.

2021-03-22 09:50 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +    room ID, as determined via a lexicographic utf-8 ordering.
That sounds pretty good to me, thank you :)

**How about `s/lexicographic/numeric/`** in your suggested change?

Is valid utf-8 enforced? If not, I would suggest simply numerically ordering byte-by-byte (which is what I meant above with "numerically ordering the strings", sorry about the confusion).

Again, sorry to nitpick here, but I feel the spec should be unambiguous and not require arbitrarily difficult things without real need for them.

----
I just find the word "lexicographic" to be ambiguous, even though it sounds obvious to us ([classical XKCD 1425](https://xkcd.com/1425/)).
As one possible example of what could go wrong with "lexicographic ordering", what if I have `é` in the room name? Should it be normalized first (as it can be stored as either `U+00E9` or with a combining accent mark `U+0065 U+0301`). Should two strings (normalized an not) be treated the same? Harmonization rules sometimes vary from library to library, and become outdated with newer unicode standards.

2021-03-22 10:00 UTC, MayeulC commented on proposals/1772-groups-as-rooms.md
> +    `\x20` (space) to `\x7F` (`~`), or consist of more than 50 characters, are
Thanks for the clarification. As for "phrasing" lexicographic ordering, I guess we'll copy what we agree on for the previous review. "true" lexicographic ordering is less complex for such a reduced set of characters, but you have to decide whether `space` is sorted after or before `0`, which is probably locale-dependant (`LC_COLLATE`). It's just that "lexicographic" doesn't mean the same to you and me. To me, it just sounds really complex to agree on the same ordering in multiple implementations :)

2021-03-22 17:13 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    room ID, as determined via a lexicographic utf-8 ordering.
> How about s/lexicographic/numeric/ in your suggested change?

I think this would be more confusing, as it implies that you're going to try to convert the whole thing to a single number and then compare.

2021-03-22 17:22 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    room ID, as determined via a lexicographic utf-8 ordering.
I've tweaked the wording, but I don't think it's worth getting hung up on this any further from the point of the MSC. Everyone else I've spoken to is pretty clear about what lexicographic ordering means, which means this is good enough for us to reach agreement for an MSC. We might choose to add more clarification when it lands in the main spec, which needs to be accessible to a wider audience.

2021-03-22 18:15 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
The client check for the correctness at the time of writing to it, the server to check again for TTWTTR issues, and the server check at the time of reading and removing the disallowed values to enforce the flair-membership constraint.

2021-03-22 18:21 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
> TTWTTR

please could you stop using meaningless acronyms? I'm getting tired of second-guessing what you mean.

2021-03-22 18:33 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
It was meant as "time of write to time of read", i.e. TOCTOU.

2021-03-22 18:37 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
> TOCTTOU

nope, no idea about that one either.

Have you read https://github.com/matrix-org/matrix-doc/pull/2801 by the way? I think it conflicts with what you are trying to suggest here.

2021-03-22 18:52 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
TOCTTU: time of check to time of use
The server may also make use of flair data (external integration management by plug-ins etc.), therefore it should ensure it is well formed. Not all data require such guarantees hence we can list those that do (the list would be short). All other data is going to remain untrusted.

2021-03-23 11:29 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> + * The client must check that the user is *actually* a member of the advertised
ok, I think it's reasonably obvious that if the server ends up making use of flair data directly, it needs to verify that data.

I think we're done on this thread.

2021-03-24 21:19 UTC, gfodor commented
Apologies if this isn't the place for this, but one thing that I didn't see in this proposal is how to create space-level notification settings. (Similar to those found in chat clients such as slack and discord.) For example, I'd like to be able to turn on notifications for all chat messages for all room in a specific space but not rooms I've joined in other spaces. As far as I can tell there is no obvious way to do this without having to do a ton of client-driven bookkeeping.

The most obvious place for this to go would be to the introduce a new `space` rule kind for push rules, where the room id specifies a space room and the rule matches all rooms in that space. This would, however, require the server to become aware of which rooms belong to that space, and additionally would need to deal with the semantics of 'unpublished' rooms in a space which only have a parent reference. (And probably other issues.)

2021-03-25 10:42 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +allow peeking; you have to be joined to see the members.
@MayeulC I'm going to resolve this thread. If you'd like to clarify your suggestion, we can reopen it.

2021-03-25 10:42 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +   profile rooms of those users. (Ideally there would be an API to support
@MayeulC again, closing pending further clarification.

2021-03-25 10:52 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
@gfodor [writes](https://github.com/matrix-org/matrix-doc/pull/1772#issuecomment-806193425)

> one thing that I didn't see in this proposal is how to create space-level notification settings

(please use a comment on the document in future so that we can maintain a conversation thread rather than it being lost among all the other comments on the PR.)

That's true, although notifications (and push rules as a whole) are well overdue a makeover. I'm loath to complicate this proposal by trying to figure out how we would wedge support into push rules. [MSC2785](https://github.com/matrix-org/matrix-doc/pull/2785) is a proposal for how the notifications system could be revamped, and I think it would be better to consider integrating notifications and spaces when that work gets done.

2021-03-25 11:21 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    forbidden and should be ignored if received.)
@joepie91 I'm closing this thread for now; if you want to clarify your proposal, we can reopen.

2021-03-25 12:33 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +allow invalid users to join.<sup id="a3">[3](#f3)</sup>
I was struggling to remember why we decided it was better to start with `join_rule: public` and lock it down, rather than `join_rule: invite` and open it up.

I think the answer amounts to: from the perspective of the [auth rules](https://matrix.org/docs/spec/rooms/v1#authorization-rules), the expected behaviour is the same as that of `join_rule: public`, because the `allow` restrictions cannot be enforced post-hoc.

So, from the auth rules' point of view, `public` makes more sense. From the C-S API's point of view, `invite` makes more sense. I'm a bit worried that this is going to be very confusing for everybody.

I wonder if, for clarity as much as anything else, we should introduce a different `join_rule` - say, `restricted` - to reflect the fact that what we have is a cross between `invite` and `public`? in this world:
 * `public`: anyone can join, subject to `ban` and `server_acls`, as today
 * `invite`: only people with membership `invite` can join, as today
 * `restricted`: the same as `public` from the perspective of the auth rules, but with the additional caveat that servers are expected to check the `allow` rules before generating a `join` event (whether for a local or a remote user).

Since we're talking about needing a new room version for this anyway, it seems like a reasonable thing to do?

2021-03-25 12:35 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +allow invalid users to join.<sup id="a3">[3](#f3)</sup>
oops, wrong MSC

2021-03-25 15:09 UTC, gfodor commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
ah thank you for the reference! for now, I've updated my system to inject a `spaceroom_id` into the message event content payload for now to be able to condition on it.

2021-03-26 13:12 UTC, joepie91 commented on proposals/1772-groups-as-rooms.md
> +# Proposal for Matrix "spaces" (formerly known as "groups as rooms (take 2)")
I agree that notifications should be considered separately; I don't see any obvious way in which the current design would get in the way of the notifications design later, so IMO it is not a blocker for this MSC.

2021-03-31 10:13 UTC, Cadair commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "!abcd:example.com",
It's worth noting here that once a room id is added to a space in the state key it can't ever be removed again. While this is a very minimal metadata leak (only really showing the existence of a room with that id) is it worth considering some method of obfuscating the ids in the state key? So that the actual room id could be redacted with the content?

2021-04-06 17:07 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
Does this make sense to include in here then or does it make sense to leave this up to implementations?

2021-04-07 09:41 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
I think it probably does make sense to make a recommendation here, yes.

2021-04-07 10:20 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "!abcd:example.com",
yeah, one solution here would be to make the `state_key` a hash of the room id, and embed the unhashed room id in the body of the event - so that the event could be redacted leaving only the hashed id behind.

For me, that feels a bit overengineered given the scope of the information leak (room IDs aren't really that sensitive). It's maybe something we could come back to in future.

2021-04-07 10:40 UTC, ShadowJonathan commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "!abcd:example.com",
Maybe a future MSC could define a "paranoid" setting which'd enable this, either by default or optionally, to indeed make statekeys hashed?

2021-04-29 16:32 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +        "state_key": "!abcd:example.com",
totally agreed that this would make an excellent future MSC.

2021-04-29 16:48 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
We talked about this in depth and came up with the following:

* Clients are cautioned about loops and should avoid infinitely recursing the tree.
* If a client does hit a loop and isn't sure which of the nodes should be the root, it picks the node with the oldest `m.room.create` event (and tiebreaking on random because that's not entirely realistic as a scenario)

2021-04-29 17:15 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
> and tiebreaking on random

Why not tiebreak on the smallest room ID?

2021-04-29 17:16 UTC, erkinalp commented on proposals/1772-groups-as-rooms.md
> +I think kegan found a solution for this when implementing MSC2946 in Dendrite.
> if a client does hit a loop and isn't sure which of the nodes should be the root, it picks the node with the oldest m.room.create event (and tiebreaking on random because that's not entirely realistic as a scenario)

Then tiebreak on the smallest room ID.

2021-04-29 19:52 UTC, t3chguy commented on proposals/1772-groups-as-rooms.md
> +    rooms with no `order` come last. `order`s which are not strings, or do not
How do we order those which come last?
Surely clients must agree so that order is deterministic & consistent between clients

2021-04-29 19:57 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    rooms with no `order` come last. `order`s which are not strings, or do not
let's do it based on age, and failing that tiebreak on room_id.

2021-04-29 20:10 UTC, ara4n commented
I believe this is at last ready for final review by @matrix-org/spec-core-team.  Huge thanks to everyone who's helped review and iterate on it and get it to the final stage, and especially @richvdh and @clokep for shepherding it.

@mscbot fcp merge

2021-04-29 20:23 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +changes, other than better support for peeking (see Dependencies below).
E_NEEDS_UPDATE (section missing, not a dependency anymore, etc)

2021-04-29 20:40 UTC, turt2live approved these changes
overall looks great, just a few nitpicks for when we get to the spec PR side of things :)

2021-04-29 20:40 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +`type: m.space` property in the content of the `m.room.create` event. This allows clients to
spec PR note: Standardized identifier grammar

2021-04-29 20:40 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +way as a normal room.
presumably avatars too

2021-04-29 20:40 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +invite is to a space-room or not.
should we turn this into a general recommendation for all invites, particularly with the likely proliferation of types in future MSCs?

2021-04-29 20:40 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +    Children where `via` is not present are ignored.
what if via is invalid? (not an array)

2021-04-29 20:40 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +    received.)
the child is ignored, or the `order`?

2021-04-29 20:40 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +    Parents where `via` is not present are ignored.
same question: what if not an array

2021-04-29 20:40 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +invite is to a space-room or not.
we do exactly this later on in the MSC - this section could do with an update

2021-04-29 20:47 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +invite is to a space-room or not.
I have a draft MSC (https://hackmd.io/P8qVmVJORvSvvKRbjiU_nw) which might do what you're asking...

2021-04-29 20:50 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +    Children where `via` is not present are ignored.
MSC #2946 seems to have some more words on this:

> `m.space.child` with an invalid via (invalid is defined as missing, not an array or an empty array) are ignored.

Maybe that should be moved here though.

2021-04-29 20:58 UTC, uhoreg approved these changes
Some nits, but looks plausible in general

2021-04-29 20:58 UTC, uhoreg commented on proposals/1772-groups-as-rooms.md
> +`type: m.space` property in the content of the `m.room.create` event. This allows clients to
(non-blocking comment) I know already mentioned in the "Rejected Alternatives" section, but I think it would be helpful to have a short rationale for why there's a new `type` property (possibly with a pointer to the "Rejected Alternatives" section for more details).  Maybe something like 

> A `type` property on the `m.room.create` event is used to ensure that a room cannot change between being a space-room and a non-space room.  For more information, see the "Rejected Alternatives" section below.

2021-04-29 20:58 UTC, uhoreg commented on proposals/1772-groups-as-rooms.md
> +"Public" or "community" spaces would be set to `world_readable` to allow clients
(style nit) This seems to me like a continuation of the previous sentence since it's about `m.room.history_visibility`, so feels like it should be part of the same paragraph.

2021-04-29 20:58 UTC, uhoreg commented on proposals/1772-groups-as-rooms.md
> +allow peeking; you have to be joined to see the members.
This seems related to https://github.com/matrix-org/matrix-doc/issues/1653

2021-04-29 21:01 UTC, uhoreg commented on proposals/1772-groups-as-rooms.md
> +    received.)
FWIW, I read it as `order` being ignored

2021-04-29 21:12 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    received.)
the `order`.

2021-04-29 21:31 UTC, uhoreg commented on proposals/1772-groups-as-rooms.md
> +MSC #2758. This allows clients to offer slightly customised user experience
```suggestion
[MSC2758](https://github.com/matrix-org/matrix-doc/pull/2758). This allows clients to offer slightly customised user experience
```

2021-04-29 22:20 UTC, uhoreg commented on proposals/1772-groups-as-rooms.md
> +include the `m.room.create` event in their `invite_state`.
Should we also add `m.room.create` to `knock_state`?

2021-04-30 07:58 UTC, BillCarsonFr commented on proposals/1772-groups-as-rooms.md
> +`room_id` string).
Proposal to resolve cycles. https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fx:

2021-04-30 11:44 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +include the `m.room.create` event in their `invite_state`.
This is similar to the conversation above: https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r623375762

I have a separate draft-MSC that attempts to standardize some of the stripped state that can be seen by users: https://hackmd.io/P8qVmVJORvSvvKRbjiU_nw

2021-04-30 14:06 UTC, uhoreg commented on proposals/1772-groups-as-rooms.md
> +include the `m.room.create` event in their `invite_state`.
OK. If there's movement towards fixing it up later, then I'm fine with punting it for now.

2021-04-30 14:09 UTC, erikjohnston commented on proposals/1772-groups-as-rooms.md
> +    sufficient power-level to send such an `m.space.child` event in the
This does mean that if an admin leaves the parent space the child relationship will break, which is a bit weird. I don't know how you'd handle it any differently though.

2021-04-30 14:34 UTC, richvdh commented on proposals/1772-groups-as-rooms.md
> +    sufficient power-level to send such an `m.space.child` event in the
s/leaves/is demoted/. And yes, this is called out in the issues.

2021-04-30 14:37 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +`room_id` string).
added

2021-04-30 14:39 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +include the `m.room.create` event in their `invite_state`.
until @clokep's MSC lands, shall we just add it to `knock_state` too in here?

2021-04-30 14:39 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +root (i.e. oldest parent).  'Oldest' means the room whose `m.room.create`
fixed

2021-04-30 14:43 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +    sufficient power-level to send such an `m.space.child` event in the
yup, agreed it's weird. but nobody has found a better solution. speak now or forever...

2021-04-30 14:55 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +include the `m.room.create` event in their `invite_state`.
That seems reasonable to me. 👍

2021-04-30 14:59 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fxg shows an algorithm for doing so.
can we include the algorithm in the MSC please? This is highly likely to not age well...

2021-04-30 15:00 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fxg shows an algorithm for doing so.
i guess we can shove it in as an appendix. but it's just an implementation hint, imo

2021-04-30 16:05 UTC, erkinalp requested changes

2021-05-03 17:09 UTC, deepbluev7 approved these changes
Looks good to me, thank you!

I have some slight reservations about "suggested" being the right name and if that shouldn't accept an enum, but not enough to open a comment about it and it is at least the simple solution.

So yeah, in general this looks really reasonable to me and thank you for putting so much effort into this!

2021-05-03 17:37 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +include the `m.room.create` event in their `invite_state`.
Not done yet, but I did put this up as #3173.

2021-05-03 17:48 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fxg shows an algorithm for doing so.
I don't feel this needs clarifying in the MSC, but thank you.

2021-05-03 17:49 UTC, turt2live commented on proposals/1772-groups-as-rooms.md
> +https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fxg shows an algorithm for doing so.
indeed: just looking to dump it essentially verbatim into the MSC so it doesn't bitrot. The spec wouldn't include it necessarily.

2021-05-03 21:25 UTC, ara4n commented on proposals/1772-groups-as-rooms.md
> +https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fxg shows an algorithm for doing so.
I'll dump it in, but first I need to understand why the implementation cares ordering by the number of incoming edges before ordering by ts... paging @BillCarsonFr

2021-05-04 07:49 UTC, BillCarsonFr commented on proposals/1772-groups-as-rooms.md
> +https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fxg shows an algorithm for doing so.
It's to give more weight to nodes that are real roots as defined by user.
If not the algorithm could start anywhere in hierarchy and break the cycle in a strange way.

````

                                  ┌────┐
                                  │ S1 │
                          ┌───────┴────┴───────┐
                          │                    │
                          │                    │
                          │                    │
    ┌──────────────────►┌─▼─┐               ┌──▼──┐
    │                   │   │               │     │
    │             ┌─────┴───┘             ┌─┴─────┴──┐
    │             │                       │          │
    │             │edge2                  │          │
    │             │                       │          │
  edge1         ┌─▼──┐                  ┌─▼──┐     ┌─▼─┐
    │           │S0  │                  │    │     │   │
    │       ┌───┴────┴──┐               └────┘     └───┘
    │       │           │
    │       │           │
    │       │           │
    │       │           │
    │     ┌─▼─┐     ┌───▼─┐
    └─────┤   │     │     │
          └───┘     └─────┘

````
Here S0 is older than S1
If using Nie edge1 will be broken, if not edge2 will be

Not sure what would be the best way to create the most 'logically balanced tree', we could go a lot farther and detect all cycles then age the edges based on child and/or parent state event age, then decide to break the last added edge. But it's a lot more complex.

TL;DR; the idea was to add more weight to real roots, and not rely only on age given that i can create a new space to enclose and old one. But no mathematical proof that it's that better

2021-05-04 12:07 UTC, richvdh commented
@mscbot concern no agreement on cycle-breaking algorithm

The day before an MSC completes FCP is not the time to be discussing the merits of various algorithms, not least because it makes it very clear that we are speccing something without a tested implementation.

We've got this far without a consistent algorithm, and I remain far from convinced we really need one. Additionally, it seems like an easy thing to experiment with a bit in implementations. Can we not leave it out of this MSC in the interests of practicality?

2021-05-04 12:23 UTC, erkinalp commented
> Can we not leave it out of this MSC in the interests of practicality?

For user experience reasons, the cycle breaking algorithm should be consistent with group access control MSC.

2021-05-04 13:34 UTC, clokep commented
> The day before an MSC completes FCP is not the time to be discussing the merits of various algorithms, not least because it makes it very clear that we are speccing something without a tested implementation.
> 
> We've got this far without a consistent algorithm, and I remain far from convinced we really need one. Additionally, it seems like an easy thing to experiment with a bit in implementations. Can we not leave it out of this MSC in the interests of practicality?

Per our conversation in #matrix-spec:matrix.org, I've removed the bit about the algorithm, leaving only the text above it that warns that cycles may exist (although are not permitted) and must be broken. If necessary, a recommended algorithm for breaking cycles consistency could be proposed after experimentation.

2021-05-04 13:36 UTC, clokep commented on proposals/1772-groups-as-rooms.md
> +https://hackmd.io/eQpyqCcRR-Gj-SWZcD-Fxg shows an algorithm for doing so.
Per the conversation in #matrix-spec and the concern from @richvdh, I've removed the bit about the algorithm for now. After experimentation, a separate MSC can be provided which describes a recommended algorithm, if this is necessary.

2021-05-04 14:04 UTC, ShadowJonathan commented
> If necessary, a recommended algorithm for breaking cycles consistency could be proposed after experimentation.

Agreed, although I'm not entirely comfortable with UB being left in the spec, maybe mention it? ("Warning: while not allowed, cycles may exist, and a future spec change shall address client-specific behaviour for this. In the meantime, implementations must be aware of such a phenomenon.")

2021-05-04 14:53 UTC, richvdh commented
@mscbot resolved no agreement on cycle-breaking algorithm

2021-05-04 15:10 UTC, clokep commented
> > If necessary, a recommended algorithm for breaking cycles consistency could be proposed after experimentation.
> 
> Agreed, although I'm not entirely comfortable with UB being left in the spec, maybe mention it? ("Warning: while not allowed, cycles possibly exist, and a future spec change shall address client-specific behaviour for this. In the meantime, implementations must be aware of such a phenomenon.")

I don't know what "UB" means.

As the sentence before the one which you quoted says (emphasis added):

>  I've removed the bit about the algorithm, **leaving only the text above it that warns that cycles may exist (although are not permitted) and must be broken**. 

So there's already text in in there which says something similar. The exact wording is:

> Cycles in the parent->child and child->parent relationships are *not* permitted, but clients (and servers) should be aware that they may be encountered, and MUST spot and break cycles rather than infinitely looping.

2021-05-04 15:22 UTC, richvdh commented
people, go and use a thread, please.

2021-05-05 15:42 UTC, merged

2021-05-05 15:45 UTC, turt2live commented
`blocked` label is because we don't want to spec this formally until other Spaces-related MSCs land.

2021-05-07 22:55 UTC, MadLittleMods commented on proposals/1772-groups-as-rooms.md
> +implementation of `allow`.
This thread was moved to https://github.com/matrix-org/matrix-doc/pull/2962#discussion_r557000283

2021-12-31 00:25 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-doc/pull/3610

2022-01-17 17:04 UTC, turt2live commented
Merged 🎉

2022-02-07 08:06 UTC, soloturn commented
@ara4n , what a cool idea! this means users can organize themselves into a directed acyclic graph? so a company following a matrix organisation could use these spaces to build out communication. and use a feature like "message to all UK employees"? and one could then go away from the room structure, and, as matrix client, just present a flat list of messages, bearing tags of spaces they belong to? and a GUI displaying this graph and filter the messages like this?

2022-02-07 08:23 UTC, ptman commented
@soloturn This MSC has been merged and spaces are available in Element. You can try them out and see for yourself.

2022-02-08 02:52 UTC, soloturn commented
@ptman thank you! i tried in element now, and got a headache - a proper GUI designer with a flair for simplicity, one which had no previous affiliation with element, would be the most beneficial investment for this application. if it is permitted to say that *blush*.