MSC2312: Matrix URI scheme proposal
matrix-org/matrix-doc pull request #2312
Opened 2019-10-04 10:09 UTC by KitsuneRal

This is a remake of #455 - now in Markdown, and greatly extended.

2019-10-04 12:52 UTC, MayeulC reviewed
This looks like a solid MSC to me, with good self-consistency. I am still not sold on the type specifier, though maybe the way to go is to have a first version out and iterate on it (with all the complexity due to backwards compatibility).

I would put a lot more real-life examples in the spec, as advised in the RFCs. Has this been trough a lot of verification, or does it need further analysis (like fuzzing) to check that no ambiguous situation might arise?

I would like to see someone from the IETF review this MSC once it is approved on the Matrix side, before accepting this, as they are likely to have a lot more experience on that topic.
[Here are my previous notes on the subject (sigil-based)](https://cloud.mayeul.net/index.php/s/BxoRxK6DkKQoqZ7)

The most relevant stuff from those notes is probably the action plan I wrote:

----------
<h3 id="todo-uri-scheme"></h3>

### Action plan:

The following steps are required to bootstrap the ecosystem once the proposal has been accepted:
 - [X] Declare the `matrix:` protocol to the IANA as per [BCP35]. The `matrix:` scheme is now [registered as provisional](https://www.iana.org/assignments/uri-schemes/prov/matrix) in the [schemes list](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)
 - [x] Add `matrix:` to the [safelisted schemes list](https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers:safelisted-scheme) to allow websites registering themselves as protocol handlers. [PR](https://github.com/whatwg/html/pull/6320)
   - [ ] Make sure Chromium safelists it: [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1169258)
   - [x] Make sure Firefox does so too: [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1688030), [patch](https://phabricator.services.mozilla.com/D113023)
   - ~~Safari~~ Does not support custom handlers
 - [ ] matrix.to improvements:
   - [ ] add a [parser](https://github.com/matrix-org/matrix.to/issues/191) for `matrix:` urls
   - [ ] add a `matrix:` [scheme generator](https://github.com/matrix-org/matrix.to/issues/192)
   - [ ] Add matrix.to as a default handler for `matrix:` URLs
     - [ ] Mozilla Firefox
     - [ ] Chromium
     - [ ] Various desktop environments
     - [ ] Open issues for proprietary browsers
 - [ ] Update various clients to handle the new scheme
   - [X] [libQuotient-based Clients](https://github.com/quotient-im/libQuotient/releases/tag/0.6.0) ([MR](https://github.com/quotient-im/libQuotient/pull/407)): [Quaternion](https://github.com/quotient-im/Quaternion/commit/89dc3ea05bba64e4170922272644ab50f57d5d82), Spectral
    - [X] [Fluffychat](https://gitlab.com/famedly/fluffychat/-/merge_requests/330)
    - [X] [Nheko](https://github.com/Nheko-Reborn/nheko/pull/370)
    - [ ] [gomuks](https://github.com/tulir/gomuks/issues/89) (contains info on how to register the protocol on Linux)
    - [ ] [Element for Nextcloud](https://github.com/gary-kim/riotchat/issues/145) (contains info about web browsers protocol whitelist)
    - [ ] [Element](https://github.com/vector-im/element-web/issues/16875)

[BCP35]: https://tools.ietf.org/html/bcp35

2019-10-04 12:52 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +authority = host [ “:” port ]
Do we have a use-case for multiple authorities? To protect against bit-rot and servers being decommissioned, I could see multiple authorities being used (unless the routing part is enough)

2019-10-04 12:52 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +action = “action=join”
If it needs to be acknowledged by the user, is `action=join` really useful?

2019-10-04 12:52 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +MUST ignore it if found and MUST NOT generate it for other Matrix resources.
Note that it could be useful for decentralized identifiers later, though it might not be relevant to that spec.

2019-10-04 12:52 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +    (decentralised id, future) `!lol823y4bcp3qo4`
Did you mean to write something like `matrix:roomid/!lol823y4bcp3qo4`?

2019-10-04 12:52 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   _Why not Reddit-style single-letter type specifiers? That's almost
Interesting question, worth discussing. If emojis were easier to enter on all platforms, thy might even have been a good choice.

2019-10-04 12:52 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +leaving a room (`action=leave`); bounds for a segment of the room timeline
I think that having those URIs opens the gate to a range of problems: denial of service (leave action), leak of user identity (join, chat). Is there really a strong case for those?
As I see it, the join operation is one of the only ones the user could perform on a room, so why do we need to specify it? The same holds true for direct chat.
Plus, taking the example of a project giving a Matrix URL for discussion, I wouldn't necessarily be interested in joining the room (but maybe browse it as a guest), yet the project could somewhat force me to join with an `action=join` URI

2019-10-04 12:52 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +and Matrix identifiers as easy as a bunch of regular expressions; so
should those regexes be provided in the MSC as well?

2019-10-05 06:29 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +authority = host [ “:” port ]
That's a great question to which I don't have a definitive answer. This MSC is written with an assumption that the authority is _basically_ singular (i.e. there's a single entity controlling that authority). But I can conceive a case with several Matrix federations being co-accessible from a single client, even though I doubt this has much merit. In that setting a use case for multiple authorities under each federation becomes viable. While in theory we could use `,` or `;` to make a list of host-ports, I'm pretty sure not too many parsers will handle this reasonably (especially the port part). I also added some ramblings on the subject here: https://github.com/matrix-org/matrix-doc/issues/2309#issuecomment-538619094.

2019-10-05 06:31 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +action = “action=join”
It is, to convey the point that the UI should (at least) prompt the user to join the room. Also, there are cases where such acknowledgement is extraneous, e.g. joining through a room upgrade.

2019-10-05 06:35 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +MUST ignore it if found and MUST NOT generate it for other Matrix resources.
Right. This MSC says to ignore the action in "improper" contexts but further MSCs may extend applicability of a join action, of course - at which point I'd rather the spec not step on feet of clients that ventured to add some independent meaning to `action=join`.

2019-10-05 06:43 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   _Why not Reddit-style single-letter type specifiers? That's almost
Emojis in URIs don't quite fly - not as a primary medium at least. [You should be able to write a URI on a napkin](https://tools.ietf.org/html/rfc3986#section-1.2.1), and emojis are terrible for that. (WIth that said, for napkins we already have Matrix identifiers.)

2019-10-05 06:49 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +leaving a room (`action=leave`); bounds for a segment of the room timeline
The action brought up here are just ideas for further MSCs. I share your concern to some extent, and we might end up not having `action=leave` at all, for example. As for your case with `action=join` - I think I'll add to the MSC that normally clients SHOULD NOT append `action=join` in URIs generated for general purposes.

2019-10-05 07:32 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +and Matrix identifiers as easy as a bunch of regular expressions; so
Yes and no. RFC 3986 is quite diligent at providing such regex for the high-level parsing; but these days such high-level parsing should be done by some already existing library rather than custom code. This MSC would surely benefit from an algorithm turning the path into Matrix identifiers though; and half of that work is already done in the "URI semantics" section.

2019-10-05 20:40 UTC, auscompgeek commented on proposals/2312-matrix-uri.md
> +path = type “/” id-without-sigil “/” path
Unless I missed it, it looks like there's no terminal rule for path. I suspect you meant:
```suggestion
path = type “/” id-without-sigil [“/” path]
```

2019-10-05 23:12 UTC, KitsuneRal commented
> 
> 
> It looks like "smart quotes" have been used throughout this doc (except in one or two places), even in the BNF. Is that intentional?

Not exactly, it's just a result of copy-pasting from the older Google doc. If that causes problems, I can revert to ASCII quotes.

2019-10-07 03:48 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +    (decentralised id, future) `!lol823y4bcp3qo4`
Spot on, thanks!

2019-10-13 11:25 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   _Why not Reddit-style single-letter type specifiers? That's almost
One of the issues I see with using plain english words is that those can be as opaque as sigils (but longer) for those who do not speak it (and could hypothetically be harde to type on some keyboard layouts).
I would really like to give Matrix all the chances it deserves on the International scene, as a communication tool. One-letter sigils might be more universal? Though harder to understand than words for English-speaking users. Of course, the client itself could explain the URLs in a locale-appropriate way, or display it with sigils, regardless of the URI form. So is it a non-issue as well? Especially with many Internet technologies (and the scheme itself) being English-focused.

2019-10-13 13:19 UTC, auscompgeek commented on proposals/2312-matrix-uri.md
> +   _Why not Reddit-style single-letter type specifiers? That's almost
One issue with the `#` sigil is that they denote fragments in URIs, so that's already a showstopper unless you want to make consuming matrix URIs significantly more difficult than necessary.

2019-10-13 17:21 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   _Why not Reddit-style single-letter type specifiers? That's almost
Woops, I wrote "one-letter sigils" without explicitly stating that I meant `/r/` instead of `/room/`, for instance. Or `/#/` for that matter.
That said, it doesn't need to be significantly more complex, as you can just `s,#,room/,` and parse the URI as usual, whenever you detect a `matrix:` scheme URI. But we might as well elect to pick the `/room/` version as the actual URI, and let the client do the opposite transform, as I wrote :)

2019-11-06 21:41 UTC, andrewrothman commented on proposals/2312-matrix-uri.md
> +authority = host [ “:” port ]
@KitsuneRal What would be a use case where you would specify an authority?

2019-11-07 05:30 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +authority = host [ “:” port ]
The comment I linked to gives one use case - if you have a bunch of federated networks the URI should include some way to identify an "entry point" or, well, an authority. Another even use-case is a URI into a given Matrix unfederated room available from only one server.

2019-11-07 23:19 UTC, andrewrothman commented on proposals/2312-matrix-uri.md
> +authority = host [ “:” port ]
I see. That makes sense. Thank you.

2019-11-21 08:57 UTC, tulir commented on proposals/2312-matrix-uri.md
> +_instead of engaging the current user's homeserver connection_:
[@nep:pink.packageloss.eu](https://matrix.to/#/@nep:pink.packageloss.eu) had some good points about this: it doesn't seem to make any sense, why would the client need to be able to resolve users/rooms/etc that it won't be able to talk to anyway?

Original quote:

> What is the point of this? Why can't the client just ask the server for the ressource while providing the authority data?
> I.e URL previews seem to be in matrix exactly to prevent this
> i.e setting up a server to steal ips on matrix://badhost.example/room/evilroom

> The reasoning of "it may not be reachable per federation" doesn't quite make sense to me, i don't see how or why a client should try to resolve ressources of servers it has no access too (i.e with which it doesn't speak at all normally)

2019-12-16 17:31 UTC, martindale commented on proposals/2312-matrix-uri.md
> +`group`; and the only `query` defined for now is `action=join`. The Matrix
I petition that these URIs be changed to plurals, as otherwise they serve no purpose other than to leak information about the requested document.  This would also open up `matrix:example.com/rooms` as a canonical identifier for a server's room list, `matrix:example.com/users` for a user directory, etc.

2019-12-16 18:20 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +`group`; and the only `query` defined for now is `action=join`. The Matrix
Actually, the MSC mentions why, in particular, `matrix:example.com/rooms` does _not_ seem a good fit for purpose. In order for your call to be considered, I have to request your response to that reasoning - namely how you believe the ambiguity should be resolved. You may also miss the point that overall `matrix:room/roomalias:example.com` is expected to be much more widespread than `matrix:example.com/room/roomalias:example.com` (or `matrix:example.com/rooms/roomalias:example.com`, if the it is plural).

P.S. The purpose of those words is very focused: they are a substitute for sigils in original Matrix identifiers, and therefore specify the resource type.

2019-12-16 19:30 UTC, martindale commented on proposals/2312-matrix-uri.md
> +`group`; and the only `query` defined for now is `action=join`. The Matrix
Why include the `room` component of the URI at all?  Why not just `matrix:example.com#roomalias` or even `matrix:#roomalias:example.com`?

2019-12-17 05:57 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +`group`; and the only `query` defined for now is `action=join`. The Matrix
Because without specifying the resource type the URI is unpredictably ambiguous. Even right now `matrix:something:example.org` can equally mean a user id, a room alias, and a group name. Using `#` to denote the type is improper and not RFC-compliant (for the [same reason](https://github.com/matrix-org/matrix-doc/pull/2312/files#discussion_r334277740) `matrix:#roomalias:example.com` is not compliant). I can imagine using something like `matrix:example.com?roomalias` but that invades the query part territory which was not intended to _identify_ resources but rather _query_ the server on the resources identified by the authority and path components.

2019-12-17 16:37 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +`group`; and the only `query` defined for now is `action=join`. The Matrix
>  petition that these URIs be changed to plurals, as otherwise they serve no purpose other than to leak information about the requested document.

The *whole* point of this proposal is to introduce a canonical way to identify a document. There is no information leak to worry about, as the purpose really is to pass "information about the requested document" around (and if you are thinking about web clients, that URI can be put after a "#" fragment in a browser's address bar to avoid leaking it to the server that hosts the web client).

Moreover, using the plural form does not really identify a resource. The best case I can make for using a plural here would be to transparently handle browsing a hierarchy of properties like the REST API already does. I don't really think that fits the intended design bill here, although that could be useful at times.

The intended purpose being to identify a unique resource, I still think the singular makes more sense here (if only because the biggest use case is to share a link to matrix:room/matrix-spec:matrix.org which is subjectively prettier than the plural form as it is grammatically correct). And, although it might be a bit less pretty when browsing a hierarchical view that another tool might provide, it's still clearly understandable.

2020-01-18 16:43 UTC, kb-1000 commented on proposals/2312-matrix-uri.md
> +MUST ignore it if found and MUST NOT generate it for other Matrix resources.
But aren't there other things than rooms that users can join too?

2020-01-18 17:01 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +MUST ignore it if found and MUST NOT generate it for other Matrix resources.
In short - none enshrined in the spec.

Outside of the spec we now have groups (aka communities); once they are specced another MSC may propose URIs like `matrix:group/us:matrix.org?action=join`. The current MSC intentionally does not cover groups since they will be overhauled and mechanics of handling them may change (although I'm pretty sure that joining a group will still be a thing).

2020-01-18 17:23 UTC, kb-1000 commented on proposals/2312-matrix-uri.md
> +MUST ignore it if found and MUST NOT generate it for other Matrix resources.
Oh... I didn't know that they weren't in the spec, that would explain it.

2020-03-14 23:05 UTC, nogweii commented
I'm just passing by, but I wonder if anyone has put any thought into the use of English terms in the URI? Does it matter?

2020-03-15 06:48 UTC, julianfoad commented
@nogweii: yes they have: search for "English" in the earlier comments.

2020-03-28 13:56 UTC, ilmari commented on proposals/2312-matrix-uri.md
> +`matrix:room/roomid:example2.org/event/eventid`.
Shouldn't this have type `roomid`, i.e. `matrix:roomid/roomid:example2.org/event/eventid`?

2020-06-01 10:23 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  these is not a reasonable option, given that the two are the most used sigils.
That's also what comes to my mind now that I get back to this MSC and try to finalise it. Looking at the described use cases for Matrix URIs:
- (1) Representation (business cards etc.). We have a great means for that already working ("classic" identifiers); Matrix URI are somewhat foreign here (they look more like "machine language" than identifiers) but they, theoretically, are more expressive (can convey actions, hierarchy, extra info to pass along). 
  Whether it's valuable for a case of "writing URI on a napkin" - maybe, but we may extend the grammar of identifiers instead. Another idea that I'm thinking of since, like, yesterday is to have a specific "user-friendly" form of Matrix URI that would start with `matrix:#` (or even `matrix:/#`) thereby making the rest of the URI a fragment. Clients then have to convert this form to the "wire Matrix URI" form.
- (2/3). Integration is the most wanted use case for Matrix URIs usage (links on HTML pages, resource identifiers for APIs, etc.). Machines will not care about percent encoding, they decode URLs as a part of parsing anyway.

The more I play with Matrix URI in the form proposed as yet, the more this specific decision (to drop sigils) looks dubious to me; so if an idea of two forms of Matrix URIs doesn't sound too bad, the "wire Matrix URI" might have sigils percent-encoded when necessary, and the "user Matrix URI" form would punt encoding issues on to clients that will have to transform them before putting on the wire. Or just keep using identifiers for case 1 (and also transform them in order to turn to Matrix URIs).

2020-06-01 10:45 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +Clients MUST resolve all Matrix entities that they support.
Ok, I was afraid it's confusing. My point was that if the client supports a certain Matrix entity (usually: user/room/room-alias/event, but not group) it MUST be able to make and handle URIs for that entity.

2020-06-01 11:27 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +Clients MUST resolve all Matrix entities that they support.
Surely "clients must do X" (unconditionally) doesn't belong in *this* spec, does it?

2020-06-01 11:52 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +Clients MUST resolve all Matrix entities that they support.
Fair enough, I should probably mention that the requirement only applies to clients that are supposed to deal with Matrix URIs at all.

Or I can just drop the line and allow clients to apply "best effort" in supporting Matrix URIs. Given the pretty high value of interoperability in a desktop setting, clients that have anything to do with Matrix URIs are likely to support as much of them as feasible, right?

2020-06-01 13:00 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +Clients MUST resolve all Matrix entities that they support.
Really, just remove it.

2020-06-14 10:20 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  these is not a reasonable option, given that the two are the most used sigils.
Update to the above: I scratched the idea of two Matrix URI forms.
1. Two different forms mean implementation and maintenance overhead.
2. For "user Matrix URIs", clients have go an extra mile of extracting the query part out of the fragment, as normally the query is supposed to precede the fragment, not the other way around. Moreover, this is semantically confusing because with RFC-compliant URIs you first perform the query, then navigate to the result's fragment, and this holds for Matrix URIs too.
3. According to RFC3986 (and probably counterintuitively a bit), the list of reserved characters for the path and the fragment is identical. This means that "user Matrix URIs" have to use exactly the same encoding as "wire Matrix URIs", making them equally (in)convenient for napkins.

2020-06-14 10:40 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +authority = host [ “:” port ]
As of right now, multiple authorities are put out of scope. Further MSCs can introduce syntax extensions for that.

2020-06-14 10:46 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +without joining it anyway.
I think of rewriting it along the lines "If it's an external link and the room is not a predecessor or successor, clients MUST ask the user; if it's internal or the room is in an upgrade chain, join automatically". WDYT?

2020-06-14 11:21 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +without joining it anyway.
You should not write "clients should" or "clients must" in this spec. (Consider writing a companion document for that sort of thing.) Instead, here, you should write examples of scenarios where it does or does not make sense to use each possibility defined in this spec.

2020-06-14 11:30 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +without joining it anyway.
Well, maybe "should" can be OK, but you can't generalise about all clients: some clients are robots intended to respond automatically, for example. Here should be something like: "A link using action=join means the link author intends the user should join the room right away, so for example an interactive client might either initiate a join procedure without further input or might prompt the user before doing so."

2020-06-14 11:35 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +without joining it anyway.
I do like your ideas about how a client might treat links to next and previous room-version differently from other links, and so on, but they are ideas better expressed in a companion doc and should not become part of the definition of URI semantics.

2020-06-14 12:39 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  these is not a reasonable option, given that the two are the most used sigils.
Thinking further to that end, clients could probably be encouraged to decode the sigils before displaying URIs to the end-user, in the same way web browsers do... The (somewhat smallish) problem remains then that blunt copying of `matrix:#roomalias:example.org` to stick into a command line to call some script, or even into another Matrix client, can lead to unintended results. And `#` is the only sigil potentially causing such problems.

2020-06-14 13:36 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +_instead of engaging the current user's homeserver connection_:
Documenting what was also discussed with @nep in Matrix back then - this is specifically to address the case when there are two homeserver networks and the user has an account in each. Think of such URI as pinning the specific network: if you have your own (non-federating) homeserver that's only seen in your LAN, you likely don't want to send a URI containing its address to matrix.org or whatever "current" connection you use. This becomes more sensitive when you have one public and one "closed" (e.g., corporate) federation and your Matrix client can connect to both: sending a closed URI to the public federation is an information leak.

I get that there's also a threat of IP address leaking through rogue links accidentally followed so let me address this. First off, Matrix URIs with the authority part look different to common Matrix URIs so this alone should cause suspicions, in the same way an https link to a bare IP-address you don't readily recognise; on the other hand, your Internet provider doesn't know about your internal LAN details so trying to route requests to 192.168.x.x through your Internet connection is usually pretty stupid. Basically, it's a question of Internet hygiene: if you click on links without thinking, Matrix protocols won't save you from an eventual fiasco.

Second, I can imagine using your "current" homeserver as a proxy for all interactions with Matrix; in that case you're likely to ban or rewrite all URIs with authority parts altogether since you have the only authority server available. I realise that the current wording does not have such provision and will try to add it.

Finally, given that Matrix URIs with the authority part are, as I see it, mostly a case about controlled environments (see above), client applications can probably be obliged to confirm with the user before following the link to the server they don't "know". Depending on the level of paranoia, "knowledge" of the server may mean either "the homeserver is in the whitelist" or "the homeserver the user has an account at". This partially alleviates the first point about clicking links without a good look at them.

2020-06-14 14:33 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +without joining it anyway.
Well, our spec is quite opinionated on what the clients should and shouldn't do in many places, and despite a few facepalms I think it's generally for the better. What I'd really like to avoid in this case is careless clients just slapping the room joining code to Matrix URI handler opening their users to all kinds of privacy, if not security, hazards. Therefore I certainly want to put a requirement or at least a strong recommendation for such confirmation in the spec.

We do plan (since, basically, [this week](https://github.com/matrix-org/matrix-doc/pull/2618)) to provide implementation guides that seem to match what you call a companion document; I'm pretty sure though that we want to keep some things normative, and implementation guides by definition are not supposed to have normative clauses. 

I'm hearing you about robots - what if we require the confirmation from clients that have UI?

2020-06-14 14:51 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +without joining it anyway.
Let's continue the discuss in #matrix-spec:matrix.org please. Github issues isn't so good for holding a conversation.

2020-06-14 23:17 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +_instead of engaging the current user's homeserver connection_:
Hmm, I see multiple cases against this:
1. Is it worse to leak info about the homeserver, or the client? I'd say the latter, as there is at best one client per homeserver, and at worst thousands. Thousands of clients *will* at some point leak the homeserver address. But one leaked address is better than a thousand.
2. The homeserver is generally much-better equipped to make smart choices about its privacy, and it knows whether it federates or not: therefore, it can avoid making such outbound connections in the first place
3. The way clients work today, and that also applies to other domains such as web browsers, e-mail accounts, etc, is that multiple accounts are really compartmentalized. You switch from one identity to another, and everything is assumed to be performed with that identity, which is much easier to reason about IMHO. If you need to migrate data from one identity to another, you have explicit ways to do so (menus, drag-and-drop, copy-paste).
4. This places an unfair burden on client developers, that until now only had to concern themselves with interacting with only one server.

Overall, I do not see the authority part as really useful, and feel like it can be dropped from this proposal, and reintroduced later (maybe specify that URIs with an authority part are reserved for later use?). Especially in light of 3., I feel that non-federating homeservers have valid internal links inside a given "profile", and they are going to be communicated inside that environment in 98% of cases.

In the case of two disjoint Matrix communities trying to communicate room addresses, etc, I can see that as somewhat useful (if that's a frequent occurrence), but these instances should probably federate together in the first place anyway.

Worst case scenario I can think of is phishing, where someone sends a `matrix:room/itsupport:secretcompany.com` which is a legit room on the non-federated HS, but is an attacker-owned room on the federation. Thankfully, aliases help a bit with that (except for typosquatting). Phishing is a real issue with roomids, especially as those can be arbitrary (think `matrix:roomid/itsupport:secretcompany.com` which is probably valid within the matrix spec, but could be attacker-controlled).

I feel like the last remark is good food for thought, I'm going to bed now ;)

-----
More specific remarks on your last answer :)

> this alone should cause suspicions

Maybe for technical-minded individuals, but if history hs shown us anything, it's that this rarely works with the general public.

> Second, I can imagine using your "current" homeserver as a proxy for all interactions with Matrix; in that case you're likely to ban or rewrite all URIs with authority parts altogether since you have the only authority server available.

Unlikely in a mostly E2EE world :/ That is, unless your client asks your *current* homeserver about a URL when you click on it, instead of having the client perform the lookup. This also avoids spec'ing a paranoia level negotiation for the CS API.

2020-06-15 10:17 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +_instead of engaging the current user's homeserver connection_:
TL;DR:
> Overall, I do not see the authority part as really useful, and feel like it can be dropped from this proposal, and reintroduced later (maybe specify that URIs with an authority part are reserved for later use?). 

Yes, apparently this part needs more discussion and elaboration; I'll take this out.

More responses (for the sake of continued discussion):
> Hmm, I see multiple cases against this:
> 
>     1. Is it worse to leak info about the homeserver, or the client? I'd say the latter, as there is at best one client per homeserver, and at worst thousands. Thousands of clients _will_ at some point leak the homeserver address. But one leaked address is better than a thousand.

I care less about "leaking" homeserver information per se than about leaking the user's particulars and attentions, such as (continuing on public+closed networks case) internal Matrix ids, rooms, addresses in the internal network (not necessarily Matrix) - things like that.

>     2. The homeserver is generally much-better equipped to make smart choices about its privacy, and it knows whether it federates or not: therefore, it can avoid making such outbound connections in the first place

That's not the concern; the concern is that internal matters of the client's environment are leaking to the external network with no clear way to control the default for that.

>     3. The way clients work today, and that also applies to other domains such as web browsers, e-mail accounts, etc, is that multiple accounts are really compartmentalized. You switch from one identity to another, and everything is assumed to be performed with that identity, which is much easier to reason about IMHO. If you need to migrate data from one identity to another, you have explicit ways to do so (menus, drag-and-drop, copy-paste).

Well, compartments are actually a bit different thing that should not have anything to do with URIs. `mailto:whoever@example.org` doesn't (and is not supposed to) say anything about a mail account you can/should use to have a message delivered to this address.

>     4. This places an unfair burden on client developers, that until now only had to concern themselves with interacting with only one server.

Valid point.

> Especially in light of 3., I feel that non-federating homeservers have valid internal links inside a given "profile", and they are going to be communicated inside that environment in 98% of cases.

98% of cases doesn't cut it when it's about privacy/security :) But more importantly, as I said above, URIs are not supposed to convey the information about the profile to use; only about the network to connect to. When I open Quaternion with a link like `matrix://internal.server/room/secret:internal.server` the link conveys no information whether I should use `@user1:internal.server`, `@user2:internal.server` or `@kitsune:matrix.org`. It only conveys information that the room `#secret:internal.server` should be accessed as-if it were authoritatively available at `internal.server`; and Quaternion is not supposed to contact `matrix.org` in order to get to this room.

Hmm, now that I've written it, I feel that it _is_ unnecessarily harsh. Also, it makes assumptions about routing in Matrix, and URI's shouldn't tackle routing questions.

> In the case of two disjoint Matrix communities trying to communicate room addresses, etc, I can see that as somewhat useful (if that's a frequent occurrence), but these instances should probably federate together in the first place anyway.

That's not the envisioned case; such exchange should really consider using federation instead.

> Worst case scenario I can think of is phishing, where someone sends a `matrix:room/itsupport:secretcompany.com` which is a legit room on the non-federated HS, but is an attacker-owned room on the federation. Thankfully, aliases help a bit with that (except for typosquatting). Phishing is a real issue with roomids, especially as those can be arbitrary (think `matrix:roomid/itsupport:secretcompany.com` which is probably valid within the matrix spec, but could be attacker-controlled).
> 
> I feel like the last remark is good food for thought, I'm going to bed now ;)

Yeah, thanks, I also think that this is really something to ponder over.

> > Second, I can imagine using your "current" homeserver as a proxy for all interactions with Matrix; in that case you're likely to ban or rewrite all URIs with authority parts altogether since you have the only authority server available.
> 
> Unlikely in a mostly E2EE world :/ That is, unless your client asks your _current_ homeserver about a URL when you click on it, instead of having the client perform the lookup. This also avoids spec'ing a paranoia level negotiation for the CS API.

Sorry I wasn't clear here - I didn't mean "rewriting" on the server but rather having the client that disables or rewrites such URIs.

2020-06-15 10:37 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +action = “action=join”
A quick search through matrix.to didn't reveal any specific handling of the query part, including `action`... Am I looking in a wrong place or does it just send the query part transparently to a web client?

2020-06-20 10:17 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +action = “action=join”
A more thorough search brought that `action` is entirely client-specific, so this is a feature not of matrix.to but of Riot Web. That being said, I think it makes sense to push `action=chat` from future suggestions to the main proposal.

2020-07-22 05:57 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  these is not a reasonable option, given that the two are the most used sigils.
Ok, so I still think that the currently proposed notation has its merits because it's more _writeable_ (you can manually enter a URI without remembering that `#` is `%23` and so on); but I'm putting the sigil-preserving variant as a possible future extension in the form of `matrix:id/full_id_with_sigil`. Ok?

2020-07-22 12:54 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +without joining it anyway.
While working on the next revision, I'm convinced that this paragraph is more about a personal preference that should not get to the specification.

2020-07-22 13:09 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   _Why not Reddit-style single-letter type specifiers? That's almost
> One of the issues I see with using plain english words is that those can be as opaque as sigils (but longer) for those who do not speak it (and could hypothetically be harde to type on some keyboard layouts).

That's indeed pretty hypothetical - English is _lingua franca_ of infocommunication technologies, for better or worse; and what's more important, in agreement with what you say below, the primary purpose of these URIs is programmatic integration because we already have Matrix identifiers for humans.

That being said, the chosen notation leaves ample room for synonyms so in theory we can even support localised URIs (`matrix:benutzer/kitsune:matrix.org` for German, e.g.). But this is extremely far-fetched even if technically feasible.

> I would really like to give Matrix all the chances it deserves on the International scene, as a communication tool. One-letter sigils might be more universal? Though harder to understand than words for English-speaking users. Of course, the client itself could explain the URLs in a locale-appropriate way, or display it with sigils, regardless of the URI form. So is it a non-issue as well?

Exactly. Client applications always have an opportunity to represent URIs in a user-accessible way, to the point of turning them to Matrix identifiers or even replacing entirely with human-friendly display name for a given entity.

2020-07-22 15:11 UTC, KitsuneRal commented
The proposal is out of WIP - all feedback is welcome.

2020-07-23 10:15 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   b. If `query` contains one or more items starting with `action=` - treat
The dash is a bit strange here, and a. is a bit hard to parse
```suggestion
   a. If `query` contains one or more items starting with `via=`: for each item, treat
      the rest of the string as as a percent-encoded authority to be used in
      [routing](https://matrix.org/docs/spec/appendices#routing).
      
   b. If `query` contains one or more items starting with `action=`: treat
```

2020-07-23 10:18 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +      chat, as per this proposal.
Maybe a bit too specific? Can also be used to join a room.

```suggestion
      _the last_ such item as an instruction, as this proposal defines in [query](#query).
```

2020-07-23 10:24 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +The classes of URIs and corresponding default actions (along with relevant
I would put all of this into a new "Appendix" section, together with more examples, if needed.

2020-07-23 10:26 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   and nicely avoids the confusion described in the previous question._
What previous question? If mentioning advantages, slightly better internationalization is one

2020-07-23 13:50 UTC, KitsuneRal commented
Responding to points not mentioned inline with the proposal:

>     * are clients "allowed" to extend action with client-specific action classes?

That's a good point. Probably it makes sense to have an extension point here, although I'd really hate to prepend the current actions with `m.`, as we usually do with customisable pieces. Perhaps a separate action key (say, `custom_action`) could be reserved for that, though it looks somewhat ugly and prone to ambiguity.

>     * Is `mxc:` completely out of scope for this proposal? On the other hand, the current mxc architecture could use a few overhauls: content-based addressing, for starters.

Yes, it is completely out of scope here. Basically, it's good enough to be working here and now, and it's used in contexts entirely orthogonal to those of `matrix:` URIs. Further on we might unify things under a single umbrella but given that `mxc` URLs are semantically very different (they _are_ centralised, to begin with) I wouldn't mix them in at this point in time.

Alexey

2020-07-23 13:50 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  [successor or predecessor](https://matrix.org/docs/spec/client_server/latest#module-room-upgrades).
Right, sorry, it's an editing left-over.

2020-07-23 13:52 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   1. Room IDs (`!roomid:example.org`)
Not completely - they still follow the localpart:serverpart pattern, unlike event ids.

2020-07-23 13:54 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   b. If `query` contains one or more items starting with `action=` - treat
Could you edit "as as"?

2020-07-23 13:56 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   b. If `query` contains one or more items starting with `action=` - treat
Also, these servers are not _quite_ authoritative - they are just routing gateways. It's true that they (in theory) can present their own idea of what a given room is but in a public federation it's rather pointless.

2020-07-23 13:57 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   and nicely avoids the confusion described in the previous question._
Yeah, it's actually referring to the question before previous. I knew it would be confusing, will fix.

2020-07-23 22:03 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   b. If `query` contains one or more items starting with `action=` - treat
Done ;)

These edit suggestions are just that: suggestions; I do not pretend to have the best wording. I also get your point about using "authority" instead of "homeserver name". I thought it would be simpler, more consistent and generic, but that's not necessarily the case. Since IP addresses or other arbitrary sources can be used, how about `authoritative source`?

2020-07-23 22:13 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   1. Room IDs (`!roomid:example.org`)
All right, this seems to be what [the spec is saying](https://matrix.org/docs/spec/appendices#room-ids-and-event-ids). I am not sure synapse enforces it, though :)

2020-07-24 10:30 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   b. If `query` contains one or more items starting with `action=` - treat
The way `via=` works now assumes exactly that, a homeserver identification. And again - it's really not an authority, it's just a server knowledgeable about the room. It may have, like, 0.001% of this room's events stored and none of it originating from a user registered on this server. It just "knows" where to find the rest of events, and that's what matters. "Authority" means the server is the ultimate source of truth. Servers can only be authoritative about events originated at them, and having even one is not a requirement for `via=`. The fact that the syntax includes the `authority` term is a mere coincidence; actually, I think of renaming it to prevent confusion.

2020-07-24 10:33 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   1. Room IDs (`!roomid:example.org`)
Not sure how that supports your argument. The spec says that the domain is an essential part of the room id.

2020-07-24 14:55 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
This introduces that event IDs must be globally unique instead of per-room unique and can also greatly complicate client implementations. See discussion over here: https://github.com/matrix-org/matrix-doc/pull/2695#discussion_r459641368

2020-07-24 15:13 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +Putting the whole id to the URI fragment (`matrix:#id_with_sigil` or,
Why not just url-encode the full URI? That would also solve issues with `/`'s in user-IDs etc. `#` would become `%23` then, etc. and this would probably through less people off-guard

2020-07-24 21:55 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
It doesn't. This requirement says nothing about the level of the identifier, only about the form.

2020-07-25 06:31 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
That is the problem: This MSC does not explicitly forbid event IDs on their own, leading to the global-uniqueness of event IDs which is undesirable, see linked thread for the discussion on that.

While the examples currently hint per-room uniqueness, nothing in this MSC seems to forbid event IDs being used on their own.

2020-07-25 07:44 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   1. Room IDs (`!roomid:example.org`)
Sorry if I wasn't clear. the "Right" at the beginning of my sentence meant I agreed with you :)

I can't mark this thread as resolved myself, though...

2020-07-25 08:47 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
I tend to agree with @Sorunome here. This MSC should explicitly forbid event IDs on their own, until that is something that can be relied upon. Standalone event IDs don't really mean anything currently.

As for complicating client implementations, I don't think it's necessarily the case, but this is out-of-scope here, as I think this MSC should be clarified to forbid event IDs not being in a subpath.

2020-07-25 09:17 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +Putting the whole id to the URI fragment (`matrix:#id_with_sigil` or,
Well, if your user name was a hypothetical `@u/se#r:example.com`, the above text would require it to be linkified as `matrix:/@u%2Fse%23r:example.com`, or `matrix:/%40u%2Fse%23r%3Aexample.com`. Existing parsers should return exactly the same parsed string, which is the decoded user name. Web browsers tend to URL-encode as little as possible, as I did with my first example.

For the sake of completeness, the current MSC states it should be `matrix:user/u%2Fse%23r:example.com`

I also think that sigils are useful for:
* Human-friendliness: very different from the rest of the string, easy to recognize
* Compactness
* Consistency with regular matrix identifiers and the way they are written down in the rest of the ecosystem
* Language-neutrality

So [percent-encoding sigils breaks the purpose of sigils](https://matrix.to/#/!pJwzQQUCraoWtdHmYE:matrix.org/$1595570287884025rBmMS:matrix.org?via=matrix.org&via=m.wfr.moe&via=mayeul.net), by defeating every single one of the above list (except the third, which isn't as compelling as the orhers). We lose consistency, especially if one sigil is encoded but not the others.

One of the takeaways is that URIs are primarily useful as a stateless identifier of a given resource. This is most useful for computers, less so for humans. [Clients should probably use a more human-friendly representation than the raw URIs](https://matrix.to/#/!pJwzQQUCraoWtdHmYE:matrix.org/$15955876079lijXH:foad.me.uk?via=matrix.org&via=m.wfr.moe&via=mayeul.net), which releases the constrains a bit (@KitsuneRal, how about specifying this as a SHOULD?). Humans would only occasionally deal with raw URIs, so while they still need to be understandable, this isn't the main constrain either.

2020-07-25 09:21 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +   b. If `query` contains one or more items starting with `action=` - treat
Thank you for the clear explanation, I understand it better now, and adjusted the suggestion accordingly.

This is probably worth adding to the MSC body. I'll likely end up sending you a few PRs.

2020-07-25 09:43 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +Putting the whole id to the URI fragment (`matrix:#id_with_sigil` or,
`/` is an unfortunate allowance in user IDs. And [MSC1597/8](https://github.com/matrix-org/matrix-doc/pull/1598) proposes to remove it, and I'm strongly in favour of that, too.

The problem with url-encoding is that we have basically two identifier classes that are supposed to be human-readable/friendly, and specifically `#` is a monkey wrench that happened to be thrown in this wheel. I think that we have to decide whether we really want to keep URIs for human-readable identifiers also human-readable, or we don't care. If we don't care, `matrix:` can be just a prefix to a percent-encoded identifier, even without the leading `/` to denote the path (modulo the query part). This MSC tries to care about human readability of URIs overall so it doesn't consider `matrix:/%23matrix:matrix.org` as a desirable form for the most popular/populous room in Matrix.

2020-07-25 09:45 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +Putting the whole id to the URI fragment (`matrix:#id_with_sigil` or,
> / is an unfortunate allowance in user IDs. And MSC1597/8 proposes to remove it, and I'm strongly in favour of that, too.

legacy legacy mxids.....heh, sadly there are already quite a few people with `/` in their mxid, and thus we will have to deal with that indefinitely. Just like we have to deal with uppercase mxids.

The other points of destroying the human-readability of sigils is appropriate, though

2020-07-25 09:52 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
I'm afraid the whole question of whether event ids can be resolved out of room context or not is a bit out of scope here. Let's focus on the general framework that would accommodate a wide variety of identifiers here, and leave the discussion of globally unique event ids to [MSC2695](https://github.com/matrix-org/matrix-doc/pull/2695).

2020-07-25 09:53 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
As it is out-of-scopoe here this MSC should explicitly forbid globally-unique-event-ids for now, as that is how things have been in the past. Else we accidentally introduce something new without proper discussion.

2020-07-25 10:11 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +Putting the whole id to the URI fragment (`matrix:#id_with_sigil` or,
> This MSC tries to care about human readability of URIs overall so it doesn't consider `matrix:/%23matrix:matrix.org` as a desirable form for the most popular/populous room in Matrix.

My point is that even if we decide that we don't care about human-readability, there would be almost no advantage to the encoded version (yeah, implementation would likely save one or two lines of codes, but that's negligible complexity). So the readable option is likely better if it comes at virtually no cost. Otherwise, favor the computer-readable and interoperable version.

2020-07-25 10:20 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +Putting the whole id to the URI fragment (`matrix:#id_with_sigil` or,
> Well, if your user name was a hypothetical `@u/se#r:example.com`

That's actually an invalid user id, as per the current [spec](https://matrix.org/docs/spec/appendices.html#user-identifiers). User identifiers are actually very well specified, the only issue being the `/` character mentioned above. With regards to `/`, since these are legacy ids, I guess those folks will have to memorise that `/` is `%2F` in URIs because it's too much disruption to attempt to keep `/` unencoded as soon as we go beyond purely client-side handling of URIs.

Formally, it's MUCH worse with room aliases: the thing is, they are supposed to use a much wider alphabet, and [MSC1608](https://github.com/matrix-org/matrix-doc/pull/1607). However, the established practice is such that room aliases are _mostly_ using the reduced alphabet, closer to that of user ids - hence my concerns around `#` turning to `%23`. Now that I revisited that, I start thinking that trying to keep room aliases unencoded in URIs would actually hamper internationalised room aliases. Respectively, URIs would have to be handled as a means of machine integration, and we'll have to accept the fate web browsers accepted (the way they recode URIs in the address line is beyond my comprehension).

> One of the takeaways is that URIs are primarily useful as a stateless identifier of a given resource. This is most useful for computers, less so for humans. [Clients should probably use a more human-friendly representation than the raw URIs](https://matrix.to/#/!pJwzQQUCraoWtdHmYE:matrix.org/$15955876079lijXH:foad.me.uk?via=matrix.org&via=m.wfr.moe&via=mayeul.net), which releases the constrains a bit (@KitsuneRal, how about specifying this as a SHOULD?).

Yeah, makes sense in the context of the above. Doesn't solve the `#` issue though - we may get genuine URI fragments in the future so we can't keep `#` unencoded.

2020-07-25 10:40 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +  `matrix:room/internalroom:internal.example.org`. This can only be resolved by a client connected to the appropriate server, likely internal.example.org in this case, so it can be hinted at: `matrix
Broken link.
```suggestion
  `matrix:room/internalroom:internal.example.org`. This can only be resolved by a client connected to the appropriate server, likely internal.example.org in this case, so it can be hinted at: `matrix:room/internalroom:internal.example.org&via=internal.example.org`. See the [Discussion points and tradeoffs](#discussion-points-and-tradeoffs) section.
```

2020-07-25 10:58 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
I'm afraid "out of scope" means "doesn't deal with": neither allowing, nor forbidding. Note that the text here should survive any outcome of MSC2695 - either acceptance or rejection.

2020-07-25 12:33 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +`group`; and the only `query` defined for now is `action=join`. The Matrix
The comment regarding `action` is now incorrect since the MSC now also proposes `action=chat`. Perhaps it's best to remove the comment regarding `query` at this point in the document?

2020-07-25 12:38 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +and Matrix resources can be contained in each other, in which care the
Typo.

```suggestion
and Matrix resources can be contained in each other, in which case the
```

2020-07-25 12:46 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +with `type` being one of: `user`, `room`, `roomid`, `event` and
Observation: the wording here does seem to imply that `event` is allowed as the top-level type.

2020-07-25 12:50 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +1. The following classes MUST be supported:
Classes of what? Perhaps this should be changed to "entities" so that it is consistent with the wording used in point 4 of the previous list.

I also remember someone in the MSC room referencing this part when complaining that it allows top-level event references. This change would make it obvious that we are simply saying here that Matrix URIs should have the ability to (somehow) refer to all of these Matrix entities and not prescribing how it is done.

```suggestion
1. References to the following entities MUST be supported:
```

2020-07-25 13:04 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
I also tend to agree the MSC currently reads as if leaning (perhaps unintentionally) toward the acceptance of MSC2695 (especially due to [this part](https://github.com/matrix-org/matrix-doc/pull/2312/files#r460401772)). Perhaps we should add a comment like this in that part?

> Whether `event` is allowed as the top-level `type` depends on the resolution of MSC2695.

2020-07-25 13:08 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
Sounds like this MSC is blocked by MSC2695, then? If no clear wording is added.

2020-07-25 13:23 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
I would rather not see this blocked, if possible. Also, I just saw [this](https://github.com/matrix-org/matrix-doc/pull/2312/files#diff-27c668f5e5f8213c7d8531cea9bf1932R464-R465) (lines 464 and 465) which already raises the concern about bare event references pretty explicitly. This in turn makes me think the part I linked to in my previous comment is just an oversight.

2020-07-25 13:24 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +1. _Why type specifiers use singular rather than plural
Nitpick: grammar.

```suggestion
1. _Why do type specifiers use singular rather than plural
```

2020-07-25 13:29 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +1. _Why event URI cannot use the fragment part for the event id?_
Nitpick: grammar.

```suggestion
1. _Why can an event URI not use the fragment part for the event ID?_
```

2020-07-25 14:45 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
> I would rather not see this blocked, if possible

then it sounds like it isn't blocked by the MSC but by the discussion on the uniqueness of event IDs.

> Also, I just saw this (lines 464 and 465) which already raises the concern about bare event references pretty explicitly

also raised that issue in said MSC, as that needs proper discussion.

2020-07-25 14:59 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +and Matrix resources can be contained in each other, in which care the
I have reworded the entire paragraph, will push the changes. Thanks for spotting anyway.

2020-07-25 15:00 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +`more type/id pairs` series is used to reconstruct inner identifiers.
I rephrased - please see if that is less confusing now.

2020-07-25 15:25 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
Lines 464 and 465 are in the "Future evolution"; it's a collection of ideas, not a normative section. Rather, please check the reference algorithm: it's very explicit on where the current proposal expects `event` and where it doesn't, _as of now_. Now, the section this thread is bound to is a section about _requirements_ for URIs. I don't see any merit in a requirement "URIs MUST NOT include top-level event ids" - top-level event ids are not a security mishap that has to be prevented. Please take your sword elsewhere.

Also - this is exactly the kind of discussion worth taking to the Matrix room. It's already too verbose for the PR thread. We can put the summary to the "Discussion points" section once we're through.

2020-07-25 15:48 UTC, Sorunome commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
> Lines 464 and 465 are in the "Future evolution"; it's a collection of ideas, not a normative section.

which is why this comment was not on those lines

> it's very explicit on where the current proposal expects event and where it doesn't, as of now.

Where do you take that from? It seems to soru that that is actually not what the MSC says on how the path is defined. It appears to allow top-level events
```
path = type “/” id-without-sigil [“/” path]
type = “user” / “roomid” / “room” / “event” / “group”
id-without-sigil = string ; see below
```

> I don't see any merit in a requirement "URIs MUST NOT include top-level event ids" - top-level event ids are not a security mishap that has to be prevented. Please take your sword elsewhere.

The spec is supposed to make sense and be consistent. With that argument we should also merge the EDU-to-PDU events into the spec without second-thinking them

> Also - this is exactly the kind of discussion worth taking to the Matrix room. It's already too verbose for the PR thread. We can put the summary to the "Discussion points" section once we're through.

And noone seems to have checked the other thread mentioned on the top of this one where exactly the global uniqueness.
Not everyone is in that room, so not everyone can partake in a discussion. If you want to discuss the global uniqueness of event IDs in a matrix rooms, the spec room seems way more appropriate. Where that exactly happened multiple times already. And the consensus was always room-unique IDs.

2020-07-25 15:59 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
@KitsuneRal, I'm not sure who you are responding to, but I think there might have been a misunderstanding: I mentioned 464-465 to show the MSC is clearly talking about bare event references as something for the future, not something happening now. No sword here.

In any case, I agree this is better discussed in the room so we can continue there if necessary.

2020-07-25 17:40 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +   1. Event IDs (`$arbitrary_eventid_with_or_without_serverpart`)
The note about the sword was more to @Sorunome who seems to insist I have to insert some text forbidding globally-unique event ids around this area. If not, I'm not sure what this conversation is about.

> > it's very explicit on where the current proposal expects event and where it doesn't, as of now.

The parsing algorithm section I was referring to starts from [line 279](https://github.com/matrix-org/matrix-doc/pull/2312/files#diff-27c668f5e5f8213c7d8531cea9bf1932R279).

> It seems to soru that that is actually not what the MSC says on how the path is defined. It appears to allow top-level events
> 
> ```
> path = type “/” id-without-sigil [“/” path]
> type = “user” / “roomid” / “room” / “event” / “group”
> id-without-sigil = string ; see below
> ```

Ah, now I see where your concern stems from; probably this thread should have been there. This grammar intends to show the generic recurrent structure of `path`. Formally it allows many non-sensical things, e.g., room-in-user-in-roomid; but the text just after the grammar discusses it, and also touches exactly the case you're concerned about. As the intention is to lay down extensible foundation, I'd still prefer to keep the grammar this way but probably will move out the list of values for `type` as it doesn't actually belong to that extensible foundation. Hope this will make it less confusing.

> > I don't see any merit in a requirement "URIs MUST NOT include top-level event ids" - top-level event ids are not a security mishap that has to be prevented. Please take your sword elsewhere.
> 
> The spec is supposed to make sense and be consistent. With that argument we should also merge the EDU-to-PDU MSCs into the spec without second-thinking them, as they aren't security mishaps.

Sorry but the analogy is so stretched that I cannot get it. 

> > Also - this is exactly the kind of discussion worth taking to the Matrix room. It's already too verbose for the PR thread. We can put the summary to the "Discussion points" section once we're through.
> 
> And noone seems to have checked the other thread mentioned on the top of this one where exactly the global uniqueness.

That's not a reason to pull that discussion here though. I'm well aware of that other thread. I don't have strong opinions on globally unique event ids so I don't comment there.

> Not everyone is in that room, so not everyone can partake in a discussion.

I don't see many who desire to partake in the discussion here; the room is public and a link to it is now in the PR description.

> If you want to discuss the global uniqueness of event IDs in a matrix rooms, the spec room seems way more appropriate. Where that exactly happened multiple times already. And the consensus was always room-unique IDs.

That's exactly the thing: I **don't** want to discuss that topic **here**. This MSC has nothing to do with that _discussion_. If MSC2695 gets accepted before this one, I'll refresh it accordingly. I don't see what else to discuss here.

2020-09-24 07:26 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +The classes of URIs and corresponding default actions (along with relevant
Coming back to this - it turns out that [RFC 7595 quite clearly recommends](https://tools.ietf.org/html/rfc7595#section-3.4) to specify both applicable operations on URIs and the a "default" operation - which is effectively what this part describes. So I tend to turn it to normative rather than put away to an appendix.

2020-09-30 06:02 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +Putting the whole id to the URI fragment (`matrix:#id_with_sigil` or,
I retargeted URIs as a tool for (primarily) integration rather than representation. The URI scheme design didn't change though: I still believe that sigils are not too scalable, and on the other hand, a separate MSC can introduce something like `matrix:id/` that would encode sigils rather than replace them with words.

2020-10-01 16:44 UTC, KitsuneRal commented
I tried to address all review comments as much as possible - feel free to have another review round.

2020-10-16 18:47 UTC, timokoesters commented on proposals/2312-matrix-uri.md
> +Examples:
Would something like a link to register on a homeserver make sense? If I want to tell a friend to register on my homeserver, I currently have to tell him to open a matrix client and click on the right buttons to customize the homeserver url. It would be nice to do that with a single link that works across multiple applications.

2020-10-17 18:23 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +Examples:
Well, there are quite a few assumptions here - specifically that a friend already uses Matrix, _and_ that they won't mind getting another account, rather than converse with you using their existing account, _and_ they are prepared that their current client might log them out from their current account because it doesn't support multiple accounts (looks sullenly at the whole Element family).

What would be absolutely terrific to have is a register link at a given homeserver for those not yet on Matrix - but that has to be an `https:` in order to get to registration in as few clicks as possible. Something like going to a special page (matrix.to?) that serves platform-specific links for all major clients, with native clients having a pre-configuration mechanism to fill the homeserver... ok, I got carried away. In any case, I don't quite see how the dedicated Matrix scheme would help with bootstrapping of any sort; and adding yet another Matrix account is questionable in general and very inconvenient with most-used client applications.

2020-11-29 22:36 UTC, CodingAnonymous commented
Any news?

2020-12-18 13:13 UTC, richvdh commented on proposals/2312-matrix-uri.md
> +non-id-segment = segment-nz ; as defined in RFC 3986, see also below
```suggestion
nonid-segment = segment-nz ; as defined in RFC 3986, see also below
```

2020-12-18 13:15 UTC, richvdh commented on proposals/2312-matrix-uri.md
> +- the name of the item MUST follow the reverse-DNS (aka "Java package")
Maybe refer to #2758 here?

2020-12-18 13:22 UTC, richvdh reviewed
I've not grokked the full text of the "Implementation" section, and I'm not an expert in the URI syntax RFCs, but generally this proposal seems excellent.

2021-01-19 17:45 UTC, uhoreg commented
Looks plausible to me

2021-01-19 19:13 UTC, KitsuneRal commented
With ample time given to discuss alternatives and incorporate adjustments, as well as several client-side implementations existing by now (Quaternion, FluffyChat and Nheko at least), this should be quite ready for FCP.

@mscbot fcp merge

2021-01-19 19:17 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +  CS API means.
What is the difference between this and no action on room links? Should the user not be prompted to join the room in the latter case?

2021-01-19 19:32 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
From the UI interaction perspective, the difference may be when a room with guest access allowed can be opened without joining it. In that case, `matrix:room/forguests:example.org` would simply open that room in the client of choice without actually joining it; and `matrix:room/forguests:example.org?action=join` would prompt the client to actually join the room (after confirming with the user). For rooms that don't allow guest access, clients would likely suggest joining the room for both URLs since that's pretty much all they can do about the room referred to.

2021-01-19 20:11 UTC, uhoreg commented on proposals/2312-matrix-uri.md
> +  CS API means.
Do you mean peeking/preview instead of guest access?

2021-01-19 20:28 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +  CS API means.
I think it would make sense to document some guidance on how clients should behave and when they should generate which kind of action. Since Nheko doesn't support previewing rooms, I'll just prompt to join in either case.

2021-01-19 20:40 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
@uhoreg, sorry, right, it's not about guest access actually, it's about public access.

@deepbluev7, the MSC [documents it](https://github.com/matrix-org/matrix-doc/pull/2312/files/43e6470acae6f43c09f05dda239f61ccee3efbed#diff-f4ae31b823cdbeac105bd4b6526b3da8f6db03ae29847e1c7916b9ac51997fdfR403); but the suggested operations are a SHOULD, not a MUST.

2021-01-19 20:45 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +  CS API means.
Hm, I guess when I read that section, I did not understand that. It is a bit short and does neither mention what to do with action=join, when you are already joined to the room, nor does it mention previewing, when there is not action=join. I guess you can interpret it correctly, but when I implemented it, I did not understand why there was an action=join at all, because I saw no valuable distinction. As such I think elaborating that section a bit in the final spec may be valuable.

2021-01-19 20:47 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
Apparently the section has some left-overs :-\ the idea is conveyed though.

2021-01-21 11:04 UTC, MayeulC commented on proposals/2312-matrix-uri.md
> +  CS API means.
Hmm, I [expressed doubts](https://github.com/matrix-org/matrix-doc/pull/2312#discussion_r331472489) about this action, and I am still unsure if it's really useful: it really looks like an implementation detail (from a join button in Element, for instance).

I don't think clients should perform any action without user confirmation, but this can serve as a hint of what to perform with a given resource.

2021-01-21 11:18 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
> It is a bit short and does neither mention what to do with action=join, when you are already joined to the room,

I'd say it entirely depends on what your client usually does in such situation (e.g., if a user typed `/join #alreadyjoined:matrix.org` as a command, what do you do?). Clients may check their records; or they may just blindly call `/join` API (advised in the table), get 200 (or 201, or 204, or even 304 - whatever the future spec would say) and act accordingly. The client application might not even be aware that the user has already joined the room, because it never ran `/sync`, e.g. That's not something this MSC should codify as it has nothing to do with URIs; it's the context within which it operates.

> nor does it mention previewing, when there is not action=join.

First off, there's no particular API in the spec for room _previewing_ as of now; you can get an event from a public room without joining it using the same API as if you were a member. But the point here is that, again, this MSC cannot assume that the client knows a priori about the user's member state in the given room. I'd really prefer to stay away from prescribing behaviour in all the cases like "what if there's `action=join` and the client knows the user is banned from the room?" or "what if there's no `action=join` and the client doesn't know anything about the member state of the user in the room?". These questions are equally applicable without the concept of URIs. The MSC specifies a mechanism to turn a URI to an identifier + requested action pair; it's ultimately up to the client what it can do with this identifier and this request.

> As such I think elaborating that section a bit in the final spec may be valuable.

I can add a comment reiterating on the distinction between the two cases; but as I said, I'd prefer to stay away from directing clients to some specific mode of operation. Not all clients are supposed to act on all Matrix URIs, in the first place (think of off-screen clients, including bots, e.g.). Therefore I try to focus on describing the abstract semantics of a particular URI form, that is, in this case:

- a URI to a room with no query component simply _identifies_ that room;
- a URI with `action=join` in the query means that a user agent should perform that action, with certain precautions.

The rest is up for interpretation within a particular context.

2021-01-21 13:38 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +  CS API means.
Seems to me that actions are a whole topic, that "join" is just the first action that anybody thought of and is only the tip of the iceberg of useful actions (room: join, leave, change settings, compose message, ...; event: compose reply, redact, ...; etc.). Seems to me having this "join" in this MSC is an ugly wart and it should be excluded and a separate MSC should be opened to specify actions.

2021-01-21 19:47 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +  CS API means.
> I can add a comment reiterating on the distinction between the two cases; but as I said, I'd prefer to stay away from directing clients to some specific mode of operation.

Yeah, I agree. Just a short explanation of the original rationale, why the action was added would be good enough. So that clients are aware, that in some circumstances they may be handled differently. On the other hand, this MSC discussion may already be enough for that, if someone is looking to find out.

> Seems to me having this "join" in this MSC is an ugly wart and it should be excluded and a separate MSC should be opened to specify actions.

I disagree. While my client does not really have a good way to do different stuff on join, I think it has some merit (after @KitsuneRal explained it). The "chat" action is also very useful. Maybe there will be other actions in the future, but the current set seems sensible and useful in at least some instances.

2021-01-22 14:31 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
@julianfoad, I don't see how it is an ugly wart, tbh - it follows the higher-level conventions, and it doesn't look different in nature to `action=chat`. Seems like a matter of perception?

2021-01-22 15:07 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +  CS API means.
@KitsuneRal it's a matter of separation of concerns. Perhaps I shouldn't have used such strong language; but it is an oddity defining just one action for a room within this MSC (and "chat" for a user, which I overlooked but doesn't change my argument), when we already know there will be other useful actions (as suggested in "Further evolution" section), and these are just the tip of the iceberg of useful actions. Hasn't it been shown time and again that small clean specs work better? From today's perspective it might be said "these two actions are already in use so it would be nice to codify them" but from a perspective a few years later it is not unlikely to look like "the section defining two actions in the original MSC2312 is obsolete and superseded by MSCxxxx". And that would make for ambiguity in deciding whether certain implementations comply with this MSC. Would it not be better to leave actions out of this MSC entirely and (quoting from this MSC's text) "further MSCs may introduce additional operations enabled either by passing an action value in the query part..." so do this all in further MSC(s)? "Further evolution" begins "This MSC is obviously just the first step"; let's make it a crisp clean one?

2021-01-22 15:34 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
I totally understand your point; it's like this MSC throws in a design idea but then stops short of completing it. The rationale behind that was to provide a proof of concept, while giving others (you, for example ;) ) the opportunity and the means to draft simple, short MSCs building on top of that foundation and even reusing parts of the MSC language. I could do it in a separate MSC but given that the whole query thing is a part of the same underlying RFC, I thought I'd rather give a feeling of what can be done with the scheme right here. Were I not to do it, implementations probably wouldn't even try to do actions; but now the ice is broken and further steps are easier. And if I split actions to a separate MSC now, I would call FCP on it immediately anyway because it's better to have many smaller MSCs than a bulky one for all the actions that would be harder to pass and implement.

I'm a bit disappointed I could not lay the foundation in the same way for the authority part - but that part proved to be controversial enough that it was better to drop it. Queries are not that controversial, on the other hand - at least the discussion did not reveal that.

And I'm absolutely fine to have pieces of this MSC be obsoleted in a few years - we have to start somewhere (heh, we should have started a couple years ago), and then evolution ftw.

2021-01-22 15:46 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +  CS API means.
I like your attitude while I don't like those bits being normative. How about marking the actions sections as non-normative?

2021-01-22 16:53 UTC, julianfoad commented on proposals/2312-matrix-uri.md
> +  CS API means.
I hear you. I've said what I wanted to say; I'll leave it to you and the others now.

2021-01-22 17:00 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
Thanks for expressing the opinion.

2021-01-22 19:00 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +  CS API means.
@deepbluev7, I added the clarification.

2021-01-23 00:02 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +  CS API means.
Lovely, thanks!

2021-02-17 04:44 UTC, turt2live approved these changes
This looks incredible - thank you for taking the time to work on it!

2021-02-17 05:25 UTC, ara4n commented
This MSC is a work of art :) My only remaining input is:

a) it scares me that we have no way to say "if you don't have a Matrix client, you should default to this branded instance" (which we used extensively for FOSDEM).  it also lacks "you /have/ to use this matrix client to access this homeserver" semantics (for private federations, where you may need to use a webclient on the same network as the server). These aren't client-specific params so can't be handled by rDNS query params but need to be specced, same as the webinstance param on matrix.to.

b) i prefer the aesthetics of reddit style matrix:u/matthew:matrix.org to matrix:user/matthew:matrix.org. I think it's because:
  * user/matthew makes it look like the word user could be part of the identifier somehow, whereas u/ is very clearly a not-an-english-word
  * u/ is shorter and closer to the familiar sigils
  * reddit has set a strong precedent for users to recognise it as a prefix. in other words, my brain reads it as `@matthew:matrix.org` whereas somehow user/matthew:matrix.org reads as "user matthew", which feels impersonal and cold.

So, at the least, can we include u/ and r/ and i/ and e/ as official abbreviations to user/ room/ roomid/ and event/?

Neither of these things are showstoppers for FCP though, but please can we incorporate them before FCP finishes?

2021-02-17 05:31 UTC, ara4n commented
i also think we may regret not having a way to say: "this url only works if you are connected to this hs", for private federations. this is different to the via param, which says which server your server should join via; instead it's more a force_hs=unfederated.example.com if you know this the url is only going to work if you're on a given private server.

2021-02-17 05:54 UTC, ara4n commented
for setting defaults and overrides, possible querystrings could be:

default_client=https://chat.fosdem.org
(and we mandate that all webclients must parse matrix uri parameters at their root, so chat.fosdem.org/u/matthew:matrix.org will do the right thing). This would supplant matrix.to's current web-instance[] query param.

matrix.to could then be defined as the implicit default client for folks who don't have one installed (passing through the uri params), which feels very nice as fallback.

Finally, a native app vendor could put up a "install the app!" landing page at https://quaternion.com and set it as the default_client in the URL (which could then deeplink into the app once installed). This avoids having to spec how to deeplink directly to random native appstores in the matrix URI scheme.

Seperatelt:

require_hs=matrix.example.local
require_client=https://element.example.local

^ would let unfederated servers on private networks work, or servers which restrict the client codebases which are allowed to connect for policy/security reasons.

2021-02-17 10:42 UTC, ptman commented
> So, at the least, can we include u/ and r/ and i/ and e/ as official abbreviations to user/ room/ roomid/ and event/?

Is it really worth having two different but equivalent versions of the URI? Which one is the canonical one?

2021-02-17 11:14 UTC, dkasak commented
I'm also of the mind we want to avoid multiple forms here and just choose one. Having multiple forms will increase the burden on implementations with no (to me) obvious gain. I'm personally fine with using the shorter prefixes, though.

2021-02-17 11:21 UTC, paulvt commented
> i also think we may regret not having a way to say: "this url only works if you are connected to this hs", for private federations. this is different to the via param, which says which server your server should join via; instead it's more a requires_hs=unfederated.example.com if you know this the url is only going to work if you're on a given private server.

I interpreted the required HS as the authority in this particiular case, because that HS is the only HS that has that room/user/etc. compared to the federated case where there is no authority. Also described in https://github.com/quotient-im/matrix-doc/blob/kitsune/matrix-uri/proposals/2312-matrix-uri.md#authority and case matrix-org/matrix-doc#2309. Am I confused here?

2021-02-17 14:17 UTC, MayeulC commented
I'm leaving this idea ([first written here](https://matrix.to/#/#uri-scheme-proposal:matrix.org/$161357008567ntEAE:mayeul.net))here as a comment, though it would flip the MSC on its head, which is not really the right time:

If everything is going to become a room: user profiles (#1769), spaces (#1772), rooms, etc, why not drop the `{r,u,i,e,*}` qualifier altogether?

Advantages:
* Simpler URLs
* No more arguing about sigils vs letters vs names
* Everything works

Drawbacks:
* No telling the type at a glance (either for a user or client)
* Delayed support in clients until the MSCs are accepted
* Less extensible.

This may very well be a bad idea mind you, the extensibility we lose is hard to make up for.

---------

Passing comment on roomid: using `i` isn't really explicit. I'd suggest using `r/!actualid` instead. As a bonus, this leaves `i` for future use (image to partially replace mxc?)

2021-02-17 17:03 UTC, KitsuneRal commented
I'll start with the one less controversial.

> b) i prefer the aesthetics of reddit style matrix:u/matthew:matrix.org to matrix:user/matthew:matrix.org.
> [...]
> So, at the least, can we include u/ and r/ and i/ and e/ as official abbreviations to user/ room/ roomid/ and event/?

Including them as official abbreviations LGTM. The MSC discusses the use of Reddit style as an alternative, pointing out potential(!) ambiguity in a very long run as the only disadvantage. I personally feel though they are a bit less readable; however, on the other hand, they are better in _writeability_ (typing `r/` before the sigil-less room alias is easier than `room/` - "or wait, is it not `rooms/`, just in case?") and don't raise localisation questions, which is a rather strong argument.

Using `i/` for room ids is more ambiguous than other abbreviations - in theory, it could mean "any id". It's also worthwhile to make a clearer distinction between room aliases and room ids in the absence of aliases - so, as discussed elsewhere, `roomid/` is here to stay.

Re: one vs. two notations: I tend to agree that having two notations is ambiguous in itself ("which one is canonical?" has no intuitive answer, in my perception; hence authors will have to refer to the spec) and also adds (but honestly, negligibly low) maintenance burden. So I think of using the Reddit style as the only one, despite the fact that several implementations already took the current style. Discussion in [the MSC room](https://matrix.to/#/#uri-scheme-proposal:matrix.org) converged on the same.

2021-02-17 17:08 UTC, KitsuneRal commented
> I'm leaving this idea ([first written here](https://matrix.to/#/#uri-scheme-proposal:matrix.org/$161357008567ntEAE:mayeul.net))here as a comment, though it would flip the MSC on its head, which is not really the right time:
> 
> If everything is going to become a room: user profiles (#1769), spaces (#1772), rooms, etc, why not drop the `{r,u,i,e,*}` qualifier altogether?

First off, it's only going to, and we don't know where it lands; and second, more important, it's really important to distinguish between, e.g., users and rooms visually in the URL since actions on the resources are different, let alone the distinction between room ids and room aliases that won't go anywhere.

2021-02-19 22:21 UTC, KitsuneRal commented
@mscbot concern setting overrides and defaults needs more discussion

2021-02-20 17:21 UTC, KitsuneRal commented
@mscbot fcp cancel

since the bot doesn't do it automatically.

2021-02-23 02:13 UTC, kevincox reviewed
I have a major concern about security of the action parameter. I don't think the URI will be able to be adopted widely if it can perform actions with just a click.

I'm also kinda sad that `roomid` is spelt out as I share private rooms (without a "name") more often than public ones and a room is very fundamental to matrix so it seems worth using some of the single-letter space for it to me. But I don't think this is blocking especially as it can be added later without too much difficulty.

2021-02-23 08:18 UTC, ShadowJonathan commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
I think actions would need to open a dialog option inside a client with a yes-no option, to allow users to opt-out of the action if they want. Would what work better?

2021-02-23 08:39 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
It was certainly my understanding that it was a requirement for clients to show a confirmation dialog before executing any of the actions. See this sentence earlier in the MSC:

> For both actions, where applicable, client applications SHOULD ask for user confirmation or at least notify the user before joining or creating a new room.

Though I now note that it gives the choice between asking for confirmation and notifying, and the use of `SHOULD` instead of `MUST`, so perhaps I projected my expectations a bit too much. In any case, I agree that it is absolutely necessary for a client to have to ask for confirmation before executing an action from an URI.

2021-02-23 10:10 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +a series of CS API calls, entirely on the client side. It is recognised,
It's a very well-known part of the specification; but ok, I'll make it a link.

2021-02-23 10:13 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +It is proposed to use the routing query to be used not only for resolving
This will be rewritten in the light of the [suggested reinstatement](https://github.com/matrix-org/matrix-doc/pull/2312#issuecomment-780320011) of dedicated query parameters for closed federations (see also #3020).

2021-02-23 11:46 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
> Clicking a URL should be "safe". It shouldn't perform any "interesting" action without user confirmation. I don't think that clicking a link with `?action=chat` should create a room as that action is visible to the referenced individual which could be undesirable.
> 
> Instead I would say that the client should bring up a compose UI to that user, but there should be no actual indication sent to the recipient until the user explicitly performs something.

First off, that's not how the Matrix protocol is designed. You cannot compose and send a message to some user before inviting him to a room. Any conversation (even the initial message) can only occur within a room.

> Similar to `?action=join` it should not join the room but bring up UI optimized for joining.

Clients can be different and contexts can be very different too. Some clients simply don't have the means to notify a user because they work off-screen; some may assume that the user knows what they are requesting (e.g. in `curl`-like context); etc. Hence SHOULD. See also https://github.com/matrix-org/matrix-doc/pull/2312/files#r561796343 to get an idea of the diversity tackled.

Consider also that, drawing parallels with WWW, you probably wouldn't want your web browser to ask every single time whether it is your actual intention to follow some HTTPS link (for better or worse).

> As a rule any URL should not map to a POST request as that is likely doing something with a side effect.

I'm afraid you're conflating the URI specification and the HTTP(S) protocol. By definition URL/URIs _identify_ the resource and the action (query) on it; even if it's an HTTPS URL, requesting it may mean a state change on the other side. E.g, `https://example.org/login?user=me&password=secret` can be a perfectly valid URL for some `example.org`, "mapping" to `POST /login?user=me&password=secret` because GET is plain invalid for it; this URL conveys the _intention_ to perform the action.

Earlier revisions of the MSC included an explicit discouragement from using URIs that include `action=join` in "reference" cases (information on web pages etc.); after discussing in the community, that has been removed as (in particular) falling outside of the MSC remit: people who draft those pages are not expected to read this MSC, or the spec even.

> If matrix URLs are made "unsafe" as proposed here they will never be able to be made clickable by default which will seriously impact the benefits of these URLs. I want to be able to use `matrix:` URLs everywhere I can use `mailto:` or `https:`

`https:` links are, of course, always safe :-\ I understand the motion but sorry, WWW has proven that you always must check the links you're clicking on. The MSC expects client authors to understand and, where reasonable, facilitate that (with confirmation dialogs etc.)

2021-02-23 12:33 UTC, kevincox commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
> @dkasak and the use of SHOULD instead of MUST

I think changing to MUST (and maybe even being explicit about how trustworthy a link click should be treated as) would solve the issue.

I think we should also consider removing the "non-interactive option" from this table if it is "unsafe".

> @KitsuneRal You cannot compose and send a message to some user before inviting him to a room.

That may be how the underlying protocol works but the client can hide this with UX. Inviting someone to a room isn't the *worst* information leak but I still think it should be avoided as it could be intentionally embarrassing at the least and possibly even more harmful to the user.

> I'm afraid you're conflating the URI specification and the HTTP(S) protocol.

You are right. What I am trying to say is the reason that the browser feels safe to follow URLs with GET requests is because it is expected that doing so is safe. There is very limited ways to use different methods or set headers and similar from URLs so that sites can reasonably defend themselves.

> https: links are, of course, always safe :-\

Unfortunately they are not always safe. But this is considered a security vulnerability in the website if they aren't. ([CSRF](https://owasp.org/www-community/attacks/csrf) I don't want to add a CSRF vulnerability into the protocol. Especially because if we do browsers and other interfaces will never allow matrix links to be opened with a single click.

2021-02-23 13:22 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
> I think changing to MUST (and maybe even being explicit about how trustworthy a link click should be treated as) would solve the issue.

I think @KitsuneRal has a valid point against the change to MUST. The spec shouldn't make specialized, headless clients non-compliant.

On the other hand, it seems to me that in the case of normal, user-oriented, interactive clients, a compliant client should be required to always ask for confirmation (not just notify). Phrased a bit differently, I do not think there is a reasonable scenario where a *click* on a `matrix:` URI should lead to an automatic execution of the action. Do we all agree with that? Am I missing something?

2021-02-23 13:30 UTC, ShadowJonathan commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
I agree with that, a click can be hidden and redirected behind other clicks or links inside words, so anything that comes from that, and a client hooking into `matrix:` to receive those calls, shouldn't automatically execute "write" actions like that. (read actions are still iffy tho)

2021-02-23 14:22 UTC, kevincox commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
> I think @KitsuneRal has a valid point against the change to MUST

Maybe the wording should be changed to keep it SHOULD but be very specific about how privacy should be considered?

2021-02-23 17:21 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
Before we proceed, I have to point out that specifically this piece of the MSC went through a tiring amount of nitpicking both here and in the Matrix URI room. If you guys are really into changing that piece I'll have to require you to show knowledge of the MSC background (RFC's, in particular) and the prior discussion, which I don't quite see so far.

@dkasak:
> On the other hand, it seems to me that in the case of normal, user-oriented, interactive clients, a compliant client should be required to always ask for confirmation (not just notify). Phrased a bit differently, I do not think there is a reasonable scenario where a _click_ on a `matrix:` URI should lead to an automatic execution of the action. Do we all agree with that? Am I missing something?

You do:
1. "Clicking" the URI is just one very particular way of dereferencing a URI; the MSC is supposed to apply to as wide variety of dereferencing methods as possible.
2. In some cases client applications can legitimately bypass the confirmation and the MSC points out one such case (even though it's tangential to its main purpose): room upgrades.

@kevincox:

> I think we should also consider removing the "non-interactive option" from this table if it is "unsafe".

This is exactly the point where I have to urge you to get more acquainted with past discussions in the Matrix URI room. This option came around because there's a need for it.

> > @KitsuneRal You cannot compose and send a message to some user before inviting him to a room.
> 
> That may be how the underlying protocol works but the client can hide this with UX. Inviting someone to a room isn't the _worst_ information leak but I still think it should be avoided as it could be intentionally embarrassing at the least and possibly even more harmful to the user.

Yes, they can hide this but that's out of scope for this MSC. Clients are recommended to double-check with the user before actually opening the chat - the language with which they do it, the specific flow, supplementary controls if any are all up to them. This MSC does not specify user interaction, it's not its purpose.

> > I'm afraid you're conflating the URI specification and the HTTP(S) protocol.
> 
> You are right. What I am trying to say is the reason that the browser feels safe to follow URLs with GET requests is because it is expected that doing so is safe. There is very limited ways to use different methods or set headers and similar from URLs so that sites can reasonably defend themselves.

Well, that's a bit irrelevant to URIs discussion since URIs are not limited to what you can (or should) type in the browsers address line. You may want to read about [the distinction between identification and interaction](https://tools.ietf.org/html/rfc3986#section-1.2.2).

> > https: links are, of course, always safe :-\
> 
> Unfortunately they are not always safe. But this is considered a security vulnerability in the website if they aren't.

There's more than one facet of safety; URIs may be designed to lead into a trap. The most problematic security vulnerabilities to patch are in the heads by now. But I digress - what I was meaning is that the way `matrix:` URIs are defined now is much more restrictive than how `https:` URIs are defined. If you feel more unsafe to click on such `matrix:` URIs than `https:` URIs, you should look for a better Matrix client application (or make your current one safer), not a better URI specification.

2021-02-23 17:50 UTC, kevincox commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
I agree with what you say. I think the MSC as written doesn't require dangerous behaviour but I think that clarifying this fact is very important as clients are going to be using this as a reference and if it is easy to miss the security concerns here then we will end up with unsafe clients which will hinder adoption. 

For example this section fairly explicitly says that the default action for these URLs with `?action=chat` involves inviting the user mentioned in the URL to a room and `?action=join` specifies that it should join the room. So while it does say earlier in the document that clients should ask for confirmation I think it is worth fixing up this section to be very explicit that the client should carefully consider what to do with actions in untrusted URLs.

>  If you feel more unsafe to click on such matrix: URIs than https: URIs, you should look for a better Matrix client application

I agree. But the spec currently guides towards this behaviour. I think it would be best for the ecosystem if the spec guided towards safe behaviour. And expressing that in cases where it is known to be acceptable the action can be performed automatically.

2021-02-23 21:08 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
You didn't get the key thing - "dangerous behaviour" has nothing to do with the way URIs are constructed.

The ecosystem has been discussing this document over the last 2 years, involving authors of all prominent clients. I think everybody's pretty much on the same page on how they should treat the URIs - the rambling about how clients should act on URIs with care has been specifically in response to the feedback from the community. The current wording in the MSC is clear that precautions should be taken. The Security and Privacy section mentions that as well. If you want to change something, make a PR, share it in the Matrix URI room and discuss it there with others who've been following the saga all along.

2021-02-23 23:56 UTC, dkasak commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
> "Clicking" the URI is just one very particular way of dereferencing a URI; the MSC is supposed to apply to as wide variety of dereferencing methods as possible.

I wasn't implying otherwise, just searching partial agreement in this particular case.

> In some cases client applications can legitimately bypass the confirmation and the MSC points out one such case (even though it's tangential to its main purpose): room upgrades.

Right, that's fair, I forgot about that.

Anyway, I'm signing out of this discussion and I'm satisfied with the conclusion: typical user-oriented clients shouldn't perform the action automatically in an overwhelming majority of cases. There is an edge case where this is allowed, which is room upgrades. Special-purpose clients may execute the action without confirmation, but they should then at least notify the user.

I think such a conclusion could be stated in the MSC somewhere more or less verbatim and it would solve any concerns I had while retaining the same meaning as it has today. However, I'm obviously missing some context and history here, since this MSC is not the primary thing in my focus and I'm not willing to bikeshed it any longer.

2021-03-16 15:51 UTC, erkinalp commented on proposals/2312-matrix-uri.md
> +
Add an answer to "Why not `matrix:user@server/room/event`?

2021-03-16 15:52 UTC, erkinalp requested changes

2021-03-16 15:52 UTC, erkinalp commented on proposals/2312-matrix-uri.md
> +
Add an answer to "Why not `matrix:user@server/room/event`".

2021-03-17 16:07 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +
I haven't seen this suggested in the past, and I don't quite understand - what that string would even mean? I don't grasp the semantics.

2021-03-17 16:20 UTC, erkinalp commented on proposals/2312-matrix-uri.md
> +
I compressed two forms into one: `matrix:user@server` and `matrix:server/room/event`.

2021-03-17 19:42 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +
`matrix:user@server` has no meaning though currently? So even your current explanation doesn't make much sense to me.

2021-03-17 19:51 UTC, erkinalp commented on proposals/2312-matrix-uri.md
> +
@deepbluev7 It will replace `@user:server` form for users.

2021-03-17 20:46 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +
You mean, change the layout of mxid's? I'd say that is out of scope for this MSC and I don't see any benefit there apart from changing stuff for change sake. Especially since one of the goals of this MSC was to avoid sigils in identifiers.

2021-03-17 20:52 UTC, erkinalp commented on proposals/2312-matrix-uri.md
> +
But you do need a sigil to separate user and server.

2021-03-17 23:02 UTC, deepbluev7 commented on proposals/2312-matrix-uri.md
> +
This proposal presents a solution to that already, without introducing much ambiguity.

2021-03-18 09:11 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +
I can only add that I don't see why one would refer to a particular user when referring to an event; and that the whole thing looks terribly similar to `http://user@host/path`, enough to produce massive confusion.

2021-03-18 09:31 UTC, erkinalp commented on proposals/2312-matrix-uri.md
> +
@KitsuneRal BTW the full form `user@server/room/event` would retrieve `event` from `room` at `server` as seen `user`, while still following the authentication rules of the sending user as established by authentication process.

2021-03-18 17:09 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +
I don't understand what you mean by "authentication rules of the sending user"; but first of all, I urge you to read the MSC to the end. There's an explicit out-of-scope statement for any kind of user information in the URI out of security considerations. The track record of that in HTTP/FTP URLs is pretty bad.

2021-03-21 06:16 UTC, erkinalp commented on proposals/2312-matrix-uri.md
> +
@KitsuneRal This is the use case: say, you are user `kitsuneral@matrix.org` but you want to see the room from `erkinalp@matrix.org`'s POV. Then you would supply `matrix:erkinalp@matrix:matrix.org`, while still being authenticated as `kitsuneral:matrix.org` to see the Matrix HQ room as I would see (like, with ignores and notification settings I set). You will still not be able to log in as `erkinalp@matrix.org` without knowing my credentials.

2021-03-23 14:49 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +
Matrix has no such mechanism so you'll have to propose one, before devising a URI notation for it.

2021-03-25 06:35 UTC, alexmingoia commented
[MSC3074: Change URIs to conform to RFC3986](#3074) should be considered alongside this proposal, as they both relate to the future of Matrix URIs.

2021-03-30 10:18 UTC, anoadragon453 commented
@alexmingoia That URL markdown doesn't work I'm afraid. [Link to MSC3074: Change URIs to confirm to RFC3986](https://github.com/matrix-org/matrix-doc/pull/3074).

2021-03-30 17:45 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +It is proposed to use the routing query to be used not only for resolving
Ultimately the rewrite has been left for a separate MSC; but I've made the changes to make the sentence clearer.

2021-03-30 17:47 UTC, KitsuneRal commented on proposals/2312-matrix-uri.md
> +| User Id (`action=chat`):<br/>`matrix:u/her:example.org?action=chat` | Open a direct chat with the user (see the next column on identifying the room) | If [canonical direct chats](https://github.com
In retrospect, I apologise for being a bit obnoxious; I have added a few words to the same effect as @dkasak proposed; and indeed, the "Operations" section should have advised interactive clients to ask for confirmation; it's there now.

2021-03-30 17:48 UTC, KitsuneRal commented
@mscbot resolve setting overrides and defaults needs more discussion

2021-03-30 17:49 UTC, KitsuneRal commented
Overrides and defaults are left for a separate MSC.

2021-04-04 22:46 UTC, merged

2021-12-30 01:09 UTC, turt2live commented
New spec PR: https://github.com/matrix-org/matrix-doc/pull/3608

2021-12-31 05:11 UTC, turt2live commented
Merged 🎉