MSC2400: Add "knock"
matrix-org/matrix-doc pull request #2403
Opened 2020-01-09 18:56 UTC by Sorunome

[Rendered](https://github.com/Sorunome/matrix-doc/blob/soru/knock/proposals/2400-kock.md)

2020-01-12 23:28 UTC, anoadragon453 commented on proposals/2403-knock.md
> +when creating a new room, prevent anyone from knocking.
Can't one just set the required power level to send a knock event to something about the default power level?

2020-01-12 23:35 UTC, anoadragon453 commented on proposals/2403-knock.md
> +      "membership": "knock",
I'd put the `displayname` and `avatar_url` fields here just to show all possible fields for whoever puts this into the spec afterwards.

2020-01-13 11:48 UTC, Sorunome commented on proposals/2403-knock.md
> +when creating a new room, prevent anyone from knocking.
Yes, we could. The join rules could be more easily exposed via UI, however, thus making the PL approach the advanced one while the join rules one is the simple setting, basically.

2020-01-13 11:48 UTC, Sorunome commented on proposals/2403-knock.md
> +      "membership": "knock",
Yes, they are meant to be optional here. Will update the MSC to reflect that better

2020-01-14 02:17 UTC, yangm97 commented
Gives me Habbo vibes...

2020-01-14 18:23 UTC, Sorunome commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
@yangm97 
> Gives me Habbo vibes...

what do you mean by this?

2020-01-14 18:28 UTC, yangm97 commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
<img width="362" alt="Screen Shot 2020-01-14 at 15 26 17" src="https://user-images.githubusercontent.com/4412002/72371023-3bae2a00-36e2-11ea-90bb-a40cd5f71845.png">

This.

2020-01-14 18:31 UTC, Sorunome commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
It is up to the client how to visualize a knock. An event in the time line is way less intrusive than a popup.

2020-01-14 19:46 UTC, yangm97 commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
I didn't try to make any point though, just stated the fact this MSC reminded me about Habbo (and about my childhood by extension).

2020-01-19 12:33 UTC, Sorunome commented
While implementing this in synapse soru noticed a few issues with the endpoints (that it simply wouldn't have worked the way it was originally outlined). Thus, this MSC has been updated.

2020-01-29 18:13 UTC, anoadragon453 commented on proposals/2403-knock.md
> +  "error": "An unknown error occurred"}
```suggestion
  "error": "An unknown error occurred"
}
```

2020-02-06 13:23 UTC, turt2live submitted a review, later dismissed

2020-02-06 13:23 UTC, turt2live commented on proposals/2403-knock.md
> +memtership types the parameters "displayname" and "avatar_url" are optional. This membership can
```suggestion
membership types the parameters "displayname" and "avatar_url" are optional. This membership can
```

2020-02-06 13:23 UTC, turt2live commented on proposals/2403-knock.md
> +The default power level for "knock" is 0. If a user has a too low power level to knock they aren't
why not the invite power level?

2020-02-06 13:23 UTC, turt2live commented on proposals/2403-knock.md
> +# Potential issues
The proposal is missing how knocks come down `/sync`, and what clients should be rendering it as. Are we expecting that knocks are handled immediately by the room, or do we say that it ists in the room list for a while?

2020-02-06 13:23 UTC, turt2live commented on proposals/2403-knock.md
> +# Security considerations
The MSC needs to cover the transition from knock -> any other membership.

2020-02-07 17:47 UTC, Sorunome commented on proposals/2403-knock.md
> +# Security considerations
How so? That doesn't change at all, if you join the room, you join it. If someone sends you a leave membership, you get that. It doesn't seem relevant for this MSC?

2020-02-07 17:48 UTC, Sorunome commented on proposals/2403-knock.md
> +# Potential issues
The same as other membership changes? It doesn't seem relevant for this MSC as it just introduces a new membership type, and it is already covered how memberships come down `/sync`

2020-02-07 17:49 UTC, Sorunome commented
@turt2live 
> why not the invite power level?

(github doesn't allow to reply to that conversation)

because invite and knock are two different features so you can easily think of scenarios where you want different PLs for those features

2020-02-07 17:50 UTC, Sorunome commented on proposals/2403-knock.md
> +The default power level for "knock" is 0. If a user has a too low power level to knock they aren't
because invite and knock are two fundamentally different things and so there is no real reason to combind their power level. It is like combinding ban and invite power level.

2020-02-07 17:51 UTC, Sorunome commented on proposals/2403-knock.md
> +The `join_rule` of `m.room.join_rules` must be set to "invite". This means that people can't knock
It is briefly mentioned in the alternative approaches

2020-02-07 18:05 UTC, Half-Shot commented on proposals/2403-knock.md
> +# Security considerations
I agree that it would be useful to see a set of transition rules purely as an exercise to show that it works at all, even if it's obvious to you. When inserting another state for membership, we should be clear how it affects other memberships.

2020-02-07 18:25 UTC, turt2live commented on proposals/2403-knock.md
> +# Potential issues
Invites, joins, and kicks/leaves all come down different sections.

2020-02-07 18:27 UTC, turt2live commented on proposals/2403-knock.md
> +# Security considerations
it also helps prove that it works, and makes it easier to spec

2020-02-07 18:28 UTC, Sorunome commented on proposals/2403-knock.md
> +# Potential issues
Soru is confused: They all come down the normal event streem of the room, just as setting *any* state event does.

2020-02-07 18:29 UTC, turt2live commented on proposals/2403-knock.md
> +The default power level for "knock" is 0. If a user has a too low power level to knock they aren't
sorry, not to combine, but to use the default. Instead of defaulting to zero, default to the `invite` power level.

2020-02-07 18:31 UTC, Sorunome commented on proposals/2403-knock.md
> +The default power level for "knock" is 0. If a user has a too low power level to knock they aren't
but that is zero, too?

2020-02-07 18:31 UTC, turt2live commented on proposals/2403-knock.md
> +# Potential issues
![image](https://user-images.githubusercontent.com/1190097/74055486-05f61b80-49d8-11ea-91b2-fd151c565a4e.png)

2020-02-07 18:32 UTC, turt2live commented on proposals/2403-knock.md
> +The default power level for "knock" is 0. If a user has a too low power level to knock they aren't
sure, but if it changes then at least the room will be using the same default number. They seem related.

2020-02-07 18:32 UTC, Sorunome commented on proposals/2403-knock.md
> +# Potential issues
Ooooooh, you weren't talking about how the knock trips down into the room for people that are in it but for the one doing the knock. Currently the MSC doesn't cover the one doing the knock getting any feedback on that at all, as that would require the server to keep track of rooms that, well, it simply doesn't know/have

2020-02-07 18:33 UTC, Sorunome commented on proposals/2403-knock.md
> +The default power level for "knock" is 0. If a user has a too low power level to knock they aren't
Doesn't seem that related to soru:

Imagine a room that is invite-only and you only want certain people to be able to invite others. So you raise the invite level. Then you are suddenly confused why you aren't receiving any knocks at all anymore.

2020-02-07 18:33 UTC, turt2live commented on proposals/2403-knock.md
> +# Potential issues
That's fine, that's why we're at the idea stage :p

2020-02-07 18:34 UTC, turt2live commented on proposals/2403-knock.md
> +The default power level for "knock" is 0. If a user has a too low power level to knock they aren't
I guess, fair point.

2020-02-07 18:34 UTC, Sorunome commented on proposals/2403-knock.md
> +# Potential issues
currently the knocker also gets no information on the room (room name + avatar) which would probably be needed when a client were to introduce a "knocked rooms" category, similarly to invites.

2020-02-07 18:36 UTC, turt2live commented on proposals/2403-knock.md
> +# Potential issues
Yup, would definitely put that into the MSC.

2020-02-07 18:37 UTC, Sorunome commented on proposals/2403-knock.md
> +# Potential issues
does it sound reasonable that, on a knock, the knocker receives all the invite state events? Wouldn't that leave a security consideration that information of the room is leaked outwards, that it might make more sense to define a new knock state events which is (not necessarily) a subset of the invite state events?

2020-02-07 18:41 UTC, Sorunome commented on proposals/2403-knock.md
> +# Potential issues
Note to self: when adding this also keep in mind that the knock can be rejected (sending `leave` membership), that also needs to (potentially federate) to the homeserver and then land down `/sync`

2020-02-07 18:43 UTC, Sorunome commented on proposals/2403-knock.md
> +when creating a new room, prevent anyone from knocking.
Thoughts from others?

2020-02-07 18:44 UTC, Sorunome commented on proposals/2403-knock.md
> +}
Shouldn't the normal displayname deduping as outlined in how to render a displayname apply? Along with potential user interaction to see the full mxid? Like.....this isn't really anything new?

2020-02-07 18:51 UTC, Sorunome commented on proposals/2403-knock.md
> +# Security considerations
Added this in!

2020-02-07 21:05 UTC, turt2live commented on proposals/2403-knock.md
> +# Potential issues
the aesthetics of the room are probably fine, from my 30 seconds of security review.

2020-02-13 17:15 UTC, richvdh commented on proposals/2403-knock.md
> +As for the join rule "invite", instead the join rule "knock" could be introduced, meaning the room
I like this: it means that semantics for existing rooms can be left unchanged whilst allowing new rooms to adopt the new semantics that allow knocking.

2020-02-13 17:17 UTC, richvdh commented on proposals/2403-knock.md
> +## Restrictions
bear in mind that we can't change the [auth rules](https://matrix.org/docs/spec/rooms/v1#authorization-rules) without introducing a new room version, since otherwise we get into the situation where some servers will accept events which should be rejected, and we'll get into a split-brain situation.

2020-02-13 17:17 UTC, richvdh commented on proposals/2403-knock.md
> +when creating a new room, prevent anyone from knocking.
I'm inclined to agree that having two ways of doing things is going to lead to confusion.

I actually think it would make more sense just to use the join rules, rather than also having support in the power levels. The join rules currently control who can transition from `leave` to `join`: perhaps they should also control who can transition from `leave` to `knock`?

2020-02-13 17:17 UTC, richvdh commented on proposals/2403-knock.md
> +The default power level for "knock" is the default power level for the room. If a user has a too low
what do you mean by "the default power level for the room"?

2020-02-13 17:22 UTC, richvdh commented on proposals/2403-knock.md
> +The two endpoints for the client-server API seem redundant, this MSC followed how JOIN is working
my instinct is that we could get away without speccing `/rooms/{roomId}/knock` ?

2020-02-13 17:24 UTC, Sorunome commented on proposals/2403-knock.md
> +As for the join rule "invite", instead the join rule "knock" could be introduced, meaning the room
What about dropping the join rules from this MSC at all in favour of the PL control?

2020-02-13 17:43 UTC, richvdh commented on proposals/2403-knock.md
> +As for the join rule "invite", instead the join rule "knock" could be introduced, meaning the room
see https://github.com/matrix-org/matrix-doc/pull/2403#discussion_r379003104: I think I prefer the use of join rules to control this than power levels.

2020-02-13 17:43 UTC, Sorunome commented on proposals/2403-knock.md
> +The two endpoints for the client-server API seem redundant, this MSC followed how JOIN is working
Yeah, but then there would be an inconsistency with invite, and soru thought consistency was more important

2020-02-13 17:44 UTC, Sorunome commented on proposals/2403-knock.md
> +when creating a new room, prevent anyone from knocking.
The problem arises if you have e.g. knocking spam from one person and want to easily dissallow them to knock but still allow others to knock

2020-02-13 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +when creating a new room, prevent anyone from knocking.
ban the spammer?

2020-02-13 17:47 UTC, Sorunome commented on proposals/2403-knock.md
> +## Restrictions
Ah, didn't know that. Does there happen to be another room version in discussion anyways?

2020-02-13 17:48 UTC, richvdh commented on proposals/2403-knock.md
> +The two endpoints for the client-server API seem redundant, this MSC followed how JOIN is working
I assume you mean `join` ?

understood; personally I'd prefer not to repeat the mistakes of /join, but it's subjective.

2020-02-13 17:48 UTC, Sorunome commented on proposals/2403-knock.md
> +The default power level for "knock" is the default power level for the room. If a user has a too low
![Screenshot_2020-02-13_18-48-03](https://user-images.githubusercontent.com/2433620/74463000-67fbc880-4e91-11ea-854a-1bcb0790ab90.png)

All these "Default", is that not how it is called?

2020-02-13 17:49 UTC, Sorunome commented on proposals/2403-knock.md
> +The two endpoints for the client-server API seem redundant, this MSC followed how JOIN is working
Ah yes, sorry :+1:

2020-02-13 17:50 UTC, Sorunome commented on proposals/2403-knock.md
> +As for the join rule "invite", instead the join rule "knock" could be introduced, meaning the room
As you mentioned that adding knock would need a new room version anyways due to auth rules then it simply couldn't be introduced in current rooms [without them upgrading], correct? If so, soru would probably also prefer to introduce "knock" rather than "private"

2020-02-13 17:52 UTC, richvdh commented on proposals/2403-knock.md
> +## Restrictions
there's always another room version in discussion. Best way is to implement the MSC in a temporary/test/experimental room version [like this](https://github.com/matrix-org/synapse/blob/49d3bca37b91fa092e13fd28c42dcf970fb86bb7/synapse/api/room_versions.py#L105) so that it can be tested etc. Then at some point someone will propose a proper room version to include the MSCs which have landed since the last one.

2020-02-13 17:54 UTC, richvdh commented on proposals/2403-knock.md
> +The default power level for "knock" is the default power level for the room. If a user has a too low
I don't know offhand how riot maps those onto values in the `m.room.power_levels` event: it would be helpful to describe this at the protocol level.

2020-02-13 17:54 UTC, richvdh commented on proposals/2403-knock.md
> +As for the join rule "invite", instead the join rule "knock" could be introduced, meaning the room
correct

2020-04-30 16:14 UTC, Kegsay commented on proposals/2403-knock.md
> +# Security considerations
You need to explicitly state that we've considered knock spam and mitigations against it. We allude to using banning as a solution but this section is there for you to spell it out.

Also, can you transition from knock -> knock? Can you rescind your own knock?

2020-04-30 16:23 UTC, erikjohnston commented on proposals/2403-knock.md
> +   the room.
I wonder if we should make it so that the user auto joins, e.g. one of:

1. have the knocker's HS immediately do a join after receiving invite,
2. allow the federation invite API return a signed join instead, or
3. some other mechanism

2020-04-30 16:24 UTC, erikjohnston commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
We might want to consider being able to "silently" reject knocks, i.e. don't proactively send the `/leave` to the knocking server? Mainly as an anti abuse mechanism so that you can clear the room UI without having to let the other side know you interacted with them.

2020-05-20 12:13 UTC, Sorunome commented on proposals/2403-knock.md
> +# Security considerations
Soru thought that you cannot transition from knock->knock and you cannot rescind your own knock, to prevent spam: If you can do knock->knock then you can just flood a room without knows, if you can rescind knocks, you can just knock->rescind->knock->rescind and thus still flood a room.

2020-05-20 12:14 UTC, Sorunome commented on proposals/2403-knock.md
> +   the room.
🤔 that might be a good idea, but could maybe also lead to unexpected behaviour? Not quite sure. Is autojoining a room a thing in the spec yet?

2020-05-20 12:15 UTC, Sorunome commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
The problem with that is that different servers then potentially have different views of a room - to what other problems will that lead down the road?

2020-06-09 15:23 UTC, erikjohnston commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
I don't think the servers in the room would have a different view, just the user wouldn't be sent the knock rejection.

OTOH I think this is a nice to have, rather than something that should block the MSC

2020-06-09 15:24 UTC, erikjohnston commented on proposals/2403-knock.md
> +   the room.
I don't think we have anything like this currently over federation. We do have thing where servers will auto join new local users to a room

2020-06-09 15:24 UTC, Sorunome commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
You could reject knocks with a ban, too, and the preson couldn't knock again

2020-06-09 15:25 UTC, erikjohnston commented on proposals/2403-knock.md
> +None. This doesn't allow users access to a room in any way.
Yeah, maybe that is good enough for now

2020-06-24 15:36 UTC, Sorunome commented on proposals/2403-knock.md
> +}
> If so, would that not be confusing to room admins if they let in "bob" and "alice" joins the room?

Not much different if they join and right after change their displayname / avatar_url. That is what mxids exist for.

2020-06-24 15:37 UTC, Sorunome commented on proposals/2403-knock.md
> +outsiders to send messages into the room. Clients can optionally add a way for users of a room to
Maybe instead of just "show reason" but "new knock from <mxid>, show details"?

2020-06-24 16:57 UTC, anoadragon453 commented on proposals/2403-knock.md
> +outsiders to send messages into the room. Clients can optionally add a way for users of a room to
Yeah, that could work.

You could also just take the approach of leaving it up to the implementation, which may think of a better solution :)

2020-06-24 17:02 UTC, anoadragon453 commented on proposals/2403-knock.md
> +}
When you join and then change your details, a "bla changed their displayname" appears in the timeline. But I'm assuming you wouldn't get that if someone's membership is knock. So if someone knocks, changes their details, and then joins, you'd see:

```
"Bob would like to join"
*accept knock*
"Alice has joined the room"
```

Though, I guess if you instead included the mxid, you'd instead see:

```
"Bob (@bob:matrix.org) would like to join"
*accept knock*
"Alice (@bob:matrix.org) has joined the room"
```

then it's not so bad.

This ties into the discussion directly below. If we don't show displayname/avatar in the timeline at all before a user joins (but only their mxid), then that eliminates this problem.

2020-07-30 16:59 UTC, anoadragon453 commented
Everyone: I've been assigned as Spec Core Team member to shepherd this MSC and help get it through.

2020-08-25 17:18 UTC, anoadragon453 commented
I've created [a sequence diagram](https://sequencediagram.org/index.html#initialData=title%20MSC2403%3A%20Knocking%0A%0AClient_A-%3EServer_A%3A%20POST%20%2F_matrix%2Fclient%2Fr0%2Frooms%2F%7BroomId%7D%2Fknock%2C%20%7Breason%3A%20%22pls%22%7D%0Anote%20left%20of%20Server_A%3A%20Client_A%20membership%20%3D%3D%20%22leave%22%2Fnull%3F%20%0Anote%20left%20of%20Server_A%3A%20Room%20join%20rules%20%3D%3D%20%22knock%22%3F%0AClient_A%3C--Server_A%3A%20%7B%7D%0AServer_A-%3EServer_B%3A%20GET%20%2F_matrix%2Ffederation%2Fv1%2Fmake_knock%2F%7BroomId%7D%2F%7BuserId%7D%0Anote%20left%20of%20Server_B%3A%20Same%20checks%20as%20Server_A%0AServer_A%3C--Server_B%3A%20%7B%22event%22%3A%20%7B...%20%22type%22%3A%20%22m.room.member%22%2C%20%22content%22%3A%20%7B%22membership%22%3A%20%22knock%22%7D%20...%7D%0Anote%20right%20of%20Server_A%3A%20Signs%20the%20given%20event%0AServer_A-%3EServer_B%3A%20PUT%20%2F_matrix%2Ffederation%2Fv1%2Fsend_knock%2F%7BroomId%7D%2F%7BeventId%7D%2C%20%7B...signed%20event...%7D%0AServer_A%3C--Server_B%3A%20%7B%7D%0AServer_B-%3ERoom%3A%20m.room.member%20knock%20event%2C%20reason%3A%20%22pls%22%0AServer_B-%3EClient_B%3A%20Knock%20appears%20in%20timeline%2Fsomewhere%0AClient_A-%3EServer_A%3A%20%2Fsync%0Anote%20left%20of%20Client_A%3A%20Hey%20user%2C%20you've%20got%20a%20pending%20knock%0AClient_A%3C--Server_A%3A%20rooms-%3Eknock-%3Einfo%2C%20state-%3E%22knock%22%2C%20room%20metadata%20(summary)%0Anote%20left%20of%20Client_B%3A%20sounds%20good%20to%20me%0AClient_B-%3EServer_B%3A%20POST%20%2F_matrix%2Fclient%2Fr0%2Frooms%2F%7BroomId%7D%2Finvite%2C%20%7B%22user_id%22%3A%20%22%40...%22%7D%0AClient_B%3C--Server_B%3A%20%7B%7D%0AServer_B-%3ERoom%3A%20m.room.member%20event%2C%20%40...%20membership%20-%3E%20%22invite%22%0AServer_A%3C-Server_B%3A%20You've%20got%20mail%20(invite)%0AClient_A-%3EServer_A%3A%20%2Fsync%0AClient_A%3C--Server_A%3A%20rooms-%3Einvite-%3Einfo%2C%20state-%3E%22invite%22%0Anote%20left%20of%20Client_A%3A%20Hey%20user%2C%20your%20knock%20succeeded.%5CnAlso%20you%20have%20an%20invite%0AClient_A-%3EServer_A%3A%20(invite%20dance%2C%20user%20joins%2C%20etc)%0A%3D%3Dknock%20attempt%20is%20rejected%20by%20room%20admin%3D%3D%0Anote%20left%20of%20Client_B%3A%20nah%0AClient_B-%3EServer_B%3A%20PUT%20%2F_matrix%2Fclient%2Fr0%2Frooms%2F%7BroomId%7D%2Fstate%2Fm.room.member%2F%7BuserId%7D%2C%20%7B%22membership%22%3A%20%22leave%22%7D%0AServer_B-%3ERoom%3A%20m.room.member%20event%2C%20%40...%20membership%20-%3E%20%22leave%22%0AClient_B%3C--Server_B%3A%20%7B%7D%0AServer_B-%3EServer_A%3A%20You've%20got%20mail%20(leave)%0AServer_B%3C--Server_A%3A%20%7B%7D%0AClient_A-%3EServer_A%3A%20%2Fsync%0AClient_A%3C--Server_A%3A%20rooms-%3Eknock-%3Einfo%2C%20state-%3E%22leave%22%2C%20room%20metadata%20(summary)%0Anote%20left%20of%20Client_A%3A%20Hey%20user%2C%20your%20knock%20was%20rejected%20%3Ac) of the flow, including the proposed CS stuff from @turt2live. Should hopefully help others wrap their head around things (it definitely helped me writing it).

2020-08-28 12:58 UTC, anoadragon453 commented
I've updated the [sequence diagram](https://sequencediagram.org/index.html#initialData=title%20MSC2403%3A%20Knocking%0A%0AClient_A-%3EServer_A%3A%20POST%20%2F_matrix%2Fclient%2Fr0%2Frooms%2F%7BroomId%7D%2Fknock%2C%20%7Breason%3A%20%22pls%22%7D%0Anote%20left%20of%20Server_A%3A%20Client_A%20membership%20%3D%3D%20%22leave%22%2Fnull%3F%20%0Anote%20left%20of%20Server_A%3A%20Room%20join%20rules%20%3D%3D%20%22knock%22%3F%0AServer_A-%3EServer_B%3A%20GET%20%2F_matrix%2Ffederation%2Fv1%2Fmake_knock%2F%7BroomId%7D%2F%7BuserId%7D%0Anote%20left%20of%20Server_B%3A%20Same%20checks%20as%20Server_A%0AServer_A%3C--Server_B%3A%20%7B%22event%22%3A%20%7B...%20%22type%22%3A%20%22m.room.member%22%2C%20%22content%22%3A%20%7B%22membership%22%3A%20%22knock%22%7D%20...%7D%0Anote%20right%20of%20Server_A%3A%20Signs%20the%20given%20event%0AServer_A-%3EServer_B%3A%20PUT%20%2F_matrix%2Ffederation%2Fv1%2Fsend_knock%2F%7BroomId%7D%2F%7BeventId%7D%2C%20%7B...signed%20event...%7D%0AServer_A%3C--Server_B%3A%20%7Bknock_state_events%3A%20m.room.name%2C%20m.room.avatar%2C%20...%7D%0AClient_A%3C--Server_A%3A%20%7B%22room_id%22%3A%20%22!abc%3Amatrix.org%22%7D%0AServer_B-%3ERoom%3A%20m.room.member%20knock%20event%2C%20reason%3A%20%22pls%22%0AServer_B-%3EClient_B%3A%20Knock%20appears%20in%20timeline%2Fsomewhere%0AClient_A-%3EServer_A%3A%20%2Fsync%0AClient_A%3C--Server_A%3A%20rooms-%3Eknock-%3E!room%3Aid-%3Estate-%3E%5Bm.room.name%2Favatar%5D%0Anote%20left%20of%20Client_A%3A%20Hey%20user%2C%20you've%20got%20a%20pending%20knock%0Anote%20left%20of%20Client_B%3A%20sounds%20good%20to%20me%0AClient_B-%3EServer_B%3A%20POST%20%2F_matrix%2Fclient%2Fr0%2Frooms%2F%7BroomId%7D%2Finvite%2C%20%7B%22user_id%22%3A%20%22%40...%22%7D%0AClient_B%3C--Server_B%3A%20%7B%7D%0AServer_B-%3ERoom%3A%20m.room.member%20event%2C%20%40...%20membership%20-%3E%20%22invite%22%0AServer_A%3C-Server_B%3A%20You've%20got%20mail%20(invite)%0AClient_A-%3EServer_A%3A%20%2Fsync%0AClient_A%3C--Server_A%3A%20rooms-%3Einvite-%3Einfo%2C%20state-%3E%22invite%22%0Anote%20left%20of%20Client_A%3A%20Hey%20user%2C%20your%20knock%20succeeded.%5CnAlso%20you%20have%20an%20invite%0AClient_A-%3EServer_A%3A%20(invite%20dance%2C%20user%20joins%20the%20room)%0A%3D%3Dknock%20attempt%20is%20rejected%20by%20room%20admin%3D%3D%0Anote%20left%20of%20Client_B%3A%20nah%0AClient_B-%3EServer_B%3A%20PUT%20%2F_matrix%2Fclient%2Fr0%2Frooms%2F%7BroomId%7D%2Fstate%2Fm.room.member%2F%7BuserId%7D%2C%20%7B%22membership%22%3A%20%22leave%22%7D%0AServer_B-%3ERoom%3A%20m.room.member%20event%2C%20%40...%20membership%20-%3E%20%22leave%22%0AClient_B%3C--Server_B%3A%20%7B%7D%0AServer_B-%3EServer_A%3A%20You've%20got%20mail%20(leave)%0AServer_B%3C--Server_A%3A%20%7B%7D%0AClient_A-%3EServer_A%3A%20%2Fsync%0AClient_A%3C--Server_A%3A%20rooms-%3Eknock-%3E!room%3Aid-%3Estate-%3E%5Bm.room.member%3D%22leave%22%5D%0Anote%20left%20of%20Client_A%3A%20Hey%20user%2C%20your%20knock%20was%20rejected%20%3Ac) (new link) to note that the CS endpoints will only return after a knock succeeded or failed, and updated how the client was informed on knock progress.

2020-08-28 14:08 UTC, anoadragon453 commented on proposals/2403-knock.md
> +}
I think this is the same problem invites face actually, so I'm minded not to fix it in this MSC.

2020-09-01 07:30 UTC, Sorunome commented on proposals/2403-knock.md
> +knocks.
Rooms in general accumulate, so this shouldn't be much an issue?

2020-09-01 07:35 UTC, Sorunome commented on proposals/2403-knock.md
> +allowing knocks, "knock" is no different from the "invite" join rule.
> rather than push rules?

You mean rather than power levels? xP

Anyhow, coming back to this after the few month pause the join_rules seems the cleaner way: we can still disallow certain people to knock by banning them. The only situation you can't do with join rules rather than PLs is that, by default, noone may knock and then you whitelist who is allowed to walk. This can be helpful for private communities with e.g. venting rooms where people sometimes have to leave due to a triggering topic being present and then they can knock to come back in......so yeah, still not entirely sure which approach is better.

2020-09-01 10:44 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knocks.
Yes, though at least the client can leave those rooms if they want.

If a user knocks on a room, and the admin of that room disappears, the user is stuck with that knock for the rest of time.

2020-09-01 10:47 UTC, anoadragon453 commented on proposals/2403-knock.md
> +allowing knocks, "knock" is no different from the "invite" join rule.
> You mean rather than power levels? xP

lol yes, seems I've been hearing too much about the notifications project recently :P 

As for your mentioned use-case, perhaps that could be solved by an evolution of the moderation tools. Say banning via whitelist/blacklist?

2020-09-01 13:38 UTC, Sorunome commented on proposals/2403-knock.md
> +allowing knocks, "knock" is no different from the "invite" join rule.
> As for your mentioned use-case, perhaps that could be solved by an evolution of the moderation tools. Say banning via whitelist/blacklist?

Yes, that could work and is out-of-scope for this MSC.

Just to toss ideas around: If we have permission roles, rather than power levels (similar to how discord does it), kicking, knocking, join rules etc. could all be handled by just one on and the same permission system.

2020-09-01 13:39 UTC, Sorunome commented on proposals/2403-knock.md
> +allowing knocks, "knock" is no different from the "invite" join rule.
So to conclude: Using join rules seems sufficient for now

2020-09-02 11:03 UTC, anoadragon453 commented on proposals/2403-knock.md
> +allowing knocks, "knock" is no different from the "invite" join rule.
> Just to toss ideas around: If we have permission roles, rather than power levels (similar to how discord does it), kicking, knocking, join rules etc. could all be handled by just one on and the same permission system.

This is something we want to do eventually, yes. It's just going to be a *very large project*.

2020-09-03 12:39 UTC, richvdh requested changes

2020-09-03 12:39 UTC, richvdh commented on proposals/2403-knock.md
> +knocks.
yeah this sounds wrong. Users should be able to un-knock if they knock by accident. If you've got a problem user, just ban them.

2020-09-03 12:39 UTC, richvdh commented on proposals/2403-knock.md
> +This is loosely based off of the
```suggestion
This is loosely based on the
```

2020-09-03 12:39 UTC, richvdh commented on proposals/2403-knock.md
> +The event was successfully accepted into the graph by the receiving
which server is responsible for sending the knock event to the rest of the servers in the room? The resident server, presumably?

2020-09-03 12:39 UTC, richvdh commented on proposals/2403-knock.md
> +As we're updating the join rules, and thus the auth rules, this proposal will
I'd like to see an explicit proposal for how the auth rules will be changed.

2020-09-03 12:39 UTC, richvdh commented on proposals/2403-knock.md
> +then backport this filter to invites? :)
I don't really understand this paragraph.

2020-09-03 12:39 UTC, richvdh commented on proposals/2403-knock.md
> +XXX: Is `m.room.canonical_alias` worth allowing here for any reason?
can we just make this the same as the state sent for invite events?

2020-09-03 12:39 UTC, richvdh commented on proposals/2403-knock.md
> +of when an invite is recinded).
this seems a bit out of place in the "extensions to sync" section?

2020-09-03 15:05 UTC, anoadragon453 commented on proposals/2403-knock.md
> +The event was successfully accepted into the graph by the receiving
Yes, I should state that explicitly.

2020-09-03 15:06 UTC, anoadragon453 commented on proposals/2403-knock.md
> +then backport this filter to invites? :)
Whoops, those weren't meant to be checked in.

2020-09-03 15:22 UTC, richvdh commented
btw: this needs a section saying where the API endpoints will live during development.

2020-09-04 13:13 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knocks.
Yeah, after thinking about it we still have the problem of a homeserver admin being able to send knocks from hundreds of users. Our response to that is to ban (ACL) the server, so there's no reason that we should implement a different defense mechanism here if it only leads to added complexity.

2020-09-04 13:15 UTC, Sorunome commented on proposals/2403-knock.md
> +knocks.
And if a person annoyingly knocks again and again then they can be banned...which means that the transition `knock` --> `leave` actually does make somewhat sense?

2020-09-04 13:15 UTC, Sorunome commented on proposals/2403-knock.md
> +knocks.
Oh, and knock reasons have to be redactable, in case they are non-nice texts, e.g. nsfw

2020-09-04 13:17 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knocks.
@richvdh Should we "leave it up to implementation" in how homeservers deal with trying to rescind a knock to a room with no active homeservers? I don't think we specify anything in the spec in regards to stuck invites either...

2020-09-04 13:29 UTC, anoadragon453 commented on proposals/2403-knock.md
> +XXX: Is `m.room.canonical_alias` worth allowing here for any reason?
Yes, and that is defined as:

> An optional list of simplified events to help the receiver of the invite identify the room. The recommended events to include are the join rules, canonical alias, avatar, and name of the room.

I'll just put in the same.

2020-10-01 16:39 UTC, anoadragon453 commented on proposals/2403-knock.md
> +of when an invite is recinded).
It became duplicated information after fleshing out the "Membership changes" section.

2020-10-01 17:51 UTC, anoadragon453 commented
I think I've covered all of the things you've asked for @richvdh, and would love another look over :innocent:

2020-11-06 18:41 UTC, michaelkaye commented
Are there any concerns given rooms with this mode toggled on, will see lots of state events with keys relating to users not part of the room, which could lead to a performance impact on the servers taking part in that room?

While I'm not a state-res expert, I think that special attention is taken to [membership events of type "ban" sent by room admins](https://matrix.org/docs/guides/implementing-stateres#defining-control-events-and-normal-state-events) as they control who is allowed to send further events to the room, and so these bans of users who have never joined the room will need to accumulate forever.

The traditional method of managing a invite only room where you use a website or similar doesn't accumulate these failed joins, as they're effectively kept outside of the room of interest, so keeping the room state clear of temporary information.

2020-11-10 05:11 UTC, turt2live reviewed
apologies for the massive comment dump - this has been sitting in my queue for a while.

Some of my comments are more serious concerns than others. Many are stylistic, though.

Overall the proposal seems sensible. Just a couple clarifications/questions to be had.

2020-11-10 05:11 UTC, turt2live commented on proposals/2403-knock.md
> +room admins to opt in to this behaviour.
```suggestion
partake in. That is why this proposal enables the `knock` join rule, in order to allow
room admins to opt in to this behaviour.
```

2020-11-10 05:11 UTC, turt2live commented on proposals/2403-knock.md
> +knocks over and over.
it's worth mentioning that this attack is easier with knocks than it is with join/leave cycles, as joining often takes effort while knocking doesn't. Similarly, it's not really possible to invite yourself over and over and instead requires cooperative effort.

There's not much incentive to avoid hammering (un)knocks into a room under this proposal.

2020-11-10 05:11 UTC, turt2live commented on proposals/2403-knock.md
> +experimental support for room knocking.
Not needed if you also use a custom room version under the capabilities API.

2020-11-10 05:11 UTC, turt2live commented on proposals/2403-knock.md
> +the new join rule for rooms and the `content.membership` key of the member
not a new join rule

2020-11-10 14:29 UTC, richvdh commented on proposals/2403-knock.md
> +Or should it be the same power level that's required to accept the knock?
+1. Particularly if we're using the /kick endpoint to implement it. 

(I think a case could be made that the sender of an invite should be allowed to retract it, in case of a mistake. I see no equivalent here.)

2020-11-10 14:30 UTC, richvdh commented on proposals/2403-knock.md
> +validate the `prev_events` and `auth_events` that the event references. We
it really doesn't. the remote server gets the kick and *only* the kick - it isn't allowed to request any other events to help it build up an auth graph.

2020-11-10 14:31 UTC, richvdh commented on proposals/2403-knock.md
> +back to you - but what if it goes offline in the meantime?
we should, but we don't need to block this feature on it.

2020-11-10 14:35 UTC, richvdh approved these changes
this lgtm.

2020-11-10 18:05 UTC, anoadragon453 commented on proposals/2403-knock.md
> +remote homeservers when invited their users to a room.
Synapse will send the encryption state during invites by default: https://github.com/matrix-org/synapse/blob/c059413001cd2ff7c6104cfcd323ed115245ae90/docs/sample_config.yaml#L1395

But yes, the spec for invites currently lacks this recommendation: https://matrix.org/docs/spec/server_server/r0.1.4#put-matrix-federation-v2-invite-roomid-eventid

2020-11-19 17:06 UTC, clokep reviewed
In the context of reviewing matrix-org/synapse#6739 I took a look at this. I think is reasonable, but some bits could be a bit more explicit.

2020-11-19 17:06 UTC, clokep commented on proposals/2403-knock.md
> +   been rejected. Alternatively, the knocking user has rescinded their knock.
I don't really see much discussion of rescinding knocks except in the "Security considerations" section. How would a user rescind their knock? Is this the same as rejecting invites?

2020-11-19 18:23 UTC, clokep commented on proposals/2403-knock.md
> +### `PUT /_matrix/federation/v1/send_knock/{roomId}/{eventId}`
Not to get into a weird versioning debate, but I wonder if this should be `v2` since the response format matches the v2 of `send_join` and `send_leave`.

2020-11-19 19:11 UTC, anoadragon453 commented
> Are there any concerns given rooms with this mode toggled on, will see lots of state events with keys relating to users not part of the room, which could lead to a performance impact on the servers taking part in that room?

Unfortunately even preventing users from rescinding their knocks won't eliminate this attack vector, and an attacker could create infinite users/servers.

I would say that this is the same problem a public room faces with joins, but @turt2live makes a good point in that:

> it's worth mentioning that this attack is easier with knocks than it is with join/leave cycles, as joining often takes effort while knocking doesn't.

One interesting idea off the top of my head that could be explored is requiring a certain amount of time to pass before a server will accept another knock attempt. While yes, accurate time doesn't really exist in a federation, even rough time could be useful here.

It's not a be-all end-all solution, but I'm open to ideas on a better one!

2020-11-20 14:54 UTC, anoadragon453 commented on proposals/2403-knock.md
> +by each room version. To change these rules, the implementation of this
Indeed... I've linked to v6 for now. While it is fairly simple to follow the chain of auth rules throughout room versions now, I dread to think what would happen if we didn't have a linear upgrade path through room versions.

2020-11-20 14:56 UTC, anoadragon453 commented on proposals/2403-knock.md
> +      are already used to enforce whether someone can or cannot knock.
Correct. I try to explain this in the "Membership changes" section, but do you think I should mention that here at all?

It requires invite permissions to accept, and kick permissions to reject.

2020-11-20 16:45 UTC, anoadragon453 commented on proposals/2403-knock.md
> +remote homeservers when invited their users to a room.
I've added the recommendation for encryption into this MSC.

2020-11-20 16:45 UTC, anoadragon453 commented on proposals/2403-knock.md
> +### `PUT /_matrix/federation/v1/send_knock/{roomId}/{eventId}`
I think this makes sense, and we currently don't require endpoints to start at `v1`. The relevant proposal also does not require this: https://github.com/matrix-org/matrix-doc/pull/2475

I'll bump it up, thanks!

2020-11-20 16:45 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knocks over and over.
This is a good point, though I wonder if one day joins will be light enough such that the difference is negligible. (I hope so, but for different reasons :).

I've added a line mentioning this.

2020-11-24 16:46 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knocking is much lighter than the act of joining a room.
@turt2live @michaelkaye @Sorunome @clokep One potential solution for solving this is to *not* allow rescinding a knock from a room, but *do allow* for knocks to be rescinded locally. Thus when a client chose to rescind a knock, the client's homeserver would not attempt to send the `leave` into the room, but just inform the user that they no longer have a knock in that room. The state for that user in the room is still `knock` though. This would allow a user to only ever send one state event into the room while their knock is pending.

After locally rescinding the knock, if the user's knock is accepted then it just appears as a normal invite into the room. If rejected, the leave event will appear down /sync, but otherwise nothing will change.

I think this is a good compromise between good client UX and limiting abusive room behaviour. What do you think?

2020-11-24 18:07 UTC, turt2live commented on proposals/2403-knock.md
> +knocking is much lighter than the act of joining a room.
Locally rescinding the knock feels like a way to encourage a fork of the room, or be left with stuck knocks. I'm not sure how important of an issue it is to solve here and now - I think we might need a more federated rate limit structure that somehow prevents looping behaviour like this.

2020-11-24 21:14 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knocking is much lighter than the act of joining a room.
@turt2live That's a good point, locally rejecting invites is really only used as an implementation bandaid due to homeservers that fail to respond, so we probably shouldn't codify that behaviour into the spec...

> a more federated rate limit structure that somehow prevents looping behaviour like this.

This sounds ideal, and it's true that this problem isn't limited to knocks. There are lots of things you can do when you have unlimited users/servers.

2020-11-26 16:51 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
I'm not sure what to do about transitioning from `invite` -> `knock`. I'm tempted to allow it as I don't see any inherent harm by doing so.

2020-11-26 18:13 UTC, turt2live commented on proposals/2403-knock.md
> +      are already used to enforce whether someone can or cannot knock.
just a pointer would be appreciated - it hasn't been discussed in the MSC by this point in reading, so the reader is making assumptions. Just a "Approving/declining the knock is still subject to permissions, however, and are discussed later in this proposal" would be fine.

2020-11-26 18:15 UTC, turt2live commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
I would argue that invite -> knock is invalid - the client should be smart enough to do invite -> join

2020-11-27 10:52 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
I was wondering if there were any valid edge cases for invite -> knock... But I can't really think of any, and clients can just reject the invite and then knock again if they *really* feel they need to.

2020-11-27 11:04 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
Changed in 7dcff8f2.

2021-02-08 12:22 UTC, erkinalp requested changes
Knock-invite corroboration semantics

2021-02-08 12:22 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
```suggestion
    iii. If the `sender`'s membership is not `ban`, `knock` or `join`, allow.
    iv. If the `sender`'s membership is `invite`, allow and resolve the membership status as `join`.
    v. Otherwise, reject.
```
Suggested change enables an user that knocks a room to join, from a server that has not received the invite that has already been sent from another server.

2021-02-08 12:22 UTC, erkinalp commented on proposals/2403-knock.md
> +      invited to the room or if they are already in the room.
```suggestion
    - a.iii is justified as knocks should not be allowed if the knocking user
      has been banned from the room, has already knocked on the room, 
      or if they are already in the room.
```

2021-02-08 12:28 UTC, tulir commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
> resolve the membership status as `join`

I don't think that's a thing

2021-02-08 12:32 UTC, erkinalp commented on proposals/2403-knock.md
> +knocking is much lighter than the act of joining a room.
What about making rescinded knocks self-imposed bans?

2021-02-08 12:33 UTC, auscompgeek commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
I don't see why the user's homeserver can't simply try to join as normal in such a scenario.

2021-02-08 12:44 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
> why ... n't simply try to join as normal

Because in this case, we want to resolve the combination of an unresponded invite and an unresponded knock as a forcible member add.

2021-02-08 15:38 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
That should be down to the homeserver to either:

* Attempt to join the room if a user knocks when they're already invited to a room, or
* Reject the knock and inform the client that they're already invited, and should attempt a join instead.

Getting the behaviour you're after doesn't need to be determined by the event auth rules.

2021-02-08 16:15 UTC, anoadragon453 commented on proposals/2403-knock.md
> +      invited to the room or if they are already in the room.
The answer above applies here as well.

2021-02-08 17:11 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
> Getting the behaviour you're after doesn't need to be determined by the event auth rules.

As a principle, all events that cause a user join a room should be initiated by some client, not by the server on its own. This is the reason that I add it to the event auth rules, where servers can overrule or reject the event rather than inserting an event in between.

2021-02-08 18:30 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
With the current auth event rules, if a server attempts to insert a `knock` membership into a room that they are already invited to, that will be rejected by all servers.

It's up to the implementation whether it wants to send a `join` membership into the room upon receiving a knock for a room where the knocking user is already invited.

Broadly I'm not sure what this change to the event auth rules accomplishes that a check on the Client-Server API implementation of a homeserver couldn't do already.

2021-02-08 18:43 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knocking is much lighter than the act of joining a room.
That would prevent someone from knocking on the same room again e.g if they accidentally cancelled the knock.

You're also currently unable to ban yourself from a room :)

Using the moderation tools (bans, Server ACLs) we have today is currently the best way to solve potential abuse by knocking.

2021-02-08 18:46 UTC, anoadragon453 commented
This MSC has been sitting around the same generally agreed upon state for a good long while now. I think it's ready to go:

@mscbot fcp merge

2021-02-09 06:02 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
Homeserver of the knocking user or homeserver of the inviter can indeed do that, but there are possibilities that those two unresponded requests meet in yet another server, and I want to retain tne client-initiated nature of invite, knock, and join, with a very intuitive conflict resolution.

2021-02-09 10:37 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
I believe I see what you're saying. If a homeserver decides to send a knock on behalf of a user after they've already been invited, then other homeservers should treat that as a join.

Unfortunately, it's not possible for an event to be changed while processing it in regards to the auth rules. The event content is signed by the homeserver that created it, and cannot be modified unless the new content is resigned by the original homeserver.

We could just go ahead and insert the `knock` state event into the DAG and instruct homeservers that "if a user has a knock membership, and at some point in the past had an invite, then they are join". However, implementing that would be a radical change to the current idea of only needing to look at the current state in a room to get the full picture. It would also likely be an inefficient calculation for homeservers to constantly make.

I'm OK with saying that homeservers should transform a knock attempt into a join attempt if an invite exists in the given room, *if they'd like to*, before sending that out to other homeservers. You may get homeservers that do this, and others that don't. If you want this behaviour, use one that does.

2021-02-09 12:48 UTC, kakolisgay commented
I like the concept this MXC brings up, however I have two big issues that remain unaddressed in it's current form.

Firstly is state spam. This is *currently* only a concern for public rooms and rooms with invite being accessible to normal users. Adding `knock` provides a false sense of protection to a `knock` room, as there are already numerous scripts that can be used to spam-join a room by abusing homeservers without adequate registration requirements. This does nothing to protect against that, and citing this as a "known issue" doesn't fix the problem

Secondly is state pollution/state bloating. i.e: rooms having so many states that it begins to lock out clients that can't handle large amounts. `knock` doesn't address this either, external users can still manipulate room state.

Users who are not participating in a room should not be able to directly manipulate it, like `knock` currently allows them to.

2021-02-09 13:24 UTC, ShadowJonathan commented
On synapse `lazy_loading_members` don't give all `membership` state events at once, maybe that can be applied here? ("Don't load `knock` memberships older than a day, unless explicitly requested.")

2021-02-09 14:26 UTC, kakolisgay commented
> On synapse lazy_loading_members don't give all membership state events at once, maybe that can be applied here? ("Don't load knock memberships older than a day, unless explicitly requested.")

> It's also possible that knock requests then shouldn't be visible for users that cannot accept them

That's a client solution to a *to be* server problem. Ignoring the states client-side doesn't help homeservers with low complexity values, which could be locked out of rooms if they're knock-spammed enough

>  The first issue can be addressed (e.g. if a certain domain starts spamming the room with knock requests) with ACL lists

ACL banning entire servers is not a solution. Once you ACL one server, they'll just use another.

2021-02-09 14:35 UTC, ShadowJonathan commented
The other solution is to expire `"knock"` events, then, but that can be problematic due to people "refreshing" them.

2021-02-09 15:10 UTC, kakolisgay commented
The best solution would probably be to keep knocks behind a designated endpoint, similar to how other platforms do. That however isn't a very "matrixy" solution though.

Several matrix communities already use secondary or "vetting" rooms to alleviate spam in the "actual" room. Maybe knock requests could be directed into to another room, and clients would `/peek` into it to view knock information.

2021-02-09 15:43 UTC, richvdh commented
@kakolisgay @ShadowJonathan PLEASE use threads for comments on MSCs!

2021-02-09 17:31 UTC, dbkr commented on proposals/2403-knock.md
> +
I think we'd probably need to add something here about the importance of clients displaying some kind of information to help users spot attackers impersonating another user by stealing their display name & avatar then knocking on rooms: knocking makes this a *really* easy attack vector. IMO it's critical that the client display e2e verification status / how many rooms you already share with the knocker, or at the very least the mxid, and flag a huge warning if anything looks amiss. That in itself is a challenge to balance between false positives and false negatives.

2021-02-09 17:31 UTC, dbkr commented on proposals/2403-knock.md
> +user to indicate that they want to join a room.
Looks fine in general, my main concern with this is that right now spaces are almost here which will allow people in a space to join rooms in that space without having to knock or ask for an invite. This seems like the main driver for this feature, and it certainly introduces a lot of extra potential security / spam vectors so I wonder if the remaining benefit outweighs the cost.

2021-02-09 17:46 UTC, anoadragon453 commented on proposals/2403-knock.md
> +user to indicate that they want to join a room.
That's a good point and certainly one of the main drivers. Another usecase is having a room (or a Spacec!) that is publicly known, but those in the room/Space want to validate a potential outsider before allowing them in, without needing to find and invite them first.

This could support situations where a student requests to join a school organisation or signs up for a planned event.

2021-02-09 18:02 UTC, anoadragon453 commented on proposals/2403-knock.md
> +
Considering one can easily set their displayname and avatar to anything when sending a membership event, we'll indeed need to show the user's MXID in the client. E2EE verification status would be useful as well. I believe this can be handled with existing endpoints in the spec, but I'll make a note that clients should be aware of this here.

2021-02-09 19:35 UTC, KitsuneRal commented on proposals/2403-knock.md
> +`m.room.member` state event. This state event indicates that when a user
How much does knocking need to be a state event? I understand we have a reserved membership value for that but what if we make it an EDU instead? I wouldn't expect knocks to be long-lived (a user knocking and getting allowed in a month - is it even a case?), and it would nicely alleviate an issue of altering the room state of the room without joining the room (which, to me, feels rather counter-intuitive). Implications are that repeated knocks become a thing, so it would be good to impose some lengthy cool-down period after knocking (say, 1 day for a server to keep a knock event around while rejecting repeated knocks from the same user). Just an idea to mull over.

2021-02-10 18:01 UTC, anoadragon453 commented on proposals/2403-knock.md
> +tools easy even if the offensive user or server is not present in the room.
@KitsuneRal @uhoreg and I talked out of band about the abuse potential of external users knocking on a room. 

@KitsuneRal offered [a fundamental change](https://github.com/matrix-org/matrix-doc/pull/2403/files#r573180627) which would eliminate this issue, but carries other trade-offs.

The system as described allows abuse by sending lots of unwarranted state events in a room. This is not a new problem however. The same can occur when one creates a public room, and someone joins lots and lots of accounts to that room, thus resulting in a ballooning of room state. The solution - if room bans and server ACLs are not enough - is for the room admin to switch the room to invite-only until the attack subsides or the attacker gets bored.

The same is the case for knocking. If someone is attacking your room by sending lots of knocks, then switching the room to invite-only will block the attack. Knocking can then be turned back on at a later date.

@uhoreg mentioned that a fundamental problem we have today in matrix is that state in a room cannot be removed or collapsed, which can lead to large state graphs, and in some implementations performance woes. This is true, and something that we'll need to solve as matrix rooms grow and more homeservers spring up (and p2p matrix brings with it many more users).

This *is* something we'll need to solve, but I don't think this particular MSC will be the one to do that.

2021-02-10 18:42 UTC, anoadragon453 commented on proposals/2403-knock.md
> +`m.room.member` state event. This state event indicates that when a user
This is something I didn't think about, and is actually a pretty cool idea. I worry about the usability and technical implications however.

Remember that EDUs are not tied to a room, but rather to a user. So a knocking user will first need to find someone in the room to send an EDU to. That user's homeserver may receive the EDU, and will then need to rebroadcast it to everyone in the room - which there isn't really precedence for yet. Additionally, if a new admin/mod is appointed, and the others relinquish control of the room to them, they won't know about the knock.

The solution for that last bit is to have the outsider knock again in order to re-distribute EDUs. This is where my concerns about usability come in. It's true that in most cases knocks will likely accepted rather quickly - but sometimes you get inactive admins. They may not come back and accept the knock until a week later, and the idea of myself - totally personal UX opinion - is that clicking the knock button each day in the hopes to alert the admin a bit annoying. I don't know whether I'm just being ignored or if the EDU got lost somewhere.

That all said, besides the state benefit, using EDUs does have the benefit of only certain users can view the knock attempt, rather than the whole room, which may be useful in some use cases. Though on the other side of the coin, history of when someone knocked can also be useful, which state events provide.

It's an interesting idea, and possibly the basis of some new state event-like data type that's tied to rooms, but that doesn't end up in the room history.

2021-02-10 19:46 UTC, erkinalp commented on proposals/2403-knock.md
> +`m.room.member` state event. This state event indicates that when a user
A reasonable middle ground could be having the knock itself as EDU, but accept, reject and rescind of kick as state events.

2021-02-15 12:34 UTC, anoadragon453 commented on proposals/2403-knock.md
> +`m.room.member` state event. This state event indicates that when a user
For clarity, accepting a knock is an invite, rejecting a knock is a kick, and rescinding a kick doesn't translate to a specific state event. I wrote the above rebuttal under the assumption that knock would be an EDU, and the other actions would remind their respective state events.

2021-02-15 12:43 UTC, anoadragon453 commented on proposals/2403-knock.md
> +
Added in 876c5624.

2021-02-15 13:06 UTC, erkinalp commented on proposals/2403-knock.md
> +knocking is much lighter than the act of joining a room.
@anoadragon453 self-ban with room block semantics is proposed as part of #3007.

2021-02-15 13:14 UTC, anoadragon453 commented on proposals/2403-knock.md
> +can decide to reject it instead.
Good point, I hadn't considered push notifications. Being able to trigger a push based on whether a user can accept the knock (invite) would be useful, though I'm not sure whether we have any conditions for the notification target's power level yet? https://matrix.org/docs/spec/client_server/r0.6.1#actions

Having it on by default is a topic of debate. It sounds useful if we can only notify those who can act on it.

Unfortunately `sender_notification_permission` doesn't help us here as it's only concerned about the power levels of the sender of the event (i.e the knocking user).

2021-02-15 13:19 UTC, erkinalp commented on proposals/2403-knock.md
> +tools easy even if the offensive user or server is not present in the room.
> uhoreg mentioned that a fundamental problem we have today in matrix is that state in a room cannot be removed or collapsed, which can lead to large state graphs, and in some implementations performance woes. This is true, and something that we'll need to solve as matrix rooms grow and more homeservers spring up (and p2p matrix brings with it many more users).

This is essentially unsolvable without allowing server instances to arbitrarily censor events.

2021-02-15 14:30 UTC, anoadragon453 commented on proposals/2403-knock.md
> +tools easy even if the offensive user or server is not present in the room.
I'm talking about the resource-usage implications of storing old, redundant state (lots of leaves, joins, leaves, joins) resulting in a large, slow to traverse DAG. The problem isn't accepting lots of new events, but dealing with long tails of state. I don't think censoring (rejecting?) events solves that problem.

2021-02-16 18:38 UTC, uhoreg reviewed
Looks plausible.  I think the main blocker is a resolution an Kitsune's idea of using an EDU.

2021-02-16 18:38 UTC, uhoreg commented on proposals/2403-knock.md
> +| ver | [string] | The room versions the sending server has support for. Defaults to `[1]`.
Why not make this required?  It's optional in `make_join` for backwards compatibility, but we don't need to worry about backwards compatibility for this endpoint.  Also, defaulting to `[1]` doesn't make much sense because room version 1 doesn't support knocking.

2021-02-16 18:38 UTC, uhoreg commented on proposals/2403-knock.md
> +
Should it return 404 if it doesn't know about the room, like `make_join`?

2021-02-16 18:38 UTC, uhoreg commented on proposals/2403-knock.md
> +as user bans and server ACLs. Clients are encouraged to ease employing these
"... ease employing these tools easy ..."  I think intended to say either "... ease employing these tools ..." or "... make employing these tools easy ..."

```suggestion
as user bans and server ACLs. Clients are encouraged to make employing these
```

2021-02-16 18:38 UTC, uhoreg commented on proposals/2403-knock.md
> +of a new room version. Clients can check for a room version that includes
Is there an experimental room version that is being used?

2021-02-17 04:32 UTC, turt2live commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
This feels like a server-side bug if it can't handle the error of invite -> knock meaning invite -> join. The server could retry on behalf of the user to resolve the conflict.

2021-02-17 04:35 UTC, turt2live commented on proposals/2403-knock.md
> +validate the `prev_events` and `auth_events` that the event references. We
not sure I understand tbh - the kicked server should be able to pull history from a remote server for the section of DAG it was a member of, up to and including the kick event. If the kick event references future events then that would be a problem?

2021-02-17 04:37 UTC, turt2live commented on proposals/2403-knock.md
> +back to you - but what if it goes offline in the meantime?
not sure I agree tbh - it feels like an important part of this feature to reliably have declines shipped over federation. Without the fix, we end up risking possibly not solving the problem at all. 

I'd be happier if this MSC at least linked to another MSC which outlines a solution we can take a look at.

2021-02-17 04:38 UTC, turt2live commented on proposals/2403-knock.md
> +### `PUT /_matrix/federation/v2/send_knock/{roomId}/{eventId}`
why is this v2 when the make_knock is v1?

2021-02-17 10:37 UTC, anoadragon453 commented on proposals/2403-knock.md
> +| ver | [string] | The room versions the sending server has support for. Defaults to `[1]`.
Oh! I wasn't aware of the backwards compatibility requirement for `make_join`. In that case yes, let's make this required.

And you're right, it indeed doesn't make sense to default to a room version that doesn't include knocking :)

2021-02-17 10:40 UTC, erkinalp approved these changes

2021-02-17 11:02 UTC, anoadragon453 commented on proposals/2403-knock.md
> +| ver | [string] | The room versions the sending server has support for. Defaults to `[1]`.
Done in 84008775.

2021-02-17 12:11 UTC, anoadragon453 commented on proposals/2403-knock.md
> +
Yes, there's no reason it shouldn't. Done in 337c87b9.

2021-02-17 12:16 UTC, anoadragon453 commented on proposals/2403-knock.md
> +of a new room version. Clients can check for a room version that includes
Yep, didn't realise that wasn't quite noted here. Explicitly added in 74f3b12a.

2021-02-17 12:42 UTC, anoadragon453 commented on proposals/2403-knock.md
> +### `PUT /_matrix/federation/v2/send_knock/{roomId}/{eventId}`
This is `/v2` as a result of an earlier conversation: https://github.com/matrix-org/matrix-doc/pull/2403#discussion_r527103623

The idea was that it matches the response body of `/v2/send_join` and `/v2/send_leave`.

If we were going by [MSC2475](https://github.com/matrix-org/matrix-doc/pull/2475) rules it takes exception to starting at `/v1` for "sweeping changes", which may or may not include new endpoints aligning with old.

I'm happy to go either way on this though.

2021-02-18 16:16 UTC, anoadragon453 commented on proposals/2403-knock.md
> +`m.room.member` state event. This state event indicates that when a user
@KitsuneRal do you think the above is fair? I'm not ruling it out as a possible solution for a new iteration, but I think with what we have available in Matrix today it makes more sense to keep it as a state event for now.

2021-02-18 16:17 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
Indeed, this is a server implementation issue rather than something that should be resolved in the spec event authorisation.

2021-02-18 16:25 UTC, dbkr commented on proposals/2403-knock.md
> +user to indicate that they want to join a room.
True, it's interesting and quite nice that it would work for spaces equally.

2021-02-18 16:27 UTC, dbkr commented on proposals/2403-knock.md
> +can decide to reject it instead.
Ok - deciding to leave it for a separate MSC is perfectly fine I think, but better to explicitly decide to do so than forget about it.

2021-02-18 16:33 UTC, turt2live commented on proposals/2403-knock.md
> +### `PUT /_matrix/federation/v2/send_knock/{roomId}/{eventId}`
the endpoint versioning mechanics are largely defined under [MSC2844](https://github.com/matrix-org/matrix-doc/pull/2844) which is to say "no change". MSC2475 is likely to be closed as irrelevant under MSC2844.

The mechanics are roughly:
* Start at v1 unless something drastic happened to say otherwise (see: identity server spec where we'd want to start at v2 to indicate auth for historical reasons)
  * An argument could be made for either using v1 or v2 in this MSC under this condition.
* When the endpoint changes format or needs a new version, increment it.

I would argue that we should be symmetrical for `make/send_*` endpoints, which means either deciding on v1 or v2 depending on whether or not "different PDU format" feels like a reason to not use v1. Personally, I do not hold an opinion beyond them being symmetrical.

2021-02-18 16:41 UTC, anoadragon453 commented on proposals/2403-knock.md
> +### `PUT /_matrix/federation/v2/send_knock/{roomId}/{eventId}`
I'm happy with following [MSC2844](https://github.com/matrix-org/matrix-doc/pull/2844) and starting at v1. I don't think this qualifies as a sweeping change. The context of `/send_knock` being v1 and thus making `/make_knock` v2 a bit confusing is a perfectly reasonable argument against doing so, MSC2844 or not.

I'll to it v1.

2021-02-18 16:49 UTC, anoadragon453 commented on proposals/2403-knock.md
> +### `PUT /_matrix/federation/v2/send_knock/{roomId}/{eventId}`
Done in 248a3da5.

2021-02-18 17:08 UTC, anoadragon453 commented on proposals/2403-knock.md
> +can decide to reject it instead.
Agreed. Added a note to the MSC in eda65847.

2021-02-18 17:11 UTC, anoadragon453 commented on proposals/2403-knock.md
> +related to the knock attempt.
I think lands squarely in the ballpark of implementation detail, I've made a note mentioning this in 24f61c28.

2021-02-19 13:32 UTC, anoadragon453 commented on proposals/2403-knock.md
> +   the room.
I've left this down to an implementation detail for now, seeing as it's currently not something we're able to realistically mandate in the spec.

A note has been left in https://github.com/matrix-org/matrix-doc/pull/2403/commits/24f61c283cd39f5466e8908955bc3dcf99d9bb31.

2021-02-19 13:34 UTC, anoadragon453 commented on proposals/2403-knock.md
> +The two endpoints for the client-server API seem redundant, this MSC followed how JOIN is working
This was additionally mentioned in https://github.com/matrix-org/matrix-doc/pull/2403#discussion_r520283202. I went with the decision of just having one endpoint, with the assumption that we may combine the other redundant endpoints in the future.

2021-02-19 17:56 UTC, richvdh commented on proposals/2403-knock.md
> +validate the `prev_events` and `auth_events` that the event references. We
> the kicked server should be able to pull history from a remote server for the section of DAG it was a member of

the problem is that the kicked server has *never* been a member of the room.

2021-02-19 18:31 UTC, anoadragon453 commented on proposals/2403-knock.md
> +validate the `prev_events` and `auth_events` that the event references. We
We had [a discussion](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$ONbVOVgeEJrffOv24yUGJEAPu2jbulFLNRTKRUohsFY?via=matrix.org&via=vector.modular.im&via=envs.net) about this in #synapse-dev.

While this is a something that we'll need to solve, the underlying problem itself is quite complex. We've decided to not block this MSC on a solution for it.

2021-02-19 18:31 UTC, anoadragon453 commented on proposals/2403-knock.md
> +back to you - but what if it goes offline in the meantime?
Resolving this thread on the conclusion at https://github.com/matrix-org/matrix-doc/pull/2403/files#r579391876.

2021-02-23 17:01 UTC, richvdh commented on proposals/2403-knock.md
> +currently in said room. An example for the membership would look like the
```suggestion
"avatar_url" are optional. This membership can be sent by users who aren't
currently in said room. An example for the membership would look like the
```

2021-02-23 17:08 UTC, erkinalp approved these changes

2021-02-23 17:46 UTC, richvdh reviewed
this seems generally good to me. I've made a bunch of comments to clarify the text, but I have no objections to anything proposed technically.

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +accepting or denying the knock.
```suggestion
accepting or denying the knock.  A formal description of the changes to the auth rules is given below; 
first we summarise the semantics of the proposed changes.
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +rules from room version 5 are:
This reads confusingly - the changes to the semantics of the join rules are inherently implemented via changes to the auth rules: they aren't separate things.

```suggestion

### Auth rules

Each room version defines the auth rules which should be applied in that room version.
This MSC proposes a new room version with the following changes to the [auth
rules from room version 6](https://matrix.org/docs/spec/rooms/v6#authorization-rules-for-events):
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +* Under "5. If type is `m.room.member`", the following will be added:
```suggestion
* Under "5. If type is `m.room.member`", insert the following after "e. If membership is `ban`":
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +    iii. If the `sender`'s membership is not `ban`, `knock`, `invite` or `join`, allow.
we don't allow knock->knock? I think allowing it is less likely to confuse the state res algorithm, unless you have good reasons to forbid it.

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +      the `state_key` is the invitee.
The "not any other user" phrase is more confusing than helpful.

```suggestion
    - Both the `sender` and `state_key` fields are set to the user ID of the knocking
      user. This is different to an `invite` membership event, where the `sender` is the inviter and
      the `state_key` is the invitee.
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +  a. If `membership` is `knock`:
```suggestion
  f. If `membership` is `knock`:
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +    - a.ii is justified as one user should not be able to knock on behalf of
```suggestion
    - f.ii is justified as one user should not be able to knock on behalf of
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +    - a.iii is justified as knocks should not be allowed if the knocking user
```suggestion
    - f.iii is justified as knocks should not be allowed if the knocking user
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +invites. The user's homeserver will then send an invite - over federation if
```suggestion
invites. The accepting user's homeserver will then send an invite - over federation if
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +knock.
:thinking: I wonder what happens if both try to accept the invite... there might be a race? I suspect the client will get an error which it might need to handle?

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +### Membership change to `invite`
it might be worth adding a section here for the initial change to `knock`: what are the C-S and S-S APIs involved?

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +rescinded their knock.
it might be clearer to split the two cases into separate sections: they are somewhat different.

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +/_matrix/client/r0/rooms/{roomId}/leave`](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-rooms-roomid-leave).
... presumably the server does a send_leave over federation if necessary?

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +A dumb thing we could easily do here is to trust the leave event implicitly
https://developers.google.com/style/inclusive-documentation#ableist-language

```suggestion
A simple thing we could easily do here is to trust the leave event implicitly
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +  Note that:
I don't think making this part of the list item helps readability.

```suggestion
Note that:
```

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +The newly proposed endpoint requires authentication and can be rate limited.
put this under the section for the endpoint in question?

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +```
should we not return the room id?

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +### `POST /_matrix/client/r0/knock/{roomIdOrAlias}`
link to https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-join-roomidoralias for comparison?

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +A problem arises for discovery of knockable rooms. Ideally one wouldn't have
needs a link to https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-publicrooms for context.

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +The two endpoints for the Client-Server API seem redundant, this MSC followed
I only see one endpoint proposed, so this is presumably outdated.

2021-02-23 17:46 UTC, richvdh commented on proposals/2403-knock.md
> +* `POST /_matrix/client/unstable/xyz.amorgan/rooms/{roomId}/knock`
outdated?

2021-02-23 17:49 UTC, richvdh commented on proposals/2403-knock.md
> +### Membership change to `invite`
I guess an alternative way of expressing this is: it feels odd to read through the MSC and realise that we've got to "how to transition *out* of `knock`" before seeing "how we transition *into* `knock`". It might be worth putting the docs for the new APIs higher up in the doc: there's a bit of a causality fail right now.

2021-02-24 18:33 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iii. If the `sender`'s membership is not `ban`, `knock`, `invite` or `join`, allow.
I think it was originally prevented as there wasn't really any good reason for it. But thinking about it now, it'd be nice to update your pending knocks when you change your display name.

Given one can instead just rescind and knock again, there isn't really any good reason to forbid it.

2021-02-24 18:40 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iii. If the `sender`'s membership is not `ban`, `knock`, `invite` or `join`, allow.
Note to self, change L70 as well.

2021-02-24 18:42 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knock.
By "both" are you referring to the homeserver and the client automatically accepting the invite?

Ideally the homeserver would try to accept the invite before sending it down to the client, I suppose.

2021-02-24 18:43 UTC, anoadragon453 commented on proposals/2403-knock.md
> +/_matrix/client/r0/rooms/{roomId}/leave`](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-rooms-roomid-leave).
That's implied, but I should probably specify that here indeed.

2021-02-24 18:44 UTC, anoadragon453 commented on proposals/2403-knock.md
> +```
Oh yes, I think this might've been a copy/paste error from the `/join/!room_id` endpoint which was later discarded.

2021-02-24 18:49 UTC, richvdh commented on proposals/2403-knock.md
> +knock.
> By "both" are you referring to the homeserver and the client automatically accepting the invite?

yes.

> Ideally the homeserver would try to accept the invite before sending it down to the client, I suppose.

well ok, but accepting invites isn't instant... I guess it could withhold the invite from the client until the join completes (or fails). Which leads me to... what happens when the join fails?

2021-03-01 12:42 UTC, Kegsay commented on proposals/2403-knock.md
> +      in the room.
Doesn't this allow knock spam then?

2021-03-03 16:37 UTC, anoadragon453 commented on proposals/2403-knock.md
> +      in the room.
Are you referring to the fact that knock->knock transitions are allowed? This has been noted before, and the current consensus is to enforce moderation in the form of banning the spammer/ACL'ing their homeserver or disabling knocking altogether until the spammer gets bored.

Existing discussions on the topic: 

https://github.com/matrix-org/matrix-doc/pull/2403#discussion_r418128235
https://github.com/matrix-org/matrix-doc/pull/2403#discussion_r529723767
https://github.com/matrix-org/matrix-doc/pull/2403#discussion_r379017812

And the discussion resulting in allowing knock->knock:

https://github.com/matrix-org/matrix-doc/pull/2403#discussion_r581226456

2021-03-03 16:47 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knock.
This seems to be slipping into implementation territory (though perhaps we could solve things by speccing a way for the client to ask the server to automatically accept invites on its behalf).

I suppose at that point the server would pass the invite down to the client, who would then try itself, and if that fails the client will either continue trying (in which case it's bad client code) or would present the error to the user and ask to manually intervene, similar to how users deal with stuck invites today. Ideally joins would just work though.

2021-03-03 17:25 UTC, anoadragon453 commented on proposals/2403-knock.md
> +### Membership change to `invite`
Agreed. I've moved them up near the top of the doc, which does seem a bit more sensible, at least to me.

2021-03-04 20:39 UTC, erkinalp approved these changes

2021-03-09 17:16 UTC, anoadragon453 commented on proposals/2403-knock.md
> +knock.
Added a note to this effect in 68d2d7cf.

2021-03-09 17:21 UTC, erkinalp requested changes

2021-03-09 17:21 UTC, erkinalp commented on proposals/2403-knock.md
> +discretion.
I oppose this because this means a non-client-initiated event. Interpreting invite+knock as join, on the other hand, does not entail server issuing events in behalf of client

2021-03-09 17:26 UTC, anoadragon453 commented on proposals/2403-knock.md
> +discretion.
The spec cannot stop homeservers from automatically accepting invites on a user's behalf.

2021-03-16 18:17 UTC, anoadragon453 commented on proposals/2403-knock.md
> +`m.room.member` state event. This state event indicates that when a user
> The question here is whether we want (read: whether potential users need) a knock to be only slightly heavier than, say, a presence notification - or rather that knocks be auditable permanent records of attempts to gain entry to the room. Do you have any idea? I don't find it in the MSC.

That's a good way to phrase it. I think it is useful to have knock history for auditability purposes. Being able to figure out whether a user joined via a straight invite or via a knock originally can be useful categories when designing features/bots. I don't think that's a question that's been asked before, and a conclusion for that in the MSC would be really beneficial.

> I think that if we allow state changes from outside that basically changes the security model under which we were designing things so far - that nothing can change the room state from "outside" of it (both in terms of interacting user and a homeserver), and joining has been a single point of interaction to change an "outside" user (and homeserver) status to "inside". By adding a knock as a state we're adding another point of interaction (in terms of API, quite literally) that needs extra protection.

You're right that it allows people outside the room to change a limited subset of the room state, just as a join does. One can no longer assume a user's membership state is immutable unless they are in the room or are performing a join. But I don't think the current model should limit us to extend it to another entry point. Fundamentally these state changes depend on the event auth rules and current state of the room. One can still disable knocking, just as they do public joins, by augmenting that state.

From the implementation side of EDUs, I'm a bit worried about needing to manage the edge cases when we step outside of using room state. For instance, device updates and key sharing work this way and we've had many implementation bugs with the edge cases.

2021-03-23 13:46 UTC, erkinalp requested changes

2021-03-23 13:46 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
Really no harm accepting knocks to public rooms as the sender may not have received the change in the meantime.
```suggestion
    i. If the `join_rule` is anything other than `public` or `knock`, reject.
    ii. If `sender` does not match `state_key`, reject.
    iii. If the `sender`'s membership is not `ban`, `invite` or `join`, allow.
    iv. Otherwise, reject.
```

2021-03-23 14:31 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
What do you mean by "the sender of the knock may not have received the change in the meantime".

2021-03-23 15:13 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
The client's state may be behind the homeserver's and the room may become public in the meantime, whereas it was a knock-and-accept room before.

2021-03-23 16:08 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
It'd be a bit confusing for room admins if people knocked on a room that was public. I don't think we should support that just for that highly unlikely edge case.

2021-03-23 16:12 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
We cannot assume the latency is low enough, hence we need to account for that edge case.

2021-03-23 16:17 UTC, anoadragon453 commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
By that logic we should allow anyone to ban anyone in case someone is set as an admin on the server and the client hasn't caught up yet.

2021-03-23 16:22 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
No, that logic only applies in cases that *effective power increases*, such as from ban to unban, from "cannot do A" to "can do A".

2021-03-23 16:24 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
That kind of logic will really only apply in cases *effective power of all affected users increase*.

2021-03-23 17:25 UTC, KitsuneRal commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
I'd say there's really no harm in the client syncing its state in that edge case. The fewer events take part in auth rules, the better.

2021-03-23 17:37 UTC, erkinalp commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
> I'd say there's really no harm in the client syncing its state in that edge case.

Then, every client will need to try at least twice to ensure a knock actually goes through. Which is a huge communication overhead.

2021-03-23 18:20 UTC, erkinalp approved these changes

2021-03-23 18:32 UTC, KitsuneRal commented on proposals/2403-knock.md
> +    iii. If the `sender`'s membership is not `ban`, `invite` or `join`, allow.
That doesn't seem aligned with the earlier words in "Current membership". Either here, or "Current membership" should be updated.

2021-03-23 18:32 UTC, KitsuneRal commented on proposals/2403-knock.md
> +While we could send easily send the leave event as part of a generic
```suggestion
While we could easily send the leave event as part of a generic
```

2021-03-23 18:32 UTC, KitsuneRal commented on proposals/2403-knock.md
> +partake in. That is why this proposal enables the a `knock` join rule, in
```suggestion
partake in. That is why this proposal enables the `knock` join rule, in
```

2021-03-23 18:32 UTC, KitsuneRal commented on proposals/2403-knock.md
> +for users of a room to review all current knocks.
How much is displaying knocks by default valuable for users that cannot invite?

2021-03-23 18:32 UTC, KitsuneRal commented on proposals/2403-knock.md
> +`m.room.member` state event. This state event indicates that when a user
The ephemeral nature of EDUs and (historically) a limited number of use cases for them does make them more prone to breakage and harder to debug, I admit. That said, if we go with the current state event way, I'd really prefer to not give an excuse to knocking just for the sake of getting something in return (see my comment on `knock_state`).

2021-03-23 18:37 UTC, KitsuneRal commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
Certainly not _every_ client and not with _every_ knock, given that it's an edge case.

2021-03-23 22:22 UTC, ara4n commented on proposals/2403-knock.md
> +    iv. Otherwise, reject.
allowing knocking on a public room would just increase the likelihood of knock spam. it only makes sense to knock on a door which is shut. the fact there might be a race with that room becoming public is irrelevant, imo.

2021-03-23 22:23 UTC, ara4n commented on proposals/2403-knock.md
> +information sent to remote homeservers when invited their users to a room.
e.g.?

2021-03-23 22:24 UTC, ara4n commented on proposals/2403-knock.md
> +for users of a room to review all current knocks.
it mirrors real life, and means that a non-privileged user in the room can go and get the attention of someone who can invite out-of-band to let the knocker in.

2021-03-24 01:00 UTC, turt2live approved these changes
overall looks great - really exciting to land this (finally)

2021-03-24 07:43 UTC, KitsuneRal commented on proposals/2403-knock.md
> +information sent to remote homeservers when invited their users to a room.
I mean that the room directory is an example of where one could find the information on the room. Actually, I even suggest that such information be found in the room directory, rather than shared in `knock_state`, in order to make the "knocked" state as close as possible in terms of information availability to the "leave" state (since the level of trust to members in both states is the same).

2021-03-24 07:50 UTC, KitsuneRal commented on proposals/2403-knock.md
> +for users of a room to review all current knocks.
I really wouldn't mind that even in real life (by default, not always) knocking was heard to someone authorised to open the door. Matrix clients could be compared to butlers in that case. It's just a question of picking the defaults.

2021-03-24 08:02 UTC, KitsuneRal commented on proposals/2403-knock.md
> +for users of a room to review all current knocks.
One concern here is that, unlike joins, knocks can be 1) legitimately repeated; 2) are prone to be abused to spam the room. If a knock attack comes, I'd rather give users of that room an opportunity to continue undisrupted discussion instead of seeing the timeline interspersed with numerous knocks; and leave tackling the attack (if anything, by switching `join_rule` to `invite`) to room admins.

2021-03-24 08:19 UTC, ShadowJonathan commented on proposals/2403-knock.md
> +for users of a room to review all current knocks.
Maybe make a note that clients should group multiple knocks by the same people together? e.g. "X has knocked Y times", to make it minimally disruptive, yet informative.

2021-03-24 16:17 UTC, anoadragon453 commented on proposals/2403-knock.md
> +information sent to remote homeservers when invited their users to a room.
You're right that it exposes some state from the room. The state it exposes is up to the homeserver implementation, but the recommendation is clear.

The reason we choose to expose this information is to help clients with displaying a list of pending knocks. Without this state, that list would just be a list of room IDs. With the state, the list can be made up of room names, avatars and aliases.

We could ask clients to try and retrieve this information from the public room directory instead (although it's not clear whether they should use their local homeserver's directory, or some remote one). However I don't like tying the presentation of a room in a pending knock list with the public room directory for a couple reasons:

1. The room you are knocking on may not be in the public room directory, thus only some rooms you knock on you will see avatar/name information for. (Granted not all rooms will have an avatar or name to begin with).

2. Homeservers can choose to withhold public room information from remote users.

Perhaps instead of it being up to whatever homeserver implementation external users are invited/knock through, we could instead define a state event which determines what state event types are sent to external users?

2021-03-24 16:48 UTC, anoadragon453 commented on proposals/2403-knock.md
> +value `public`.
Hmm, I see what you're saying. Similar, but subtly different. Shouldn't require any change in the implementation really though. Sounds fine to me.

2021-03-24 17:00 UTC, anoadragon453 commented on proposals/2403-knock.md
> +for users of a room to review all current knocks.
> Maybe make a note that clients could/should visually group multiple knocks by the same people together? e.g. "X has knocked Y times", to make it minimally disruptive, yet informative.

That's true, and clients should probably do so anyways. Though you'd still have timeline flooding if multiple users were carrying out the attack.

It's definitely a UX/design question. Only showing knocks in the timeline for admins would mitigate the disruption of (non-admin) conversation during an attack. However it would hide an otherwise convenient display of information for users.

It's probably best if I just dump these potential benefits/pitfalls into the MSC and clients can set up their UI as they think best.

2021-03-25 19:54 UTC, KitsuneRal commented on proposals/2403-knock.md
> +information sent to remote homeservers when invited their users to a room.
I guess that would solve some issues concerning "unfederated" interaction with rooms, yes. Worth a separate MSC.

2021-03-25 20:00 UTC, KitsuneRal commented on proposals/2403-knock.md
> +for users of a room to review all current knocks.
I think it's worth stating these considerations in the MSC in order to include them in an implementation guide, rather than in the spec.

2021-03-25 21:14 UTC, turt2live approved these changes
checkmark so I know where I got to last :)

2021-03-27 01:18 UTC, kevincox approved these changes

2021-03-27 01:18 UTC, kevincox commented on proposals/2403-knock.md
> +accept this invite given they're aware that it's the result of a previous
Should we say that the homeserver **should** accept the invite?

2021-03-27 01:18 UTC, kevincox commented on proposals/2403-knock.md
> +they have access to the events it references.
Doesn't this mean that the knock will forever live on the users list as an active knock? They will never know that it has been rejected? This seems very suboptimal.

Should we provide an API to check the status of a knock that can be polled occasionally?

2021-03-27 01:18 UTC, kevincox commented on proposals/2403-knock.md
> +message, and then having each of them knock in order.
This seems like questionable advise. I think most people would want to see the reason upfront, even if it may contain undesirable content. Something like:

> goodperson asked to join the room. "I like foxes."
> badperson asked to join the room. "I hate you all."

Maybe the wording should be changed to something like "Clients should be aware that the reason is arbitrary text that can come from any user and should consider options to hide the message by default for users who don't want to see hateful, violent or otherwise unpleasant content that may have been put in the `reason` field.

Also note that there is not much different between the reason and display name. Are most clients expected to display:

> Someone knocked in this room, click to see the information they provided.

I think there are cases where that makes sense. But advising this by default seems odd.

2021-03-27 14:56 UTC, KitsuneRal commented on proposals/2403-knock.md
> +they have access to the events it references.
As the MSC says, this problem is not specific to knocks; and it is something that we live with, already. Note that its scale is limited to homeservers that are not already in the room; this will become more burning as we decentralise further but with the today's network it's more of a nuisance than a showstopper. Therefore rather than spend effort on patching the spot of nusance (forcing technical debt on client authors along the way), the underlying problem should be fixed by a separate MSC.

2021-03-27 14:57 UTC, KitsuneRal commented on proposals/2403-knock.md
> +is banned, is invited or is currently in the room cannot knock on it.
See https://github.com/matrix-org/matrix-doc/pull/2403/files#diff-9dcacf9adb620c5346eba2f70f71bd50ed4f85a5e2844ac130e112165ce35c06R69

2021-03-27 15:29 UTC, kevincox commented on proposals/2403-knock.md
> +is banned, is invited or is currently in the room cannot knock on it.
That is what I am referencing isn't it? It does say if they aren't allowed. My point is that

1. It would be nice to be explicit here. That section only mentions "(e.g. they are banned)".
2. It would be nice to provide better error messages for cases such as "you have already knocked" and "you are already in the room", if only to help implementers and buggy clients.

2021-03-27 15:57 UTC, erkinalp requested changes

2021-03-27 15:57 UTC, erkinalp commented on proposals/2403-knock.md
> +can decide to reject it instead.
```suggestion
After a knock in a room, a member of the room can let the knocker in, or they
can decide to reject it instead.
```

2021-03-27 15:57 UTC, erkinalp commented on proposals/2403-knock.md
> +   and they are inviting the knocker into the room.
```suggestion
 - `join`: In this case, the knock was accepted by someone inside the room.
```

2021-03-27 15:57 UTC, erkinalp commented on proposals/2403-knock.md
> +discretion.
This dance can also be eliminated if we define the result of accepted knock as `join`, rather than invite.

2021-03-27 16:14 UTC, kevincox commented on proposals/2403-knock.md
> +they have access to the events it references.
I see. Should we point this out some how that clients should be sure to hide old knocks as they may have been declined? The worse case I see here is that the user knocks again and either causes bother or gets a 403.

2021-03-27 17:01 UTC, KitsuneRal commented on proposals/2403-knock.md
> +they have access to the events it references.
How would they determine if a knock is "old" though?

2021-03-27 17:03 UTC, KitsuneRal commented on proposals/2403-knock.md
> +they have access to the events it references.
Also - getting a 403 is already a good sign that the user has been bumped; Quaternion uses exactly that kind of response to drop stale invites from the room list.

2021-03-27 17:12 UTC, KitsuneRal commented on proposals/2403-knock.md
> +discretion.
Not without changing the shape of the federation API: as for now, a join should originate from the joining side, not from the receiving side. Unless I'm mistaking, you can only invite a user on an external homeserver, not force-join it (and that's actually a good thing because servers can't trust each other).

2021-03-27 17:18 UTC, KitsuneRal commented on proposals/2403-knock.md
> +they have access to the events it references.
Hm, wait, actually there's no chance to get a 403 unless the user has been banned. Otherwise knocking again would just produce another knock, by the current reading of the MSC :(

2021-03-27 17:29 UTC, erkinalp commented on proposals/2403-knock.md
> +discretion.
> as for now, a join should originate from the joining side

With my proposal, the join would still originate from the joining side as `knock` and the receiving side would merely "attest" it, i.e. if `join_rule` is  not `invite`, memberships state transistion of `knock` to `join` would be an allowed state transistion.

> Not without changing the shape of the federation API

You would take the signed knock as attestation, i.e. the knock-join endpoint would require supplying both the knock record and acceptance event.

2021-03-27 17:57 UTC, KitsuneRal commented on proposals/2403-knock.md
> +discretion.
That doesn't come from your suggested changes. Please elaborate how you propose to changes the API, in particular what you mean by that "entirely separate" knock-join endpoint, and the sequence of calls between the homeservers. Bare in mind that a knock and its acceptance may be days away from each other.

2021-03-27 18:20 UTC, erkinalp commented on proposals/2403-knock.md
> +discretion.
```suggestion
### Membership change to `join`

The knock has been accepted by someone in the room.

The user who is accepting the knock must have the power level to perform
invites. The accepting user's homeserver will then send an invite - over federation if
necessary - to the knocking user. The knocking user may then join the room as
if they had been invited normally.

To accept a knock, the client should call `POST /_matrix/client/r0/rooms/{roomId}/ack_knock`
with a knock accept event, that also includes the event body of knock body in it, as signed by
the signature of knocking user's homeserver.

If the knocking user is on another homeserver, then the homeserver of the
accepting user will call [`POST /_matrix/federation/v2/ack_knock/{roomId}/{eventId}`]
on the knocking homeserver to inform it that the knock has been accepted and user has been
added to the room.
```

In this design, knock accept event also includes knock event in its body and if that knock event
supplied in the accept event (including its signature) mismatches a currently valid knock, then 
the join will be rejected.

2021-03-27 19:31 UTC, kevincox commented on proposals/2403-knock.md
> +they have access to the events it references.
I think that is the problem. There is no good answer for if a knock is old. But we should be explicit about that so that clients don't look around for a way to tell. Clients are then up to pick their UX for displaying knocks which may or may not have been answered.

2021-03-27 19:49 UTC, erkinalp commented on proposals/2403-knock.md
> +message, and then having each of them knock in order.
> should consider options to hide the message by default 

That will not work with application question use case, where the members actually want to read the answers of the knocker.

2021-03-27 20:40 UTC, KitsuneRal commented on proposals/2403-knock.md
> +discretion.
Your design is still very patchy, and it's hard to validate it. Too many loose ends. You may want to draw a sequence diagram - for yourself, not here - and check what data flows through each API call before the next iteration; because either your explanation is too incomplete or you have gaps all over the design.
Just a few questions before I stopped trying to understand what you're proposing:
1. I understand that English is not your first language but please double-check what you are suggesting. `the event body of knock body` doesn't make any sense to me. Did you mean `the body of the knock event`?
2. What is "invite accept event"? Sorry but I couldn't find it across the spec and I can't get what you mean by that.
3. How does the client have the "accept event" (whatever it is) signed by the "receiving server" if it's just about to send this event to its homeserver?
4. Where does the client take the signature of the original knock event from? Clients normally don't receive event signatures as produced by remote servers, it's a prerogative of homeservers to generate and check them.

2021-03-28 03:12 UTC, turt2live commented on proposals/2403-knock.md
> +they have access to the events it references.
This is unlikely to be a major problem in practice given how servers will most likely implement it, and the social scenarios in which it comes up. In particular, servers are likely to optimize out the second attempt at knocking, instead preferring to claim the user already knocked: the server wouldn't have the context that the knock was rejected, so as far as it is concerned the knock is still valid. A server could retry the knock over federation, though that means a whole federation round trip and perceived slowness - Synapse for instance doesn't try a join over federation if it thinks the user was banned, even if the ban may have been lifted.

If the server is lucky enough to be a member of the room through some other user, it will have seen the reject and can send it over `/sync` to the user. This is probably about half of the cases.

In the event a server does decide to retry the knock over federation, the room could end up being "spammed" with knocks or otherwise appear as abusive behaviour, though at the point where someone was declined a knock a ban isn't very far off. This is similar to being kicked from a room for spamming: the spammer would just rejoin and continue, being banned as a result. Rooms could skip the bans instead of just rejecting the knock, if they wanted. 

Knocking in the public federation is somewhat more likely to involve out-of-band processes which help guide people into the right room (for instance, if your matrix ID isn't known to a crowdfunding platforming, they could have you knock on a supporters room with a unique code to complete the link). Rooms which end up on the directory for the public federation are somewhat "doing it wrong" given they probably want to be publicly joinable instead (they would be inundated with spammy requests, regardless of people accidentally trying to knock twice).

In private federations, such as corporate deployments, it's more likely that the person knocking can be approached through some other means and told "hey, don't do that". Private federations would likely use the room directory for other reasons relating to discoverability, and would have different social representations of what that would mean.

This is definitely something we should fix, but I don't think it's a blocker for this MSC. The solution is likely far more complicated than this MSC can handle, and given the above I don't think this MSC would be blocked by a future MSC which fixes this problem. Instead, we should land knocking (with all of the notes and considerations I've outlined here, and are outlined in the MSC itself), and take a look at fixing unbans/rejections/etc over federation properly.

2021-03-28 03:15 UTC, turt2live commented on proposals/2403-knock.md
> +accept this invite given they're aware that it's the result of a previous
That feels a bit invasive, even if it is the expected behaviour. I'd prefer it if we kept it as implementation-specific and revisit in another MSC later on.

2021-03-28 03:18 UTC, turt2live commented on proposals/2403-knock.md
> +message, and then having each of them knock in order.
(worth noting that the spec cannot and should not prioritize examples of "harmful" content - the spec intentionally leaves "harmful" and similar such descriptors up to the implementations/users, not itself. What is harmful to one person might not be harmful to another, for better or worse.)

"Clients must take care..." can also mean "our user base doesn't care, so we show the reason verbatim". The wording would have to change before landing in the spec, but I believe the intention is to tell clients that there is a potential for abuse here and that they should consider that, even if that means doing nothing.

2021-03-28 03:20 UTC, turt2live commented on proposals/2403-knock.md
> +discretion.
It's extremely hard to support autojoining without opening a can of worms/security vulnerability. This would be something that requires extensive thought and careful review, which won't be able to be provided over a comment thread on github. This is the sort of thing we'd solve in a later MSC and room version, after having this system in place as-is.

Knocking is a pretty big feature, so there's a good chance that this MSC isn't perfect. However, it's the best it can be before bikeshed laws start to take effect. Future MSCs can consider the cases where knocking fell short.

2021-03-28 03:22 UTC, turt2live commented on proposals/2403-knock.md
> +can decide to reject it instead.
this seems overly nitpicky, and without sign-off.

2021-03-28 03:24 UTC, turt2live commented on proposals/2403-knock.md
> +mentioned above.
like the invite state, there's no requirement to actually include those state events. It's helpful for aesthetic reasons, but this section of the MSC seems to be reminding readers what *could* be there to help them review the API format. It doesn't appear to be mandating that those state events be present.

2021-03-29 01:55 UTC, merged

2021-03-29 16:15 UTC, anoadragon453 commented on proposals/2403-knock.md
> +is banned, is invited or is currently in the room cannot knock on it.
The message to include is up to the implementation, but yes the error should be `403`, `M_FORBIDDEN` if you are unable to join the room due to your currently membership state (ban, invite, join).

2021-04-30 15:21 UTC, turt2live commented
merged 🎉