[WIP] MSC2545: Emotes
matrix-org/matrix-doc pull request #2545
Opened 2020-05-15 09:43 UTC by Sorunome

WIP becasue stuff and things

[Rendered](https://github.com/Sorunome/matrix-doc/blob/soru/emotes/proposals/2545-emotes.md)

2020-05-15 10:05 UTC, jplatte commented on proposals/2545-emotes.md
> +are set with a state event of type `im.ponies-room_emotes` and a blank state key. The contents are
Is this a typo?

```suggestion
are set with a state event of type `im.ponies.room_emotes` and a blank state key. The contents are
```

2020-05-15 10:35 UTC, anoadragon453 commented
People wanting to try out an implementation of custom emotes on the web can use their existing homeserver account through [this riot-web instance](https://ponies.im/_matrix/client).

2020-05-15 10:47 UTC, Sorunome commented on proposals/2545-emotes.md
> +are set with a state event of type `im.ponies-room_emotes` and a blank state key. The contents are
woops, typo, thanks

2020-05-15 11:02 UTC, anoadragon453 commented on proposals/2545-emotes.md
> + - Tag rooms as "these emotes can be used anywhere" inside of account data somehow
I don't think it would be too much extra content to include this in this MSC. It wouldn't be too bike-sheddy of a concept :)

2020-05-15 11:03 UTC, Sorunome commented on proposals/2545-emotes.md
> + - Tag rooms as "these emotes can be used anywhere" inside of account data somehow
It is WIP as we discussed and soru didn't want to make an MSC at all but people wanted soru to make one so she used this as a dump field for the state of how things currently are (thus also the `im.ponies` prefixes) and also tossed in things she is interested in adding in here down the road

2020-05-15 11:17 UTC, Sorunome commented on proposals/2545-emotes.md
> +The emotes are defined inside of a dict called `short`, meant as the "short and easy" representation
The initial idea was to eventually add more keys for optional metadata or something. However, if you want to have many emotes, you quickly hit the 65k limit, so this is just about the smallest representation needed. The wrapping into `"short": {}` is just 11 characters and provides more flexibility. Dunno

2020-05-15 14:17 UTC, jcgruenhage commented on proposals/2545-emotes.md
> + - Tag rooms as "these emotes can be used anywhere" inside of account data somehow
So you'd want someone else to flesh this out more?

2020-05-15 14:19 UTC, Sorunome commented on proposals/2545-emotes.md
> + - Tag rooms as "these emotes can be used anywhere" inside of account data somehow
Soru didn't spend some time thinking about how to do this well yet. If others have ideas, they are happy to propose. Given enough time, soru will also write her own thing. She simply didn't give this enough thought yet, thus it is "just" in the ideas section.

2020-05-15 17:54 UTC, MTRNord commented
> 
> 
> People wanting to try out an implementation of custom emotes on the web can use their existing homeserver account through [this riot-web instance](https://ponies.im/_matrix/client).

Fluffychat Android works too :)

2020-05-19 21:18 UTC, turt2live reviewed
Generally seems to be in a sensible direction, though the duplicated effort for custom emoji is a bit bothersome :(

2020-05-19 21:18 UTC, turt2live commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
This would need a comparison to https://github.com/matrix-org/matrix-doc/pull/1951 which aims to cover everything from distribution, pack building, rendering, and interaction with 3rd party pickers.

2020-05-20 10:07 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
as #1951 uses a separate state event for every single emote it doesn't seem to be very practical: Managing / editing isn't only more difficult for a client to achive, but you have significantly more metadata attached with every single emote. If you have many (on discord there are people who have many hundreds of emotes....) that is a lot of unneeded overhead.

But yes, adding some comparison section seems appropriate further down the road when this is more towards its finished state.

2020-05-20 10:19 UTC, Sorunome commented on proposals/2545-emotes.md
> + - Tag rooms as "these emotes can be used anywhere" inside of account data somehow
This is added now, would be great if someone could look over it

2020-05-20 11:46 UTC, MatMaul commented
What about adding a mandatory level of indirection ?

`im.ponies.room_emotes` would only contains something like:
```
{
  "packs": ["im.ponies.room_emotes.mypack1", "im.ponies.room_emotes.mypack2"]
}
```
and then use what is proposed here inside `im.ponies.room_emotes.mypackX`.

This allows bundling and updating packs independently.

2020-05-20 11:56 UTC, Sorunome commented
> What about adding a mandatory level of pack indirection ?
> 
> `im.ponies.room_emotes` would only contains something like:
> 
> ```
> {
>   "packs": ["im.ponies.room_emotes.mypack1", "im.ponies.room_emotes.mypack2"]
> }
> ```
> 
> and then use what is proposed here inside `im.ponies.room_emotes.mypackX` state events.
> 
> This allows bundling and updating packs independently, and overcome the 65k limit by quite a margin.

Not quite sure what you mean, here. That, for room emotes, you can specify other state keys that just extend that one pack?

While not explicitly stated in this MSC (yet?), if multiple packs have the same `pack.short` they are expected to be merged together - that way you can also overcome the 65k limit, however, when adding it to your account data you will have to add multiple entries for just a single pack. Maybe it would be better to explicitly add related state keys?

2020-05-20 12:00 UTC, Sorunome commented on proposals/2545-emotes.md
> +is `im.ponies.user_emotes`. The content is as following:
Added `m.` suggested codes in parenthesis now

2020-05-20 12:09 UTC, MatMaul commented
Ok nevermind, I misread. I thought `im.ponies.room_emotes` was the state key, not the type.

2020-05-20 12:19 UTC, Sorunome commented on proposals/2545-emotes.md
> +is `im.ponies.user_emotes` (`m.emotes`). The content is as following:
for now it is `im.ponies.user_emotes`, but once this is more finalized to actually be merged it'll be `m.emotes`

2020-05-20 12:19 UTC, Sorunome commented on proposals/2545-emotes.md
> +pack, whereas the default one would be a blank state key. E.g. a discord bridge could set as state key
The difference is that that one has by default a `pack.short` of "room"

2020-05-20 12:20 UTC, Sorunome commented on proposals/2545-emotes.md
> +   and casting it all to lowercase.
yeah, no empty string

2020-05-20 12:20 UTC, Sorunome commented on proposals/2545-emotes.md
> + - `pack.short`: A short identifier of the pack. Defaults to the normalized state key, and if the state
Any more appropriate name suggestion?

2020-05-20 12:20 UTC, Sorunome commented on proposals/2545-emotes.md
> +    "short": "some_discord_guild"
Oh, here it is, good idea

2020-05-20 12:21 UTC, Sorunome commented on proposals/2545-emotes.md
> +    ":other-emote:": "mxc://example.org/other-blah"
It is actually nowhere mentioned here that an emote has to start and end with `:`

2020-05-20 12:21 UTC, Sorunome commented on proposals/2545-emotes.md
> +        "short": "new_short_name"
woops, name should have been displayname, the long name

2020-05-20 12:22 UTC, Sorunome commented on proposals/2545-emotes.md
> +pack name is used for room emotes, and "user" for user emotes.
if it exists. If `im.ponies.room_emotes` with an empty state key just contains the `short` dict for the emotes, then it falls back to "room" as explained above.

2020-06-07 10:18 UTC, ellietheoracle commented
how hard would it be to add versioning and uuids to emoji packs
like for example if i'm in a room with a sticker pack that matches the UUID and version of the pack i'm using, then it won't add those emotes to my emote list

2020-06-07 10:30 UTC, Sorunome commented
> how hard would it be to add versioning and uuids to emoji packs
> like for example if i'm in a room with a sticker pack that matches the UUID and version of the pack i'm using, then it won't add those emotes to my emote list

You already have versioning with state events - or do you mean something like `v1.0`? It would be trivial to add more information like that, or a uuid, to the `pack` object.

That being said, what if multiple packs have the same uuid but different emotes? Merge them? What if you spread one pack over multiple state events to overcome the 65k chars limit and then give them all the same uuid? Should they appear as one pack? How should that work with emote_rooms?

2020-06-07 10:43 UTC, ellietheoracle commented
> > how hard would it be to add versioning and uuids to emoji packs
> > like for example if i'm in a room with a sticker pack that matches the UUID and version of the pack i'm using, then it won't add those emotes to my emote list
> 
> You already have versioning with state events - or do you mean something like `v1.0`? It would be trivial to add more information like that, or a uuid, to the `pack` object.
> 
> That being said, what if multiple packs have the same uuid but different emotes? Merge them? What if you spread one pack over multiple state events to overcome the 65k chars limit and then give them all the same uuid? Should they appear as one pack? How should that work with emote_rooms?
if emotes are added to a pack, then the version number should be changed, and yeah i meant like a 1.0 thing, if multiple packs have the same uuid and the same version number, but different emotes, then the conflict should be reported to the user, after thinking about it might make more sense to have a last modified date instead of a version number, and it just uses the newest one, because if you want to remove an emote from a pack, then it shouldn't add it back from an older version of the pack, and i don't see how any of this is affected by it being in a room or a user account

2020-06-07 10:45 UTC, Sorunome commented
> and i don't see how any of this is affected by it being in a room or a user account

`emote_rooms` is where you say that you want emotes in a room (by room id and by state key) visible everywhere for yourself. How to handle now, if you spread one pack over multiple state events by putting the same uuid? Do you have to enable all the state keys? Should it autodetermine? If the later, wouldn't that be complex for client development?

> and yeah i meant like a 1.0 thing, if multiple packs have the same uuid and the same version number, but different emotes, then the conflict should be reported to the user

Would a user care about the version of an emote pack? How to determine which version is newer? Grammer for version numbers would need to be defined, etc.

2020-06-07 10:46 UTC, Sorunome commented
Like, maybe the uuid and versioning stuff could be added in a separate msc building onto this - the goal of this was to keep things as simple as possible

2020-06-07 10:54 UTC, ellietheoracle commented
> `emote_rooms` is where you say that you want emotes in a room (by room id and by state key) visible everywhere for yourself. How to handle now, if you spread one pack over multiple state events by putting the same uuid? Do you have to enable all the state keys? Should it autodetermine? If the later, wouldn't that be complex for client development?

ok if one pack was spread over multiple events, i would have them share the uuid and also have part numbers, like "part":1 "part":2 etc for A, mainting the order of emotes, and B, to prevent them from overlapping eachother. 

> Would a user care about the version of an emote pack? How to determine which version is newer? Grammer for version numbers would need to be defined, etc.

state events have timestamps right, so you could just use the newest state event instead of bothering with version numbers

2020-06-07 10:56 UTC, Sorunome commented
> state events have timestamps right, so you could just use the newest state event instead of bothering with version numbers

origin_server_ts can't be trusted and can easily be forged

> ok if one pack was spread over multiple events, i would have them share the uuid and also have part numbers, like "part":1 "part":2 etc for A, mainting the order of emotes, and B, to prevent them from overlapping eachother.

What would it need part for? It shouldn't matter if they are ordered correctly or not, emotes are an unordered set

2020-06-07 11:02 UTC, ellietheoracle commented
> > state events have timestamps right, so you could just use the newest state event instead of bothering with version numbers

oh you could just put a modified tag in then with like unixtime or something
> What would it need part for? It shouldn't matter if they are ordered correctly or not, emotes are an unordered set

the most important reason for the part value is to distinguish continuations of the pack from updates and being able to order the emotes could matter to some pack maintainers, i would want to be able to do that for example

2020-06-07 11:05 UTC, Sorunome commented
> oh you could just put a modified tag in then with like unixtime or something

In a federated system there is no one true timesource. That is a mathematically unsolvable problem.

> the most important reason for the part value is to distinguish continuations of the pack from updates and being able to order the emotes could matter to some pack maintainers, i would want to be able to do that for example

Updates would replace the previous state event. You don't need any "part" attribute for that. As for ordering, you could say they are ordered alphanumerically by the state key.

2020-06-07 11:09 UTC, ellietheoracle commented
> In a federated system there is no one true timesource. That is a mathematically unsolvable problem.

right ok, could just be an integer like, every time a pack is modified, the version number is just bumped

> Updates would replace the previous state event. You don't need any "part" attribute for that. As for ordering, you could say they are ordered alphanumerically by the state key.

 oh right ok not important then

2020-06-07 11:21 UTC, ellietheoracle commented
another thing about packs split over multiple state events, is that there maybe should be some sort of indicator that the pack is a slave pack and not the like, source pack or the pack where the avatar and name are held, with the possibility of adding more data to a pack later

2020-06-20 10:38 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Done, added a comparison block

2020-06-20 13:09 UTC, auscompgeek commented on proposals/2545-emotes.md
> +property `data-mx-emote` is introduced. A client may chose to ignore the size attributes of emotes
How should a `data-mx-emote` attribute with a value be interpreted? If a value would have no significance, should a `class` be used instead?

2020-06-20 14:15 UTC, Sorunome commented on proposals/2545-emotes.md
> +property `data-mx-emote` is introduced. A client may chose to ignore the size attributes of emotes
This is dependent on the client. A client may chose to ignore it, a client may chose to add a class. A client may chose to do something completely different. This is there to signal the client "Hey, this is an emote!"

Current things in the spec seem to work by adding `data-mx` properties, such as `data-mx-color` and `data-mx-bg-color` and `data-mx-spoiler`, so this seems to be in-line with that.

2020-06-20 16:18 UTC, auscompgeek commented on proposals/2545-emotes.md
> +property `data-mx-emote` is introduced. A client may chose to ignore the size attributes of emotes
We already have `code` using `class`, although I wonder if that's just a historical accident and the spec team would prefer to not have more `class`.

2020-06-23 15:12 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
@ellietheoracle @Sorunome I'm going to request that the emote pack UUID/versioning discussion continue here in this thread so we don't spam the discussion overview.

As for my own take on it, I think it may be over-complicating things. If I understand correctly, it could be used to solve two problems: deduplicating packs across rooms, and automatically dealing with different versions of a pack across different rooms, where one may be improved and marked with a high version number.

For the second problem, I believe this could spiral into a lot of edge cases, including specifying version semantics, so it should probably be best left to a separate MSC, or otherwise just putting the burden on the user to choose between packs - which, as they are relatively easy to compare, doesn't sound like a particularly bad solution.

As for de-duplication, let's consider the use-case where the user is in two rooms, who each have the same emote pack, and don't want to see two emotes when they search for `coolemote`.

Being able to set which emotes you would like to see globally partially solves this by allowing only one emote pack to show globally. So when you're in other rooms, you won't see two sets of the same emotes. But what about when you're chatting in the room with that pack that you've chosen not to show globally?

Now you will see both the global emote pack, and the one for the current room - meaning duplicated emotes again.

UUIDs could solve this problem, but indeed we can't currently decide which pack is better, and thus to show. To solve this problem, we *could* add an option to disable an emote pack for a room. However, I'm not entirely convinced that this solves all edge cases here, or that it should be a problem that we try to solve in this MSC.

If all of this becomes an epic, then I say it's best to leave out and fix separately.

2020-06-23 22:22 UTC, ellietheoracle commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
it still seems like most of the conflicts here would be resolved by an incremental version tag, just use the newest one, and only prompt the user when two packs with the same version number have different emotes, which should in theory only occur if a client fails to bump the version number up by one, or if someone modifies the json of a pack without incrementing the number, or if two packs get out of sync in seperate rooms- which is a conflict that i hadn't thought of before just now and honestly have no idea how to resolve that, and it makes the whole UUID thing seem sort of pointless unless the emote packs were tracked by the  server itself which only adds more complexity, so basically i think i just made my own idea seem pointless .

2020-06-23 22:25 UTC, ellietheoracle commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
i think a much more reasonable solution would be to just give the users the power to for example, disable all the emotes in a room except two that only that room has, or maybe a filter to disable duplicate emote names, and also an option to copy an emote shortcode and import it to a room or to the users account, seem like more practical solutions

2020-06-23 22:40 UTC, ellietheoracle commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
at some point if there were deeper integration into synapse, a versioning system could be implemented, and packed without a UUID and a version number could be considered "legacy packs" and older packs would be given the oppurtunity to be upgraded, and merged .

2020-06-24 07:41 UTC, Sorunome commented on proposals/2545-emotes.md
> +said image, in this case an emote. As there is no way to encrypt content behind `<img>` tags yet,
Yeah, but that is well out of scope for this spec, as you'd also need to specify keys and thelike as attributes.

Additionally you'll want to keep an (encrypted) mapping of plaintext mxc to re-uploaded mxc so that emotes that are used often aren't constantly being re-uploaded, which would cause the server to clutter.

Soru thought it was appropriate to mention this issue here, even though it is nothing new. Related issue: https://github.com/matrix-org/matrix-doc/issues/2418

2020-06-24 07:49 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
The deduplication accross rooms could be solved by deduplicating by mxc uri, prefering the one of the local room. If you sync emote bots accross rooms you are likely doing that with a bot and thus they all have the same mxc uri.

2020-06-24 08:22 UTC, ellietheoracle commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
that's more sensible than by name, i agree on that, for priority of the tag chose to represent an mxc uri would be user, then added room packs, then local room though, as that would be what the user would be most familiar with .

2020-08-18 15:03 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Sorry if this has already been mentioned, I haven't been following the discussion here very closely.
Heads up that an "emote" is already a thing in the Matrix spec and refers to the messages with the `m.emote` msgtype: https://matrix.org/docs/spec/client_server/latest#m-emote
It'd be nice to avoid a name clash with this feature; maybe by renaming this MSC into "custom emojis" (which is how Slack names it) or something similar?

2020-08-18 15:40 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Indeed, an "emote" in messaging apps is colloquially attributed to actions: https://en.wikipedia.org/wiki/Emote

2020-08-18 16:06 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
That is very inaccurate, though. "Emoji" only refers to the emotes in unicode, *not* to custom ones.

2020-08-19 09:58 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
For one to have a "custom" something, you must still have an original something, and in this case it's called emoji?

2020-08-19 10:53 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
it's like saying that some random car is a "custom ferrari", which is inaccurate

2020-08-19 11:02 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
I'm not saying I have a perfect name for it, it was a suggestion. My point is that "emote" doesn't fit with what the feature does _and_ clashes with an existing feature in the spec.

2020-08-19 11:03 UTC, jplatte commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Why not prepend "Custom" without chancing Emote > Emoji?

2020-08-19 11:03 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> "Emoji" only refers to the emotes in unicode, not to custom one

That's the point of "custom" though, isn't it? Standard emojis are the emojis in the unicode spec, custom emojis are the emojis outside of the unicode spec.

2020-08-19 11:08 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> Why not prepend "Custom" without changing Emote > Emoji?

The issue then is that this feature isn't a custom version of emotes (as defined in Matrix and most messaging apps I know of). As I explained and anoa outlined, an emote generally refers to a `/me` action, not an emoji/image.

2020-08-19 11:13 UTC, jplatte commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Oh, sorry! I thought this was mainly about this name being taken in the event namespace, I didn't know off the top of my head that `m.emote` was for `/me` messages.

2020-08-19 11:21 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
The core problem  here is that "emote" can refer to multiple things, `/me` messages and, well, custom emote image thingies. And both are valid.

2020-08-19 11:28 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> The core problem here is that "emote" can refer to multiple things, `/me` messages and, well, custom emote image thingies. And both are valid.

FWIW I don't personally recall ever seeing "emote" being used to refer to a custom image, only "emoticon" or "custom emoji" (the latter seeming to be the industry standard).

2020-08-19 11:29 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
![image](https://user-images.githubusercontent.com/1342360/90629607-94651880-e217-11ea-836e-cb990a8aeeee.png)


For a random ecosystem data point, Discord just calls them "Emoji".

2020-08-19 11:36 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> For a random ecosystem data point, Discord just calls them "Emoji".

To add more data/context, Slack and Mattermost call them "Custom emoji".

2020-08-19 11:56 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Other platforms calling it emoji doesn't mean it is right xP Discord even calls their guilds "server" which is  very confusing.

Emote is short for Emoticon, in this case.

2020-08-19 12:06 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> Emote is short for Emoticon, in this case.

Afaik, `emot'` is, but `emote` is afaik generally known for `/me` actions.

2020-08-19 12:13 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> Other platforms calling it emoji doesn't mean it is right xP

No, but in this case it's not technically wrong (apart from discord calling them just "emoji" but imo it's still pretty close to the real thing) and following this industry standard would help less technical users understanding the feature and not get confused by what it's about.

2020-08-19 12:37 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> > Emote is short for Emoticon, in this case.
> 
> ime, `emot'` is (to make it clear you're referring to an emoticon, not an emote), but `emote` is afaik generally known for `/me` actions.

https://en.wikipedia.org/wiki/Emoticon

> An emoticon [...] short for "emotion icon", also known simply as an emote, [...]

2020-08-19 12:38 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> > Other platforms calling it emoji doesn't mean it is right xP
> 
> No, but in this case it's not technically wrong (apart from discord calling them just "emoji" but imo it's still pretty close to the real thing) and following this industry standard would help less technical users understanding the feature and not get confused by what it's about.

So calling any car a "custom ferrari" is also not wrong, then? As that would be the analogy here...

2020-08-19 12:51 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> > > Other platforms calling it emoji doesn't mean it is right xP
> > 
> > 
> > No, but in this case it's not technically wrong (apart from discord calling them just "emoji" but imo it's still pretty close to the real thing) and following this industry standard would help less technical users understanding the feature and not get confused by what it's about.
> 
> So calling any car a "custom ferrari" is also not wrong, then? As that would be the analogy here...

This analogy doesn't work, but that's because "ferrari" is a subset of "cars" whereas "custom emoji" is a subset of "emoji" (so the other way around). I would consider a ferrari a car of a specific kind (just like I'd consider a custom emoji as an emoji of a specific kind), and a non-standard ferrari (i.e. if I added stuff to it that isn't included in the standard spec) a custom ferrari (and consider "custom ferrari" to be a subset of "ferrari"), yes.

2020-08-19 13:42 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> This analogy doesn't work, but that's because "ferrari" is a subset of "cars" whereas "custom emoji" is a subset of "emoji" (so the other way around).

This is incorrect. "emoji" is a subset of "emoticon". "custom emoji" would e.g. be your own custom emoji font on how to represent emoji.

2020-08-19 13:55 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
How about `m.emoticons`?

2020-08-19 14:26 UTC, babolivier commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
> How about `m.emoticons`?

Yeah I think that'd work :)

2020-08-19 23:18 UTC, ZerataX commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
yeah to me custom emoji would be defining emoji in PUA, not inline images.

2020-09-01 08:10 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Done!

2020-09-01 08:11 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
Added deduplication by mxc URI. This should be sufficient?

2020-09-01 09:26 UTC, auscompgeek commented on proposals/2545-emotes.md
> +    ":other-emote:": "mxc://example.org/other-blah"
IMO these should include the shortcode only, and shouldn't concern itself with the input method.

2020-09-01 09:28 UTC, Sorunome commented on proposals/2545-emotes.md
> +    ":other-emote:": "mxc://example.org/other-blah"
That is exactly what soru is saying - these are only the shortcode. In the examples here they *happen* to start with `:`, but other clients may do other stuff.

2020-09-01 12:56 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +The the contents of `im.ponies.emote_rooms` (later: `m.emoticons.rooms`) could look like the following:
```suggestion
The contents of `im.ponies.emote_rooms` (later: `m.emoticons.rooms`) could look like the following:
```

2020-09-24 13:49 UTC, Sorunome commented
Changed the format from

```
{
  "short": {
    ":emote:": "mxc://blah/blubb"
  }
}
```
to
```
{
  "emoticons": {
    ":emote": {
      "url": "mxc://blah/blubb"
    }
  }
}
```

2020-09-26 22:16 UTC, ara4n commented on proposals/2545-emotes.md
> +Emoticons, or short emotes...we need them!
I'm having problems parsing this MSC due to lack of definitions.  Matrix already uses 'emote' to refer to the msgtype for an IRC-style /me action.  Emoticons however are *textual* representations of smilies etc - e.g. :), :S, or possibly (◕‿◕) for kaomoji.

It seems like this proposal is for custom emoji (i.e. inline images?)  So I'm really confused on why it seems to flip between talking about Emotes (the current PR name) and Emoticons (the h1 header) interchangeably... when it's actually talking about custom emoji?  I think?

I'm lost :/

2020-09-26 22:23 UTC, theotheroracle commented on proposals/2545-emotes.md
> +Emoticons, or short emotes...we need them!
Seems like a duplicate of https://github.com/matrix-org/matrix-doc/pull/2545#discussion_r472266607

2020-09-27 08:15 UTC, Sorunome commented on proposals/2545-emotes.md
> +Emoticons, or short emotes...we need them!
`m.emote` is for emotion - and it has been incorrectly named that way. `m.action` would have been more appropriate, as you use it to describe *actions*, not *emotions*. E.g. "/me is walking to the gym", or "/me is happy" and NOT "/me happy".

That, however, is *not* what this MSC is about. Instead, it is about Emoticons, which, well, can also be abbreviated as emotes.

Emoticons are just little images or text describing emotions or other things. Emojis are a subset of emoticons, namely those found within unicode. Custom emoji here would actually refer to a custom emoji font, your own rendering of 🦊, 🐱, etc., *not* new images. That is what custom emoticons, or custom emotes, are for.

2020-09-27 09:08 UTC, Sorunome commented on proposals/2545-emotes.md
> +Emoticons, or short emotes...we need them!
Also, emoticons are not only textual representations, as seen by the naming of the respective [unicode block](https://en.wikipedia.org/wiki/Emoticons_(Unicode_block))

2020-09-28 13:53 UTC, Cadair commented on proposals/2545-emotes.md
> +Emoticons, or short emotes...we need them!
perhaps the title of the PR should be edited to match the title of the proposal?

2020-09-30 13:30 UTC, Sorunome commented on proposals/2545-emotes.md
> +Emoticons, or short emotes...we need them!
Done!

2020-09-30 13:36 UTC, Sorunome commented on proposals/2545-emotes.md
> +Emoticons, or short emotes...we need them!
also added a paragraph on emoji and `m.emote` as it came up a few times.

2020-10-09 13:01 UTC, KitsuneRal commented on proposals/2545-emotes.md
> +`m.emtoe` is for emotion - and it has been incorrectly named this way. `m.action` would have been more
```suggestion
`m.emote` is for emotion - and it has been incorrectly named this way. `m.action` would have been more
```

2020-10-09 18:49 UTC, turt2live requested changes
Apologies it took me so long to properly review this - I've been meaning to get back to it but just haven't had enough time to formalize my thoughts into something coherent.

The overall technical approach (using state events, account data, etc) and relevant schemas seems well designed for the use cases - most of my problems with the MSC stem from the language and lack of clarity in the MSC.

The MSC reads a bit like a wishlist rather than a firm proposal, which makes it hard to translate into what the specification would say on the subject. Proposals are meant to be firm but open for discussion and changes, which essentially means it should be written at a notch below demanding.

Since this MSC was opened we've also iterated on the process to better clarify how to represent unstable/pre-spec identifiers and such. Some of my comments in this review allude to this, but I thought I should mention it here as well.

Many of my comments apply throughout the whole MSC - I feel extremely bad for dropping 31 comments (or so github tells me) on the MSC though, so I've tried to only identify the first and second occurrence. 

Apologies for dumping this massive review on you :( I've been thinking about it for a while and finally got around to writing words into boxes.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +mxc uris. All the emote sources described here are merely suggestions on where to get emotes from.
> In order to be able to send emotes the client needs to have a list of shortcodes and their corresponding
mxc uris.

technically no they don't - it's more valuable to say that clients should be getting the graphics from the same place rather than rely on the client having to support features.

> All the emote sources described here are merely suggestions on where to get emotes from.

This makes me sad because it means that the sources to follow (whatever they are - I haven't read them while writing this yet) are unlikely to land in the spec. If they are merely suggestions then this means implementations can choose to do whatever they want, which makes the MSC a bit pointless. I suspect this is not what is intended though, so I would suggest rewording this to indicate that this is the baseline sharing mechanism for how these things work.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +<img data-mx-emoticon src="mxc://example.org/emote" alt=":emote:" title=":emote:" height="32" />
Validation is important to us (as indicated on other MSCs): what if `data-mx-emoticon` has a value? what if the `src` is an `http`, `ftp`, or `mailto` scheme when the emoticon attribute is present?

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +is `im.ponies.user_emotes` (later: `m.emoticons`). The content is as following:
The unstable prefix section at the bottom covers event types - the proposal should never use unstable prefixes in the actual proposal parts.

```suggestion
is `m.emoticons`, the `content` of which is as follows:
```

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +User emotes are per-user emotes that are defined in the users respective account data. The type for that
```suggestion
User emotes are per-user emotes that are defined in the user's respective account data. The type for that
```

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +for clients or future MSCs to define custom metadata to emotes directly.
what if its an array? what is a required field? what are valid values for each of them?

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +is just a map of the shortcode to the mxc url.
Not relevant to the proposal - please remove or incorporate properly.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +are set with a state event of type `im.ponies.room_emotes` (later: `m.emoticons`). The state key denotes a possible
again with the event types

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +bridged emotes from matrix emotes separate.
the state key semantics are unclear here - what is a "pack"? is it an opaque ID?

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> + - `displayname`: An easy displayname for the pack. Defaults to the room name, if it doesn't exist
let's fix this awful convention now:
```suggestion
 - `display_name`: An easy display name for the pack. Defaults to the room name, if it doesn't exist
```

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> + - `displayname`: An easy displayname for the pack. Defaults to the room name, if it doesn't exist
what if it's not a string, or invalid, or present but empty?

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> + - `displayname`: An easy displayname for the pack. Defaults to the room name, if it doesn't exist
can packs have the same name over multiples of them?

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +Room emotes are per-room emotes that every user of a specific room can use inside of that room. They
```suggestion
Room emotes are per-room emotes that every user of a specific room can only use inside of that room. They
```

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +   if it doesn't exist.
I assume you mean this:
```suggestion
 - `avatar_url`: The mxc uri of an avatar/icon to display for the pack. Defaults to the room avatar,
   if it doesn't exist.
```

it does still raise a question about what happens if it's an invalid type, empty, or the room doesn't have one.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +   key is blank it defaults to "room".
can we call this an ID? Do we need it if it's just a version of the state key?

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +to mxc url.
remove or incorporate please - it's not relevant to the MSC as an idea

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +which room emote states should be globally accessible for that user. For that, a `room` key contains
```suggestion
which room emote states are globally accessible for that user. For that, a `room` key contains
```

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +        "short": "new_short_name"
I don't think we need these two bits of metadata here.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +the shortcode will convert to the img tag, e.g. sending `Hey there :wave:` will convert to `Hey there <img-for-wave>`.
The phrasing is slightly off on this. I'd suggest:

```suggestion
Clients should consider converting shortcodes like `:wave:` to a relevant `<img>` tag for the emoticon.
```

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +pack name and has a blank state key, then "room" is used.
Phrasing is also a bit awkward on this one as it implies a specified UX requirement, which generally do not make it into the spec:

```suggestion
Clients should also consider supporting ways for the user to find the emoticon they are attempting to send, 
such as having a syntax like `:room~wave:` to find `wave` emoticon in the current room. Alternatives might also
be `user` or pack names to search within.
```

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> + - fluffychat
this bit can be moved to the PR description for easier checkboxes and visibility - ideally linking to the implementations of the MSC directly for validation purposes within the MSC process.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +When sending an `<img>` tag in an end-to-end encrypted room, the client will make a request to fetch
it's subtle but important:
```suggestion
When sending an `<img>` tag in an encrypted room, the client will make a request to fetch
```

Matrix only supports end-to-end encryption currently (and likely only ever will tbh), however by overly specifying what kind of encryption it means the feature has to be reconsidered when/if things change.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +side and a discord bridge would plop all the discord emotes in another pack in the same room.
MSC1951 is more focused on sharing packs with users so they can indeed capture them from other places as needed. Part of the idea is to avoid overwhelming the state of the room with multiple packs, though it could indeed be useful to have a single provider's packs in one place for ease of discovery and general resource usage.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +only exists in MSC form.
MSC1951 is used in the wild, though hasn't been pushed to the surface of clients - this makes sense because they solve different areas of a similar problem.

also putting relative time in an MSC is a recipe for disaster - it'd be best to compare based on where they've been implemented, or simply exclude this statement as it doesn't help the technical merits of the MSC.

2020-10-09 18:49 UTC, turt2live commented on proposals/2545-emotes.md
> +and thus should allow for significantly larger packs.
MSC1951 is infinitely scalable while this one is limited to a few thousand emotes implicitly by using a single event for everything. This comparison seems flawed.

2020-10-09 18:51 UTC, Sorunome commented on proposals/2545-emotes.md
> +are for.
The spec should name things accurately for what they are. Clients can name things in the UI however they like - we already have a discrepancy of groups vs communities in element, for example.

2020-10-09 18:53 UTC, Sorunome commented on proposals/2545-emotes.md
> +even within riot flavours). To allow clients to distinguish emoticons from other inline images, a new
Towards the end of the MSC is a list of clients that support rendering `<img>` and those that already implement this MSC.

Or do you mean using `data-mx-emoticon` specifically? That would be only revolution and fluffychat, which wasn't added in either until about a week, which is why it is not mentioned in here yet.

2020-10-09 18:54 UTC, Sorunome commented on proposals/2545-emotes.md
> +## Proposal
Why? Different formats make sense in different situations. There are also gif emotes, webp, etc.

2020-10-09 18:55 UTC, Sorunome commented on proposals/2545-emotes.md
> +mxc uris. All the emote sources described here are merely suggestions on where to get emotes from.
> This makes me sad because it means that the sources to follow (whatever they are - I haven't read them while writing this yet) are unlikely to land in the spec.

The HTML subset for clients is merely a suggestion, and it is still in the spec. Soru does not see why it being a suggestion would prevent it form landing in the spec, especially since such things are there already.

2020-10-09 18:56 UTC, Sorunome commented on proposals/2545-emotes.md
> +is `im.ponies.user_emotes` (later: `m.emoticons`). The content is as following:
how about `m.emoticons` (unstable prefix: `im.ponies.user_emotes`)

The problem soru faced is that both `im.ponies.user_emotes` and `im.ponies.room_emotes` is to be mapped to `m.emoticons`, thus she can't just define unstable prefixes at the bottom.

2020-10-09 18:56 UTC, turt2live commented on proposals/2545-emotes.md
> +even within riot flavours). To allow clients to distinguish emoticons from other inline images, a new
I more mean that the bit in brackets isn't needed - it just makes the reader feel like this is going to turn out to be an attack on clients rather than an MSC.

Possible alternative wording would be:
> ... as such existing clients should already be able to render them, though not all clients currently handle `img` tags.

2020-10-09 18:57 UTC, turt2live commented on proposals/2545-emotes.md
> +## Proposal
sure, but without a standard then this MSC has no guiding light. There's no reason to not suggest some recommended formats and sizes.

2020-10-09 18:58 UTC, turt2live commented on proposals/2545-emotes.md
> +is `im.ponies.user_emotes` (later: `m.emoticons`). The content is as following:
The unstable prefixes section is often a table of mapped values. Putting them in the middle of the MSC makes it incredibly hard to read.

2020-10-09 18:59 UTC, Sorunome commented on proposals/2545-emotes.md
> +   key is blank it defaults to "room".
The state key could e.g. in the case of a bridge be the bridge-bot's mxid to make sure the bridged emotes do not clash. As `name` can be used for suggestions, it might make sense to have as state key `@_discord_bot:yourserver.com` and as name `discord_awesome_guild` (for a guild named "Awesome Guild")

2020-10-09 19:00 UTC, turt2live commented on proposals/2545-emotes.md
> +are for.
I don't see this as the same thing. Developers and end users alike are most likely to call these emoji whether we like it or not. We already tried to call something by its formal technical name (relationships) and ultimately had to settle for putting "rich replies" into the spec verbatim because no one was going to call it a relationship.

2020-10-09 19:00 UTC, Sorunome commented on proposals/2545-emotes.md
> +side and a discord bridge would plop all the discord emotes in another pack in the same room.
Multiple packs in one room make sense as soon as you have e.g. one room bridged to both discord and slack

2020-10-09 19:01 UTC, turt2live commented on proposals/2545-emotes.md
> +mxc uris. All the emote sources described here are merely suggestions on where to get emotes from.
It's the phrasing that is different - it's perfectly valid to land suggestions in the spec, it just has to sound like a suggestion. This ties back into the "firm and direct" things I mentioned in the overarching review comment: the proposal sounds like it's unsure about what it wants to propose when in fact it should be saying something more direct.

2020-10-09 19:01 UTC, Sorunome commented on proposals/2545-emotes.md
> +and thus should allow for significantly larger packs.
one emote in MSC1951 needs more bytes than one emote in this MSC. This MSC allows for multiple packs per room.

If you assume state keys can be infinitely long, both MSCs can hold infinite emotes per room.

In practice state keys cannot be infinitely long, though.

2020-10-09 19:02 UTC, turt2live commented on proposals/2545-emotes.md
> +   key is blank it defaults to "room".
I don't really see what the value of a display name and a name are.

2020-10-09 19:04 UTC, turt2live commented on proposals/2545-emotes.md
> +and thus should allow for significantly larger packs.
Those packs are limited by event size in this proposal though, whereas MSC1951 does not limit this. MSC1951 requires more overall resources, but if the argument is that this proposal can store more emotes per pack then the claim is false.

2020-10-09 19:04 UTC, Sorunome commented on proposals/2545-emotes.md
> +are for.
Yet the key is called `m.relates_to`. Soru was talking about the *key* name, for the actual API

There was actually already a lengthy discussion about this on this MSC, here (please note that soru still called it `m.emote` back then, to make it easier to read that conversation): https://github.com/matrix-org/matrix-doc/pull/2545#discussion_r472266607

2020-10-09 19:05 UTC, Sorunome commented on proposals/2545-emotes.md
> +## Proposal
Same argument for the HTML subset, then. What is the point of defining it in the spec if it is just a suggestion?

2020-10-09 19:06 UTC, Sorunome commented on proposals/2545-emotes.md
> +## Proposal
There is also no suggestion as to what type is allowed for `m.image` or `m.sticker`. Emotes are basically mini-versions of those, so all those formats should also apply to emotes?

2020-10-09 19:06 UTC, turt2live commented on proposals/2545-emotes.md
> +are for.
I'd honestly advocate that we just give in and call it emoji across the board.

2020-10-09 19:07 UTC, turt2live commented on proposals/2545-emotes.md
> +## Proposal
That's because of a historical failure to do so. There's now an MSC to fix that, and this MSC should not repeat the failures of the past.

2020-10-09 19:07 UTC, Sorunome commented on proposals/2545-emotes.md
> +is `im.ponies.user_emotes` (later: `m.emoticons`). The content is as following:
Sorus point is - you can't map the values.

if you put

Unstable prefix:
`m.emoticons` is `im.ponies.user_emotes` and `m.emoticons` is `im.ponies.room_emotes` noone will know when to use which unstable prefix.

2020-10-09 19:09 UTC, Sorunome commented on proposals/2545-emotes.md
> +   key is blank it defaults to "room".
State Key: machine-readable thing to make the pack unique, e.g. a uuid or the mxid of a bridge bot
Display Name: Nice name, e.g. `[Discord] Awesome Guild`
Name: short description, used for the typing syntax stated further down, e.g. `discord_awesome_guild`, and, when typing an emote, `:discord_awesome_guild~someemote:`

2020-10-09 19:10 UTC, Sorunome commented on proposals/2545-emotes.md
> +and thus should allow for significantly larger packs.
It could be that this was from an idea to be able to make one pack spread multiple state events which didn't make it in this MSC.

Got your point, will adjust :+1:

2020-10-09 19:10 UTC, turt2live commented on proposals/2545-emotes.md
> +is `im.ponies.user_emotes` (later: `m.emoticons`). The content is as following:
The section would look something like this:

> ### Unstable prefix
> For `m.emoticons` in the user's account data, use `im.ponies.user_emotes`. For `m.emoticons` in room state, use `im.ponies.room_emotes`.

It's a bit questionable to do that though - I'd probably recommend just making it consistent and accepting that existing implementations will have to change their ways slightly.

2020-10-09 19:12 UTC, turt2live commented on proposals/2545-emotes.md
> +   key is blank it defaults to "room".
that description should be `shortcode_prefix` or `description` then - two names makes no sense.

2020-10-09 19:13 UTC, Sorunome commented on proposals/2545-emotes.md
> + - `displayname`: An easy displayname for the pack. Defaults to the room name, if it doesn't exist
In `m.room.member` it is called `displayname`, soru wanted to stay consistent with existing events.

2020-10-09 19:14 UTC, Sorunome commented on proposals/2545-emotes.md
> +## Proposal
Alright, so png, gif, jpg, webm and svg all seem valid for now.

2020-10-09 19:15 UTC, Sorunome commented on proposals/2545-emotes.md
> +## Proposal
Will also add recommended sizes.

2020-10-09 19:19 UTC, Sorunome commented on proposals/2545-emotes.md
> +are for.
(just so you know, soru does not currently plan on changing this. Multiple people in here have expressed "emoticon" being a good name, and she'd love to hear more opinions from others.)

2020-10-09 19:30 UTC, turt2live commented on proposals/2545-emotes.md
> + - `displayname`: An easy displayname for the pack. Defaults to the room name, if it doesn't exist
yea, normally I would agree but I'm a bit tired of seeing it propagate through Matrix, personally :p

2020-10-11 19:36 UTC, richvdh commented on proposals/2545-emotes.md
> + - `displayname`: An easy displayname for the pack. Defaults to the room name, if it doesn't exist
sadly we have an almost equal mix of the two. I think we've previously agreed to prefer `display_name`. (we should probably update https://github.com/matrix-org/matrix-doc/blob/master/meta/documentation_style.rst#general)

2020-10-25 09:47 UTC, Sorunome commented on proposals/2545-emotes.md
> +        "short": "new_short_name"
They are local overrides, in case a user wants the emote pack to display differently for themself.

2021-03-20 18:28 UTC, erkinalp commented on proposals/2545-emotes.md
> +side and a discord bridge would plop all the discord emotes in another pack in the same room.
You can have a "store" using a room of emoji pack rooms.

2021-03-20 20:30 UTC, kevincox commented on proposals/2545-emotes.md
> +are for.
My 2c. To the protocol Unicode Emoji and Image Emoticons are quite distinct so I think it will be less confusing to implementors if we keep the terms separate and try to be precise with which one we are talking about when. 

However I agree that for user facing documentation, UX and even feature names I think that it will make sense to just call them all emoji.

2021-03-21 23:22 UTC, kevincox commented on proposals/2545-emotes.md
> +can be animated.
Can we include `image/svg+xml` for nice scalable emoticons?

2021-03-21 23:22 UTC, kevincox commented on proposals/2545-emotes.md
> +that it is easier for clients or future MSCs to define custom metadata to emotes directly.
It would be beneficial to support multiple "names" for the emoitcons. For Example 🙏 is officially called "folded hands" but is often looked up as "prayer", "praying" or even "thanks". Restricting to one name will make finding emoji very difficult.

I think this should be either made into a list, or add a field `additional_names`.

2021-03-21 23:22 UTC, kevincox commented on proposals/2545-emotes.md
> +   easily specify which pack to pick an emoticon from, should there be clashes.
I'm confused by this property.

- Isn't `display_name` a human-readable identifier for the pack?
- `^[a-z0-9-_]+$` isn't "human-readable". Especially if the user only speaks languages that don't use ASCII characters.
- Does it have to be unique?

2021-03-21 23:22 UTC, kevincox commented on proposals/2545-emotes.md
> +3. Room emoticons (emotes defined in the currently open room)
This seems too far into client UX territory.

2021-03-22 11:40 UTC, Sorunome commented on proposals/2545-emotes.md
> +   easily specify which pack to pick an emoticon from, should there be clashes.
Ah, bad wording in the MSC

This was meant to be something machines can easily parse while still being human readable, thus the limit to those characters. Meant for e.g. inputting emotes, like `:packname~emotename:` so like `:foxes~wave:` would specify the `foxes` pack.

As for uniqueness, it is impossible to require it to be unique accross all of federation.

2021-03-22 11:41 UTC, Sorunome commented on proposals/2545-emotes.md
> +3. Room emoticons (emotes defined in the currently open room)
thus suggested, not must.

2021-03-22 11:42 UTC, Sorunome commented on proposals/2545-emotes.md
> +3. Room emoticons (emotes defined in the currently open room)
will re-word that soon anyways 👍

2021-03-22 11:58 UTC, kevincox commented on proposals/2545-emotes.md
> +   easily specify which pack to pick an emoticon from, should there be clashes.
I agree that it needs more explanation.

I also am unsure that we want it at all though. Wouldn't people who speak other languages want to use their own character set? Also if they aren't guaranteed to be unique then clients can't do the simple text parsing anyways. I think it would be better UX to let the clients deal with this problem. If they want then can "slugify" the pack name or they can just allow referencing the `display_name`. For example there are many apps that allow typing in people's names with spaces and non-ascii characters and it works just fine. I don't think there is much if any benefit prescribing a syntax for composition in this RFC, especially when it has these downsides.

2021-03-22 12:00 UTC, Sorunome commented on proposals/2545-emotes.md
> +   easily specify which pack to pick an emoticon from, should there be clashes.
ooooh, yes, "slug" would be the proper term for this. Totally brainfarted here.

Letting clients slugify the display_name also sounds good 👍

2021-03-25 12:08 UTC, Sorunome commented on proposals/2545-emotes.md
> +can be animated.
the problem is that we also need some way to tell the client that those are svg sources, else it will just request a thumbnail from the server.

Also note that that is a suggestions list, and the client might actually send more

2021-03-25 12:34 UTC, auscompgeek commented on proposals/2545-emotes.md
> +can be animated.
The media server already sends an appropriate `Content-Type`. The only problem would be clients that don't support SVG.

2021-03-25 12:42 UTC, Sorunome commented on proposals/2545-emotes.md
> +    ":other-emote:": "mxc://example.org/other-blah"
Updated the MSC now so that the client should tackle deliminators on themself

2021-03-25 12:44 UTC, Sorunome commented on proposals/2545-emotes.md
> +# MSC2545: Emotes
resolving this conversation as it has this deduping and stuff

2021-03-25 12:47 UTC, Sorunome commented on proposals/2545-emotes.md
> +        "short": "new_short_name"
removed this override now as it didn't make much sense

2021-03-25 12:48 UTC, Sorunome commented on proposals/2545-emotes.md
> +side and a discord bridge would plop all the discord emotes in another pack in the same room.
That sounds like one could easily collect many rooms very quickly :/

2021-03-25 12:48 UTC, Sorunome commented on proposals/2545-emotes.md
> +   easily specify which pack to pick an emoticon from, should there be clashes.
Updated the MSC now

2021-03-25 12:48 UTC, Sorunome commented on proposals/2545-emotes.md
> +3. Room emoticons (emotes defined in the currently open room)
Is this better?

2021-03-25 12:49 UTC, Sorunome commented
Updated the MSC to

1. include stickers
2. change shortcodes from `:emote:` to `emote`, the client can wrap in `:` or `()` or whatever it wants to 
3. define a bit more metadata that proved to be useful during discussions

2021-03-25 13:28 UTC, tulir commented on proposals/2545-emotes.md
> +Stickers are recommended to have a size of up to 512x512 pixels.
Can we recommend that stickers should be rendered as 256x256, similar to emoticons using 128x128 graphics but rendering as 32x32?

My bridges and maunium-stickerpicker already set the `w` and `h` in the `info` to 256px even though the image is 512px. I'm not sure if it's a good idea to spec that exact behavior though.

2021-03-25 13:58 UTC, Sorunome commented on proposals/2545-emotes.md
> +can be animated.
there is no way to specify a content type on an `<img>` tag, though

2021-03-25 13:59 UTC, Sorunome commented on proposals/2545-emotes.md
> +Stickers are recommended to have a size of up to 512x512 pixels.
the 512x512 recommendation is meant as the image source size, kept a bit higher on purpose for high-DPI-screens or thelike. Should this be clarified better?

2021-03-25 13:59 UTC, Sorunome commented on proposals/2545-emotes.md
> +Stickers are recommended to have a size of up to 512x512 pixels.
Also, note how those are "up to" and not "of about"

2021-03-25 14:05 UTC, tulir commented on proposals/2545-emotes.md
> +Stickers are recommended to have a size of up to 512x512 pixels.
> Should this be clarified better?

Hmm, I guess actually specifying that clients should render stickers like 256px is out of scope for this MSC

2021-03-25 23:38 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +`im.ponies.room_emotes`.
```suggestion
`im.ponies.emote_rooms`.
```

2021-03-26 01:28 UTC, kevincox commented on proposals/2545-emotes.md
> +can be animated.
Sounds like we need [`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) support. (out of scope of this MSC)

But this is why the list here is important. If you send an image to a client that doesn't support it there is no way to remediate that (other than adding a new protocol for the client to ask someone else with access to the message to re-encode it) assuming an e2ee context.

2021-03-26 10:17 UTC, Cadair commented on proposals/2545-emotes.md
> + - `license`: (String, optional) The license of this pack.
Is the content of this key intended to be standardised in anyway? Most licences require a copyright line with authorship info. Is the idea that all this goes in here like "Copyright Stuart Mumford CC-BY 4.0" or that this is just a SPDX identifier? Or does the MSC just not care?

My only thought after all those questions is, if it's the "it doesn't matter, put the authorship info in here too" then is the key `license` really the most appropriate?

2021-03-26 10:36 UTC, Sorunome commented on proposals/2545-emotes.md
> + - `license`: (String, optional) The license of this pack.
it is meant as a free text form thingy

2021-03-26 10:38 UTC, Sorunome commented on proposals/2545-emotes.md
> +can be animated.
that picture tag does not seem to solve the issue of the client knowing before requesting if they would get an svg back or not at all.

2021-03-26 16:07 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +Stickers are recommended to have a size of up to 512x512 pixels.
The original Stickers MSC defined that, I think, but I don't think it made it into the spec properly?

2021-03-26 17:30 UTC, Cadair commented on proposals/2545-emotes.md
> + - `license`: (String, optional) The license of this pack.
In that case would "attribution" or a more general name be more applicable. (sorry for picking the nittiest of nits, I just want to encourage people to use it right).

2021-04-01 22:01 UTC, theotheroracle commented on proposals/2545-emotes.md
> +are for.
i imagine developers would understand the difference between unicode characters and images, it doesn't make sense to call them emoji, it would honestly be more confusing .z

2021-04-01 22:04 UTC, theotheroracle commented on proposals/2545-emotes.md
> +side and a discord bridge would plop all the discord emotes in another pack in the same room.
having more packs per room just seems much more sensible, i don't really see a point to just having a single room dedicated to a pack

2021-04-01 22:31 UTC, theotheroracle commented on proposals/2545-emotes.md
> +can be animated.
obviously the scop for another msc, but maybe the media repo could just reply with the svg as the thumbnail ? since there's not really any thumbnailing that can be done to it, beside like converting it to png, *or* instead of just giving an unkown error when an svg thumbnail is requested, it could respond  by saying "vector graphic" or something to that effect, so the client can then request the image normally ?

2021-04-01 22:39 UTC, theotheroracle commented on proposals/2545-emotes.md
> +that it is easier for clients or future MSCs to define custom metadata to emotes directly.
i think maybe a queries field would make sense, since for example on discord or slack, the emote is still only presented to the user with a single name, but internally it has several terms you can query to find the emote .

2021-05-24 15:46 UTC, turt2live requested changes, later dismissed
I don't have bandwidth to iterate the thoughts and opinions I have, but I do have some on this MSC. Just recording this so people down the line (including myself) know that there's potentially outstanding discussion to be had.

2021-07-04 10:22 UTC, Sorunome commented on proposals/2545-emotes.md
> + - `license`: (String, optional) The license of this pack.
done!

2021-07-05 05:51 UTC, SimonBrandner commented on proposals/2545-emotes.md
> +Stickers already exits in Matrix. They are reusable images one can send, usually as a reaction sent
```suggestion
Stickers already exist in Matrix. They are reusable images one can send, usually as a reaction sent
```

Signed-off-by: Šimon Brandner <simon.bra.ag@gmail.com>

2021-07-14 09:21 UTC, BBaoVanC commented
shouldn't the discord appservice bridge be listed as one of the bridges with support?

2021-07-18 17:45 UTC, Sorunome commented on proposals/2545-emotes.md
> +are for.
Since the only place that `emoticon` appears anymore is in the `usage`, can this thread be considered resolved?

2021-07-18 17:47 UTC, Sorunome commented on proposals/2545-emotes.md
> +property `data-mx-emote` is introduced. A client may chose to ignore the size attributes of emotes
`code` using `class` is probably done because that seems to be pretty standard outside of matrix with highlight.js

2021-07-18 17:49 UTC, Sorunome commented on proposals/2545-emotes.md
> +can be animated.
Additional mechanisms for `<img>` tags are out-of-scope of this MSC. While SVGs are a nice idea, a separate MSC would probably be appropriate.

2021-07-18 17:57 UTC, Sorunome commented on proposals/2545-emotes.md
> +Stickers are recommended to have a size of up to 512x512 pixels.
Resolving conversation as out-of-scope of this MSC

2021-07-19 13:59 UTC, deepbluev7 commented
If anyone is interested, I made a quick and dirty hack on top of @tulir's sticker-picker, so that it can create state events from this MSC: https://github.com/deepbluev7/stickerpicker (And implemented sending stickers in Nheko, as mentioned in the description now)

2021-07-24 15:01 UTC, Sorunome commented
Added now to also suggest image packs in claimed parents (`m.space.parent`)

2021-07-26 22:37 UTC, kevincox requested changes
This needs E2EE support.

I know that it "works" without it but every feature that leaks data leads to one of two problems:

1. Users unknowingly leak information. (Most users won't understand that stickers are a privacy issue)
2. This feature is only available in unencrypted rooms.

1 is unacceptable to me and every feature that is only available in unencrypted rooms causes friction and pain to upgrading to a private room.

I know it is tempting to kick that can down the road forever but it hurts the ecosystem. I think that this should be blocked on a proper E2EE solution to avoid shipping harmful features.

2021-07-26 22:50 UTC, deepbluev7 commented
Please comment such things in a thread. But in general I don't see, why this explicitly should support e2ee. You can already send encrypted stickers (although the media itself wouldn't be encrypted, just the sticker event). But none has any idea yet how to do encrypted state events or how to encrypt this in account data (maybe SSSS?). I don't see why this MSC specifically would be blocked by that. The only thing the user leaks is which sticker packs they use and if they upload a pack in a room, the pack is available unencrypted. This is the same as the room topic, room name, room membership, room avatar, etc. Those 4 are much more critical than what sticker packs you created, especially since people will probably subscribe to public packs more often than create private packs that shouldn't be seen by the server operators.

I don't see why stickers of all things should be blocked behind E2EE state events.

2021-07-26 23:28 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
Continuing: https://github.com/matrix-org/matrix-doc/pull/2545#issuecomment-887078884 by @deepbluev7

We need E2EE support because emotes are a significant part of a conversation and shouldn't be leaked to the homeserver. A dramatic comparison would be that we don't need to encrypt exclamation marks because they aren't as important as words. We wouldn't accept a protocol that leaks all exclamation marks to the server so why should we accept a protocol that leaks emotes?

I get that it is mitigated because they are locally cached but with a large number of stickers the server will still see the first time you download each, and can see what the content is. This is especially bad when personal sticker packs become more common and contain possible personal images.

So while there are limits to what we can do here, and commonly used sticker packs will likely be leaked to the homeservers eventually (via unencrypted rooms) I don't think we should be leaking stickers that are only used in E2EE rooms. You could also imaging the security conscious users re-upload their sticker packs and use their own sticker msx URLs.

However as this RFC currently sits a huge number of users are going to unknowingly be leaking more information that they should be homeservers. That doesn't sit well with me.

2021-07-26 23:46 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +## Security Considerations
Your comparison with the exclamation marks isn't entirely correct. It is only leaked, that you are loading a specific emote. The server can't know which message the emote is from. Since emotes are just inline images, they can easily be encrypted at the same time that inline images can be encrypted. Until then having an encrypted message body, that references unencrypted images is good enough, imo. Encrypted inline images should be a separate MSC.

Same thing for state events. An MSC for encrypted state events would be very useful, but it can be easily done independently of this MSC. Especially since there are other state events, that benefit much more from being encrypted, like the room topic. Currently most users don't know, that they leak data, if they set a topic. That usually contains sensitive data like logins, meeting locations, links and numbers.

The only thing a user leaks is sticker packs they author. This is the same as when they upload a user avatar or set a topic. So I don't see how this would be a specific consideration for this MSC. Alternatively one could argue, that the server may be able to correlate when a client downloads an emote or sticker to when the user views the event and sends a read receipt. This is however very unreliable and should be fairly rare after loading an emote for the first time or if the user opens the emote picker once.

I don't think there is a clear path to solve that, since you want the mxc URI to change on every download too. Otherwise the server can still correlate what emote is use where. A solution for that would far exceed the complexity this MSC should have imo and as such it should be a separate MSC.

2021-07-27 01:54 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
> Since emotes are just inline images, they can easily be encrypted at the same time that inline images can be encrypted.

The Security Considerations section seems to disagree.

> As there is no way to encrypt content behind `<img>` tags yet, this could potentially leak part of the conversation.

I think this is something that should be resolved before this RFC is accepted. 

> Until then having an encrypted message body, that references unencrypted images is good enough, imo.

This is the part that I disagree with most strongly. I think that before making sharing images such as this any more common we should figure out how to encrypt them so that servers can't copy and scan the contents. This strong base would allow building things like sticker packs with encryption in mind and similar. If we skip on this then all of the pieces built on top will also defer encryption support.

---

> The only thing a user leaks is sticker packs they author.

That depends on how the sticker pack is shared. Sure, if your server recommends the pack to you then it knows what the images are. But if it is shared from someone you know there is no reason that your server has to learn what the images are. 

---

> I don't think there is a clear path to solve that, since you want the mxc URI to change on every download too. Otherwise the server can still correlate what emote is use where.

I don't think that is necessary. It would be nice for the most paranoid of users but for now I just think that we need a way to attach a key (that the server never sees) to the `<img>` and to include those keys in the pack description which should be encrypted. Then all of these more paranoid options are available to be implemented on top. Sure, it isn't perfect as a single use of a sticker in an unencrypted room will leak the key to those servers. But at least packs only used in encrypted rooms are quite private and the foundation is there to build on top of.

The argument "well we leak a lot anyways, so no harm layering on more leaks" doesn't sit well with me. This is how you never end up having proper privacy in a protocol. Instead we should ensure that foundational pieces such as referencing an image can be done in a way that enabled privacy.

2021-08-10 18:14 UTC, turt2live commented
This is believed to be ready for FCP, though I haven't personally looked at it.

2021-08-11 21:32 UTC, TobiasFella commented on proposals/2545-emotes.md
> + - `info`: (`ImageInfo`, optional) The already speced `ImageInfo` object used for the `info` block of
Can you clarify on how optional this is? For sending stickers, the ImageInfo is required, while as far as i can tell it is legal according to this MSC to add stickers without ImageInfo

2021-08-12 04:21 UTC, Sorunome commented on proposals/2545-emotes.md
> + - `info`: (`ImageInfo`, optional) The already speced `ImageInfo` object used for the `info` block of
Actually, while the spec for `m.sticker` lists the `info` block as required, all its keys are not. thus, it is spec-compliant to send a blank info block (`"info" : {}`)

2021-08-24 18:44 UTC, anoadragon453 reviewed
Just some general clarifications and ideas, but nothing too dramatic. As a user I would love to see this come to Matrix - thanks for working so hard on it!

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +   this overrides the usage defined at pack level for this particular image.
What is the usecase for overriding the usage abilities per-item in pack? I can see that it would allow more flexibility, but am not sure in what situation that would be helpful.

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +There are several places where a client is expected to look for these `m.image_pack` events, mainly
```suggestion
There are several places where a client is expected to look for these `m.image_pack` objects, mainly
```

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +and stickers from all the image packs found in those rooms/spaces.
We may want to clarify that a client should only need to discover image packs for Space rooms that the user is actually in?

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +
To be sure, you're saying that image packs sent into the rooms with `type: m.space` themselves should also be shown in child rooms?

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +
Say I have a space hierarchy of:

```
A-E
|
B-C
|
D
```

where E, C and D are `m.space.child` rooms, and A and B are m.space rooms.

Should an emote from an image pack in C be shown when I'm messaging in E?

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +The the contents of `m.image_pack.rooms` could look like the following:
```suggestion
The contents of `m.image_pack.rooms` could look like the following:
```

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +Thus, specifying both the `alt` and `title` attributes is required.
We may want to consider adding a `blurhash` field to this MSC - or [MSC2448](https://github.com/matrix-org/matrix-doc/pull/2448), whichever doesn't land first :yum:

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +pack in a room. This could be problematic in e.g. bridged rooms: You set some emotes or stickers from the matrix
```suggestion
in a room. This could be problematic in e.g. bridged rooms: You set some emotes or stickers from the matrix
```

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> + - For stickers: Recommend rendering sizes / resolutions
I'd love to also embed custom emotes into reactions - and having clients suggest that from the available image packs. However, I understand that aggregations are still outstanding from the spec...

2021-08-24 18:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +are for.
It looks to also appear in `data-mx-emoticon`.

2021-08-24 18:50 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +Thus, specifying both the `alt` and `title` attributes is required.
I think the intention isn't to have different values for those, but that browsers need both set, since they are show in different cases.

2021-08-24 19:05 UTC, deepbluev7 commented on proposals/2545-emotes.md
> + - For stickers: Recommend rendering sizes / resolutions
I think Revolution can do custom reactions based on this, but image reactions should probably be its own MSC. Using the emotes from a pack like this should be easily doable, but figuring out how the reaction should look might cause a lot of bikeshedding. Currently those clients just react with an mxc uri as the key.

2021-08-24 19:51 UTC, uhoreg commented on proposals/2545-emotes.md
> + - `usage`: (String[], optional) An array of the usages for this image. If present and non-emtpy,
```suggestion
 - `usage`: (String[], optional) An array of the usages for this image. If present and non-empty,
```

2021-08-24 19:56 UTC, Sorunome commented on proposals/2545-emotes.md
> +   this overrides the usage defined at pack level for this particular image.
account data - you only have a single image pack tied to your own account

2021-08-24 19:57 UTC, Sorunome commented on proposals/2545-emotes.md
> +
correct. the parent way checking is done to ensure canonical spaces are being used

2021-08-25 16:22 UTC, Sorunome commented on proposals/2545-emotes.md
> +
The emote packs should depend on `m.space.parent`, not `m.space.child`. That way only emotes of canonical spaces are included.

2021-08-25 16:23 UTC, Sorunome commented on proposals/2545-emotes.md
> +Thus, specifying both the `alt` and `title` attributes is required.
Soru would argue this isn't needed: The MSC makes `data-mx-emoticon` the flag for it being an emote, and the other MSC adds the blurhash to the `<img>` tag. So.....both are additions to `<img>` so no need to mention it explicitly here?

2021-08-25 16:24 UTC, Sorunome commented on proposals/2545-emotes.md
> + - For stickers: Recommend rendering sizes / resolutions
Yeah, emote reactions should be its own MSC. Soru can think that, in general, something like having a format for reactions: Current reactions can combine emojis and text, it's only a matter of time until people want to combine custom emotes, emojis and text into a single reaction.

2021-08-28 11:20 UTC, kate-shine commented on proposals/2545-emotes.md
> +Thus, specifying both the `alt` and `title` attributes is required.
> @kate-shine, isn't that what the body is for?

We are getting offtopic here, but `m.sticker` has **only** body, which is quite often used for a flavor text accompanying the sticker instead of its description (and that usage is even suggested in spec), and doesn't allow for what uhoreg suggested.

2021-09-11 20:46 UTC, BBaoVanC commented
Shouldn't fluffychat say "stickers and emoticons" under the "Sending, using the mentioned events here" section (under Current implementations)

2021-09-16 13:28 UTC, Sorunome commented on proposals/2545-emotes.md
> +There are several places where a client is expected to look for these `m.image_pack` events, mainly
But they are events: either an account data event or a room state event

2021-09-16 13:29 UTC, Sorunome commented on proposals/2545-emotes.md
> +and stickers from all the image packs found in those rooms/spaces.
It does? 

> Clients should suggest image packs of a space that a room is in, **if the user is also in the space**.

Will update to canonical space, though

2021-09-16 13:33 UTC, Sorunome commented on proposals/2545-emotes.md
> +
> Although there may be a usecase for linking to packs of other, disjoint rooms in order to get new emotes/stickers as they're updated, that probably isn't something that should be done through Spaces.

That also sounds like it could easily be a separate MSC

2021-09-20 15:21 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +There are several places where a client is expected to look for these `m.image_pack` events, mainly
Oh, I think I thought here that `m.image_pack` was a JSON key rather than an event type for some reason.

```suggestion
There are several places where a client is expected to look for events with type `m.image_pack`, mainly
```

:shrug:

2021-11-21 17:29 UTC, anoadragon453 reviewed
This proposal seems mostly solid. Just a few more nits to add alongside existing threads.

2021-11-21 17:29 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +
What if different clients decide to use different deliminators? Would it be confusing for my client, which typically uses `:` as a deliminator, to see `$shortcode$` when hovering over an emote?

Suggesting clients not place deliminators in the `alt` / `title` text would solve this.

2021-11-21 17:29 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
Hello! I took another read-through this MSC today, and along with the points below I made some readability and clarification-related edits along the way. These are contained in https://github.com/matrix-org/matrix-doc/commit/364256e579b4886c6f668f6c8c5d48852831fe88.

Feel free to incorporate them if you wish!

2021-11-21 17:29 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +across all rooms you are in.
This strikes me as something that may actually be potentially useful to include in this MSC. And this MSC does have somewhat of an equivalent; namely space image packs.

The concept of space image packs makes perfect sense to me, especially when bridging from Discord. When you bridge a Discord server - where custom emoji are defined at the server level - duplicating/maintaining the emote info per-room would be a nightmare. Instead, you can just shove all Matrix rooms mapped to Discord channels in a space, and then define all the emotes in that space.

Suppose another usecase though, where I had two rooms which contained image packs I enjoyed. Say one for [ponymotes](https://ponymotes.net/bpm/), and one for a collection of [super cool stickers](https://telegramchannels.me/stickers/s-prtyparrot). I don't maintain either of the image pack rooms, and am thankful to those that do.

I want images from both packs to appear for users in my room, and perhaps I don't want to ask my users to enable each of these packs globally to make that happen.

I don't think this usecase is possible with what's currently defined in this MSC. It could be made possible by having the ability for rooms to reference other room IDs, which clients should suggest image packs from (if the user is joined to that room). Say by having an `m.image_pack.rooms` state event in the room.

I don't consider this a blocker for this MSC though - rather just something that may be considered for adding down the line if the usecase becomes necessary.

2021-11-21 18:52 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +across all rooms you are in.
One related thing, that would be very useful, is if a sticker could have a reference to what pack it came from, so that a user can just click on it to add it instead of having to ask around. Would probably need to be optional though.

2021-11-21 23:57 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +across all rooms you are in.
That's a good idea! Though could you create a new thread for it?

I'm also conscious of scope-creeping this MSC further, so maybe the above and referencing packs could land in a separate MSC.

2021-11-22 00:41 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +
Split off from https://github.com/matrix-org/matrix-doc/pull/2545/files#r753839678

It would be great to also have some metadata you could opt into for stickers and emotes, that would allow a user to then also add that pack, if sent in a different room without having to ask for it.

Maybe sharing as a whole could be a follow up MSC, which defines sharable links, recommendation events as well as metadata to add a pack, when you got sent one of its stickers.

2021-12-17 08:48 UTC, based-a-tron commented
Hey Matrix team,

I am a trans brony, and i really love your platform. but my gender reassignment surgery will cost 30 million dollars. and i need the sticker packs to generate income on my matrix platform to make me feel like who i am inside!!! now if matrix can get 30 million and get nothing done. with the idiotic communities that not even the trans broney community will use you guys are incompetent. either fix the stickers or consider donating to my surgery with that money.

thanks UWU

2022-03-22 16:40 UTC, richvdh commented
I'm removing this from "proposed for FCP readiness" for now, as I see a lot of unresolved comment threads, and no progress for several months.  I hope it manages to get some love soon though!

2022-05-05 19:50 UTC, AndrewRyanChama commented
@turt2live @richvdh I see that there are a lot of comments on this proposal, which is understandable due to the large scope and complexity, but my understanding is that it's effectively complete except for small clarifications and readability improvements.  @anoadragon453 would you agree with this?  If not, it would be helpful to call out specifically the issues that must be addressed for this.

Also, it seems that the original author may have abandoned this PR, as both the author's website and demo element instance have been taken down.  If there is substantiate change needed here is it OK if I created a new PR for this?  Would this need a new MSC number?

2022-05-05 20:17 UTC, kate-shine commented
> Also, it seems that the original author may have abandoned this PR, as both the author's website and demo element instance have been taken down. If there is substantiate change needed here is it OK if I created a new PR for this? Would this need a new MSC number?

Small clarification, original author is still interested in this MSC being finished, she's just unable to find energy to contribute to it right now for personal reasons. Demo element (revolution) instance stopped working for different reason, but implementations in Fluffychat and Nheko are still functional.

2022-05-05 20:20 UTC, turt2live commented
This is still on my personal todo list to figure out, though is blocked behind some larger moving pieces. Once things like Extensible Events clear out, I'll be able to take a look at this. 

For adding implementations, please just leave a comment and we'll associate them. This does not require a new MSC.

For comments about the MSC, please use line comments on the diff. Otherwise, replies/comments are not considered during review.

And finally, for further questions please visit [#matrix-spec:matrix.org](https://matrix.to/#/#matrix-spec:matrix.org) so we can answer with a bit more clarity :)

2022-05-05 23:37 UTC, AndrewRyanChama commented
@kate-shine I guess that is a misunderstanding on my part then.  I'm happy to wait on the original author if that is so desired, but I can also offer assistance in editing this if it would help expedite progress here.

2022-06-29 07:37 UTC, AndrewRyanChama commented
After implementing this in https://github.com/SchildiChat/schildichat-desktop I found some issues that might be a big deal.  Even though this is implemented now in several Matrix clients, this might need some change.

# Image ordering
This change implements the list of images in an image pack as a JSON object, which is a key-value store (aka dict/object) of slug: {image} format.  In this case, the key-value does not encode any natural ordering to it.  In practice, on Element, this seems to keep its order, but the JSON spec does not provide this, and it's highly likely that for many languages, deserializing this JSON in any practical way will obliterate the ordering.

This issue of ordering is just as much of a problem for ```m.image_pack.rooms``` which uses the room ids as keys in a k-v store again.  This MSC proposal specifically calls out the importance of presenting a predictable ordering, but this representation is not conducive to that.

## Requirement for a slug for each image
This representation also ends up requiring a unique string slug for each image in the pack.  This will affect bridging from other services that don't provide slugs, such as Telegram, and also prevents multiple images in a pack from having the same slug, which may be desirable.  A possible mitigation is to put random garbage in the keys, but this will result in a terrible customer experience if these slugs are to be used for suggestions.

At a higher level, this usage of k-v data representation for storing what's essentially an ordered sequence of things, (packs, stickers, etc.).  Logically, it seems cleaner to present this information in a json array, such as an array of images in a pack.

# Deduplication
It's important to present separate image packs as logically separate to the user.  If two packs share some images but not others, how can this be presented to the user?  Will these images be arbitrarily dropped from one of the packs but not the other?

The motivation for this seems to be that multiple rooms with the same maintainer may want to have an identical image pack.  A more direct approach to this would be to provide a way for multiple rooms to share the same underlying image pack (which might be out of scope for this MSC).  In the case that two packs legitimately have some intersection, I believe the correct behavior is to show those images in both packs, such that the pack is shown to the user exactly as the pack author intended.

My suggestion is to drop deduplication completely as a scope creep that isn't necessary for this MSC.

# Smaller stuff
1. The specification of an image-pack-only room isn't written as far as I can tell.  I think simply choosing a room type would suffice here.
2. It would be quite useful to provide a canonical reference to each pack and image in the pack.  Such as packid = roomid:statekey, and imageid = roomid:statekey:imagekey.  This can have many potential uses, such as making sent stickers and emojis sharable.  Defining how these keys can be used may be out of scope, but I believe that it should be a hard requirement that an image or pack be uniquely identifiable by a string id somehow.

2022-06-29 16:44 UTC, AndrewRyanChama requested changes

2022-06-29 16:44 UTC, AndrewRyanChama commented on proposals/2545-emotes.md
> +### Image pack event
It would be quite useful to provide a canonical reference to each pack and image in the pack. Such as packid = roomid:statekey, and imageid = roomid:statekey:imagekey. This can have many potential uses, such as making sent stickers and emojis sharable. Defining how these keys can be used may be out of scope, but I believe that it should be a hard requirement that an image or pack be uniquely identifiable by a string id somehow.

2022-06-29 16:45 UTC, ckiee commented on proposals/2545-emotes.md
> +#### Example image pack event
> This representation also ends up requiring a unique string slug for each image in the pack. This will affect bridging from other services that don't provide slugs, such as Telegram, and also prevents multiple images in a pack from having the same slug, which may be desirable. A possible mitigation is to put random garbage in the keys, but this will result in a terrible customer experience if these slugs are to be used for suggestions.

Bridges could use something like npm's [`slug`](https://www.npmjs.com/package/slug). I don't think we should give up a valuable feature because it *might* not work for *some* bridges.

2022-06-29 16:48 UTC, ckiee commented on proposals/2545-emotes.md
> +### Image pack source priority and deduplicating
+1 for dropping, UI details should be dependent on the client UI implementation.

2022-06-29 17:56 UTC, kate-shine commented on proposals/2545-emotes.md
> +#### Example image pack event
Thanks for suggestions! I sadly didn't have time to work on MSC update yet, but I have it scheduled for following week or two, so this came in a really great time. The ordering issue sounds like a right call, while the ordering mentioned in spec is mostly tied to ordering of priorities for various sources, it is a good idea to have ordering predictable in the source itself as well.

I'm really not sure about making slugs optional though. If I understand Telegram sticker packs correctly, they do contain at least the emoji identifier, which can be slugified (even if it might not be an ideal representation). Having at least some placeholder for emoticon instead of no placeholder at all still sounds like a good thing to have.

2022-06-29 18:04 UTC, kate-shine commented on proposals/2545-emotes.md
> +While room image packs are specific to a room and are only accessible within that room, image pack
Room types weren't a thing at the point of time where this spec was written. Thank you for reminder!

2022-06-30 17:09 UTC, turt2live commented on proposals/2545-emotes.md
> +While room image packs are specific to a room and are only accessible within that room, image pack
https://spec.matrix.org/v1.3/client-server-api/#types ?

2022-06-30 17:13 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +While room image packs are specific to a room and are only accessible within that room, image pack
Hm, seems like it actually made it into the spec, although I remember the discussion on the spaces MSC to originally go differently.

2022-08-05 14:03 UTC, ajbura commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
FYI Cinny [implements this MSC fully](https://github.com/cinnyapp/cinny/pull/686) so could be added in implementations.

2022-08-12 08:54 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
Thank you! I've added the link to the relevant places in the PR description.

2022-08-15 21:07 UTC, kevincox commented on proposals/2545-emotes.md
> +#### Example image pack event
I find this argument compelling. The editor may choose to sort alphabetically but having the ability to order in the protocol seems valuable. 

I would say that the protocol should have ordering and clients *should* display the stickers in that order. Of course they don't have to which opens the door for per-user ordering use-vased ordering or other UIs.

2022-08-27 18:54 UTC, JacksonChen666 commented on proposals/2545-emotes.md
> + - `avatar_url`: (String, optional) The mxc uri of an avatar/icon to dipslay for the pack. Defautls
```suggestion
 - `avatar_url`: (String, optional) The mxc uri of an avatar/icon to dipslay for the pack. Defaults
```

2022-08-27 19:00 UTC, Alcaro commented on proposals/2545-emotes.md
> + - `avatar_url`: (String, optional) The mxc uri of an avatar/icon to dipslay for the pack. Defautls
```suggestion
 - `avatar_url`: (String, optional) The mxc uri of an avatar/icon to display for the pack. Defautls
```

2022-09-02 18:17 UTC, ashkitten commented on proposals/2545-emotes.md
> + - `avatar_url`: (String, optional) The mxc uri of an avatar/icon to dipslay for the pack. Defautls
Defaults, even

2022-09-03 11:26 UTC, Sorunome commented on proposals/2545-emotes.md
> +#### Example image pack event
Soru didn't do image ordering with an array because of the inflated size the event will have; image packs are still bound by the 65k limit for events over federation.

@kate-shine had the idea to put the ordering in a different, separate, event, so that a user can also easily override the order for themself and/or frequent usage can be easily tracked

2022-10-27 10:40 UTC, Sorunome commented on proposals/2545-emotes.md
> +### Image pack event
That is not necessarily needed, as a futur MSC could just add the roomid and statekey to the sticker event / the img data and then the identifier would be a tuple and doesn't have to be a string that is parsed extra

2022-10-27 10:42 UTC, Sorunome commented on proposals/2545-emotes.md
> +### Image pack source priority and deduplicating
> A more direct approach to this would be to provide a way for multiple rooms to share the same underlying image pack (which might be out of scope for this MSC).

well, since the writing of the msc spaces have been a thing so you could just attach the sticker pack to the space

2022-10-27 10:43 UTC, Sorunome commented on proposals/2545-emotes.md
> +
Yeah, that would be a follow-up MSC

2022-10-27 10:44 UTC, Sorunome commented on proposals/2545-emotes.md
> +across all rooms you are in.
Space image packs are already a thing as per this MSC

2022-10-27 10:48 UTC, Sorunome commented on proposals/2545-emotes.md
> +
Good point :+1:

2022-10-27 10:48 UTC, Sorunome commented on proposals/2545-emotes.md
> +An empty state key is the default pack for a room.
Hmm, not really, good point

2022-10-27 10:49 UTC, Sorunome commented on proposals/2545-emotes.md
> +   image pack event is not in a room, this pack does not have an avatar.
but avatar_url would be more consistent with the remaining spec?

2022-10-27 10:50 UTC, Sorunome commented on proposals/2545-emotes.md
> +that it is easier for clients or future MSCs to define custom metadata to emotes directly.
This could be a future MSC

2022-10-27 10:52 UTC, Sorunome commented on proposals/2545-emotes.md
> +## Security Considerations
This will be for a future MSC

2022-10-27 10:57 UTC, Sorunome commented
Soru went through and closed threads which are future MSCs that build ontop of this and linked them for reference in the top post. Please say if soru missed any!

2022-10-27 11:20 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
I strongly disagree. Implementing this MSC as-written would be irresponsible and harmful. People would start creating and using sticker packs not knowing that they are leaking data. Few users would expect or understand this feature to leak and few if any clients would warn or prevent them. How (and why) should I be expected to know that uploading an image in an encrypted conversation is protected by E2EE but uploading an image to an image pack and then sharing it in that conversation isn't? 

Matrix claims to be "An open network for **secure**, decentralized communication" but if mistakes like this keep being made we should strip all mentions of E2EE from the homepage. Unless they come with disclaimers like "a few features are protected by E2EE". As it is clear that security and privacy are not a priority. 

You don't create a secure protocol but loading in insecure features and hope that someone will come by later and slather on some encryption. You get a secure protocol by ensuring that every feature is secure and privacy respecting before it is allowed into the spec. If a messenger like Signal that is serious about privacy released a feature like this people would complain like no tomorrow. The fact that this is even being considered in it's current state shows how little the people running Matrix care about privacy.

2022-10-27 11:39 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +## Security Considerations
Encrypted state events are a different MSC. Please direct your concern at all other MSCs, that also use state events, like group calls. It is not reasonable to have this specific MSC solve a very complicated problem, that is at least as much a concern to elements already in the spec and other MSCs. Topics are unencrypted, room names and avatars are unencrypted, member names and reactions are unencrypted and group call states are unencrypted. Why single this MSC out, that is already complex enough and has a lot of other open discussions, instead of just accepting that encrypted state events are an orthogonal problem and should be solved for all of them?

In 90% of cases emoticons and stickers are used in public rooms and not having them there is a significant issue. Please don't vent your anger at some random contributor, that is already struggling to manage time and energy on this MSC. Direct it to the core spec team, or better yet, be constructive. We now have the first MSC exploring signed membership: #3917 . That is a prerequisite to having encrypted state. Once we can encrypt state, this MSC automatically can be encrypted as well. Let's keep the focus on the sharing packs of images here, please.

2022-10-27 11:55 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
IIUC even signed state events aren't enough to provide E2EE for this feature. 

What I see is that maybe Matrix isn't quite ready for this MSC yet. I know it sucks to delay features because foundational work hasn't been done yet but that is the responsible thing to do. 

> Topics are unencrypted...

Yes, let's not make this worse. We need to avoid letting the broken-window effect making this problem forever worse. 

> Direct it to the core spec team, or better yet, be constructive.

I'm sorry, I thought this is what I was doing. I was raising issues that I see to be blocking this MSC so that the core team can consider them before accepting. If there is a better avenue to do that (as I agree that this issue is not specific to only this MSC) please let me know what that is.

2022-10-27 12:12 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +## Security Considerations
> IIUC even signed state events aren't enough to provide E2EE for this feature.

No, but signed state events are a requirement to be able to share encryption keys for encrypted state events in a reasonable manner.

> I'm sorry, I thought this is what I was doing. I was raising issues that I see to be blocking this MSC so that the core team can consider them before accepting. If there is a better avenue to do that (as I agree that this issue is not specific to only this MSC) please let me know what that is.

In my opinion it is much worse to have a room topic be unencrypted than having a list of stickers be unencrypted. This MSC just replaces an existing unencrypted way of hosting stickers with a federated and user controlled one. There is already an issue open to be able to encrypt state events as well as a few MSCs working in that direction. Blocking this MSC indefinitely on that might be fine, but then please link to the relevant issues and MSCs. There are MSCs in progress by the core team or people being paid to work on Matrix, that also send unencrypted state events (location sharing, group calls, etc). The author of this MSC doesn't have the funding to develop such a foundational feature, so pointing at who else is solving this or accepting that the solution will be a different MSC would go a long step to actually resolving concerns on this MSC, that affect the functionality of this MSC instead of a lower layer (like state events). Throwing "Matrix should remove secure and encrypted from their branding" at the head of someone who just wants to be able to send emoticons, while that author already wrote suggestions about how to be able to encrypt reactions and other relations, is simply targeting the wrong people.

2022-10-27 13:41 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
>  is much worse to have a room topic be unencrypted than having a list of stickers be unencrypted.

Sure, but this is mostly unrelated to this MSC. We shouldn't make things worse just because they are already bad.

> Blocking this MSC indefinitely on that might be fine, but then please link to the relevant issues and MSCs.

That is what I am proposing on doing. We can definitely gather related MSCs (I see you have linked a few, thanks) and track there progress. But please note that the core reason I think his MSC isn't ready yet isn't any specific MSC or issue but that fact that it adds more unencrypted state which I don't think needs to be added. I understand that solving this likely requires some other MSCs to land first, but the exact MSCs are nto completely clear yet.

> Throwing "Matrix should remove secure and encrypted from their branding" at the head of someone who just wants to be able to send emoticons, while that author already wrote suggestions about how to be able to encrypt reactions and other relations, is simply targeting the wrong people.

Fair point, I apologize for that. It was an attempt to emphasize why I disagree with the author's statement that this concern should be handled in a future MSC. I didn't mean to suggest that they are the one in power to change that. Just why I don't think this MSC as written aligns with the Matrix Foundation's stated goals.

---

So to summarize my opinion:

1. I don't think this proposal should be accepted until it is possible to create and use sticker packs without leaking the contents of the stickers to homeservers when used in E2EE rooms.
2. I understand that other MSCs will be required in order to satisfy the privacy requirements for 1.
3. I think that the MSCs in 2 need to land **before** this MSC so that:
  a. We don't end up with people using this feature assuming it is E2EE and compromising their privacy.
  b. We have a single version of the sticker protocol, not one encrypted version and one non-encrypted version.

2022-10-27 13:47 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
One other approach that may work and allow this to move forward quicker is I would consider approving of this MSC if it was written such that it would be private and secure **assuming** that state events are encrypted. Even if that isn't currently the case.

This is not the best solution as it makes a big assumption and still will leak data until the encryption of state events lands but seeing as we have proposals such as https://github.com/matrix-org/matrix-spec-proposals/pull/3917 and it is likely that some form of private and secure state events will land to fix issues such as room topics.

2022-10-27 13:57 UTC, HarHarLinks commented
- element web in the meantime gained support for rendering inline-images: https://github.com/vector-im/element-android/pull/5877
- @SpiritCroc might be able to tell us when SchildiChat-android added support for sending custom emoji from (existing) image packs, as I can't find a PR or commit to reference right now

2022-10-27 14:01 UTC, Cadair commented on proposals/2545-emotes.md
> +## Security Considerations
I think that blocking this feature that is heavily requested completely because it can't be secure in E2EE rooms is silly.

As Nico says, the main use of this feature (imo) would be in public rooms anyway, and clients could choose to disable it or throw a big red warning in E2EE rooms (just as they could do for other things at the moment).

If you have specific concerns about how this MSC works that you think are incompatible with the current state of the encrypted state proposals then I think they would be very constructive points to add to the discussion.

2022-10-27 15:47 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
> I think that blocking this feature that is heavily requested completely because it can't be secure in E2EE rooms is silly.

I think we have different values and won't agree here.

> the main use of this feature (imo) would be in public rooms anyway

I don't see why this would be "mainly" in public rooms. I've created private sticker packs with funny photos of friends in the past.

> If you have specific concerns about how this MSC works that you think are incompatible with the current state of the encrypted state proposals

I don't see any specific incompatibilities however it seems that even with those proposals this will reveal unnecessary information to the homeservers.

2022-10-28 14:31 UTC, Sorunome commented on proposals/2545-emotes.md
> +### Image pack source priority and deduplicating
soru said now deduplication should be done and suggests mxc URIs, how clients actually do that is up to them

2022-10-28 14:32 UTC, Sorunome commented on proposals/2545-emotes.md
> +While room image packs are specific to a room and are only accessible within that room, image pack
That is something orthogonal to this MSC and should be in a new MSC then, to not feature creep this one.

2022-10-28 14:38 UTC, Sorunome commented on proposals/2545-emotes.md
> +in their own account data and in room states.
That is already a problem that clients should be conscious of throughout all the spec and thus it isn't job of this MSC to re-iterate that.

2022-10-28 17:40 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
My specific comment is that the image data is sent in plaintext to the homeserver. My ideal solution would not even have the ability to do this but I would at least like to see the option to not send any plaintext image data to the homeserver.

My current rough concept is:
- Add a required encryption key to each `Image` object.
- Include the encryption key in the `<img>` tag when using the image.

There is likely also a bit of metadata around algorithm required in each of these places.

This would leak the data of all images if the sticker pack is shared in an unencrypted room or unencrypted account data and leak the data of images used in unencrypted messages. This seems reasonable to me. Sticker packs never used in unencrypted places would not be leaked to anyone but the recipients (either revealed image-by-image or by pack if the pack is shared).

The downside is that currently this isn't enough to provide secure stickers as state events and account data can't currently be encrypted. However I think it is a reasonable compromise to assume that these types of data will gain encryption support in the future and ship the MSC today as it will be "automatically upgraded" to support encryption rather than creating a second version of the protocol in the future.

2023-01-02 23:33 UTC, z411 commented
I've been trying emoji and sticker packs with both Nheko and Cinny and I've seen a discrepancy with the usage of the "info" object (currently optional according to spec) in the image pack event which leads to some discrepancies when shown by clients or bridges, and I think it'd be prudent to clarify it somehow in the spec to achieve parity between clients.

When adding a sticker with Cinny, the `info` object of the sticker (mimetype, image size) is not saved in the image pack event. It's only sent when sending the actual sticker, in the `m.sticker` event. On the other hand, on Nheko, when adding a sticker the `info` of the sticker does get saved into the image pack event. See:

```
    "sticker_created_in_cinny": {
                "url": "mxc://redacted",
                "usage": [
                    "sticker",
                    "emoticon"
                ]
            },
    "sticker_created_in_nheko": {
                "info": {
                    "h": 169,
                    "mimetype": "image/jpeg",
                    "size": 55289,
                    "w": 223
                },
                "url": "mxc://redacted"
            },
```

Cinny doesn't need the info in the image pack event; it seems to generate the `info` object when sending `m.sticker`. Meanwhile Nheko uses the `info` objects of the image pack event of the room to send the sticker, and since Cinny doesn't save this information in the image pack event, Nheko sends the sticker with a info object with empty values:

```
(Sticker created in Cinny sent by Nheko)
"info": {
            "h": 0,
            "mimetype": "",
            "size": 0,
            "thumbnail_info": {
                "h": 0,
                "mimetype": "",
                "size": 0,
                "w": 0
            },
```

This results in stickers being too big or bridges not knowing how to handle them due to the lack of mimetype.

My question is: what's the correct way to handle this? Should clients be mandated to include info in the image pack event and use that information when sending the sticker, or should they handle stickers with no info and generate it on the fly when sending it?

Related Nheko issue https://github.com/Nheko-Reborn/nheko/issues/1255

2023-04-13 03:23 UTC, greentore commented on proposals/2545-emotes.md
> +list.
I really don't like this part. People shouldn't be forced to convert perfectly fine jpeg images.

2023-04-13 12:06 UTC, Sorunome commented on proposals/2545-emotes.md
> +list.
Soru would prefer to not have image type suggestions, but, if sorus memory serves her correctly, this was added on @turt2live 's suggestion

2023-08-18 12:55 UTC, ata-star commented
merge when?

2023-11-14 16:35 UTC, turt2live reviewed
WIP review

2023-11-15 02:40 UTC, uhoreg commented on proposals/2545-emotes.md
> +Thus, specifying both the `alt` and `title` attributes is required.
I'd prefer to make the `alt` and `title` required for emoticons.  The image packs already associate a shortcode with the images, which can be used for those, so it won't be hard for the clients to supply them.  And having them is good for accessibility (even for those who do not have visual impairment).

2023-11-15 03:01 UTC, uhoreg commented on proposals/2545-emotes.md
> + - `usage`: (String[], optional) An array of the usages for this pack. Possible usages are `"emoticon"`
I wonder if it's worth allowing implementations to create their own usages, in which case, we probably want the usages to be `m.emoticon` and `m.sticker`, and have the custom usages follow the Java package naming convention as usual.

2023-11-15 16:34 UTC, richvdh commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
Since this MSC will intersect with MSC3911, I think we should consider this blocked until MSC3911 (or some other solution to the issues solved by that MSC) is merged.

2024-03-09 01:37 UTC, tusooa commented
Stickers support in kazv: https://lily-is.land/kazv/kazv/-/merge_requests/71

2024-04-15 00:09 UTC, ara4n commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
I'm not sure this has to be blocked on MSC3911 - MSC2545 is already in use in the wild all over the place. MSC3911 will need to figure out how to address it, but not block the whole of this on media linking/auth.

2024-08-15 13:25 UTC, anoadragon453 reviewed
Hello all. I plan to breathe new life into this MSC by addressing any outstanding concerns and making changes as necessary.

I'm aware that this MSC has already been successfully implemented in numerous clients (thank you!), and I intend to remain compatible with those implementations as much as possible.

I very much look forward to seeing custom emotes and stickers become a part of the Matrix spec. Let's make it happen!

2024-08-15 13:25 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +Furthermore, clients are expected to de-duplicate images so that same images are not displayed multiple
It also makes it more difficult to manage packs, in case you want to manually remove duplicates.

Perhaps it would make more sense to only de-duplicate packs themselves?

2024-08-21 08:23 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +list.
> doesn't appear to supply a list of supported mimetypes?

yeah. my suggestion is to not define it here, but back of the definition for m.image, which is missing as of yet and is tracked by above spec issue.

2024-08-21 08:27 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +The `height` is just a height that looks good on most devices with the normal, default font size.
shouldn't it be the receiver that decides what "emoji" size is appropriate to fit the text line height? after all the receiver also "decides" what size to show the local real emoji in (by selecting font and font size), and supposedly custom emoji should fit in with that.

2024-08-21 12:25 UTC, Gremious commented on proposals/2545-emotes.md
> +Furthermore, clients are expected to de-duplicate images so that same images are not displayed multiple
Also, less relevant and only marginally importnat, but assuming you can click on a sticker to view it's name in the chat like you can with discord stickers/emojis, that should probably be taken into account.

So if you have a smug/grimacing face in one pack titled "I'm gonna get u" and the same sticker in another pack titled "satisfied", you _could_ potentially want to send the different stickers in different rooms, on the assumption that people are gonna click and read the name. And you'll probably search the sticker by the name you intend to convey.

Whether people actually use emojis/stickers like that is up to debate, but hey, I like naming my emoji nicely in discord, so I can kind of see it.

---

If de-duplicating is "automatic", then don't know if it's really even necessary. I don't see why a user shouldn't be able to just put 400 of the same sticker in a pack if they wanted to. They probably won't anyway, buf if they do it as a joke, who cares. Feels like slightly wasted development time to me to put an arbitrary restriction.

A button to remove duplicates in the pack on demand sounds cool though, makes life easier if you just have a big sticker folder that might have a few repeating images, e.g. from downloading/collecting stickers you see manually.

2024-08-21 12:28 UTC, Gremious commented on proposals/2545-emotes.md
> +The `height` is just a height that looks good on most devices with the normal, default font size.
Yeah, I imagine it's good for accessibility for the reciever to decide what size to render font/emoji/sticker/image embeds/etc. Usually though, you just have font and/or global scaling that makes everything bigger/smaller.

I think the suggestion here is that the spec should just clearly _recommend_ a sensisible default "that looks good on most devices with the normal, default font size." which clients are free to deviate from based on their design.

2024-08-21 17:42 UTC, deepbluev7 commented on proposals/2545-emotes.md
> +The `height` is just a height that looks good on most devices with the normal, default font size.
In practice currently all clients set the default size to 32px and then when rendering it locally, they set it to some size based on their font size, if the data-mx-emoticon attribute is set on an image.

2024-08-28 10:51 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +Furthermore, clients are expected to de-duplicate images so that same images are not displayed multiple
> A button to remove duplicates in the pack on demand sounds cool though, makes life easier if you just have a big sticker folder that might have a few repeating images, e.g. from downloading/collecting stickers you see manually.

Good idea, though this can be implemented in the client. The current spec won't get in the way of such a client feature.

2024-08-28 12:31 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +The `height` is just a height that looks good on most devices with the normal, default font size.
Thanks all. I've documented this in c429552d.

2024-08-28 12:33 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +The `src` attribute *must* be a mxc url. Other URIs, such as `https`, `mailto` etc. are not allowed.
I've applied the suggestion in the first comment in a separate commit.

> We need consequences listed: does the event not get rendered, or just the emoticon?

I don't see why the rest of the event should not be rendered. It'd be ideal to still be able to see the text in a message, even if the emotes aren't formatted properly (and are thus not rendered). Do you agree?

2024-08-28 12:43 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +Furthermore, clients are expected to de-duplicate images so that same images are not displayed multiple
@deepbluev7 What are your thoughts on this, given your experience with implementing this MSC?

2024-08-28 13:18 UTC, uhoreg commented on proposals/2545-emotes.md
> + - `usage`: (String[], optional) An array of the usages for this pack. Possible usages are `"emoticon"`
Agreed.  It just seems to me like naming it `m.emoticon` instead of just `emoticon` makes it easier and clearer.  Anyways, it's a non-blocking comment.

2024-08-28 14:44 UTC, anoadragon453 commented on proposals/2545-emotes.md
> + - `usage`: (String[], optional) An array of the usages for this pack. Possible usages are `"emoticon"`
Has anyone seen any use cases for additional "usages" in the wild while this MSC has been implemented? @deepbluev7 perhaps?

If not, perhaps it's just best to leave this as is.

2024-08-28 22:56 UTC, tusooa commented on proposals/2545-emotes.md
> +list.
I think we should NOT limit the types. New media formats can appear and get used over time.

Also, jpg is not "unsuitable" for emoticons in any way. There are even people who prefer them to be of low quality and/or low resolution. It is not uncommon in the Mandarin-speaking communities to think that having low quality is a *desired* trait of emoticons.

> For now, shall we simply recommend clients SHOULD use a core list?

This is a good suggestion to recommend that clients *at least* support certain formats.

2024-08-29 12:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +list.
I've captured this in d4e9cd22.

2024-11-26 07:35 UTC, je-sendra commented
Any updates on this?

2024-12-26 20:52 UTC, anoadragon453 reviewed
Apologies to those that I had in-person discussions with; I realise it's now months on since then. Still, I hope we can drive these outstanding points to a conclusion now!

2024-12-27 19:27 UTC, TobiasFella commented on proposals/2545-emotes.md
> + - `usage`: (String[], optional) An array of the usages for this pack. Possible usages are `"emoticon"`
> One client developer (can anyone remember who?)

that was me

> On the other hand, @deepbluev7 argued that they liked being able to import a pack containing both emotes and stickers at the same time. Perhaps there could be no usage field at all; any pack you import can immediately be used for both stickers and emotes.

What does "import" mean exactly here? from some kind of export format?
I guess nothing stops one from having both stickers and emoticons in the same "export file" and importing both simultaneously

2025-03-27 16:22 UTC, SkyePrism commented on proposals/2545-emotes.md
> +Furthermore, clients are expected to de-duplicate images so that same images are not displayed multiple
So it seems that de-duplication of emotes should be removed from the MSC?

2025-03-27 16:24 UTC, SkyePrism commented on proposals/2545-emotes.md
> +Furthermore, clients are expected to de-duplicate images so that same images are not displayed multiple
@Sorunome

2025-03-27 16:36 UTC, SkyePrism commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
so, is this conversation resolved as MSC2545 isn't blocking on MSC3911?

2025-03-27 17:34 UTC, TobiasFella commented on proposals/2545-emotes.md
> + - `usage`: (String[], optional) An array of the usages for this pack. Possible usages are `"emoticon"`
My general concern still remains, but I don't think this should hold up the process here - I'm happy enough with the current UX of my implementation of this MSC

2025-03-27 18:34 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +Furthermore, clients are expected to de-duplicate images so that same images are not displayed multiple
Given that nobody has returned with a rebuttal to push for de-duplication, I'm opting to resolve this discussion. The suggestion of de-duplication has been removed from the MSC text in [2366ffd](https://github.com/matrix-org/matrix-spec-proposals/pull/2545/commits/2366ffd71009ae471f91404c3278c0a38908c823).

2025-03-27 18:36 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +that if an image has a shortcode of `emote`, the user can enter `:emote:` to send it. If there are
A shortcode grammar has been added to the MSC text in [7d399e6](https://github.com/matrix-org/matrix-spec-proposals/pull/2545/commits/7d399e6cf014afbe3156d77e6c3324dd207ef1b4).

We've opted to state that `:` MUST NOT be included in the shortcode. This still assumes that clients will still show `:` in the UI around shortcodes, but saves bandwidth by not forcing it to be included in the event every time.

2025-03-27 18:36 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
Just to be clear that this concern is not resolved. It is still an open concern and at the very least should be mentioned in the "Security Considerations" section. Although I think not blocking this RFC until it respects users privacy is a bad idea (but understand that other people have different priorities).

2025-03-27 18:38 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +   image pack event is not in a room, this pack does not have an avatar.
After 3 years, I no longer think this *needs* to be `icon_url`. `avatar_url` is fine.

2025-03-27 18:40 UTC, kevincox commented
Is there a way to mark https://github.com/matrix-org/matrix-spec-proposals/pull/2545/files#r677009720 as not resolved?

1. It represents a serious privacy concern.
2. It represents major maintenance and evolution pain (assuming that there is eventually an E2EE version of stick packs).

One of the following needs to happen before that concern is resolved:

1. This RFC needs to be made E2EE.
2. One or more of the "Security Considerations", "Potential Issues" or "Alternatives" sections of the RFC need to explicitly mention this tradeoff.

2025-03-27 18:51 UTC, SkyePrism commented
Signed-off-by: SkyePrism skye.prism@outlook.com

2025-03-27 19:57 UTC, kevincox commented on proposals/2545-emotes.md
> +## Security Considerations
Thank you for including this consideration in the MSC so that it can be explicitly considered.

2025-03-27 19:58 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +## Security Considerations
@kevincox thanks for bringing this up. I've attempted to address the concerns sufficiently in https://github.com/matrix-org/matrix-spec-proposals/pull/2545/commits/c24374872d4ae134928e40e57016e017c898ae71.

2025-03-30 00:56 UTC, anoadragon453 reviewed
Hello! I have heavily refactored the MSC in https://github.com/matrix-org/matrix-spec-proposals/pull/2545/commits/56639066e0b1a670f3868c44e241712d5cb562b3 to make it clearer.

The one functional change buried in that commit was clarifying that the `alt` attribute of a custom emote should be a description of the image, whereas the `title` should be the shortcode (what one would expect to appear in a tooltip). This felt more in line with what clients do today, and with the original intention for those attributes in the HTML spec.

Below are some outstanding questions I had after closely reading through the MSC again. Please weigh in to help this MSC move towards FCP :steam_locomotive:

2025-03-30 00:56 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +with clients that do not support custom emotes.
`height` is not a required field in `<img>` tags [as defined by the HTML standard](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element). Neither is it required by [the Matrix spec](https://spec.matrix.org/v1.14/client-server-api/#mroommessage-msgtypes).

So is it really required, or can we let it be omitted (and default to `32px`)?

2025-03-30 00:56 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +containing non-Latin characters for communities of those languages.
Should spaces be disallowed in shortcodes? I feel that if a shortcode has spaces in it, it may be tricky to filter for it in a client that pops up a search UI when typing `:`. Typically I would expect typing a space when searching to cancel the search.

2025-03-30 00:56 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +room ID and `state_key`.
Should we combine the `m.image_pack` and `m.image_pack.rooms` account data events into a single account data event? Such that `m.image_pack` would have a `rooms` field with the contents of the existing `m.image_pack.rooms` account data event?

My initial assumption for why this was originally done was account data event size limits. But actually, I don't think individual account data events *have* event size limits? Instead, it would make more sense for a homeserver to limit the total amount of account data a user could store.

So, what purpose is there in having two separate account data event types defined?

2025-03-30 01:43 UTC, Destinyg133 commented on proposals/2545-emotes.md
> +containing non-Latin characters for communities of those languages.
I agree with you, shortcodes should not have spaces. It would bring more complexity to case. Disallowing spaces in shortcodes is a best practice that improves usability, technical reliability, and consistency. If you want to support multi-word shortcodes, consider using alternative separators like hyphens or underscores

2025-03-30 01:59 UTC, Destinyg133 commented on proposals/2545-emotes.md
> +with clients that do not support custom emotes.
Default it to 32px if not present. No need to enforce it

2025-03-30 02:47 UTC, Destinyg133 commented on proposals/2545-emotes.md
> +room ID and `state_key`.
I have question(s) about this:

1. Users can define global packs for their account to be used in rooms or users could specify set of emojis only to be used in specific rooms?

2. Would admin/moderator allow and upload what they think its best suiting for room if its community driven

3. Can we limit that specific rooms dont allow emojis or just allow emojis defined by room from question 2

2025-03-30 15:29 UTC, SkyePrism commented on proposals/2545-emotes.md
> +with clients that do not support custom emotes.
true the default to 32px seems sensible

2025-03-30 16:57 UTC, HarHarLinks approved these changes
:tada: Overall, I can't wait for this to be officially approved. After all, it's shadow-spec for a couple years at this point ;) I do however think that improvements that enable better sharing features in this or a timely followup MSC would be important to enable shipping a complete feature.

2025-03-30 16:57 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
Besides a room pack being shared with the whole room, further potential mechanisms for sharing image packs are not described (https://github.com/matrix-org/matrix-spec-proposals/pull/2545#discussion_r753881475), though image pack "stores" seem integral to sticker and "emoji" features of other platforms. Clearly it would be possible to create 3rd party platforms that serve as indices for sticker pack rooms, similar to how https://servers.joinmatrix.org and https://matrixrooms.info exist. Sharing images packs is slightly more complicated, because to reference one, you need to reference a room AND an event, which however is well possible using matrix.to and matrix: URIs. The current approach in practise seems to be using spaces as an index.

Client developers aiming to implement a rich e.g. sticker pack UX might come up with the idea to offer a "share" button in the client's image pack management settings that would generate a matrix.to link to a pack's origin room and state event. It comes with some potential problems for the receiver as they might have to join the room, wait for join, maybe not being able to join an invite-only room, being confused why there is a new room in their room list, etc. The sharing user's client might check for some of these requirements, such as invite-only rooms, and even offer to alleviate them (semi-)automatically, e.g. by sending an invite (on the other hand potentially causing more confusion).

Many clients implement "pills" as a GUI shard that indicates a certain functionality, i.e. linking to users/rooms/events. However recipients have no way of indicating more info, e.g. whether the linked event is a state event, let alone an image pack. Nice rich UI for sharing "links" to image packs therefore remains open at this time.

---

Another related thought is that as this feature becomes available, a lot of people unfamiliar with matrix moderation might start creating public rooms to author and distribute their packs. Introducing an image pack room type was discussed prior at https://github.com/matrix-org/matrix-spec-proposals/pull/2545#discussion_r910190308. Yet even without it, clients may wish to create UX specific for creating new pack-only-rooms with reasonable power level setups similar to what is currently used as announcement rooms to limit the abuse potential. It is a nice side-product feature of this MSC that discussion of image packs in otherwise pack-only-rooms is possible, but I think that is not usually available on other platforms.

2025-03-30 16:57 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +## Security Considerations
There are currently 3 levels of "sharing" image packs proposed:
- the user is entirely in control of the packs. This is when the pack is defined in profile data, or in a room they are the sole admin of.
- the user is trusting a community. This is when the pack is defined in a room or space by that community's admins, and the pack is within the rooms itself the discussion is happening in.
- the user is trusting the pack author. this is when a user enables global use of a pack by referencing it in their profile data. This is very similar to the above, but prone to a higher risk imo, assuming that it will often be some lone random pack author without further association to a community besides the users of that pack.

In any case the user is not in alone control over the pack, they are vulnerable to an attack where those who can update the pack can add or entirely replace the previous content with abusive content. If this were to happen, said user would be upon opening their sticker picker etc the next time be presented with thumbnails of abusive content. 

A possible way to address this, could be "pinning" pack versions, by referencing the event ID at the time of "subscribing" to the pack (this was mentioned in a previous review). It would then be prudent for the client UX to also offer some kind of update notice (or a way to navigate and switch versions in general? if state supports that?) to the user. Updating of course then presents the problem again.

I'm not sure, but I would expect due to the nature of state events, having ignored certain users is no solution for this either, as one would still receive their state updates by necessity of keeping the room intact.

Over all, the impact of this issue seems like it would not be too severe; most pack owners are known in their communities etc. This might however change as image packs become a "mainstream" matrix feature, especially if Element decides to adopt it for its widespread clients.

2025-04-06 19:37 UTC, anoadragon453 reviewed
Thank you for the feedback, all! I've responded to or incorporated your comments below.

2025-04-06 19:37 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +with clients that do not support custom emotes.
Ah I see, it's for clients that don't support custom emojis. 32px sound good then.

I've updated the justification in bccfa910c7aa7ff33034a62b89421c93a75940bb.

2025-04-06 19:37 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +containing non-Latin characters for communities of those languages.
Spaces have been disallowed in 2f14ae15.

2025-04-06 20:59 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +NOT attempt to render images accessible through other URI schemes, as this may
I agree, and I'm fairly certain the spec does. It felt worth mentioning because it's fine that the MSC points out that the URI should be validated for being an mxc, yet if the client then goes and fetches and displays an unsanitised svg that is obviously bad.
Feel free to resolve this if there isn't anything to be added at this point.

2025-04-06 21:09 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +A client should treat an `<img>` tag as a custom emote if the custom
I'm not sure what the issue (2.) with clients simply switching over to stable IDs would be, since as you say, there aren't compatibility concerns?

> What if you aren't in the referenced room?

I don't follow entirely. Then you still know what room to get the sticker pack from, and your client might even show you a join (public) or knock button, or a lock if it can determine that it is invite only.

But I agree this doesn't need to block this MSC, it would merely be nice to have.

2025-04-06 21:26 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +#### `m.image_pack.rooms` account data event
Hm, I think I have 2 arguments here:
1. We get via this MSC "room packs", i.e. the proposed UX is roughly that in a given regular chat room used primarily for chatting, the moderators can upload images to a pack which is stored in the same room, and then any member of the room will have their sticker/emoji picker suggest the images from that pack while viewing that specific room. I don't see why we would limit this such that in my Matrix Workation Thailand 2025 space, which will never canonically have `#blobhaj:the-apothecary.club` as a parent, I can't default that (my) community to be able to use the blobhaj pack. Wouldn't it be neat? Especially as the feature is basically already designed.
2. We already have the technical side modeled and included elsewhere (personal packs) and it would actually simplify this MSC to use it in both places

Again, not a blocker imo, maybe I am misjudging users/the use case.

2025-04-06 21:28 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +## Security Considerations
What about the ~~security~~ safety considerations around the topic?

2025-04-06 21:37 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +room ID and `state_key`.
> Looks like there is some precedence similar to the naming convention:
> 
>     * SSSS: `m.secret_storage.key.<key_id>`, `m.cross_signing.master`, `m.cross_signing.user_signing`
> 
>     * [MSC3890](https://github.com/matrix-org/matrix-doc/pull/3890): `org.matrix.msc3890.local_notification_settings.<device_id>`

These look like different cases? Here in MSC2545 we propose to have both `m.image_pack` and `m.image_pack.rooms`. Does a `m.cross_signing` (not `m.cross_signing.*`!) event exist that my Ctrl+F is missing?

Besides that, yes I am sure this proposal was aiming to sort its events into a common namespace, which is more than reasonable.

2025-04-07 03:30 UTC, Destinyg133 commented on proposals/2545-emotes.md
> +#### `m.image_pack.rooms` account data event
Sharing packs via links can feel like a detour, requiring users to venture out and manually add them to their accounts. In contrast, integrating room-specific packs directly into the interface makes them effortlessly accessible, fostering a sense of community and collaboration.

Links often represent solo creations, lacking the shared spirit of community-driven packs. By centralizing pack management within rooms or spaces, moderators can curate content without external tools, simplifying tasks and empowering communities to thrive.

Imagine a professional Matrix space with sleek emoji packs and a casual room bursting with fun emojis —each tailored to its unique vibe. This localized approach not only enhances usability but also personalizes the experience, making it more enjoyable and engaging for everyone involved.

2025-04-11 08:53 UTC, witaliy12 commented
https://github.com/ton-blockchain/wallet-contract/issues/348

2025-04-12 21:45 UTC, AverageHelper commented
@witaliy12 ?? Looks like spam...

2025-05-13 08:46 UTC, shootie22 commented
any updates on this? seems like it's almost all the way there

2025-05-13 21:12 UTC, zbee commented on proposals/2545-emotes.md
> +## Security Considerations
I think with c243748 and MSC3414 in general, this chain _could_ be marked as resolved.
I personally think it _should_ be, especially considered the existing adoption of this MSC, but if not then MSC3414 should probably be listed more noticeably as a requirement.

2025-05-13 21:34 UTC, zbee commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
Pack sharing does strike me as a fairly important consideration, and could be a whole new `### Sharing` section under `Proposal`. However that would be quite the addition, perhaps even just deserving of being a future MSC.
If such an addition to this proposal is not desired, I think this chain could be marked as resolved.
Otherwise ... would a PR to [soru/emotes](https://github.com/Sorunome/matrix-doc/tree/soru/emotes) be the way to go?

2025-05-13 21:43 UTC, zbee commented on proposals/2545-emotes.md
> +## Security Considerations
Maybe the safety considerations warrant being called out, but I agree that it should be left to a future MSC - this isn't a feature or a consideration that other platforms have, and seems to be a pretty uncommon attack vector.

2025-05-13 21:47 UTC, zbee commented on proposals/2545-emotes.md
> +## Security Considerations
A new room type would certainly be a good approach to that, I think; but certainly agree that it'd be something for the future.
Given that, I think this chain could be resolved, especially since it is already noted under Future MSCs (and, to reiterate: https://github.com/matrix-org/matrix-spec-proposals/pull/2545#discussion_r1008134381).

2025-05-20 16:04 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +room ID and `state_key`.
> These look like different cases? Here in MSC2545 we propose to have both `m.image_pack` and `m.image_pack.rooms`. Does a `m.cross_signing` (not `m.cross_signing.*`!) event exist that my Ctrl+F is missing?

I suppose they are slightly different.

We could aim for `m.image_pack.user` instead of `m.image_pack` to be more consistent. It wouldn't break backwards-compatibility either as clients today are using `im.ponies.user_emotes`. I'm not too fussed either way though - curious what others think.

2025-05-20 16:11 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +A client should treat an `<img>` tag as a custom emote if the custom
> I'm not sure what the issue (2.) with clients simply switching over to stable IDs would be, since as you say, there aren't compatibility concerns?

Sorry, by that I meant that I would prefer to keep the changes required to a client to declare support for MSC2545 as minimal as possible, if they've already implemented a previous version of MSC2545. This allows the ecosystem to more quickly adopt the new identifiers.

> I don't follow entirely. Then you still know what room to get the sticker pack from, and your client might even show you a join (public) or knock button, or a lock if it can determine that it is invite only.

I suppose I was saying that a client would need to add the extra logic to check for whether the room can be joined/knocked on, and designing UI around that. It would be a significant amount of extra work to implement MSC2545.

The behaviour you briefly described should go in the follow-up MSC though. It would be good to draft that up.

2025-05-20 16:20 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +# MSC2545: Image Packs (Emoticons & Stickers)
@zbee the original author, who controls https://github.com/Sorunome/matrix-doc, is no longer working on matrix. As members of the Spec Core Team, we have access to the `soru/emotes` branch, but not the entire upstream repository. As such, we won't be able to interact with/approve a PR made to https://github.com/Sorunome/matrix-doc. Suggestions are thus best made in PR comments here, and I can integrate those into the document in the branch.

re: this comment, I think [the above](https://github.com/matrix-org/matrix-spec-proposals/pull/2545/files#r2020190557) will naturally be figured out by clients implementing the MSC and sticker index projects being built. I think it best to let these emerge naturally, then incorporate the lessons into either the spec or "client implementation guides" after the fact.

2025-05-20 16:49 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack.rooms` account data event
@HarHarLinks the use case example helped, thank you for providing that!

If I understand you correctly, you're suggesting adding a `m.image_pack.rooms` room state event with the equivalent definition as the same-named account data event (plus a `state_event` field)? And clients would then behave as if the room had an `m.image_pack` state event present with the referenced content?

That works, though recall that we don't have federated peeking, and users won't be in all referenced rooms. Thus, clients should add some UI to prompt the user to join the referenced room.

---

I think this would lead to de-duplication, which is a good thing. It also feels like a very natural thing to add to this MSC, with little controversy, rather than a follow-up. I've added this in d6e4e3902637e6c1d6db67929712cfee303f56a3.

2025-05-20 16:50 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +## Security Considerations
Given there's been no other input, let's resolve it then.

2025-05-20 17:04 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +A client should treat an `<img>` tag as a custom emote if the custom
Given I just added a new feature in https://github.com/matrix-org/matrix-spec-proposals/pull/2545/files#r2098450162, I should walk this back a bit:

> I would prefer to keep the changes required to a client to declare support for [MSC2545](https://github.com/matrix-org/matrix-doc/pull/2545) as minimal as possible

This still feels like a larger change than that one was though, as we'd need to add a new query parameter to Matrix URIs (`image_pack`), which I feel could involve some back and forth.

I think what I really meant was that I'd like to *get this MSC over the line*, and thus I'm adverse to introducing new areas of potential bikeshedding.

2025-05-20 17:07 UTC, anoadragon453 commented
All threads that don't require input from a wider audience have been resolved. As such, I propose this MSC be considered by the rest of the SCT:

@mscbot fcp merge

2025-05-20 17:10 UTC, anoadragon453 commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

Checklist:
- [x] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal)
  specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example,
          modifying the set of redacted fields changes how event IDs are calculated,
          thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with
    [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved.
      Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present,
  the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail
  any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.".
  See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about,
  but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

@mscbot concern checklist incomplete

2025-05-20 17:20 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +## Security Considerations
I've referenced this discussion under the "Security Considerations" section in 50512feeb7e3acab1622d39d8e835290ee0d6c74.

2025-05-20 17:41 UTC, turt2live approved these changes
thanks for working on this. I haven't read the MSC in detail, but the parts I did read look more than sufficient for starting FCP in my opinion.

2025-05-31 15:56 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This restriction MUST be
Good point! I've done some research to try and figure this out. To clarify, there's a difference between "valid UTF-8 byte sequences" and "valid Unicode scalar values".

Not every byte sequence can be decoded as valid UTF-8. Therefore, if we allowed *any* sequence of bytes (as the proposal currently does), text decoders may panic upon attempting to blindly decode them. For this reason, we absolutely should restrict the grammar to only "byte sequences that can be decoded as UTF-8".

Separately, the set of "valid Unicode scalar values" is a range that has been stabilised since 2003 ([RFC 3629](https://www.rfc-editor.org/rfc/rfc3629)) and is unlikely to change. We _could_ restrict the grammar to this range to avoid causing any Unicode parsers to fail. This seems reasonable to me.

The Unicode consortium *assign* new codepoints every year in each Unicode update. It would be foolish to restrict to only the currently valid set of assigned codepoints, as that would break forwards-compatibility.

Given the above, the grammar rules could be:

1. The value must be a well-formed UTF-8 byte sequence;
2. After decoding, every code point must be a Unicode scalar (i.e. not a surrogate or noncharacter);
3. Length ≤ 100 bytes;
4. Must not contain `:` (`U+003A`) or ` ` (`U+0020`).

What do you think?

2025-05-31 16:37 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +pack `my pack`.
Indeed, it will conflict, good point! And `:` is much easier to type.

It's important to note that this is purely a suggestion for clients to add a feature to auto-complete emotes when typing. It does not need to be a unique representation of the emote. For instance, two image packs could have the same exact name as well.

2025-06-03 10:31 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +The `:` character MUST NOT be included in the emote shortcode. The `:` character
We should also formally exclude `U+0000` (`NUL`) characters from shortcodes, as some parsers can treat that character as "end of string".

2025-06-03 14:35 UTC, Gremious commented on proposals/2545-emotes.md
> +The `:` character MUST NOT be included in the emote shortcode. The `:` character
Should it also exclude EOL characters in that vein? I kind of doubt anyone will actually use those since multiline short-codes would be strange, but I don't know if we prefer to be explicit

2025-06-03 15:18 UTC, Sir-Walrus commented on proposals/2545-emotes.md
> +pack `my pack`.
I'd prefer putting the emoji name before the pack name. This increases UI consistency if user forgets whether that emoji name is unique (still starts out with typing :towel), and if user wants to type emoji name or pack name then click/touch the correct emoji, typing emoji name will likely return fewer choices than pack name.

I think @ would be the best candidate, so you get (for example) :towel\@h2g2: (towel emoji @ h2g2 emoji pack).

2025-06-03 15:52 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +pack `my pack`.
> I'm going to strip that suggestion as a result and replace it with a warning.

I don't really understand - you will remove the suggestion for the client to fully automatically replace the shortcode completed with the second `:` because it's not deterministic? Why wouldn't a client simply recognise that there are 2 packs using that code and thus leave the autocompletion going until a unique (from the user/client's perspective) identifier was entered?

> I'd prefer putting the emoji name before the pack name.

The current, organically evolved convention seems (?) to be `:neocat_floof:`, `:neofox_floof:`, etc. I.e. effectively `:` + $packname + `_` + $emote_name_snake_case + `:`. I think I want to agree with Alcaro, because at least in some of the current implementations, the search is not great, and you often have to type shortcodes ~completely. I would hope that with this extension, the implementations become better at this, so the UX with the 2 emoticons above would be that I type `:floo` and the client is smart enough to filter the results down to `:floof:`, and then given there are 2 packs using this shortcode show its usual UI, e.g. dropdown-like where I can navigate with arrow keys between the one from neocat and neofox packs. If I already know what I want from the start, I can type `:neofox/floof:` and get the right one fully completed, or I should also be able to type `:neofox/` (possibly also only `:neof`?) and get a UI letting me select all emoticons from that pack (and other matches without `/`).

2025-06-03 15:54 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +The `:` character MUST NOT be included in the emote shortcode. The `:` character
Just NUL seems to match https://spec.matrix.org/latest/appendices/#room-ids. I fear we might find a lot of characters in unicode that might warrant some kind of exception :thinking:

2025-06-03 16:14 UTC, Sir-Walrus commented on proposals/2545-emotes.md
> +pack `my pack`.
Another option would be to reserve both @ and /, and permit both :towel@h2g2: and :h2g2/towel: (presumably rewriting one to the other at some point).

I don't know if it's a good option, but it's worth considering, at least. Being able to type the pack name and see a list of its contents could be helpful if the user forgets how exactly the emote is spelled, or just wants to see what's available.

2025-06-03 20:10 UTC, clokep commented on proposals/2545-emotes.md
> +pack `my pack`.
> Why wouldn't a client simply recognise that there are 2 packs using that code and thus leave the autocompletion going until a unique (from the user/client's perspective) identifier was entered?

~~Yeah -- this would be my thought too, I'm having some trouble envisioning what the concern is here. Is the expectation that clients will keep the text and then replace on send vs. directly insert the image into the text box? Does that give different experiences or something?~~

That didn't make any sense. ☝️ 

Regardless my concern is mostly that whatever character is used as a separated needs to be protected from being in the names. 👍

2025-06-03 20:11 UTC, clokep commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This restriction MUST be
Actually -- are we limited by what's allowed in an event/message already here? Otherwise you might have a mostly correct message with an invalid short-code?

2025-06-03 20:13 UTC, clokep commented on proposals/2545-emotes.md
> +pack `my pack`.
Does the user need to ever see the full short code? Does it make sense to use `:!roomid:.../shortcode:` so that it is easy to look up for clients?

2025-06-03 21:01 UTC, tulir commented on proposals/2545-emotes.md
> +pack `my pack`.
> Does the user need to ever see the full short code? Does it make sense to use `:!roomid:.../shortcode:` so that it is easy to look up for clients?

Shortcodes are only for users doing tab-completions and such, machines don't need them for anything. This whole thread is about a client UI suggestion

2025-06-03 21:39 UTC, clokep commented on proposals/2545-emotes.md
> +pack `my pack`.
Yeah I realized that after commenting, but didn't want to edit it for a fifth time. I think realistically you'll probably have an image in the UI anyway so the specific short code disambiguation doesn't matter?

2025-06-04 10:02 UTC, richvdh reviewed
excites to see progress on this!

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +Unicode's 🦊, 🐱, etc. This differs from new images; which is what custom
nit
```suggestion
Unicode's 🦊, 🐱, etc. This differs from new images, which is what custom
```

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +type](https://spec.matrix.org/v1.14/client-server-api/#msticker). They are
Nit
```suggestion
Stickers already exist in Matrix (see the [`m.sticker` event
type](https://spec.matrix.org/v1.14/client-server-api/#msticker)). They are
```

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +aide the visually impaired. That is more suitable to the `body` field; defined
nit

```suggestion
aide the visually impaired. That is more suitable to the `body` field, defined
```

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +* `images`: **Required, Map[String, Object]**. A map from a shortcode to an Image Object.
link to the notes on shortcode grammar here?

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +* `images`: **Required, Map[String, Object]**. A map from a shortcode to an Image Object.
```suggestion
* `images`: **Required, Map[String, Object]**. A map from a shortcode to an [Image Object](#image-object).
```

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +* `pack` **Optional, Object**. A Pack Object.
```suggestion
* `pack` **Optional, Object**. A [Pack Object](#pack-object).
```

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +Note that an empty object under a room ID, for example:
```suggestion
An empty object under a room ID, for example:
```

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This restriction MUST be
"Valid UTF-8" is somewhat implied by the fact that it has to be transferred over a JSON REST API as part of an event (though it's certainly the case that the spec could do better on this: it's one of the many things discussed in https://github.com/matrix-org/matrix-spec/issues/365). Anyway, I wouldn't bother calling it out for this instance: clients can and do reasonably expect that they can utf-decode all event content.

Ditto the surrogates, and (fwiw) characters above U+10FFFF.

You mention "noncharacters": are you talking about things like U+FDD0? We don't special-case those elsewhere afaik, so I wouldn't do so here.

More to the point, though, I question why we are specifying this in bytes rather than unicode codepoints. All the clients and servers I know of work in unicode codepoints at this level; to determine if a shortcode is longer than 100 bytes they would have to *re-encode* those strings back into utf-8 and see what the result is. (Admittedly I haven't actually looked at server impls other than Synapse, so maybe this is bogus logic, but remember that to even get as far as inspecting a shortcode you've had to deserialize the JSON into some sort of higher-level object).

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This restriction MUST be
maybe we don't even need a length limit? suppose somebody makes a shortcode that is 62000 bytes long. What have they achieved, other than filling their entire image pack with a single shortcode?

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +enforced by servers when sending reactions, but servers MUST NOT reject events
Why the sudden mention of reactions?

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +having too many bytes in the shortcode field.
I assume this whole requirement for servers applies to the rest of the grammar, not just the length?

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +having too many bytes in the shortcode field.
I'm a little surprised that we're requiring servers to enforce this grammar rather than clients. Typically, we've steered clear of requiring servers to do much in the way of validation on event bodies.

We're probably going to have to answer the question "what should clients do when they see a shortcode that doesn't match the grammar" anyway (since homeservers may be old, and anyway they "MAY opt to locally redact events" rather than MUST).

Was any thought given to putting the requirement for enforcing grammar on the client rather than the server?

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +multiple other byte sequences associated with spaces in Unicode.
> There are multiple other byte sequences associated with spaces in Unicode.

... which are allowed, or not? This is unclear.

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +The `alt` attribute MUST be present. Its value SHOULD be the `body` of the emote, or if unavailable, its shortcode.
to be clear, if any of these MUST requirements on the attribute are not adhered to, a receiving client should refuse to render them?

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +pack `my pack`.
IMHO, this whole discussion feels like a thing that could reasonably left up to clients, rather than worrying about it in the spec.

2025-06-04 10:02 UTC, richvdh commented on proposals/2545-emotes.md
> +| `m.image_pack.rooms` account data event type | `im.ponies.emote_rooms` |
`m.image_pack.rooms` state event?

2025-06-04 11:02 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +pack `my pack`.
@richvdh the spec angle concerns whether we should bar a specific character from the shortcode grammar for clients to use in order to implement such a feature.

I agree that we should stop arguing about the order of pack name vs. emote name here though. The only relevant discussion to this forum is which character to bar from the grammar. The current contenders are:

* `/`
* `_`
* `~`

> The current, organically evolved convention seems (?) to be `:neocat_floof:`, `:neofox_floof:`, etc. I.e. effectively `:` + $packname + `_` + $emote_name_snake_case + `:`.

This only works if `$packname` doesn't contain any `_`, which feels counter-intuitive if emote names are `snake_case`.

I still find `~` difficult to type.

I would be in favour of reserving both `/` and `@` (as anecdotally from my own experience, they are uncommon in emote names) and letting clients make use of them however they like. For this feature, it's *okay* if client A starts using `/` and client B starts using `@`.

2025-06-04 18:30 UTC, zbee commented on proposals/2545-emotes.md
> +pack `my pack`.
I agree that `_` is probably not the best choice. Am personally more a fan of `@` or `~`, but really just anything other than `_`.
Thought I will say that an `@` feels like it makes more sense if the pack name came after the emote name.

2025-09-10 20:57 UTC, EmDash00 commented on proposals/2545-emotes.md
> +multiple other byte sequences associated with spaces in Unicode.
In context it is poorly worded. The above paragraph specifies the intention.

```
In addition, the space character is not allowed. This helps avoid common usability paper-cuts (multiple spaces between words, spaces at the beginning/end of a shortcode). Shortcodes containing multiple words are encouraged to use alterantive separators like hyphens or underscores.
```

This paragraph is below the intention, and is meant to clarify what exactly is not allowed. Considering the intent (arbitrary spacing between words). It might be good to avoid negation, which is typically bad for readability. Instead of saying what isn't allowed, say what is. This also addresses concerns regarding the null character all in one.

```suggestion
In addition, only non-separator graphic unicode characters are allowed. This helps avoid several problems:

1.  **Typos and Usability Issues:** Prevents problems caused by varying whitespace between words or at the beginning/end of a shortcode. Shortcodes containing multiple words are encouraged to use alternatives (hyphens, underscores, casing, etc.), to create a visual separation between words.

2.  **Null Character:** Disallows shortcodes that contain the null character (`U+0000`), which may be interpreted as a string terminator by many processors.

3.  **Control Characters & Security:** Disallows malicious shortcodes that contain control characters such as backspace (`U+0008`), delete (`U+007F`), or carriage return (`U+000D`). These characters serve no legitimate purpose in this context and may even be exploited to engineer security vulnerabilities.
```

2025-09-10 22:22 UTC, EmDash00 commented on proposals/2545-emotes.md
> +#### Custom emotes
We should just reword the entire paragraph. It's not super clear what MUST and SHOULD mean in this context. Additionally, `alt` and `title` are not required in HTML. They are for providing accessibility or tooltips. We should prioritize rendering something over completeness.

```suggestion
#### Custom emotes

Custom emotes are sent into rooms as `<img>` tags within the `formatted_body`
field of an
[`m.room.message`](https://spec.matrix.org/v1.14/client-server-api/#mroommessage)
event. Many existing clients already render `<img>` tags in message bodies when
they render HTML, and it's logical to reuse that functionality here.

To allow clients to distinguish custom emotes from other inline images, a new
attribute, `data-mx-emoticon`, is introduced to the `<img>` tag:

```html
<img data-mx-emoticon src="mxc://example.org/emote" alt="A cat holding a paper heart" title="cat_luvs_u" height="32" />
```
Emote tags are detailed below. Attributes are categorized by their requirement level:

- **Required**: The attribute MUST be present for the tag to be considered a valid custom emote. Clients MUST NOT render invalid custom emotes and MAY fall back to rendering a standard image or ignoring the tag.

- **Recommended**: The attribute SHOULD be present. Its absence does not invalidate the emote but may reduce usability or accessibility.

- **Optional**: The attribute MAY be present. Its absence does not affect validity or core functionality.

- `data-mx-emoticon`: **Required**. A client MUST treat an `<img>` tag as a custom emote ONLY IF the custom
`data-mx-emoticon` attribute is present; otherwise, the client SHOULD treat the tag as an ordinary image. Any values assigned to `data-mx-emoticon` are ignored and clients SHOULD make no assumptions about the existence or structure of any value assigned to the `data-mx-emoticon`.

- `src`: **Required*. The client MUST ignore any image tags without a valid `src` attribute. Clients MUST treat the `src` attribute as valid only if it is in  [Matrix Content (MXC)
URI](https://spec.matrix.org/v1.14/client-server-api/#matrix-content-mxc-uris).
Clients MUST treat other URI schemes, such as `https`, `mailto` etc. as invalid. Clients MUST NOT attempt to render images accessible through other URI schemes, as this may lead to unintended network requests. Clients MUST sanitize valid URIs before rendering.

- `title` *Recommended.* This attribute's meaning is inherited from the [HTML specification](https://html.spec.whatwg.org/multipage/dom.html#attr-title). It is primarily used for advisory information like tooltips. Its value SHOULD be the shortcode of the emote. If not present, a tooltip will not be shown.

- `height`: **Recommended.**. Clients SHOULD set height to "32px" . If the height attribute is missing, clients SHOULD assume a default height of 32px. This is a default intended to look good on most devices, and is for the benefit of legacy clients that do not treat custom emotes differently from other inline images. Clients implementing this MSC SHOULD ignore this value for rendering purposes. They are expected to override the height and render emotes based on their own UI requirements (e.g., the user's font size, displaying messages containing only emoticons in a larger font, etc.).

- `width`: **Optional**. This attribute is not required. Clients SHOULD maintain the aspect ratio of non-square emotes.

- `alt` **Recommended**. The `alt` attribute's meaning is inherited from the HTML specification:
<https://html.spec.whatwg.org/multipage/images.html#alt>. It is primarily used
for accessibility purposes in describing an image for visually impaired users. Its value SHOULD be the `body` of the emote, or if unavailable, its shortcode. If the alt attribute is not present, clients SHOULD fall back to the title. If the title attribute is not present, clients SHOULD assign their own default alt text. 
```

2025-09-10 22:38 UTC, EmDash00 commented on proposals/2545-emotes.md
> +with clients that do not support custom emotes.
I made a recommendation myself. I think since it's not enforced currently we shouldn't enforce it in this MSC. It should be recommended, but otherwise fine if it's not. I don't think it's a significant degradation to have legacy clients displaying something at 1024px occasionally.

2025-09-10 22:44 UTC, EmDash00 commented
Happy to help push this to get to FCP. I think we're getting close. Added a few comments above. What still needs to be resolved? Pinging @anoadragon453 for pointers.

2025-09-12 00:30 UTC, EmDash00 commented on proposals/2545-emotes.md
> +pack `my pack`.
> I would be in favour of reserving both `/` and `@` (as anecdotally from my own experience, they are uncommon in emote names) and letting clients make use of them however they like. For this feature, it's _okay_ if client A starts using `/` and client B starts using `@`.

I think there are a couple thoughts here:

1. It doesn't matter what is chosen as the shortcode as the client can decide whatever syntax they want to trigger completion. I think `/` is the most pragmatic choice as clients may hierarchically search and render results that way. Clients can still use the `@` syntax as syntactic sugar without it actually being reserved by the pack shortcode grammar.
2. Choosing a single reserved character makes it easier for clients and simpler to handle.
3. Escape sequences exist for a reason. Clients can use `\` to distinguish between a syntactic character trigger and a literal. Discord already does this with commands. You can tell someone how to write a command by using `\/command` to tell it that the `/` is literal and not syntax.

That being said, yes, let's put this to rest. I think this entire section should be deleted and the `/` should be put into the grammar section with the suggestion that it be used as a hierarchical separator.

2025-10-22 20:52 UTC, Destinyg133 commented
@anoadragon453 any news on this?

2025-11-03 20:46 UTC, Enovale commented
I have opened [MSC4377](https://github.com/matrix-org/matrix-spec-proposals/pull/4377) that builds on top of this MSC to clarify the ordering of image packs within a source (to allow for users to reorder packs as they wish).

2025-11-03 21:10 UTC, SkyePrism commented
> @anoadragon453 any news on this?

Maybe one day we can pass this MSC to our grandkids.

Btw this joke isnt intended to disrespect all the great contributors to this giant MSC. Thanks anoa and any other contributors for pushing this along.

2025-11-14 13:16 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +pack `my pack`.
Resolved in b259a848.

2025-11-14 13:46 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +`:shortcode:` or `:image-pack-name:shortcode:` in the message field to a
sorry, did I miss something? i think the intention was to say
```suggestion
it to each emote's shortcode, using a `/` to separate shortcode and image pack.
For instance, the user could enter `:my_emo/my_pack_na:` to quickly surface an
image with shortcode `my_emote` in the pack `My Pack Name!`.

It's important to note that image pack names aren't globally unique either, so
even `:emote/my-pack:` could refer to multiple possible emotes. Thus, it is not
recommended to add a feature to clients to try and automatically translate
`:shortcode:` or `:shortcode/image-pack-name:` in the message field to a
```

2025-11-14 13:46 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +of a shortcode). Shortcodes containing multiple words are encouraged to use alterantive separators like hyphens (`-`) or underscores (`_`).
```suggestion
of a shortcode). Shortcodes containing multiple words are encouraged to use alternative
separators like hyphens (`-`) or underscores (`_`).
```

2025-11-14 15:08 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +`:shortcode:` or `:image-pack-name:shortcode:` in the message field to a
Whoops, that was from a previous draft of updating the separators paragraph from months ago. Nice catch!

2025-11-14 15:21 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +enforced by servers when sending reactions, but servers MUST NOT reject events
This limitation originated from [a discussion](https://github.com/matrix-org/matrix-spec-proposals/pull/4027#discussion_r1232671292) on MSC4027, and it looks like the [text did too](https://github.com/beeper/matrix-spec-proposals/blob/custom-images-in-reactions/proposals/4027-custom-images-in-reactions.md#proposal):

> The shortcode must have a length of less than or equal to 100 bytes (including the colons at the beginning and end of the string). This restriction must be enforced by servers when sending reactions ...

The justification (which I didn't include here!) was:

> field length [...] can be checked cheaply by homeservers [...] The benefit it provides is preventing a malicious actor from sending [...] a shortcode length close to the event size limit, therefore potentially causing issues with sending other events that reference it in some way.

Which still seems reasonable to me. What do you think?

I've added it to the current MSC so it's at least written down: 2a3ff672.

2025-12-11 00:12 UTC, maxwell-kalin commented
> > @anoadragon453 any news on this?
> 
> Maybe one day we can pass this MSC to our grandkids.
> 
> Btw this joke isnt intended to disrespect all the great contributors to this giant MSC. Thanks anoa and any other contributors for pushing this along.

same, i really hope this gets official since element seems to wait for this standart

2025-12-13 14:05 UTC, tulir commented on proposals/2545-emotes.md
> +to a future MSC.
A future MSC exists now: https://github.com/matrix-org/matrix-spec-proposals/pull/4389

2026-01-30 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack.rooms` account data event
Do we actually need the concept of a separate, personal image pack (`m.image_pack` account data event)? It feels unnecessary to me for two reasons:

1. You can already define (unlimited) packs in rooms and save them to your profile via `m.image_pack.rooms`.
2. If users want to eventually share the stickers in this pack, they'd have to have their client copy them into a new room (and then they'd get out of sync as the user updated their personal pack again).

It would be much more simple to only have room-based packs, without these limitations. So do away with the `m.image_pack` account data event, and just keep the `m.image_pack.room` event, which points to image packs in rooms.

The only downside to having an image pack that you don't intend to share is that it'd appear in your room list. But this could be solved in a future MSC with a new room type (i.e. `m.image_pack_room`) which clients would recognise and hide by default.

Clients could still support creating an image pack in user settings, they would just create a room in the background.

(The room type would also allow you to build a "list of recommended emoji packs" by abusing the public rooms list. Similar to what clients do today for spaces, you could filter by image pack room type to get a curated list of emojis to choose from).

2026-01-30 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +    available in account data.
@tobiasfella suggested IRL at FOSDEM '26 to remove this field, and I agree with them.

Being able to override the usage may sound interesting in theory, but in practice having an image pack with one usage, but an image within with a conflicting usage leads to a confusing user experience.

For instance, imagine if you have an image pack with `"usage": ["sticker"]`. Then, one of 50 image within is marked as `"usage": ["emoji"]`. You'd think of this pack as a "sticker pack", but wouldn't see one of the images in the sticker picker. And you'd see what appears to be another pack (with the same name) in your emoji picker, but with only one image. This is a really confusing UX, especially when it comes to designing a Settings screen for it. You're essentially splitting a single image pack into two, image-by-image.

The `usage` field makes sense at the pack level (prevent low-res emoji packs from appearing in a user's sticker picker UI), but less so at the individual image level IMO.

2026-01-30 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack.rooms` account data event
So: remove `m.image_pack` and keep `m.image_pack.rooms`.

2026-01-30 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +forwards-compatibility with future Unicode updates.
@turt2live, @TobiasFella and I discussed this IRL at the Matrix hackathon at FOSDEM '26. We came to the conclusion that allowing the entire UTF-8 spec for an identifier would lead to a lot of edge cases for clients to cover. These identifiers will also find their way into other events. Other applications don't allow such a broad spectrum of characters (Discord only allows a subset of ASCII, Telegram only emoji) and users of those services are happy (AFAIK).

Excluding spaces, `:` and `/` characters is still important, as well as including `-` / `_` to help separate words, as already detailed in the MSC.

The following, simple grammar is proposed: `[a-zA-Z0-9-_]+`. Shortcodes *are* considered case-sensitive. Also importantly, this grammar matches [that of Discord](https://support.discord.com/hc/en-us/articles/360036479811-How-to-Add-Custom-Emojis-on-Discord#:~:text=Keep%20in%20mind:-,Emoji%20names%20must%20be%20at%20least%202%20characters%20long%20and%20can%20only%20contain%20alphanumeric%20characters%20and%20underscores,-Emojis%20must%20be) and [Slack](https://docs.slack.dev/reference/methods/admin.emoji.add/#:~:text=The%20name%20of%20the%20emoji%20to%20be%20added%20%28using%20lower%2Dcase%20letters%20only%29), allowing for easy bridging.

To help users of non-latin languages, a future MSC could add one or more aliases (with full UTF-8) to provide additional keywords to search for.

2026-01-30 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +having too many bytes in the shortcode field.
Yes, it should apply to the whole shortcode grammar; not just the field length.

And it would be clearer to split enforcement by CS API vs. Fed API, where it's only enforced on the former.

2026-01-30 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +    empty, all possible usage types are assumed.
We should make it clear that clients can still use image packs for any purpose they like, and that the `usage` field is really just a suggestion.

2026-02-02 14:38 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +#### `m.image_pack.rooms` account data event
Another technical difference of account data is that it supports unlimited pack size. I think we can probably reasonably ignore this, there are some advantages to chunking packs into max size anyway?

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
Has any client actually ended up making use of this? From a brief look at Cinny and FluffyChat, they don't appear to be. If not, we should remove it.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack.rooms` account data event
I've removed the `m.image_pack` account data entry in bad3ac8d806289d7ffd8e689f8e7ccc1a3b737bc.

> Another technical difference of account data is that it supports unlimited pack size. I think we can probably reasonably ignore this, there are some advantages to chunking packs into max size anyway?

It does support unlimited size, though I wouldn't be surprised if the spec tries to limit the size of account data in the future (to guard against DDoS).

You can get pretty far with a single pack in a state event (~400 images IIRC). Past that point, I think it socially makes a lot of sense to break it up into multiple packs.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### Custom emotes
I agree that we shouldn't exclude rendering an event if it's missing the `alt` or `title` attribute. I've included your recommendations in ba60a925893372e2c784237e06f1fed087fb396f.

However, I'm not convinced it's worth defining the `width` attribute if we don't want clients to use it? I included it in the description of `height` just in case anyone thought it was forgotten about.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +    empty, all possible usage types are assumed.
Done in ba954c2ef388900f26d7db2971574f2e6fb9b537.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +    available in account data.
Image-level `usage` field removed in e5f497429f74ce5e35036d63d3905e823b104912.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +room ID and `state_key`.
This conversation is no longer relevant after the `m.image_pack` account data field was removed in bad3ac8d806289d7ffd8e689f8e7ccc1a3b737bc.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +enforced by servers when sending reactions, but servers MUST NOT reject events
Resolved in 980e9352ffa531bb6acf68e6fc1ff559f5d0ebec.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +having too many bytes in the shortcode field.
Resolved in 980e9352ffa531bb6acf68e6fc1ff559f5d0ebec.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +The `:` character MUST NOT be included in the emote shortcode. The `:` character
No longer relevant after c786d482963aadfc5f2b02b52411db85ef08ae24.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +forwards-compatibility with future Unicode updates.
New shortcode grammar has been added in c786d482963aadfc5f2b02b52411db85ef08ae24.

2026-02-04 17:35 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +The `alt` attribute MUST be present. Its value SHOULD be the `body` of the emote, or if unavailable, its shortcode.
Resolved by ba60a925893372e2c784237e06f1fed087fb396f making these fields SHOULD, instead of MUST.

2026-02-07 20:46 UTC, Destroyer commented
I've been waiting for years—will custom emotes or GTA 6 be released first?

2026-02-07 21:03 UTC, thisisjoesGH commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
At least Cinny, FluffyChat, Nheko, and Commet appear to be using it with the correct unstable identifier `im.ponies.room_emotes`, unless you are referring to something other than the state event.

2026-02-09 16:06 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
Ah, sorry, this was put on the wrong title. I meant to put this under the `m.image_pack.rooms` header below. Let me recreate this thread.

2026-02-09 16:37 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +said packs.
Has any client actually ended up making use of this? From a brief look at Cinny and FluffyChat, they don't appear to be. If not, we should remove it.

2026-02-09 16:39 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
Ah! This should have been left under the `m.image_pack.rooms` state event heading instead. I've moved it there -> https://github.com/matrix-org/matrix-spec-proposals/pull/2545#discussion_r2765147600.

2026-02-09 20:34 UTC, ranidspace commented on proposals/2545-emotes.md
> +said packs.
I think cinny does have it, i noticed in my "global account data" there's an `im.ponies.emote_rooms`, and the room defined there appears in my emojis and stickers list.

2026-02-09 20:42 UTC, tulir commented on proposals/2545-emotes.md
> +said packs.
@ranidspace the comment is specifically about state events. Everyone uses the account data event defined earlier, but I don't think anyone uses it as a state event (+1 to removing, I hadn't even realized this was defined as a state event)

2026-02-09 21:03 UTC, ranidspace commented on proposals/2545-emotes.md
> +said packs.
Ah I see, my mistake

2026-02-10 10:38 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +said packs.
Right, removed in 5e00fba5 then.

2026-02-10 10:39 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +multiple other byte sequences associated with spaces in Unicode.
No longer needed after reducing the size of the shortcode grammar.

2026-02-10 14:05 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +having too many bytes in the shortcode field.
I've noted explicitly that clients SHOULD enforce this grammar when managing packs in 06ca1859.

However there are two sides to this on the client side:

- Creating/modifying/viewing packs (addressed above)
- Viewing emotes/stickers in the timeline.

I'd like to suggest clients fail to render images in the latter case as well (to prevent images with invalid shortcodes becoming widespread). However, if we ever shrank the grammar in the future, such a restriction would cause clients to fail to render historical images. But I'm not not convinced such a change is realistic?

2026-02-12 04:57 UTC, AndrewRyanChama commented
I believe that GTA 7 will be released first.  Perhaps even Half Life 3.

2026-02-24 09:54 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
Should the spec suggest moving(?) the event on calls to the room upgrade API?

2026-02-25 11:36 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
Yes, that's a good addition, thanks! I've added it in 0c731cb4.

2026-02-25 12:15 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
Are you saying this should happen for the upgrading user or also for any other users "subscribing" to an upgraded pack? It seems somewhat reasonable for homeservers to handle this automatically for any pack. I suppose the "normal" mechanics would be for a user to receive a room upgrade notification, go through the usual room upgrade process, during which the client recognises that this room is in the list of this user's globally subscribed packs and updates the reference as it joins the new room?

2026-02-25 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
Should this be renamed to `m.room.image_pack` to fit in with all other room-level state events?

2026-02-25 15:46 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
I would expect the homeserver to upgrade a user's account data upon joining the new room, yes.

That would probably rely on the new room pointing to the old via a `predecessor` field.

2026-02-26 15:30 UTC, syrm commented
Are you planning to support the [lottie](https://lottie.github.io/) format for stickers?
It allows for very lightweight stickers.

2026-02-26 15:41 UTC, tulir commented on proposals/2545-emotes.md
@syrm said outside of a thread:

> Are you planning to support the [lottie](https://lottie.github.io/) format for stickers?
It allows for very lightweight stickers.

2026-02-26 15:42 UTC, tulir commented on proposals/2545-emotes.md
`m.sticker` is already in the spec and image formats in general are out of scope for this MSC. This is just defining how packs are shared, not what the packs contain.

Another MSC could be opened to define that `video/lottie+json` is something clients should support in `m.sticker`

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This is to prevent a
now that the grammar is limited to ascii, it's hardly important, but bytes are still kinda the wrong unit for measuring strings.


```suggestion
A shortcode's length MUST NOT exceed 100 characters. This is to prevent a
```

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +because searching for, and indexing, such shortcodes is complicated.
For the record: I wondered for a while if we could just use the [Opaque identifier grammar](https://spec.matrix.org/v1.17/appendices/#opaque-identifiers) here (the only differences being (a) that would allow `~` and `.`; (b) it would allow identifiers up to 255 chars).

On reflection though, that's probably not appropriate, because:
 * The Opaque identifier grammar is explicitly for "non-user-visible identifiers", which this is not
 * I think I saw somewhere that this is the same charset as used by Slack (and Discord?), which is compelling. You should maybe write down this rationale.

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +being included (e.g. ブイチューバー). This is guard against various edge cases of
I mean, it excludes pretty much every language other than English, but fine

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +being included (e.g. ブイチューバー). This is guard against various edge cases of
```suggestion
being included (e.g. ブイチューバー). This is to guard against various edge cases of
```

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +These restrictions MUST be enforced by servers on the Client-Server API, but MUST
Could you flesh this out a bit? What does "enforced by servers on the Client-Server API" mean in practice? Does this only affect sending `m.image_pack` events, or are there others?

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +over federation). This avoids a split-brain in the room. Servers MAY opt to
I don't think that enforcing what is sent over the C-S API helps prevent split-brains?

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +These restrictions MUST be enforced by servers on the Client-Server API, but MUST
I'm still unconvinced that servers MUST enforce this, given clients have to handle malformed events anyway.  I think this introduces a confusing inconsistency in the way events are validated.

2026-03-03 20:06 UTC, richvdh commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
> I would expect the homeserver to upgrade a user's account data upon joining the new room, yes.

If you want this to happen, better make it explicit.

2026-03-03 20:09 UTC, kevincox commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This is to prevent a
I think bytes are better. "characters" is an ill-defined concept. Do we mean unicode code-units? grapheme cluster? Also unicode definitions change over time. The most reasonable option is to limit the UTF-8 byes and the clients can decide what characters are.

2026-03-03 20:21 UTC, richvdh commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This is to prevent a
Eh maybe you're right. https://github.com/matrix-org/matrix-spec/issues/1001 moved in the direction of `bytes`.

The question is, of course, entirely moot given the allowed character set.

2026-03-03 20:22 UTC, richvdh commented on proposals/2545-emotes.md
> +A shortcode's length MUST not exceed 100 bytes. This is to prevent a
```suggestion
A shortcode's length MUST NOT exceed 100 bytes. This is to prevent a
```

2026-03-04 14:22 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +because searching for, and indexing, such shortcodes is complicated.
Yes! I mentioned it [here](https://github.com/matrix-org/matrix-spec-proposals/pull/2545#discussion_r2746060891). Good point on communicating that in the doc as well. I've now done so in 49e26791.

2026-03-04 14:22 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
@richvdh are you suggesting converting the SHOULD to a MUST? Or adding a RECOMMEND for homeserver implementations to update each user's account data upon upgraded room join?

2026-03-04 14:22 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +#### `m.image_pack` state event
I've heard no arguments against, so I've gone ahead and done so in 8cf32fcf.

2026-03-04 14:22 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +These restrictions MUST be enforced by servers on the Client-Server API, but MUST
I suppose since homeservers don't actually pull any fields out of these events, nor do anything other than deliver them to clients, there's no real risk associated with split-brains.

I've softened this in d8fedcd6, and encouraged the usual caution for clients when dealing with malformed events.

2026-03-04 14:22 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +over federation). This avoids a split-brain in the room. Servers MAY opt to
Ah, I was implying that not enforcing the rules _over federation_ avoids split-brain scenarios. This has also been updated in https://github.com/matrix-org/matrix-spec-proposals/commit/d8fedcd67892b9d115d08810ffc114d3bcfbdbd0.

2026-03-04 14:22 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +being included (e.g. ブイチューバー). This is guard against various edge cases of
Updated in 9a5ab4c1.

2026-03-11 10:18 UTC, richvdh commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
I think I'm slightly confused about what you are expecting to happen when.

The text of the MSC as currently written seems to imply that the only change needed to account data is during the actual upgrade process, but your comments here suggest that the server needs to walk the upgrade history every time someone joins a room.

I'm mostly asking you to spell out the operations a bit more explicitly.

2026-03-11 17:37 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
I've added an implementation strategy in db4f57b39c03ec7eeecadcf646e181fec447b675. Is that clearer?

2026-03-11 23:12 UTC, tulir commented
All old threads seem to be mostly resolved and the rest of the checklist is complete too:

@mscbot resolve checklist incomplete

2026-03-11 23:13 UTC, tulir commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
IMO the whole section should be moved to a new MSC to avoid getting this one blocked on needs-implementation for another few years

2026-03-11 23:29 UTC, tulir commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
@mscbot concern missing server implementation for room upgrades

(to be resolved if/when it's moved to a new MSC)

2026-03-12 16:17 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
This has been split out to https://github.com/matrix-org/matrix-spec-proposals/pull/4433.

Pointer added in 17b36f4a.

2026-03-12 16:18 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +to the new room. Homeservers SHOULD also update user's account data so that any
@mscbot resolve missing server implementation for room upgrades

2026-03-24 00:59 UTC, clokep commented on proposals/2545-emotes.md
> +A suggestion for clients of image pack ordering is as follows:
Should this just be a SHOULD in the spec instead of “a suggestion” which will be lost in th spec PR?

2026-03-24 17:40 UTC, richvdh approved these changes

2026-03-25 03:02 UTC, uhoreg commented on proposals/2545-emotes.md
> +delivered to them by the homeserver. Clients SHOULD to try and show emotes and
```suggestion
delivered to them by the homeserver. Clients SHOULD try and show emotes and
```

2026-03-25 03:02 UTC, uhoreg commented on proposals/2545-emotes.md
> +Clients implementing this MSC are expected to override the height when rendering
"are expected to" = "SHOULD" ?

2026-03-25 03:06 UTC, uhoreg commented on proposals/2545-emotes.md
> +    [`ImageInfo`](https://spec.matrix.org/v1.14/client-server-api/#msticker_imageinfo)
```suggestion
    [`ImageInfo`](https://spec.matrix.org/v1.18/client-server-api/#msticker_imageinfo) 
```

when 1.18 is released, to include the `is_animated` property

2026-03-27 16:57 UTC, anoadragon453 commented
As the last three SCT reviews were either approvals or quite minor, I think it's finally time to call FCP on this MSC!

@mscbot fcp merge

Edit: It's been so long since we called FCP that I had forgotten it was still ongoing.

Well, consider this the point where I think this MSC is now _finally_ ready to go :)

2026-03-27 18:00 UTC, anoadragon453 commented
For those that have implemented an earlier version of this MSC, here is a summary of the changes in recent months:

- The image-level `usage` field has removed from the `m.image_pack` room state event. The pack-level `usage` field remains.
- The `m.image_pack` account data entry has been removed in favour of using the `m.image_pack.rooms` account data entry to point to `m.image_pack` room state events, which are less limited.
- `m.image_pack.rooms` **state event** has been removed due to lack of real-world usage.
- The shortcode grammar has now been properly defined. Take a look at what characters are now allowed in shortcodes (and the new length limit).
- New client implementation recommendations have been added.
- **Apr 28, 2026:** an empty dictionary under a room in `m.image_pack.rooms` no longer means "all image packs in the room", but instead has no special meaning (clients can ignore it). This was due to no clients implementing UX for the former definition. Changed in https://github.com/matrix-org/matrix-spec-proposals/pull/2545/changes/1220db34e2a60e5ab94cababdfd5a757a51b6181.

In either case, if you've not read this proposal in a long while, I recommend reading through it again entirely as much has changed. Thanks!

2026-03-27 18:33 UTC, tulir commented on proposals/2545-emotes.md
> +1. User image pack (defined in the user's account data)
This doesn't seem to exist anymore

2026-03-27 18:38 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +1. User image pack (defined in the user's account data)
Fixed in https://github.com/matrix-org/matrix-spec-proposals/pull/2545/commits/775e3dd62e27b406ec52f71cd737131fa6d0201a.

2026-03-27 18:44 UTC, tulir commented on proposals/2545-emotes.md
> +      "usage": ["sticker"]
Image-specific usage was removed

```suggestion
      "url": "mxc://example.org/sticker"
```

2026-04-07 15:37 UTC, dbkr commented on proposals/2545-emotes.md
> +    "images": {
I feel like this question must have been asked already but I'm not sure I can wade through the 583 comments to find out: I'm not sure why images is separate and everything else lives under a "pack" object?

2026-04-07 16:13 UTC, dbkr commented on proposals/2545-emotes.md
> +can be added to a `m.image_pack.rooms` account data event.
This just talks about the room ID which isn't what the section below says.

2026-04-07 16:35 UTC, dbkr commented on proposals/2545-emotes.md
> +listing the (potentially many) packs a room may have.
I'm not really convinced about this. I think we need to think about what the UI would look like for this because it feels super complex for probably not a great saving in event size: how many image packs is a room likely to have, and if it does have lots, are you likely to want all of them?

2026-04-07 19:58 UTC, HarHarLinks commented on proposals/2545-emotes.md
> +listing the (potentially many) packs a room may have.
You might consider it a feature that this would automatically subscribe to any additional packs added to a room, much like you are subscribing to any images added to a pack. The latter is implied above ("a future MSC could define only certain images to be sourced from a pack, instead of the entire pack.") but perhaps could be stated outright.

2026-04-21 10:12 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +    "images": {
The structure was determined long ago by the original author (in https://github.com/matrix-org/matrix-spec-proposals/pull/2545/changes/96f28647ca72c22d5bd9851448634417882df768, before `short` was renamed to `images`.

Thus I don't know why it was originally chosen, but the separate is fairly clear. `images` is the image-level information, while `pack` is the metadata about the pack as a whole. I'll write this into the MSC.

2026-04-21 10:13 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +    "images": {
But as a client developer, do you have a justification for why it might be better to structure the object a different way?

2026-04-21 10:31 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +can be added to a `m.image_pack.rooms` account data event.
Good catch, thanks! Fixed in 4c16abd5.

2026-04-21 11:43 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +listing the (potentially many) packs a room may have.
One use case I can think of are absolutely huge emote packs, like the popular "Ponymotes" which many people still use to this day. To give you an idea of the size: https://github.com/anoadragon453/friendica-ponymotes-addon/tree/master/ponymotes/emotes (~17,500 emotes). This pack isn't developed any more (afaik), but imagine if it was.

If I was porting this into Matrix, I'd probably break the pack up into category rooms (say 2000 emotes per category, with 4-5 image packs in each room, as the event size limit [restricts the size of an image pack to ~400 emotes](https://github.com/Sorunome/matrix-doc/blob/soru/emotes/proposals/2545-emotes.md#event-size-limits). This would produce about 9 Matrix rooms to cover all of the different categories.

If a user wants to use a particular category in other rooms, they could go into their setting, select all the packs in that room, and enable them globally. Ideally they'd have a "Select All" button to do so.

Yet if new emojis continue to be added, then eventually I, as the pack manager, would need to add another image pack to one of the category rooms. Without the ability for users to "subscribe" to all packs in a room, I'd have to `@room` everyone and make them go into their settings to add the additional pack each time. The subscribing mechanism eliminates that extra busywork.

---

UI-wise, I took a look at what Cinny does. It appears to not support subscribing to all packs in a room currently:

<img width="1631" height="1881" alt="image" src="https://github.com/user-attachments/assets/21dd53c7-8a92-4b4a-88b2-25b6fb214576" />

Neither does FluffyChat (which only allows enabling all or no packs in the room, and does so individually):

<img width="3164" height="1991" alt="image" src="https://github.com/user-attachments/assets/0488fac9-4bb7-4a6b-85c7-a41247b73675" />

---

If I were designing this, I would expect to see a list of packs for a room, a Select All button to make it easy to select/deselect all packs, and finally a toggle (Subscribe?) to mean "Subscribe to all and any future packs in this room". When toggled on, all pack-specific toggles would grey out to indicate that the room itself is subscribed to.

When the "Subscribe" button is hovered over, a tooltip stating "Any new room packs added to the room will immediately be available globally" could help get the point across.

---

So I think that this needs some design consideration on the client side. But I don't don't think it's worth blocking the MSC over. The functionality seems useful to keep in, and we can see how/whether it's used in practice.

2026-04-22 09:09 UTC, dbkr commented on proposals/2545-emotes.md
> +    "images": {
Fair enough, I don't really have any concrete reason why another structure would be better, it just seemed... a bit weird, which is probably not sufficient justification for changing things now it's got to this stage.

2026-04-22 09:21 UTC, dbkr commented on proposals/2545-emotes.md
> +listing the (potentially many) packs a room may have.
Honestly the fact that two implementations of this MSC don't implement this feature feels fairly telling to me, and arguably means those don't really count as implementations of the MSC either. I'd rather split this out to a separate MSC so it can go through the, "will clients actually implement it" test on its own merit. The use case for very large image packs kinda feels like working around technical size limitations ought to be transparent to the user rather than them having to check a separate box and feels like we need to (dare I say it) choose a fundamentally different approach if supporting image packs this large is a requirement.

2026-04-28 09:59 UTC, anoadragon453 commented on proposals/2545-emotes.md
> +listing the (potentially many) packs a room may have.
Given that no clients (that I'm aware of) have implemented it, I'm happy to punt it to a future MSC to get this one through, yeah.

Done in 1220db34

2026-04-28 12:09 UTC, KitsuneRal commented on proposals/2545-emotes.md
> +    "attribution": "drawn by @kayley:example.org"
Personally I think it's worth exploring whether a [full-fledged `spdx` dictionary](https://spdx.github.io/spdx-spec/v3.0.1/serializations) would provide better structure and extensibility for attribution but that deserves a separate MSC, so I'm just leaving it as a note here.

2026-05-03 13:51 UTC, SkyePrism commented
10 days till the 6 year anniversary :eyes: excited for the merge!

2026-05-04 15:19 UTC, merged

2026-06-02 14:06 UTC, Cknight70 commented
Will a new pr for element mention this thread (and show up in this feed) or is there a better place to keep track of this?

2026-06-02 14:51 UTC, turt2live commented
Element's support is likely to be tracked amongst the Element issue trackers. There's still process work which needs to be done here before the MSC is actually in the spec, which might affect when/how Element decides to implement it.

If someone were to write up the spec PR, that would help things along.

2026-06-10 16:02 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/2397

2026-06-25 13:36 UTC, catfromplan9 commented
Is there no stable equivalent to `im.ponies.user_emotes`?

2026-07-01 20:14 UTC, turt2live commented
Merged 🎉

2026-07-07 09:58 UTC, anoadragon453 commented
> Is there no stable equivalent to `im.ponies.user_emotes`?

Indeed. It's mentioned in the [comment that explains the differences between historical unstable implementations and today's spec](https://github.com/matrix-org/matrix-spec-proposals/pull/2545#issuecomment-4144315200).

Since GitHub likes to collapse large PR comment threads, I've linked that comment now from the PR description.

2026-07-07 10:13 UTC, catfromplan9 commented
> > Is there no stable equivalent to `im.ponies.user_emotes`?
> 
> Indeed. It's mentioned in the [comment that explains the differences between historical unstable implementations and today's spec](https://github.com/matrix-org/matrix-spec-proposals/pull/2545#issuecomment-4144315200).
> 
> Since GitHub likes to collapse large PR comment threads, I've linked that comment now from the PR description.

Bummer, it's really convenient to be able to easily store a couple stickers/emoticons without making a room for it. Oh well, I've implemented it in my client with the legacy `im.ponies.user_emotes`, I suppose that works

2026-07-07 11:52 UTC, anoadragon453 commented
> Bummer, it's really convenient to be able to easily store a couple stickers/emoticons without making a room for it. Oh well, I've implemented it in my client with the legacy `im.ponies.user_emotes`, I suppose that works

The justification is in https://github.com/matrix-org/matrix-spec-proposals/pull/2545#discussion_r2637952407.