MSC0000: Helping others with mandatory implementation guides
matrix-org/matrix-doc pull request #2618
Opened 2020-06-09 17:26 UTC by turt2live

[Rendered](TBD)

2020-06-11 15:01 UTC, anoadragon453 requested changes
Great overall! I'm really looking forward to the clarity this may bring :)

Just a couple questions below.

2020-06-11 15:01 UTC, anoadragon453 commented on proposals/2618-implementation-guide-requirement.md
> +implemented and be prepared to document any common questions they receive as considerations.
Is this true even if the MSC has already been merged?

2020-06-11 15:42 UTC, turt2live commented on proposals/2618-implementation-guide-requirement.md
> +it would be greatly appreciated if the redundancy was present for the sake of clarity.
ish, yea. Basically if your MSC is "We should mandate that all text is purple" the implementation considerations should say "All text is now purple".

2020-06-11 15:43 UTC, turt2live commented on proposals/2618-implementation-guide-requirement.md
> +implemented and be prepared to document any common questions they receive as considerations.
merged or landed? If it's merged then we have a problem.

2020-06-11 15:53 UTC, anoadragon453 commented on proposals/2618-implementation-guide-requirement.md
> +it would be greatly appreciated if the redundancy was present for the sake of clarity.
Ahh, I see. This paragraph means redundancy between what you wrote and the implementation guide. I thought it was referring to redundancy with existing content in the implementation guide/other MSCs.

2020-06-11 15:54 UTC, anoadragon453 commented on proposals/2618-implementation-guide-requirement.md
> +implemented and be prepared to document any common questions they receive as considerations.
I'm actually not sure what the difference is between "merged" and "landed".

I mean the MSC itself has been merged into the `proposals/` folder, a spec PR could still be absent.

2020-06-11 16:24 UTC, turt2live commented on proposals/2618-implementation-guide-requirement.md
> +implemented and be prepared to document any common questions they receive as considerations.
That is landed. Merged is a specific status for when a spec PR has been accepted and a spec release performed.

2020-06-11 16:34 UTC, anoadragon453 commented on proposals/2618-implementation-guide-requirement.md
> +implemented and be prepared to document any common questions they receive as considerations.
Ahhh, ok, I see what you're saying now.

So... is this true even when an MSC has landed? :) I guessing suppose this is true and someone's responsibility up until the MSC is merged.

2020-06-11 16:36 UTC, turt2live commented on proposals/2618-implementation-guide-requirement.md
> +implemented and be prepared to document any common questions they receive as considerations.
Yup. It's no different than the requirement to keep the MSC updated with changes.

2020-06-11 17:17 UTC, anoadragon453 commented on proposals/2618-implementation-guide-requirement.md
> +implemented and be prepared to document any common questions they receive as considerations.
Cool. I think this point and the other one could use some light clarification in the document? Otherwise the rest of it looks good to me.

2020-06-14 14:50 UTC, KitsuneRal requested changes
Generally LGTM, except I think we should keep the spec as the cornerstone authority.

2020-06-14 14:50 UTC, KitsuneRal commented on proposals/2618-implementation-guide-requirement.md
> +should fix that.
Shouldn't The Spec be the source of truth, with the guide giving in in case of contradictions (although, if those happen, we still should fix them)?

2020-06-14 14:50 UTC, KitsuneRal commented on proposals/2618-implementation-guide-requirement.md
> +We sit in sadness for lack of documentation, leading to frustrated developers and abandoned implementations.
On a more serious note, the alternative could be to continue filling the spec documents with implementation advices. The downside of that is described in the introduction, as this is business as usual to some extent.

2020-06-14 17:10 UTC, turt2live commented on proposals/2618-implementation-guide-requirement.md
> +should fix that.
This is mostly acknowledging the risk of us failing to realize when the spec and guides differ in any ways, and that the mitigation is the common sense answer of fixing it.

2020-06-15 09:58 UTC, KitsuneRal commented on proposals/2618-implementation-guide-requirement.md
> +should fix that.
I just don't want to give an impression that we don't assume the spec to be the ultimate source of truth, using anything else (implementation guides, Synapse/Riot implementation, common sense) as a possibly "equally authoritative" or even "better" reference point for implementers. But yeah, the second sentence says exactly that we should fix such situation if it emerges.

2026-05-14 18:00 UTC, turt2live commented
In practice we've placed more requirements on MSCs as they approach FCP instead of needing implementation guides, so I'm closing this.

2026-05-14 18:00 UTC, closed without merging