[WIP] MSCXXXX: Unread counts
matrix-org/matrix-doc pull request #2654
Opened 2020-06-24 09:26 UTC by babolivier

2020-06-24 09:36 UTC, richvdh commented
(to replace #2625)

2020-06-30 15:35 UTC, richvdh submitted a review, later dismissed
looks good to me.

I think we also need a proposal for how to specify that certain rooms should be excluded from the badge count in `/_matrix/push/v1/notify`.

2020-06-30 15:35 UTC, richvdh commented on proposals/2654-unread-counts.md
> +* include a `msgtype` parameter in its content which value is `m.notice`.
per https://docs.google.com/document/d/1pjYrGokTQGDZQLtagZvG4dY67RsjUdFDfpOzSiWtOBg/edit?disco=AAAAJvIgsqM: probably needs to check the event type too.

2020-06-30 15:35 UTC, richvdh commented on proposals/2654-unread-counts.md
> +information to clients. However, when it comes to unread messages, it doesn't
> it doesn't provide a count

what is "it" in this sentence?

I think it would be clearer to reverse this sentence:

> However, no count is provided for unread messages.

2020-06-30 15:35 UTC, richvdh commented on proposals/2654-unread-counts.md
> +[MSC2625](https://github.com/matrix-org/matrix-doc/pull/2625) which doesn't use
it kinda reads like you're saying that MSC2625 doesn't use push rules. A comma helps a bit:

```suggestion
[MSC2625](https://github.com/matrix-org/matrix-doc/pull/2625), which doesn't use
```

2020-06-30 16:26 UTC, babolivier commented
> I think we also need a proposal for how to specify that certain rooms should be excluded from the badge count in /_matrix/push/v1/notify.

I assume you mean a separate MSC rather than an addition to this MSC?

2020-06-30 16:59 UTC, richvdh commented
> I assume you mean a separate MSC rather than an addition to this MSC?

well no, I rather think it ought to be part of this one. See also https://docs.google.com/document/d/1pjYrGokTQGDZQLtagZvG4dY67RsjUdFDfpOzSiWtOBg/edit#

2020-07-01 04:11 UTC, turt2live submitted a review, later dismissed
Overall this feels fine, though some rationale for the decisions would be appreciated.

2020-07-01 04:11 UTC, turt2live commented on proposals/2654-unread-counts.md
> +of the parameter is a count of every unread event since that user joined it.
A read receipt should always be present as we implicitly have a read receipt for the user's last sent event. We apparently haven't gotten around to specifying that though: https://github.com/matrix-org/matrix-doc/issues/569

2020-07-01 04:11 UTC, turt2live commented on proposals/2654-unread-counts.md
> +* include a non-empty `body` parameter in its content
do we care if it's not a string?

2020-07-01 04:11 UTC, turt2live commented on proposals/2654-unread-counts.md
> +    * `m.room.name`
why name and not avatar? why not pinned events? why these 3 specifically?

2020-07-01 04:11 UTC, turt2live commented on proposals/2654-unread-counts.md
> +## Potential issues
This MSC can result in a count mismatch for clients: notifications could say 12 notified messages but the server says 3 unread messages. Which one is the client to prefer/believe?

2020-07-01 04:11 UTC, turt2live commented on proposals/2654-unread-counts.md
> +* be an encrypted message (i.e. have the `m.room.encrypted` type)
Should the client re-execute these rules itself like they do for push rules once the event is decrypted?

2020-07-01 08:58 UTC, babolivier commented on proposals/2654-unread-counts.md
> +of the parameter is a count of every unread event since that user joined it.
While implementing that MSC, I realised that wasn't the case (at least Synapse doesn't store one in this case). As you said, it is currently not a specified behaviour, so I believe this mention belongs in the MSC.

2020-07-01 10:29 UTC, ara4n commented on proposals/2654-unread-counts.md
> +    * `m.room.name`
i suspect we should have `m.room.avatar` too, it was an oversight.

pinned events aren't new messages (unlike a new avatar, or a new name), so i don't think they should count.

The distinction i had in mind were things which tell the user that new first-class information has been added to the room (i.e. name, topic, avatar, new access rules, etc) as opposed to other random state.  But agreed it's quite fuzzy and subjective.  I also forget where this list came from originally, but I'm not sure I was intending it to be exhaustive.

2020-07-01 10:42 UTC, richvdh commented on proposals/2654-unread-counts.md
> +* include a non-empty `body` parameter in its content
I vote: "Yes". if we're checking it's non-empty, we should check it's a string too.

2020-07-01 10:43 UTC, richvdh commented on proposals/2654-unread-counts.md
> +    * `m.room.name`
@babolivier can we add `m.room.avatar` here?

2020-07-01 10:45 UTC, richvdh commented on proposals/2654-unread-counts.md
> +## Potential issues
if it has access to the full /sync data, it should probably use that. the `notifications` update is to keep the badge count up-to-date on clients that aren't syncing.

2020-07-01 10:45 UTC, richvdh commented
thanks for the detailed review and helping to spot the edge-cases we forgot, @turt2live !

2020-07-01 10:46 UTC, babolivier commented on proposals/2654-unread-counts.md
> +    * `m.room.name`
Yes, I'm planning on updating this MSC to answer review comments later today.

2020-07-02 12:44 UTC, Cadair commented on proposals/2654-unread-counts.md
> +    * `m.room.name`
Power levels feels like a weird inclusion to me. Unlike the other properties of the room (name, topic etc) it's unlikely to be new information for me to read / process most of the time. Also do PL changes cause a room to be shown with new events in most clients at the moment (using mentions only push rules etc)?

2020-07-11 13:08 UTC, tulir commented on proposals/2654-unread-counts.md
> +    * `m.room.avatar`
Why `m.room.power_levels` and why not `m.room.pinned_events` and `m.room.tombstone`?

2020-07-11 13:08 UTC, tulir commented on proposals/2654-unread-counts.md
> +  in [MSC1849](https://github.com/matrix-org/matrix-doc/pull/1849).
```suggestion
  in [MSC2676](https://github.com/matrix-org/matrix-doc/pull/2676).
```

2020-07-11 13:08 UTC, tulir commented on proposals/2654-unread-counts.md
> +unclear whether this MSC can be merged before MSC1849.
```suggestion
[MSC2676](https://github.com/matrix-org/matrix-doc/pull/2676). Therefore, it is
unclear whether this MSC can be merged before MSC2676.
```

2020-07-29 14:38 UTC, richvdh commented on proposals/2654-unread-counts.md
> +    * `m.room.avatar`
(and removing `m.room.power_levels`)

2020-07-29 14:40 UTC, babolivier commented on proposals/2654-unread-counts.md
> +    * `m.room.avatar`
ftr pinned events have already been discussed here: https://github.com/matrix-org/matrix-doc/pull/2654#discussion_r448270153

2020-10-19 23:28 UTC, cloudrac3r commented on proposals/2654-unread-counts.md
> +* be an encrypted message (i.e. have the `m.room.encrypted` type)
Did you find out the answer?

2021-08-04 06:46 UTC, KitsuneRal approved these changes
This looks quite useful to me: specifying the way events are counted would help clients and homeservers to do it in a uniform way (and actually, Quotient devised event counting logic that served exactly this purpose but used an inferior algorithm). I have a couple of nitpicks below; but I think this is generally good to go.

2021-08-04 06:46 UTC, KitsuneRal commented on proposals/2654-unread-counts.md
> +  parameter in its content which value is `m.notice`.
What if an `m.notice` event _has_ `state_key`? Officially that would make it a (spec-incompliant) state event; and since it's not matching any type from the list above, it's not icluded in the unread count anyway. Seems like "no `state_key`" condition is superfluous here.

2021-08-04 06:46 UTC, KitsuneRal commented on proposals/2654-unread-counts.md
> +of the parameter is a count of every unread event since that user joined it.
Considering the case when the user joined, left, and joined again, all without ever reading the timeline. Should the number of unread messages be counted from the first or from the latest join?

2021-08-04 07:16 UTC, KitsuneRal requested changes
After studying further the current logic in matrix-react-sdk, there might be a couple more things worth adding to the criteria.

2021-08-04 07:16 UTC, KitsuneRal commented on proposals/2654-unread-counts.md
> +  parameter in its content which value is `m.notice`.
In addition to `m.notice`, it's worth excluding `m.key.verification.*` messages (this can only be done on the client side, of course).

2021-08-04 07:16 UTC, KitsuneRal commented on proposals/2654-unread-counts.md
> +    * `m.room.tombstone`
https://github.com/matrix-org/matrix-react-sdk/blob/84af29a7f1a5e4d4a8f3408f0f741293f10be010/src/components/views/rooms/EventTile.tsx#L1186 (as called from https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Unread.ts#L32) has another interesting addition - it counts an event as unread if it's `m.room.create` with non-empty `predecessor`. To be honest, I don't quite understand the rationale behind that and am just documenting the case.

2022-03-30 16:42 UTC, zecakeh commented on proposals/2654-unread-counts.md
> +of the parameter is a count of every unread event since that user joined it.
Since there are no implicit read receipts, shouldn't that be the number of unread messages since the last event sent by the user, or something like that?

2022-06-08 14:08 UTC, erikjohnston commented
What's the status of this? There is currently code in Synapse to make this work that is on the hot path, and we should rip it out if we're not going to finish this any time soon.

2022-06-08 14:12 UTC, babolivier commented
> What's the status of this? There is currently code in Synapse to make this work that is on the hot path, and we should rip it out if we're not going to finish this any time soon.

I think the next steps are addressing the concerns in threads and asking for FCP to be proposed. I'm unlikely to get bandwidth to do that anytime soon though.

2022-06-08 14:14 UTC, erikjohnston commented
Is this actually being driven by something? If it's not a feature that people are asking for then I'm not sure there's much point finishing it?

2022-06-08 14:20 UTC, babolivier commented
> Is this actually being driven by something? If it's not a feature that people are asking for then I'm not sure there's much point finishing it?

It was driven by the notification rework that was underway at the time, but isn't anymore. I have occasionally seen people use this feature, but rarely and I believe this is a pretty niche feature, so I don't mind if we decide to abandon it.

2022-06-11 15:06 UTC, KitsuneRal commented
Upcoming libQuotient 0.7 also has it implemented (driving my feedback here).

2022-09-01 14:30 UTC, richvdh commented on proposals/2654-unread-counts.md
> +unclear whether this MSC can be merged before MSC2676.
MSC2676 is now merged.

2022-09-01 14:32 UTC, richvdh commented
I don't think it's reasonable to keep this "experimental" code in synapse's mainline indefinitely; we either need to commit to speccing it properly, or to removing it. 

It's worth noting that enabling the option in Synapse has a substantial performance impact, so making it part of the spec would require us to find a solution to that.

Given that the author of this MSC has said that he is no longer interested in pursuing it, I think that it will need a volunteer to take it on; otherwise it is likely to be closed as "abandoned".

So, any volunteers to address the comments and think about how to solve the performance problems?

2022-09-01 18:01 UTC, KitsuneRal commented
I'm willing to take this over - is there a write-up of the performance issues somewhere?

2022-09-01 18:19 UTC, clokep commented
> I'm willing to take this over - is there a write-up of the performance issues somewhere?

Not really, no. matrix-org/synapse#13694 is the PR of interest. Happy to chat over there (or we can file a separate issue on Synapse referencing that if you'd like).

2023-11-26 21:56 UTC, tezlm commented on proposals/2654-unread-counts.md
> +[`/sync`](https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-sync)
Did you mean `unread_notifications.unread_count`?

2024-08-08 20:31 UTC, Sec32fun32 approved these changes

2025-11-25 01:27 UTC, bretthowell714-source commented on proposals/2654-unread-counts.md
> +[MSC2625](https://github.com/matrix-org/matrix-doc/pull/2625), which doesn't use
Thanks

2026-07-20 20:02 UTC, babolivier commented
Heads up I am formally abandoning this proposal since I don't currently have time for Matrix spec contributions (I'm not sure whether I should close it or wait for someone to adopt it).

2026-07-20 20:14 UTC, turt2live commented
Generally we close abandoned MSCs - I'll do so now to the ones with the above comment.

2026-07-20 20:14 UTC, closed without merging