MSC2664 Get rooms in common with another user
matrix-org/matrix-doc pull request #2666
Opened 2020-07-05 12:31 UTC by Half-Shot

2020-07-05 12:38 UTC, Sorunome commented on proposals/2666-get-rooms-in-common.md
> +[
Shouldn't the reply be

```json
{
  "rooms": [
    "!blah",
    "!blubb",
  ]
}
```
As so far *no* endpoint in the spec returns an array, only objects?

2020-07-05 12:38 UTC, Sorunome commented on proposals/2666-get-rooms-in-common.md
> +The response format will be an array containing all rooms where both the `user_id` and `other_user_id` have
It should be required that one of the user IDs is your own user ID, thus also requiring authentication via access token

2020-07-05 12:39 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +[
Yeah, agreed. I was lazy here.

2020-07-05 12:40 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +The response format will be an array containing all rooms where both the `user_id` and `other_user_id` have
It would probably make most sense to require `user_id` to be your own user ID

2020-07-05 12:41 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +The response format will be an array containing all rooms where both the `user_id` and `other_user_id` have
I was riffing off what we do for account_data. My thought process was as follows:

- Seems a shame to add a new root `/shared_rooms` path, I wonder if I can use `/rooms`.
- Hm, no. `/rooms` is for fetching data about a single room. How about `/users`
- Oh, but all `/users` calls expect the owners user_id.

So in the end I could either break the `/users` convention, write a new path, or use the existing convention. I went with C, but I am happy to hear arguments otherwise.

2020-07-05 12:42 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +The response format will be an array containing all rooms where both the `user_id` and `other_user_id` have
> It would probably make most sense to require `user_id` to be your own user ID

That's what I am doing in the code, perhaps I need to spell it out :P

2020-07-05 12:51 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
Wouldn't it also be useful to return rooms which you both participated in, in the past, but the other user was banned/kicked. So instead of returning a list of rooms you both joined, the endpoint could return multiple lists, one for each membership state

2020-07-05 12:51 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +The response format will be an array containing all rooms where both the `user_id` and `other_user_id` have
In conduit I fully ignore the user id in the path and always use the user id from the access token. Is that okay?

2020-07-05 13:01 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +The response format will be an array containing all rooms where both the `user_id` and `other_user_id` have
In practise that's fine. It's a bit of a spec wart that we have the user_id in the path, because the spec does not allow for it to differ from the access_token.

2020-07-05 13:05 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
In theory we could stick a ?membership=[types] on the end of this endpoint, which is a comma separated list of allowed membership states for the remote user. I guess we could even do it for the current user too, however I'm unsure how useful this is.

2020-07-05 13:13 UTC, Sorunome commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
This unfortunately leaks information (and thus soru is strongly in favour *not* to do it):

Suppose alice and bob shared a room at once point, but alice left. Via that endpoint she can then keep querying the room if bob is still in there.

2020-07-05 13:17 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
@Sorunome I meant room where alice is joined, but bob has a different membership state. In the UI it would show all rooms alice joined and bob has *any* membership event in, with some text saying which one it is.

2020-07-05 13:18 UTC, Sorunome commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
Aaaah, that would be ok, as in, that wouldn't leak information, thanks for clarification!

2020-07-05 13:18 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
Another idea is to also show the power level, sothe Ui can say that a user is moderator, admin or muted in some room

2020-07-05 13:19 UTC, Sorunome commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
That would also require fetching power level events for a given room, not only search `m.room.member`, and thus would (greatly?) increase complexity on the server side for little gain?

2020-07-05 13:26 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
I don't think getting two events of the current state is expensive, but maybe in synapse's architecture it is. Idk

2020-07-05 13:47 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
I think it's important to keep this MSC scoped in order to improve it's chances of ~~not getting bikeshedded~~ keeping the implementation easy for *all* homeservers.

I'm going to consciously prioritise the use case of showing a simple list of rooms that you are both in, and clients can populate their UI with any state they have for the room.

2020-07-05 14:49 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
Perhaps you can rename the `rooms` field to `join` then, so it's easy to add to it in the future?

2020-07-05 15:08 UTC, uhoreg commented on proposals/2666-get-rooms-in-common.md
> +modern clients often implement "lazy-loadeding", so they often only have state for a subset of all rooms
```suggestion
modern clients often implement "lazy-loading", so they often only have a subset of state for the rooms
```

2020-07-05 15:08 UTC, uhoreg commented on proposals/2666-get-rooms-in-common.md
> +the authenticated users MxID and the user that is being searched for.
```suggestion
the authenticated user's MxID and the user that is being searched for.
```

2020-07-06 11:11 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`. If either user is not joined to any rooms, or the `other_user_id` does not exist, an
What happens if current_user == other_user ?

2020-07-06 11:20 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`. If either user is not joined to any rooms, or the `other_user_id` does not exist, an
Good point. In my opinion it's an invalid request, as you can just called /joinedRooms for the same result except that path can optimise for the current user.

2020-07-06 11:35 UTC, tulir approved these changes

2020-07-06 13:06 UTC, auscompgeek commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`. If either user is not joined to any rooms, or the `other_user_id` does not exist, an
So something like this?

Servers may reject the request, with [some appropriate error code], if `other_user_id` is the same as `current_user`.  Clients should use /joinedRooms to determine what rooms the current user has joined instead.

2020-07-06 14:32 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`. If either user is not joined to any rooms, or the `other_user_id` does not exist, an
It's a tossup between consistency and being too strict. I am minded to be lean on a strong requirement to reject, because doing this has no purpose since another endpoint exists.

2020-07-06 16:12 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
Yep, I think that's a fair compromise.

2020-07-10 11:09 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +GET _matrix/client/unstable/uk.half-shot.msc2666/users/@alice:example.com/shared_rooms/@bob:example.com
@anoadragon453 asks if we should continue to use the /users/{user_id}/.../{other_user_id}/ format given we don't allow you to do it on behalf of other users. This was probably intended as a way for appservices to puppet their accounts a long time ago before as_user became the way to do things like this

2020-07-10 11:10 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +GET _matrix/client/unstable/uk.half-shot.msc2666/users/@alice:example.com/shared_rooms/@bob:example.com
IMO, I'm fine with dropping this OR we could decide that homeservers can decide whether to allow other user_ids so that admins can spy on their users?

2020-07-10 11:12 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +GET _matrix/client/unstable/uk.half-shot.msc2666/users/@alice:example.com/shared_rooms/@bob:example.com
I was thinking about this functionality, but I can't really visualize how this would be useful in client UI.

I could see something that would allow you to see what rooms an arbitrary number of users share though? That's probably out of scope here though.

Admins can also usually just go and have a poke in the DB as well.

2020-07-10 11:14 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +GET _matrix/client/unstable/uk.half-shot.msc2666/users/@alice:example.com/shared_rooms/@bob:example.com
Yeah, I think at best this would be convenience but frankly it means every client now needs to paste in their user_id in order to call the api. That sucks. Let's drop it.

2020-07-10 15:00 UTC, uhoreg commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/users/{current_user}/shared_rooms/{other_user_id}` which will take
Why `/users/` rather than `/user/` as other existing endpoints use?

2020-07-10 15:21 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/users/{current_user}/shared_rooms/{other_user_id}` which will take
Seems to be a typo in the MSC, it's implemented as `/user/`

2020-07-10 15:21 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +GET _matrix/client/unstable/uk.half-shot.msc2666/users/@alice:example.com/shared_rooms/@bob:example.com
Isn't the MSC supposed to use the actual endpoint and not vendor-prefixed ones?

2020-07-10 17:22 UTC, timokoesters commented on proposals/2666-get-rooms-in-common.md
> +GET _matrix/client/unstable/uk.half-shot.msc2666/users/@alice:example.com/shared_rooms/@bob:example.com
I'm for dropping as well. Maybe even replace existing endpoints with non-userid paths (or support both for a while)

2020-07-20 21:17 UTC, turt2live requested changes
Overall this doesn't feel like it needs to be an endpoint.

2020-07-20 21:17 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +as well as include lots of extranious information.
This does not feel like a compelling reason to add an endpoint to the spec. Low bandwidth and mobile clients should be using more restrictive filters to limit their exposure to information, and if a client isn't using a local store for checking this then they've really messed up how this feature could work. Clients which would want this feature would have already cached state locally.

2020-07-20 21:36 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +as well as include lots of extranious information.
I don't really get your point. Do you mean there should be some non-standalone-endpoint way to get the information without loading all room state?

The only way for this to work without any API changes is if clients either stop lazy loading or request the member lists for *all* rooms at the same time. What's wrong with wanting this feature and lazy loading at the same time?

2020-07-20 21:41 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +as well as include lots of extranious information.
Lazy-loading is a much stronger justification than the words here.

2020-07-20 22:24 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +as well as include lots of extranious information.
Lazy-loading is mentioned [here](https://github.com/matrix-org/matrix-doc/pull/2666/files/db99583ce577582f6bfe4b28d6ecfa7b1bf54590#diff-366ea8b6ee99e7bf4f9501ae6e9ac376R13-R15) and it was meant to be taken in mind when reading the rest of the MSC, but I'll make a point of including it in this section too.

2020-07-20 22:28 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +a membership of type `join`.
I've gone with "joined" to line up with things like https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-rooms-roomid-joined-members, but otherwise it's been included.

2020-07-20 22:29 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/users/{current_user}/shared_rooms/{other_user_id}` which will take
fixed

2020-07-31 13:46 UTC, Half-Shot commented
Synapse and matrix-js-sdk have been updated to match the latest version of the spec.

2020-08-18 17:24 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +
Could you specify some expected error codes here please? Such as the code when trying to request shared rooms with yourself.

2020-08-18 17:24 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +The /versions endpoint MUST include a new key in `unstable_features` with the name `uk.half-shot.msc2666`.
Just checking that you're stating that `uk.half-shot.msc2666` has to be present, but could either be `true` or `false` to indicate that this homeserver supports this feature.

2020-08-18 17:24 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +GET _matrix/client/r0/user/shared_rooms/@bob:example.com
```suggestion
GET /_matrix/client/r0/user/shared_rooms/%40bob%3Aexample.com
```

2020-08-18 17:32 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +
I think there is only one error situation likely to occur, which is the one you mentioned. Users who do not exist will return an empty list, as will invalid user_ids.

2020-08-18 17:36 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +
I probably would've said `M_INVALID_PARAM`, but I don't think it matters much.

2020-08-18 17:37 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +The /versions endpoint MUST include a new key in `unstable_features` with the name `uk.half-shot.msc2666`.
Have spelt it out, but yes.

2020-08-20 20:29 UTC, timokoesters commented
One can implement this very efficiently if one already stores a sorted list of joined roomids for both users, because then you can go through both lists at the same time resulting in linear time complexity

2020-08-24 10:49 UTC, anoadragon453 commented
> One can implement this very efficiently if one already stores a sorted list of joined roomids for both users, because then you can go through both lists at the same time resulting in linear time complexity

Nice tip! One to go in the [homeserver implementation book](https://spec.matrix.org/books/server/) (once it's fleshed out a bit...).

2020-08-28 15:28 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +The response error for trying to get shared rooms with yourself will be an HTTP code 400, with `M_FORBIDDEN` as the `errcode`.
Should this be an HTTP `403` since it's `M_FORBIDDEN`?

2020-09-01 10:21 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +The response error for trying to get shared rooms with yourself will be an HTTP code 400, with `M_FORBIDDEN` as the `errcode`.
Doesn't have to be. [403](https://httpstatuses.com/403) "The server understood the request but refuses to authorize it." would imply an authentication failure which would leave clients confused because they are using correct authentication information.

[400](https://httpstatuses.com/400) "The server cannot or will not process the request due to something that is perceived to be a client error" which would be correct here, since the request cannot be processed due to incorrect parameters. The request is still FORBIDDEN, but not due to authentication. This is the closest approximation I could find in the spec. `M_INVALID_PARAM` would have worked, but the spec implies that this is due to incorrect typing which isn't the case here.

I think this is fine.

2020-09-01 10:34 UTC, ptman commented on proposals/2666-get-rooms-in-common.md
> +The response error for trying to get shared rooms with yourself will be an HTTP code 400, with `M_FORBIDDEN` as the `errcode`.
I've used 422 Unprocessable Entity in some of my own projects.

2020-09-01 10:37 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +The response error for trying to get shared rooms with yourself will be an HTTP code 400, with `M_FORBIDDEN` as the `errcode`.
422 would actually make the most sense, but I couldn't find any usage of it in Synapse/TheSpec so I assumed it was unpopular (as 410+ error codes often are..)

2020-09-02 12:20 UTC, Half-Shot commented
Heads up that the Synapse PR has landed as an unstable feature now.

2021-08-22 13:36 UTC, ShadowJonathan commented
Blocked on https://github.com/matrix-org/synapse/issues/10339

2021-08-28 15:50 UTC, kevincox approved these changes

2021-08-28 15:58 UTC, kevincox commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/user/shared_rooms/{user_id}` which will take
Nit: `shared_rooms` could be taken to mean either "rooms I have shared with this user" or "rooms that I share with this user". It is probably better to call this `common_rooms`. (Although that may be confused for common as in popular, but that doesn't make sense when passing another user ID).

2021-08-28 15:58 UTC, kevincox commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
Does it make sense to extend the search API with member constraints?

This would be more generic and be able to specify multiple usersto include? This may be helpful for finding old rooms (I remember that I was walking with Alice and Bob about this but can't find the room).

There is a bit of a mismatch because right now because IIUC the search API always returns messages however I can also imagine this filter being useful for message searches. (Ex: messages containing "pizza" in a room that contains Alice and Bob.) Extending the Search API with a `result_type: room` option and adding support for a `member` constraint would add both of these features and provide an obvious way to add more constraints on "Find common rooms" in the future.

2021-08-28 16:12 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
The `/search` API seems to already have query and result categories (`room_events` being the only currently defined one). It also already supports sender constraints, but that doesn't directly help with room search.

2021-08-28 17:49 UTC, kevincox commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
That sounds good. So we could add the `rooms` category and add `member` constrains. I agree that `sender` is different than `member`.

Although this does raise fallback questions. If we say that `member` can be used for `room_events` is it required? Or can the server ignore it. But is a server allowed to ignore it for `rooms`? If it does ignore it it makes it useless for the use case described by this MSC.

2021-12-15 12:57 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/user/shared_rooms/{user_id}` which will take
I kinda agree, we could probably rename it to "mutual_rooms", just like discord has "mutual friends/servers".

2021-12-15 12:57 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
While i think these are good ideas, they kinda fall out of scope of this MSC, the search api needs better tuning in general, and i don't think that bolting something like this onto it is a good idea for now. We should probably revisit this bit when we overhaul the search API in a more broader sense.

2021-12-19 00:05 UTC, kevincox commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/user/shared_rooms/{user_id}` which will take
I think that name is quite clear.

2021-12-20 09:41 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
+1 I'd rather not encumber the search API with more things when it's already not fit for purpose, and would rather we wrote a MSC specifically to alter how search works separately.

2021-12-20 12:40 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/user/shared_rooms/{user_id}` which will take
Mutual sounds good to me, and probably the most clearest one.

2022-03-19 16:10 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +GET /_matrix/client/r0/user/mutual_rooms/%40bob%3Aexample.com
There should probably be a way to refuse service to this endpoint with no data, see https://github.com/matrix-org/synapse/pull/12038#discussion_r819599640

I suggest responding with a 404 as a known general failure condition, in addition to "user not found".

2022-04-02 15:26 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +# MSC 2666: Get rooms in common with another user
@ spec scribe;

I've added an implementation which updates the JS SDK code to use the new naming; https://github.com/matrix-org/matrix-js-sdk/pull/2271

2022-04-12 08:48 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +The /versions endpoint MUST include a new key in `unstable_features` with the name `uk.half-shot.msc2666`.
```suggestion
The /versions endpoint MUST include a new key in `unstable_features` with the name `uk.half-shot.msc2666.mutual_rooms`.
```

See [this implementation review comment](https://github.com/matrix-org/matrix-js-sdk/pull/2271#discussion_r841389852), considering we now have two endpoints for one unstable MSC, we should differentiate the two as well.

2022-04-12 09:42 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +The /versions endpoint MUST include a new key in `unstable_features` with the name `uk.half-shot.msc2666`.
Ah, I see. Yes, this seems valid if we've changed the endpoint between versions.

2022-04-12 22:41 UTC, anoadragon453 reviewed
Other than working through the minor case in https://github.com/matrix-org/matrix-spec-proposals/pull/2666#discussion_r830500133 and the below nits, I think this MSC is ready for FCP.

What say you @Half-Shot?

2022-04-12 22:41 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +Once the MSC has been merged, clients should use `/_matrix/client/r0/user/mutual_rooms/{user_id}`
```suggestion
Once the MSC has been merged, clients should use `/_matrix/client/v1/user/mutual_rooms/{user_id}`
```

2022-04-12 22:41 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +GET /_matrix/client/r0/user/mutual_rooms/%40bob%3Aexample.com
```suggestion
GET /_matrix/client/v1/user/mutual_rooms/%40bob%3Aexample.com
```

To follow the new per-endpoint versioning scheme.

2022-05-03 16:14 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +signalling its unwillingess (or inability) to satisfy the request.
this is a very uncommon thing to do in the spec. All endpoints are currently required to be implemented (unless bundled into a module the server doesn't care about), so this endpoint should never fall into "unwillingness" or "inability". 

If we do want to do this, please provide justification in the MSC.

2022-05-03 16:52 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +signalling its unwillingess (or inability) to satisfy the request.
I'm conflicted on this requirement myself also, I'm starting to think that the arbitrary requirement from Synapse - where this is implemented via the optionally-ran user directory - would not be enough to restrict this MSC to have to include this.

I will take another look at the Synapse implementation, see if it can be implemented in a way that makes this section redundant.

2022-05-03 20:05 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +signalling its unwillingess (or inability) to satisfy the request.
Conveniently, the Synapse implementation is what drove this thread being opened. Implementation-specific restrictions are not supposed to be carried into the protocol (but cases where many/all implementations have issues would be considered).

For this case, the Synapse side is kinda stuck at "figure it out" rather than having the spec concede.

2022-05-22 15:56 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +signalling its unwillingess (or inability) to satisfy the request.
https://github.com/matrix-org/synapse/pull/12836 pushed a change to synapse, I'll keep this open until that has been resolved.

2022-05-30 09:09 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +signalling its unwillingess (or inability) to satisfy the request.
This has been resolved on both fronts now.

2022-05-30 09:54 UTC, Half-Shot commented
Hi there, I'm delegating this PR to @ShadowJonathan as I lack time to complete it.

2022-05-30 09:54 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +signalling its unwillingess (or inability) to satisfy the request.
https://github.com/matrix-org/matrix-spec-proposals/pull/3822 has also been made to address the proposal-text-side of things.

2022-05-31 20:59 UTC, ShadowJonathan commented
I hereby sign all my comments on this branch, preceding and following, with;

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

2022-05-31 20:59 UTC, turt2live commented
The author/shepherd, @ShadowJonathan, believes this MSC is ready for FCP.

2022-08-02 15:50 UTC, anoadragon453 reviewed
From the PR description:

> matrix-react-sdk PR: https://github.com/matrix-org/matrix-react-sdk/pull/4897

It looks like this PR was never merged. I think it's useful to leave it for historical purposes, but could you indicate that this PR was closed?

Otherwise this is looking positive overall, and I think just mainly need some more client implementation work to push it over the edge (the js-sdk PR is a good start, but I'd be interested in seeing how a client implements UI for this, especially with respect to different room types).

2022-08-02 15:50 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
Off the back of the above conversation, are there any use cases for allowing clients to hand multiple user IDs to this API, that act as an AND condition to search mutual rooms with?

All I can think of is the use case that @kevincox mentioned above, where you're trying to find a room given some known participants - which actually sounds like a pretty cool feature. We would need to reshape this API to use query parameters instead of path parameters or similar though. Do others think that may be worthwhile, or can think of other use cases?

It's also perfectly valid to just assume that specific use case will be handled by a more featureful room search API.

2022-08-02 15:50 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +Once the MSC has been merged, clients should use `/_matrix/client/v1/user/mutual_rooms/{user_id}`
```suggestion
Once the MSC has been merged, and the homeserver has advertised support for the Matrix version that this endpoint is included in, clients should use `/_matrix/client/v1/user/mutual_rooms/{user_id}`
```

2022-08-02 15:50 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +an empty array should be returned.
With room types now merged to the spec, should we add a query parameter to constrain the results by type of room? I could see this being useful for:

1. Being able to show a separate list of "Mutual Spaces" and "Mutual rooms".
1. Hiding rooms from the results that shouldn't be shown in clients (i.e. profile rooms).

I also recognise that the client could probably do local filtering, but I'm not sure how different that would be to implement.

2022-08-02 19:22 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
I think that at this point, it's too much of a diversion from what has already settled in over the course of this MSC's development; personally, i'd like to see that in a new endpoint, or in that room search api you mentioned.

(FWIW, the above is talking about a message search API as well, i'm mentioning this to make sure you're not confusing the above two.)

2022-08-02 19:24 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +an empty array should be returned.
Personally, I'd like this to be implemented in the Room Search API you alluded to [here](https://github.com/matrix-org/matrix-spec-proposals/pull/2666#discussion_r935730582), in a seperate MSC, rather than tacking it onto this one.

I think going forward, local filtering and matching could better address this usecase than not, I think going forward with this MSC as-is is a better option than to wait a longer while for a more fruitful Room Search API.

2022-08-02 19:30 UTC, ShadowJonathan commented
> the js-sdk PR is a good start, but I'd be interested in seeing how a client implements UI for this, especially with respect to different room types

Element's progression is tracked [here](https://github.com/vector-im/element-meta/issues/371) and [here](https://github.com/vector-im/element-web/issues/14339), seeing as they were the original driver of this MSC, i requested the design team if they could pick this up in their new team structure.

Seeing as it is available in js-sdk, cinny.in could implement this themselves (tracked in https://github.com/cinnyapp/cinny/issues/710)

2022-08-03 10:09 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
I appreciate that this MSC has been open for a while, but I'm not sure if it's _actually_ near-complete. We've yet to reach proposed FCP or have any implementation in use other than [a trivially mutable function](https://github.com/matrix-org/matrix-js-sdk/pull/1417/files#diff-627fe08d8bba6a4fa76e7c5ed36ef6f16d126733e65e19236b391de0d34f1fe0R4852-R4864) written for it. I don't think potentially major changes to the MSC at this point are off the table?

I know that extending this MSC's lifecycle isn't ideal, but I do want to make sure we have a maintainable API.

My current thoughts are:

* If we *do* end up wanting this functionality (**which is not yet clear!**) then we'd be painting ourselves into a corner with the current shape.
* The convention of putting user IDs in path parameters was originally intended to allow AS' to insert puppeted Matrix User ID. But that ended up being scrapped for [the `user_id` query parameter](https://spec.matrix.org/v1.3/application-service-api/#identity-assertion). As a result, ideally we'd remove about half of the instances of user IDs in path parameters; thus it may not be the best precedence to adhere to.

> (FWIW, the above is talking about a message search API as well, i'm mentioning this to make sure you're not confusing the above two.)

Ah indeed it is talking about message search. My comment probably should have been its own thread.

2022-08-20 15:28 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +Once the MSC has been merged, clients should use `/_matrix/client/v1/user/mutual_rooms/{user_id}`
👍

@Half-Shot Could you add this?

2022-08-21 14:16 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
We discussed in DMs what the best way forward for this MSC would be, and we came to the conclusions;
- To swap the path parameter to a query parameter.
- To have such an endpoint implicitly include the self-user in the search.
- A possible moderation use-case for this can best be addressed in an admin api.
- If, in the future, a use case comes along where more-than-one users have to be queried, then this endpoint can be easily edited by another MSC, and clients will have to version-check if the server supports multiple users with the query part.

2022-08-23 04:17 UTC, turt2live reviewed
drive-by review. Sorry, it's incomplete but should be enough to cover some concerns.

2022-08-23 04:17 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/_matrix/client/v1/user/mutual_rooms/{user_id}` which will take
```suggestion
Homeservers implement a new endpoint `/_matrix/client/v1/user/mutual_rooms/{user_id}` which will take
```

"should" implies it's optional when it's not :P

2022-08-23 04:17 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/_matrix/client/v1/user/mutual_rooms/{user_id}` which will take
can it be rate limited?

2022-08-23 04:17 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +and /search may be complimentary.
something we've been moving away from is pulling large chunks of data out of the server - a question to consider is if this endpoint needs pagination, or if it's unlikely to be a problem. 

Server-side folks probably have a stronger opinion on this than I.

2022-08-23 04:17 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +    "!OGEhHVWSdvArJzumhm:matrix.org",
Should we be returning stripped state for these rooms too? (or do we plan to do something similar in a future release? if so, making this an object with an empty object as the value would give extensibility).

2022-08-23 10:17 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/_matrix/client/v1/user/mutual_rooms/{user_id}` which will take
Yes, that should be added. 👍

2022-08-23 10:22 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +and /search may be complimentary.
I feel like this is not particularly "large", it's going to be a subset of rooms the user is in, and only then, just their IDs, which would be a string that's reasonably usually around 16 characters.

Even if the user would share around 100 rooms with the other person (a result on the high end, in my opinion), with 16 characters average, it'd only be around ~1.8kb to share (taking into account quotes and commas), which would still be less than a random average (synapse) sync response of around 2KB, and only double of its empty sync response (of ~700B).

Even if the numbers start to rise (beyond 1000 shared rooms), I don't think this'll ever get into the Megabyte territory of responses, and thus require pagination.

Thoughts?

2022-08-23 10:25 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +    "!OGEhHVWSdvArJzumhm:matrix.org",
The idea of this endpoint is that it just gives pointers to rooms for an existing "spun-up" client, one which already would have information about these rooms.

However, I don't know the full details of sync v3, and how it'll handle this, will it effectively hide rooms "under the fold", including any and all detail?

If so, then I personally think there's indeed merit in making this future-proof (and thus making it a mapping to empty objects).

However still, if this is going to be the case, I have to think about pagination, which complicates this endpoint a lot. (See your previous comment and my response)

2022-08-23 14:39 UTC, erikjohnston commented on proposals/2666-get-rooms-in-common.md
> +and /search may be complimentary.
I'd quite like us to move to a world where every endpoint that responds with a variable amount of data is paginated, for a few reasons:

1. it's much less faff for clients if the endpoints start off being paginated compared with introducing pagination later;
2. if everything is paginated and follow a similar structure then its just easier for clients and servers to deal with; and
3. even if the common case only returns a small amount of data, the mere potential that a client *can* cause lots of data to be returned makes it hard to run Synapse in a resource constrained way.

Also, if we end up extending the API to include stripped state then the size of the response can easily balloon.

2022-08-23 14:42 UTC, erikjohnston commented on proposals/2666-get-rooms-in-common.md
> +accessible. Homeservers that have implemented [POST /user_directory/search](https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3user_directorysearch)
I think the performance impact will be OK if this endpoint is used "infrequently", i.e. like for the use cases described in the intro.

Basically: the query requires looking up the list of rooms for each user and doing the intersection, which is not cheap, but is also not particularly expensive.

2023-02-01 15:05 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +accessible. Homeservers that have implemented [POST /user_directory/search](https://spec.matrix.org/v1.3/client-server-api/#post_matrixclientv3user_directorysearch)
Yeah, in Element's case, I expect this endpoint to be hit in a few cases;
- Explicitly opening a detail profile view (e.g. clicking on a profile in the sidebar in cinny in element).
- Upon viewing invites (to cross-reference where the person is known from).
- When viewing a minimal DM, where the header ("This is your conversation with X") is visible.

I don't expect it to be pre-loaded en-masse, or loaded en-masse in general.

2023-02-01 15:05 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +Once the MSC has been merged, clients should use `/_matrix/client/v1/user/mutual_rooms/{user_id}`
/res this has been added in https://github.com/matrix-org/matrix-spec-proposals/pull/3913

2023-02-01 15:05 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +signalling its unwillingess (or inability) to satisfy the request.
/res this has been added in https://github.com/matrix-org/matrix-spec-proposals/pull/3913

2023-02-01 15:06 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +## Alternatives
/res this has been added in https://github.com/matrix-org/matrix-spec-proposals/pull/3913

2023-02-01 15:06 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/_matrix/client/v1/user/mutual_rooms/{user_id}` which will take
/res this has been added in https://github.com/matrix-org/matrix-spec-proposals/pull/3913

2023-02-01 15:07 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +Homeservers should implement a new endpoint `/_matrix/client/v1/user/mutual_rooms/{user_id}` which will take
/res this has been added in https://github.com/matrix-org/matrix-spec-proposals/pull/3913

2023-02-01 15:09 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +and /search may be complimentary.
/res this has been added in https://github.com/matrix-org/matrix-spec-proposals/pull/3913

We didn't need to specify the order the rooms are returned in, but allow the server to specify the ordering itself, and simply return an opaque token to get the next batch of rooms

this'd allow it to define an ordering itself, with any kind of optimisation strategy

2023-02-01 15:19 UTC, ShadowJonathan commented
Checkpoint for myself, and as a general note of progress:

With the changes introduced by #3913, the JS SDK and Synapse implementation are no longer valid, and need to be updated.

The following has to be implemented:
- The change from `/mutual_rooms/{user_id}` to `/mutual_rooms?user_id={user_id}`
- The addition of `next_batch_token` (and logic)
- Unstable flag now being `uk.half-shot.msc2666.query_mutual_rooms` (instead of `<...>.mutual_rooms`)

---

- [ ] Update the JS SDK to reflect this: #TBD
- [ ] Update Synapse to reflect this: #TBD
- [ ] Update Ruma to reflect this: #TBD

2023-02-07 05:38 UTC, turt2live commented
@ShadowJonathan given the status you posted, I'm removing this from the SCT's board for now. When it's (likely) ready for FCP again, please raise it in the [SCT Office](https://matrix.to/#/#sct-office:matrix.org) and we'll add it back.

2023-05-18 15:07 UTC, clokep commented on proposals/2666-get-rooms-in-common.md
> +`"next_batch_token"` can be inserted, which the client has to pass to `batch_token` in the query
The synapse implementation seems to return a particular error for unknown batch tokens?

2023-05-18 16:03 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +`"next_batch_token"` can be inserted, which the client has to pass to `batch_token` in the query
...and merged, this thread can be resolved.

2023-05-19 09:37 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +- `uk.half-shot.msc2666.mutual_rooms`
🐑 Small addition, as I forgot this a few times prior:

```suggestion
- `uk.half-shot.msc2666.mutual_rooms`
- `uk.half-shot.msc2666`
```

2023-06-05 10:30 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<any valid ascii string up to 32 chars>"
I'm just now realising that this might cause problems, and we should restrict this to just `[a-zA-Z0-9]` to prevent issues with url encoding.

No implementation (right now) generates a batch token, so if the below suggestion is accepted, no implementations would have to be altered.

```suggestion
  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
```

2023-06-05 10:32 UTC, anoadragon453 commented
In my opinion, it would be nice to see an implementation of this MSC in a client before acceptance, just to ensure that the proposed spec is enough for a client to implement a decent UI. Such an implementation can simply exist on a fork of a codebase.

2023-06-05 10:35 UTC, tulir commented
The original Element Web implementation still works fine, I have it in my fork here: https://github.com/maunium/matrix-react-sdk/tree/tulir/shared-rooms

2023-06-05 10:35 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
Other spots in the spec call a similar field `next_batch` instead of `next_batch_token`. It seems confusing to deviate?

* https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3search
* https://spec.matrix.org/v1.7/client-server-api/#pagination
* https://spec.matrix.org/v1.7/client-server-api/#get_matrixclientv1roomsroomidthreads
* etc

2023-06-05 10:41 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
Apologies, I wasn't aware of the naming convention.

According to this, its both `next_batch` in the response, and `next_batch` in the query request.

I could update, but that would be a bunch more churn. If you like to see me do it, just say it.

2023-06-05 11:03 UTC, Mikaela commented
This is also implemented in Nheko unless there are multiple competing ways of displaying shared rooms.

2023-06-05 11:08 UTC, ShadowJonathan commented
@Mikaela There are, i recommend taking a look at the [latest JS SDK](https://github.com/matrix-org/matrix-js-sdk/pull/3381) commit to see how it handles the MSC's history, and how it approaches calling the unstable endpoint.

When it lands as stable, this could be removed and only the latest endpoint be required, but since i wanted to not remove perfectly-working backwards-compatible MSC changes (only cosmetic ones, like changing a path to a query, or changing the endpoint name itself), i implemented it anyways.

2023-06-05 11:12 UTC, ShadowJonathan commented
<details>
<summary>A general comment about my feelings for the usefulness of this MSC, and how it developed</summary>

When I began shepherding this MSC, I was anxious that it would be eventually rejected because sync would provide all the necessary details for a user to know which rooms a user would be in, but after this MSC aged (like fine cheese), and other developments came to light, or i realised other things, i realise that this endpoint does have merit.

Right now, in today's sync, we have lazy-loading members, which would already remove the guarantee that the client knows all users at any time. However, with sliding sync (if i'm not mistaken), we will also narrow that viewpoint even more, where the client doesnt even need to know about the existence of "older" rooms, like this.

As such, having an endpoint that definitively grabs a user's mutual rooms, would still hold up, and be useful in an age where matrix clients can opt into even-more-sparse synchronisation, to keep this as a feature that helps along privacy security, and helps a user judge abuse when they're invited out of the blue, and many more use cases.

</details>

2023-06-05 12:33 UTC, kevincox commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<any valid ascii string up to 32 chars>"
It may be convenient to also include `-_` so that data can be URL-safe base64 encoded. This provides a bit of an escape hatch for encoding arbitrary data. This way 24 binary bytes can be encoded into the token. The token should of course be considered opaque to the client still.

2023-06-05 12:41 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
Per [this comment](https://github.com/matrix-org/matrix-spec-proposals/pull/2666#discussion_r1218010122)

```suggestion
  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9_-]+/>"
```

2023-06-05 17:00 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
Implementations will need to update to remove unstable prefixes anyways, so why not do a parameter rename at the same time?

The implementations don't need to have the exact names to be considered proven and unblock FCP.

2023-06-05 23:24 UTC, turt2live approved these changes
overall, the MSC seems like a sensible way forward. A couple FCP-blocking concerns:

* Stuff to do with pagination
* Text/discussion around supporting multiple `user_id` params

2023-06-05 23:24 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +matched against.
If `user_id` can't be specified multiple times, it might belong in the HTTP path instead. Also, can it be specified multiple times?

2023-06-05 23:24 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +This endpoint can be rate limited.
boilerplate:
```suggestion
This endpoint can be rate limited and requires authentication.
```

2023-06-05 23:24 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +continue until the server does no longer insert `"next_batch_token"`.
Somewhere we need the words "this batch_token is only valid for use with this endpoint", and the semantics for expiration (does the homeserver need to remember the batch token forever?)

2023-06-05 23:24 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
Pagination is also specified as https://spec.matrix.org/v1.7/appendices/#pagination ftr

2023-06-05 23:24 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
can we just use https://github.com/matrix-org/matrix-spec-proposals/blob/rav/proposals/id_grammar/proposals/1597-id-grammar.md#opaque-ids please?

Ideally by name: "a batch_token is an opaque identifier, currently capable of containing the characters [0-9a-zA-Z._~-], must be at most 255 characters, and non-empty"

2023-06-05 23:24 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +matched against.
ah, it's listed later in the MSC. Is there a technical reason preventing multiple users from being searched? It feels like an awkward thing to make a future MSC for when we're already here.

2023-06-05 23:24 UTC, turt2live commented on proposals/2666-get-rooms-in-common.md
> +longer need to check for the `unstable_features` flag.
```suggestion
Once this MSC is considered stable, implementations can use the stable endpoint instead.
```

It may also be worth reading https://github.com/matrix-org/matrix-spec-proposals/pull/4024 to match the language there, as this seems like the sort of feature a client would want to use between FCP completing and spec release.

2023-06-05 23:24 UTC, turt2live commented
@mscbot fcp merge

2023-06-05 23:26 UTC, turt2live commented
@mscbot concern Pagination should match appendices
@mscbot concern Discussion around searching for multiple user IDs, and text to formalize the conclusion there

2023-06-06 06:08 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +matched against.
The discussion context is here: https://github.com/matrix-org/matrix-spec-proposals/pull/2666#discussion_r936483418

2023-06-06 06:11 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +matched against.
There is no technical reason preventing multiple users for being searched, but I don't see a convincing client usecase, while I agreed to keep the path open for one if the time came, to make it easily extendible.

2023-06-06 09:29 UTC, richvdh commented on proposals/2666-get-rooms-in-common.md
> +matched against.
I think if we're *not* putting the user id in the path, then we shouldn't use the `/_matrix/client/v1/user` hierarchy, since most of the endpoints under that hierarchy do have a user_id as the next path component.

2023-06-06 09:56 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +matched against.
I'm also realising that if we want to be able to get rooms in common with more users, there could just be another version of this endpoint.

2023-06-06 09:57 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +continue until the server does no longer insert `"next_batch_token"`.
I think an expiration time of 10 minutes could be reasonable here.

2023-06-06 10:18 UTC, richvdh commented on proposals/2666-get-rooms-in-common.md
> +GET /_matrix/client/v1/user/mutual_rooms/?user_id=%40bob%3Aexample.com
this example includes a trailing `/`, which is inconsistent with the definition above.

In general Matrix does not allow extra `/`s in endpoints.

2023-06-06 10:19 UTC, richvdh commented on proposals/2666-get-rooms-in-common.md
> +rooms with the authenticated user, an empty array should be returned.
is the behaviour on invalid user IDs left as an implementation decision? (I think that's fine if so, but best to say so explicitly)

2023-06-06 10:25 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +GET /_matrix/client/v1/user/mutual_rooms/?user_id=%40bob%3Aexample.com
Ah, that's an error from a previous change that moved path-element parameters to query parameters.

2023-06-06 10:26 UTC, richvdh commented on proposals/2666-get-rooms-in-common.md
> +`M_INVALID_PARAM` as the `errcode`.
Not a strong opinion here, but 422 is pretty obscure (and we don't use it anywhere else in matrix, afaik).

The *idea* in Matrix is that we shouldn't rely too heavily on HTTP response codes, to make it easier (one day) to move to alternative transports. So if we need to distinguish this from other error cases, we'd do that via a custom `errcode` rather than HTTP response code.

2023-06-06 10:26 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +rooms with the authenticated user, an empty array should be returned.
IIRC that would fall under some `400` `Bad Request` semantics, implementation-specific, yeah.

2023-06-06 10:29 UTC, richvdh reviewed
Generally seems good to me but there are a few things I'd like to see resolved before FCP

2023-06-06 10:31 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +longer need to check for the `unstable_features` flag.
Ah, I think with this original language I remember/wrote this down to "consider stable" to be "when it is included in a spec version"

Together with richvdh's comment [here](https://github.com/matrix-org/matrix-spec-proposals/pull/4024#discussion_r1219377897), i think that for this MSC it is unnecessary to introduce a `.stable` `unstable_features` flag.

2023-06-09 13:27 UTC, KitsuneRal commented on proposals/2666-get-rooms-in-common.md
> +`M_INVALID_PARAM` as the `errcode`.
Ftr, [CoAP](https://www.rfc-editor.org/rfc/rfc7252#section-5.9) doesn't have code 4.22 or anything semantically similar to HTTP's 422, and there don't seem to be subsequent RFCs addressing that (while 429, e.g., has got is CoAP equivalent in a [later RFC](https://datatracker.ietf.org/doc/html/rfc8516)).

2023-06-09 13:34 UTC, KitsuneRal commented on proposals/2666-get-rooms-in-common.md
> +matched against.
With the current MSC text, this seems to be resolved?

2023-06-15 21:44 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +`M_INVALID_PARAM` as the `errcode`.
Doing this sounds like programmer error vs. something that would actually need to be explicitly handled in practice. So this could just be a `400` / `M_UNKNOWN` - "you cannot request rooms in common with yourself".

2023-06-15 21:53 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +continue until the server does no longer insert `"next_batch_token"`.
In which case we should specify an error case for clients supplying an unknown / expired batch token, so that they can retry.

We can't use `M_UNKNOWN_TOKEN` - as this error would also be returned if the user used an unknown access/refresh token to access this endpoint.

We may need to define a new `errcode` - perhaps `M_UNKNOWN_PAGINATION_TOKEN`?

2023-07-04 03:21 UTC, turt2live commented
It appears as though the author(s) aren't currently able to take this on - cancelling FCP pending the MSC being [re-raised to the SCT](https://matrix.to/#/#sct-office:matrix.org)

@mscbot fcp cancel

2023-07-13 09:53 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
Thanks, I was looking for something like that, will add it 👍

2023-07-13 10:10 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
/res #4035

2023-07-13 10:10 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +  "next_batch_token": "<a string up to 32 characters abiding by the regex /[a-zA-Z0-9]+/>"
/res #4035

2023-07-13 10:10 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +This endpoint can be rate limited.
/res #4035

2023-07-13 10:12 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +continue until the server does no longer insert `"next_batch_token"`.
#4035

I have added the 10 minute timer, and added text that it will handle expired tokens the same as invalid tokens, so that implementations may forget those tokens entirely. Do you think this is a good method?

Then the clients' default response to "invalid token" is just to start over, without any token.

The only problem i see is that clients may loop on a broken implementation, where it is not passing the right token back to the server will cause it to get stuck in its mechanism where it continually retries.

2023-07-13 10:13 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +longer need to check for the `unstable_features` flag.
/res

2023-07-13 10:15 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +matched against.
I want some clear direction on this. The current version (that I merge in this branch via #4035) changes some labels around enough that i'd have to give it another unstable_features tag.

I haven't yet, as i want to sweep the result of this in that tag, before i propose it FCP again.

---

Should I change this back to a path component, or should I keep this as a query element endpoint? I can do either.

2023-07-13 10:16 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +`M_INVALID_PARAM` as the `errcode`.
I've changed the error to 400 + M_UNKNOWN

/res #4035

2023-07-13 10:22 UTC, ShadowJonathan commented
<details>
<summary>Current Status</summary>

With #4035, I have applied a lot of changes that will need a new unstable_features tag. However, I want [this discussion](https://github.com/matrix-org/matrix-spec-proposals/pull/2666#discussion_r1262342461) to be resolved first before I go ahead and do that.

After that, implementations need to be updated to match, and only then will I request FCP again.

</details>

2023-07-13 10:22 UTC, ShadowJonathan commented on proposals/2666-get-rooms-in-common.md
> +GET /_matrix/client/v1/user/mutual_rooms/?user_id=%40bob%3Aexample.com
/res https://github.com/matrix-org/matrix-spec-proposals/pull/4035

2023-07-13 13:23 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +continue until the server does no longer insert `"next_batch_token"`.
I would just leave the validity period up to the implementation, but *recommend* at least 10 minutes. Clients should be prepared to handle tokens that do have a ridiculously short window though.

I would also recommend clients limit the maximum number of retries before giving up, precisely to prevent infinite loops as you describe.

2025-09-01 14:15 UTC, Half-Shot commented
Hello 5 years later :wave: 

https://github.com/element-hq/element-web/pull/30654 is an implementation that finally uses this information, so could be used as an example of an implementation.

2025-09-01 14:43 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +longer need to check for the `unstable_features` flag.
Sounds like this is resolved.

2025-09-01 14:49 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +matched against.
This seems to be the stalling factor in this MSC now, and it seems like a fairly trivial matter of just:

 - Drop `/user/`, path becomes `_matrix/client/v1/mutual_rooms`
 - Keep the query parameter, leave the door open to allowing multiple in the future if the need arises.

If everyone is happy with that, we can make the change and re-request FCP.

2025-09-01 14:53 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +matched against.
`/v1/mutual_rooms` rather than /v3, but yeah that sounds good to me. No need to define a new unstable prefix either, just change the stable one

2025-09-01 15:11 UTC, Half-Shot commented on proposals/2666-get-rooms-in-common.md
> +matched against.
Done. And agreed, I don't think it's worth putting in another unstable prefix at this late stage.

2025-12-04 23:22 UTC, tulir commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

MSC authors: feel free to ask *in a thread* on your MSC or in the [#matrix-spec:matrix.org](https://matrix.to/#/#matrix-spec:matrix.org) room for clarification of any of these points.

- [x] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal) specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example, modifying the set of redacted fields changes how event IDs are calculated, thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with [the appendices](https://spec.matrix.org/latest/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved. Ideally, the first paragraph should be understandable by a non-technical audience.
- [x] All outstanding threads are resolved
  - [x] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present, the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](https://github.com/matrix-org/matrix-spec-proposals/blob/main/README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](https://github.com/matrix-org/matrix-spec-proposals/blob/main/CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.". See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about, but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-12-04 23:52 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +the [standard for opaque identifiers](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
Pagination hasn't been implemented anywhere, which is a bit of a problem. I can't come up with any sensible way to implement it either. All current implementations simply load the room list of both users into memory and return a set intersection. Client implementation is trivial and has already been done, so the options are:

1. Implement pagination in some server (how?)
2. Remove pagination entirely, require a single response
3. Keep pagination in the spec without implementing it on a server, so that clients are future-proof in case a server does eventually implement pagination
4. Reject this MSC

Given how simple the spec is, I wouldn't mind option 3. Option 2 is fine too. 4 would be unfortunate.

2025-12-05 00:15 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +the [standard for opaque identifiers](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
Actually, if the reason for adding pagination is primarily response size, then I can think of a relatively trivial implementation:

1. compute entire response list
2. sort list lexicographically
3. cut off response at a certain index
4. return the last room id as the next batch token
5. when a request has a from token, drop items that are lexicographically lower than the token before cutting the response list

2025-12-05 00:22 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +the [standard for opaque identifiers](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
Only problem with that is the character set for opaque identifiers doesn't allow `!`, plus pre-v12 room IDs can have arbitrary unicode. Maybe it can be base64 encoded and truncated? Just need handling for the silly user case of having more than the batch size of pre-v12 rooms that have the same first 191 letters (e.g. don't return next batch token if new token matches old one)

2025-12-05 01:16 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +the [standard for opaque identifiers](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
https://github.com/element-hq/synapse/pull/19279

2025-12-05 01:17 UTC, tulir commented
This has been mostly ready for over 2 years and with https://github.com/element-hq/synapse/pull/19279, everything should be implemented as well

@mscbot fcp merge

2025-12-08 07:04 UTC, Johennes commented on proposals/2666-get-rooms-in-common.md
> +    "!DueayyFpVTeVOQiYjR:example.com"
Given that at least some of the foreseen use cases involve presenting the rooms in common to a user, would there be any benefit in including more than just the room ID here? As a drastic example, could the endpoint use the same response format as [`/publicRooms`](https://spec.matrix.org/v1.16/client-server-api/#post_matrixclientv3publicrooms), for instance?

2025-12-08 07:10 UTC, Johennes commented on proposals/2666-get-rooms-in-common.md
> +and is beyond the scope of this proposal.
Other endpoints in the spec, such as [`/_matrix/client/v3/users/{userId}/report`](https://spec.matrix.org/v1.16/client-server-api/#post_matrixclientv3usersuseridreport), explicitly reserve `404` for this case but allow other status codes if the server wishes to conceal user non-existence. Maybe this should be the same here?

2025-12-08 07:15 UTC, Johennes commented on proposals/2666-get-rooms-in-common.md
> +## Security considerations
Depending on how the server behaves when non-existing user IDs are queried, it could be possible for a client to infer whether or not an MXID exists. [`/_matrix/client/v3/users/{userId}/report`](https://spec.matrix.org/v1.16/client-server-api/#post_matrixclientv3usersuseridreport) in the current spec includes some precautions against this.

2025-12-08 12:04 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +    "!DueayyFpVTeVOQiYjR:example.com"
I don't think any of the client implementations so far have needed extra information. By definition the client is in all the rooms and most likely already has the room state (excluding member list). AFAIK even with sliding sync clients will get the entire room list fairly quickly

2025-12-08 12:05 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +## Security considerations
This is already in the MSC?

> If the `user_id` does not exist, or does not share any rooms with the authenticated user, an empty array should be returned.

Current server implementations don't really care whether the user exists or not, they just query the current state table for member events. If the user doesn't exist, there just won't be any results.

2025-12-08 12:08 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +and is beyond the scope of this proposal.
I think this line is specifically talking about things that can never be user IDs, like `?user_id=foobar` or `?user_id=@:::::`. `/report` doesn't seem to mention that case, it's only talking about user IDs that don't exist.

For invalid user IDs, there are no security considerations and it really doesn't make any difference whether the server returns 200 with an empty list or 400 because the client was dumb

2025-12-08 13:20 UTC, Johennes commented on proposals/2666-get-rooms-in-common.md
> +and is beyond the scope of this proposal.
Ah, ok. I misread this to refer to non-existing MXIDs, sorry. This seems fine then.

2025-12-08 13:23 UTC, Johennes commented on proposals/2666-get-rooms-in-common.md
> +## Security considerations
I think the response timing attack is not mentioned in the proposal.

> Furthermore, it might be possible for clients to deduce whether a reported user exists by timing the response. This is because only a report for an existing user will require the homeserver to do further processing. To combat this, homeservers MAY add a random delay when generating a response.

2025-12-08 13:28 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +## Security considerations
Current implementations aren't vulnerable to that, but I guess that might be worth mentioning in the MSC. There's no need for random delays or anything, because there's no separate code path for non-existent users

2025-12-08 13:28 UTC, Johennes commented on proposals/2666-get-rooms-in-common.md
> +    "!DueayyFpVTeVOQiYjR:example.com"
Ok, that sounds sensible. I was just curious and nothing in the proposal seems to touch upon why the response is not richer or more extensible.

2025-12-08 13:48 UTC, Johennes commented on proposals/2666-get-rooms-in-common.md
> +## Security considerations
Makes sense, thank you. 👍

2025-12-16 15:47 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +continue until the server does no longer insert `"next_batch"`. The `next_batch` field follows
```suggestion
continue until the server no longer inserts `"next_batch"`. The `next_batch` field follows
```

2025-12-16 15:47 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +`M_UNKNOWN` as the `errcode`. And the error description may be "you cannot request rooms in common with yourself".
```suggestion
`M_UNKNOWN` as the `errcode`. The `error` field value is up to the implementation. A suggested
value is "you cannot request rooms in common with yourself".
```

to avoid accidentally implying implementations cannot diverge from this suggestion.

2025-12-16 15:47 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +Tokens generated by this endpoint must be valid for at least 10 minutes, after which, tokens can expire.
```suggestion
Batch tokens generated by this endpoint SHOULD be valid for at least 10 minutes, after which, tokens can expire.
```

It's impossible to enforce this in [the Synapse implementation](https://github.com/element-hq/synapse/pull/19279), which just uses the base64url-encoded, last-returned Room ID as the batch token. It will be invalidated by the user joining/leaving rooms or rooms being purged by the homeserver.

2025-12-16 15:47 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +Expired tokens must be handled similar to invalid tokens, as described above.
```suggestion
Expired tokens SHOULD be handled similar to invalid tokens, as described above.
```

The [Synapse implementation](https://github.com/element-hq/synapse/pull/19279) will just return a random page of pagination. This is considered acceptable, as it's very unlikely that the list will change meaningfully during a pagination session.

We also cannot check whether the pagination token, which is a base64url-encoded Room ID, is valid as we truncate the encoded string to 255 bytes (due to the grammar rules above).

2025-12-16 15:47 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +longer need to check for the `unstable_features` flag.
@tulir I assume you (and other clients) will want to use this before homeserver implementations get around to advertising support for the Matrix version this will merge into?

2025-12-16 16:10 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +Tokens generated by this endpoint must be valid for at least 10 minutes, after which, tokens can expire.
The synapse implementation never invalidates tokens, it just won't return all rooms. Should probably specify that too (when using a batch token, rooms added after generating the token may not be included at all)

2025-12-16 16:13 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +longer need to check for the `unstable_features` flag.
Oh yes, stable flags are needed for basically all endpoints

2025-12-19 10:34 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +
```suggestion

The client can make another request to get the next batch of results:

```http
GET /_matrix/client/v1/user/mutual_rooms?user_id=%40bob%3Aexample.com&from=<opaque_identifier>
```
```

(Note: GitHub won't render the above properly due to the additional set of backticks.)

2025-12-19 10:41 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +with `M_INVALID_PARAM` as `errcode`.
```suggestion
If the batch token provided by the client is deemed invalid by the server, the server
MAY return the standard error response with HTTP code 400 and `errcode`
`M_INVALID_PARAM`.
```

2025-12-19 10:44 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +There possibly comes a time where it's desirable to query mutual rooms for more-than-one other user,
```suggestion
There possibly comes a time where it's desirable to query mutual rooms for more than one other user,
```

2025-12-19 10:45 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +parameters under `user_id`
```suggestion
parameter for the time being. This restriction may be lifted by a future MSC.
```

2025-12-19 12:04 UTC, anoadragon453 approved these changes
This MSC and the associated Synapse implementation look good to me.

Excited to see this one land!

2025-12-19 12:04 UTC, anoadragon453 commented on proposals/2666-get-rooms-in-common.md
> +This endpoint will take a query parameter of `user_id` which will contain the MXID of the user
```suggestion
This endpoint will take a required query parameter of `user_id` which will contain the MXID of the user
```

2026-01-06 15:50 UTC, turt2live approved these changes

2026-01-13 01:50 UTC, 1vel approved these changes

2026-01-13 13:27 UTC, clokep commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
This paragraph is a bit weird. I'd suggest making it an error instead:

```suggestion
If an invalid user ID is provided the server MUST respond with a 400 error with
code `M_INVALID_PARAM`.
```

2026-01-13 13:48 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
I think it was worded that way because it'd be better for another MSC to define user ID validation requirements across all endpoints

It's easiest for servers to just reuse existing logic rather than add new errors just for this endpoint. Synapse's query string parsing refuses non-ascii characters, but I don't think that precisely matches any existing user ID spec

2026-01-13 14:04 UTC, clokep commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
> It's easiest for servers to just reuse existing logic rather than add new errors just for this endpoint. Synapse's query string parsing refuses non-ascii characters, but I don't think that precisely matches any existing user ID spec

Isn't that just a bug in Synapse then and not something we should encode into the spec?

2026-01-13 14:26 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
Currently the MSC says to leave it as an implementation detail rather than encoding anything into the spec. Other endpoints like `GET /profile/{userId}` also don't specify any particular handling of invalid user IDs. I'd prefer doing it consistently for all endpoints rather than just this one.

2026-01-13 14:35 UTC, clokep commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
I think the current MSC gives zero guidance to client authors what to expect though. If I'm calling this API how am I supposed to write reasonable error handling?

2026-01-13 17:21 UTC, dbkr commented on proposals/2666-get-rooms-in-common.md
> +The response format will be an array containing all rooms where both the authenticated user and
```suggestion
The response format will be an array containing the room ID of all rooms where both the authenticated user and
```

2026-01-13 17:27 UTC, dbkr commented on proposals/2666-get-rooms-in-common.md
> +[opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
This does feel like more than is necessary to solve the brief given in the intro. A server might not want to bother implementing it, but then they need some way to show the results are truncated.

2026-01-21 00:42 UTC, uhoreg commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
I think that we should try to start new endpoints by having correct behaviour. If an user ID is invalid, it should return an error.

2026-01-21 03:21 UTC, uhoreg commented on proposals/2666-get-rooms-in-common.md
> +[opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
Maybe a `count` property, indicating the total number of rooms?  So that the client can say something like: "You're in these rooms, and 172 other rooms".

(Clients may also not want to paginate through all the results.)

2026-02-10 14:57 UTC, clokep commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
@tulir Can we come to a conclusion here? This is the last thread blocking my tick.

2026-02-10 14:57 UTC, dbkr commented on proposals/2666-get-rooms-in-common.md
> +[opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
Yeah, a count could work, although of course the server then still has to work out the total which might be nontrivial work.

2026-02-10 16:09 UTC, uhoreg commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
@mscbot concern should an error be required for invalid user IDs

2026-02-24 17:23 UTC, richvdh commented on proposals/2666-get-rooms-in-common.md
> +HTTP code 400, with `M_UNKNOWN` as the `errcode`. The `error` field value is up to the
👎  on speccing `M_UNKNOWN`.  `M_UNKNOWN` is basically "an exception got thrown in the depths of synapse and now we have to return something". It only really makes sense with 500 errors.

use `M_INVALID_PARAM` or something.

2026-02-24 17:23 UTC, richvdh commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
> If I'm calling this API how am I supposed to write reasonable error handling?

Given this only happens when you call the endpoint with a user id which we know doesn't exist (since it's invalid), I'm kinda failing to see the problem here. Don't call it with user ids that don't exist, and you won't have a problem?

2026-02-24 17:27 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +HTTP code 400, with `M_UNKNOWN` as the `errcode`. The `error` field value is up to the
Huh yeah not sure why that uses `M_UNKNOWN`, will change to invalid param

```suggestion
HTTP code 400, with `M_INVALID_PARAM` as the `errcode`. The `error` field value is up to the
```

2026-02-24 17:35 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
Yeah as a client author this isn't something I'd ever write explicit handling for. For non-critical endpoints like this one, errors can just be plumbed directly through to the UI, it doesn't matter why the server is refusing to answer.

If we really want to specify it, I can do this to explicitly specify that the "non-compliant" user ID class is rejected:

```suggestion
If the user ID is [non-compliant](https://spec.matrix.org/v1.17/appendices/#historical-user-ids),
the server returns HTTP 400 with the `M_INVALID_PARAM` error code.
```

but will need to find time to implement that in synapse, because right now the allowed character set is all of ASCII which is slightly larger than the compliant user ID set, plus I think the error code is different

2026-02-24 17:39 UTC, clokep commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
Then let's just spec something sane as an edge case instead of leaving it up to the implementation.

2026-02-24 17:41 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +[opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
In the current implementations adding the count would be trivial. It might not be in future implementations, but maybe that doesn't matter? The primary goal of pagination is ensuring the server doesn't have to send arbitrarily large response payloads.

We could define that the count may be inaccurate or something like that to let servers skip calculating the exact count if they feel it's too difficult

2026-02-24 17:44 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +return a success response with an empty array for invalid user IDs.
@mscbot resolve should an error be required for invalid user IDs

@mscbot concern implementations need updating to match specified error responses

2026-02-24 17:54 UTC, tulir commented on proposals/2666-get-rooms-in-common.md
> +[opaque identifier](https://spec.matrix.org/v1.16/appendices/#opaque-identifiers).
Added a count field, will implement it when I update the error codes (which already have a concern)

2026-02-27 22:02 UTC, tulir commented
@mscbot resolve implementations need updating to match specified error responses

https://github.com/element-hq/synapse/pull/19511

2026-03-04 22:23 UTC, merged

2026-04-30 18:26 UTC, thetayloredman commented
I thought I'd give a shot at writing this a Spec PR: https://github.com/matrix-org/matrix-spec/pull/2367

2026-06-02 15:02 UTC, turt2live commented
Merged 🎉