MSCxxxx: Serverside aggregations of message relationships
matrix-org/matrix-doc pull request #2675
Opened 2020-07-07 20:21 UTC by uhoreg

2020-07-07 21:00 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +incremental syncs), for instance: initial sync, gappy incremental sync,
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r308506108:

TravisR says:

> for readers: initial sync is one where the client doesn't provide a previous batch token, gappy is `limited: true` results.
> 
> (note to us: we should put these words in the spec because they aren't there).

(wording changed to reflect clarification given later in the thread)

2020-07-07 21:03 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +                      "count": 3
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r289391480:

jryans says:

> Our UI for reactions currently shows the senders of each reaction key in a tooltip when hovering, but we don't get that data at the moment when bundled. Should we add it here, or should the UI query all reactions when you try to hover (likely requiring a spinner)?

BillCarsonFr says:

> We also need a timestamp for ordering (time of first reaction of this type). We could compute it from the list of source events (if we know them?), but could be useful to have it in summary.
> 
> For reference, actually the local summary created incrementally in the riotX client, we have a boolean 'addedByMe', the list of source events and local echos, and a 'firstTimestamp' for ordering

ara4n says:

> the idea for showing senders is that you should get them via the `/relations` API if you want the full list of senders, rather than proactively summarising. We can start of with a placeholder using our local cache of details, and then swap it out for the full info from /relations on hoverover if that's insufficient.
> 
> however, BillCarsonFr's point i think is that if we're to display the reactions in chronological order, we need that info in the bundle somehow. i'll add a note into the rewrite that we could include this in the bundled version.

jryans says:

> See also the thread at [#1849 (comment)](https://github.com/matrix-org/matrix-doc/pull/1849#discussion_r311002030).

2020-07-07 21:05 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +sophisticated pagination techniques in future. For instance:
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r309630413:

erikjohnston says:

> I feel that not including `m.reference` here is surprisingly inconsistent TBH. If the intention in this MSC is for clients to be able to display "there are X replies to this messages" in the UI then it would be useful for `m.reference` to be included. If we want to have `m.reference` work in fancy ways I feel that we should remove it from the MSC rather than have it half specced in a way that no one would use, (though I worry that we're not implementing useful features today in the hopes that some day in the future we might finally implement fancy threading).

ara4n says:

> hang on - this isn't meant to provide the "there are X replies to this message"; it's meant to say "here are the relations you missed during the gap". Meanwhile, the next unbundled event you get will tell you the new aggregation count (in the proposed `unsigned.annotation_count` field).
> 
> I'm unclear where you'd send the "X replies to this messsage" metadata in general - we don't send it on the replies themselves anywhere (bundled or unbundled) currently

erikjohnston says:

> Oh, synapse currently bundles references in `unsigned["m.relations"]` to support that

2020-07-07 21:07 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +```
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r281994265:

erikjohnston says:

> We need to figure out how to send the aggregation key

erikjohnston says:

> We add a `key` query string param with the (url encoded) aggregation key

ara4n says:

> @erikjohnston why? can't we just fish it out of the event contents?

2020-07-07 21:12 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r308625636:

bwindels says:

> We would need a way for `/event` to not do server-side aggregation in that case, e.g. not replace the content with the latest edit. That's why we went with this solution, as all other endpoints are assumed to be doing server-side aggregation of the content for edits.

ara4n says:

> oh, right, i see. then how about making it optional when querying /relations?

bwindels says:

> you mean like a `include_original_event` query param? Yeah, that would work.

ara4n says:

> anoadragon453, erikjohnston wdyt?

erikjohnston says:

>Could do, though I would be fine with just always including the original event TBH, its not that much extra data for an endpoint that isn't on a hot path.

ara4n says:

> it's quite a hot path though - for instance, every time you hover over a message with reactions, your client will go and try to pull the full reaction list to formulate an accurate tooltip. do you really want to re-download the event every time too?

erikjohnston says:

> Getting the list of reactions is already going to contain a bunch of events anyway, including one more isn't going to be the end of the world. Also, didn't client folk request we included some `sender` fields in the bundled aggregations so that they didn't have to do a HTTP request to render the tooltip?

ara4n says:

they did, but i'm not convinced that it's a disaster to do a separate query to /relations to get the details? jryans how much do you want the server to calculate an aggregated label for you? it feels like this could be another refinement in future (the equivalent of LLing)

jryans says:

> I'm trying to think through the implications of not having the senders in bundled data...
> 
>     * For non-gappy incremental syncs, we receive the full relation, so we can store and display those senders
> 
>     * For other event receive paths (initial sync, gappy incremental sync, /messages, /context), we won't get the senders
> 
> 
> This means for recent reactions while your client has been alive in the room, we should have the senders already. For all other cases, we may be missing some or all senders, so the reaction tooltip will need to show a spinner and request `/relations` to complete the sender list. If we think that UX is okay for now, then it resolves this spec question from my perspective.

uhoreg says:

> Was this question ever resolved on the implementation side? If so, can we get the result written up in the MSC?

2020-07-07 21:16 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +a 404.
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r361335368:

tulir says:

> Assuming I didn't misunderstand something, this makes absolutely no sense. It doesn't prevent you from getting the relations, it just makes it pointlessly more difficult. In addition to that, looking at the reactions or replies of a redacted message should absolutely be allowed.

2020-07-07 22:02 UTC, deepbluev7 commented on proposals/2675-aggregations-server.md
> +relation events individually to the client.
Does this mean /messages doesn't return individual reactions or that it just provides additional info in unsigned?

2020-12-28 05:04 UTC, deepbluev7 commented on proposals/2675-aggregations-server.md
> +latest events using the `dir` param.
I think this needs to define, which is the default order and what the parameters to dir are. Otherwise edits will look funky, if a server returns the events in reverse by default. While we are at it, I don't see limit, from and to mentioned anywhere. An explicit mention of them would be nice.

Synapse by default seems to return the events in backwards order, i.e. latest event first and does not accept a dir parameter currently from what I can tell.

2020-12-31 12:05 UTC, Sorunome commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/relations/{eventID}[/{relationType}[/{eventType}]]
Depending on how we handle encrypted aggregations, the relationType might be encrypted and thus inaccessible to the server. As that parameter is optional in this MSC and a client could just fetch all aggregated events, decrypt, and filter, this request does NOT block the path of also encrypting the relation type. Soru thought it would be appropriate to mention the thoughts on this here, though, with the conclusion that it isn't blocking or anything.

2021-05-18 17:42 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +                "event_id": "$original_event_id",
Should this be the target event id rather?

2021-06-02 22:29 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +                      "count": 3
It looks like there is now an `origin_server_ts` field that can be used for ordering, and senders can be obtained from `/relations`, so I think this can be resolved now.

2021-06-30 14:19 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +### Redactions
It should mention here that redacting a relation should exclude it from the server-side aggregation for the relation target event.

2021-07-01 13:31 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +### End to end encryption
Aggregating annotations currently requires the event type of the relation event. This would mean the event type also should be provided in the plaintext somehow...

2021-07-01 14:07 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +`m.relates_to` field that may contain sensitive information.
[tulir says](https://github.com/matrix-org/matrix-doc/pull/2674#discussion_r451168542):
> Wouldn't it be better to include `m.relates_to` in both the plaintext and ciphertext to prevent servers from faking things like replies?
> 
> It should be a fairly painless migration: just start including it in the ciphertext and ignore the plaintext version if it exists in the ciphertext.

2021-07-01 17:01 UTC, deepbluev7 commented on proposals/2675-aggregations-server.md
> +`m.relates_to` field that may contain sensitive information.
One issue with that is, if a client is allowing edits of pending messages. Then it may be hard to decrypt the pending message again to fix the relation...

2021-07-02 11:30 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +`m.relates_to` field that may contain sensitive information.
@kevincox also [said](https://github.com/matrix-org/matrix-doc/pull/2674#discussion_r625431244):

> The other option would be signing the relation but that seems more complex and not worth it as we would expect that relations are often small.
> 
> The duplication also leaves open interesting possibilities such as adding additional context to the relationship in the ciphertext but omitting it in the relationship the server sees. This way you can have rich information without leaking it to the server. This would solve the "future MSC" issue in the following paragraph IIUC.
> 
> Another interesting feature would be client-only relationships. Obviously you can't have server support for indexing but for high-security scenarios this may be desired. However the tradeoffs with that would easily be a big MSC on its own.

2021-07-02 16:08 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +How do you handle ignored users?
See discussion at https://github.com/matrix-org/matrix-doc/pull/2674#discussion_r451151436 as well

2021-07-22 10:03 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
Note that, per https://github.com/matrix-org/synapse/issues/10310, Synapse currently replaces the original event with the edit even when you call `/event` directly on the original. I'm pretty sure that's incorrect behaviour, but it would be great if the MSC could call out exactly which endpoints should return the original, and which should return the edited version.

2021-09-10 11:50 UTC, clokep commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/aggregations/{eventID}[/{relationType}][/{eventType}][?filter=id]
I might have missed it, but what is this `filter=id` referring to? Is it meant to refer to a [standard filter from the C-S API](https://matrix.org/docs/spec/client_server/latest#filter)? I think some words mentioning that would be nice!

(Also, why would we only have the `/aggregations` endpoint accept this and not the `/relations` endpoint?)

2021-09-13 09:30 UTC, bwindels commented
@deepbluev7 has pointed out that we could make the target event id an opaque (encrypted) value as far as the server is concerned and pass that opaque id to /relations and /aggregations. If clients can decrypt that opaque value to the actual target event id, they can still apply the returned aggregation and relations to the correct event.

2021-09-13 09:35 UTC, deepbluev7 commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/relations/{eventID}[/{relationType}[/{eventType}]]
Attaching myself to this, because we had a discussion about this in #spec: https://matrix.to/#/%23matrix-spec%3Amatrix.org/%24fZGD31p5FqkWGIYTeHRR_YDwFZ6kNo0NsaJ2Ji7vj74?via=neko.dev&via=0x1a8510f2.space&via=matrix.org&via=libera.chat

Basically imo the server does not need to know about the rel_type, event_id or key to calculate aggregations. It can totally just operate on opaque values. That means it might calculate unnecessary aggregations or relations, if it precaches them, but clients would be able to obfuscate/encrypt those relation values.

One downside of that is that the server can't return different API shapes for the same query. I.e. /aggregations would always need to return the same schema. Imo that is the right way to go about it anyway, since having to switch return values for different input values can be ugly in statically typed languages and in general I think it is a bad design. Instead we should spec different endpoints for how we want the result aggregated instead of switchig in the rel_type. Further context is linked above.

2021-09-22 21:24 UTC, kevincox commented
I'm not quite sure I follow that suggestion. Maybe an example would help. If the server knows which events to return based on an encrypted event ID doesn't that mean that the server knows the mapping from encrypted id -> id which makes it pointless?

2021-09-22 22:04 UTC, kevincox commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/relations/{eventID}[/{relationType}[/{eventType}]]
I think that makes sense. I actually don't even see much point to querying based on `rel_type`. Why does the client need to ask for the edits, and replies, and reactions, and redactions... to each event? Most of them will just want to say "give me everything that references this event" and they can render the reactions, edits...

I think the only think right now that most clients don't ask for is replies to an event, but honestly that could be useful as a client could indicate that there is a reply somewhere (especially if we get threading, but that may want a full thread returned as mentioned anyways...) Either way the amount of data that references a particular event is probably fairly small anyways so the overhead is small.

The only use case we miss out is "aggregations" such as the server summarizing the reactions into `Map[Type => Count]` but every clients wants to show *who* did each reaction anyways so I don't think we have a real use case for aggregations yet and would happily defer that.

2021-10-04 14:18 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +The `/relations` API lets you iterate over all the **unbundled** relations
so does this mean that any relations of the returned events themselves are not included in bundled format? E.g. if `A` relates to `B` which relates to `C`, and you ask for `/relations/C`, will `B` include `A` as a bundled relation or not when returned?

2021-10-04 14:23 UTC, clokep commented on proposals/2675-aggregations-server.md
> +The `/relations` API lets you iterate over all the **unbundled** relations
Synapse does not currently include those, this was changed in matrix-org/synapse#5654. It seems the rationale is:

> {W]e don't allow relations to be applied to relations, so we return the original relations without any aggregations on top of them here.

The PR description notes that this is really because of edits:

> We [do not bundle relations] when pulling the relation events as well, because edits of edits are not something we'd like to support here.

This seems based on the request to include the original event in the `/relations` response (matrix-org/synapse#5595).

I don't think this is quite doing the right thing.

2021-11-19 16:01 UTC, clokep commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/aggregations/{eventID}[/{relationType}][/{eventType}][?filter=id]
I suspect this should just be removed, I'm not sure it makes sense and isn't implemented AFAIK.

2021-11-19 16:25 UTC, clokep commented on proposals/2675-aggregations-server.md
> +related events with the original event where appropriate.
It also defines an API to paginate through relations of an event, which seems to missing in this paragraph.

2021-11-19 16:27 UTC, clokep commented on proposals/2675-aggregations-server.md
> +aggregations, avoids us having to always send lots of individual unbundled
Is it a bundled relation or a bundled aggregation? I find the terminology confusing that we seem to use both. We should choose one (probably "bundled aggregation").

2021-11-19 16:32 UTC, clokep commented on proposals/2675-aggregations-server.md
> +The format of the aggregated value in the bundle depends on the relation type.
This seems to overly prescribe what happens with annotations and references, but is inaccurate for edits and threads.

It might be clearer to say to skip the bits about `chunk`/`count`, etc.

```suggestion
The bundled aggregations are grouped according to their `rel_type`. The format
of the aggregated value in the bundle depends on the relation type.
```

2021-11-19 16:35 UTC, clokep commented on proposals/2675-aggregations-server.md
> +sophisticated pagination techniques in future. For instance:
Just a note that Synapse doesn't current implement `stale_events`.

2021-11-19 16:36 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  XXX: Is this implemented in Synapse yet?
No, Synapse does not support fetching multiple events at once this way.

2021-11-19 16:38 UTC, clokep commented on proposals/2675-aggregations-server.md
> +The `/relations` API lets you iterate over all the **unbundled** relations
There's a current PR up for Synapse to change this behavior to be specific to annotation and edits. Pretty much stating that any relation which targets to an event which is an annotation/edit is invalid.

See #matrix-org/synapse#11284, this is somewhat described in MSC3440 but really should be here.

2021-11-19 16:40 UTC, clokep commented on proposals/2675-aggregations-server.md
> +M_INVALID_REL_TYPE.
```suggestion
`M_INVALID_REL_TYPE`.
```

2021-11-19 16:41 UTC, clokep commented on proposals/2675-aggregations-server.md
> +The `/aggregations` API lets you iterate over **bundled** relations, and within them.
I think this could be more explicit (and that the two forms of this API could use section headers:

```suggestion
The `/aggregations` API lets you iterate over **bundled** relations, and the
unbundled relations within them.
```

2021-11-19 16:42 UTC, clokep commented on proposals/2675-aggregations-server.md
> +M_INVALID_REL_TYPE.
This paragraph should probably be after the paragraph below this one, otherwise you're talking about an error state before describing the non-error state (which is confusing IMO).

2021-11-19 16:51 UTC, clokep commented on proposals/2675-aggregations-server.md
> +## Edge cases
An edge case that seems to be missing here is what to do if you lose access to a room after receive an event, for example:

alice and bob are in a room together. Alice sends event `A`,  `A` is annotated by event `B` (key = 🚢  ) from bob, alice leaves the room and history is not world visible. Bob annotates `A` with event `C` (key = 🚀 ). When alice requests event `A` should the bundled relations include results from both `B` and `C`? (Similar logic should be applied for the `/relations` and `/aggregations` API, I think.)

The opposite case also should probably be mentioned somewhere in this MSC, but I think is more straightforward:

If alice joins a room that does not have history visibility and receive events `Y` which annotates event `X`, what does that mean? (I think it means that there's an annotation that it can't resolve of the content of and tough luck, clients need to deal with that -- this is pretty much how we deal with quote replies currently.)

2021-11-19 16:54 UTC, clokep commented on proposals/2675-aggregations-server.md
> + * XXX: what does synapse do here?
It does not look like Synapse has any special handling here (minus handling event edits, I think?)

2021-11-19 17:06 UTC, clokep commented on proposals/2675-aggregations-server.md
> +associated with an event in standard topological order.  You can optionally
Note that there was a discussion at https://github.com/matrix-org/matrix-doc/pull/3440#discussion_r732607492 about how this can somewhat fail in federation since this API (as-is) only returns events known to the homeserver. This mostly comes about when a server joins a room (which it can see history of) and needs context in what the various relations flying around are to.

It might be OK to leave this to a future improvement, but we should probably mention it.

2021-11-22 15:25 UTC, richvdh commented
seems like there are lots of comments here which need addressing; I don't think more input from the SCT is a blocker at the moment, so I'm removing it from the todo list.

2021-11-22 15:32 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
This makes no sense. If we're iterating over the relations for an event, that implies they aren't bundled with the event.

2021-11-22 15:34 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +aggregations, avoids us having to always send lots of individual unbundled
big +1 to this. I spent a while being confused about what the difference between an "bundled aggregation" and "bundled relation" is.

Personally, I think "bundled aggregation" is too vague (aggregation of what?). The very fact it's being bundled implies the aggregation, and we should stick to calling it "bundled relation". 

But I don't mind too much so long as we pick one and stick to it rather than using them interchangably.

2021-11-23 14:22 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
AIUI, this would iterate over the aggregation groups of the relations, of which the layout depends on the rel_type. For `m.annotation`, the entries would be grouped by `key`.

2021-11-23 14:27 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +a 404.
@clokep how is this currently implemented?

2021-11-23 14:35 UTC, clokep commented on proposals/2675-aggregations-server.md
> +a 404.
Right now `/relations/{eventId}` and `/aggregations/{eventId}` for a redacted event returns an empty pagination `chunk`.

It seems that iterating the relations in a bundled aggregation `/aggregations/{eventId}/[/{relationType}][/{eventType}]` doesn't do this check at all.

We should definitely be consistent about the three and probably consistent with other similar APIs (if there are any?)

2021-11-23 14:39 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +## Edge cases
I'd be include to say that Alice should not see the :rocket: as it was sent while she was not in the room. Any reason to do it otherwise (e.g. server impl complexity)?

The opposite case, it would indeed be good to mention.

2021-11-23 14:49 UTC, clokep commented on proposals/2675-aggregations-server.md
> +## Edge cases
> I'd be include to say that Alice should not see the 🚀 as it was sent while she was not in the room. Any reason to do it otherwise (e.g. server impl complexity)?

I think for iterating over individual relations it should be quite doable. For aggregations it might be a bit harder. (But I agree that we shouldn't leak information about events the user can't access.)

2021-11-23 15:09 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
e.g. as described here: https://github.com/uhoreg/matrix-doc/blob/aggregations-helpers/proposals/2675-aggregations-server.md#bundled-relations

2021-11-23 15:29 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +incremental syncs), for instance: initial sync, gappy incremental sync,
Have tried to clarify this.

2021-11-23 15:33 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +sophisticated pagination techniques in future. For instance:
I will remove any mention of `stale_events` as it is not implemented currently.

2021-11-23 16:15 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +aggregations, avoids us having to always send lots of individual unbundled
I understood that "bundled" referred to it being bundled with the target event, not that it "bundled" several relations together in an aggregation. I will stick to bundled aggregation (short for bundled relation aggregation if at some point we will aggregate something else) throughout the MSC.

2021-11-23 16:23 UTC, clokep commented on proposals/2675-aggregations-server.md
> +aggregations, avoids us having to always send lots of individual unbundled
It might help to define the term somewhere up-front, instead of in prose. But yeah, we need to stick to a single term. I don't think `aggregation` is ever really defined?

I've been referring to these internally in the Synapse code-base as "bundle relations", but I don't really care which we choose as long as we're consistent.

2021-11-23 17:24 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
yes, but in this case, they aren't bundled with the event, right? So why are they called bundled relations (or bundled aggregations, or bundled anything?)

aren't they just the relations for an event?

2021-11-23 17:26 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
indeed, apparently the whole point of this is that we *don't* want to bundle them:

> we do not want to overload the client by including them all in a bundle

2021-11-23 18:07 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +relation events individually to the client.
I think this is answered below?

2021-11-23 18:11 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +                      "origin_server_ts": 1562763768320,
Where does the timestamp come from here?

2021-11-23 18:23 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +To refresh events, we need an API to load arbitrary events from the room in
I'm not entirely clear on why this is necessary: a comment below says synapse doesn't implement it anyway, so maybe this should be split out to a different MSC (or just removed for now)?

2021-11-23 18:24 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +`{roomId}/event/{eventId}` to accept a list of event IDs on the URL, e.g:
In the example, they're in the body, not the URL.

2021-11-23 18:32 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +elements in the list.
This is a bit confusing without reference to the relations endpoints below - a nod to say that this is effectively the first few results of the pagination given by the endpoints would be good (although it's in the chunked format & includes count, but doesn't include next_batch: is that intentional?)

2021-11-23 18:40 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
*prod* - would be good to know the current status of this in the impl

2021-11-23 18:42 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +Trying to iterate over an relation type which does not use an aggregation key
```suggestion
Trying to iterate over a relation type which does not use an aggregation key
```

2021-11-23 18:51 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
The description in the FIXME is accurate to the implementation!

2021-11-23 18:56 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +## Edge cases
Hmm, this does also imply that if Alice sends an event, Bob leaves the room, Alice edits the event and Bob rejoins, Bob should see the un-editied message, which doesn't feel right. Equally I think it would be confusing if people saw different reactions counts on a message in the situation you mention. I'd be more inclined to argue that visibility should be on the basis on whether you can see the parent event. Neither is really ideal for threads though...

2021-11-23 19:02 UTC, clokep commented on proposals/2675-aggregations-server.md
> +## Edge cases
Oh, that's a really weird one! One might argue that the most recent edit should always be shown (although that does depend on the server still being in the room).

Visibility of the original event is something that I thought about briefly, but it seemed odd for threads, and maybe for edits (as you point out).

Implementation wise it is definitely easier (and more cachable) if all users see the same "view" of the room's bundled events.

2021-11-24 12:33 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +elements in the list.
Good point, and you're proving it as the pagination would actually happen through the /aggregations endpoint ;)

2021-11-24 12:35 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +                      "origin_server_ts": 1562763768320,
Yeah, I guess this is given more as a non-binding example of what annotations could look like, but perhaps it's better to remove it altogether and not give any examples for `rel_type`'s in this MSC?

2021-11-24 13:27 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +Relations are received during non-gappy incremental syncs (that is, syncs
This implies they are not received for anything but non-gappy syncs, which is not true.

2021-11-24 13:34 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +                "count": 1
Am I right to think that it would also set `next_batch` if there are more aggregations to be fetched using `/aggregations`? See https://github.com/matrix-org/synapse/blob/a19d01c3d95f5dbd3a4bb181cb70dacd44135a8b/synapse/storage/databases/main/relations.py#L216

2021-11-24 13:34 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +                "count": 1
Getting the count would be somewhat valuable though for displaying purposes, before fetching the rest.

2021-11-24 13:44 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +To iterate over the unbundled relations within a specific bundled relation, you
is this actually used? shouldn't we be using /relations for this? seems weird /aggregations would return unbundled relations rather than aggregations...

2021-11-25 10:47 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +aggregations, avoids us having to always send lots of individual unbundled
I've tried to clarify this. I'll let either of you have a look before resolving this.

2021-11-25 13:08 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +relation events individually to the client.
Have explicitly mentioned that relation events are always returned, just aggregations are not always bundled on the target event.

2021-11-25 13:10 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +```
This endpoint has been left out, rendering this redundant.

2021-11-25 13:11 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/relations/{eventID}[/{relationType}[/{eventType}]]
Resolving this given that encrypted relations are out of scope for this MSC.

2021-11-25 14:56 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +### End to end encryption
I've documented this limitation for the new endpoints. The limitation for annotations should be documented in #2677

2021-11-25 15:02 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +                "count": 1
went with what synapse does now, using `chunk` and `next_batch`.

2021-11-25 15:12 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  XXX: Is this implemented in Synapse yet?
This has been removed since

2021-11-25 15:18 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
So the idea is that the bundled aggregations are truncated if there are more than a certain amount, and using /aggregations allows you to paginate the rest. I've tried to clarify this since your comment, let me know if that resolves it.

2021-11-25 15:21 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +                      "origin_server_ts": 1562763768320,
Have removed the timestamp and clarified that this is a non-normative example.

2021-11-25 15:21 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +`{roomId}/event/{eventId}` to accept a list of event IDs on the URL, e.g:
This endpoint has been removed since

2021-11-25 15:21 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +elements in the list.
Have clarified this

2021-11-25 15:22 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +To refresh events, we need an API to load arbitrary events from the room in
Have removed

2021-11-25 15:55 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +`m.relates_to` field that may contain sensitive information.
We're focussing on documenting what is being used in the wild, so punting this for now.

2021-11-25 16:05 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +The `/relations` API lets you iterate over all the **unbundled** relations
Ok, so if I understood correctly we're solving this by:
 - the CS api will refuse to send a relation targeting a m.replace or m.annotation. Do we care about the federation workaround here?
 - /relations will include bundled aggregations (which will be empty for m.replace and m.annotation relations as those can't be targeted)

2021-11-25 17:43 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +latest events using the `dir` param.
Does https://github.com/matrix-org/matrix-doc/commit/143a70ea9739a924f29ab15c5af6f6264f6ac1fb resolve this?

2021-11-25 17:45 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
Thanks - who has the con on updating this? Personally it feels like this would be a thing that belongs in an `m.replace` MSC rather than this one?

2021-11-25 17:51 UTC, dbkr commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
As above - feels like maybe this ought to be in an `m.replace` MSC? Does someone have the con on updating it either way?

2021-11-26 10:06 UTC, deepbluev7 commented on proposals/2675-aggregations-server.md
> +with events they return:
Is there a way to opt out of this, i.e. using a filter option?

2021-11-26 10:08 UTC, deepbluev7 commented on proposals/2675-aggregations-server.md
> +latest events using the `dir` param.
Yep, looks fine now.

2021-11-26 10:37 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
I'm mentioned it here, but also made a node to mention it in #2676

2021-11-26 10:42 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  call /event to grab the contents of the original?
Yeah, will make a note in #2676 to mention this/deal with this. I agree, I don't think it belongs here.

2021-11-29 14:35 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +with events they return:
No, nothing like this is foreseen. Do you think there should be an option like this? If so, can you argue why there should be?

2021-11-29 15:05 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +with events they return:
Actually, we're focusing on documenting the current implementations of this MSC here, so I don't think we'll want to add this option here. A future MSC would be more appropriate.

2021-11-29 15:41 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +To iterate over the unbundled relations within a specific bundled relation, you
AFAICT, this isn't used in any platform of Element, nor is it implemented [in Synapse](https://github.com/matrix-org/synapse/blob/6a5dd485bd82b269e7e169c0385290d081eae801/synapse/rest/client/relations.py#L284), so removing `/aggregations/{eventID}/${relationType}/{eventType}/{key}` which returns a discrete relation event.

2021-11-29 15:46 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +To support creating relations for pending events, clients will need a way for
Have mentioned transaction_id now

2021-11-29 15:46 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +To iterate over the unbundled relations within a specific bundled relation, you
Have removed

2021-11-29 16:07 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +To iterate over the unbundled relations within a specific bundled relation, you
Actually, synapse [does](https://github.com/matrix-org/synapse/blob/6a5dd485bd82b269e7e169c0385290d081eae801/synapse/rest/client/relations.py#L359) implement it. But still leaving this out as I find it counter-intuitive that an endpoint that usually returns aggregations would with an extra parameter return a discrete event. And that no client uses it.

2021-11-30 10:10 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +The `/relations` API lets you iterate over all the **unbundled** relations
I've added comments to #2676 and #2677 regarding the first point, regarding the second, I've added /relations to the list of endpoints that should bundle aggregations above. Is this sufficient to resolve this issue?

2021-11-30 10:13 UTC, bwindels commented on proposals/2675-aggregations-server.md
> + * XXX: what does synapse do here?
I'm not sure we should special case relations in /context tbh. At least not while we don't have a usecase for it. If you want the target event of a relation, you can easily get the event id from the relation and call /context on the parent. Shall I remove this edge case or add that we don't want to special case it for now?

2021-11-30 10:19 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +associated with an event in standard topological order.  You can optionally
Copying the comment mentioned above here as the link doesn't work anymore:

Kegsay:

There are no server or federation considerations here which is a mistake. You're relying on [MSC2675](https://github.com/uhoreg/matrix-doc/blob/aggregations-helpers/proposals/2675-aggregations-server.md) to aggregate thread replies but that has no federation handling at all. This means you will get incomplete thread replies over federation, making this feel flakey and unreliable. Consider cases like:
 - Server A in a big room, users make a thread and send a bunch of replies.
 - Server B joins the room. The server has no history other than the current state.
 - Users on Server A send a reply to a thread.
 - Clients on Server B are unable to work out what the root event is or the earlier replies are in this single-level deep thread. There's no mechanism to fetch the root event (`/context` doesn't work over federation) and there is no mechanism to fetch earlier replies in the DAG).

This behaviour may be acceptable when it is just reactions and losing a few don't really matter (controversial choice but okay). However, this is unacceptable when it comes to messages themselves. MSC2836 explores this topic and has a proposal to handle this:

> In an ideal world, every server would have the complete room DAG and would therefore be able to explore the full scope of a thread in a room. However, over federation, servers have an incomplete view of the room and will be missing many events. In absence of a specific API to explore threads over federation, joining a room with threads will result in an incomplete view.

2021-11-30 10:24 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +M_INVALID_REL_TYPE.
The text has changed considerably since your comment, can you verify that the order isn't confusing anymore now?

2021-11-30 10:45 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +a 404.
The spec doesn't really mention whether redacted events should be left out, but from testing on matrix.org, both `/context` and `/messages` leave redacted events in. I agree with Tulir that this is the desired behaviour (for one, it helps clients find overlap with the parts of the timeline they already know about).

What do you think @clokep? Should we:
 - not special case redacted relation target events to be (seemingly, AFAICT) in line with /messages and /context, and change Synapse according that that change in this MSC.
 - OR focus on documenting the current (Synapse) behaviour, even though we agree it is undesirable.

2021-11-30 12:29 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +## Edge cases
Hmm, not sure what to do here ... Not sure if that's what you're both saying or not but I think (too) that it makes sense that for `m.replace` and `m.annotation` relations, visibility depends on whether the target event is visible.

For `m.thread` relations, it feels like the actual `m.thread` relation should be visible to the user.

Should we specify that visibility depends on the relation type used and should be specified in the MSC defining the `rel_type`?

2021-11-30 13:29 UTC, clokep commented on proposals/2675-aggregations-server.md
> +a 404.
> not special case redacted relation target events to be (seemingly, AFAICT) in line with /messages and /context, and change Synapse according that that change in this MSC.

I suspect being consistent with `/messages` and `/context` is better. Synapse is already internally inconsistent so we'll need to make changes there anyway.

2021-11-30 13:31 UTC, clokep commented on proposals/2675-aggregations-server.md
> + * XXX: what does synapse do here?
I'm not sure why we would re-define `/context` for relations. I suppose it could do something like return the root event and other relations for it, but that's essentially what the `/relations` API does.

I agree this can be removed.

2021-11-30 13:32 UTC, clokep commented on proposals/2675-aggregations-server.md
> +## Edge cases
> Should we specify that visibility depends on the relation type used and should be specified in the MSC defining the `rel_type`?

Special-casing based on relation type is non-desirable as it adds complexity. I'd be curious if any one else has opinions on what to do here. I think the "easiest" thing is to just let the events be visible, even if they don't make much sense (e.g. seeing an annotation to an event you don't have access to).

2021-11-30 13:44 UTC, clokep commented on proposals/2675-aggregations-server.md
> +relationships and maintain an correct view.
```suggestion
relationships and maintain a correct view.
```

2021-11-30 13:51 UTC, clokep commented on proposals/2675-aggregations-server.md
> +of a given event, and the discrete relation events within them.
I believe you removed the form of this endpoint which lets you iterate over individual events.

```suggestion
The `/aggregations` API lets you iterate over aggregations for the relations
of a given event.
```

2021-11-30 13:55 UTC, clokep commented on proposals/2675-aggregations-server.md
> +As clients only receive discrete relation events through /sync,
```suggestion
As clients only receive discrete relation events through `/sync`,
```

2021-11-30 13:56 UTC, clokep commented on proposals/2675-aggregations-server.md
> +   (or using edits as a side-channel to harass you).
This is somewhat non-trivial as it breaks the assumption that aggregations are the same for all users.

2021-11-30 18:41 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +a 404.
Have clarified this.

2021-11-30 18:45 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +   (or using edits as a side-channel to harass you).
I agree that would be very nice to simplify the server implementation, but the visibility question above also already puts this into question...

2021-11-30 19:07 UTC, clokep commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/aggregations/{eventID}[/{relationType}][/{eventType}][?from=token][&to=token][&limit=amount]
I suspect both APIs will actually land with `v1`, not `r0` since they only exist as unstable right now? I'm not sure how the SCT wants to handle these APIs though since they've existed for so long, but are technically pre-1.1.

2021-11-30 19:37 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/r0/rooms/{roomID}/aggregations/{eventID}[/{relationType}][/{eventType}][?from=token][&to=token][&limit=amount]
Good point, have addressed this.

2021-11-30 20:08 UTC, turt2live commented
The majority of this should be ready for re-review from the SCT.

2021-12-01 15:01 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  - `GET /rooms/{roomId}/context`
For both `/messages` and `/context` Synapse does *not* bundle aggregations for state events (just like it doesn't bundle them for `/state`). Not sure if we should add that in here?

I think generally relations to state events are not supported, but not sure if any MSC makes that explicit or if it just doesn't really make sense.

2021-12-01 15:04 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  - `GET /rooms/{roomId}/context`
(I guess this applies to `/sync` too if we wanted to be consistent.)

2021-12-02 18:07 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  - `GET /rooms/{roomId}/context`
Thinking on this a little more, we should probably consistently never return these for state events or return them for all events.

MSC2674 does not forbid relations to state events, so I think the synapse implementation does this as an optimization? Not a huge deal either way, but would be good to have a decision.

2021-12-02 19:03 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  - `GET /rooms/{roomId}/context`
I guess MSC 2674 could have mentioned that you can't relate to state events, but it's merged now ...

I've added a mention here that state events never bundle aggregations. Sufficient?

2021-12-02 19:12 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  - `GET /rooms/{roomId}/context`
Seems reasonable to me.

2021-12-02 20:14 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  - `GET /rooms/{roomId}/event/{eventId}`
Just to be consistent:

```suggestion
  - `GET /rooms/{roomId}/context/{eventId}`
  - `GET /rooms/{roomId}/event/{eventId}`
```

2021-12-07 01:23 UTC, ara4n commented on proposals/2675-aggregations-server.md
> +## Edge cases
I'm with Bruno.  For `m.replace` and `m.annotation` then visibility depends on the event they target.  But for `m.thread` it should be on the actual relation.  Yes, it makes the spec more complicated, but from a privacy perspective it's only the appraoch that makes sense.

2021-12-07 17:03 UTC, turt2live commented
In an effort to get concerns raised more quickly, let's merge this:

@mscbot fcp merge

2021-12-14 01:56 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +## Edge cases
Dependence on  the relation seems the right way to go, even if it does mean a new room version (as we have to change the history visibility rules, effectively). Note that this will also have an impact on encryption for clients which (currently) opt-in the premise of sending decryption keys to new, or recently new, members - they'll have to consider a case where the now-rejoined user will need keys for past relations as it might impact their visibility of the whole thing.

2021-12-14 01:58 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +   (or using edits as a side-channel to harass you).
This is a more important argument to me than history visibility: users should never receive/see events from ignored users, including reactions, etc.

2021-12-14 02:00 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +The `/relations` API lets you iterate over all the **unbundled** relations
I think so? @clokep does the above seem reasonable to you?

2021-12-14 02:01 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
@richvdh do the new changes clarify your concern here?

2021-12-14 10:51 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
yup they seem to, thank you!

2021-12-14 12:16 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +   (or using edits as a side-channel to harass you).
I think nothing needs to be added here as I think we agree that we need to sacrifice cacheability to prevent possible abuse.

2021-12-14 12:50 UTC, clokep commented on proposals/2675-aggregations-server.md
> +The `/relations` API lets you iterate over all the **unbundled** relations
I missed this thread, sorry. Got buried by GitHub's UI it seems.

I think your summary above makes sense. Punting the discussions of which sort of events those specific relations can target to the other MSCs makes sense. I think the current state of this MSC makes sense and we can treat those as exceptions in the other MSCs.

2021-12-14 12:53 UTC, clokep commented on proposals/2675-aggregations-server.md
> +## Edge cases
I guess if we made the changes we would want them to apply to e.g. `/sync` and such as well, which is why this would require changes to history visibility rules?

Do we need changes in this MSC for this or are we essentially saying the other relation MSCs need to discuss this?

2021-12-14 18:28 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +## Edge cases
> f we made the changes we would want them to apply to e.g. `/sync` and such as well, which is why this would require changes to history visibility rules?

Yeah, that's how I understand it too. Visibility rules apply to all CS API endpoints.

> Do we need changes in this MSC for this or are we essentially saying the other relation MSCs need to discuss this?

I've made changes to this MSC with the visibility changes, so I'm resolving this issue.

2021-12-14 18:51 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +## Edge cases
I've also added a section here what to do with relation events for which the target event is not visible to a user.

2021-12-14 18:54 UTC, richvdh requested changes
Quite a lot of comments here, but I don't think any of them are particular show-stoppers.

There are a couple of requests for justification, but hopefully they are easily answered.

Most of the comments are about formatting and wording. I'm sorry if this seems nit-picky; it's not intended to, but rather it's to confirm that my understanding is correct.

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +others might aggregate to a single object or any other value really.
some examples here would really help my understanding, even though it would be non-normative. I think `m.annotation` is an example of a rel type that groups by key, whereas `m.replace` is an example that aggregates to a single object?

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +(in line with `/sync` API).
Somehow the first sentence here made me question everything that I'd understood so far about this MSC. It's kinda factually correct, whilst apparently approaching the problem from an odd direction. Isn't this "too much data" problem the entire reason aggregations exist?

How about:
```suggestion
To allow clients to get more detail on the relationships of a given event, we 
provide a new `/relations` API, which  behaves in a similar way to
`/messages`, except using `next_batch` and `prev_batch` names
(in line with `/sync` API).
```

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +  ],
again: how do we know the `rel_type` here?

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/v1/rooms/{roomID}/relations/{eventID}[/{relationType}[/{eventType}]][?from=token][&to=token][&limit=amount]
presumably `relationType` and `eventType` work the same way as for `/aggregations`?

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +As clients only receive discrete relation events through `/sync`,
huh. I thought that `/sync` returned aggregations?

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +as a client might not be aware of all relations for an event. Local aggregation
Long sentence is very long. I think the final clause confuses more than it clarifies?

```suggestion
As clients only receive discrete relation events through `/sync`,
they need to locally aggregate these relation events for their parent event,
on top of any server-side aggregation that might have already happened,
to get a complete picture of the aggregations for a given parent event,
Local aggregation
```

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +event, ideally regardless of the parent event having an `event_id` already or
```suggestion
event, ideally regardless of the parent event having received an `event_id` already or
```

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +need to be set the newly received `event_id`.
this feels a bit like we're mandating one possible implementation - isn't it up to the client implementation to figure out how best to make the numbers match up?

Perhaps we could prefix this with words like "Here is one possible implementation:" ?

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +   (or using edits as a side-channel to harass you).
it might be worth adding a note here to make it explicit that this means that different users may see different aggregations (and hence different reaction counts) on the same event.

2021-12-14 18:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +account of the relation will suffer from the same limitation.
I don't understand this - what does "take the event type into account of the relation" mean?

2021-12-14 18:59 UTC, richvdh requested changes
argh

2021-12-14 18:59 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +The change of visilibilty rules will require a new room version.
this is a *huge* scope change to throw in this late in the MSC process! If we want to change the way visibility works, please can it be a new MSC explaining the changes in more depth?

2021-12-14 19:00 UTC, richvdh commented
@mscbot concern visibility changes need to be descoped

2021-12-15 10:07 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +State events never bundle aggregations.
Because synapse doesn't implement this, see  see https://github.com/matrix-org/matrix-doc/pull/2675#discussion_r760269297 . We're documenting the existing implementation(s), for better or worse.

2021-12-15 10:11 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +in the `m.relations` property of their unsigned data.  These are called
Indeed documenting the existing state, not sure what the rationale was at the time, but looking at https://github.com/matrix-org/matrix-doc/pull/3171/files#diff-2f4a093e1bce3b08fb198ee1698c230c5c9303162f06b18bc9cc305e10f27069R403 I'm also not sure when the usage of `m.` as a prefix is recommended.

2021-12-15 11:50 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +in the `m.relations` property of their unsigned data.  These are called
the CNSIG is really meant for things that are very likely to be extended by client/server implementations. Event types are a good example; the contents of `unsigned` is not, really (particularly given everything else in `unsigned` does not use a prefix).

Part of me wants to fix this before it gets too much worse. I guess we could make synapse return *both* `m.relations` and `relations` for a while, and then make sure the clients get switched over to `relations`. It's a bit of a long game at this point though :(.

2021-12-15 13:33 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +account of the relation will suffer from the same limitation.
Right, so specifically, as part of #2677, it is still being debated whether the aggregation for `m.annotation` events should be grouped by, and contain the event `type` (mostly if not always `m.reaction`) or not. Relations are supposed to be encrypted, apart from their `m.relates_to` field, so their event type would in that case always be `m.room.encrypted`, which would render this grouping by event type less useful. I think the rationale is that annotations of a different type than `m.reaction` could be displayed in a different way by clients, but in practice we don't really have such a use case.

Less to the point, but also note that some if not all clients currently:
 - cheat and don't encrypt reactions at all
 - don't use server aggregation for reactions
 
More to the point, would this rewording make it more understandable? Or would you like the above rationale to be included in the MSC?
```suggestion
less useful for encrypted rooms. Aggregation algorithms that take the type of the relation events they aggregate into
account will suffer from the same limitation.
```

2021-12-15 13:37 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +   (or using edits as a side-channel to harass you).
Have added a specific note :+1:

2021-12-15 14:09 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +The change of visilibilty rules will require a new room version.
Ok, fair point, and sorry for the mess. I've moved this to MSC3570 now.

2021-12-15 15:04 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +## Edge cases
Rich made the good point this what is discussed here is too big of a scope creep this late in the game, so I have moved the visibility changes to #3570 . Note that threads don't depend on this as `m.thread` relations have the same visibility as other events.

2021-12-15 15:19 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +in the `m.relations` property of their unsigned data.  These are called
> Part of me wants to fix this before it gets too much worse. I guess we could make synapse return _both_ `m.relations` and `relations` for a while, and then make sure the clients get switched over to `relations`. It's a bit of a long game at this point though :(.

That's reasonable, but can we please not do that here an stick to documenting usage in the ecosystem?

2021-12-15 15:26 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +
There's also /relations though (which you pointed out feels slightly out of scope)

2021-12-15 15:34 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +paginate within each group using Matrix's defined pagination idiom of
This MSC doesn't specify any values for `rel_type` in the relation, and hence no aggregation formats that are specific to the `rel_type`.

OTOH, we did come up with a pattern that seems sensible to use for pagination (and that is partially implemented in Synapse IIRC), so I opted to suggest it here, so that the work does not get lost.

Perhaps it would be better to remove this though and leave it up to the first MSC needing pagination to introduce this.

2021-12-15 15:42 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +Some `rel_type`s might additionally group the aggregations by the `key` property
there is no difference, it's just a reminder which field is used to determine the relation type.

2021-12-15 15:51 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +(i.e. `m.replace` and `m.reference`) should fail with 400 and error
They do aggregate, but just not to an array. There are some voices that the `key` field should be used in all relation types that group on a key like annotations do, hence the generic language here.

2021-12-15 16:12 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  ],
That is an excellent point. In practice, synapse only returns the aggregation for `m.annotation` when the rel_type is omitted, and when another rel_type than `m.annotation` is provided, it returns an error (with the wrong error code, it should be `M_INVALID_REL_TYPE`):
```json
{"errcode":"M_UNKNOWN","error":"Relation type must be 'm.annotation'"}
```

I think the easiest solution is make rel_type mandatory.

2021-12-15 16:15 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +relation type and target event type):
> (perhaps you mean relating event type?)

I do indeed, fixed.

2021-12-15 16:32 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/v1/rooms/{roomID}/aggregations/{eventID}[/{relationType}][/{eventType}][?from=token][&to=token][&limit=amount]
Good point, I suspect it was originally added to mirror `/messages`. The only value I can think off is the `prev_batch` token from a previous invocation of this endpoint, but I don't really see how that is useful either.

I have removed the `to` query parameter and the `prev_batch` response field both for /aggregations and /relations.

2021-12-15 16:32 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  "prev_batch": "some_token"
Have removed this :+1:

2021-12-15 16:37 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +in the `m.relations` property of their unsigned data.  These are called
Also, I think the room summary added with lazy loading room members does something similar with the `m.heroes`, `m.invited_member_count` and `m.joined_member_count` fields. Not sure if those are different somehow or they have the same problem?

2021-12-15 16:38 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +
Wouldn't it be "Pagination of aggregations" given that bundling only happens on an event?

2021-12-15 16:49 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +(in line with `/sync` API).
Unsure what part is confusing, but possibly it stems from the misconception that aggregations and discrete relation events serve the same purpose for a client, the latter just being more verbose than the former?

If so, aggregations don't always provide all the information that a client could want from relations of a given type.
For example: the aggregation for `m.thread` will just provide some information about the thread (amount of messages, ...) but not all the messages. Receiving all these events up front when the thread head is synced but hasn't been expanded yet would be wasteful. Once the thread is expanded to show the messages, we use /relations. This is what is being alluded to in the above paragraph.

If that wasn't what confused you, could you elaborate?

2021-12-15 16:49 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  ],
have made rel_type mandatory

2021-12-15 16:50 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +GET /_matrix/client/v1/rooms/{roomID}/relations/{eventID}[/{relationType}[/{eventType}]][?from=token][&to=token][&limit=amount]
Indeed. Does `You can optionally filter by a given type of relation and event type` above not explain sufficiently?

2021-12-15 16:58 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +others might aggregate to a single object or any other value really.
Have added examples

2021-12-16 10:36 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +Aggregations are never bundled into state events.
In reply to https://github.com/matrix-org/matrix-doc/pull/2675#discussion_r769469674:

> > why not?
>
> Because synapse doesn't implement this, see  see https://github.com/matrix-org/matrix-doc/pull/2675#discussion_r760269297 . We're documenting the existing implementation(s), for better or worse.

I'm afraid the comment permalink doesn't work, but fair enough.

Could we have a sentence or footnote that records for future reference that this is a current implementation detail which could be revisited, rather than a specific design decision?

2021-12-16 10:36 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +in the `m.relations` property of their unsigned data.  These are called
>   That's reasonable, but can we please not do that here and stick to documenting usage in the ecosystem?

yes, fair.

> Also, I think the room summary added with lazy loading room members does something similar with the `m.heroes`, `m.invited_member_count` and `m.joined_member_count` fields. Not sure if those are different somehow or they have the same problem?

I wouldn't have chosen to use `m.` prefixes there, but at least they appear within a `summary` object where *all* the keys are namespaced. The thing that is particularly objectionable about `m.relations` is it means that a single object (`unsigned`) contains a *mix* of namespaced and unnamespaced identifiers.

2021-12-16 10:43 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +
well no, this section seems to be specifically talking about how the bundling process deals with the case that there are too many aggregations to bundle. Maybe `Limiting the size of bundled aggregations` is more accurate?

2021-12-16 10:43 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +paginate within each group using Matrix's defined pagination idiom of
> This MSC doesn't specify any values for `rel_type` in the relation, and hence no aggregation formats that are specific to the `rel_type`.

I'm afraid I don't understand this sentence, but maybe I don't need to.

If this stuff isn't happening yet, suggest you move it to the "Future extensions" section.

2021-12-16 10:47 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +
> There's also /relations though (which you pointed out feels slightly out of scope)

that might be a plausible argument if *all* the stuff about aggregations was under the "aggregations" heading, but it's really not.

2021-12-16 12:14 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +As clients only receive discrete relation events through `/sync`,
Agreed this is not clear, but AIUI, this is talking about how to deal with this scenario:

 - receive event through sync with 5 👍 reactions in the bundled aggregation
 - receive another 👍 m.reaction relation through sync for the previous event

The client should show a reaction count of 6, 5 from the aggregation and 1 of a relation it received through sync at a later point in time.

2021-12-16 12:16 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +As clients only receive discrete relation events through `/sync`,
I'll rewrite this paragraph and put it under a "Local aggregation" header.

2021-12-16 12:25 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +As clients only receive discrete relation events through `/sync`,
Have done this, let me know if it's clearer now.

2021-12-16 12:31 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +as a client might not be aware of all relations for an event. Local aggregation
Have rewritten this, lmk if it's more understandable now

2021-12-16 13:04 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +paginate within each group using Matrix's defined pagination idiom of
I've moved all the pagination bits (including /aggregations) to https://github.com/matrix-org/matrix-doc/pull/3571

2021-12-16 13:08 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +Aggregations are never bundled into state events.
Did this

2021-12-16 13:18 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +in the `m.relations` property of their unsigned data.  These are called
Have split this out into https://github.com/matrix-org/matrix-doc/pull/3572

2021-12-16 13:24 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +
> that might be a plausible argument if _all_ the stuff about aggregations was under the "aggregations" heading, but it's really not.

I've tried to make this so, and have restructured the headers to reflect this. Lmk if this works for you

2021-12-16 13:25 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +
I've moved any mention of pagination limiting the size to #3571

2021-12-16 14:01 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +(in line with `/sync` API).
> the misconception that aggregations and discrete relation events serve the same purpose for a client, the latter just being more verbose than the former?

Not quite the words you used, but my assumption/understanding is that, if it we had infinite bandwidth/processing power, we could give clients all the relations (allowing clients to maintain the reaction counts/keep track of threads themselves) and not bother with aggregations at all. The reason we have aggregations is that we do *not* have infinite bandwidth and processing power.  I hope that's correct.

The phrasing "we do not want to include them [relations] like we do for aggregations" implies to me that, even if we *did* include the relations, we would still *also* want to include the aggregations (which in turn implies that aggregations must contain extra data that can't be gleaned from the relations themselves).

2021-12-16 14:24 UTC, richvdh commented on proposals/2675-aggregations-server.md
>  just like described for the `/messages` endpoint.
my understanding (correct me if I'm wrong) is that in the case of `/relations`, the `from`,`to`,`next_batch` and `prev_batch` are pagination tokens as retuned by `/sync` and `/messages`, which means it does make sense to request the relations in a specific timeline window, as well as going forwards and backwards.

(which is to say, `/relations` works much more like `/messages` does than `/aggregations`).

If my understanding is correct, we should probably make it explicit that it's ok to use tokens returned by `/sync` and `/messages` here - but also you should probably reinstate `to` and `prev_batch`.

2021-12-16 14:24 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +Clients should ignore relation events for which the target event is
s/relation events/relating events/

2021-12-16 14:24 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +  ],
this doesn't appear to have happened: the URL still has `relationType` in square brackets, and the text says "you can optionally filter by a given type of relation and event type".

2021-12-16 14:24 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +account of the relation will suffer from the same limitation.
this new wording is much clearer. No need to include the whole rationale imho.

2021-12-16 14:30 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +account of the relation will suffer from the same limitation.
well, s/relation events/relating events/

2021-12-16 14:41 UTC, richvdh commented on proposals/2675-aggregations-server.md
> -GET /_matrix/client/v1/rooms/{room_id}/aggregations/{event_id}/{rel_type}[/{event_type}][?from=token][&limit=amount]
Hrm, I hadn't realised that getting rid of the pagination stuff from `m.relations` meant also getting rid of this. That's probably the right call, but given synapse implements it, we still either need to spec it, or commit to disabling it in synapse. Do you know if it's used anywhere?

2021-12-16 14:53 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +as a client might not be aware of all relations for an event. Local aggregation
yeah, definitely better now. thanks!

2021-12-16 14:53 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +As clients only receive discrete relation events through `/sync`,
definitely better now, thanks!

2021-12-16 14:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +
grumble. I'd say that "End to end encryption" and "Redactions" are also part of "aggregations", but it's better. thanks.

2021-12-16 14:57 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  ],
Won't the content include the relation type? This is iterating through events, so I see no reason it can't be optional?

2021-12-16 15:10 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +relation type and relation event type):
Hmm, I've actually been trying to use the term "relation event" consistently throughout the relation MSCs. In MSC2674 one occurrence must have slipped as it does mention "relating event" once, whereas it uses "relation event" twice. I'd also say "relating event" is only meaningful in the context of the target event, which _is_ the case here, so I went with relating here but perhaps not everywhere?

2021-12-16 15:13 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +not visible to them.
It was brought up by cl0pek as something that would be good to document. Would you be more comfortable if it said "can" rather than "should"?

2021-12-16 15:17 UTC, bwindels commented on proposals/2675-aggregations-server.md
>  just like described for the `/messages` endpoint.
Hmm, this is not my understanding. I understood it as:
 - to get the first page, you omit `from` but set a `limit`
 - use the `next_batch` token from the previous page to as the `from` parameter for the next request.

Hence I'd still think we don't need bidirectional pagination.

Perhaps @clokep can confirm this is how it is implemented? If it is, we should mention this explicitly.

2021-12-16 15:26 UTC, bwindels commented on proposals/2675-aggregations-server.md
>  just like described for the `/messages` endpoint.
Thanks, so seems my understanding was somewhat off. I'll apply Rich' suggestions then :+1:

2021-12-16 16:44 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +relation type and relation event type):
mmm ok, let's stick to "relation event". sorry for the noise!

2021-12-16 16:47 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +not visible to them.
yes. Or "In general, clients can safely ignore relation events where the target event is unknown to them." ?

2021-12-16 16:54 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +  ],
@clokep makes an excellent point.

(It would probably help if the `content` was fleshed out a bit more in the example).

so should `rel_type` be mandatory? it doesn't seem to be in synapse's implementation.

2021-12-16 16:58 UTC, richvdh reviewed
Still a couple of outstanding threads (https://github.com/matrix-org/matrix-doc/pull/2675/files#r768950693, https://github.com/matrix-org/matrix-doc/pull/2675/files#r768926538). Otherwise this is looking good to me.

@mscbot resolved visibility changes need to be descoped

2021-12-16 16:58 UTC, richvdh commented
@turt2live, @erikjohnston: this has changed substantially since your FCP ticks so I'm taking the liberty of removing your ticks.

2021-12-16 16:59 UTC, richvdh commented
@mscbot resolved visibility changes need to be descoped

2021-12-16 18:01 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  ],
I can't immediately think of a use-case for not providing it, but I don't see why it would be mandatory.

The only vague use-case I can think of is if you want to see all data that went into rendering of a single event, including all of those events which relate to it in any way. I'm not sure if that's something clients will actually do though.

2021-12-16 18:17 UTC, richvdh commented on proposals/2675-aggregations-server.md
> +  ],
in general I'd favour speccing what we *know* we need, and opening it up later if it turns out to be necessary, but I'm also in favour of speccing what's implemented, so if we chose to restrict it, I'd be keen that we change the synapse impl to require `rel_type`.

2021-12-16 18:53 UTC, clokep commented on proposals/2675-aggregations-server.md
> +  ],
I do plan to ensure Synapse implements what's in the MSC! 👍

2021-12-17 08:54 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +not visible to them.
Hmm, "unknown" seems a bit ambiguous. For example, when a client is backfilling, it will often first see the relations and then the target event. In this case, clients doing local aggregation will still need keep track of the relations somewhere for when they find the target event. Perhaps this is enough reason to remove this whole paragraph as it is not super clear how to distinguish between a target event that is invisible to you and one that you haven't backfilled yet. So will remove :+1:

2021-12-17 09:00 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +account of the relation will suffer from the same limitation.
Did this. :+1:

2021-12-17 09:03 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +  ],
Hmm, I'm also torn, but I think being able to fetch all the relations of an event feels like it's generally useful enough, so I'll make it optional again.

2021-12-17 09:06 UTC, bwindels commented
I have addressed the mentioned open threads.

2021-12-17 10:48 UTC, richvdh approved these changes

2021-12-17 10:53 UTC, richvdh commented
(removing needs-implementation here because this stuff is all used in element and synapse today)

2021-12-20 21:00 UTC, turt2live commented
if someone could track down the implementations and link them in the PR description, that'd be super amazing. It's hard to believe that this is implemented exactly as described without evidence.

2021-12-20 21:28 UTC, turt2live reviewed
generally looks fine to me - just a few concerns around clarity.

2021-12-20 21:28 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +this mechanism are called "bundled aggregations".
This isn't drawing a clear enough picture, I think. Can we get a worked example of bundling?

The example later on is also not entirely clear. Removing hypotheticals and relying on non-normative examples would be best.

2021-12-20 21:28 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +The endpoint does not have any trailing slashes.
Can it be rate limited? Does it require authentication?

2021-12-20 21:28 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +common case for rapidly fixing a typo in a msg which is still in flight!)
this feels like its in the wrong proposal

2021-12-20 21:28 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +need to be set the newly received `event_id`.
I think this is covered by https://spec.matrix.org/v1.1/client-server-api/#local-echo ?

2021-12-20 21:28 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +[MSC2836](https://github.com/matrix-org/matrix-doc/blob/kegan/msc/threading/proposals/2836-threading.md#making-relationships) also makes mention of this issue.
ideally we link to the github PR rather than the rendered file as the branch name is ephemeral

2021-12-20 21:28 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +to what is implemented at the time of writing.
https://github.com/matrix-org/matrix-doc/pull/3523 😇

2021-12-20 21:28 UTC, turt2live commented
@mscbot concern lacking implementation validation
@mscbot concern general clarity - TR review

2021-12-21 12:38 UTC, clokep commented
> if someone could track down the implementations and link them in the PR description, that'd be super amazing. It's hard to believe that this is implemented exactly as described without evidence.

I linked to the relevant bits of the Synapse implementation (the new endpoint and how the bundled aggregations get included).

2021-12-21 15:23 UTC, turt2live commented
Thanks! Looks to be vaguely enough to compare against.

@mscbot resolve lacking implementation validation

2021-12-21 16:28 UTC, uhoreg reviewed
Looks mostly good, modulo Travis' comments.  I just have some nitpicky changes to offer.

2021-12-21 16:28 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +in the relation and aggregate to an array,
```suggestion
in the relation and aggregate to an array, while
```

2021-12-21 16:28 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +Bundled aggregations on an event give a snapshot of what relations were know
```suggestion
Bundled aggregations on an event give a snapshot of what relations were known
```

2021-12-21 16:28 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +   (or using edits as a side-channel to harass you). Therefor, it is possible
```suggestion
   (or using edits as a side-channel to harass you). Therefore, it is possible
```

2021-12-21 16:28 UTC, uhoreg commented on proposals/2675-aggregations-server.md
> +or has not joined the room. This can cause a user to see an incomplete edit history or reaction count
```suggestion
or have not joined the room. This can cause a user to see an incomplete edit history or reaction count
```

2022-01-04 21:43 UTC, ara4n commented on proposals/2675-aggregations-server.md
> +[MSC2836](https://github.com/matrix-org/matrix-doc/blob/kegan/msc/threading/proposals/2836-threading.md#making-relationships) also makes mention of this issue.
```suggestion
[MSC2836](https://github.com/matrix-org/matrix-doc/pull/2836) provided a proposal for following relationships over federation in the "Querying relationships over federation" section via a `/_matrix/federation/v1/event_relationships` API
```

2022-01-07 16:11 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +The endpoint does not have any trailing slashes.
Have added this

2022-01-10 12:58 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +this mechanism are called "bundled aggregations".
Have tried to addres this in https://github.com/matrix-org/matrix-doc/pull/2675/commits/be6b1c7c8ebff157583a77e2f82d7d23cf3ccaaf

2022-01-10 14:04 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +common case for rapidly fixing a typo in a msg which is still in flight!)
Have removed this and added a comment on #2676 to add it there.

2022-01-10 14:17 UTC, anoadragon453 commented
@turt2live I see you removed the `unresolved-concerns` label, but you still have one outstanding concern on this MSC. Is that intentional?

2022-01-10 14:32 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +need to be set the newly received `event_id`.
Have removed the duplication and tried to keep it specifically to relating relations to their target before the latter is sent.

2022-01-10 14:34 UTC, bwindels commented on proposals/2675-aggregations-server.md
> +to what is implemented at the time of writing.
Can you formulate this into a suggestion or question please? :pray:

2022-01-10 20:57 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +to what is implemented at the time of writing.
This probably doesn't need explicit inclusion - the links between the MSCs are formed by the comment and should be good enough.

2022-01-10 20:58 UTC, turt2live commented
oops, thought I didn't hold that concern as blocking, sorry.

@mscbot resolve general clarity - TR review

2022-01-15 22:07 UTC, merged

2022-03-25 12:35 UTC, revidee commented
So regarding [Handling limited (gappy) syncs](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2675-aggregations-server.md#handling-limited-gappy-syncs): I couldn't find any MSC Proposal handling this, is there any?

IMHO, this is the most important part, since for example:
If we received and event via sync, which may has annotations bundled into it and keep it up-to-date via local aggregation using all future `m.relates_to` events, but then go offline for a day and come back, without syncing _all_ events in-between, we end up in an incorrect state for the local aggregations of the already received event.

If we would simply use a locally cached copy of the locally aggregated event, it would not match a refreshed version from the server. Thus, in this situation, we can't really trust any local copies of events, except we query all relational events, that happened in-between. This would make "jumping back" to the locally saved event somewhat incorrect (mismatches a fresh copy from the server). And refreshing all locally saved events would diminish any possible traffic savings gained by local caching.

Only case I see in which we could realistically save traffic is an initial sync, with filters enabled to not fetch all m.annotation / ... / events, but include then in consecutive `/sync` calls. Other than that, this makes locally caching/saving events, in order to not re-query them, a step harder, since we have to be really careful to keep all the local events in sync & up-to-date.

This problem is (imho) rather drastic in bigger rooms with large amounts of daily traffic. When loading older messages we may end up loading batches upon batches of events filled with relational events only until we load a real m.text message that the client could display. (e.g. if many reactions have happened) But we cannot exclude them, if we choose to locally aggregate already received events, since we might miss some otherwise.

In that light, it almost seems more logical and traffic-saving to discard local copies all together in order to take advantage of aggregations and bundling. In that case, we can always apply a filter for the events received in `/sync` and can be sure that the data received is up-to-date. (after loading/paginating through the `/aggregations` endpoint if there is a `next_batch` present)


Am I missing something obvious here, or am I correct that making local copies in combination with this MSC seems like a pain?

2022-03-25 14:46 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +# MSC2675: Serverside aggregations of message relationships
@revidee says:

> So regarding [Handling limited (gappy) syncs](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2675-aggregations-server.md#handling-limited-gappy-syncs): I couldn't find any MSC Proposal handling this, is there any?
> 
> IMHO, this is the most important part, since for example:
If we received and event via sync, which may has annotations bundled into it and keep it up-to-date via local aggregation using all future `m.relates_to` events, but then go offline for a day and come back, without syncing _all_ events in-between, we end up in an incorrect state for the local aggregations of the already received event.
> 
> If we would simply use a locally cached copy of the locally aggregated event, it would not match a refreshed version from the server. Thus, in this situation, we can't really trust any local copies of events, except we query all relational events, that happened in-between. This would make "jumping back" to the locally saved event somewhat incorrect (mismatches a fresh copy from the server). And refreshing all locally saved events would diminish any possible traffic savings gained by local caching.
> 
> Only case I see in which we could realistically save traffic is an initial sync, with filters enabled to not fetch all m.annotation / ... / events, but include then in consecutive `/sync` calls. Other than that, this makes locally caching/saving events, in order to not re-query them, a step harder, since we have to be really careful to keep all the local events in sync & up-to-date.
> 
> This problem is (imho) rather drastic in bigger rooms with large amounts of daily traffic. When loading older messages we may end up loading batches upon batches of events filled with relational events only until we load a real m.text message that the client could display. (e.g. if many reactions have happened) But we cannot exclude them, if we choose to locally aggregate already received events, since we might miss some otherwise.
> 
> In that light, it almost seems more logical and traffic-saving to discard local copies all together in order to take advantage of aggregations and bundling. In that case, we can always apply a filter for the events received in `/sync` and can be sure that the data received is up-to-date. (after loading/paginating through the `/aggregations` endpoint if there is a `next_batch` present)
> 
> 
> Am I missing something obvious here, or am I correct that making local copies in combination with this MSC seems like a pain?

2022-04-06 14:33 UTC, clokep commented on proposals/2675-aggregations-server.md
> +# MSC2675: Serverside aggregations of message relationships
> So regarding [Handling limited (gappy) syncs](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/2675-aggregations-server.md#handling-limited-gappy-syncs): I couldn't find any MSC Proposal handling this, is there any?

Correct, there is currently not MSC which proposes this behavior.

> IMHO, this is the most important part, since for example:
If we received and event via sync, which may has annotations bundled into it and keep it up-to-date via local aggregation using all future `m.relates_to` events, but then go offline for a day and come back, without syncing _all_ events in-between, we end up in an incorrect state for the local aggregations of the already received event.

Correct, the local client might not know some of the related messages without filling the entire gap. (Note that I don't think this is any different than if *only* local aggregation was done -- so I'm unsure if this MSC really changes that behavior.)

> If we would simply use a locally cached copy of the locally aggregated event, it would not match a refreshed version from the server. Thus, in this situation, we can't really trust any local copies of events, except we query all relational events, that happened in-between. This would make "jumping back" to the locally saved event somewhat incorrect (mismatches a fresh copy from the server). And refreshing all locally saved events would diminish any possible traffic savings gained by local caching.

I think this is pretty much what the gappy syncs issue in the MSC describes. I'm unsure what current clients do -- @gsouquet do you know if Element Web does anything special in this case?

> Only case I see in which we could realistically save traffic is an initial sync, with filters enabled to not fetch all m.annotation / ... / events, but include then in consecutive `/sync` calls. Other than that, this makes locally caching/saving events, in order to not re-query them, a step harder, since we have to be really careful to keep all the local events in sync & up-to-date.

This might work, but I doubt the savings in traffic would be the tremendous, unless the majority of your events are annotations, specifically. (I think you would still want to fetch references / edits / threads since the aggregation of those somewhat assumes you're going to fetch the full event anyway).

> In that light, it almost seems more logical and traffic-saving to discard local copies all together in order to take advantage of aggregations and bundling. In that case, we can always apply a filter for the events received in `/sync` and can be sure that the data received is up-to-date. (after loading/paginating through the `/aggregations` endpoint if there is a `next_batch` present)

Note that the `/aggregations` endpoint was removed from this MSC (and from Synapse). [MSC3571](https://github.com/matrix-org/matrix-spec-proposals/pull/3571) includes the bits split out of MSC2675.

> Am I missing something obvious here, or am I correct that making local copies in combination with this MSC seems like a pain?

I don't think you're missing anything obvious, but maybe @gsouquet has some ideas of how the clients deal with this.

2022-04-09 18:00 UTC, alphapapa commented
@ara4n @turt2live  I guess it's pointless to comment here since the proposal has been merged, but I feel like chiming in, as a client developer:

I've been reluctant to implement anything not yet in a released version of the spec, but in my client I did implement support for reaction annotations, since they're so widely used in Element and other clients already.  But now I'm seeing my client not render annotations in some cases, which I've found is because the server is now aggregating some of them.

I understand the motivations for this proposal, but at the same time, it increases the complexity of developing clients: rather than simply handling each reaction annotation event, a client must handle both aggregated reaction annotations and individual reaction annotation events.  This means that, when an individual event comes in, I have to emulate the server-side aggregation in my client, adding it to the annotated event's unsigned data myself, so that I can still have a single path for rendering an event.

Fundamentally, this means that a single logical action (reacting to a message) may now be represented in a room's timeline in two different ways: as individual events, or as aggregations of metadata on the annotated event.  So this does not seem to make it easier for clients, but rather, more complicated.

I feel like Matrix would do well to emulate the Zen of Python: there should be one, and preferably only one, way to represent a logical event in a room's timeline.  This would greatly simplify implementations on both clients and servers, which would do much to help ensure Matrix's adoption and longevity.

My two cents.  Thanks.

2022-04-09 18:42 UTC, turt2live commented on proposals/2675-aggregations-server.md
> +# MSC2675: Serverside aggregations of message relationships
@alphapapa says:

> @ara4n @turt2live  I guess it's pointless to comment here since the proposal has been merged, but I feel like chiming in, as a client developer:
> 
> I've been reluctant to implement anything not yet in a released version of the spec, but in my client I did implement support for reaction annotations, since they're so widely used in Element and other clients already.  But now I'm seeing my client not render annotations in some cases, which I've found is because the server is now aggregating some of them.
> 
> I understand the motivations for this proposal, but at the same time, it increases the complexity of developing clients: rather than simply handling each reaction annotation event, a client must handle both aggregated reaction annotations and individual reaction annotation events.  This means that, when an individual event comes in, I have to emulate the server-side aggregation in my client, adding it to the annotated event's unsigned data myself, so that I can still have a single path for rendering an event.
> 
> Fundamentally, this means that a single logical action (reacting to a message) may now be represented in a room's timeline in two different ways: as individual events, or as aggregations of metadata on the annotated event.  So this does not seem to make it easier for clients, but rather, more complicated.
> 
> I feel like Matrix would do well to emulate the Zen of Python: there should be one, and preferably only one, way to represent a logical event in a room's timeline.  This would greatly simplify implementations on both clients and servers, which would do much to help ensure Matrix's adoption and longevity.
> 
> My two cents.  Thanks.

2022-05-27 03:31 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1062

2022-06-08 21:33 UTC, turt2live commented
Merged 🎉