MSCxxxx: Message editing
matrix-org/matrix-doc pull request #2676
Opened 2020-07-07 20:21 UTC by uhoreg

2020-07-07 21:28 UTC, uhoreg reviewed
Transfer comments from 1849

2020-07-07 21:28 UTC, uhoreg commented on proposals/2676-message-editing.md
> +redacted message on receiving a redaction.
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r361335488:

tulir says:

> This also makes little sense. Why is redacting only the original revision not allowed? Trusting clients like that is also bad, fully redacting an edited message really has to redact all the edits as well.
> 
> With mass redactions, removing all the revisions at once is easy, so why not just define that fully redacting an edited message requires redacting every revision? (and that redacting the original message only redacts the original revision)

deepbluev7 says:

> I just hit that. Someone redacted their message, but I could still read their message, because my client doesn't support edits yet. And even in Riot, I can still view that message by enabling hidden events. This is not, what you want.
> 
> By default, you want to redact all edits of a message. The only use case, where you don't want that, is when you had sensitive info in the message before the edit, but that is not what the above statement seems to try to support!

2020-07-07 21:28 UTC, uhoreg commented on proposals/2676-message-editing.md
> +What power level do you need to be able to edit other people's messages, and how
In the thread at https://github.com/matrix-org/matrix-doc/pull/1849/files#r291955122:

jryans says:

> We should try to define in more detail who is allowed to edit and also how C-S APIs should behave for a disallowed edit. Currently, Synapse [behaves inconsistently](https://github.com/matrix-org/synapse/issues/5364) accepting edits into the timeline from anyone, but filtering them out of the bundled data.

ara4n says:

> agreed. can someone (erikjohnston) do so? i don't have strong thoughts on this.

2020-11-21 19:58 UTC, erdnaxeli commented on proposals/2676-message-editing.md
> +}
This JSON is actually invalid.

```suggestion
{
    "type": "m.room.message",
    "content": {
        "body": "s/foo/bar/",
        "msgtype": "m.text",
        "m.new_content": {
            "body": "Hello! My name is bar",
            "msgtype": "m.text"
        },
        "m.relates_to": {
            "rel_type": "m.replace",
            "event_id": "$some_event_id"
        }
    }
}
```

2020-11-25 16:40 UTC, jplatte commented on proposals/2676-message-editing.md
> +            "msgtype": "m.text"
Why is the `msgtype` duplicated in `m.new_content`? Is an edit allowed to change the message type?

2020-11-25 16:50 UTC, erdnaxeli commented on proposals/2676-message-editing.md
> +            "msgtype": "m.text"
Yes. You can try by forging an event, element web handle it correctly (but the edit history is then broken).

2020-11-25 16:59 UTC, jplatte commented on proposals/2676-message-editing.md
> +            "msgtype": "m.text"
Element Web currently handling it isn't a very good motivation IMO. If there isn't any reasoning behind this, I'd rather not have it in the spec (it's extra work for client implementors afterall).

2020-11-25 16:59 UTC, jplatte commented on proposals/2676-message-editing.md
> +            "msgtype": "m.text"
I guess I should have asked: *Should* edits be allowed to change the message type?

2020-11-25 22:54 UTC, uhoreg commented on proposals/2676-message-editing.md
> +            "msgtype": "m.text"
One use case is to allow `m.text` to change to `m.emote` or vice versa.  For example, if someone typos a `/me` command such that it isn't initially recognized as a `/me` command.  Or if someone sends an emote when they actually wanted to send a message starting with `/me`.

Another possibility is to change between `m.file`/`m.image`/`m.audio`/`m.video` if, for example, you upload the wrong file initially, which is a different type from the file you intended to upload, and you edit the event with the correct file.  (I don't know if any clients currently allow editing of media events.)

2020-11-26 10:44 UTC, jplatte commented on proposals/2676-message-editing.md
> +            "msgtype": "m.text"
Okay, makes sense. I think it would be good if these use cases were mentioned in the MSC.

2020-12-31 15:38 UTC, Sorunome commented on proposals/2676-message-editing.md
> +What power level do you need to be able to edit other people's messages, and how
Depending on what gets decided for event aggregations in e2ee rooms it'll be impossible for the server to tell which events are edits, so the client is required to validate this, then.

2021-01-21 21:51 UTC, ognarb commented on proposals/2676-message-editing.md
> +            "body": "Hello! My name is bar",
It would be good to specify somewhere in this MSC that `formatted_body` can also be specified.

2021-06-09 10:36 UTC, deepbluev7 commented on proposals/2676-message-editing.md
> +
I think I need some clarification around how the `m.new_content` is supposed to work, since it seems I implemented it wrong:

Am I supposed to replace `content` unconditionally with `m.new_content` or am I supposed to copy keys over one by one? I thought I had to do the latter, because I didn't want to overwrite the relations and such, but in practice Element seems to do it differently, which leads to interesting edge cases like:

```
"content": {
    "m.new_content": {
        "msgtype": "m.text",
        "body": "Dawn of the second day\n- 48 hours remain -"
    },
    "msgtype": "m.text",
    "body": " * /plain Dawn of the second day\n- 48 hours remain -",
    "format": "org.matrix.custom.html",
    "formatted_body": " * <p>/plain Dawn of the second day</p>\n<ul>\n<li>48 hours remain -</li>\n</ul>\n"
},
```

That event obviously renders differently. But if new_content contained a relation, we obviously wouldn't want to override our relation in the root event... So the algorithm looks like:

1. Backup `content/m.relates_to`
2. replace `content` with `content/m.new_content`
3. copy backup of the relation back into `content`

Is that correct?

2021-07-23 13:52 UTC, t3chguy commented on proposals/2676-message-editing.md
> + * The edited reply should ditch the fallback representation of the reply itself
This should probably be `must` to match the de-facto standard from the Element Web & Element Desktop implementations (probably more too)

2021-07-26 21:51 UTC, uhoreg commented on proposals/2676-message-editing.md
> + * The edited reply should ditch the fallback representation of the reply itself
@t3chguy does this mean that the ["XXX" comment below](https://github.com/matrix-org/matrix-doc/pull/2676/files#diff-1761bdadd1caacb2503d2b2e6c572fc628c7321b0beab8d502ac249c15b2826aR122) can be removed?

2021-07-26 21:52 UTC, t3chguy commented on proposals/2676-message-editing.md
> + * The edited reply should ditch the fallback representation of the reply itself
Well, Android definitely doesn't adhere to that, but should and has an open issue to do so

2021-07-26 22:18 UTC, uhoreg commented on proposals/2676-message-editing.md
> + * The edited reply should ditch the fallback representation of the reply itself
OK, I think we can remove that comment then.  From a spec perspective, that comment is only relevant as far as determining whether an implementation exists.  If Element Web/Desktop implements it, then we don't have to worry about it on the spec side, and since there's an open issue on the Element Android side, it isn't something we need to track here.

2021-11-22 15:18 UTC, richvdh commented on proposals/2676-message-editing.md
> + * We just send an m.replace which refers to the m.reference target; nothing
is `m.reference` a typo? AIUI that is used for e2e verification events (https://spec.matrix.org/v1.1/client-server-api/#device-verification etc)?

2021-11-22 15:21 UTC, deepbluev7 commented on proposals/2676-message-editing.md
> + * We just send an m.replace which refers to the m.reference target; nothing
It is a left over of when the original relations MSC proposed to replace replies with m.reference, I think.

2021-11-26 10:33 UTC, bwindels commented
We should add this:

Note that for `m.replace` relations, the server should put the related-to event in
a `original_event` property of the response. This way the full history
(e.g. also the first, original event) of the event is obtained
without further requests.

2021-11-26 10:42 UTC, bwindels commented
Also, richvdh mentioned this on #2675 which really belongs here:

Note that, per matrix-org/synapse#10310, Synapse currently replaces the original event with the edit even when you call /event directly on the original. I'm pretty sure that's incorrect behaviour, but it would be great if the MSC could call out exactly which endpoints should return the original, and which should return the edited version.

2021-11-26 15:36 UTC, ShadowJonathan commented on proposals/2676-message-editing.md
> +# MSC2676: Message editing
@bwindels said:

> Synapse currently replaces the original event with the edit even when you call /event directly on the original. I'm pretty sure that's incorrect behaviour.

I concur that this it incorrect behaviour, something I expect to be able to do is see edit history, including the original event.

However, I see where this requirement comes from, and maybe something could/should be done to refer to the fact the event has been replaced when /event is called.

I know this is relation aggregation, but a hint that the client has to take in mind could help with "what-if" scenarios it has to figure out, and if it isn't included, it could lead to bad UX (events flickering between old and new states, slow event loading in general, etc.)

2021-11-30 10:08 UTC, bwindels commented
The CS API should not allow to send a relation targetting a `m.replace` event, as discussed at https://github.com/matrix-org/matrix-doc/pull/2675#discussion_r757010873

2021-12-01 15:58 UTC, chagai95 commented
I'd like to see admins able to edit messages in the future.

2021-12-01 19:06 UTC, anoadragon453 commented
@chagai95 please leave suggestions in a pull request review on a relevant line, or (canonically) the first line of the proposal if it doesn't fit anywhere else. This is so that each individual thread of discussion can be resolved and minimised as the proposal evolves :slightly_smiling_face: 

Additionally, note that there is already an existing thread talking about users editing other user's messages: https://github.com/matrix-org/matrix-doc/pull/2676#discussion_r451153640. It would be best to leave additions that further the conversation there.

2021-12-03 08:35 UTC, MadLittleMods commented on proposals/2676-message-editing.md
> + * We do not recommend that native Matrix clients expose this as a feature.
Not validating edits on the homeserver causes edits to be a super easy foot gun for anyone writing a client or application-service. Someone can exploit this and edit anyone's message if you implement edits naively and expect the homeserver to validate edits like you can for redactions. We have first-hand experience of getting this wrong this in all of the Element clients 🥴

When exploitable, for native Matrix clients, it's most likely just a display problem since fixing the exploit on the client, results in the errant edit event being ignored and the original event shows up again or maybe even not a problem at all because Synapse filters them out of bundled data (not sure on exact Synapse details). **But for bridges (application services) it can be a much bigger problem!** Those edit events are not filtered out and get sent straight to the application service via `/transactions`. When someone naively relies on edit events to be correctly permissible against the room, those events get accidentally processed by the bridge and the information is persisted and overwritten in the 3rd party service.

Validating edits to other peoples messages with a power-level like redactions is a pretty good way forward though ⏩

https://github.com/matrix-org/synapse/issues/5364 tracks the same problem space on Synapse

2022-01-10 13:00 UTC, bwindels commented
Transferring from MSC 2675, mention this for local echo:
> Particularly, please remember to let users edit unsent messages (as this is a
common case for rapidly fixing a typo in a msg which is still in flight!)

2022-01-14 03:51 UTC, turt2live commented on proposals/2676-message-editing.md
> +# MSC2676: Message editing
ftr, I am assuming at this point this MSC will end up targeting present day implementation for historical reasons. Other MSCs can improve upon the system.

2022-01-14 04:24 UTC, turt2live commented on proposals/2676-message-editing.md
> +## Proposal
Apologies if it is mentioned somewhere, but it'd be good to get explicit clarity on how the replacement effect works: is it just `m.new_content` overriding `content`, or can the event lose its `type`, `unsigned`, etc in favour of the updated event?

2022-02-01 11:55 UTC, dkasak commented on proposals/2676-message-editing.md
> +redacted message on receiving a redaction.
So... Can we just specify that all edits of a message should be redacted as well? I don't see a downside and it seems like the only sane way of handling this.

2022-02-01 15:39 UTC, deepbluev7 commented on proposals/2676-message-editing.md
> +redacted message on receiving a redaction.
The downside is that the relation goes missing and so you now have multiple redactions in your timeline. But that is a price I am willing to pay for actually redacting stuff, that should be redacted.

2022-02-01 15:57 UTC, dkasak commented on proposals/2676-message-editing.md
> +redacted message on receiving a redaction.
Ah, right. In principle, we could change the semantics of redaction so that it doesn't remove the arrows (i.e. the `m.relates_to` field), which might even be sensible...

2022-02-01 16:26 UTC, clokep commented on proposals/2676-message-editing.md
> +redacted message on receiving a redaction.
[MSC3389](https://github.com/matrix-org/matrix-doc/pull/3389) discusses updating the redaction rules. I think they're somewhat unrelated problems, but ideally both need to be solved for the best user experience.

2022-02-11 16:38 UTC, clokep commented on proposals/2676-message-editing.md
> +redacted message on receiving a redaction.
> So... Can we just specify that all edits of a message should be redacted as well? I don't see a downside and it seems like the only sane way of handling this.

Synapse [seems to have a test](https://github.com/matrix-org/synapse/blob/4d7e74b2e503373da66ec929afd1aa7010676878/tests/rest/client/test_relations.py#L1176-L1179) for this, kind of. The test says:

> Test that edits of an event are redacted when the original event is redacted.

But the actual test only ensures you can't call `/relations` on the endpoint. I'm not sure if it is internally redacted or not though.

2022-03-15 17:24 UTC, clokep commented on proposals/2676-message-editing.md
> + * We can't change relation types either.
Synapse limits what it will aggregate to `m.room.message` events currently, unclear if this is a bug or not.

2022-03-15 17:28 UTC, clokep commented on proposals/2676-message-editing.md
> +The `m.new_content` includes any fields that would normally be found in an
This could use an example of what to do when trying to edit an encrypted event. I can see two ways of the content for the edit:

```json
{
  "m.new_content": {"algorithm": ..., "ciphertext": ..., ...},
  "m.relates_to": {"event_id": ..., "rel_type": "m.replace"}
}
```

Or (this is what I've observed in the wild):

```json
{
  "algorithm": ..., "ciphertext": ..., ...,
  "m.relates_to": {"event_id": ..., "rel_type": "m.replace"}
}
```

Where the ciphertext, once decrypted includes the plaintext fields to replace.

Note that the server cannot help at all in the second case since there's no "new content" visible to it (since it is part of the encrypted ciphertext).

2022-03-16 09:00 UTC, Anderas commented on proposals/2676-message-editing.md
> +The `m.new_content` includes any fields that would normally be found in an
This choice will have consequences for an initial client-side sync: if the server cannot aggregate edits for old encrypted events (i.e. `ciphertext` is always the same for an event before and after an edit), the client will not be able to display the edited message, unless it itterates through all future events and does the aggregation locally.

A prefereble solution would be the one already used for unencrypted rooms, where `content.body` of an unencrypted message always contains the most recent edit of the text. If I understand the above correctly, choosing `"m.new_content": {"algorithm": ..., "ciphertext": ..., ...}` for encrypted messages would allow keeping the `cipertext` of an edited event up-to-date as well.

2022-03-16 10:47 UTC, dkasak commented on proposals/2676-message-editing.md
> +The `m.new_content` includes any fields that would normally be found in an
Note that the choice we make here will have consequences for [encrypted message relationships](https://github.com/matrix-org/matrix-spec/issues/660). I'm wary of exposing even more stuff in the plaintext.

It seems to me that the ability for the server to return the set of all related events of some event is enough. The server doesn't need to perform the aggregation operation on the set itself. This can be done client-side as long as the client is able to retrieve all related events easily.

2022-03-23 18:26 UTC, clokep commented on proposals/2676-message-editing.md
> + * We can't change relation types either.
@t3chguy and I were discussing this and it seems that in some situations in encrypted rooms (pretty much any time that the client might not have a full timeline, e.g. when forward paginating or looking at threads) this causes a major issue as the client has to essentially assume all events might have edits and individually query for them.

I suspect we should be aggregating any type of event so we at least include the information about the edit event. What to do about `new_content` is a separate question probably best handled at https://github.com/matrix-org/matrix-spec-proposals/pull/2676/files#r784498672

2022-04-12 15:43 UTC, richvdh commented on proposals/2676-message-editing.md
> +
Yes, that's correct. You can see synapse's impl at https://github.com/matrix-org/synapse/blob/v1.55.0/synapse/events/utils.py#L443.

I've attempted to clarify this in [1de6c11](https://github.com/uhoreg/matrix-doc/commit/1de6c11026b7eb1e48f606a4067fea4ec8d52495).

2022-04-12 17:25 UTC, richvdh commented on proposals/2676-message-editing.md
> +# MSC2676: Message editing
made this clear in adcdddc16

2022-04-12 18:53 UTC, richvdh commented on proposals/2676-message-editing.md
> +# MSC2676: Message editing
The synapse bug here is https://github.com/matrix-org/synapse/issues/10310. I've made the *expected* behaviour explicit in fc2a6908ae. I think this thread is resolved.

2022-04-19 18:00 UTC, richvdh commented on proposals/2676-message-editing.md
> + * We can't change relation types either.
Filed as https://github.com/matrix-org/synapse/issues/12503

2022-04-19 21:02 UTC, richvdh commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
I've opened https://github.com/vector-im/element-web/issues/21851 about this: eleweb shows attempts to edit state events as successful.

2022-04-20 10:24 UTC, andybalaam commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
Hmm. We have been using the idea of editing state events in our implementation of live location sharing, not realising it was prohibited. cc @ara4n @kerryarchibald @Johennes

2022-04-20 11:18 UTC, richvdh commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
I've got to say, at this point that sounds like a problem with your implementation of location sharing :-p

2022-04-20 11:25 UTC, t3chguy commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
Blocked the EW PR until this the MSC confirms what can & cannot be edited

2022-04-20 12:51 UTC, andybalaam commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
> I've got to say, at this point that sounds like a problem with your implementation of location sharing :-p

:-) On the other hand, this MSC is intended to document current usage, so maybe we slipped in under the wire?

2022-04-20 12:56 UTC, andybalaam commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
Where it makes sense (potentially, to me) to edit a state event is when it has meaning both as something that happened at a particular time, as well as something that modifies room state. `m.call` ([MSC3401](https://github.com/matrix-org/matrix-spec-proposals/pull/3401)) is a good example of this, as is `m.beacon_info` ([MSC3489](https://github.com/matrix-org/matrix-spec-proposals/pull/3489)). In both these cases, the original event is referenced by future events, so it helps if the original event's ID remains the relevant one, even if it is later altered. In the case of live location sharing, we are editing the original sharing event (`m.beacon_info`) to say that it is no longer live.

2022-04-20 14:50 UTC, andybalaam commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
We discussed via DM.

Yes, the problem is related to editing state events.
No, the point does not cover referring to state events.
The distinction is that editing state events modifies room state whereas referring to state events does not.

2022-04-20 14:53 UTC, richvdh commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
Andy and I took this offline, but a summary of the conversation is:

I'm specifically referring to *editing* state events. I have no concerns about other relations.

2022-04-21 08:33 UTC, andybalaam commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
I have been persuaded that editing state events is a Bad Idea, so withdraw my objections to this section of the MSC.

2022-05-17 17:57 UTC, richvdh commented on proposals/2676-message-editing.md
> +What power level do you need to be able to edit other people's messages, and how
Hopefully now clarified at https://github.com/uhoreg/matrix-doc/blob/aggregations-edits/proposals/2676-message-editing.md#validity-of-message-edit-events in bb96694.

2022-05-17 17:58 UTC, richvdh commented on proposals/2676-message-editing.md
> +What power level do you need to be able to edit other people's messages, and how
Yes, it's up to the client to validate edits of encrypted events. Hopefully this is now clear.

2022-05-17 18:08 UTC, richvdh commented on proposals/2676-message-editing.md
> + * The edited reply should ditch the fallback representation of the reply itself
The "XXX comment" went away in 634dc2e, and hopefully the intention is now clear.

2022-05-17 18:10 UTC, richvdh commented on proposals/2676-message-editing.md
> + * The edited reply should ditch the fallback representation of the reply itself
The "XXX comment" went away in 634dc2e, and hopefully the intention is now clear.

I'm not sure which issue @t3chguy is referring to here (possibly https://github.com/vector-im/element-android/issues/2448?), but it seems like replies in element-android are generally known to be broken anyway (see https://github.com/vector-im/element-android/issues/3731).

2022-05-17 18:11 UTC, richvdh commented on proposals/2676-message-editing.md
> + * We just send an m.replace which refers to the m.reference target; nothing
yup. Clarified now, thanks.

2022-05-17 18:13 UTC, richvdh commented on proposals/2676-message-editing.md
> + * We do not recommend that native Matrix clients expose this as a feature.
I've attempted to call out the dangers of trusting the edit events. For now, that's the framework we need to work within. If that's unworkable, it's going to need another round of changes to implementations and spec, so it's out of scope here.

2022-05-17 18:15 UTC, richvdh commented on proposals/2676-message-editing.md
> +The `m.new_content` includes any fields that would normally be found in an
We don't really have a choice here - we have to follow what's been implemented in the wild for the last three years, as the introduction to this MSC makes clear.

https://github.com/uhoreg/matrix-doc/blob/aggregations-edits/proposals/2676-message-editing.md#encrypted-events attempts to clarify what an encrypted edit would look like.

2022-05-17 18:16 UTC, richvdh commented on proposals/2676-message-editing.md
> + * Only non-state events for now.
The MSC now makes clear that state events may not be edited.

2022-05-17 18:16 UTC, richvdh commented on proposals/2676-message-editing.md
> +## Proposal
This is now spelt out in https://github.com/uhoreg/matrix-doc/blob/aggregations-edits/proposals/2676-message-editing.md#applying-mnew_content.

2022-05-17 18:18 UTC, richvdh commented
Right, I think this is complete.

@mscbot fcp merge

2022-05-17 18:25 UTC, richvdh commented
This is based on my research of what synapse and Element do in practice (modulo minor bugs such as https://github.com/matrix-org/synapse/issues/12503), so I'm going to remove the "needs-implementation" label.

2022-05-17 18:33 UTC, MadLittleMods commented on proposals/2676-message-editing.md
> + * We do not recommend that native Matrix clients expose this as a feature.
I see a note where "Client authors are reminded to take note of the requirements for [Validity of message edit events](#validity-of-message-edit-events), and to ignore any invalid edit events that may be received." But this doesn't really call out any danger. It's such a subtle note pointing you to a list of ways you can get it wrong.

It seems like we should at least plainly point out these examples out in the security considerations section to explain what can happen.

And maybe a note about a future consideration to have it under a power-level.

2022-05-17 18:37 UTC, MadLittleMods commented on proposals/2676-message-editing.md
> +   which expects only one relationship per event.
This does work in Element, https://github.com/vector-im/element-web/issues/10391#issuecomment-919531983 but instead put the `m.relates_to -> m.in_reply_to` in the `m.new_content`

2022-05-17 18:41 UTC, MadLittleMods commented on proposals/2676-message-editing.md
> +   which expects only one relationship per event.
Although I guess it shouldn't work according to the *Applying `m.new_content`* section

2022-05-17 18:47 UTC, deepbluev7 commented on proposals/2676-message-editing.md
> +which is left *unchanged*. For example, given a pair of events:
What happens if m.new_content contains an `m.relates_to`? Should clients interpret that or not? Element used to do that, but then horribly broke, if the relation was a reply relation to the original event, but worked fine if it referred to another event. But that was removed sometime between 1.10.1 and 1.10.12.

Basically should that:

- be ignored
- interpreted as if it was the original relation
- The MSC says nothing about that and some MSC in the future should clear that up

The current statement somewhat reads like 1. maybe?

2022-05-17 20:40 UTC, richvdh commented on proposals/2676-message-editing.md
> +which is left *unchanged*. For example, given a pair of events:
Yes, it should be ignored. I'll update the text to make that explicit.

2022-05-19 08:07 UTC, richvdh commented on proposals/2676-message-editing.md
> +which is left *unchanged*. For example, given a pair of events:
done e58715cfa

2022-06-01 02:10 UTC, turt2live requested changes
First of all, thank you for writing this up and bringing it in sync with reality - that is certainly not an easy feat given the history of these features.

I've approached this review somewhat differently from past reviews, which mostly means more comments (sorry) and more FCP-blocking concerns (sorry). For this review, the aim is to de-risk as much of the spec writing as possible while in previous reviews it might have been to ensure the feature is sound and can be figured out, however without an explicit implementation link (because it's impossible), it's more important for the MSC to be accurate about what it wants to happen. 

Roughly half my comments are raised as FCP-blocking concerns (annotated on the thread roots themselves, backed up by mscbot concerns shortly after this review). The other half are important for the MSC to land, but not exactly revolutionary in the changes they make, so can wait until during/after FCP if needed (or in some cases, ignored forever if not feasible/practical to write up the changes). The "request changes" review is to denote more on the side of not-FCP-affecting comments rather than FCP-affecting comments.

Provided the concerns are resolved, I'm happy to see this MSC go through. Excited, even, given it's been a literal eternity since this feature was first scoped.

2022-06-01 02:11 UTC, turt2live commented
@mscbot concern It is unclear if editing the relationship of an original event is valid
@mscbot concern The APIs which return edited events needs to be specified precisely
@mscbot concern The ordering algorithm for edit events is under specified
@mscbot concern Edits to replies are not sufficiently specified
@mscbot concern Behaviour for new_content on the plaintext part of an encrypted event is unclear

2022-06-07 15:18 UTC, turt2live commented on proposals/2676-message-editing.md
> +# MSC2676: Message editing
Element web appears to be relying on `/relations` returning the *most recent* `m.replace` event when a `limit` of `1` is specified - not sure if this should be documented in this MSC or not, but it's not immediately clear that that's a proper way to get the "latest" edit.

2022-06-08 19:46 UTC, uhoreg commented on proposals/2676-message-editing.md
> +# MSC2676: Message editing
I think the fact that `/relations` returns the most recent event is one thing that gets clarified by https://github.com/matrix-org/matrix-spec-proposals/pull/3715.

2022-06-08 20:12 UTC, turt2live commented on proposals/2676-message-editing.md
> +# MSC2676: Message editing
it'll actually get covered as part of https://github.com/matrix-org/matrix-spec/pull/1062 - we found it during implementation review of that PR.

2022-06-28 14:26 UTC, richvdh commented on proposals/2676-message-editing.md
> +### Validity of message edit events
Per https://github.com/uhoreg/matrix-doc/blob/aggregations-edits/proposals/2676-message-editing.md#applying-mnew_content: "`m.relates_to` ... is left unchanged. Any `m.relates_to property` within `m.new_content` is ignored.". So in short, you can't change the relationship of an event in this way.

2022-06-28 14:51 UTC, richvdh commented on proposals/2676-message-editing.md
> +Whenever a homeserver would return an event via the Client-Server API, it
My concern here is that it's a huge list. I could try to list them, but I'd probably miss something, which would not be the intention. And more to the point, it should include any *future* C-S APIs.

As a further thought experiment: currently `GET /_matrix/client/v3/rooms/{roomId}/members` would be excluded from such a list, because you can't edit state events. But if we were to change that restriction, we'd need to remember to *also* go and update the definition for  `GET /_matrix/client/v3/rooms/{roomId}/members`.

In general, I worry that having a specific list of endpoints is the start of a slippery slope where each endpoint has its own special way of rendering an event, because each endpoint has been updated by some unique combination of overlapping MSCs in the past. And sure, `/event` is doing this to some extent, but at least there we're making an explicit decision.

Far better IMHO to say "this applies to everything except `/event`." I can mention `/event` sooner if that helps.

2022-06-28 14:58 UTC, richvdh commented on proposals/2676-message-editing.md
> ++/_matrix/client/v3/rooms/{roomId}/context/{eventId}`](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidcontexteventid)
mmhmm, I take your point. The fact it returns full room state (modulo lazy-loading room members) does make it heavy.

I'm not super-keen to change the *default* behaviour for `/event` at this stage, but I could introduce a param to force it to return the edited copy?

2022-06-28 16:38 UTC, turt2live commented on proposals/2676-message-editing.md
> +Whenever a homeserver would return an event via the Client-Server API, it
It's far easier to say "everything except `/event`", however at the spec we can't reasonably say that in a way where people are going to notice or care. Listing the endpoints explicitly, with an added note that future ones are affected too, is required for the spec to function, I think.

2022-06-28 16:38 UTC, turt2live commented on proposals/2676-message-editing.md
> +`origin_server_ts`, falling back to `event_id`).
that needs to be in spec, as I can imagine clients and servers will screw it up.

2022-06-28 16:39 UTC, turt2live commented on proposals/2676-message-editing.md
> ++/_matrix/client/v3/rooms/{roomId}/context/{eventId}`](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidcontexteventid)
Adding a param of some behaviour would work, yea. I'm not particularly concerned with the how - just questioning that we ended up relying on `/context`.

2022-06-28 16:58 UTC, richvdh commented on proposals/2676-message-editing.md
> ++/_matrix/client/v3/rooms/{roomId}/context/{eventId}`](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidcontexteventid)
> I could introduce a param to force it to return the edited copy?

On reflection, I'm a little reluctant to change this without a clear usecase. Do we actually have clients that want to do this operation? Perhaps it would be better just to omit the whole sentence and assume that if people feel the need for this operation, they'll either find a way or propose an `apply_edits` param?

2022-06-28 17:00 UTC, turt2live commented on proposals/2676-message-editing.md
> ++/_matrix/client/v3/rooms/{roomId}/context/{eventId}`](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidcontexteventid)
I'm also quite in favour of that option. We should mention that `/event` is different from the other endpoints behaviourly, but I don't think we need to tell people how to get the "updated" event copy. 

They can figure it out or ask questions which prompt an MSC.

2022-06-28 17:23 UTC, richvdh commented on proposals/2676-message-editing.md
> +resolve. See also
> the MSC could at least suggest that clients redacting events redact the edits too

Is that what we actually do though? I'm reluctant to spec it if it's not a thing that happens.

2022-06-28 17:32 UTC, richvdh commented on proposals/2676-message-editing.md
> + * The original event and replacement event must have the same `room_id`.
I'm not entirely following what you're saying here. The aggregation behaviour for state events is orthogonal afaict.

I've clarified that the requirement of a matching room_id matches that in the spec for event relationships in general.

2022-06-28 17:33 UTC, richvdh commented on proposals/2676-message-editing.md
> +example, an encrypted replacement event might look like this:
Have added some words and a link to the spec.

2022-06-28 17:33 UTC, richvdh commented on proposals/2676-message-editing.md
> +        }
I'm really not sure what this was doing here. I've ripped it out and added some words to make it clear that it would be ignored were it present.

2022-06-28 17:39 UTC, turt2live commented on proposals/2676-message-editing.md
> +resolve. See also
it's not what we do, but the rationale for why we *should* be redacting old versions is much easier to reason about than why we didn't implement the feature in the first place.

it's long-since been considered a security-ish issue aiui that clients (including bots) don't redact old versions properly. What would be future MSC territory though is making it happen magically from the server rather than requiring the client to do it.

2022-06-28 17:49 UTC, richvdh commented on proposals/2676-message-editing.md
> ++/_matrix/client/v3/rooms/{roomId}/context/{eventId}`](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidcontexteventid)
I've removed the suggestion to use `/context`. The more I look at it, the less I am convinced we need anything specific here.

2022-06-28 17:50 UTC, richvdh commented on proposals/2676-message-editing.md
> +An event which replaces a [reply](https://spec.matrix.org/v1.2/client-server-api/#rich-replies) might look like this:
I've reworded this somewhat, hopefully strengthening the conditions.

2022-06-28 17:57 UTC, richvdh commented on proposals/2676-message-editing.md
> +Whenever a homeserver would return an event via the Client-Server API, it
> It's far easier to say "everything except /event", however at the spec we can't reasonably say that in a way where people are going to notice or care.

Firstly, I don't agree. We can absolutely find somewhere in the spec ([here](https://spec.matrix.org/v1.3/client-server-api/#room-event-format), most likely) to  say "all C-S APIs return the edited content, except where stated otherwise", and then make the text for `/event` say otherwise.

Secondly, even if we do need to list them in the spec, I don't see that it's for the MSC to make that mapping. In particular, if we forget one, that should be a spec bug which we can fix easily, rather than requiring another round of MSCs.

2022-06-28 18:06 UTC, richvdh commented on proposals/2676-message-editing.md
> +resolve. See also
Hrm, it just feels like a can of worms that I don't particularly want to open right now. What happens if the client doesn't have all the edits? (ok, it's better, but it's still a crappy solution). What happens if there are a million edits and we unexpectedly hit a rate limit?

I'm not really sure what we gain by adding a "hey, we could do this totally untested temporary hack" to an MSC.

2022-06-28 23:18 UTC, deepbluev7 commented on proposals/2676-message-editing.md
> +resolve. See also
> Is that what we actually do though? I'm reluctant to spec it if it's not a thing that happens.

Nheko does, but I don't think other clients do.

Link: https://github.com/Nheko-Reborn/nheko/blob/b6bbbdeae7966761ad2de7cdad92363c6926cfb5/src/timeline/TimelineModel.cpp#L1275

2022-06-29 16:20 UTC, turt2live commented on proposals/2676-message-editing.md
> +resolve. See also
there's several degrees of abuse which we can consider. Spamming edits is one form of abuse, but so is redacting a message and not the edits.

2022-06-29 18:44 UTC, richvdh commented on proposals/2676-message-editing.md
> +resolve. See also
Well fine, this isn't a hill I'm going to die on. Can you suggest some words?

2022-06-29 19:10 UTC, tulir commented on proposals/2676-message-editing.md
> +resolve. See also
The Telegram bridge also redacts all edits when a message is deleted on Telegram. It causes a fun redacted event placeholder spam on Matrix because clients don't know they're edits anymore (#3389), especially if you delete a message sent by some fun telegram bot that edits a message every second for a few hours. But appservices aren't ratelimited so it's fine

2022-07-05 14:10 UTC, erikjohnston commented on proposals/2676-message-editing.md
> +        "session_id": "<outbound_group_session_id>",
It might be worth noting that *what* we should encrypt with? I.e. think we encrypt with the "next" key as if it was a normal message, rather than reusing the same key as for the edit event? Not 100% sure though

2022-07-06 08:11 UTC, deepbluev7 commented on proposals/2676-message-editing.md
> +        "session_id": "<outbound_group_session_id>",
You always need to use a new key. Not only for security, but if you didn't the fallback would be useless since clients relying on the fallback would mark the event as a key reuse attack.

2022-07-12 13:52 UTC, richvdh commented on proposals/2676-message-editing.md
> +        "session_id": "<outbound_group_session_id>",
hopefully clarified in https://github.com/uhoreg/matrix-doc/commit/1e63094d3294eddf8ee45c7d38fa1c71f6a7294b.

2022-07-12 17:46 UTC, turt2live commented on proposals/2676-message-editing.md
> +Whenever a homeserver would return an event via the Client-Server API, it
I don't think putting it in the room events area of the spec will get noticed tbh, but point taken on the rounds of MSC review.

I'm very much treating this MSC as an effective spec PR given the history here, so would appreciate at least language to the effect of the following:

> The most recent edit is applied when returning events from all client-server endpoints, with the exception of `GET /event`. This includes the following endpoints:
> * ...

This is all because from a spec writing perspective I'd like to stick a "This endpoint returns edited events." message, with a link back to the event editing section, on every endpoint which is affected. There's also a mild concern that `/sync` is being forgotten here, despite "returning" events and I don't think it uses edited ones. 

If we forget some in the MSC's list, the language proposed above should make it a regular spec bug rather than an MSC.

2022-07-12 17:50 UTC, turt2live commented
@mscbot resolve The ordering algorithm for edit events is under specified
@mscbot resolve Behaviour for new_content on the plaintext part of an encrypted event is unclear
@mscbot resolve Edits to replies are not sufficiently specified

2022-07-12 21:25 UTC, turt2live commented
@mscbot resolve The APIs which return edited events needs to be specified precisely

2022-07-12 21:25 UTC, turt2live approved these changes

2022-07-12 21:25 UTC, richvdh commented on proposals/2676-message-editing.md
> +Whenever a homeserver would return an event via the Client-Server API, it
Right, I guess it's good you made me look at this harder, because I've realised it only happens when we were bundling aggregations.

I've updated this section - PTAL?

2022-07-12 21:49 UTC, uhoreg commented on proposals/2676-message-editing.md
> +plaintext body. (Again, any such property would be ignored.)
```suggestion
cleartext body. (Again, any such property would be ignored.)
```

plaintext is the decrypted event; cleartext is the part that is never encrypted (https://www.hypr.com/cleartext/)

2022-07-12 21:49 UTC, uhoreg commented on proposals/2676-message-editing.md
> +still be bundled, as described above.
```suggestion
still be bundled, as described above).
```

2022-07-12 21:49 UTC, uhoreg commented on proposals/2676-message-editing.md
> +visible in Element, subsequent edits remain unredacted and can be seen via API
It seems a bit strange to call out Element here specifically.  Is this behaviour applicable only to Element and not to other clients?  Or is this how most clients are expected to behave?

2022-07-12 22:42 UTC, deepbluev7 commented on proposals/2676-message-editing.md
> +visible in Element, subsequent edits remain unredacted and can be seen via API
At least a few other clients don't behave that way, since they consider it a privacy violation. :3

2022-07-13 06:34 UTC, richvdh commented on proposals/2676-message-editing.md
> +plaintext body. (Again, any such property would be ignored.)
thanks!

2022-07-13 06:35 UTC, richvdh commented on proposals/2676-message-editing.md
> +visible in Element, subsequent edits remain unredacted and can be seen via API
This means "I haven't done a comprehensive survey, and I wouldn't necessarily expect other clients to follow suit".

2022-07-13 13:08 UTC, benkuly commented on proposals/2676-message-editing.md
> +When applying a replacement, the `content` property of the original event is
1. I don't think that my opinion will change anything, but to cite this MSC `"Hopefully, processes have improved over the last three years"`. I don't think that merging an immature MSC just because Element does implement it is an "improvement". Element should implement the matrix spec and not the matrix spec should implement Elements implementation ;)
2. I meant redacted. According to this MSC, events with rel_type of m.replace can be redacted. Therefore you first have event1 with content1, then with an edit you have event1 with content2 (from event2) and with a redaction of event2 you should have event1 with content1. 

The section "Applying `m.new_content`" is from my viewpoint of a SDK developer far more complicated then it needs to be.

2022-07-18 03:00 UTC, merged

2022-08-16 18:12 UTC, richvdh commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1211

2022-09-21 13:43 UTC, richvdh commented
merged, at last!

2026-06-25 10:21 UTC, richvdh commented on proposals/2676-message-editing.md
> +The `m.new_content` includes any fields that would normally be found in an
see also https://github.com/element-hq/element-meta/issues/1323