[WIP] MSC2706: IPFS as a media repository for Matrix
matrix-org/matrix-doc pull request #2706
Opened 2020-07-28 04:34 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/ipfs/proposals/2706-IPFS.md)

This is inspired by matrix-media-repo's work towards IPFS, but still needs work.

This is done with a community hat on:
```
Signed-off-by: Travis Ralston <travis@t2bot.io>
```

2020-07-28 15:05 UTC, KB1RD commented on proposals/2706-IPFS.md
> +will allow legacy servers and clients to contact their homeserver and resolve it to an IPFS gateway
Who pins the IPFS content? IMO, server-side pinning creates an opportunity for managing retention and redaction using IPFS.

2020-07-28 15:09 UTC, KB1RD commented on proposals/2706-IPFS.md
> +For completeness, an example IPFS-styled MXC URI would be `mxc://example.org/ipfs:cidgoeshere`.
This may conflict with #2703. ( `unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"` ) Maybe #2703 could be expanded to allow certain exceptions for protocols like IPFS?

2020-07-28 15:13 UTC, KB1RD commented on proposals/2706-IPFS.md
> +For completeness, an example IPFS-styled MXC URI would be `mxc://example.org/ipfs:cidgoeshere`.
It might also be helpful to use a CID that points to an IPLD object containing metadata, such as filename, MIME type, or `Content-Disposition` data, as well as a link to the actual data. This could help implement #2702.

2020-07-28 15:19 UTC, turt2live commented on proposals/2706-IPFS.md
> +will allow legacy servers and clients to contact their homeserver and resolve it to an IPFS gateway
What do you mean by pinning here?

2020-07-28 19:20 UTC, KB1RD commented on proposals/2706-IPFS.md
> +will allow legacy servers and clients to contact their homeserver and resolve it to an IPFS gateway
From https://docs.ipfs.io/concepts/persistence/,
> IPFS nodes treat the data they store like a cache, meaning that there is no guarantee that the data will continue to be stored. "Pinning" a CID tells an IPFS server that the data is important and mustn't be thrown away.

AFAIK, the current method of retrieving Matrix media effectively "pins" media on all participant servers. Ideally, a server could do a reference count on IPFS resources and pin them accordingly. The difficult part with that would be that there is no standard way of determining which media an event references without knowing its schema. I.e, if I create a new event type and upload media with it, the server has no clear way of pulling the media out of that new event except by searching for all `mxc` URLs.

A future P2P world could use a more conservative pinning algorithm.

2020-07-28 19:48 UTC, turt2live commented on proposals/2706-IPFS.md
> +will allow legacy servers and clients to contact their homeserver and resolve it to an IPFS gateway
I'm not sure this is the MSC to solve that problem tbh. The server doesn't need to pin it, and in popular enough rooms the media will get shared across other nodes naturally. 

We could try and pin the media to a server, however in a p2p environment we'd probably want to do the opposite in support of freedom?

2020-07-28 19:49 UTC, turt2live commented on proposals/2706-IPFS.md
> +will allow legacy servers and clients to contact their homeserver and resolve it to an IPFS gateway
fwiw it is not proposed (and won't be proposed when this MSC is de-drafted) to have the old media system disappear. It would still exist, just at a lesser prominence than IPFS.

2020-07-28 20:03 UTC, KB1RD commented on proposals/2706-IPFS.md
> +will allow legacy servers and clients to contact their homeserver and resolve it to an IPFS gateway
> I'm not sure this is the MSC to solve that problem tbh.

Yeah probably best to leave up to a media pruning MSC.

> The server doesn't need to pin it, and in popular enough rooms the media will get shared across other nodes naturally.

If not pinned, all participant nodes will prune it if its not accessed for a while, so at least 1 node has to pin it. This could be just the originating server, but if that server goes offline, it can't be accessed. Retaining access after a server goes offline may also be beyond the scope of this MSC. Just `add`ing a file to IPFS pins it though, (unless otherwise specified) so if the originating server adds it, then others will be able to access it.

> We could try and pin the media to a server, however in a p2p environment we'd probably want to do the opposite in support of freedom?

True... AFAIK, each client would serve as a pinning node in this case, so technically no "servers."

2020-07-29 12:39 UTC, KitsuneRal commented on proposals/2706-IPFS.md
> +For completeness, an example IPFS-styled MXC URI would be `mxc://example.org/ipfs:cidgoeshere`.
I believe #2703 could use `pchar = unreserved / pct-encoded / sub-delims / ":" / "@" instead, sans `pct-encoded`?

2021-01-09 23:42 UTC, notramo commented
**Problems with this:
2 huge problems:**
- When the user originally uploads a file, it can **reveal his IP address** to everyone in the room as the only node that has the file at the beginning.
- IPFS nodes **crash** all consumer routers with Intel Puma 6 or 7 chip after few minutes. https://badmodems.com/

**Multiple smaller problems:**
- In a room with many members, an upload would cost multiples of the file size in bandwidth because the first few nodes will download from the uploader
- JS-IPFS isn't capable of seeding content (browser clients can't seed)
- IPFS use some background traffic to keep the DHT connections, which wastes mobile data. Unacceptable on phones.
- This would generate much more traffic than needed for downloading
  - If viewers don't seed, then everybody will download from the uploader. In a 200 member room, a 8 MiB image would cost 1.6 GiB for the uploader. Unacceptable on mobile data.
  - If viewers seed, then viewing an image would cost multitudes of the file size in traffic. (Dowload it once, and seed it for multiple peers.) Unacceptable on mobile data.
- If the uploader has a slow connection, it will be slow for everybody
- It has to be pinned on the client, which means it will use **lot of** storage. Unacceptable on phones. If it would be done that way, I would have to delete Element from my phone because it would use so much space that I don't have on my phone.
- If client sends a file in a DM, then becomes offline, the chat partner can't download it

**Possible solution:**
Upload to the server, and the server hashes, pins it, then every server can access, cache, replicate, or download it on IPFS.
Benefits:
- Network traffic equals to the size of file both when downloading and uploading.
  - No unnecessary seeding, or DHT gossip
- Servers have fast connections
- Servers have lot of storage to pin it
- Servers are always online, so the uploader can go offline after uploading
- No change to the client-server spec.
- No client-side implementation needed.

2021-01-10 03:10 UTC, turt2live commented
@notramo please use threads to receive replies.

2021-01-11 22:52 UTC, notramo commented
@turt2live What do you mean by threads?

2021-02-25 09:11 UTC, momack2 commented
This is exciting! Anything needed from us on the IPFS side to land this? (cc @aschmahmann @stebalien @lidel)

2021-02-25 13:25 UTC, lidel commented on proposals/2706-IPFS.md
> +For completeness, an example IPFS-styled MXC URI would be `mxc://example.org/ipfs:cidgoeshere`.
If #2703 used self-describing [CID](https://github.com/multiformats/cid) then you would not need `ipfs:` prefix. 
You could use custom `codec` ([table](https://github.com/multiformats/multicodec/blob/master/table.csv))  for different type of Media ID.

2021-02-25 13:55 UTC, lidel commented
@notramo thank you for this comprehensive list. 

Small clarifications/updates:
- Crashing consumer routers happens only when you run non-desktop settings on consumer network.  
  Consumer IPFS nodes in Brave and IPFS Desktop are running with lower connection count (trying to avg. [50-300](https://github.com/ipfs-shipyard/ipfs-desktop/blob/0ff806aa1185a423fa166618346045b9acb4d095/src/daemon/config.js#L50-L51))
- JS-IPFS is  capable of delegating seeding content to preload nodes ([config](https://github.com/ipfs/js-ipfs/blob/master/docs/MODULE.md#optionspreload), [FAQ](https://github.com/ipfs/js-ipfs/blob/ba4992ca69d2b3c148ea24833955b5b50003d76f/docs/FAQ.md#what-are-all-these-refsqmfoo-http-errors-i-keep-seeing-in-the-console))
- DHT traffic can be decreased by setting routing type to [dhtclient](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#routing). go-ipfs >0.5.0 automatically detects when node is behind a NAT and runs as a dhtclient automatically.

That being said, the approach you proposed (using IPFS to simplify backend media management) sounds sensible.  

Matrix would no longer need to worry about facilitating data transfers: only CID would have to be passed around, and the actual data would be found and fetched over IPFS. 

Moreover, instance operators could decide that their IPFS node acts only as a hot cache, and/or pin data using [vendor-agnostic api](https://ipfs.github.io/pinning-services-api-spec/) to a remote service(s) like [Pinata](https://pinata.cloud/documentation#PinningServicesAPI) (expect more in the future). This simplifies archival of old media without the need for managing archive on your own.

Leveraging IPFS on the client can be added later, but I believe that as long you use CIDs and content-paths in URLs user agents like [Brave](https://brave.com/ipfs-support/) or [IPFS Companion](https://github.com/ipfs/ipfs-companion#readme) will be able to leverage them and load data from IPFS thanks to [protocol upgrade](http://docs.ipfs.io.ipns.localhost:8080/how-to/address-ipfs-on-web/#protocol-upgrade) path.

Let us know  if you have any questions / concerns / ideas.

2022-05-08 14:58 UTC, planetoryd commented
Some people I know use Matrix in Tor browser. IPFS is not audited at the moment, and could compromise anonymity. I second that the servers run IPFS.

2022-06-17 17:18 UTC, notramo commented
> Some people I know use Matrix in Tor browser. IPFS is not audited at the moment, and could compromise anonymity. I second that the servers run IPFS.

Even if it's audited, it can compromise anonimity. IPFS is not designed to be private, it's designed to be only censorship- and attack-resistant.

2022-06-17 17:52 UTC, planetoryd commented
> > Some people I know use Matrix in Tor browser. IPFS is not audited at the moment, and could compromise anonymity. I second that the servers run IPFS.
> 
> Even if it's audited, it can compromise anonimity. IPFS is not designed to be private, it's designed to be only censorship- and attack-resistant.

There is some proposal on that, but they are not that interested in this topic indeed. I don't think keeping pics private here really makes sense, since you can use encrypted rooms, and in non-encrypted private rooms you don't get the hashes of private pics either. Once you have the hashes, you will get it.

2022-06-17 19:54 UTC, turt2live commented
(please use comments on the actual diff if you're expecting engagement from MSC authors or the SCT - otherwise feedback is outright ignored)

2022-06-18 08:31 UTC, planetoryd commented on proposals/2706-IPFS.md
> +* Retention and redaction, erasure.
The point is that once you know the CID of some picture you can always get it from IPFS, in an ideal network, because it's hard to prohibit the content once it has been published. For non-members of a room they never know the CID, so it's not a problem. In practice we can only do redaction of that message, unpinning and gc.

2022-06-18 08:37 UTC, planetoryd commented on proposals/2706-IPFS.md
> +**TODO: This.**
IPFS is known to have anonymity and privacy issues (fingerprintable, no audits, no Tor support), so it might be problematic for anonymous users. Running it on homeservers could mitigate this issue

2022-07-05 12:51 UTC, notramo requested changes
Please don't connect to IPFS from clients as it's a terrible idea.

2022-07-05 12:51 UTC, notramo commented on proposals/2706-IPFS.md
> +**TODO: This.**
IPFS was never designed to be private. It was designed to be censorship and attack resistant, but not private.
So it's important to run it on servers instead of clients.

2022-07-06 14:59 UTC, lidel commented on proposals/2706-IPFS.md
> +know if the server even supports IPFS to be able to bypass `/upload` entirely.
All the above, including privacy concerns when providing data to IPFS swarm,   assume a full IPFS node runs on the client that is also the only provider for the [CID](https://docs.ipfs.io/concepts/glossary/#cid). 

However, that is not the only possible architecture. P2P part of IPFS is optional. I'd argue even running full node is optional:
- CID could be created on the client, and sent to Matrix server as [CAR](https://docs.ipfs.io/concepts/glossary/#car) file for pinning and providing.
- Or the original  file could be sent to Matrix server, and it would do the work and produce CID for it. 

In both cases, the client does not leak IP by providing data to the IPFS network.

In my mind, the value of using IPFS in Matrix are CIDs.  [Content-addressed](https://docs.ipfs.io/concepts/what-is-ipfs/#content-addressing) identifiers allow the community to keep the data alive in addition to Matrix server operators, and use the same data outside of Matrix (and benefit from the pinning and caching on various layers).

Matrix servers could cap costs and set up policy to "pin CIDs for X amount of time/space" and if people want them to be available for longer, they can cache them on their clients, external pinning services, or run their own IPFS node and start reproviding it to the IPFS swarm on their own. 

When opening very old messages which are no longer kept around by Matrix server, one could still be able to retrieve the content, as long it was pinned somewhere. 

- _Providing_ CIDs to IPFS swarm can be handled by Matrix server, OR multiple  [external pinning services](https://github.com/ipfs/pinning-services-api-spec#readme).  
- Even when Matrix server does not have the data anymore, [HTTP Gateways](https://docs.ipfs.io/concepts/glossary/#gateway) allow delegating  _retrieval_ of IPFS content without running full node or providing anything to the network. 
  -  Client can request deserialized data (and trust the gateway did it correctly - fine if it is provided by Matrix server), or make a trustless request for verifiable [application/vnd.ipld.raw](https://www.iana.org/assignments/media-types/application/vnd.ipld.raw) or [vnd.ipld.car](https://www.iana.org/assignments/media-types/application/vnd.ipld.car) response and do inexpensive validation and deserialization on the client – this way, any gateway can be used, it no longer needs to be run by the same operator as Matrix server.

2023-05-30 20:12 UTC, DarkKirb requested changes
I expanded a bit on this MSC here: https://github.com/DarkKirb/matrix-spec-proposals/commit/d8516e5a848f5c499bbc13325d07a77b621209cd

The biggest difference between the current msc and my changes is that I added a pinning endpoint. I also changed the model a bit from the original vision. In many cases, nothing will change for the client, except that they can download the media from an IPFS gateway of their choice. Clients will continue uploading to the media server by default, due to the concerns others have listed here. They are also now listed in the MSC. I linked some related RFCs.

2026-05-14 18:01 UTC, turt2live commented
IPFS feels like it could be a beneficial change for Matrix, but someone who actually knows how it works (which isn't me) should write the proposal for this. I'm closing this in favour of a future proposal from someone who knows what they're doing :)

2026-05-14 18:01 UTC, closed without merging