Clarify canonical JSON more explicitly
matrix-org/matrix-doc pull request #2777
Opened 2020-09-16 14:07 UTC by ShadowJonathan

Per some discussion in the [conduit room](https://matrix.to/#/!INsBtndtvSOQMXuneb:koesters.xyz/$4OGIT3xWkZw2C-lP5PjB_A_yuSJn0z4G0ojGtKDqIgY?via=nordgedanken.dev&via=matrix.org&via=privacytools.io), explicitly stating the requirements for canonical JSON in bullet points should be more preferable over embedding it in one paragraph.

2020-09-16 14:18 UTC, ShadowJonathan commented
If these two commits need to be squashed before commit, please let me know.

2020-09-16 16:24 UTC, turt2live commented
We don't do squash merging on the spec and generally prefer that people never rebase a PR after it's been opened.

Can we get signoff on these changes per the contributing guidelines?

2020-09-16 16:33 UTC, ShadowJonathan commented
I only signed off the last one, I assume that would be enough, is it not?

If it's not, i'd have to force-push these changes to sign them both, or potentially just squash (on my side) and create a single commit encompassing all changes.

2020-09-16 16:35 UTC, turt2live commented
a github comment is fine. The whole changeset needs a signoff.

this hasn't actually been reviewed yet, so if you really want to sign it off in the commits then feel free.

2020-09-16 16:41 UTC, ShadowJonathan commented
I force-pushed the changes into one commit, so signing them is already handled.

In the future, i'll probably do it differently, but i'd rather have this simple clarification be as simple as possible for now.

2020-09-16 16:54 UTC, turt2live commented
thanks :D At a glance it looks good - sending it off for formal review.

2020-09-16 17:07 UTC, ShadowJonathan commented on specification/appendices/signing_json.rst
> +- With numbers in the JSON as integers in the range ``[-(2**53)+1, (2**53)-1]``.
Should this be prefixed with "A JSON value" for consistency and explicitness?

2020-09-23 15:41 UTC, richvdh requested changes
Breaking up into bullet points is sensible, but the bullets need to make sense!

2020-09-23 15:41 UTC, richvdh commented on specification/appendices/signing_json.rst
> +- A JSON value with the shortest UTF-8 string.
this... doesn't really make sense? 


"We define the canonical JSON encoding as: A JSON value with the shortest UTF-8 string."

an encoding is not a value?

2020-10-01 09:03 UTC, ShadowJonathan commented on specification/appendices/signing_json.rst
> +- A JSON value with the shortest UTF-8 string.
The canonical JSON encoding, therefore the way that the JSON value gets encoded with, is the shortest UTF-8 string that that value can encode into.

I agree this is confusing, let me think how i could better this

2021-08-03 16:15 UTC, richvdh commented
This seems to have stagnated, so I'm going to close it. We can reopen if you want to update it.

2021-08-03 16:15 UTC, closed without merging