MSC XXXX: Providing authentication method for appservice users
matrix-org/matrix-doc pull request #2778
Opened 2020-09-16 17:11 UTC by Half-Shot

[Rendered](foo)

2020-09-16 17:31 UTC, tulir commented on proposals/2778-appservice-login.md
> +`POST /login` until this lands in a released version of the specification.
Support for this should probably be advertised somewhere, probably in `GET /login` and/or unstable features. (I guess this is mostly a comment for the synapse PR if advertising in `GET /login` is enough)

2020-09-16 17:33 UTC, tulir commented on proposals/2778-appservice-login.md
> +which means bridge users need to be able to generate a device on demand.
Technically only one user from the bridge needs to have a device, not all users in a room. This will useful even if it's only used for logging in as the bridge bot though

2020-09-17 07:15 UTC, auscompgeek commented on proposals/2778-appservice-login.md
> +This can safely be ignored or used, but is an extra token hanging around.
Would it be a good idea to not generate an access token at all when `m.login.application_service` is used?

2020-09-17 08:25 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +This can safely be ignored or used, but is an extra token hanging around.
It's a bit tricky. The access token is tied to the device, so we do actually kinda need it. (Unless we restrict AS users to one device, or allow ASes to specify a device though query params)

2020-09-18 17:51 UTC, tulir commented
mautrix-python impl: https://github.com/tulir/mautrix-python/commit/12d7c48ca7c15fd3ff61608369af1cf69e289aeb

2020-09-18 17:53 UTC, tulir commented on proposals/2778-appservice-login.md
> +`POST /login` until this lands in a released version of the specification.
This is resolved now (synapse added it to the `GET /login` flows), but GitHub forgot to allow the "resolve" button for the user who created the thread

2020-11-19 10:51 UTC, bwindels commented on proposals/2778-appservice-login.md
> +traditionally need a "device". However E2E encryption demands that all users in a room have a device
The downside will be that the AS has access to all of a user's encrypted messages, not only for the rooms it is bridging. From the moment you bridge one encrypted room, you can't have any e2e encrypted conversations anymore... The only way to avoid that would be to associate a list of rooms with an e2ee device, with the default being all.

2020-11-19 11:04 UTC, tulir commented on proposals/2778-appservice-login.md
> +traditionally need a "device". However E2E encryption demands that all users in a room have a device
How would logging in as ghost users or the bridge bot affect non-bridged rooms? The AS still won't receive keys or messages for any rooms it's not in.

2020-11-19 11:27 UTC, tulir commented on proposals/2778-appservice-login.md
> +    "user": "alice"
This would make it clearer that the appservice can only log in as appservice-managed users:

```suggestion
    "user": "_bridge_alice"
```

2020-11-19 11:30 UTC, tulir commented on proposals/2778-appservice-login.md
> +- The access token does not correspond to a appservice that manages this user
Any particular reason this returns `M_FORBIDDEN` instead of `M_EXCLUSIVE` like identity assertion does?

2020-11-19 12:18 UTC, bwindels commented on proposals/2778-appservice-login.md
> +traditionally need a "device". However E2E encryption demands that all users in a room have a device
Oh, sorry, I misunderstood indeed. This would be used for ghost users that are only in bridged rooms. I was imagining this being used for regular matrix users that are in some bridged rooms, but that's not how bridging works probably :)

2021-04-29 14:59 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +which means bridge users need to be able to generate a device on demand.
Reworded this a bit.

2021-04-29 15:00 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +This can safely be ignored or used, but is an extra token hanging around.
Having thought this through, and my own response I'm going to remove this concern.

2021-04-29 15:02 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +- The access token does not correspond to a appservice that manages this user
I wanted to follow the spec for /login's standard:

>M_FORBIDDEN: The provided authentication data was incorrect.

Which is technically true in this case. You could probably make an argument for either given this treads the boundary of ASes/Clients, but I don't see a super compelling reason to change this.

2021-04-29 15:22 UTC, uhoreg commented
Looks straightforward and fairly sane.  Has multiple implementations.  I don't see any reason for this not to move forward, so

@mscbot fcp merge

2021-05-03 15:37 UTC, turt2live commented on proposals/2778-appservice-login.md
> +- The access token does not correspond to a appservice that manages this user
This should be M_EXCLUSIVE

2021-05-03 15:41 UTC, turt2live requested changes

2021-05-03 15:41 UTC, turt2live commented on proposals/2778-appservice-login.md
> +None
This section should always be filled out, either describing the security impact of letting appservices impersonate users and harvest encryption, or if there's truly nothing to worry about then a description as to why.

2021-05-03 15:41 UTC, turt2live commented
@mscbot concern Security considerations not made

2021-05-03 16:43 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +None
I've added some words :+1:. I'm not sure if they are the best words, but hopefully someone can review those words.

2021-05-03 16:44 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +- The access token does not correspond to a appservice that manages this user
This has been done.

2021-05-03 17:21 UTC, deepbluev7 commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
Should `/register` maybe still return a `device_id` anyway, so that this is symmetrical to how normal clients generate `access_token`s and `device_id`s? Appservices can still call `/login` to generate a new token at a later point anyway. Or should it intentionally not do that, so that large appservices, that don't use that, don't need to opt out and calling `/login` once more per user is not that much additional overhead?

2021-05-04 15:53 UTC, erikjohnston commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
I'm also a bit confused by this section. I think its fine to have `/login` *and* `/register`, but calling throwing away the device in `/register` just to call `/login` seems a bit silly? 

> It would difficult to log out these tokens if they got exposed additionally, as the AS would not be able to fetch a new access token.

But that's true for `/login` too? Or is the intention that a `/login` logs out other devices for that user?

2021-05-04 15:54 UTC, erikjohnston commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
@mscbot concern Why shouldn't we use /register

2021-05-05 15:04 UTC, jaller94 commented on proposals/2778-appservice-login.md
> +new devices should the appservice intentionally or inadvertently lost the client-side device data.
```suggestion
new devices should the appservice intentionally or inadvertently lose the client-side device data.
```
or
```suggestion
new devices should the appservice intentionally or inadvertently have lost the client-side device data.
```

2021-05-05 17:29 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
Unless I'm reading it wrong, I don't think I'm advocating for throwing away the information from `/register`.

>I think its fine to have /login and /register

This *is* my intention because you might want an access token for a user in your namespace that is already registered. This MSC essentially just ensures the bridge can call /login for it's users without having to set a password for each one.

2021-05-05 17:46 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
@erikjohnston I've attempted to tidy up the section and bullet point the concerns with this method because I think it was not clear.

2021-05-05 20:29 UTC, turt2live commented on proposals/2778-appservice-login.md
> +  new device on their existing sessions. It should be very obvious if a malicous appservice is creating new devices on your account.
this is untrue: the spec has no such mechanism, but Element does. 

The remaining points are convincing enough where this point shouldn't need including though.

2021-05-05 20:29 UTC, turt2live commented on proposals/2778-appservice-login.md
> +If the access token does not correspond to a appservice that manages this user, then the `errcode` should be `"M_EXCLUSIVE"`.
only if the access token is another application service though? It can be a bit confusing, but `M_EXCLUSIVE` is meant to be "an appservice tried to use a user outside of its own namespaces but that resides in *another* appservice's *exclusive* namespace".

Otherwise this would be M_FORBIDDEN, which is presumably the error code non-appservice users can expect.

2021-05-05 20:30 UTC, turt2live commented
@mscbot resolve Security considerations not made

2021-05-05 20:30 UTC, turt2live commented on proposals/2778-appservice-login.md
> +If the access token does not correspond to a appservice that manages this user, then the `errcode` should be `"M_EXCLUSIVE"`.
@mscbot concern M_EXCLUSIVE error code is unclear on usage

2021-05-05 22:00 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +If the access token does not correspond to a appservice that manages this user, then the `errcode` should be `"M_EXCLUSIVE"`.
Yeah, that was my intention. Words are hard.

2021-05-05 22:01 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +  new device on their existing sessions. It should be very obvious if a malicous appservice is creating new devices on your account.
Fair, can uninclude this one.

2021-05-05 22:10 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +If the access token does not correspond to a appservice that manages this user, then the `errcode` should be `"M_EXCLUSIVE"`.
Words have been adjusted.

2021-05-06 03:40 UTC, turt2live commented on proposals/2778-appservice-login.md
> +If the access token DOES correspond to a appservice but the user is not inside it's namespace,
its

2021-05-06 03:40 UTC, turt2live approved these changes

2021-05-06 03:40 UTC, turt2live commented
@mscbot resolve M_EXCLUSIVE error code is unclear on usage

2021-05-12 17:09 UTC, erikjohnston commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
I'm still confused why you're saying the following then:

> The expected flow for appservices would be to /register their users, and then /login to generate the appropriate device.

Why do appservices need to register *and then* login, creating multiple devices?

2021-05-12 17:42 UTC, Half-Shot commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
Okay, I think I was confused because this thread is highlighting the wrong section and it would be better to comment on the lines that are confusing directly. I've amended that line to explain when /register can be used and when /login is needed.

2021-05-13 16:34 UTC, erikjohnston commented
@mscbot resolve Why shouldn't we use /register

2021-05-13 16:34 UTC, erikjohnston approved these changes

2021-06-01 15:38 UTC, dbkr commented on proposals/2778-appservice-login.md
> +which do not implement encryption do not store this information as neither the device_id or access_token are needed f However critically
Not sure what's happened with this stray 'f'

2021-06-01 17:04 UTC, anoadragon453 reviewed
Some nits, but nothing that's really blocking.

2021-06-01 17:04 UTC, anoadragon453 commented on proposals/2778-appservice-login.md
> +which do not implement encryption do not store this information as neither the device_id or access_token are needed f However critically
These look like notes that were used to build the above bullet point list and can probably be deleted?

2021-06-01 17:04 UTC, anoadragon453 commented on proposals/2778-appservice-login.md
> +- Appservice namespaces are mainained by the homeserver admin. If the namespace were to change, then it's reasonable
```suggestion
- Appservice namespaces are maintained by the homeserver admin. If the namespace were to change, then it's reasonable
```

2021-06-02 18:03 UTC, uhoreg commented on proposals/2778-appservice-login.md
> +then the `errcode` should be `"M_EXCLUSIVE"`.
```suggestion
then the `errcode` must be `"M_EXCLUSIVE"`.
```

?

2021-06-02 18:23 UTC, tulir commented on proposals/2778-appservice-login.md
> +problems should the bridge wish to only join ghosts to a room (e.g. for DMs).
You can send encrypted messages without a device (using someone elses device). Right now it might be classifiable as a bug, but I think the long-term goal should be to have single-device appservices where clients are aware that it's all one appservice.

2021-06-11 19:01 UTC, penn5 commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
```suggestion

```

2021-06-11 19:02 UTC, penn5 commented on proposals/2778-appservice-login.md
> +user namespace regex to `@.*:example.com` would allow appservice to control anyone on the homeserver. While this sounds scary, in practise
```suggestion
user namespace regex to `@.*:example.com` would allow appservice to control anyone on the homeserver. While this sounds scary, in practice
```

2021-06-11 19:03 UTC, penn5 commented on proposals/2778-appservice-login.md
> +  devices for a given user's account as they could also do so by simply modifying the database.
```suggestion
  devices for a given user's account, which they could also do by simply modifying the database.
```

2021-06-11 19:03 UTC, penn5 commented on proposals/2778-appservice-login.md
> +In conclusion this MSC only automates the creation of new devices for users inside an AS namespace, which is something
```suggestion
In conclusion, this MSC only automates the creation of new devices for users inside an AS namespace, which is something
```

2021-06-23 02:24 UTC, turt2live commented
just going to go through the outstanding threads on this before landing, so the PR diff is as accurate as possible.

2021-06-23 02:25 UTC, turt2live commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
@penn5 why?

2021-06-23 02:28 UTC, turt2live commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
ah, I see, I think. In general, it's good to add explanatory comments to things.

2021-06-23 02:30 UTC, merged

2021-06-23 06:09 UTC, penn5 commented on proposals/2778-appservice-login.md
> +Furthermore, the ability to generate access tokens for real users who registered elsewhere would not be possible with this mechanism.
This text was duplicated above and has huge typos

2021-12-28 21:18 UTC, turt2live commented
Merged 🎉