MSC2801: Make it explicit that event bodies are untrusted data
matrix-org/matrix-doc pull request #2801
Opened 2020-10-01 22:34 UTC by richvdh

2020-10-01 23:00 UTC, ara4n commented on proposals/2801-untrusted-event-data.md
> +## The fundamental problem
Another unavoidable problem is that events within E2EE payloads can't be validated by the server, so have to be treated as untrusted whatever too.  At which point you might as well also assume everything's untrusted.

2020-10-01 23:01 UTC, richvdh commented on proposals/2801-untrusted-event-data.md
> +## The fundamental problem
ah yes. also that.

2020-10-02 00:34 UTC, turt2live approved these changes

2020-10-02 00:34 UTC, turt2live commented on proposals/2801-untrusted-event-data.md
> + 1. Most obviously, Synapse as it currently stands does very little validation
presumably the reason for Synapse being listed here is because it's the historical reference for the spec, though these days there are other implementations which do much stronger validation?

2020-10-02 00:34 UTC, turt2live commented on proposals/2801-untrusted-event-data.md
> +## The fundamental problem
might be worth mentioning this at the top near point 2. It will inspire sadness with the solutions that follow, but that might be acceptable given the MSC already prepares the reader for sadness.

2020-10-02 08:10 UTC, richvdh commented on proposals/2801-untrusted-event-data.md
> + 1. Most obviously, Synapse as it currently stands does very little validation
Synapse is listed here because its current behaviour is the lowest common denominator: as long as there exist servers which exhibit Synapse's current behaviour (as there will be unless we somehow spec otherwise), clients and users must handle that behaviour.

2020-10-02 08:27 UTC, richvdh commented on proposals/2801-untrusted-event-data.md
> +## The fundamental problem
Added some words about this.

2020-11-27 12:57 UTC, jplatte approved these changes

2021-03-22 18:36 UTC, richvdh commented
I think this has general agreement, so

@mscbot fcp merge

2021-03-22 18:56 UTC, erkinalp commented on proposals/2801-untrusted-event-data.md
> +
Mention the infeasiblity of alternative of requiring a new room version every time event specifications change

2021-03-22 18:59 UTC, dbkr commented
✅ and just to say thank you for taking the trouble to get complete reasoning-through of the problem down: it's super helpful to have the exact analysis of this documented somewhere.

2021-03-22 19:01 UTC, erkinalp requested changes

2021-03-22 19:01 UTC, erkinalp commented on proposals/2801-untrusted-event-data.md
> +
Mention the infeasiblity of alternative of requiring a new room version every time event specifications change

2021-03-23 11:34 UTC, ShadowJonathan commented on proposals/2801-untrusted-event-data.md
> +"`m.room.member` events with a non-string `displayname` are invald and should
```suggestion
"`m.room.member` events with a non-string `displayname` are invalid and should
```

(Typo)

2021-03-23 11:36 UTC, ShadowJonathan approved these changes

2021-03-23 11:38 UTC, erkinalp requested changes

2021-03-23 11:38 UTC, erkinalp commented on proposals/2801-untrusted-event-data.md
> +data.
There is another alternative that only requires auth-changing events such as redaction, PL change, role change, kick and ban to be well formed with no extensions, and all others be untrusted. Have you considered that?

2021-03-23 11:42 UTC, richvdh commented on proposals/2801-untrusted-event-data.md
> +data.
This is the sort of thing that is meant by 

> It may be possible to assert that specific, known cases can be treated as
> trusted data, but these should be called out as specific cases.

(https://github.com/matrix-org/matrix-doc/pull/2801/files/5db56391f30621db3a7e36824417fc57ed5f169f#diff-db3e334e6547f917a79147c0c0df60709ac25caca1ae5aaf6822482f0e04d553R188-R189)

In short, yes we have considered it, but it doesn't change the general philosophy.

2021-03-23 11:42 UTC, anoadragon453 commented on proposals/2801-untrusted-event-data.md
> +data.
I believe that's covered by the second to last sentence in the MSC: https://github.com/matrix-org/matrix-doc/pull/2801/files#diff-db3e334e6547f917a79147c0c0df60709ac25caca1ae5aaf6822482f0e04d553R188-R189

2021-03-23 11:42 UTC, richvdh commented on proposals/2801-untrusted-event-data.md
> +
Isn't this covered under the previous heading? It's not really relevant to this heading.

2021-03-26 00:24 UTC, kevincox approved these changes

2021-03-28 16:35 UTC, merged

2021-04-06 16:00 UTC, turt2live commented
Merged 🎉