Clarify m.room.redaction, remove duplicate entry
matrix-org/matrix-doc pull request #2814
Opened 2020-10-10 18:05 UTC by aaronraimist

Fixes #2171
Fixes #2172

As far as I can tell server admins cannot redact events in rooms where they don't have the proper power level so I have removed mention of that.

I have also removed

> There is also a concept of a moderator hiding a message event, which can be undone, but cannot be applied to state events.

which doesn't seem to be a thing that exists.

2020-10-11 06:07 UTC, turt2live commented
> As far as I can tell server admins cannot redact events in rooms where they don't have the proper power level so I have removed mention of that.

This is because the implementation is limited and not the spec. The authorization rules permit it happening in both v1 and v3 (where the redaction algorithms are defined).

2020-10-11 06:08 UTC, turt2live commented
"Users can redact their own events" is also misleading, as it can be prevented through power levels.

2020-10-13 03:32 UTC, aaronraimist commented
Okay I think I have fixed that.

Is it a Synapse bug that if you set the power level for `m.room.redaction` to 0 that you still can't redact other user's messages as a PL 0?

2020-10-13 03:41 UTC, turt2live commented
that's not a bug - you still need the `redacts` power level to redact other people's messages (over the client-server API).

2020-10-13 03:55 UTC, aaronraimist commented
Oh I see. That's not confusing at all... I see how it provides flexibility on how you want the room to work but the difference between

```
"content": {
  "events": {
    "m.room.redaction": 0
  }
}
```
and
```
"content": {
  "redacts": 0
}
```

does not seem to be described anywhere unless I'm missing something.

2020-10-13 04:08 UTC, turt2live commented
it's badly described, but it is described.

`redacts` controls whether or not you're able to redact other people's messages. Separately, but related, `m.room.redaction` under `events` determines whether or not you're able to send redaction events. An admin could block self-redaction by listing `m.room.redaction` events at a higher power level, and could confuse everyone by setting `redacts` at a low level but having `m.room.redaction` at a high level (you shouldn't do this). Moderators would require the permission to send `m.room.redaction` events (default `events_default`, default zero) *and* `redacts`.

2020-10-14 22:39 UTC, turt2live requested changes
only one comment left - thanks :D This is looking really great.

2020-10-14 22:39 UTC, turt2live commented on api/client-server/redaction.yaml
> +        redact messages sent by their server.
this still needs to keep the parts about users being able to self-redact.  Would also be good to give context to "there" as the reader has likely forgotten by the time they read this.

2020-10-15 01:05 UTC, aaronraimist commented on api/client-server/redaction.yaml
> +        redact messages sent by their server.
But I thought users may or may not be able to self-redact you mentioned a few days ago.

and yeah I can reword that. "may redact events there" is from the original sentence that's in the spec right now.

2020-10-15 03:02 UTC, turt2live commented on api/client-server/redaction.yaml
> +        redact messages sent by their server.
A user's ability to be able to self-redact is controlled solely by the `events` object, not `redacts`.

2020-10-16 19:19 UTC, turt2live approved these changes
Thanks for working through this :D

2020-10-16 19:19 UTC, merged