Improve wording of room version 1 warnings
matrix-org/matrix-doc pull request #2817
Opened 2020-10-10 19:29 UTC by aaronraimist

Fixes #2816

2020-10-11 06:03 UTC, turt2live requested changes

2020-10-11 06:03 UTC, turt2live commented on specification/rooms/v1.rst
> -
This warning is still quite relevant and isn't specific to state resolution

2020-10-11 06:03 UTC, turt2live commented on specification/rooms/v1.rst
> +   Room version 1 is known to have bugs that can cause the state of rooms to reset.
from a spec point of view, we need to define what a state reset is - it's not something that someone will understand by just reading the spec.

2020-10-13 03:59 UTC, aaronraimist commented on specification/rooms/v1.rst
> -
I'm not sure what it should say then. I thought the main issue with v1 was with state resolution.

2020-10-13 04:09 UTC, turt2live commented on specification/rooms/v1.rst
> -
> Servers implementing support for room version 1 should be
>   aware that restrictions should be generally relaxed and that inconsistencies
>   may occur

This bit is the most important part of it. The remainder is a bad case of age :(

2020-10-13 04:12 UTC, aaronraimist commented on specification/rooms/v1.rst
> +   Room version 1 is known to have bugs that can cause the state of rooms to reset.
How about something like

> Room version 1 is known to have bugs that can cause the state of rooms to reset
   to older versions of the room's state. For example this could mean that users
   who had joined the room may be removed from the room, admins and moderators
   could lose their power level, and users who has been banned from the room may
   be able to rejoin. Other state events such as the the room's name or topic could
   also reset to a previous version.

>   This is fixed in room version 2 and later.

2020-10-13 04:16 UTC, turt2live commented on specification/rooms/v1.rst
> +   Room version 1 is known to have bugs that can cause the state of rooms to reset.
Looks good, though we'd need to drop the "and later" part. Room versions don't have relative ordering so "later" is meaningless from a spec perspective. It's more or less a coincidence that all room versions right now are based on vN-1, which does eventually track down to v2 for everything.

2020-10-13 04:32 UTC, aaronraimist commented on specification/rooms/v1.rst
> +   Room version 1 is known to have bugs that can cause the state of rooms to reset.
So just "This is fixed in room version 2" then? If rooms done have an order and you just say "fixed in v2" then it raises the question whether the bug exists in v3 or not.

Maybe "This is fixed in the state resolution algorithm introduced in room version 2."

2020-10-13 05:13 UTC, turt2live commented on specification/rooms/v1.rst
> +   Room version 1 is known to have bugs that can cause the state of rooms to reset.
> This is fixed in the state resolution algorithm introduced in room version 2.

This sounds a lot better :D

2020-10-13 16:43 UTC, aaronraimist commented
Matthew doesn't like "Known to have undesirable effects" but I'm not sure what would be preferable.

2020-10-14 22:23 UTC, turt2live approved these changes
thanks!

2020-10-14 22:23 UTC, turt2live commented on specification/rooms/v1.rst
> +   could lose their power level, and users who has been banned from the room may
```suggestion
   could lose their power level, and users who have been banned from the room may
```

2020-10-14 22:24 UTC, merged