[WIP] MSC2844: Global version number for the whole spec
matrix-org/matrix-doc pull request #2844
Opened 2020-10-30 19:59 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/global-versioning/proposals/2844-global-versioning.md)

Note: this is currently a work in progress to gather early feedback and ideas to help fill in some of the sections of the proposal itself.

2020-10-30 20:36 UTC, turt2live commented on proposals/2844-global-versioning.md
> +## Potential issues / alternatives
Deprecation needs defining. Strawman is that (for example) 1.2 deprecates an endpoint, 1.3 is a reminder, and 1.4 deletes it. This ensures we don't need to do Matrix 2.0 just to remove an endpoint.

2020-10-30 20:47 UTC, Cadair commented on proposals/2844-global-versioning.md
> +`v1.1.0`, it also supports `v1.1.7`, for example.
Why not completely drop the bugfix version from the advertised versions in this case?

2020-10-30 21:45 UTC, turt2live commented on proposals/2844-global-versioning.md
> +## Potential issues / alternatives
this^ proposed deprecation mechanism is incompatible with semantic versioning, which we might want to uphold. Under a semantic versioning model, we'd do a minor release for the deprecation notice then a major release with the removal. In common understanding, endpoint removal would be a breaking change hence the major release requirement.

It might be useful for us to stick with semantic versioning, even if it means we'd have Matrix 212.6.1 in as little as a couple years, simply for the availability of tooling out there to check versions of things. An argument could also be that the tooling can still be used in the model proposed above (use minor versions for removal) if the spec were to demand/encourage implementations to validate against the minor version they need as if it were a major version.

Much of the semantic versioning spec also can't be referenced by our specification because there's no authoritative reference to what semantic versioning looks like in practice. The specification as defined is interpreted differently in reality, leading us to having to define what semantic versioning is and say that it's within the ideals of how it works in practice. At that point, it could be argued that we can go all-in and define our own scheme anyways.

A datapoint is that Python already uses a deprecation model where the minor version bump represents removal, so there must be tooling that exists for that space and thinking people can use. It also shows that a large project is capable of defining its own versioning scheme, though occasionally gets "ugh, why not semver" comments/issues.

----

As an author, I'm not really convinced on either direction at the moment - will have to consider both options before writing it into the MSC. Opinions and factors which might help make this decision are appreciated, though please let's not turn this thread into a polarized argument on semver vs not-semver.

2020-10-30 21:47 UTC, turt2live commented on proposals/2844-global-versioning.md
> +endpoint: `{"versions":["r0.5.0", "r0.6.0", "v1.1.0"]}`. Servers do not need to advertise every
TODO: this still doesn't solve the problem of servers not knowing if they need to advertise patch versions

2020-10-30 22:01 UTC, joepie91 commented on proposals/2844-global-versioning.md
> +## Potential issues / alternatives
A few small additions to this:

> Under a semantic versioning model, we'd do a minor release for the deprecation notice

Importantly, the deprecation notice does not need to be the *last* minor release before a new major release; it is valid for *any* minor release to introduce the deprecation notice, even if further minor releases follow it before the next major. Without this leeway, it would probably not be viable to combine semver and deprecation notices.

> An argument could also be that the tooling can still be used in the model proposed above (use minor versions for removal) if the spec were to demand/encourage implementations to validate against the minor version they need as if it were a major version.

Low-level semantic versioning tooling ([example](https://www.npmjs.com/package/semver)) typically takes whole version numbers, parsing their components internally, and so is unlikely to support custom semantics like this natively, requiring custom pre-processing string hackery to achieve this. High-level tools which use semver (package managers, testing tools, etc.) are typically 100% non-configurable semantics-wise, and only support compatibility specifiers like `^` and `~`.

> At that point, it could be argued that we can go all-in and define our own scheme anyways.

I'd consider there to be a meaningful difference between "have to redeclare semver in the spec" and "not follow semver at all"; in the former case, it is still *practically* compatible (even if it's a bit fuzzy on paper), whereas in the latter case it would not be.

2020-10-30 22:01 UTC, turt2live commented on proposals/2844-global-versioning.md
> +`v1.1.0`, it also supports `v1.1.7`, for example.
well, we'd need it for auditability of the spec but agreed we probably don't need servers to advertise their support for it.

2020-10-30 22:01 UTC, turt2live commented on proposals/2844-global-versioning.md
> +endpoint: `{"versions":["r0.5.0", "r0.6.0", "v1.1.0"]}`. Servers do not need to advertise every
https://github.com/matrix-org/matrix-doc/pull/2844/files#r515401902

2020-10-30 22:04 UTC, turt2live commented on proposals/2844-global-versioning.md
> +   endpoint, thus making most endpoints under it as `/r0/` (currently).
it's also been pointed out that we do a weird thing where our releases contain two versions of an endpoint, one deprecated and one not, which is a bit non-standard.

2020-10-30 22:07 UTC, turt2live commented on proposals/2844-global-versioning.md
> +**Note**: This proposal does nothing to room versions and are thus not included beyond this line.
this might not be a good idea. It could be desirable to release a new Matrix version every time there's a new room versions or stability changes among them.

2020-11-10 17:32 UTC, turt2live commented on proposals/2844-global-versioning.md
> +If accepted, this MSC will declare the spec as it is at the time as Matrix v1.1.0.
we need to describe what "alpha" and stuff look like for implementation proof

2020-11-10 17:32 UTC, turt2live commented on proposals/2844-global-versioning.md
> +all the `/r0/` endpoints now become `/v1/`.
do v1 endpoints work with v2 endpoints?

2020-11-10 17:32 UTC, turt2live commented on proposals/2844-global-versioning.md
> +all the `/r0/` endpoints now become `/v1/`.
will this be confusing with the old v1 endpoints? (pre-rN era)

2020-11-13 15:24 UTC, turt2live commented on proposals/2844-global-versioning.md
> +### Structure changes and changelogs
what if we release a new Matrix version that has no changes for a given implementation? They'd have to update to declare support, though the urgency is somewhat questionable. Need to codify that implementations should play nice with each other and support older versions for longer.

2020-11-13 15:25 UTC, turt2live commented on proposals/2844-global-versioning.md
> +### Deprecation approach
Need to clarify that removing an endpoint in a version does not mean it's impossible to support older versions - it'll just be deprecated as normal.

Eg: v1.1.0 deprecates `/test`, v1.2.0 removes it. A server can support both 1.1 and 1.2 by keeping `/test` deprecated.

2020-11-19 12:48 UTC, anoadragon453 reviewed
Overall I think this is a great change, which will not only encourage more frequent releases, but also simplify discussion of the Matrix spec in general. I thought your points were well thought out and I agree on the whole.

I have a few questions, suggestions and clarifications below, but otherwise this seems sane.

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +### Structure changes and changelogs
In the extreme case a major version bump of the whole spec could come due to, say, a large change in federation. Because this is a major version change, and servers are unlikely to want to support both major versions, identity servers and application services would need to advertise support for it, even though they don't need to use the Federation API.

One idea could be if ex. homeservers could say they support at least Matrix vX for other homeservers, Matrix vY for application services and Matrix vZ for identity servers, then that may help?

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +Servers which are lucky enough exist during this versioning scheme change are expected to continue
```suggestion
Servers which are lucky enough to exist during this versioning scheme change are expected to continue
```

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +As a further clarification to an solved problem, the `/versions` endpoint for the client-server API
```suggestion
As a further clarification to a solved problem, the `/versions` endpoint for the client-server API
```

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +major/minor version equivalent (`v1.1.8` gets treated as `v1.1.0`, for example).
So is there a rule about whether a homeserver should advertise `v1.1.8` vs `v1.1.0`, or is it free to do either as it will functionally mean the same thing to clients?

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +able to claim support for that version.
This is an excellent point to bring up and one that's quite relevant for new homeservers today that aren't implementing deprecated, but still available, endpoints.

The solution I'd like to see to this though is more active removal of endpoints from the spec, rather than asking more from upcoming homeserver devs.

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +unstable. The current specification says that implementatiosn don't have to implement unstable room
```suggestion
unstable. The current specification says that implementations don't have to implement unstable room
```

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +* v1.4.0 - Released in January 2020 - The current release so should definitely be supported.
Err, what's the current time in this example? Jan 2020?

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +   to be considered here.
I probably just don't know semantic versioning well enough (and am probably unconsciously a proponent of off-spec SM), but how does our MAJOR.MINOR.PATCH-EXTRA system differ from semantic versioning proper?

2020-11-19 12:48 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +`/_matrix/client/r0`.
What would an implementation even do to implement this MSC ahead of landing in the spec? Implement C-S v3 endpoints?

2020-11-19 15:13 UTC, turt2live commented on proposals/2844-global-versioning.md
> +an implementation might have. For example, Synapse currently supports 4 different APIs, all of which
it interacts with the Push Gateway, making it 4.

2020-11-19 15:14 UTC, turt2live commented on proposals/2844-global-versioning.md
> +major/minor version equivalent (`v1.1.8` gets treated as `v1.1.0`, for example).
it just has to pick one or both - they are functionally the same and the client is responsible for parsing it.

2020-11-19 15:16 UTC, turt2live commented on proposals/2844-global-versioning.md
> +* v1.4.0 - Released in January 2020 - The current release so should definitely be supported.
yes - I'm happy to drop/change the years so it's a bit easier to follow?

2020-11-19 15:17 UTC, turt2live commented on proposals/2844-global-versioning.md
> +`/_matrix/client/r0`.
Yes, and start advertising the feature support.

2020-11-19 15:18 UTC, turt2live commented on proposals/2844-global-versioning.md
> +   to be considered here.
it's largely our handling of breaking changes which differs. The MSC could probably be a bit more clear about it.

2020-11-20 15:10 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +* v1.4.0 - Released in January 2020 - The current release so should definitely be supported.
Yeah, I immediately went and tried to figure out whether January 2019 was >1.5 years old, and then got stuck at what $current_date was.

I think just thinking in versions is simpler to follow.

2020-11-20 15:10 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +   to be considered here.
Just roughly mentioning the notable differences would be valuable I think.

2020-11-20 15:11 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +`/_matrix/client/r0`.
Right. We can probably leave that out of the document then if we're trying to inch people away from not implementing it beforehand.

2020-11-20 15:15 UTC, turt2live commented on proposals/2844-global-versioning.md
> +`/_matrix/client/r0`.
It's useful imo to at least mention what implementations need to do if they are going to do something silly, though the MSC could be better at describing how silly it is.

The implementation requirement for this MSC is largely covered by a proof of concept that we can successfully build a spec that uses the version number, which is mostly done (at least it's done enough to validate it imo). So far we've built a demoable version of the spec website which uses this versioning scheme, though it's hard to validate the rest of the MSC in the same way.

2020-11-20 16:59 UTC, turt2live commented on proposals/2844-global-versioning.md
> +### Structure changes and changelogs
> One idea could be if ex. homeservers could say they support at least Matrix vX for other homeservers, Matrix vY for application services and Matrix vZ for identity servers, then that may help?

This is what we have today, which is what we're explicitly trying to steer away from in this MSC.

2020-11-22 08:03 UTC, turt2live commented on proposals/2844-global-versioning.md
> +### Structure changes and changelogs
this will be covered in a later commit, but the idea is that the MSC gets words to say "use common sense" - an implementation shouldn't arbitrarily drop an affecting version for a client because there was a no-op version.

2020-11-22 08:04 UTC, turt2live commented on proposals/2844-global-versioning.md
> +### Structure changes and changelogs
09c569f1a76c4fcce148a847f9b541ae37269933

2020-11-22 08:07 UTC, turt2live commented on proposals/2844-global-versioning.md
> +able to claim support for that version.
fair, will change this to continue the deprecated=no implementation system.

2020-11-22 08:23 UTC, turt2live commented
All the initial feedback has been addressed, and this seems to be getting supportive comments out of band. Per the MSC, this has a rudimentary implementation at https://adoring-einstein-5ea514.netlify.app/ (see "releases" dropdown in the top right) to prove that the website component works. I don't think it's practical to have an implementation proof of the remainder of the MSC - it'll have to be explored and analyzed in practice if this MSC is to be accepted.

As such,

@mscbot fcp merge

2020-11-22 09:05 UTC, aaronraimist commented on proposals/2844-global-versioning.md
> +Patch releases do not require such notice and can happen whenever.
Is there any plan to increase the frequency of patch releases? Maybe a plan to do one every 3 months assuming there have been changes and there hasn't been any new major/minor release announced for the near future?

Right now clarifications and fixed typos sit for a long time only being visible on the unstable page which most people don't look at.

2020-11-22 09:29 UTC, turt2live commented on proposals/2844-global-versioning.md
> +Patch releases do not require such notice and can happen whenever.
There's not really a plan, but by making the release process lighter it should happen more frequently.

2020-11-23 17:21 UTC, turt2live commented on proposals/2844-global-versioning.md
> +posterity, though largely has no significant meaning (unchanged by this MSC).
For clarity: v1.1.0 technically only comes into play once we (the spec core team) actually cut the release. This MSC is just saying that v1.1.0 is the first version number for the spec core team to use.

2020-12-01 00:50 UTC, uhoreg commented on proposals/2844-global-versioning.md
> +When a dash (`-`) is present after the `PATCH` version, the version is denoting some off-cycle release
This sounds like if a version has a `-` in it, then it will sort before the version without the `-` in it (i.e. `<version>-<anything>` will always come before `<version>`).  Is this correct?  (This is in contrast with things like Debian's package versioning where `-` indicates that it sorts after, and `~` indicates that it sorts before)

2020-12-01 00:50 UTC, uhoreg commented on proposals/2844-global-versioning.md
> +1. Sometime after a given release happens, the Spec Core Team announces a cutoff date for MSCs to land
```suggestion
1. Sometime before a given release happens, the Spec Core Team announces a cutoff date for MSCs to land
```
?

2020-12-01 02:29 UTC, uhoreg reviewed
Looks largely sane

2020-12-01 02:50 UTC, turt2live commented on proposals/2844-global-versioning.md
> +When a dash (`-`) is present after the `PATCH` version, the version is denoting some off-cycle release
this is trying to say that dashes can only appear after the last digit, not the ordering of the releases.

2020-12-07 14:27 UTC, richvdh commented on proposals/2844-global-versioning.md
> +3. Room versions to freezing a set of behaviour and algorithms on a per-room basis. These are well
This sentence doesn't make sense, though the intention is clear.

2020-12-07 14:27 UTC, richvdh commented on proposals/2844-global-versioning.md
> +1. Sometime after a given release happens, the Spec Core Team announces a cutoff date for MSCs to land
+1. This confused me too.

2020-12-07 14:27 UTC, richvdh commented on proposals/2844-global-versioning.md
> +Because the release schedule is well-advertised, it should be clear to everyone what the next non-patch
This is a non-blocking comment, but: I get scared whenever releases of anything are announced in advance, due to the high likelihood of unforseen circumstances arising which require an urgent, intermediate release, which then has to adopt an inappropriate version number.

I think this scenario is less likely with specs than with software, but still, I'm not terribly comfortable with this whole section, which feels orthogonal to the rest of the proposal.

2020-12-07 16:38 UTC, turt2live commented on proposals/2844-global-versioning.md
> +Because the release schedule is well-advertised, it should be clear to everyone what the next non-patch
fair, this is more trying to declare that the MSC is used upon acceptance (post-FCP) - we can probably just use words to that effect instead of picking a number, though.

2020-12-08 13:55 UTC, Kegsay commented
So the spec was originally a big single-page document with CS/SS/AS APIs all in one place, and hence was versioned as such. We split this into relevant sub-documents and decided at that point that they should be versioned separately otherwise a change on the CS API results in a bump on the SS API which makes no sense. It sounds like this MSC is proposing to revert back to a single version, and whilst I admire the desire to reduce the number of versions floating around, I don't think this MSC makes that situation any better. There will still be room versions, `v1/v2_alpha/r0` paths, the marketing 1.0 version and now a new global spec version. We did consider having per-endpoint version numbers, but thought that would end up being confusing to have say `/v11/backfill` and `/v7/send` be the "latest" for the spec, hence the decision to use `r0` to refer to the spec [r]elease rather than any endpoint version.

Ultimately we have so many versions because they convey different meanings: algorithms, marketing, revisions, etc. I don't feel unifying them under one common version is desirable and I don't think it will end up reducing complexity.

2020-12-08 14:03 UTC, turt2live commented
@Kegsay many of these points are already addressed in the MSC itself.

Please use threads on the diff for easier conversation.

2020-12-15 16:48 UTC, turt2live commented on proposals/2844-global-versioning.md
> +Because the release schedule is well-advertised, it should be clear to everyone what the next non-patch
TIL that github mobile screwed up 8 days ago and my comment makes no sense here.

@richvdh this paragraph is mostly to help define an actual release process which we don't have well-defined at the moment, so imo it's very much part of the proposal. It does try to say that implementations can't rely on the version numbers and that they can change, though perhaps the wording isn't as clear about this?

2020-12-15 17:09 UTC, dbkr reviewed
Submitting the comments for as far as I've got through this. I'm surprised by how much there is in this document: the size of this is going to make it very slow to review. There's also a lot of text talking about setting expectations that I'm not certain where it would end up living in the spec itself.

2020-12-15 17:09 UTC, dbkr commented on proposals/2844-global-versioning.md
> +process, the cutoff date is *not* enough for an implementation to switch to using stable endpoints.
I'm not sure what this is trying to say. An MSC passing FCP by the cutoff date doesn't guarantee it will be in x version of the spec?

2020-12-15 17:09 UTC, dbkr commented on proposals/2844-global-versioning.md
> +confusion with long-standing implementations.
What will they be after the starting point?

2020-12-15 17:09 UTC, dbkr commented on proposals/2844-global-versioning.md
> +the Spec Core Team be able to blindside the community with a release for no justifiable reason.
This is the sort of thing that I'm a bit surprised is in here: where is its intended home in the spec?

2020-12-15 17:14 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +   endpoint, thus making most endpoints under it as `/r0/` (currently).
That or "making" should be "marking".

2020-12-15 17:22 UTC, anoadragon453 approved these changes
Checked since my last review and all look good. Thanks for the clarifications!

2020-12-15 17:22 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +* v1.4.0 - Released in December (current day) - The current release so should definitely be supported.
This is much cleaner to read, thanks!

2020-12-15 17:22 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +(see the 'releases' dropdown in the top right; link may not be available in the distant future - sorry).
Perhaps this should be removed as that dropdown seems to no longer exist?

2020-12-15 17:37 UTC, anoadragon453 commented on proposals/2844-global-versioning.md
> +the Spec Core Team be able to blindside the community with a release for no justifiable reason.
By "its" do you mean this MSC?

2020-12-15 18:15 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +Because the release schedule is well-advertised, it should be clear to everyone what the next non-patch
This confused me too, it sort of sounds like we're implying that implementations can use that knowledge... somehow. Can we change

> ... it should be clear to everyone what the next non-patch version number will be.

to 

> ... *at the time of release* it should be clear what the next non-patch version *should be*.

Or something?

2020-12-15 18:17 UTC, turt2live commented on proposals/2844-global-versioning.md
> +   endpoint, thus making most endpoints under it as `/r0/` (currently).
this is local language making it through to a written document - will fix

2020-12-15 18:19 UTC, turt2live commented on proposals/2844-global-versioning.md
> +confusion with long-standing implementations.
hmm, this doesn't seem to be mentioned by the idea is that because they're independently versioned that they'll be able to get bumped up as needed rather than any other way.

2020-12-15 18:20 UTC, turt2live commented on proposals/2844-global-versioning.md
> +process, the cutoff date is *not* enough for an implementation to switch to using stable endpoints.
This is trying to say that you can't implement your MSC using stable endpoints just because it passed the cutoff point - you're still (supposed to) wait until the final spec release before doing anything in that respect.

2020-12-15 18:23 UTC, turt2live commented on proposals/2844-global-versioning.md
> +the Spec Core Team be able to blindside the community with a release for no justifiable reason.
I'm assuming the paragraph rather than the whole MSC for `its`, though the answer applies to many places.

Most of this MSC doesn't actually change any spec and instead fills out an imaginary "release process" or "release guidelines" document that exists somewhere. It's to establish a common understanding of how the proposal works and give the spec writer enough context to better write out how the versioning works for end-users of the spec. Somewhere we need to describe what the versioning is, how it works, etc and supplementary to that we also need a document that tells the spec core team what they're supposed to be doing to honour the versioning scheme.

2020-12-15 18:25 UTC, turt2live commented on proposals/2844-global-versioning.md
> +(see the 'releases' dropdown in the top right; link may not be available in the distant future - sorry).
possibly, though I believe there's an intention to put it back. Might need reintroducing to fulfill the implementation requirement anyways.

2020-12-15 18:53 UTC, erikjohnston reviewed
I think this broadly feels like the right thing. There are quite a lot smaller policy updates bundled in here, some of which I agree with and some I'm not sure we should "formally" commit to. I'm not sure if they should be separated out somehow to make it easier to reason about each one, but :shrug:

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +does not need to advertise all patch version changes - just the major/minor versions it supports.
Can we ban patch versions entirely? AIUI patch versions should *never* be useful to implementations?

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +  small patches are done. Implementations do not need to worry about the patch version.
I'm not sure that we should include patch in the version numbers here, and perhaps version the spec document separately? I understand that we're trying to reduce the number of versions abound, but I feel like fixing typos is completely orthogonal to the actual protocol. Some concrete concerns:

1. Almost everything uses the phrase "non-patch version",
2. What triggers a patch release? Does this prevent CD (of eg typos)? Or do we just automatically bump the patch version every time we release?

A concrete counter suggestion would be having "Matrix Versions" and "Spec revisions" (potentially using date versioning), so when referring to a particular part of the spec you'd say "v1.10.0 revision 2021-01-01" (or `v1.10.0-rev20210101` or whatever)

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +supporting the `rN` system. This is done by advertising the existing client-server API versions as
(And servers that want to support older clients)

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +ideas through the stages as quickly.
I'm... hesitant about this. When the Synapse team had release cycles much less frequent than our current fortnightly cycles it could often become *very* painful to actually get a release out of the door, as folks desperately tried to land stuff before they had to wait ages for it to become stable again. 

I'm also conscious that two months can be quite a long time if we have high value features we want to turn around.

I'd be interested to know what is motivating this? If the issue is that the community ends up waiting ages for a feature to land in a released version of the spec then, personally, I think I'd rather promote releasing the spec more frequently where there are such changes (and empowering the community to do so themselves by guiding them into writing the necessary spec additions themselves). 

If there is a concern that would end up with high version numbers I'd be tempted to suggest having an extra number on the versions that can be used for rolling out backwards compatible changes. This allows servers to advertise a set like `v1.9.2, v1.8, v.1.7` and clients can interpret that as all `v1.8.N` and `v1.7.N`  versions and `v1.9.0, v1.9.1, v1.9.2` versions, and if a server just supports `v1.9, v1.8` then that means all `v1.8.N` and `v1.9.0`. Or something like that at least.

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +and the two most recent `MINOR` versions past that. Given a cadence of about 1 release every 6 months,
```suggestion
and at least the two most recent `MINOR` versions past that. Given a cadence of about 1 release every 6 months,
```

I just don't want people to take this as an *encouragement* for servers to drop support for older versions "quickly", as time moves on I think we need to be a little careful in not assuming that the ecosystem moves as fast as it currently does (especially for custom clients for e.g. governments, which may not be actively developed).

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +and the two most recent `MINOR` versions past that. Given a cadence of about 1 release every 6 months,
I also wonder if we should specify this in terms of time? Given we are not committing to a particular release cadence (this doc talks both about 1 year and 6 months, for example, but I can also see us doing more frequent releases or have e.g. security releases)

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +Room versions are special in that they will essentially always be included in a Matrix release, even if
```suggestion
Room editions are special in that they will essentially always be included in a Matrix release, even if
```

?

2020-12-15 18:53 UTC, erikjohnston commented on proposals/2844-global-versioning.md
> +the Spec Core Team be able to blindside the community with a release for no justifiable reason.
I am not a fan of this section really. What concerns is this trying to suggest? If the spec core team want to do a few releases in quick succession then I don't see why this would cause huge problems? In some ways smaller, frequent releases are easier to deal with than infrequent large ones?

While we encourage implementations to update, they're under no obligation to do so if they feel like we're releasing to frequently, or don't have time to do so at the moment.

2020-12-16 11:42 UTC, richvdh commented on proposals/2844-global-versioning.md
> +Because the release schedule is well-advertised, it should be clear to everyone what the next non-patch
I've skimmed slightly, but I think I'm right in saying that there are comments from me, @dbkr and @erikjohnston all of which exhibit doubt about some of the "release process" bits here.

I don't see why we need to tie "global version number" and "release process" into the same MSC - to me they can stand separately, and it'll be easier to get agreement by doing so.

Indeed, I'm not even sure that "release process" needs an MSC - to me, it's not part of the spec itself.

2021-01-05 15:47 UTC, dbkr commented on proposals/2844-global-versioning.md
> +confusion with long-standing implementations.
fair enough

2021-01-05 15:54 UTC, dbkr commented on proposals/2844-global-versioning.md
> +the Spec Core Team be able to blindside the community with a release for no justifiable reason.
Yep, the paragraph was what I was talking about, and ok - sounds like the answer is that the processes formalised here are intended for some other doc not part of the spec (but that has been agreed on by the core team).

2021-01-05 16:08 UTC, dbkr commented on proposals/2844-global-versioning.md
> +MSC would require implementation validation and testing to be approved and thus would then be fine.
Have I understood this paragraph correctly? Some MSCs that require a new room version get opened, some or all of them get accepted, then when the spec is released, if the new version contains any changes that require room versions (ie. if that set of accepted MSCs is not empty) then the new spec release automatically makes a new room version with all (or maybe some?) of that set of MSCs, rather than having to get a separate MSC accepted to create & define that new room version?

2021-01-05 20:44 UTC, KitsuneRal requested changes
I think that the MSC would (have) benefit(ed) from splitting into 3: "deprecation", "brewing" (not even an MSC, probably) and "global version number"; but it's a bit late to split it by now. I'm generally fine with the approach but I have a concern on the deprecation part.

2021-01-05 20:44 UTC, KitsuneRal commented on proposals/2844-global-versioning.md
> +support v1.3, then it *should not* implement `/test` at all because it was removed.
That makes our API compatibility guarantees rather shaky across versions. `v1.2` API consumers apparently cannot rely on `/test` to actually be there any more because some servers would provide it and some wouldn't. From the API consumer perspective that's not much different from officially dropping the endpoint in `v1.2`.

I can agree that the actual functionality behind the endpoint might be reduced, slow to perform or even become somewhat nominal but if the endpoint is a part of the API definition the server should at least respond on it. Otherwise we can have embarrassing situations where both the server and the client claim to support `v1.2`, yet the client chokes on some endpoint not being there. As a client author, rather than stick the code watching for a sudden `501 Not Implemented` response from `v1.2`-compliant servers, I would announce to only support `v1.1`, and later state `v1.3` compliance once it's released and I get rid of `GET /example` usages - again, kind of defeating the purpose of deprecation as a graceful ramp-down.

2021-01-10 03:30 UTC, turt2live commented on proposals/2844-global-versioning.md
> +  small patches are done. Implementations do not need to worry about the patch version.
I have removed patch versions entirely.

2021-01-10 03:35 UTC, turt2live commented on proposals/2844-global-versioning.md
> +ideas through the stages as quickly.
I've removed this section from the proposal given it's a process change rather than a technical one - will discuss out of band (have recorded your comment elsewhere).

2021-01-10 03:35 UTC, turt2live commented on proposals/2844-global-versioning.md
> +process, the cutoff date is *not* enough for an implementation to switch to using stable endpoints.
Moving this conversation to somewhere else (procedure vs technical changes are being pulled out)

2021-01-10 03:36 UTC, turt2live commented on proposals/2844-global-versioning.md
> +the Spec Core Team be able to blindside the community with a release for no justifiable reason.
Pulling out all policy stuff

2021-01-10 03:42 UTC, turt2live commented on proposals/2844-global-versioning.md
> +support v1.3, then it *should not* implement `/test` at all because it was removed.
Yea, I'm increasingly being convinced that deprecation should mean that implementations must implement it as defined, but that it is likely to be removed in the next (or otherwise very soon) version. The deprecation would serve as a warning that something is about to disappear.

Implementations which happen to get started looking at the spec are unlikely to complete full spec implementation before we remove the endpoint, so they could conveniently skip implementation and either wait for removal in a later version or propose that it be removed with an MSC.

2021-01-10 03:44 UTC, turt2live commented
fyi to readers: all the policy stuff around spec core team process has been removed. It's planned to discuss it through another forum and potentially record as a proposal in the future.

Much of it is just saying "we'll figure it out later" anyways.

2021-01-12 15:03 UTC, richvdh commented on proposals/2844-global-versioning.md
> +support v1.3, then it *should not* implement `/test` at all because it was removed.
+1

2021-01-12 17:02 UTC, KitsuneRal approved these changes

2021-01-17 18:33 UTC, erkinalp requested changes
Do not forget the obligatory XKCD reference about standards

2021-01-17 18:33 UTC, erkinalp commented on proposals/2844-global-versioning.md
> +   which may be confusing if not sending the wrong message entirely. Though the system proposed here
```suggestion
   because there's no relevant specification document to link to. Even if there was, it would appear
   as though we were encouraging the idea of [forking a specification as a specification ourselves](https://xkcd.com/927),
   which may be confusing if not sending the wrong message entirely. Though the system proposed here
```

2021-01-17 19:58 UTC, merged

2021-08-03 17:47 UTC, richvdh commented
Next steps on this, while I remember:

- [ ] An update to https://spec.matrix.org/unstable/#specification-versions to document the way matrix spec versions work in the brave new world.
- [ ] An update to https://spec.matrix.org/unstable/client-server-api/#get_matrixclientversions to include `v1.1`, as documented at https://github.com/matrix-org/matrix-doc/blob/master/proposals/2844-global-versioning.md#endpoint-versioning
- [ ] Replace `%CLIENT_MAJOR_VERSION%` everywhere with `v3`. Note that this will break a load of anchors, so we'll need to find links to those.
- [ ] Do something about https://spec.matrix.org/unstable/#matrix-versions, which looks redundant?

2021-10-03 22:43 UTC, turt2live commented
Spec PRs:
* https://github.com/matrix-org/matrix-doc/pull/3420
* https://github.com/matrix-org/matrix-doc/pull/3421

I don't believe there's anything else remaining on this MSC to cover.

2022-02-22 17:51 UTC, deepbluev7 commented on proposals/2844-global-versioning.md
> +involved as well as the behavioural changes not being possible to implement. However, if an implementation
It might make sense to require an implementation even for changes like this in the future, because such large changes can always break (maybe badly written) clients in new and exciting ways: https://github.com/Nheko-Reborn/nheko/issues/957

For the same reason web clients, like Firefox and Chrome, take adding even a single digit to their version number very seriously: https://hacks.mozilla.org/2022/02/version-100-in-chrome-and-firefox/

2022-02-22 18:12 UTC, turt2live commented on proposals/2844-global-versioning.md
> +involved as well as the behavioural changes not being possible to implement. However, if an implementation
fwiw, the belief was that through several blog posts, notifying clients specifically, and general spec activity folks would be aware of this happening to make the required changes.

Even with an implementation, I don't believe it would have caught your specific failure mode.

2022-02-22 18:20 UTC, deepbluev7 commented on proposals/2844-global-versioning.md
> +involved as well as the behavioural changes not being possible to implement. However, if an implementation
Well, I did not know that someone added validation code for that 5 years ago. I didn't even know about Matrix at the time. Having a server that exports the new version and testing clients against it sounds not that unreasonable and because of how big and varied the WWW has become, browsers actually go through the effort to do that. Since Matrix is growing too, if there is ever a version format change again (which is very unlikely), it probably makes sense to go with a similar approach and actually test if anything expects the format not to change. Testing always trumps just reading about it and guessing if it will break anything. Anyway, this is not a complaint, just something I thought I might notify people about and which might make sense to keep in mind for the future.