Multiple SSO Identity Providers
matrix-org/matrix-doc pull request #2858
Opened 2020-11-09 12:13 UTC by t3chguy

[Rendered](https://github.com/matrix-org/matrix-doc/blob/204732099bb98ebed02eee8b546a9f10de805b21/proposals/2857-Multiple-SSO-Identity-Providers.md)

2020-11-12 11:32 UTC, richvdh reviewed
generally seems very sensible. a few minor thoughts here.

2020-11-12 11:32 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "id": "google",
can we specify an acceptable grammar for `id`? Which characters, max length, etc?

2020-11-12 11:32 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "mxc://..."
I wonder if http would be a better choice here. it seems like it will be more faff to set up the IdP on the server side if you have to stick the icon in the content repo (and make sure it doesn't get accidentally removed).

2020-11-12 11:32 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +identity provider as an option, that being the same as the user used to login with.
could you spell out what this should look like?

2020-11-12 11:32 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +Whilst in development use `msc2858.identity_providers` for the flow discovery and `/unstable`
these are supposed to be namespaced

```suggestion
Whilst in development use `org.matrix.msc2858.identity_providers` for the flow discovery and `/_matrix/client/unstable/org.matrix.msc2858/login/sso/redirect/{idp_id}`
```

2020-11-12 11:32 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "mxc://..."
are all these fields mandatory? seems like `icon` at least could be optional?

2020-11-13 00:15 UTC, auscompgeek commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "mxc://..."
In particular this could become problematic if we ever make accesses to the media repo authenticated in the future (see #2461).

2020-11-13 00:17 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "mxc://..."
great point, vdh already won me over :P

2020-11-13 11:56 UTC, auscompgeek commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +The `icon` field is the only optional field and should point to an icon representing the IdP.
Should the possible schemes be restricted to just `https`?

2020-11-13 12:01 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +The `icon` field is the only optional field and should point to an icon representing the IdP.
went one stage further and restricted the resource type, lmk what you think

2020-11-16 16:13 UTC, clokep commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
Do we care about localization at all? Is exposing the icons a privacy issue as these will all be fetched? (I don't think it is a big deal, but maybe worth mentioning...I guess they could be pulled by the homeserver and re-served if you wanted to avoid that.)

2020-11-16 16:13 UTC, clokep commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +If present then it must be an HTTPS URL to an image resource of type `image/png` or `image/svg+xml`.
This seems overly restrictive? It seems reasonable someone would want to link to favicons.

2020-11-16 16:13 UTC, clokep commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
A missing alternative is to essentially just use the backwards compatibility option and keep this fully an implementation detail of a homeserver (and out of the spec completely). I suppose that gives a not very nice user experience though:

1. User goes to login
2. User clicks "Login with SSO"
3. User choose IdP
4. User goes through SSO flow

The suggestions in here seem to allow combining steps 2 + 3. Is that why this is being proposed?

2020-11-16 16:16 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
yes, so that the "choose IdP" page can be branded for the client, rather than the homeserver.

2020-11-16 16:20 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
Right, yes, the above is not an alternative, it is just the best that is possible today, it is how Mozilla's EMS instance runs for example, their Auth0 IAM can be used to auth with Github/Google/Firefox and acts as that middle step. This is not user friendly as people are not too happy blindly clicking Continue with SSO (when choosing to register with user+pass or SSO) when they do not know what SSO IdPs are available.

2020-11-16 16:23 UTC, clokep commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
> it is how Mozilla's EMS instance runs for example, their Auth0 IAM can be used to auth with Github/Google/Firefox and acts as that middle step

I'm not sure this is a fair comparison though. For Mozilla, wouldn't you *still* need to show this page in order to bounce through Auth0? (Since they have an SSO delegation setup where Synapse uses Auth0 as an IdP, which is then backed by multiple user stores.)

2020-11-16 16:26 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
Good point, misread your original comment, doesn't solve the user confusion about what SSO entails specifically, users are familiar with `Continue with {Google,Apple,etc}` not `SSO` - this is primarily in consideration for on m.org being connected to multiple IdPs to simplify user onboarding for the Delight team.

2020-11-16 16:35 UTC, clokep commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
> Good point, misread your original comment, doesn't solve the user confusion about what SSO entails specifically, users are familiar with `Continue with {Google,Apple,etc}` not `SSO` - this is primarily in consideration for on m.org being connected to multiple IdPs to simplify user onboarding for the Delight team.

This makes sense! Being able to easily show those seems nice. (As well as showing those + password login all at once. But that's a client issue, not a spec issue ATM.)

Thanks for the explanation!

2020-11-16 16:37 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
The spec issue is the sane consistent way for the server to pass supported IdPs to the client rather than it being a Synapse+Element specific custom bodge.

2020-11-19 13:17 UTC, clokep commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
> than it being a Synapse+Element specific custom bodge.

I'm not sure where it was suggested for a custom Synapse+Element piece, but I agree that specing it is reasonable given the rationale.

I think the MSC would be stronger if it talked about how this would improve user experience.

2020-11-19 13:48 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
/me 's first MSC - appreciate the advice and will add a paragraph on that

2020-12-11 12:23 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +for the new endpoints.
Since we have no way to detect a 404 from the redirect endpoint, I think that using it will lock the server into supporting the unstable endpoint for the significant future. We should just use the stable endpoint immediately.

2020-12-15 17:15 UTC, turt2live reviewed
overall the MSC looks fine - just a couple small points/questions

2020-12-15 17:15 UTC, turt2live commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +which lets them choose between the available IdP options as a fallback.
Authoritative voice:
```suggestion
For the case of backwards compatibility the existing endpoint is to remain,
and if the server supports multiple SSO IDPs it should offer the user a page
which lets them choose between the available IdP options as a fallback.
```

2020-12-15 17:16 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
really, why? see https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r522034264

2020-12-15 17:26 UTC, erikjohnston commented
The description says:

```
note over Client: User clicks on one of the "Continue with" buttons
Client->+Server: GET /login/sso/redirect/$ID
Server->-Client: Returns the SSO IDP URL to redirect the user to
```

But isn't it the case that the client opens the browser at `/login/sso/redirect/$ID` which then 302s?

2020-12-15 17:29 UTC, t3chguy commented
> But isn't it the case that the client opens the browser at `/login/sso/redirect/$ID` which then 302s?

Yes, that is a better description for non-web clients. Will update the diagram

2020-12-15 17:57 UTC, dbkr commented
Agree with comments on grammar and mxc icons, otherwise looks fine!

2020-12-15 18:03 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +for the new endpoints.
I have spoken to the rest of the spec core team about this at some length, and the correct process is now somewhat clearer. It should be as follows:

 1. for now, clients look at `org.matrix.msc2858.identity_providers` in the `/login` response. If they find it, they open a browser at `/_matrix/client/org.matrix.msc2858/login/sso/redirect/:idp`. Clients and synapse know nothing about the stable property or the stable endpoint.
 2. later, MSC2858 completes FCP/spec
 3. synapse is updated to return *both* `identity_providers` and `org.matrix.msc2858.identity_providers`, and to support *both* `/_matrix/client/r0/login/sso/redirect/:idp` *and* `/_matrix/client/org.matrix.msc2858/login/sso/redirect/:idp`
 4. Clients are updated to support *both* stable and unstable properties, and use the *stable* endpoint if they saw a stable property, and the *unstable* endpoint if they saw only an unstable property.
 5. after some compatiblity period, both clients and servers can stop worrying about the unstable stuff.

That's fiddly, because it means we need to do another round of dev after FCP, but it's fundamental to the way the spec process is designed to avoid presenting faits accomplis.

There is a key point here, which I had completely overlooked earlier, and that is: clients *must not* use the *unstable* endpoint if they see only a *stable* property. The reason for this is that any client doing so will not degrade gracefully when they are used with a server that supports the stable API and has dropped support for the unstable API.

2020-12-15 18:10 UTC, turt2live commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
Clients are resistant to making requests to random servers if they don't have to, and an MXC URI at least ensures the client will be making a request to the homeserver. This also feels like the sort of thing that the IdP doesn't have to deal with an the server could intercept/fix on behalf of the idp

2020-12-15 18:16 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
certainly the IdP doesn't have to deal with it. It's just a pita, as a synapse admin, to have to upload media to a content repo when I'm trying to set up SSO.

I suppose on the server we can define some "magic" MXCs which can be used for IdP logos, but that's a bunch of work I'd prefer to avoid.

2020-12-15 18:26 UTC, anoadragon453 commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
Previous conversation on these: https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r522034264

2020-12-15 18:29 UTC, turt2live commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
@richvdh my only other argument would be consistency with the rest of the spec and modern day expectations. Server admins should be somewhat used to having to upload content to the media repo to get avatars by now, so the server might only need to provide instructions. https://t2bot.io/mediabot/ and similar bots also exist to help ease the pain of getting said MXC URI for purposes exactly like this.

2020-12-15 18:38 UTC, turt2live commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +for the new endpoints.
ftr it's `/unstable/org.matrix.msc2858`, not the bare `/org.matrix.msc2858`

2020-12-16 10:04 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
Once the Media Repo is authenticated how would this work?

2020-12-16 20:25 UTC, turt2live commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
that's not a problem for this MSC to solve.

2020-12-17 09:54 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
> Once the Media Repo is authenticated how would this work?

It would be reasonable for the server to only apply authentication selectively.

2020-12-17 11:09 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +for the new endpoints.
sorry, yes.

2021-01-14 17:59 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +```
+1. We should update this.

(which is annoying, because I have *just this second* landed a PR which implements the current wording)

2021-01-15 21:19 UTC, KitsuneRal commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +homeserver service provider to not leak the client's IP address unnecessarily.
I'm not really convinced if that should be `https:`, given that clients normally only use `https:` to interact with the homeserver via CS API. Restricting the URL to point to an image resource is not quite enforceable on the client side before making a request; only after the response headers are received, the client can use Content-Type, e.g., to find out if it's about to receive an image or not. Also - what if I hit a redirect to an image resource, is it legit or not (depends on where the redirect leads?)? An `mxc` address looks a bit less controversial, and most clients already know what to do with `mxc` resources anyway.

Yet another way would be to add one more endpoint, e.g. `/login/sso/{idp_id}/favicon.ico` (without `redirect` as it's not necessarily a redirect), and require homeservers to have it configured for each supported `{idp_id}`. That doesn't preclude lazy homeserver administrators from configuring a redirect on the homeserver's reverse proxy, leading to potential IP address harvesting hole with no reasonable safeguards on the client side. The `mxc` option looks safest to me in this regard.

2021-01-18 09:29 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +homeserver service provider to not leak the client's IP address unnecessarily.
There is already a thread above about using `mxc` URIs https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r543513811

2021-01-19 13:21 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +UIA.
as discussed in chat: looks like we're not using this in clients currently, and it's annoying to implement in synapse. Let's remove it.

If we wanted to support it, we'd probably also want to allow the client to choose the SSO mechanism.

2021-01-19 13:26 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +https://github.com/matrix-org/matrix-doc/pull/2858.
```suggestion
https://github.com/matrix-org/matrix-doc/pull/2758.
```

2021-01-19 13:59 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +except would allow the server to forward the user directly to the correct IdP.
what is the expected behaviour if the IdP ID is unknown? 404 with some error code?

2021-01-20 15:50 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +                    "icon": "https://..."
we're now mandating MXC URIs.

2021-01-20 15:50 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +UIA.
now removed.

2021-01-20 16:40 UTC, richvdh requested changes

2021-01-20 16:40 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +https://github.com/matrix-org/matrix-doc/pull/2758.
sorry, I'm vacillating on this (previously discussed at https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r543514840).

Given that this id doesn't convey any semantic meaning between implementations (it's just an arbitrary identifier chosen by the HS admin), I don't think there's any value in requiring that it be namespaced with `m.` or `com.example.`.

Rather, this is a "completely opaque ID", which is covered by the proposal in [MSC1597](https://github.com/matrix-org/matrix-doc/issues/1597) (though I think that proposal is currently wrong, per https://github.com/matrix-org/matrix-doc/pull/1597#discussion_r561097599.

TL;DR: I think we should go back to @t3chguy's original proposal of allowing `[0-9a-zA-Z._~-]`, though set the max length to 255 for consistency with the proposal in MSC1597.

2021-01-20 17:09 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +except would allow the server to forward the user directly to the correct IdP.
I'm going to have synapse return a 404 with `M_NOT_FOUND`.

2021-01-27 13:00 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +https://github.com/matrix-org/matrix-doc/pull/2758.
switched back in 0c18f836

2021-01-27 13:03 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +except would allow the server to forward the user directly to the correct IdP.
well, that's not great, because this is supposed to be an HTML page that is served in the browser rather than a REST endpoint.

The correct solution here is to specify an error protocol whereby we can return an error to the client rather than a `loginToken`, but that's rather out of scope here. (Guess what, OIDC has a spec here.)

I'll leave this unspecified for now

2021-01-27 13:04 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +## Alternatives
we ought to add some thoughts about OIDC here.

2021-01-27 14:26 UTC, t3chguy commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   the IdP.  If present then it must be an MXC URI to an image resource.
```suggestion
   the IdP. If present then it must be an MXC URI to an image resource.
```

2021-01-27 17:42 UTC, erikjohnston commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
I wonder if these need to be namespaced, or if they can be e.g. the brands canonical address, e.g. `"facebook.com"`? Otherwise I can see us ending up with multiple different namespaced values for any new brand, as different servers use different namespaces?

2021-01-27 21:05 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
I see your point, but basically the logic goes:
 * this is an identifier which is used between Matrix implementations to refer to a given concept, and we want to allow developers space to add their own identifiers for extensions.
 * this is exactly what MSC2758 is intended to cover
 * I'm not entirely convinced that people would be much more likely to converge if we said "pick something sensible based on the brand".

2021-01-28 10:28 UTC, erikjohnston commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
Yeah. I'm a bit on the fence about it, but something feels a bit off that we are having to curate a list of identifiers for other brands. 

1. I'm not sure I totally but that this needs to be extensible in such a way. The only situation I can really think of is having an internal SSO that you still want branded, but it would be odd if that didn't have an associated domain you could use as the identifier.
2. Using the domain of the brand means we might end up with something like example.com vs example.org, but that naively a) feels less likely to happen and b) there would only be a few choices per brand, rather than a free for all with `re.jki.*` and `org.matrix.*` etc.

TBH I have a horrible suspicion that what would happen in practice is that people would just start using `org.matrix.instagram` without asking, which feels like the worst of all worlds

2021-03-01 19:19 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
we've shipped the experimental implementation with namespaced identifiers. If people feel strongly about it, we can change it before finalisation, but I'm not convinced it would be an improvement.

2021-03-01 19:25 UTC, richvdh commented
This is now implemented in Synapse (https://github.com/matrix-org/synapse/pull/9183, mostly), element-web (https://github.com/matrix-org/matrix-react-sdk/pull/5426 and various later follow-ups), element-android and element-ios. More relevantly, it can be observed in action on the matrix.org homeserver.

I therefore think the time is right to bring it into the real spec, so:

@mscbot fcp merge

2021-03-01 22:13 UTC, ara4n approved these changes

2021-03-01 22:13 UTC, ara4n commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +and user's have to blindly click `Sign in with SSO` without any clue as to what's hiding on the other
```suggestion
and users have to blindly click `Sign in with SSO` without any clue as to what's hiding on the other
```

2021-03-01 22:13 UTC, ara4n commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
i've re-read this thread about 5 times and i still don't understand why you wouldn't refer to facebook as `com.facebook` rather than `org.matrix.facebook`. (i also don't understand why we use `org.matrix.facebook` rather than `m.facebook` if we're making it a matrix-specific prefix).

2021-03-01 22:49 UTC, uhoreg commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
(adding in to the bikeshedding)  Yeah, `org.matrix.google` seems really weird to me, and specifying a list of recognized brands within the spec seems suboptimal, as it 1) appears like we are endorsing certain brands, and 2) adds unnecessary friction in managing brands (do we need an MSC to add support for Microsoft accounts?).  I think that my ideal would be that brands would be of the form `com.google` (i.e. based on the brand's domain, rather than `org.matrix.[brandname]`), and that the brands IDs for common providers would be agreed on outside of the spec in some place, maybe in a first-come-first-served-as-long-as-it's-sensible manner. (e.g., I don't need to talk to anyone if I want to configure my client to use my own private SSO provider, but if I want to configure it to use Microsoft accounts, I should go somewhere and see if anyone else has claimed an identifier for Microsoft accounts, and if not, then I can say "Hey folks, I think we should use `com.live` for Microsoft accounts", and then everyone else who wants to use Microsoft accounts would use the same ID.  But if I say "we should use `evil.monopolists` for Microsoft accounts", then people will say "No, you're an idiot" and use something else instead.)

2021-03-02 13:11 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
@ara4n wrote:

> i still don't understand why you wouldn't refer to facebook as `com.facebook` rather than `org.matrix.facebook`.

Well, the idea was that the identifier here is being defined by the Matrix organisation, rather than Facebook themselves - hence giving it an `org.matrix` prefix rather than a `com.facebook` prefix. The whole idea of MSC2758 is that you don't use identifiers in other organisations' namespaces without their agreeing to it.

I can concede that perhaps this situation is a special case where it makes sense to use an identifier in a different organisation's namespace on their behalf, though I still say this is debatable.

If we *did* switch to brand identifiers based on the brand's domain rather than `org.matrix` - ie, we abandon the convention that the namespace only be used by the organisation that owns the domain in question - why bother with MSC2758 at all? Shouldn't we just use `facebook.com` as @erikjohnston suggested?

> (i also don't understand why we use org.matrix.facebook rather than m.facebook if we're making it a matrix-specific prefix).

yeah, nor me. I can't remember. There's also an argument they should be `io.element.*` prefixes, since it's the Element clients that actually care what this is set to (Synapse is completely agnostic.)

2021-03-02 13:11 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
@uhoreg wrote:

> specifying a list of recognized brands within the spec seems suboptimal, as it 1) appears like we are endorsing certain brands, and 2) adds unnecessary friction in managing brands (do we need an MSC to add support for Microsoft accounts?). 

Well we kindof are endorsing certain brands, at least with our Element hats on, by baking in support for certain brands into the Element clients, and it's one of the reasons that I'm not entirely happy with this whole solution and that I think we might want to revisit it to see how we would handle it in an OAuth2 fashion. That said...

> that the brands IDs for common providers would be agreed on outside of the spec in some place, maybe in a first-come-first-served-as-long-as-it's-sensible manner

An external registry is an interesting solution to this problem. It's something we've not really adopted in Matrix previously, but obviously the IETF does just that in many places. We'd need to be careful of having anything too heavyweight (would a text doc in the matrix-doc repo do for now? It would be easy for people to PR against?), but I'd be pretty happy with this as a solution. @ara4n do you have any thoughts on this approach?

2021-03-02 13:16 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
@richvdh wrote:

> why bother with MSC2758 at all

I suppose this is a simplification. MSC2758 has useful things to say about the grammar (allowed characters, min/max lengths) beyond the convention of splitting up the namespace. If we went with `facebook.com` we'd have to make a *different* definition of the grammar specific to this field.

2021-03-02 17:08 UTC, uhoreg commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
> Well we kindof are endorsing certain brands, at least with our Element hats on, by baking in support for certain brands into the Element clients,

Yes, but I personally see a big difference between endorsing something as Element, versus endorsing something as the Foundation.

> (would a text doc in the matrix-doc repo do for now? It would be easy for people to PR against?)

Yeah, I think that would work.  PRs would allow people to see what providers are already being proposed, and whoever reviews the PR can act as the "as-long-as-it's-sensible" filter.

2021-03-02 19:18 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
> Yes, but I personally see a big difference between endorsing something as Element, versus endorsing something as the Foundation.

yes, fair.

Ok, so in answer to the concerns raised here, I've factored out a separate registry doc at https://github.com/matrix-org/matrix-doc/blob/t3chguy/msc/multi-sso/registry/m.login.sso_brand.md. Please could you take a look to see if you think it is appropriate (and also feel free to suggest how it could be formatted in a way that makes it legible)?

2021-03-02 19:19 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
(note that I've also proposed a switch from `org.matrix.facebook` to `com.facebook`.)

2021-03-02 19:45 UTC, turt2live requested changes

2021-03-02 19:45 UTC, turt2live commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
This should be under the proposal tree, or in the proposal itself. The location and spec writing portion is done as a later stage and might not appear in this form.

2021-03-02 19:49 UTC, turt2live commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
I'm a bit concerned here that a registry is yet another thing we have to maintain. The information should be in the rendered spec, like we do for the SAS Emoji: there's a friendly format for consumption, though the spec itself includes the table of emoji anyways.

2021-03-02 19:49 UTC, turt2live commented
@mscbot concern https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r585858048

Otherwise the general idea seems sensible to me

2021-03-02 23:19 UTC, richvdh commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
Fine, I can vape this and move the content back into the proposal. I thought it might be helpful to factor it out.

2021-03-03 00:34 UTC, turt2live commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
urgh, I missed the whole thread that was talking about this - sorry. (It would be really great if github showed older, unresolved, threads on the diff)

This problem reminds me a bit of widget types where we originally set out to specify `m.googledocs` and such, but ultimately decided not to spec them because it overly endorsed them as partners to Matrix without the contracts to back that up. A registry probably makes the most sense, though it does raise questions of who is responsible for approving/merging changes to said registry.

2021-03-03 00:35 UTC, turt2live commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
A registry also sounds extremely close to opening the door for "my custom event, org.example.temperature, is described like so" which is something we've previously avoided with a passion. While we can put a warning up saying that the registry isn't for that, it would set precedence.

2021-03-03 10:38 UTC, erikjohnston commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
I like the idea of the registry. I think its fine to say that we will approve anything sensible that comes along,  e.g. non-offensive names, matches the company name/domain as close as possible, isn't too close to an existing name (e.g. let's not accept `com.goggle`), and maybe not a completely new/unknown thing. I'd be happy for any spec core team member, or someone they've delegated to, to approve additions (in practice I'd imagine this working as someone does a matrix-doc PR, it gets mentioned to the spec core team, if no one shouts it gets approved). 

In terms of styling, I'd be tempted to format it as a table to make it easier to read, but ymmv. But given we can spruce it up later, I don't think it matters for now.

On the ID front, to try and articulate why I feel a bit conflicted on the format:

* We're using `com.facebook` to reference an external brand, rather than as a namespace, so I think it feels a bit weird to format it as a namespace. As mentioned, we can still use the rest of the grammar (I think there's going to be more places where the rest of the grammar will be useful, but where namespaces don't make sense).
*  By formatting it as a namespace it risks making it look like this has been done by e.g. facebook, as that is what namespaces are meant to indicate, whereas in reality it has nothing to do with them.
* This runs the (rather small) risk of conflicts, e.g. facebook write a custom SSO and name it `com.facebook` (as that's the namespace to use for unspecced/unregistered stuff), but actually someone has already gone and registered it and started using it in the wild.
* The flip side, there's virtue in consistency and being able to tell people to just use the standard style format. Also, flipping it around to have e.g. `facebook.com` doesn't solve the conflict from the previous item, unless we start mixing and matching namespace vs domains.
* If we're having a registry then we don't even need to make them domains, we could just do `facebook` (since the disambiguation is handled by the registry), and then custom ones are namespaced as usual.

I do feel like we shouldn't be forcing things into namespaces just because we have a grammar for doing so, but also I think this is a bit of a subtle edge case where there's a mix between pointing at brands/domains vs. allowing custom values.

In an attempt to get to a conclusion to this, I'd be happy with the following formats, roughly in order of preference. All assume that we're following the rest of the grammer in MSC2758:
1. Use the brand name, e.g. `facebook`, for registered providers. Perhaps prefixed with `m.*` or `r.*` (where `r` is for "registered", and used to try and differentiate between "endorsed by the foundation" vs "this is a registered constant", any other single letter will do). Custom providers would be namespaced.
2. Use `com.facebook`. I think its a bit of a toss up between using someone else's namespace vs forever associating an arbitrary domain with the brand, e.g. `com.google.facebook` would be awful if google proposed the facebook provider (slightly less awful if we use `org.matrix.*`, but still).
3. `org.matrix.facebook`.

2021-03-03 10:38 UTC, erikjohnston commented
@mscbot concern https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r565506802 ─ ID format for providers

2021-03-03 11:10 UTC, richvdh commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
@turt2live generally there seems to be agreement from the rest of the SCT that a registry isn't *great*, but is probably the least worst solution here. Can I take it that your concerns about the concept of a registry aren't blocking?

2021-03-03 11:56 UTC, richvdh commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
@turt2live I've removed the registry document for now and replaced it with a paragraph in the doc (https://github.com/matrix-org/matrix-doc/pull/2858/files#diff-23a449bd815bfd357851e38da761fd5d5d2aef4fc26f50cbefe581e64ecafaa7R87-R91). Does that satisfy your primary concern in this thread?

2021-03-03 13:04 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
This thread is getting a bit epic. To try to keep it on track, let's separate discussion of the "registry" concept from the format of the identifiers themselves: if anybody has any outstanding concerns about the registry concept, please take them to a separate thread.

OK, so on the identifiers themselves, @erikjohnston wrote:

> * We're using `com.facebook` to reference an external brand, rather than as a namespace, so I think it feels a bit weird to format it as a namespace.

[and other arguments against the reverse-domain-namespacing].

I think I basically agree here. This isn't really a proper use of the namespacing stuff, and is why I originally went for `org.matrix.facebook`. As I wrote above, possibly we can claim to be registering the identifier on behalf of facebook, but I don't really think that holds water.

> 1. Use the brand name, e.g. `facebook`, for registered providers. Perhaps prefixed with `m.*` or `r.*` (where `r` is for "registered", and used to try and differentiate between "endorsed by the foundation" vs "this is a registered constant", any other single letter will do). Custom providers would be namespaced.

`m.facebook` basically takes us back to where we started and @ara4n was [arguing fairly hard against](https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r585087217), modulo replacing `org.matrix.` with `m.`.

2021-03-03 13:06 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
Let me try to summarise the decision tree here:

 * Should we use a reverse-domain-namespaced identifier?
   * On the plus side: it's what MSC2758 requires, so doing anything else requires inventing yet another grammar and documenting it in the spec (obviously we can base the grammar heavily on MSC2758)
   * Also on the plus side: if we do it properly (ie, use `m.` or `org.matrix.` or `io.element.`), it reduces the chances of a conflict. However, I think this is also mitigated by a low-friction registry.
   * On the down side: all of the available options seem to suck.
 * If yes (reverse-domain-namespacing), what should the prefix be?
   * the brand itself, eg `com.facebook`: This feels odd: we're reversing the domain to make it namespacey, but not *actually* treating it as a proper namespace, since we aren't facebook. Or:
   * Something else, based on who "registered" the identifier. These could result in horror-shows like `com.google.facebook`. If we go down this path, we need to decide what to use for the initial set. Suggestions I've seen are:
     * `m.`: I feel like this is only really appropriate if we're making the identifiers part of the *core* spec, and doing so raises legitimate concerns around the Matrix protocol endorsing particular external brands, as well as making it a PITA to add more brands.
     * some other special prefix, eg `r.`: I see where you're going, but adding a new dimension to the namespace isn't a can of worms I feel inclined to open. I'm also not sure it buys a great deal in this instance.
     * `io.element`
     * `org.matrix`
 * If not (un-namespaced identifiers), then I think the choices are either a raw identifier (`facebook`) or a dns name (`facebook.com`). As Erik has said: given we're relying on a registry to avoid clashes, I'm struggling to see why a dns name is preferable here.

In short, I think these are the options.
 * `com.facebook`
 * `m.facebook`
 * `r.facebook`
 * `io.element.facebook`
 * `org.matrix.facebook`
 * `facebook`
 * `facebook.com`

I'm not going to change anything immediately as it's clear that there is still disagreement among the Spec Core Team about which is preferable and I've flip-flopped enough on this. What I suggest is that folks express preferences or vetos, and in a couple of days, I'll try to see if any consensus has formed.

2021-03-03 13:09 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
Personally speaking: I'm now reasonably convinced that namespacing these identifiers does more harm than good, so my preference list would look like:

* `facebook`
* `facebook.com`
* `io.element.facebook`
* `com.facebook`
* `m.facebook`
* `org.matrix.facebook`
* `r.facebook`

2021-03-03 14:37 UTC, ara4n commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
i'm quite happy to just call it `facebook` as long as we have a light-weight registry somewhere.

2021-03-03 17:54 UTC, turt2live commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   To reduce confusion over which indentifier should be used for each brand
```suggestion
   To reduce confusion over which identifier should be used for each brand
```

2021-03-03 17:54 UTC, turt2live commented on registry/m.login.sso_brand.md
> +# `m.login.sso` `brand` identifier registry
yes, though before this lands in spec I'd like for us to discuss how we manage that registry as a SCT.

2021-03-03 17:54 UTC, turt2live commented
@mscbot resolve https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r585858048

2021-03-04 09:50 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
@dbkr @uhoreg @anoadragon453 @KitsuneRal speak now or forever hold your peace

2021-03-04 17:18 UTC, uhoreg commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
If we're using a registry, then I think that preference for identifier formats is mostly aesthetic.  The main technical issue that I see is: if I set up my own ID provider and build my own client and want to display my own branding without needing to pollute the public registry, is there an ID that I can use?  I think possible answers to that are:

- use namespacing (which means that we end up with the registered names like `io.element.facebook`, `com.facebook`, `m.facebook`, `org.matrix.facebook`, or `r.facebook`.  Or we say that registered names are of the form `facebook` and can't contain a period, so proper namespaced names are private)
- define a prefix for private use, like the `X-` headers in HTTP or emails.  Though I think they stopped doing that in one of those, which means we probably shouldn't do it either.
- declare that it's a niche case and say that I should just use whatever ID I want to, without conflicting with current registered ID.  In the event that a future registered ID conflicts with the ID that I chose, then I should just pick a new ID and roll out a new version of my custom client, which should not be too horrible because it's a private deployment and I have control over these things.

I'd be fine with any of those options, but I think we should decide on one.

From an aesthetic standpoint, `org.matrix.facebook` looks to me like something that matrix.org is hosting.  Similarly with `io.element.com`.  I don't think that `m.` necessarily needs to be reserved for things that are in the spec -- I think that `m.` just needs to mean that it's something controlled by the Foundation.  Aside from that, I don't have very strong preferences among the options, so my preference list would basically be `org.matrix.facebook` and `io.element.com` at the bottom, and everything else at the top.

2021-03-09 14:00 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
@uhoreg  says:

> The main technical issue that I see is: if I set up my own ID provider and build my own client and want to display my own branding without needing to pollute the public registry, is there an ID that I can use?

Good point. Following the advice of https://tools.ietf.org/html/rfc6648, I am minded to go with your option three.

2021-03-09 14:41 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +    * `org.matrix.twitter`
right, I've switched to `facebook`, which hopefully resolves this thread

2021-03-09 14:45 UTC, erikjohnston commented
@mscbot resolve [#2858 (comment)](https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r565506802) ─ ID format for providers

2021-03-09 14:45 UTC, erikjohnston commented
@mscbot resolve https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r565506802 ─ ID format for providers

2021-03-09 16:44 UTC, uhoreg commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +some sensible name follosing the advice of [RFC6648 sec
```suggestion
some sensible name following the advice of [RFC6648 sec
```

2021-03-09 16:52 UTC, dbkr commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   Description: Logos available at https://github.com/logos.
Think something went wrong pasting the description in here?

2021-03-09 16:52 UTC, dbkr commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   Description: Login in via the hosted https://gitlab.com SaaS platform.
Also should this have quotes, consistent with the others?

2021-03-09 16:52 UTC, dbkr commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +essential.
Feels like this might need expanding on a bit - the server just sends them straight to the SSO page of the provider they logged in with in the first place?

2021-03-09 16:54 UTC, dbkr commented
@mscbot concern https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r590544108 - How UI auth works

2021-03-09 16:54 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +essential.
kindof up to the server, but yes that would be one sensible approach.

2021-03-09 16:55 UTC, KitsuneRal reviewed
Overall LGTM, one small question remains.

2021-03-09 16:55 UTC, KitsuneRal commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   Description: "Sign in with Apple". See
Are these descriptions normative (per particular IdP's guidelines, as mentioned below in the MSC) or just suggestions? If they are suggestions, is there any particular reason they are "Sign in", "Continue" or "Log in" depending on IdP?

2021-03-09 16:58 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   Description: Logos available at https://github.com/logos.
well I agree it's not very elegantly phrased, but I'm not really sure what else I have to say here. We're just trying to give guidance for what client developers might show in their clients when they see `brand: github`.

2021-03-09 17:03 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   Description: Login in via the hosted https://gitlab.com SaaS platform.
```suggestion
   Description: Logos available at https://about.gitlab.com/press/press-kit/.
```

2021-03-09 17:05 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   Description: "Sign in with Apple". See
right, I think this speaks to some of Dave's questions too. They are referring to the various platforms' "sign in" offerings, where they have such concepts, since they tend to come with their own branding requirements.

2021-03-09 17:20 UTC, dbkr commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +   Description: Logos available at https://github.com/logos.
Fair enough, it just looked like it should have been 'Sign in with GitHub" consistent with the rest (although they're also not consistent with what element-web does which is to just say, "Continue with $name"

2021-03-09 18:12 UTC, richvdh commented on proposals/2858-Multiple-SSO-Identity-Providers.md
> +essential.
updated this section

2021-03-09 18:17 UTC, dbkr commented
@mscbot resolve https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r590544108

2021-03-09 18:20 UTC, dbkr commented
@mscbot resolve https://github.com/matrix-org/matrix-doc/pull/2858#discussion_r590544108 - How UI auth works

2021-03-14 18:52 UTC, merged

2021-05-04 01:35 UTC, turt2live commented
Merged 🎉