Allowing widgets to read events in a room
matrix-org/matrix-doc pull request #2876
Opened 2020-11-24 00:47 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/widgets-read-events/proposals/2876-widgets-reading-events.md)

2021-01-31 04:20 UTC, erkinalp requested changes
Several suggested changes and a spelling fix

2021-01-31 04:20 UTC, erkinalp commented on proposals/2876-widgets-reading-events.md
> +can reject the request with an error.
```suggestion
The `limit` is the number of events the widget is looking for. The client can arbitrarily decide to
return less than this limit, though should never return more than the limit. For example, a client
may decide that for privacy reasons a widget can only ever see the last 5 room messages - even though
the widget requested 25, it will only ever get 5 maximum back. When `limit` is not present it is
assumed that the widget wants as many events as the client will give it. When negative, the client
shall reject the request with an error.
```

2021-01-31 04:20 UTC, erkinalp commented on proposals/2876-widgets-reading-events.md
> +* For all other events, 25.
```suggestion
* For `m.room.member` state events, no limit.
* For `m.reaction` events, 100.
* For all other events, 25.
```

2021-01-31 04:20 UTC, erkinalp commented on proposals/2876-widgets-reading-events.md
> +challenges on the part of the widget developer.
```suggestion
Widgets could be powered by a bot or some sort of backend which allows them to filter the room state
and timeline themselves, however this can be a large amount of infrastructure for a widget to maintain
and the user experience is not as great. The client already has most of the information a widget would
need, and trying to interact through a bot would generally mean slower response times or technical
challenges on the part of the widget developer.
```

2021-05-04 02:02 UTC, turt2live commented on proposals/2876-widgets-reading-events.md
> +can reject the request with an error.
"Shall" isn't quite right for this sort of thing given the context of widget API error handling. Please include rationale with your suggestions.

as an aside, when making suggestions please only make the suggestion on the line(s) you're changing, not the whole paragraph. It's extremely difficult to read otherwise, and likely to be rejected purely for being too long/spammy.

2021-05-04 02:03 UTC, turt2live commented on proposals/2876-widgets-reading-events.md
> +* For all other events, 25.
Sure, a client can do this without our recommendations.

2021-05-04 02:04 UTC, turt2live commented on proposals/2876-widgets-reading-events.md
> +challenges on the part of the widget developer.
applied manually

2021-05-14 19:54 UTC, turt2live commented
This is getting rolled into https://github.com/matrix-org/matrix-doc/pull/2762 as it's basically the same action as receiving events.

2021-05-14 19:54 UTC, closed without merging