MSC2918: Refresh tokens
matrix-org/matrix-doc pull request #2918
Opened 2020-12-18 13:42 UTC by sandhose

[Rendered](https://github.com/sandhose/matrix-doc/blob/sandhose/msc/refresh-token/proposals/2918-refreshtokens.md)

Related: #1787, #2615

2020-12-18 14:03 UTC, clokep commented on proposals/2918-refreshtokens.md
> +`POST /refresh`
Guessing this is `/_matrix/client/r0/refresh`?

2020-12-18 14:03 UTC, clokep commented on proposals/2918-refreshtokens.md
> +The login API returns two additional fields:
How would this be done in a backwards compatible manner? (How would the server know that the client now supports refresh tokens?)

2020-12-18 14:03 UTC, clokep commented on proposals/2918-refreshtokens.md
> +This must be updated to reflect that devices are bound to a session, which are created during login and stays the same one after refreshing the token.
Drawing a conclusion from above:

> The Matrix server doesn't have to make the old access token invalid, since its lifetime is short enough. 

Does this also meaning that a session/device could have multiple access tokens at once?

2020-12-18 14:14 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +`POST /refresh`
Shouldn't MSCs use an unstable prefix? Not entirely sure how that works

2020-12-18 14:14 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +This must be updated to reflect that devices are bound to a session, which are created during login and stays the same one after refreshing the token.
If the Matrix server chooses to do stateless validation of tokens, yes that would be the case.
For example, if the server uses JWTs as access token, you might have a token that looks like this decoded:

```json
{
  "iat": 1516239022,
  "nbf": 1516239022,
  "exp": 1516239082,
  "iss": "https://matrix.connecteu.rs",
  "mxid": "@quentin:connecteu.rs",
  "device_id": "XXYYZZ"
}
```

But in any cases, clients should not rely on the old access token being still valid I think

2020-12-18 14:16 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +The login API returns two additional fields:
Not sure about that. Maybe a new parameter in the login API?

2020-12-18 14:16 UTC, clokep commented on proposals/2918-refreshtokens.md
> +`POST /refresh`
They should describe the final API endpoint assuming it is accepted and include unstable information in the "Unstable prefix".

2021-01-14 17:31 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +`POST /refresh`
This was fixed by https://github.com/matrix-org/matrix-doc/pull/2918/commits/f8dad2acd6b554c331793cc642c9155542f5b8c7

2021-01-14 17:31 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +The login API returns two additional fields:
This was fixed by https://github.com/matrix-org/matrix-doc/pull/2918/commits/f8dad2acd6b554c331793cc642c9155542f5b8c7

2021-05-04 16:43 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +- `expires_in`: The lifetime in seconds of the access token.
most (all?) time-related fields in Matrix are measured in milliseconds, not seconds. I'd recommend following suit, unless there are compelling reasons to go with seconds, like OAuth conventions.

2021-05-06 12:41 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +- `expires_in`: The lifetime in seconds of the access token.
This is directly inspired from [OAuth 2.0](https://tools.ietf.org/html/rfc6749#section-4.3.3). There isn't a real reason to keep it close to OAuth 2.0 here though, so `expires_in_ms` might make more sense here to keep it consistent

2021-05-20 10:11 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +- `expires_in`: The lifetime in seconds of the access token.
Resolved with https://github.com/matrix-org/matrix-doc/pull/2918/commits/0e615f78757ac2cb8bafacd2eba69deac00f6967

2021-05-20 10:14 UTC, sandhose commented
Just pushed two changes:

 - the registration API should also issue a refresh token (unless login is inhibited)
 - token expiration is now in milliseconds instead of seconds

2021-06-02 12:51 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
we should emphasize that this also applies to ASes (see https://matrix.org/docs/spec/application_service/r0.1.2#server-admin-style-permissions): ASes which use the access token returned by that endpoint will need to refresh it.

2021-06-03 15:32 UTC, sandhose reviewed
A few recent changes:

 - https://github.com/matrix-org/matrix-doc/pull/2918/commits/d433e3b7f19c771411a2a2098fab8cc765d85bf6 specify what error code should be used [related to this](https://github.com/matrix-org/synapse/pull/9450/files#r643912427))
 - https://github.com/matrix-org/matrix-doc/pull/2918/commits/b320001eb431e4bc0896095f302c9d2fc6c1bcd6 suggest what to do with refresh token revocation on use (this is what is implemented in Synapse)
 - https://github.com/matrix-org/matrix-doc/pull/2918/commits/87566c3217b44512e5dd41543ffe05d066c75e12 clarify that it also applies to ASes

2021-06-17 10:54 UTC, sandhose reviewed
I'm pretty confortable with the current state of the MSC. The implementation in Synapse is pretty much done and working (https://github.com/matrix-org/synapse/pull/9450) and in a working state in Hydrogen (https://github.com/vector-im/hydrogen-web/pull/235).

2021-06-17 10:54 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +In both cases, the server must reply with a `401` HTTP status code and an `M_UNKNOWN_TOKEN` error code.
It could also be split here, maybe having rather a `403` / `M_FORBIDDEN` (or another code?) if the token was already used

2021-06-30 17:55 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +Since this request can get lost in flight, the server should delay this revocation to when the client uses the new access token or the new refresh token for the first time.
please wrap all your lines at about 80 characters.

2021-06-30 17:55 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +Requests are currently authenticated using non-expiring, revocable access tokens.
```suggestion
In Matrix, requests to the Client-Server API are currently authenticated using non-expiring, revocable access tokens.
```

2021-06-30 17:55 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +This MSC make the access tokens expiring and introduces refresh tokens to renew them to fight against token replay attacks.
```suggestion
This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
```

2021-06-30 17:55 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +Since this request can get lost in flight, the server should delay this revocation to when the client uses the new access token or the new refresh token for the first time.
```suggestion
A new refresh token is also issued. The existing refresh token remains valid until the new access token (or refresh token) is used, at which point it is revoked. This allows for the request getting lost in flight.
```

2021-06-30 18:00 UTC, richvdh commented
this looks good to me.

@mscbot fcp merge

2021-06-30 18:09 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
we should make it clear that these are *optional* fields. If they are not present, a client should assume that its `access_token` will not expire.

2021-06-30 18:18 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
a few thoughts about backwards-compatibility and breaking changes.

This MSC is a bit unusual in that it proposes something that will definitely break compatibility with old clients, yet isn't technically a breaking change in the API because no existing endpoints/properties/etc are being removed.

I think it's important that the expiry of access tokens is left as optional (to be determined by the server), so that we don't have a hard compatibility break in the spec. So, a client that supported spec `vNext` would *have* to support refresh tokens, though a server that supports spec `vNext` doesn't necessarily have to make use of them.

Then, server implementations/admins can independently decide when they have few enough legacy clients to switch to issuing expiring access tokens by default.

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +Homeservers can choose to make the access tokens signed and non-revocable for performance reasons if the expiration is short enough (less than 5 minutes).
Signed how? What are the benefits or drawbacks? This statement feels a bit light

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +- `expires_in_ms`: The lifetime in milliseconds of the access token.
we can drop this to just `expires_in` given timestamps are already in milliseconds in Matrix.

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +This also applies to registrations done by application services.
To be clear, does this affect the masquerading of users with the `as_token` too, or just the returned token?

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +Since this request can get lost in flight, the server should delay this revocation to when the client uses the new access token or the new refresh token for the first time.
revocation is still covered by the token expiring, correct?

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +The Matrix server can but does not have to make the old access token invalid, since its lifetime is short enough.
this is a bit confusing: surely the old token should be invalidated at some point regardless of methodology?

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +`POST /_matrix/client/r0/refresh`
For appservices, I assume they want to use this without masquerading given the downstream usages of the refresh token will be unaware of their access token. Should we just go a step further and say masquerading is ignored on this endpoint given it's not super clear what that would look like?

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +`POST /_matrix/client/r0/refresh`
Does this endpoint require authentication, and can it be rate limited?

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +This MSC defines a new endpoint for token refresh, but it could also be integrated as a new authentication mechanism.
to expand on this, and the "potential issues" section above, what are the concerns with introducing it as some form of opt-in (or opt-out) mechanism for things like long-lived bots or scripts which do not easily have a refresh opportunity? For example, a nightly batch job to prune rooms/events/etc could use a static access token instead of having to login, do the work, then log out again, which would put the password near the script rather than a single revocable token.

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
Does the refresh token expire? How does one manually expire it?

2021-07-01 03:26 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
Overall feeling on this MSC is that it wants me to read the OAuth spec, but it hasn't given me links to that for areas of relevance. The MSC also doesn't really explain why this is needed outside of "OAuth doesn't do this" - we kinda need reference within the MSC as to why this change is important, and why we should go with OAuth practices over our own invented security principles. 

For both concerns, a list containing links to reading material are fine. For the "why oauth" bit, links to existing issues on matrix-doc about it placed in the MSC are also fine, if they help justify the MSC on their own.

2021-07-01 03:27 UTC, turt2live commented
Overall the idea of the MSC is clear, but I'd like to see it fleshed out a bit before we land it.

@mscbot concern General clarity and refresh token expiry.

2021-07-01 03:32 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
also would be interested to see how this plays with soft logout: if the access token expires, but the refresh token is still live, should the server be using `soft_logout: true` in expiration responses? If so, how should the server clean up the device once the refresh token also expires?

2021-07-01 03:34 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +In both cases, the server must reply with a `401` HTTP status code and an `M_UNKNOWN_TOKEN` error code.
I'd recommend sticking with the 401 error to allow servers to clear out records from their database, and for mild security against attackers trying to validate if a token is/was valid at one point (proving that their data might be reliable).

2021-07-01 10:18 UTC, sandhose reviewed
Thanks for the review, I'll do some of the requested changes this afternoon

2021-07-01 10:18 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +This MSC defines a new endpoint for token refresh, but it could also be integrated as a new authentication mechanism.
I think for both use cases (bots and scripts) I'd rather make use of the `org.matrix.login.jwt` login type with some KMS signing it for the initial login and still have the token refresh. Storing long-lived access tokens without proper secret handling is at least as bad as storing the login/pass of the bot IMO, especially if the user has admin access.
If we still need some kind of static access token, I'd rather have that in Synapse (in the config or something) than in the spec

2021-07-01 10:18 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
Makes sense, I'll clarify why we're doing this

2021-07-01 10:18 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
> to switch to issuing expiring access tokens by default.

Isn't it rather "to not support the `v1` API anymore"? Since we can't really enforce expiring token without breaking clients, I expect we'll have to have a new major revision of the API where clients *have to* support refreshing tokens?
Then when enough clients have switched to the `v2` endpoint, admins can choose to not support the `v1` API anymore?

(Sorry if it does not make sense, I'm a bit confused with versions and revisions of the API)

2021-07-01 11:59 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +`POST /_matrix/client/r0/refresh`
well, it requires authentication in that you have to supply a refresh token. It's not the same sort of authentication as we use elsewhere in the API.

2021-07-01 12:31 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
> Isn't it rather "to not support the `v1` API anymore"? 

well, if the proposal is to switch to a replacement for `/_matrix/client/r0/login`, the MSC should say that (and the sample implementations should do so rather than using a query-param on `/r0/login`). However, I don't think that is necessary, and indeed makes life harder than it needs to be for client developers.

For clarity: I understand that a successor to `/r0/login` would be called `/_matrix/client/v4/login`, thanks to [MSC2844](https://github.com/matrix-org/matrix-doc/blob/master/proposals/2844-global-versioning.md#endpoint-versioning).

So, suppose we introduce an API `/_matrix/client/v4/login`, and say "if you call this, you MUST support refreshing tokens". If you use that and you are a client, you also have to be prepared to fall back to `/r0/login` (in case you're talking to an older server).  From a client's point of view, you'd rather just hit `/r0/login` and be prepared to deal with new fields in the response.

From a server's point of view, there's nothing stopping the server issuing expiring access tokens today; nor is there anything stopping the server returning the additional fields in the login response - it's just unlikely a client will know what to do with them.

So, the only thing `/v4/login` would bring would be metrics for server admins to know how many clients support refreshing tokens, and it comes at a cost of clients having to implement an annoying fallback (as well as significant complexity in the spec documentation). That seems like a high price to pay, and there are other ways to do it. IMHO `org.matrix.msc2918.refresh_token` is going to be good enough.

2021-07-01 12:34 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +This also applies to registrations done by application services.
@sandhose: @turt2live is talking about a different mechanism of authentication for application services, which is that ASes can present a pre-shared secret known as an `as_token` in place of an `authentication_token` (see https://matrix.org/docs/spec/application_service/r0.1.2#authorization).

AFAIK we're not proposing any changes there, so the answer to travis's question is "just the returned token".

2021-07-01 19:17 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
> Refresh token don't expire, but they get invalidated on use.

This particular piece is a bit concerning, as it means that refresh tokens are hanging around waiting to give access back to the account. On the other hand, this somewhat fixes the scripts usecase as it can then store the refresh token and use that on the next run.

2021-07-01 19:18 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +This MSC defines a new endpoint for token refresh, but it could also be integrated as a new authentication mechanism.
Fair, that sounds reasonable. Just wanted to expand on the potential usecase, but agreed that scripts can find other ways to authenticate (or better yet: be replaced by features within the protocol/homeserver implementation)

2021-07-01 19:20 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +`POST /_matrix/client/r0/refresh`
ah, yes, sorry: I meant authentication in the sense that we need an `Authorization` header, which does not sound like the case here.

A mention of rate limiting/authentication is largely pedantics for the spec process to make it unambiguously clear what the MSC wanted for these properties.

2021-07-01 19:20 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +The Matrix server can but does not have to make the old access token invalid, since its lifetime is short enough.
Yup, that's a lot clearer - thank you!

2021-07-01 19:23 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +Since this request can get lost in flight, the server should delay this revocation to when the client uses the new access token or the new refresh token for the first time.
Ah, alright. Reading it with those definitions makes more sense. I was thinking in the wrong headspace when reading: in code, the token would be "revoked" (deleted) when it expires, or when the user requests, which is where this caught me off guard. 

Probably more of a me problem than an MSC issue.

2021-07-01 19:23 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +- `expires_in_ms`: The lifetime in milliseconds of the access token.
ah, fair enough. Let's keep it with `_ms` then.

2021-07-01 19:28 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +`POST /_matrix/client/r0/refresh`
This is based off the same [authentication clarification](https://github.com/matrix-org/matrix-doc/pull/2918#discussion_r662248851] richvdh supplied on the other thread: if an appservice has two registered users, Alice and Bob, with refresh tokens `aaa` and `bbb` then the appservice could potentially hit this API as `/refresh?user_id=@bob:localhost` with `{refresh_token: "aaa"}` (a mismatched user and token). Instead of having the homeserver try and figure out this leap of logic, we could just spec that masquerading (`?user_id=`) has no effect on this endpoint.

Banning masquerading on the endpoint should be fine because realistically no appservice should be insane enough to reauthenticate this way as they'll only have gotten the refresh token from registration or logging in, which means they don't need the additional context that masquerading would provide. If an appservice forgot the user ID a refresh token was for, it could renew it for an access token and hit `/account/whoami` as well.

2021-07-01 19:32 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +Homeservers can choose to make the access tokens signed and non-revocable for performance reasons if the expiration is short enough (less than 5 minutes).
ah, alright. Can we get that mentioned in the sentence somewhere? Something like:

```suggestion
Homeservers can choose to make the access tokens signed and non-revocable (like a JWT, Macaroon, etc) if the expiration is short enough (less than 5 minutes). This can help with performance by avoiding DB/auth server hits.
```

2021-07-05 10:35 UTC, deepbluev7 commented on proposals/2918-refreshtokens.md
> +This MSC defines a new endpoint for token refresh, but it could also be integrated as a new authentication mechanism.
I think an authentication option for scripts needs to be in the spec. I have a lot of scripts that push notifications or upload files from CI jobs for example. Those use access tokens, because CI jobs do sometimes get compromised (happened once because of codecov) and that way the access token can be easily rotated without being a homeserver admin. If the script used username and password instead, an attacker would have been able to get past UIA and change the password and just in general do much more nasty stuff than with an access token. The jobs also can't refresh the access token, since they may be running concurrently and can't change CI variables.

What would be my alternative for that use case, that works independent of the specific homeserver implementation?

2021-07-13 16:15 UTC, erikjohnston commented on proposals/2918-refreshtokens.md
> + - if it was already used once
How does this deal with idempotency? I think it'd be quite annoying, especially on mobile devices, if you had to relogin if the client didn't see the response to the `/refresh_token`. Can we do something like only invalidating the refresh token once we see the new access token be used?

2021-07-13 17:41 UTC, richvdh commented on proposals/2918-refreshtokens.md
> + - if it was already used once
that's what the synapse impl does :-p

2021-07-15 17:33 UTC, sandhose reviewed
I think I did all the requested changes. The recent commits can be reviewed individually.

@turt2live could go through the conversations you opened and close the ones you think I properly resolved?

2021-07-15 17:33 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +This MSC defines a new endpoint for token refresh, but it could also be integrated as a new authentication mechanism.
There is an ongoing effort to rework the whole authentication process, with use cases like scripts running in CI in mind. This MSC is also done to prepare clients for the eventual migration to this new authentication stack without having them to logout all their existing sessions.

The login API with non-expiring token will hopefully stay until this new auth stack is ready, so when you would need to migrate you will have a proper alternative.

In the meantime, if you want to still adopt refresh tokens and you are admin of your homeserver, I suggest you look into the [`org.matrix.login.jwt` login type in Synapse](https://anoadragon453.github.io/synapse/latest/jwt.html). Even though it is not standard, it will let you login using a JWT signed by some party.
It might still need some changes in Synapse to allow restricting the tokens (like not being able to use them for UIA to avoid letting the account to be nuked), but I prefer to go that route rather than adding this kind of special cases in this MSC if it will be superseded by something else soon-ish.

2021-07-15 17:33 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
Done in https://github.com/matrix-org/matrix-doc/pull/2918/commits/a050dc3a17cb50554ff11423d09ccdc75ae6975e

2021-07-15 17:33 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
Also clarified about `soft_logout` in the refresh token API in https://github.com/matrix-org/matrix-doc/pull/2918/commits/2c11e6f8306d45d66b28c336339172a37fb6a97a

2021-07-17 22:20 UTC, joepie91 requested changes

2021-07-17 22:20 UTC, joepie91 commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
... why?

I'm a bit confused as to how this made it to FCP, without the proposal even specifying *how* this new mechanism is supposed to mitigate credential leaks.

One way or another, the device will need to hold on to *some* sort of long-lived credential, whether you call it an 'access token' or a 'refresh token' or anything else, so how is this not just more steps to achieve the same level of security? Under what specific threat model does this mitigate an attack, and how?

2021-07-17 23:14 UTC, deepbluev7 commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
Neither the access token, nor the refresh token is long lived. The refresh token is single use and the access token is time limited. As such they both are only useable for a limited time, if they get leaked (i.e. someone posts their curl command in #synapse:matrix.org or so). I would still like to see some more numbers on if this actually helps or is just done "because oauth does it".

Also, this is not in FCP, it just has FCP proposed.

2021-07-18 12:37 UTC, joepie91 commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
> Neither the access token, nor the refresh token is long lived.

With "long-lived credential", I am not referring to any one specific token, but rather the more abstract state of the client having *some* kind of way to authenticate a particular session, even if a specific token is rotated. This is typically what refresh tokens are claimed to prevent, but they don't really, at least not in the general case - one way or another, the client has long-lived access to a session, and so compromising the client means compromising that session.

> The refresh token is single use and the access token is time limited. As such they both are only useable for a limited time, if they get leaked (i.e. someone posts their curl command in #synapse:matrix.org or so). I would still like to see some more numbers on if this actually helps or is just done "because oauth does it".

I agree with this, and IMO this is why it's a problem that the MSC doesn't set out the specific mitigation impact. It's something that *might* have value in a limited set of circumstances, but it does actually need to be motivated and shown to be worth the complexity - complexity in security-critical code increases attack surface, and so ineffective security measures can actually end up making a system *less* secure, even if you ignore the practical hassle of implementing that complexity.

In other words, the MSC should be very explicit about:
1. What specific attacks this is meant to protect from under which specific circumstances
2. How meaningful that is in the bigger picture
3. How that justifies the additional complexity

> Also, this is not in FCP, it just has FCP proposed.

Ah, sorry, my bad. My concern remains the same, though - this is a security-critical proposal and it's concerning to me that people perceive it as "looks good" when it's still missing crucial rationale.

2021-07-18 21:05 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
@joepie91: Thanks a lot for your remarks! I agree that this MSC might need another round of clarification around why this change makes sense. That being out of the way, let me list a few scenarios where this change is useful and IMO justifies the added complexity.

It does not quite protect against compromised client, but while I'm not saying it is expected, keep in mind that right now compromised clients can do a lot of bad things since you usually enter your account credentials directly in the client and nothing prevents them to record those credentials, send them somewhere else, and complete UIA-protected operations on your behalf without you noticing.

In contrast, it protects against a whole range of attacks where the access and/or refresh token get leaked but the client isn't completely compromised.

For example, those token can leak from user backups (user backs up his device on a NAS, the NAS gets compromised and leaks a backup of the clients secret storage), but we can assume those backups could be at least 5 min old.
If the leak only includes the access token, it is useless to the attacker since it would have expired ; if it also includes the refresh token, it is useless *if* the token was refreshed before (which will happen if the user just opens their Matrix client in between).
Worst case scenario, the leaked refresh token is still valid: in this case, the attacker would consume the refresh token to get a valid access token, but when the original client tries to use the same refresh token, the homeserver can detect it, consider the session has been compromised, end the session and warn the user.

This kind of attack also applies to leakage from the server, which could happen from database backups for example.

The important thing here is while it does not completely prevent attacks in case of a token leakage, it does make this range of attack a lot more time-sensitive and detectable (a HS will notice if a refresh token is being used twice).

Guidelines around [refresh tokens from the IETF](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#section-4.13.2) are IMO pretty interesting. Side note here, this document is pretty interesting overhaul and quite worth reading if you have an OAuth-like auth stack. They recommend that either:

 - the refresh token are sender-bound and require client authentication (making token leakage completely useless if the client credentials are not leaked at the same time)
 - or make them rotate to make the attack a lot harder as described just above.

Since all clients are basically "public" in the Matrix world, we don't have client-bound credentials we could use, hence the rotation of refresh tokens.

---

The other kind of scenario where this change makes sense is to help further changes in the homeservers.
A good, recent example of this, is in Synapse v1.34.0 [they moved away from macaroons for access tokens](https://github.com/matrix-org/synapse/pull/5588) to random, shorter, saved in database tokens, similar to [what GitHub did recently](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/).
Because there is no refresh token mechanism in the C2S API, most Synapse instances now have a mix of the two formats of tokens, and for a long time. It makes it impossible to enforce the new format of tokens without invalidating all existing sessions, making it impossible to rollout stuff like a web-app firewall in front of Synapse that verifies the shape and checksums of tokens even before reaching Synapse.

---

Last but not least, expiring tokens is already a thing that exists in Synapse (via the `session_lifetime` parameter). Before this MSC, clients had no idea when the session would end and relied on the server replying with a 401 error with `soft_logout: true` in the response on a random request to trigger a soft logout and go through the auth process again.
The nice side-effect of this MSC (although it could have been introduced separately) is that the login responses can now include a `expires_in_ms` to inform the clients when the token will expire.

---

> In other words, the MSC should be very explicit about: …

I did not include those detailed scenarios in the MSC itself to keep it short, but in retrospect I should have had this at least in the original PR comment. As said earlier, I'm happy to include changes that clarify the MSC purpose if you think the current version lacks some explanation.
I'm quite curious of what other members of the spec core team expect in terms of details and rationale in a MSC.

I will also follow up in the coming week on how this fits in the bigger picture, although I'm convinced that this change is a step in the right direction in terms of security and does improve the auth stack by itself regardless of future evolutions.

2021-07-18 21:17 UTC, deepbluev7 commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
@sandhose Thanks a lot for the extensive explanation. I am very interested in the bigger picture too! If we are already changing stuff in breaking ways, it probably makes sense to have the bigger picture so that we can bundle up the breaking changes in the spec (even if an MSC is passed at an earlier date, see spaces for example, which got approved but will probably not be specced in the next spec release, so that all the changes for it can land in one release together). Since this makes a lot of stuff harder too, as security stuff usually does, it would be nice to see the solutions for bots and such as well. I'm also still partial to UIA for /login, although I know that is blocked on the oauth experiments. So again, thank you a lot for the write up and looking forward to know more about your plans, even if that is not required for this MSC probably!

2021-07-20 18:01 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
>  I'm quite curious of what other members of the spec core team expect in terms of details and rationale in a MSC.

I can't necessarily speak on behalf of the *whole* SCT, but:

Some explanation of the rationale behind an MSC is absolutely expected. https://spec.matrix.org/unstable/proposals/#process says: "clearly state the problem being solved". That is open to interpretation, and I think that's no bad thing. The amount of explanation and justification should vary according to the MSC. If the MSC is an unambiguous improvement, then we need say very little. If the change is more controversial, that suggests we need to do better at justifying it.

In this case, I think much of your excellent comment above could be incorporated in the MSC document wholesale.

I'd recommend adding a separate "Rationale" section at the bottom so that people who want to get straight to the technical details can do so.

2021-07-22 00:28 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
ah ha, so the server would revoke the access token when a refresh token is used twice?

2021-07-22 00:30 UTC, turt2live approved these changes
Thanks for going through that. Still have a bit of a clarification point about refresh token expiration (or lack thereof), but that's not an FCP blocker in my mind.

@mscbot resolve General clarity and refresh token expiry.

2021-07-22 00:31 UTC, turt2live commented
alright bot, I'm going to need you to work:

@mscbot resolve General clarity and refresh token expiry.

2021-07-22 00:52 UTC, turt2live commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
Added justification for why we're not doubling down on UIA would be appreciated, particularly for the community perspective. Internally (and I believe a multitude of times publicly) we've talked about how UIA is deficient in delivering the functionality we want, such as by reinventing the wheel or being fairly difficult to work within for the more complex stages. 

It may be worth mentioning that down the line we may end up with an MSC that changes all of UIA over to OAuth 2.0, but for now this is effectively changing the token format and not the entry points into the authentication system: submitting usernames and passwords (or using SSO providers) is still a very capable thing.

----

@deepbluev7 fwiw, I don't see the bots usecase as a very strong one to keeping the access tokens as-is. Bots can update, as can scripts. A number of libraries already supply the functionality and scripts would easily be able to call the renew endpoint. 

For scripts in particular: an approach would be to persist the *refresh* token where it was previously persisting the access token. This does mean that the script might need a form of persistence (not impossible for a script), but still leaves the scripts highly atomic. Because they'd be persisting the refresh token, the first thing they'd do is exchange it for an access token and store the new refresh token. This also means that if something went wrong with the job then it'd be safe to re-run (auth-wise, at least) because the refresh token would simply award a new access token. Alternatively, the script could take a username and password, and hit `/logout/all` when it's done - this is effectively as good as the old-style access token, though does have the higher risk of being able to complete UIA stages (see also: replacing with OAuth 2.0) autonomously. 

Other authentication methods, including custom ones which emulate the old-style access tokens, may also be appropriate. Similarly, servers which are told that the access/refresh token will be for a script/bot could simply expose a 999 year expiration on that token. Taking these measures have security impact to consider though, as it's obvious Matrix is switching to a shorter-lived approach for a reason.

2021-07-22 09:00 UTC, deepbluev7 commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
@turt2live Persisting an access token is not really practical in a CI environment in my opinion. CI pipelines should not be stateful, as one mistake means the pipeline is now broken for everyone until an admin manually fixes it. I use scripts in my CI pipeline to upload nightlies and send notifications. So that needs something else than refresh tokens. I agree that increasing the rotation period for that specific token or fetching some other token would be possible, but storing the password is a horrible solution and such special bot tokens should not need more privileges than the current auth tokens, otherwise some bots can only be run by an admin now. I don't want to keep the current mechanism as it is just for bots, but I want a solution for bots (that can't persist state) before all matrix servers require refresh tokens.

2021-07-27 16:27 UTC, dbkr commented on proposals/2918-refreshtokens.md
> +This MSC adds support for expiring access tokens and introduces refresh tokens to renew them.
Fwiw I think linking to some standard copy of refresh tokens are a god idea (eg. the oauth draft section you linked) and a couple of sentences answer the easiest questions and spelling out the things you go on to say later would go a long way, eg. "Refresh tokens can be used only once, so ensure a leaked access token cannot continue to be used. Idempotency is achieved by only invalidating the refresh token after the new access token is used. See <link> for more on refresh tokens as a general concept".

The detailed explanation here is fantastic but whatever doesn't make it into the MSC itself will more-or-less be lost to history.

2021-07-27 17:30 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +The Matrix server can revoke the old access token right away, but does not have to since its lifetime is short enough that it will expire anyway soon after.
> ... but does not have to since its lifetime is short enough that it will expire anyway soon after.

Is this necessarily true?  Is there a requirement that clients only refresh the access token shortly before the old one expires?

I would think that it would be best to say that the server must revoke the old access token once the new access/refresh token is used.

2021-07-27 17:30 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +
Should there be a new error code for indicating that the access token has expired and needs to be refreshed?

I think this might be useful for CLI tools that might want to be fairly dumb. e.g. they can just hit the endpoint with the current access token, and if it says that the token has expired, then refresh the token and try again.  This way, it doesn't have to worry about keeping track of time.

Or it could be helpful for situations where a client's clock gets messed up and it thinks that the access token should still be valid when it actually isn't.

2021-07-27 17:30 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +While this MSC is not in a released version of the specification, clients should add a `org.matrix.msc2918.refresh_token=true` query parameter on the login endpoint, e.g. `/_matrix/client/r0/login?or
```suggestion
While this MSC is not in a released version of the specification, clients should add a `org.matrix.msc2918.refresh_token=true` query parameter on the login and registration endpoints, e.g. `/_matrix/client/r0/login?org.matrix.msc2918.refresh_token=true`.
```

?

2021-07-27 17:30 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
I agree that this MSC should spell out how backward compatibility is handled, whether by using `/v4/login` (and `/v4/register`), or by adding a parameter (like the `org.matrix.msc2918.refresh_token` parameter mentioned in the unstable prefix).  I think that adding a parameter would be better since it allows clients to just hit `/r0/login`, rather than trying `/v4/login`, seeing if it errors, and then trying `/r0/login` if it does.

2021-08-10 16:55 UTC, anoadragon453 reviewed
There are a few comment threads still open that I'd like to see resolved before adding my tick - especially the one about backwards-compatibility concerns, which I concede is possibly the most contentious.

Otherwise there's not really any other show-stoppers I can see!

2021-08-10 16:55 UTC, anoadragon453 commented on proposals/2918-refreshtokens.md
> +While this MSC is not in a released version of the specification, clients should add a `org.matrix.msc2918.refresh_token=true` query parameter on the login endpoint, e.g. `/_matrix/client/r0/login?or
I think this parameter signals support from the client for handling refresh tokens, however there is no mention anywhere of what one should do when unstable prefixes can be removed. Will a parameter `/login?refresh_token=true` stick around after we remove unstable prefixes, or will the parameter be removed altogether as it is assumed clients will be upgraded by then?

2021-08-10 16:55 UTC, anoadragon453 commented on proposals/2918-refreshtokens.md
> +The Matrix server can revoke the old access token right away, but does not have to since its lifetime is short enough that it will expire anyway soon after.
It seems as though the MSC now says this -- If so, @sandhose note that it's best to resolve outstanding PR comments once they've been addressed.

2021-08-10 16:55 UTC, anoadragon453 commented on proposals/2918-refreshtokens.md
> +
Clients probably should be keeping track of time anyways, otherwise you'll find your client wastes a request every 5m to find out that the token has expired. IMO keeping track of time isn't too hard - even embedded systems do it quite regularly.

> Or it could be helpful for situations where a client's clock gets messed up and it thinks that the access token should still be valid when it actually isn't.

This is a more convincing point. If the token is invalid and the clock says that a refresh shouldn't be necessary, the client could assume that it needs to re-login again. Though, perhaps the client should attempt a refresh of the token anyways, in which case this issue would be sidestepped...

Whatever the conclusion, probably warrants a paragraph in the "Potential issues" or "Alternatives" sections.

2021-08-23 17:16 UTC, KitsuneRal reviewed
It looks good (with a caveat that the old mechanism or some other way to get a long-lived token should remain until we have a "service accounts" implementation for stateless CLI tools); I only have one question and one opinion in support of the current API shape.

2021-08-23 17:37 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +The Matrix server can revoke the old access token right away, but does not have to since its lifetime is short enough that it will expire anyway soon after.
The point is that a server could set a lifetime for the access token to, e.g. 2 weeks, and a client could refresh the token 5 minutes after receiving it.  Then the old access token would be valid for 2 weeks minus 5 minutes, which I don't think counts as it "expir[ing] ... soon after".  So this statement seems to be incorrect.

2021-08-23 17:43 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +The Matrix server can revoke the old access token right away, but does not have to since its lifetime is short enough that it will expire anyway soon after.
Ah, I see that the MSC now says that access token expires after a short amount of time, so I think this is resolved now.

2021-08-23 17:47 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +
Right.  I think that part of the change that clients will need to make is, instead of assuming that they're logged out if they get an `M_UNKNOWN_TOKEN`, now if they get an `M_UNKNOWN_TOKEN`, they should try to refresh their token, and if that doesn't work, then they're logged out.  I think this needs to be clearer in the MSC (and also how this interacts with Soft logout).

2021-08-23 17:50 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
> > I think that adding a parameter would be better since it allows clients to just hit /r0/login, rather than trying /v4/login, seeing if it errors, and then trying /r0/login if it does.
> 
> As said in another thread, I'd lean towards enforcing refreshing access tokens in the next API version. Wouldn't the clients then be able to know what version the server supports beforehand by checking `/versions`?

I don't think that would be sufficient.  And it's not that we can just say "If `/versions` contains {vNext}, then use refresh tokens".  We'd need to remove all previous versions from the list, as clients that use those versions will break. And a lot of clients (e.g. simple bots) don't check `/versions`, at least for basic functionality, so these would just break.

I think we need an actual plan on how we're going to handle backward compatibility for this.

2021-08-23 17:52 UTC, uhoreg commented
@mscbot concern we need a backward compatibility plan

2021-08-23 19:27 UTC, KitsuneRal commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
The current approach (with the query parameter for opting in in the meantime, and extra parameters returned in the response) seems to be backwards compatible, no?

2021-08-23 21:30 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +The access token returned by the login endpoint expires after a short amount of time, forcing the client to renew it with a refresh token.
Can we have an example of what is considered a "short" amount of time?

2021-08-23 21:37 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +
Maybe add something like this to the "Proposal" section:

> If a client uses an access token that has expired, the server will respond with an `M_UNKNOWN_TOKEN` error.  Thus, if a client receives an `M_UNKNOWN_TOKEN` error, and it has a refresh token available, it should no longer assume that it has been logged out, and instead attempt to refresh the token using the new `/refresh` endpoint.  If the client was in fact logged out, then the server will respond with an `M_UNKNOWN_TOKEN` error, possibly with the `soft_logout` parameter set.

2021-08-23 22:00 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +This new API should be rate-limited and does not require authentication since only the `refresh_token` parameter is needed.
I don't know if this is the author's reason, but I would find it confusing if you used different types of tokens in the `Authorization` header for different endpoints.

2021-08-23 22:09 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
My understanding is that the the query parameter is only for while this MSC is in development, but at the next spec release, login and registration will emit refresh tokens by default, and old clients that aren't aware of refresh tokens will suddenly break.

FWIW, when I say that we need a "plan", I mean something like "We will shout loudly about this change, and in n months, homeserver implementations can feel free to use refresh tokens by default."  The plan should probably also consider the various Linux distributions.  e.g. Debian bullseye was just released a couple weeks ago, and will probably be the "stable" version for about two years.  We may be able to get updates through backports for clients, but not everyone uses backports.

2021-08-24 10:21 UTC, KitsuneRal commented on proposals/2918-refreshtokens.md
> +The access token returned by the login endpoint expires after a short amount of time, forcing the client to renew it with a refresh token.
It's stated in a couple of places (one just a few lines below, and another in Security considerations) - from those, "short" means "several minutes, could be more if the token is revocable"?

2021-08-24 19:05 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +The access token returned by the login endpoint expires after a short amount of time, forcing the client to renew it with a refresh token.
I saw the mention a couple lines below, but that seems to be distinct from this as it's specifically about non-revocable tokens.  But I now see the mention in Security Considerations, which answers my question.

2021-08-31 08:56 UTC, richvdh commented
> The final comment period, with a disposition to **merge**, as per [the review](https://github.com/matrix-org/matrix-doc/pull/2918#issuecomment-871615446) above, is now **complete**.

... but there are still outstanding concerns. I think this is a bug in the MSCbot.

2021-08-31 16:04 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
Some possibilities for dealing with backwards compatibility:

- Yell loudly about refresh tokens becoming a thing and warn that they will become default at some point.  Allow clients to specify that they want to use refresh tokens (e.g. by including a new parameter).  After some predefined time, servers can default to using refresh tokens.  Clients can stop setting the new parameter.
  - downsides:
    - clients that haven't been updated will break silently when servers default to using refresh tokens.
    - if clients stop setting the parameter, but connect to a moderately old server (supports refresh tokens, but doesn't use them by default), then refresh tokens will not be used even though both the server and client support it
- Use `/_matrix/client/v4/login` for logins with refresh tokens.  Clients will know whether to use `r0/login` or `v4/login` by checking `/versions` and seeing if the server supports the spec version that introduces refresh tokens.  At some point, `r0/login` could be removed, which will break old clients, but the breakage will be noticeable rather than silent.
  - downside: clients need to check `/versions` to see which endpoint to use
- same as above, but rather than using `/versions` to signal whether to use `r0/login` or `v4/login`, add a flag to `GET /login` that indicates whether refresh tokens are supported
  - downside: clients need to check `GET /login` to see which endpoint to use, but many do that already to see whether to log in using password or SSO
- replace current login system with [UIAuth](https://github.com/matrix-org/matrix-doc/pull/2835) or [OAuth](https://github.com/matrix-org/matrix-doc/issues/2615).  Logins using the new system use refresh tokens, and logins using the old system don't.  At some point, the old system can be turned off.
  - downside: replacing the login system may take a while, and would block this from being used

I suspect that either option 2 or 3 would be the best.

2021-09-06 12:59 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
Thanks for the summary, @uhoreg, that's very helpful and sounds about right to me. I agree that we need to get alignment on this point.

To be clear, I think option 1 is the current proposal, and option 4 is the long-term plan, but the idea was to get this change out as a way of breaking down the problem rather than having to deal with everything at once.

> * clients that haven't been updated will break silently when servers default to using refresh tokens.
> * [with `/v4/login`] ... the breakage will be noticeable rather than silent. 

When you say "clients will break silently": my understanding/expectation is that said clients will work fine for 5 minutes, then suddenly log you out. (Maybe we could even use the existing `soft_fail` mechanism to get clients to prompt for a reauthentication rather than a complete logout.)  

That's certainly pretty sucky UX, but it's not complete silent breakage, and from a user's point of view, it's not obviously worse than an obscure error from a client trying to use `/r0/login` - we could *try* returning an error message along the lines of "your client is too old", but I suspect most won't show it.

[maybe we should invent a time-machine so that we can go and add a `M_CLIENT_TOO_OLD` error to `/r0/login`].

2021-09-09 21:38 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +Homeservers can choose to have access tokens returned by the registration and login endpoints after a short amount of time, forcing the client to renew it with a refresh token.
```suggestion
Homeservers can choose to have access tokens expire after a short amount of time, forcing the client to renew them with a refresh token.
```

2021-09-09 21:56 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +Whether the access token expire and what lifetime they have is up to the homeserver, but client have to support refreshing tokens.
@sandhose: is this correct? I think we discussed keeping the query parameter as a way of allowing clients to opt in, even once the MSC lands - mostly as a way of supporting the script usecase until proper OAuth lands.

So something more like:

```suggestion
Clients are not *required* to support refreshing access tokens, though it is heavily recommended.
Clients indicate their support for refreshing access tokens via a query parameter to the `/login` and `/register` APIs.
Homeserver implementations should expire access tokens whenever a client indicates support. 
The lifetime of issued access tokens is up to homeserver deployments, but a lifetime of around 30 minutes (?) would be normal.

Handling of clients that do *not* support refreshing access tokens is up to individual homeserver deployments.
For example, server administrators may choose to support such clients for backwards-compatibility, or to expire access tokens anyway for improved security at the cost of inferior user experience in legacy clients.
```

2021-09-09 21:56 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +### Login API changes
we should probably make it explicit what happens when the access token expires.

On that front: should we recommend that servers set `soft_logout: true` (see https://spec.matrix.org/unstable/client-server-api/#soft-logout) as a way of increasing compatibility with clients that do not support refresh tokens?

2021-09-10 08:04 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +- `refresh_token`: The refresh token, which can be used to obtain new access tokens.
@turt2live is this clear enough now?

2021-09-10 08:06 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +### Login API changes
oh, this is basically the same point as another comment thread (https://github.com/matrix-org/matrix-doc/pull/2918/files#r677648682)

2021-09-10 12:37 UTC, sandhose reviewed
I clarified on backward compatibility, opted for a `refresh_token` field in the request body instead of the query param

2021-09-10 12:37 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +Whether the access token expire and what lifetime they have is up to the homeserver, but client have to support refreshing tokens.
I opted for an additional field in the request body instead. TTL of access tokens is already mentioned in the "security consideration" part. See https://github.com/matrix-org/matrix-doc/pull/2918/commits/4cf821c7c2339b6a46676c0a8b92b1593e8850a9

2021-09-10 12:37 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +### Login API changes
Just did that in https://github.com/matrix-org/matrix-doc/pull/2918/commits/c0767632c83e97f7af3204525e73953de0268c16

2021-09-10 12:37 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +
Thanks, added that in https://github.com/matrix-org/matrix-doc/pull/2918/commits/c0767632c83e97f7af3204525e73953de0268c16

2021-09-10 12:37 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +While this MSC is not in a released version of the specification, clients should add a `org.matrix.msc2918.refresh_token=true` query parameter on the login endpoint, e.g. `/_matrix/client/r0/login?or
This has been replaced by a field in the request body, that will stick once the MSC is released, see https://github.com/matrix-org/matrix-doc/pull/2918/commits/4cf821c7c2339b6a46676c0a8b92b1593e8850a9

2021-09-10 12:37 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
After discussing with @richvdh, I opted to have a `refresh_token` field in the login/registration APIs that indicate client support. Please check out the up to date "Proposal" section of the MSC

2021-09-14 15:08 UTC, uhoreg commented on proposals/2918-refreshtokens.md
> +Whether the access token expire and what lifetime they have is up to the homeserver, but client have to support refreshing tokens.
Thanks.  I think that adding the request body field solves the issue of backward compatibility.  I think this means that this technically doesn't match the implementation, but I think that having the body param is close enough to the existing query param that we don't need to raise the "needs-implementation" flag on this.

2021-09-14 15:09 UTC, uhoreg commented
@mscbot resolve we need a backward compatibility plan

2021-09-14 15:16 UTC, uhoreg commented
mscbot seems to have gotten confused, so let's try to start a new FCP

@mscbot fcp merge

2021-09-14 15:27 UTC, erikjohnston commented on proposals/2918-refreshtokens.md
> +Unless `inhibit_login` is `true`, the account registration API returns two additional fields:
Shouldn't this be if its *false*? I.e. we include the params when we return a valid access token?

2021-09-14 15:59 UTC, dbkr commented on proposals/2918-refreshtokens.md
> +Whether the access token expire and what lifetime they have is up to the homeserver, but client have to support refreshing tokens.
It still says they're required to support them here though, conflicting with below.

2021-09-16 09:05 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +Unless `inhibit_login` is `true`, the account registration API returns two additional fields:
The spec says:

> `inhibit_login`: If true, an access_token and device_id should not be returned from this call, therefore preventing an automatic login. Defaults to false.

So that sentence seems correct? If `inhibit_login` is `true`, it will **not** return the additional fields

2021-09-21 16:38 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +Whether the access token expire and what lifetime they have is up to the homeserver, but client have to support refreshing tokens.
yup, what @dbkr said

2021-09-21 16:39 UTC, richvdh commented on proposals/2918-refreshtokens.md
>  Whether the access token expire and what lifetime they have is up to the homeserver, but client have to support refreshing tokens.
I think we can just get rid of this sentence.

```suggestion
```

2021-09-21 16:43 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +If the client was in fact logged out, then the server will respond with an `M_UNKNOWN_TOKEN` error, possibly with the `soft_logout` parameter set.
this is confusing. It says:
 * If the client was not logged out, but the access token expires, the server responds with `M_UNKNOWN_TOKEN` error.
 * If the client *was* logged out, the server responds with `M_UNKNOWN_TOKEN` error.

so the same thing in each case? It seems to be a complicated way of saying that.

2021-09-21 16:44 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +Unless `inhibit_login` is `true`, the account registration API returns two additional fields:
it's not the easiest thing to grok, but @sandhose is right, and @erikjohnston is confused.

2021-09-21 16:47 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +# MSC2918: Refresh tokens
I'm going to resolve this thread, as we have a plan for compatibility now.

2021-09-23 12:54 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +If the client was in fact logged out, then the server will respond with an `M_UNKNOWN_TOKEN` error, possibly with the `soft_logout` parameter set.
The last sentence talks about the token refresh request, so it's more a "if you get a `M_UNKNOWN_TOKEN` to a random request, you should try refreshing, and if you get a `M_UNKNOWN_TOKEN` when refreshing, you're really logged out"

2021-09-23 13:11 UTC, richvdh commented on proposals/2918-refreshtokens.md
> +If the client was in fact logged out, then the server will respond with an `M_UNKNOWN_TOKEN` error, possibly with the `soft_logout` parameter set.
ah I see, that wasn't clear to me.

2021-09-23 14:49 UTC, sandhose commented on proposals/2918-refreshtokens.md
> +If a client uses an access token that has expired, the server will respond with an `M_UNKNOWN_TOKEN` error.
done here: https://github.com/matrix-org/matrix-doc/pull/2918/commits/70b2dfcde2f087c4c2e9eea33792e0b13a64e0e9

2021-09-23 15:57 UTC, richvdh approved these changes
looks grand, thanks!

2021-09-28 16:23 UTC, merged

2022-05-04 20:13 UTC, uhoreg commented
FTR, I'm working on the spec PR for this

2022-05-20 01:43 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/1056

2022-06-02 20:30 UTC, uhoreg commented
merged! :tada:

2022-10-10 19:11 UTC, anoadragon453 commented
I've added Element Web and iOS implementations of this MSC to the PR description.

2022-10-11 06:10 UTC, turt2live commented
@anoadragon453 ftr, the web implementation was reverted: https://github.com/matrix-org/matrix-react-sdk/pull/7821

2022-10-14 13:17 UTC, anoadragon453 commented
Oh, thanks for letting me know!