Spaces Summary
matrix-org/matrix-doc pull request #2946
Opened 2021-01-07 16:22 UTC by Kegsay

2021-01-07 16:42 UTC, ara4n commented on proposals/2946-spaces-summary.md
> +This MSC defines a new endpoint which can be used to reveal information about the space directory.
```suggestion
This MSC defines a new endpoint which can be used to reveal information about the space hierarchy.
```

imo "directory" implies that we're talking about /publicRooms or something, which we're not

2021-01-07 16:43 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +This MSC defines a new endpoint which can be used to reveal information about the space directory.
Hierarchy is a misnomer too though as it implies there's a root, which there really isn't.

2021-01-07 16:47 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +      all `m.space.child` and `m.room.parent` state events which *point to* (via `state_key` or `content.room_id`)
This should probably factor in https://github.com/matrix-org/matrix-doc/pull/1772/files#diff-cdaa2b5bfe73f40db1903d17b1d242d8caa54d4af81e78e0396a369bcd9a1b90R140-R143 as it has the potential to cut trees shorter and further alleviate work off clients.

2021-01-07 16:53 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +                "order": "abcd",
Will the server be respecting this order too?

2021-01-08 02:04 UTC, nfraprado commented on proposals/2946-spaces-summary.md
> +This MSC defines a new endpoint which can be used to reveal information about the space directory.
But doesn't the retrieved room tree have the queried room as its root? From my understanding, while there might not be a single universal root, the query response is indeed a hierarchy with the queried room as its root. In that case, why not say it as `This MSC defines a new endpoint which can be used to reveal information about the space hierarchy under a given space`?

2021-01-08 11:10 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +This MSC defines a new endpoint which can be used to reveal information about the space directory.
> But doesn't the retrieved room tree have the queried room as its root?

Not really. This API just exposes nodes/edges, so a graph like:
```
  A
  |
  B
  |
  C   D
  |___|
    |
    E
```
with root room = D will return all the way up to A. The root room ID is just where to start exploring the graph.

2021-01-08 11:24 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +      all `m.space.child` and `m.room.parent` state events which *point to* (via `state_key` or `content.room_id`)
The API needs to support it so we can track secret rooms. It's not that onerous for clients to check there is both a parent->child and child->parent relationship if they only want to render bi-directional links. History visibility checks are done so it'll only actually return these non-bi-directional links if you are joined to a room which specifies it already, so I don't think this is a spam vector.

2021-01-08 11:27 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +                "order": "abcd",
I've purposefully left `events` as unsorted for now, and it's undefined which edges get returned first. We can use the `order` key but that alone is insufficient to get a stable sort (nothing stops the same order being present in different rooms, so which comes first?). We need to figure out a tie break mechanism.

2021-01-08 11:31 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +      all `m.space.child` and `m.room.parent` state events which *point to* (via `state_key` or `content.room_id`)
I don't think that quite covers it, its to prevent Joe Bloggs from adding a "Secret Room" to "Official Community" when he has absolute no permissions in "Official Community" - he shouldn't be able to make it show up in their hierarchy

2021-01-08 11:34 UTC, bwindels commented on proposals/2946-spaces-summary.md
> +Spaces are rooms with `m.space` as the [room type](https://github.com/matrix-org/matrix-doc/pull/1840).
Is this an intentional departure from using a field in the `m.room.create` [we landed on in MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772/files/6cc3995ce825e5afbf29272967aef8adde899597#r526747733)? Just asking because this is not what the room type MSC is currently proposing.

2021-01-08 14:52 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +      all `m.space.child` and `m.room.parent` state events which *point to* (via `state_key` or `content.room_id`)
It wouldn't unless you were already a part of "Official Community".

2021-01-11 18:13 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +Spaces are rooms with `m.space` as the [room type](https://github.com/matrix-org/matrix-doc/pull/1840).
No, the intention is to follow what MSC1772 says.

2021-01-15 14:28 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +            "room_type": "m.space"
Presumably this will have a `canonical_alias` field too if available

2021-01-15 14:43 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +            "room_type": "m.space"
Yes, the `PublicRoomsChunk` in the spec includes:
```
canonical_alias | string | The canonical alias of the room, if any.
```

2021-01-15 16:49 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> + - Loop through the `events` and keep track of parent->child relationships by looking at the `room_id`
in the example above `room_id` appears to be missing

2021-02-25 13:14 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
/me proposes `/_matrix/client/unstable/org.matrix.msc2946`

2021-03-10 10:33 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +            "num_refs": 42,
I'm going to unresolve this, because it would really be *WAY* easier to read this if the fields were documented more obviously rather than in the long "Justifications" text.

2021-03-10 10:35 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +    * If this room has not ever been in `rooms` (across multiple requests), extract the
The intention is to deliver each `Room` object exactly once to the client hence "has not ever been in `rooms`". However, when walking the tree, you will need to visit the node multiple times hence "if this room has been processed, skip".

2021-03-10 10:40 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +Spaces are rooms with `m.space` as the [room type](https://github.com/matrix-org/matrix-doc/pull/1840).
please can it be made to follow what MSC1772 says then?

2021-03-10 10:44 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +*This MSC depends on [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772).*
actually sorry, that's not really right. It *does* depend on significant parts of MSC1772. I wish MSC1772 wasn't so sprawling.

```suggestion
*This MSC depends on parts of [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772).*
```

2021-03-10 15:58 UTC, richvdh commented on proposals/2946-spaces-summary.md
> + - Extract the room ID from the request. Sanity check request data. Begin walking the graph
what should the server do if the supplied room id is not a spaceroom?

2021-03-10 16:11 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
should guest users be allowed to call this API? I assume so?

2021-03-10 16:24 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
why is this a POST rather than a GET?

2021-03-10 16:26 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
Sounds like it could be a potentially expensive API call

2021-03-10 16:26 UTC, richvdh commented on proposals/2946-spaces-summary.md
> + - `batch`: Required for pagination. Could be a query parameter but it's easier if
why is this called `batch`? we don't seem to use that name anywhere else. Alternatives might include `from` (for consistency with `/messages`) or `since` (for consistency with `/publicRooms`).

2021-03-10 16:30 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
Guests don't need to pass captcha which makes this infinitely easier to abuse

2021-03-10 17:18 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> + - Extract the room ID from the request. Sanity check request data. Begin walking the graph
This API doesn't look at the create event to see if the room type is a space, it only looks at state events. This feels somewhat desirable, though unexpected. We should probably reject at this stage if the room type isn't a space.

2021-03-10 17:18 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +      If no, skip this room. If yes, continue.
if the room is not accessible, should we continue into its children/parents or not?

2021-03-10 17:19 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
Aside from the computational cost, there's no reason why guests should be prevented from hitting this endpoint.

2021-03-10 17:20 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +      If no, skip this room. If yes, continue.
No, if the room is not accessible children/parents should not be explored.

2021-03-10 17:23 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
There's a decent number of input parameters and that only looks set to grow (i.e suggested rooms, auto join rooms, etc). If it's too big it might cause problems being query params.

2021-03-10 18:12 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +            ],
as an aside: note that `aliases` is no longer returned by synapse here (https://github.com/matrix-org/matrix-doc/issues/3056).

2021-03-10 18:54 UTC, richvdh commented on proposals/2946-spaces-summary.md
> + - `limit`: The maximum number of events to return in `events`. It is desirable for clients
should this have a name which makes it clear it applies to the number of `events`, not the number of rooms?

2021-03-10 18:54 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +    "events": [
according to the description, seems it does.

2021-03-10 19:03 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +    `next_batch` token. The server SHOULD NOT return duplicate events or rooms on subsequent
I'm a bit confused about how the different limits and the pagination parameters interact. If we have a space with 1000 children (so we hit the max_rooms_per_space), does paginating work its way through all of those edges in preference to moving onto other spaces in the hierarchy?

2021-03-11 19:55 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    "limit": 100,                  // The maximum number of rooms/subspaces to return, server can override this, default: 100.
```suggestion
    "limit": 100,                  // The maximum number of events to return, server can override this, default: 100.
```

Maybe? I think this matches what is described below. (I was quite confused by the current wording of `max_rooms_per_space` vs. `limit`.)

2021-03-12 10:07 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +    "limit": 100,                  // The maximum number of rooms/subspaces to return, server can override this, default: 100.
you are very much not alone in your confusion...

2021-03-12 11:34 UTC, Cadair commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
Seems like abuse should be countered with rate limiting or other things not just excluding guests from this endpoint. A guest-supporting client might want to preview a whole space to the user before deciding to join / register etc.

2021-03-12 11:50 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
Excessive rate limiting could harm the usability of this for non-abusive users just switching between spaces a few times to find the room they want

2021-03-15 10:07 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> + - `batch`: Required for pagination. Could be a query parameter but it's easier if
Mainly because `/sync` has `next_batch` hence why I went with that term. I don't mind `since`.

2021-03-15 10:09 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> + - `limit`: The maximum number of events to return in `events`. It is desirable for clients
That would be useful yeah, possibly `event_limit`?

2021-03-15 10:14 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +    `next_batch` token. The server SHOULD NOT return duplicate events or rooms on subsequent
The intention behind `max_rooms_per_space` is to allow hierarchies like:
```
Root
|
|_A
| |_ Room 1
| |_ Room 2
|
|_B
  |_ Room 3
  |_ Room 4
  |_ Room 5
  |_ ... [hundreds]
```

to be roughly obtained in a single API call. That is to say, a single large subspace shouldn't starve neighbouring spaces, hence having a "per room" (although per space would be better terminology) limit. The intention is that if you then wanted to find more rooms in B, you would do this as a separate API call (e.g hitting a "And `$num_refs` more..." button). How pagination of this sub-space interacts with pagination of the root space I don't fully know the answer to. I said before that we _should_ still be returning sub-space results, but it would probably be more useful to not, and instead expect a separate API call with B as the root.

2021-03-15 16:36 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +    "max_rooms_per_space": 5,      // The maximum number of rooms/subspaces to return for a given space, if negative unbounded. default: -1.
why negative to mean unbounded, rather than simply omitting the param? we don't do this anywhere else in the API afaik.

2021-03-15 17:18 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +    "max_rooms_per_space": 5,      // The maximum number of rooms/subspaces to return for a given space, if negative unbounded. default: -1.
it's not made clear here, but apparently the root space is exempted from this limit.

2021-03-15 17:55 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +    "max_rooms_per_space": 5,      // The maximum number of rooms/subspaces to return for a given space, if negative unbounded. default: -1.
Another thing that is not made clear here: AIUI this limit applies to both edge events, and the rooms they point to. 

Example: if a space A has 10 child events, and `max_rooms_per_space` is set to 5:
 * for the first 5 events, we add the event to `events`, and recurse into the rooms they point to (assuming we haven't already visited them)
 * we completely ignore any additional events.

2021-03-16 15:35 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +    "max_rooms_per_space": 5,      // The maximum number of rooms/subspaces to return for a given space, if negative unbounded. default: -1.
Sounds good to me.

2021-03-16 15:35 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +    "max_rooms_per_space": 5,      // The maximum number of rooms/subspaces to return for a given space, if negative unbounded. default: -1.
Yes, that's correct.

2021-03-22 18:03 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +### Federation API
note to self: we need to spec the "I'm not in this space" behaviour, so that the calling server can try a different server.

2021-04-14 17:05 UTC, clokep commented
I've just pushed an updated version of this which matches the current experimental implementation in Synapse and Element Web / Android. I've also resolved most of the comments above as they were resolved at some point in the past.

2021-04-29 20:46 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +MSC2946 attempts to solve how a member of a space discovers rooms in that space. This
nitpick: when referencing the current MSC, don't do so by number.

```suggestion
This MSC attempts to solve how a member of a space discovers rooms in that space. This
```

2021-05-04 11:16 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +    room's `m.room.create` event, if any.
Sorting children within a space requires the `origin_server_ts` of the child's `m.room.create` event, given we don't get the `m.room.create` as the room type is aggregated into the `rooms` array the ts of that event should be too

https://github.com/matrix-org/matrix-doc/pull/1772/files#diff-cdaa2b5bfe73f40db1903d17b1d242d8caa54d4af81e78e0396a369bcd9a1b90R122

2021-05-04 18:28 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    room's `m.room.create` event, if any.
This got removed from MSC1772, so not sure there's anything to include here.

2021-05-04 19:12 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +    room's `m.room.create` event, if any.
It wasn't removed? https://github.com/matrix-org/matrix-doc/pull/1772/files#diff-cdaa2b5bfe73f40db1903d17b1d242d8caa54d4af81e78e0396a369bcd9a1b90R118-R127

2021-05-04 19:38 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    room's `m.room.create` event, if any.
Oh, my mistake. I thought the ordering was needed to break cycles, but it is just used generally. It should be easy enough to include, yes.

2021-05-05 12:26 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    room's `m.room.create` event, if any.
I've pushed f145fa3e8ac63edb5d7e9777cb55ecefea20beb8 with this change (and will work on getting it into Synapse).

2021-05-05 13:51 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    room's `m.room.create` event, if any.
See matrix-org/synapse#9928.

2021-05-05 17:02 UTC, dbkr commented on proposals/2946-spaces-summary.md
> +   each room and add it to `rooms`, also and any `m.space.child` events of the room
```suggestion
   each room and add it to `rooms`, also add any `m.space.child` events of the room
```

?

2021-05-05 17:11 UTC, dbkr commented on proposals/2946-spaces-summary.md
> +   inspected, or the  server-side limit on the number of rooms is reached.
You've mentioned below that clients must be aware of cycles but if you're specifying an exact algorithm here then I think, ironically, you're missing a cycle-breaking algorithm on the server side here 😭 Also, from reading I'm not 100% sure if this is breadth-first or depth-first. Having this algorithm here really helps with understanding though, so I think it would be fine to say this is a rough guide and the server impl can decide on the specifics (or is it important that all HSes generate exactly the same order?)

2021-05-05 17:21 UTC, dbkr commented on proposals/2946-spaces-summary.md
> +
If there's no `via` here, is it required that the user has already joined the root room?

2021-05-05 17:25 UTC, dbkr commented on proposals/2946-spaces-summary.md
> +None.
Does it make it any easier to cause an HS to make a lot of outbound queries if I create a space with a lot of sub-spaces with the same / different HSes in the `via` param maybe?

2021-05-05 17:32 UTC, dbkr commented on proposals/2946-spaces-summary.md
> +### Server-server API
I think I'm missing how the server-server API fits into this: I'd assumed the HS would go & query the via servers for any rooms in finds that it doesn't already know about, but the presence of a server-server API suggests not. Is the idea to instead use this API on one of the via servers and splice the results into its own results?

2021-05-05 18:48 UTC, clokep commented on proposals/2946-spaces-summary.md
> +
There's currently no requirement that the room is a space, it just looks at whether there's any `m.space.child` events in it.

We should document what happens if the room doesn't exist / if you don't have permission to view it though! 👍

2021-05-05 18:52 UTC, clokep commented on proposals/2946-spaces-summary.md
> +   inspected, or the  server-side limit on the number of rooms is reached.
It isn't meant to be an exact algorithm. Synapse currently will not revisit rooms, but has no specific algorithm for cycle-breaking. (Note that the `rooms` and `events` returned are unordered.)

We could re-word this into a paragraph, which is how @richvdh originally had it, but I found it easier as a list of steps. Adding some words around it saying that this is the vague pseudo-code might be good.

I don't think the ordering matters since the returned data is unordered. It is also potentially problematic that the cut-off for what is returned could be in different places (if one implementation uses depth-first and one uses breadth-first they could cut-off at different locations if the limit is reached).

2021-05-05 18:55 UTC, clokep commented on proposals/2946-spaces-summary.md
> +### Server-server API
Your assumption is pretty much correct, but the server must know about the root room, if it doesn't than an error is returned. This is not clear (and maybe it should take the `via` from the client to request info on it if it doesn't know it).

While visiting nodes in the tree, if the server does not know about a room it will reach out over federation (since each node includes `via` servers) and then include those results in the response.

2021-05-05 18:56 UTC, clokep commented on proposals/2946-spaces-summary.md
> +None.
Yeah this would be a DoS vector, good call! Especially since there's no guarantee the room IDs are actually valid.

2021-05-05 20:15 UTC, clokep commented on proposals/2946-spaces-summary.md
> +
The user must have joined the root room or it must be world readable.

2021-05-05 20:26 UTC, clokep commented on proposals/2946-spaces-summary.md
> +   inspected, or the  server-side limit on the number of rooms is reached.
Oh, hmm...there's a note below that says:

> The current implementation doesn't honour `order` fields in child events, as
> suggested in [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772).

I guess we want this to be stable so we should probably implement that.

2021-05-05 20:34 UTC, clokep commented on proposals/2946-spaces-summary.md
> +
I've clarified this in the errors section I believe.

2021-05-05 20:34 UTC, clokep commented on proposals/2946-spaces-summary.md
> +
I've clarified this by moving around some comments.

2021-05-05 20:35 UTC, clokep commented on proposals/2946-spaces-summary.md
> +   inspected, or the  server-side limit on the number of rooms is reached.
I made the cycle breaking a bit clearer, but maybe we should specify breadth vs depth first search?

2021-05-06 03:44 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
It seems like since this comment thread happened there spawned a GET version in addition to the POST version: why is there still a POST version?

2021-05-06 03:45 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +POST /_matrix/client/r0/rooms/{roomID}/spaces
This feels like it could be heavily cached by the server and ultimately become a public room directory-like endpoint instead.

2021-05-06 03:46 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  case-sensitive.
as far as the spec is concerned, both of these cases are booleans. We don't get into the details of query strings technically being string pairs.

2021-05-06 03:48 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  (which *does* apply to the root room); attempts to exceed this  limit are
why is the server's internal limit different than the provided limit? Seems like it'd just be even more complicated for servers than `min(provided, 50)`

2021-05-06 03:52 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +Example response:
Somewhere between the request and response it would be nice to say the words "The endpoint requires authentication and can be rate limited". Or, if these aren't conditions on the endpoint, explanations as to why not.

2021-05-06 03:52 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +* **`events`**: `m.space.child` events of the returned rooms. For each event, only the
it might be best to call this `stripped_state`, `space_state`, or similar to line up with terminology already established in the spec for this data structure. Specifically, these look like StrippedState events with the addition of a room_id

2021-05-06 03:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +* **`events`**: `m.space.child` events of the returned rooms. For each event, only the
a few words as to why this is not under the relevant room would be appreciated.

2021-05-06 03:54 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  `sender`.
why not the whole event? do we need to worry about event IDs here?

2021-05-06 03:55 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +view/peek the root room (including if  that room does not exist).
for not found, shouldn't that be M_NOT_FOUND?

2021-05-06 03:57 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  suggested in [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772).
is it supposed to? Implementation notes in the proposal section are a bit unexpected.

2021-05-06 03:57 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +POST /_matrix/federation/v1/spaces/{roomID}
POST/GET argument extends to this as well.

2021-05-06 03:58 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +MSC.
Pagination seems pretty important for a feature like this: what is the motivation for excluding it?

2021-05-06 04:02 UTC, turt2live reviewed
overall the MSC seems to be in the right direction, though is missing a lot of the detail which describes conversations that have likely already been had.

2021-05-06 12:13 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  case-sensitive.
I'm not sure I understand, are you saying to just remove this paragraph?

2021-05-06 12:14 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  (which *does* apply to the root room); attempts to exceed this  limit are
This paragraph is pretty much saying use `min(provided, 50)`, but 50 is just a recommendation.

2021-05-06 12:17 UTC, clokep commented on proposals/2946-spaces-summary.md
> +MSC.
I believe the conversation for not including pagination was that it is extremely complicated and unclear how much benefit it would bring (are cases of having over 50 rooms in a space common?), but maybe @richvdh or @t3chguy can elaborate as they were more involved in that conversation.

2021-05-06 12:20 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +MSC.
Pagination is definitely desired. @richvdh might be better to comment on this but the concern was that we don't know what the shape of the pagination mechanism should be, it could be that this API is breadth first up to a limit but always returning at least an entire depth, then you could just call this same API on a different root node as a form of traversal, or whether it should be more like the room directory/room pagination with an opaque token.

2021-05-06 12:34 UTC, clokep commented on proposals/2946-spaces-summary.md
> +* **`events`**: `m.space.child` events of the returned rooms. For each event, only the
I'm not sure there's a particular reason, I believe the child events could be added under the room.

2021-05-06 12:35 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  `sender`.
As you mentioned above, this is pretty much the stripped state, with the room ID (so you can map it to the rooms above).

2021-05-06 12:50 UTC, clokep commented on proposals/2946-spaces-summary.md
> +view/peek the root room (including if  that room does not exist).
This matches the behavior of other room endpoints (e.g. [`/aliases`](https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-rooms-roomid-aliases)). I assume it is to not divulge whether the user doesn't have permission or the room doesn't exist.

2021-05-06 12:51 UTC, clokep commented on proposals/2946-spaces-summary.md
> +POST /_matrix/federation/v1/spaces/{roomID}
I think I'd rather get rid of the both forms for the C-S API than to add them both to the S-S API. 🤷

2021-05-06 14:01 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +POST /_matrix/federation/v1/spaces/{roomID}
agreed, we should just spec one. It's a read-only API so it should be GET imho.

2021-05-06 15:01 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  case-sensitive.
just shortening it to "must be a boolean" would be fine, probably merging it into some other text somewhere.

2021-05-06 15:03 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  `sender`.
right, but why is this stripped state instead of the whole event? It's not immediately clear in the MSC why we're intentionally using stripped state over the client-server formatted events.

2021-05-06 15:06 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +view/peek the root room (including if  that room does not exist).
ah, would be good to get that into the MSC then. That makes sense :)

2021-05-06 15:08 UTC, clokep commented on proposals/2946-spaces-summary.md
> +None.
I added some brief notes. I think this is mitigated a bit by limiting the total number of rooms visited. Maybe we should rate limit the endpoint though...

2021-05-06 15:10 UTC, clokep commented on proposals/2946-spaces-summary.md
> +POST /_matrix/federation/v1/spaces/{roomID}
I've updated both of these to be `GET` only!

2021-05-06 15:17 UTC, clokep commented on proposals/2946-spaces-summary.md
> +* **`events`**: `m.space.child` events of the returned rooms. For each event, only the
@Kegsay / @richvdh Any idea why these were not added under the rooms themselves? I'm guessing this was due to the original implementation going up and down the tree or something?

2021-05-06 15:18 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  `sender`.
@Kegsay / @richvdh Not sure why this was chosen in particular. Was it just because it felt that the entire event was not needed and this reduces API size? Is it due to not wanting to leak more information than necessary?

2021-05-06 15:22 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +* **`events`**: `m.space.child` events of the returned rooms. For each event, only the
@Kegsay might know better, but I think the idea is that it's possible under certain circumstances - particularly with pagination? - to return events without their parent rooms.

2021-05-06 15:49 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +  `sender`.
For a few reasons:
 - To make sure we leak as little metadata as possible (think timestamps, `prev_content`, etc)
 - To make sure clients treat this data separately to normal events. Much like with invite state, the data here may not be trustworthy (if it came over federation) and is no substitute to the actual events.

2021-05-06 15:52 UTC, Kegsay commented on proposals/2946-spaces-summary.md
> +* **`events`**: `m.space.child` events of the returned rooms. For each event, only the
> I'm guessing this was due to the original implementation going up and down the tree or something?

This is the main reason. The previous impl had children and parents, so it wasn't clear where each event should live. The new impl just has children which are events in the room, so it could in theory live under there. However, this wouldn't play nicely with any kind of pagination as vdh points out: if you have a room (so you know the name, topic, etc) you don't want to have to return that data _again_ when returning the next page of results for the room.

2021-05-06 15:58 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  (which *does* apply to the root room); attempts to exceed this  limit are
I'd suggest leaving it at "the server might impose a more restrictive limit than the client requested" - the details aren't important for the MSC/spec.

2021-05-06 15:59 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  `sender`.
fair, would be good to document those details in the MSC.

2021-05-06 16:33 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  `sender`.
Thanks so much for the context. I've added this to the MSC.

2021-05-06 16:40 UTC, clokep commented on proposals/2946-spaces-summary.md
> +* **`events`**: `m.space.child` events of the returned rooms. For each event, only the
As discussed below these are stripped state events. We can explore renaming the field.

2021-05-07 14:05 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  suggested in [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772).
Ordering the results can potentially be really hard due to not necessarily having state of all the children of a room. If you don't have state you don't have the `origin_server_ts` of the `m.room.create` even, which is required for ordering according to MSC1772.

I think it might be an improvement to modify the ordering described in MSC1772 to only use data available in the children events instead of assuming the homeserver is in all of those rooms. I'd be curious on the thoughts of others here though! (I think that using the `origin_server_ts` was essentially an arbitrary tie-breaker anyway, so removing it shouldn't be too controversial.)

2021-05-10 14:45 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  suggested in [MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772).
matrix-org/synapse#9954 implements this, and c142433c65ff02e799575b1989a88660c8bddf3b adds some notes about this to the MSC itself.

2021-05-10 17:29 UTC, clokep commented on proposals/2946-spaces-summary.md
> +### Server-server API
I added some more information about this, hopefully it makes sense now!

2021-05-10 17:32 UTC, clokep commented
I've gone back through the open threads for this and resolved the ones which I feel have been take care of. I think the major remaining bits of work are:

* Does the API response shape make sense or should we move to having the events be under the returned rooms?
* Figure out how pagination on this API would look.

These are related and will impact each other.

2021-05-12 13:28 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +information available in the `m.space.child` event.
The point of this was to make newer/older sub-spaces/rooms appear last naturally, using roomId won't achieve this and misses the goal.
How about using the ts of the relationship event?

2021-05-12 13:38 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  events that point to them are still returned.
We should probably define more clearly what "accessible" means here.

2021-05-19 13:07 UTC, clokep commented on proposals/2946-spaces-summary.md
> +   3. Add any `m.space.child` events of the room to `events`.
This causes a bit of an odd thing to happen (see matrix-org/synapse#10020) where you can end up with an event that mentions a room, but then no room entry. It is unclear *why* you don't have the room entry (it could be either due to reaching the limit of the API response *or* due to not having access to the room).

Is having the event here useful? What purpose does it serve?

(Note that this is not any additional metadata leak -- the event is part of the state of the room so is accessible to the requester anyway.)

2021-05-19 17:18 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  events that point to them are still returned.
This was done in 3b0051fb103f150810901375a2191ae9c1b2e566.

2021-05-19 17:38 UTC, clokep commented on proposals/2946-spaces-summary.md
> +information available in the `m.space.child` event.
>  How about using the ts of the relationship event?

This would be fine with me! I've updated this with the above info!

2021-05-20 16:17 UTC, clokep commented on proposals/2946-spaces-summary.md
> +   1. If the room is inaccessible (as defined by [room history visibility](https://matrix.org/docs/spec/client_server/latest#id87))
We should probably handle something about knocking (once that's implemented) to allow rooms to be visible if they're knockable. Or maybe we should define "accessible" as "able to join" (see [MSC3173](https://github.com/matrix-org/matrix-doc/pull/3173)).

2021-05-21 19:13 UTC, clokep commented on proposals/2946-spaces-summary.md
> +`m.space`, any room with `m.space.child` events is considered.
I'm not sure why we do this -- it seems that at least Element Web strips out these results if it isn't a space, so why are we sending them? Why would we not consider the type?

2021-05-28 16:57 UTC, clokep commented on proposals/2946-spaces-summary.md
> +MSC.
I've thought about this a little bit and I *think* that the idea of traversing by providing different root nodes could lead to many request/response cycles in the case of a deep and narrow hierarchy. You might be able to pair this with greedily continuing down layers until a limit is reached, but that sounds complicated. This also seems difficult to guard against loops, but maybe that could be left up to the calling client?

In the opposite case (a shallow, wide hierarchy) you run into the issue where you might need to paginate the current depth, but this seems straightforward (you just need the node whose children are being fetched and the last returned result).

I think something similar to the current API, but including a pagination token might work. The server would need to keep track of quite a bit of state to continue the processing though, including: the processed rooms, the processed events, and the pending queue of rooms to look at. You could probably serialize those into a large pagination token, or store it in the database.

Overall, I think traversing via the tree (by choosing different roots) feels more elegant?

2021-06-04 13:00 UTC, clokep commented on proposals/2946-spaces-summary.md
> +The response has the same shape as the Client-Server API.
This needs updates based on changes to MSC3083, see https://github.com/matrix-org/matrix-doc/pull/3083/commits/0f4961118eddaf2959ad1d765dd3a0c8422df0a6

2021-06-11 13:53 UTC, clokep commented on proposals/2946-spaces-summary.md
> +`m.space`, any room with `m.space.child` events is considered.
I've reworked this to only include space rooms.

2021-06-11 13:54 UTC, clokep commented on proposals/2946-spaces-summary.md
> +   3. Add any `m.space.child` events of the room to `events`.
I've clarified the bit below about when these links to nowhere are turned.

2021-07-15 07:42 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +    [MSC3083](https://github.com/matrix-org/matrix-doc/pull/3083).
This got implemented as `allowed_spaces` - we need to either fix the MSC or the impl

2021-07-15 07:44 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +            "allowed_spaces": ["!abcdef:bleecker.street"]
This field got renamed but also should not be present in the cs api response, only in the ss api

2021-07-28 16:04 UTC, richvdh reviewed
looks very sensible to me. I can't see any obvious problems, but that's certainly not to say some won't appear during implementation...

2021-07-28 16:06 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
maybe `/children` ?

2021-07-29 08:47 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +    * **`creation_ts`**: the value of the `origin_server_ts` field from the
Sure but then you might think which `origin_server_ts` - the one of the latest event in the room? the earlier? neither, the one of the m.room.create event.

2021-07-29 11:17 UTC, clokep commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
Some of the rooms will be spaces -- this returns the room you asked for, as well as children rooms (including spaces).

2021-07-29 11:18 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
But I already implemented it as `/children` :D

https://github.com/matrix-org/matrix-js-sdk/pull/1818

2021-07-29 11:19 UTC, clokep commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
(Although `/children` does seem a bit more functional. It returns the room itself too though, which is a bit odd.)

2021-07-29 11:22 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
Good point. I'm not a huge fan of either the more I think about it. `/hierarchy` maybe?

2021-07-29 11:44 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    * **`creation_ts`**: the value of the `origin_server_ts` field from the
It is not from the create event, it is the one from the `m.space.child` event (this MSC attempts to change what MSC1772 says).

Pretty much all the fields are from the same event, so it is reasonable to use the "real" field names.

2021-07-29 11:46 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +    * **`creation_ts`**: the value of the `origin_server_ts` field from the
oh right, yes 🤦

2021-07-29 15:20 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
> Some of the rooms will be spaces -- this returns the room you asked for, as well as children rooms (including spaces).

yes, some of them will be spaces, but many of them - most of them, even - will not be. It just felt a bit odd to be asking for `/spaces` and getting a load of results that weren't spaces. `/hierarchy` sounds sensible to me.

(to answer a point you made elsewhere - I realise this isn't new with this iteration of this API. It just felt a bit odd when I was re-reading it, and if you're changing other stuff anyway, we could revisit it.)

2021-07-29 15:22 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
also changing the path to `/hierarchy` would mean we can keep the same prefix, not that it matters much at all

2021-07-29 16:05 UTC, clokep commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
I'm OK with changing it to `/hierarchy` (and re-using the old prefix). I'll update it in a bit.

2021-07-29 17:41 UTC, clokep commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/spaces
I've made this change.

2021-07-29 17:53 UTC, clokep commented on proposals/2946-spaces-summary.md
> +should be returned if the `from` token provided is unknown to the server.
@t3chguy pointed out that we should go into a bit more depth about which (if any) parameters can be modified during pagination. E.g. changing `limit` seems very reasonable (e.g. pulling 50 items for a first page, then 10 at a time), while changing `max_depth` or `suggested_only` likely doesn't make sense.

2021-08-10 17:48 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +  there are no more results.
With the notable exception of `/notifications`, `next_token` is otherwise unused in the Matrix API. I've attempted a survey of the various APIs which paginate in some way at https://github.com/matrix-org/matrix-doc/issues/1898; it's hard to discern a pattern but I think `next_batch` is marginally more common.

2021-08-10 17:57 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  there are no more results.
Ah, thanks for taking a look. I think I saw there was a variety and just picked one which sounded good.

Would you recommend using `next_batch` for both the response and request fields?

2021-08-10 18:48 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  there are no more results.
Also -- this currently states it is an error to change some parameters during pagination. I wonder if it makes more sense to just ignore those parameters (or perhaps make it an error to provide them at all with the pagination token)?

2021-08-11 10:16 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +  there are no more results.
> Would you recommend using `next_batch` for both the response and request fields?

At this point I really have very little idea. Let me try and kick off a conversation about it in #1898.

2021-08-11 11:51 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  there are no more results.
I updated this to `from` / `next_batch`. We can change it again in the future if we want though.

2021-08-12 22:16 UTC, ara4n commented on proposals/2946-spaces-summary.md
> +  of the next `/spaces` request in order to request more rooms. If this is absent,
```suggestion
  of the next `/hierarchy` request in order to request more rooms. If this is absent,
```

2021-08-25 08:12 UTC, timokoesters commented on proposals/2946-spaces-summary.md
> +# MSC2946: Spaces Summary
I'm thinking about ways to speed up "space exploration" performance and one way would be to just return the room ids of all rooms and subspaces of a space so the client can lazily fetch them as it needs

That way clients can almost instantly present *something* to the user while waiting for more detailed information to arrive over federation

But maybe clients can already do this by calling other endpoints

2021-09-02 15:13 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +      below.
Unless I'm misreading the code, the current implementation in Synapse, doesn't appear to follow this:  https://github.com/matrix-org/synapse/blob/v1.41.0/synapse/handlers/room_summary.py#L648-L652. See also https://github.com/matrix-org/matrix-doc/issues/877.

2021-09-03 19:36 UTC, clokep commented on proposals/2946-spaces-summary.md
> +      below.
Good shout, we're not doing this properly. I've put up a fix for Synapse: matrix-org/synapse#10760.

I'm not sure if this invalidates your comment on #877 or not.

2021-09-07 16:21 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +      below.
I think it does. THanks!

2021-09-07 16:24 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    `type`, `state_key`, `content`, `room_id`, `sender`,  with the addition of:
I wonder if `room_id` is actually useful here after nesting `children_state` under each entry in `rooms`? It should just match the parent's `room_id` field.

2021-09-07 16:43 UTC, turt2live commented
It is proposed that this is ready for FCP.

2021-09-07 16:47 UTC, clokep commented
This has both Synapse and Element Web implementations (which I've now noted in the description) so I think the `needs-implementation` label can be removed.

2021-09-08 20:16 UTC, K1D77A commented
Can you change it so that private subspaces that you are a member of are listed by a call to /hierarchy? Obviously private spaces should not be listed, but if you have Space A -> Private Space B and you are a member of Private Space B why is it not listed in a call to /hierarchy, this doesn't make sense to me. Thanks.

2021-09-09 12:14 UTC, clokep commented
> Can you change it so that private subspaces that you are a member of are listed by a call to /hierarchy? Obviously private spaces should not be listed, but if you have Space A -> Private Space B and you are a member of Private Space B why is it not listed in a call to /hierarchy with Space A, this doesn't make sense to me. Thanks.

They should be listed, if they're not than that's an implementation bug (and should be filed against Synapse with steps to reproduce -- but please make sure you're on the latest Synapse first).

(Also please use threads -- it makes it easier to track comments.)

2021-09-10 12:35 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +The persisted state will includes:
```suggestion
The persisted state will include:
```

2021-09-10 12:36 UTC, richvdh commented
lgtm

@mscbot fcp merge

2021-09-10 18:44 UTC, timokoesters commented on proposals/2946-spaces-summary.md
> +# MSC2946: Spaces Summary
Thoughts on this? Last time I tested space exploration on Synapse it was very slow and this could improve it.

2021-09-10 18:52 UTC, clokep commented on proposals/2946-spaces-summary.md
> +# MSC2946: Spaces Summary
It has been significantly improved recently.

I suspect the overhead of lazily fetching each room would be much slower in the case of a user who is not in many of the rooms in a space.

It might be faster in the case of a user who is in all rooms in a space.

Part of way the API is intensive is the recursive nature of it, I'm unsure if you're suggesting *not* doing that in your comment. If so, that's already possible by giving the `max_depth` parameter.

2021-09-20 20:53 UTC, turt2live requested changes
The proposal overall looks fine - just a few clarification points before I'm comfortable sending this off for FCP. 

It feels like this MSC has suffered multiple iterations but has not been fully cleaned up between those iterations. Not sure how we can really help with this process-wise; maybe a sort of proof reader step to ensure it's ready for FCP? Assuming the iterations can't be solved at an earlier step, of course.

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +This endpoint requires authentication and is not subject to rate-limiting.
Rationale for why this endpoint is exempt from rate limiting would be appreciated.

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/hierarchy
We should probably call this a `space_hierarchy` or similar to avoid confusion with room upgrade "hierarchies".

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +    * **`origin_server_ts`**: This is required for sorting of rooms as specified
origin timestamp of what?

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +    * **`origin_server_ts`**: This is required for sorting of rooms as specified
this is also not in the example below

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/hierarchy
applies to the federation endpoint too

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  from other servers.
for clarity: is this a SHOULD or a should? Difference being whether or not it ends up in the spec verbatim as a recommendation rather than a requirement: it feels important to let servers verify this bit of information with another server to ensure the responding server isn't misleading the requesting server.

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +An HTTP response with a status code of 404 is returned if the target server is
```suggestion
An `M_NOT_FOUND` error with a status code of 404 is returned if the target server is
```

2021-09-20 20:53 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +When a user asks HS1 for the space summary with a `max_rooms_per_space` equal to
Where does `max_rooms_per_space` come from?

2021-09-21 12:30 UTC, clokep commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/hierarchy
I'd really like to avoid further bike-shedding on the URL.

The only reference in the spec I see to hierarchies is at the [description of room versions](https://matrix.org/docs/spec/#id5):

> There is no implicit ordering or hierarchy to room versions, and their principles are immutable once placed in the specification. Although there is a recommended set of versions, some rooms may benefit from features introduced by other versions. Rooms move between different versions by "upgrading" to the desired version. Due to versions not being ordered or hierarchical, this means a room can "upgrade" from version 2 to version 1, if it is so desired.

I don't really see how this could be confused with this endpoint.

2021-09-21 12:32 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    * **`origin_server_ts`**: This is required for sorting of rooms as specified
I think this is fairly clear:

> For each event, only the following fields are included [...], with the addition of: `origin_server_ts`

Can you provide more info on how you would like this to be clarified?

(I've fixed the example already.)

2021-09-21 12:34 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  from other servers.
I think "SHOULD" -- it is a waste of resources to attempt to further request those room IDs from other servers.

> it feels important to let servers verify this bit of information with another server to ensure the responding server isn't misleading the requesting server.

This could be said about pretty much everything from this federation API. The information isn't really verifiable from the requesting server.

2021-09-21 12:40 UTC, clokep commented on proposals/2946-spaces-summary.md
> +When a user asks HS1 for the space summary with a `max_rooms_per_space` equal to
This field no longer exists, I've updated this section.

2021-09-21 12:41 UTC, clokep commented on proposals/2946-spaces-summary.md
> +This endpoint requires authentication and is not subject to rate-limiting.
I have no rationale, I arbitrarily picked not rate-limited and was hoping to have a conversation about it which was probably lost in the many comments above.

2021-09-24 21:47 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +This endpoint requires authentication and is not subject to rate-limiting.
It's probably fair to consider this endpoint not rate limited for now, given client behaviour is quite tightly coupled to the endpoint. Servers can also cache this reasonably well on a per-room basis, and the response size is relatively fixed, making it easy to constrain resources on. 

Excessive abuse of the endpoint can (and should) lead to rate limiting, but that's not really what the spec is trying to address. The spec is more or less trying to indicate which endpoints are "high traffic".

2021-09-24 21:49 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/hierarchy
It's less so the actual spec definition of room versions and more so how the community and ecosystem views room versions. No matter how hard we try to communicate how room versions work, including documenting all their nuances, people still see them as rolling improvements with an "old room" and a "new room", creating a hierarchy. 

I'm very interested in not bikeshedding this to death, but I do think that the word "space" needs to be in the endpoint. This doesn't require re-implementing the MSC or changing how clients use the unstable prefix, so should be safe to change.

2021-09-24 21:50 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +    * **`origin_server_ts`**: This is required for sorting of rooms as specified
The indentation tripped me up on this :( 

I'm happy to blame Markdown on this though.

2021-09-24 21:59 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  from other servers.
It's true from a federation perspective, but there's always avenues a server can take to verify the data it receives. We haven't yet made a suggestion in the spec for a server to *not* try other servers, though we also haven't put in a recommendation that they *should* do so. 

It's a bit of a philosophical argument about whether or not it's fair for the spec to say a server shouldn't try another server or not. For Matrix, we've typically leant more on the side of letting servers make bad decisions with respect to resource consumption but provide a way for them to improve (such as shortcuts in state res) - for this case, other servers might still have the information but it's highly unlikely, thus the requesting server would be wasting it's time. 

Rewording the sentence puts the onus on the requesting server to decide if it wants to waste resources or not, but still maintains the recommendation to not bother:

```suggestion
  Other servers are unlikely to have information about them as well, thus the
  requesting server can consider the rooms inaccessible from everywhere.
```

2021-09-24 22:03 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +    `type`, `state_key`, `content`, `room_id`, `sender`,  with the addition of:
can we put the words "stripped state" somewhere in here to pull in all the behaviour of [MSC3173](https://github.com/matrix-org/matrix-doc/pull/3173) ?

2021-09-28 10:45 UTC, clokep commented on proposals/2946-spaces-summary.md
> +This endpoint requires authentication and is not subject to rate-limiting.
> Servers can also cache this reasonably well on a per-room basis, and the response size is relatively fixed, making it easy to constrain resources on.

This isn't really true since the response heavily depends on user permissions to see rooms.

2021-09-28 10:50 UTC, clokep commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/hierarchy
I would be interesting in hearing the opinions of others, there was already a bikeshed about this (https://github.com/matrix-org/matrix-doc/pull/2946#discussion_r678442008 -- I don't know if that will load well because of GitHub).

> it kinda feels a bit silly that we are asking for `/spaces` when, for all we know, none of the rooms in the result will actually be spaces. But that's bikeshedding and I'm not sure I have any better ideas.

`/children` and `/hierarchy` were the other suggestions we came up with and settled on `/hierarchy` due it not returning strictly children.

2021-09-28 10:52 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    `type`, `state_key`, `content`, `room_id`, `sender`,  with the addition of:
Yeah, it's in the footnote but I'm not really sure why that's a footnote. 🤷 Probably left over from rewritings!

2021-09-28 13:38 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +## Proposal
the endpoint should exclude upgraded rooms where the server can see the new rooms.

2021-09-28 13:48 UTC, t3chguy commented on proposals/2946-spaces-summary.md
> +## Proposal
and where that upgraded room is also a child of the same parent surely? otherwise rooms might just vanish if the user doing the upgrade isn't an admin in the space also (e.g personal spaces)

2021-09-28 22:20 UTC, clokep commented on proposals/2946-spaces-summary.md
> +## Proposal
Meaning that the expectation is that when you upgrade a room you *don't* remove it from the space and just let both coexist, but only return the "latest" room or something like that?

2021-09-28 22:30 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +## Proposal
yea, so the rooms don't get punted to Home if you haven't rejoined yet.

2021-09-29 02:00 UTC, uhoreg reviewed
Looks mostly OK.  Mostly a bunch of nit picking

2021-09-29 18:21 UTC, clokep commented on proposals/2946-spaces-summary.md
> +period of time and to prefer local data over data returned over federation.
If you have Space A with Room B in it. HS1 is in Room B, but not Space A. When HS1 queries HS2 for Space A over federation the contents of Room B will be returned. Those should be discarded and calculated directly by HS1.

2021-09-29 18:47 UTC, uhoreg commented on proposals/2946-spaces-summary.md
> +period of time and to prefer local data over data returned over federation.
Aha, that makes sense.  Can we make that more explicit?  Maybe we can change the wording to

```suggestion
period of time.  The federation results may contain information on a room
that the requesting server is already participating in; the requesting server
should use its local data for such rooms rather than the data returned over
federation.
```

(which is significantly more wordy, but I'm not sure how to make it less wordy)

2021-09-29 18:58 UTC, clokep commented on proposals/2946-spaces-summary.md
> +    `type`, `state_key`, `content`, `room_id`, `sender`,  with the addition of:
I've removed this as it is redundant.

2021-09-29 19:05 UTC, clokep commented on proposals/2946-spaces-summary.md
> +persisted data may be discarded to limit resource usage.
That's fair, I don't know if we should be requiring that as part of the MSC though, it seems a little deep in the weeds of how to implement it. This was mostly included to have some logic on protecting the server from resource exhaustion.

2021-09-29 19:08 UTC, clokep commented on proposals/2946-spaces-summary.md
> +## Proposal
That seems reasonable on paper. I'll see how hard that is to implement.

2021-09-29 19:28 UTC, clokep commented on proposals/2946-spaces-summary.md
> +## Proposal
I see a couple of potential issues with this:

* If the upgraded room is moved to a sub-space, would we want to check if it appears anywhere in the hierarchy? (I'd think not.) It could be confusing if you reorganize rooms that old tombstoned rooms reappear though.
* Would we return both rooms as part of the `children_state`? (I'd think so since they're both still there.)

2021-09-30 14:48 UTC, uhoreg commented on proposals/2946-spaces-summary.md
> +persisted data may be discarded to limit resource usage.
How about just something like "To prevent resource exhaustion, the server may expire persisted data that it deems to be stale."

2021-10-01 11:38 UTC, clokep commented on proposals/2946-spaces-summary.md
> +persisted data may be discarded to limit resource usage.
I'll add something like that, thank you! :)

2021-10-05 16:48 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +## Proposal
> It could be confusing if you reorganize rooms that old tombstoned rooms reappear though.

This. To me it feels magical that we suppress the old room until the new room is removed from the space, at which point the old room suddenly reappears.

>     * Would we return both rooms as part of the `children_state`? (I'd think so since they're both still there.)

Probably? But won't it be odd that there are rooms referenced in `children_state` which we can't see?

Generally, I feel like this needs more thought, and implementation, and I don't really think we should block this MSC on it. I'd much rather we land what we have (and get it off unstable endpoints) despite a rough edge or two, than block it until we have good answers on the interaction of room upgrades with space summaries.

2021-10-05 16:50 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +This endpoint requires authentication and is not subject to rate-limiting.
> It's probably fair to consider this endpoint not rate limited for now

@turt2live: to be explicit: this means that you are happy for this to be left as-is?

2021-10-05 19:55 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +This endpoint requires authentication and is not subject to rate-limiting.
The opposite: the conversation on this thread is leading me to believe that rate limiting should be required given there's no obvious reason for it to be exempt.

2021-10-05 19:58 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +GET /_matrix/client/r0/rooms/{roomID}/hierarchy
The rationale for the endpoint naming doesn't really read as something that was fully considered to me. I'm still not happy with the naming here, but it's also not a blocking concern.

2021-10-05 20:06 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  number of rooms to return per page. Must be a non-negative integer.
Nit: 
```suggestion
  number of rooms to return per page. Must an integer greater than zero.
```

2021-10-05 20:06 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +  to no-limit. Must be a non-negative integer.
Nit:
```suggestion
  to no-limit. Must be an integer greater than zero.
```

2021-10-06 10:14 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +  number of rooms to return per page. Must be a non-negative integer.
it can be zero though?

2021-10-06 10:28 UTC, richvdh commented on proposals/2946-spaces-summary.md
> +This endpoint requires authentication and is not subject to rate-limiting.
ok. I agree with that logic :)

2021-10-06 15:54 UTC, deepbluev7 commented on proposals/2946-spaces-summary.md
> +  Client-Server API response.
I think this should also include the `allowed_room_ids`, since you could have a restricted space, that needs room membership to join it (and at least one of those rooms exists on the requesting server).

2021-10-06 16:11 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  number of rooms to return per page. Must be a non-negative integer.
Including a limit of 0 seems to be not useful (it would be an empty response). The code allows this right now though, but we shouldn't.

2021-10-06 16:13 UTC, deepbluev7 commented on proposals/2946-spaces-summary.md
> +  to no-limit. Must be a non-negative integer.
I'd say a value of 0 would make sense for the depth, it would just return the top level room, wouldn't it?

2021-10-06 16:28 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  Client-Server API response.
The initial request does not ever get sent over federation. I'm not sure it actually says this anywhere above though. I need to double check.

2021-10-06 16:49 UTC, deepbluev7 commented on proposals/2946-spaces-summary.md
> +  Client-Server API response.
I would really like to be able to do the first request over federation for https://github.com/matrix-org/matrix-doc/pull/3266. And I think this could be useful for this MSC alone as well.

2021-10-06 17:08 UTC, turt2live commented on proposals/2946-spaces-summary.md
> +## Proposal
From what I understand of that conversation, the rough suggestion is that we'd expose a flag to show that a room/space is upgraded and likely where it points to (stripped state of the tombstone might work here, I think). This doesn't really solve the problem of the upgraded room moving into a subspace as part of the upgrade, though the general consensus appears to be that the old room is intended to be forgotten from the tree (at least in the UI), so the client could just trust that the new room being *anywhere* in the tree is enough to cause the old room to be hidden completely. Upgrading spaces still appears to have an issue where it could result in needless pagination requests, though room upgrades for (sub)spaces is generally an unsolved problem, so happy to punt that right out of this conversation (imo).

Of interesting note, https://github.com/matrix-org/matrix-react-sdk/pull/6906 solves much of the problem for when the client is aware of the upgraded room, though doesn't implement a local de-dupe approach from the upgraded flag mentioned above - this is easily something we can add later on.

Sorry for being moderately difficult on this: I really just want us to consider issues with implementation and spec before it causes problems in future MSCs. I realize that doing so drags out the MSC, which is by far not my favourite thing to do, but it's extremely important from a spec perspective that we don't fall into the trap of "well, it's released so let's approve the MSC".

> I'm really, really worried that we're very soon going to be in a position where migrating away from the unstable endpoints is just too difficult.

I honestly see this as a failure of the process, not of this thread. The SCT should have worked more closely with the teams/projects looking to ship the feature, and the teams/projects should have engaged the SCT to start working on a release date. In the end, no one appears to have engaged the other side (rightly so: it's not clear who should start this conversation), which ultimately means that spec review comes late when people feel as though the MSC can't change because the feature is in the wild and being relied upon. We've already talked about this problem at a spec retro, though that retro was too late for this MSC, and the conclusion is roughly "more communication". We should iron out the details of what that means exactly separate to all of this.

----

TLDR: Thank you for running the mental exercise, and sorry it's coming across as needlessly blocking. It's really not my intention to be an arbitrary pain/blocker for this MSC.

2021-10-06 17:11 UTC, turt2live commented
@mscbot resolve Relatively minor clarifications/cleanup to be done

2021-10-06 19:28 UTC, clokep commented on proposals/2946-spaces-summary.md
> +  Client-Server API response.
This is mentioned above: https://github.com/matrix-org/matrix-doc/blob/kegan/spaces-summary/proposals/2946-spaces-summary.md#errors

> An HTTP response with a status code of 403 and an error code of `M_FORBIDDEN` should be returned if the user doesn't have permission to view/peek the root room.

2021-10-06 20:29 UTC, deepbluev7 commented on proposals/2946-spaces-summary.md
> +  Client-Server API response.
Let's say we have space A. User x and y are on server S. The space A is on server U. You need to be member of room B to join the space A. x is member of room B, y isn't. If we now request a summary of the space A over federation, we won't get the room ids required to join A. So if y requested it, we can't know, if we should return the response to them or not.

Am I missing something?

2021-10-31 19:10 UTC, merged

2021-12-31 00:25 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-doc/pull/3610

2023-08-15 05:20 UTC, Flexusma commented
Just as a heads up to people that run into the same issue as I do: msc2946 still needs to be enabled in v0.13.1 (+49d75d3) and all prior versions to support spaces room listings (/hierarchy endpoint). In a comment in one of the referenced issues I read it was already integrated in v0.13.1 which was very confusing. Is this supposed to be like this? Or have I just not gotten the latest release which has the above PR implemented?

2023-08-15 07:58 UTC, t3chguy commented
@Flexusma v0.13.1 of -what-?

2023-08-15 11:39 UTC, Flexusma commented
Oof, sorry about that. I thought I was still in the dendrite repo. I clicked through 20 issues and must've lost track.