MSCXXXX: Room Version 7
matrix-org/matrix-doc pull request #2998
Opened 2021-02-08 11:44 UTC by anoadragon453

[Rendered](https://github.com/matrix-org/matrix-doc/blob/anoa/room_version_7/proposals/xxxx-rooms-v7.md)

2021-02-08 11:54 UTC, tulir requested changes

2021-02-08 11:54 UTC, tulir commented on proposals/2998-rooms-v7.md
> +* [MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174) - Move the `redacts` key to a sane place.
There's no point in having two migrations of redaction format, we should just skip this step and go straight for mass redactions

2021-02-08 12:10 UTC, anoadragon453 commented on proposals/2998-rooms-v7.md
> +* [MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174) - Move the `redacts` key to a sane place.
@tulir I didn't include [Mass Redactions](https://github.com/matrix-org/matrix-doc/pull/2244) as it doesn't currently have an implementation.

You're right in that putting MSC2244 and MSC2174, especially as the former builds on the latter, into the same room version makes sense though. I'd be happy to review/help with a Synapse PR for it.

2021-02-08 17:52 UTC, Sorunome commented on proposals/2998-rooms-v7.md
> +* [MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174) - Move the `redacts` key to a sane place.
also, doesn't `content.redacts` have to be protected from redaction now?

2021-02-08 18:01 UTC, turt2live commented on proposals/2998-rooms-v7.md
> +considered stable enough for v6 rooms. A future room version may still include them.
```suggestion
considered stable enough for v7 rooms. A future room version may still include them.
```

2021-02-08 18:13 UTC, tulir commented on proposals/2998-rooms-v7.md
> +* [MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174) - Move the `redacts` key to a sane place.
It is protected from redaction by MSC2176, that part works the same way for MSC2174 and MSC2244.

2021-02-18 15:59 UTC, anoadragon453 commented
It turns out [MSC2175](https://github.com/matrix-org/matrix-doc/pull/2175) (remove the creator field from create events) and [MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174) (move the redacts key) do not have an implementation yet after all, so they will also be excluded. [MSC2176](https://github.com/matrix-org/matrix-doc/pull/2176) (update redacted event fields) does [have an implementation](https://github.com/matrix-org/synapse/pull/8984) however, and while related to redactions, is only concerned about the keys removed from an event by the server when an event is redacted. This does not affect the structure of a redaction event, like [MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174) and [MSC2244](https://github.com/matrix-org/matrix-doc/pull/2244) (mass redactions) is concerned with.

While this leaves us with a fairly lean room version, releasing new features and changes more regularly in smaller room versions is a good precedence to set.

2021-02-18 16:13 UTC, clokep commented
> It turns out [MSC2175](https://github.com/matrix-org/matrix-doc/pull/2175) (remove the creator field from create events) and [MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174) (move the redacts key) do not have an implementation yet after all, so they will also be excluded. [MSC2176](https://github.com/matrix-org/matrix-doc/pull/2176) (update redacted event fields) does [have an implementation](https://github.com/matrix-org/synapse/pull/8984) however, and while related to redactions, is only concerned about the keys removed from an event by the server when an event is redacted.

I'm not sure I fully grok what this is saying, but #2176 seems to imply it only makes sense if #2174 was also implemented?

2021-02-22 19:13 UTC, anoadragon453 commented
[MSC2174](https://github.com/matrix-org/matrix-doc/pull/2174), [MSC2176](https://github.com/matrix-org/matrix-doc/pull/2176) and [MSC2274](https://github.com/matrix-org/matrix-doc/pull/2244) do indeed rely on each other and it would be best to land all of those in a single room version. As the implementation for each are not yet ready, as well as lacking an implementation for [MSC2175](https://github.com/matrix-org/matrix-doc/pull/2175) we're going to leave them til the next room version, and just go ahead with knocking for this one.

Note that this MSC has been updated to simply reserve v7 for knocking. It does not prevent an MSC for room v8+ appearing in parallel once the above MSCs (or any other MSCs for that matter) have implementations ready.

Given the above, I'm going to propose FCP on this one to get the rest of the team's feedback.

@mscbot fcp merge

2021-02-24 15:02 UTC, dbkr commented on proposals/2998-rooms-v7.md
> +considered stable enough for v7 rooms. A future room version may still include them.
This took me about 5 read to understand - isn't it just saying, "other mscs aren't ready yet because they don't have impls"?

2021-02-24 15:12 UTC, anoadragon453 commented on proposals/2998-rooms-v7.md
> +considered stable enough for v7 rooms. A future room version may still include them.
Indeed, but written a bit tersely for the spec. I'm open to suggestions for something slightly clearer though.

2021-02-24 19:33 UTC, gary-kim commented on proposals/2998-rooms-v7.md
> +considered stable enough for v7 rooms. A future room version may still include them.
Maybe `Though other MSCs could be included in this version, they do not have satisfactory implementations...`?

2021-02-25 18:59 UTC, anoadragon453 commented on proposals/2998-rooms-v7.md
> +considered stable enough for v7 rooms. A future room version may still include them.
I've dropped the `stable enough` bit. Hopefully that makes things slightly clearer.

2021-03-01 15:13 UTC, merged