MSC3013: Encrypted Push
matrix-org/matrix-doc pull request #3013
Opened 2021-02-17 12:15 UTC by Sorunome

[Rendered](https://github.com/Sorunome/matrix-doc/blob/soru/encrypted-push/proposals/3013-encrypted-push.md)

Signed-off-by: Sorunome <mail@sorunome.de>

Soru already has this working as a proof-of-concept with a patched synapse and a patched fluffychat and will look into PR'ing to to synapse

2021-02-17 12:20 UTC, Cadair commented on proposals/3013-encrypted-push.md
> +    "format": "event_id_only",
Not `event_id_only` here? You wouldn't need the `public_key` here?

2021-02-17 12:20 UTC, Cadair commented on proposals/3013-encrypted-push.md
> +always.
This sentence is unfinished?

2021-02-17 12:23 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +    "format": "event_id_only",
This is just an example, as the encrypted pusher inherits from http pusher, both `event_id_only` and (with that other msc) `full_event` would work.

2021-02-17 12:25 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +always.
right, missing "the case"

2021-02-17 12:26 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +    "format": "event_id_only",
The important bits here are `data.public_key` and the different `kind`

2021-02-17 13:45 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +    "format": "event_id_only",
Yeah, I agree that while this is technically correct, it makes for a slightly confusing example.

2021-02-17 13:48 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +    "format": "event_id_only",
The issue is that there are no other speced types yet, we need https://github.com/matrix-org/matrix-doc/pull/2782 for `full_event` :D Should soru just put `full_event` in there anyways?

2021-02-17 13:48 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +In a first draft symmetric encryption was used. However, using asymmetric encryption seams like the
```suggestion
In a first draft symmetric encryption was used. However, using asymmetric encryption seems like the
```

2021-02-17 13:50 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +It is still unclear how well this will work with iOS and its limitations, especially concerning badge-only
Since iOS can now have an extension to process incoming push, this actually works nicely with new enough iOS.

2021-02-17 13:51 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +It is still unclear how well this will work with iOS and its limitations, especially concerning badge-only
Yes, but they have to result in a notif. Badge-only push frames are because of an event being marked as read on another client, which only *removes* a notif. Soru is unsure how this works on iOS

2021-02-17 14:01 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +It is still unclear how well this will work with iOS and its limitations, especially concerning badge-only
I'm guessing the way you'd do it would be to move the logic of forming the iOS-specific payload from the push gateway (which can't do it anymore anyway because it can't read the data) into the push extension in the app, so it would both decrypt and then form the appropriate 'aps' payload etc (I assume setting a badge counts as 'displaying a notification').

2021-02-17 14:03 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +It is still unclear how well this will work with iOS and its limitations, especially concerning badge-only
> I assume setting a badge counts as 'displaying a notification'

This is basically what soru is asking about here.

Additionally, synapse is happy to send out multiple badge count updates with the same count, and then *nothing* would change. Not sure how  that'd work out, either.

These are basically the things soru is asking about in there, rather than assuming it'd work out ^^

2021-02-17 14:04 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +    "format": "event_id_only",
Ah, I see - yeah, it would probably be reasonable to put that and note that the example assumes #2782 is merged

2021-02-17 14:08 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +    "format": "event_id_only",
Updated it 👍

2021-02-17 14:12 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +
Could be worth noting that as an alternative, any app could prevent Apple/Google from reading content without spec by just having the push gateway encrypt the content before sending it to APNS/GCM. This MSC would mean the push gateway doesn't get the content either though.

2021-02-17 14:15 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +
done

2021-02-19 23:36 UTC, flumeware commented
Hi

```
1. Generate an ephemeral curve25519 key, and perform an ECDH with the ephemeral key and the backup's
   public key to generate a shared secret. The public half of the ephemeral key, encoded using unpadded
   base64, becomes the `ephemeral` property of the new payload.
```

Should backup's public key be pusher's public key?

Thanks

2021-02-22 13:43 UTC, toshanmugaraj commented on proposals/3013-encrypted-push.md
> +It is still unclear how well this will work with iOS and its limitations, especially concerning badge-only
- When notification is received in iOS, its pre-processed by client's notification extension. decryption is done here.
- Badge count that has to be displayed is processed in the extension.
- Unread count is set by the `unread_count` passed with the notification json.
- Decryption may fail in notification extension for some reasons, so its always consider handling if decryption fails. Now its handled by not encrypting `userInfo ` in the json.

2021-02-23 10:18 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +4. Pass the raw encrypted data (prior to base64 encoding) through HMAC-SHA-256 using the MAC key
If we include a mac the gateway (e.g. google) could start bruteforcing your private key. They might also be able to bruteforce it easily with other constraints, that e.g. the output has to be valid json. Wanted to ask @uhoreg how much a concern that would be

2021-02-23 17:07 UTC, uhoreg commented on proposals/3013-encrypted-push.md
> +4. Pass the raw encrypted data (prior to base64 encoding) through HMAC-SHA-256 using the MAC key
Brute forcing here shouldn't be much of an issue since the key is generated from (I would assume) a cryptographically secure source, so would take a long time to brute force.  It is an issue in cryptographic logins where the key is generated from a password that might not be very secure, but in this context, it should be fine.

2021-02-23 17:08 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +4. Pass the raw encrypted data (prior to base64 encoding) through HMAC-SHA-256 using the MAC key
Gotcha, thank you for the comment 👍

2021-04-03 20:00 UTC, Kegsay commented
[MSC 3079: Low Bandwidth CS API](https://github.com/matrix-org/matrix-doc/blob/kegan/low-bandwidth/proposals/3079-low-bandwidth-csapi.md) may be an alternative to this as it makes it viable to rely on `/sync` for push notifications directly as it is made bandwidth efficient.

2021-04-06 08:46 UTC, Cadair commented
I think this and #3079 are likely to be complementary. If you are already using your platforms push provider running a permanent background process is still going to be more expensive than using the push provider, no matter how well optimised it is. #3979 with the extra work to add sync filters just for events which trigger push is a good solution to if you don't have (or don't want) and untrusted push provider.

2021-04-07 11:40 UTC, Kegsay commented
Indeed, they can be complementary but at the cost of an increased API surface. If you don't trust your push provider, that has knock on concerns though. Malicious push providers can do more subtle attacks than just sniff the message (e.g delay the delivery) so the point the provider is untrusted then really you shouldn't be using it at all.

2021-04-09 17:25 UTC, kevincox commented on proposals/3013-encrypted-push.md
> +always the case.
```suggestion
always possible.
```

2021-04-09 17:25 UTC, kevincox commented on proposals/3013-encrypted-push.md
> +## Alternatives
Can we not use the same encryption methods used for [Web Push](https://tools.ietf.org/html/rfc8291). This seems to have a number of benefits.

* Libraries already exist to do the encryption and decryption.
  * Some fully integrated like this one for FCM: https://security.googleblog.com/2018/06/end-to-end-encryption-for-push.html
* Avoids double-encrypting when using Web Push anyways (like browser-based clients).
* Uses an open standard that has been heavily reviewed by security experts.

Of course IIUC push notifications don't use Web Push directly anyways so this won't get us all of the way to a standards based push implementation but at least it is half-compatible.

2021-12-07 10:20 UTC, anoadragon453 commented
Removing the `needs-implementation` label given the linked PRs.

2021-12-07 10:21 UTC, anoadragon453 commented
Have put this in the "initial review" column on the SCT Backlog board to get eyes on it, though it may already be under the watchful purview of @dbkr. Feel free to take it off the board if you want to re-claim it Dave.

2021-12-07 11:41 UTC, dbkr reviewed
This does add significant complexity (especially because it means Homeservers now have to do elliptic curve crypto too) but it does slot nicely into the gap for more secure (and/or more efficient) push in non-e2e rooms.

Would suggest the next step here is for someone with a crypto hat on to review the crypto side of it. It sounds like it would be quite heavyweight, equivalent to establishing a new megolm session per message?

2021-12-07 11:41 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +field absent, then an algorithm of `m.plain` is assumed. The algorithms are defined as following:
```suggestion
represented as string. The currently allowed values are `m.plain` and `m.curve25519-aes-sha2`. If the
field is absent, then an algorithm of `m.plain` is assumed. The algorithms are defined as following:
```

2021-12-07 11:41 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +this won't be possible anymore.
I'm not sure this was ever really used anyway, so much as it's a shame that the format now becomes a bit weird, it's probably no great loss. Probably ought to specify above that there should only be a single device in each push for that reason.

2021-12-07 11:41 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +updates if a message was read on another device.~~ --> This should work?
This seems like the kind of question we should have more data on if there's an impl?

2021-12-07 11:41 UTC, dbkr commented on proposals/3013-encrypted-push.md
> +comptible with libolms PkEncryption / PkDecryption methods.
Note that we're now moving away from this though, towards symmetric encryption for key backup. It would also be good to have some words on why this encryption scheme was chosen & what cryptographic properties it gives (and doesn't give).

2021-12-07 12:28 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +updates if a message was read on another device.~~ --> This should work?
This is the current comment thread for that: https://github.com/matrix-org/matrix-doc/pull/3013#discussion_r577625083

2021-12-07 16:09 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +this won't be possible anymore.
Synapse actually hard-codes to only ever have one device in that array, no idea about the other homeservers.

2021-12-07 16:10 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +comptible with libolms PkEncryption / PkDecryption methods.
as far as soru is aware the PkEncryption / PkDecryption was also used for asymmetric SSSS, and it seems like a good idea to have some go-to symmetric / asymmetric algorithms to use for the matrix world, though that is obviously beyond the scope of this PR.

2021-12-08 09:56 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +comptible with libolms PkEncryption / PkDecryption methods.
If you meant symmetric vs asymmetric cryptography, there is a paragraph on that under "Security considerations"

2021-12-08 10:02 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +# MSC3013: Encrypted Push
@dbkr 
> but it does slot nicely into the gap for more secure (and/or more efficient) push in non-e2e rooms.

This isn't only good for non-e2ee rooms, but also good for them, as it means that further down the road, building ontop of this, we can easily tackle on more metadata into the push payload. Together with #3014 and a yet un-written MSC to add unread information per room, this would allow to display full push contents without having to perform any additional HTTP request, thus working significantly more reliable in sketchy network areas.

2021-12-10 09:39 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +comptible with libolms PkEncryption / PkDecryption methods.
Another thing to note is that libolms PkEncryption / PkDecryption actually has a bug where it calculates the mac wrong (which soru discovered while working on encrypted push, uhoreg is aware about and said it is ok to talk about publicly as it only affects data integrity and not security itself), so until libolm gets fixed in that regard implementations need to do their own PkDecryption anyways

2021-12-23 10:05 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +It is still unclear how well this will work with iOS and its limitations, especially concerning badge-only
After finally having an iOS development setup soru can see some issues with iOS concerning messages that change the badge only: It currently does not appear that iOS allows the `mutable-content` to modify only the badge of the app, however the `unread` stuff is encrypted with this MSC, meaning that the push gateway is not able to set badge-only messages anymore. An obvious path forward here would be to not encrypt the unread dict, however that would also decrease the security on other platforms. Perhaps making that a separate option, if the `unread` dict should be encrypted, would make sense here.

2021-12-23 11:04 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +It is still unclear how well this will work with iOS and its limitations, especially concerning badge-only
Okay, so after discussing this issue internally, we have thought of a couple of possible solutions around this. All this affects iOS only:

1. Have a flag to *not* have the homeserver send badge-only updates. Pro: good for privacy. Con: The apps badge only updates after opening the app itself
2. For badge-only messages, include a `is_only_badge` bool in cleartext.
   The push gateway sends the encrypted parts only via the unreliable background push. Pro: good for privacy. Con: Badge updates are unreliable
3. For badge-only messages, include the `counts` dict in cleartext, in addition to the ciphertext.
   The push gateway sends full apns badge updates. Pro: good user experience. Con: Apple is able to see the exact number of unreads you have in real time

Of course all three could be done as well, so that which exact method is picked is up for the implementation. That way android could also pick e.g. (1) just fine and thus iOS isn't really special-cased.

2021-12-28 20:01 UTC, uhoreg reviewed
I don't know much about push notifications, but it looks plausible

2021-12-28 20:03 UTC, turt2live approved these changes
Overall this seems fine, I think

2021-12-28 20:04 UTC, turt2live commented
Let's get it on the agenda for consideration:

@mscbot fcp merge

2021-12-29 15:02 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +The field `public_key` is required. This key is an (optionally unpadded) base64-encoded curve25519
done

2021-12-29 17:41 UTC, clokep commented on proposals/3013-encrypted-push.md
> +update.
I'm finding the last sentence difficult to read, I think there's a word missing? Could you clarify it.

2021-12-29 17:42 UTC, clokep commented on proposals/3013-encrypted-push.md
> +it, allowing the server to send the full event over push again, with this MSC and [MSC2782](https://github.com/matrix-org/matrix-doc/pull/2782).
Does this require MSC2782 or can it work without it? (It is vague to me if there's a dependency -- if there is, I don't think this can be in FCP?)

2021-12-29 17:42 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +update.
hmm, no word is missing. what soru was trying to say is that `counts_only_type` stuffs was added to the msc so that push updates that only affect the counts, and do not contain any events, could also work with apns.

2021-12-29 17:43 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +it, allowing the server to send the full event over push again, with this MSC and [MSC2782](https://github.com/matrix-org/matrix-doc/pull/2782).
it can work without. MSC2782 just adds a new `format` to http pushers, which will make push way more useful but requires encrypted push.

2021-12-29 17:44 UTC, clokep commented on proposals/3013-encrypted-push.md
> +update.
Should the beginning be:

> For this, the `counts_only_type` setting has been **added to this proposal**, so that the push gateway...

2021-12-31 10:35 UTC, Sorunome commented on proposals/3013-encrypted-push.md
> +update.
yes, that's much better, thanks

2022-02-01 15:43 UTC, erikjohnston reviewed
I personally think its fine to make the server do some encryption, so this makes sense to me.

2022-02-01 15:43 UTC, erikjohnston commented on proposals/3013-encrypted-push.md
> +   property of the new payload.
It's worth mentioning that the server should immediately drop the ephemeral secret key and shared secret after each use (or at least regularly regenerate them). If either secret is leaked then the push content will be decryptable.

2022-02-15 15:28 UTC, richvdh commented on proposals/3013-encrypted-push.md
> +A new pusher data field, `algorithm`, is introduced for pushers of the kind `http`. It is an enum,
please could we have some links to the existing spec, so we can see what is changing?

2022-02-15 16:02 UTC, richvdh commented on proposals/3013-encrypted-push.md
> +   property of the new payload.
could we use AES-GCM or something modern rather than AES-CBC, for improved performance and to save having to make a separate MAC?

(olm/megolm avoided GCM because GCM wasn't terribly widely supported at the time - I don't think that's true any more?)

2022-02-15 21:09 UTC, deepbluev7 commented on proposals/3013-encrypted-push.md
> +   property of the new payload.
This code was intentionally designed to be similar to the current pk encryption in libolm, just without the bugs in it. But switching to a different cryptographic primitive solves that too, I guess. But it would need some of the crypto experts approval then.

2022-02-15 22:13 UTC, uhoreg commented on proposals/3013-encrypted-push.md
> +   property of the new payload.
The only other (standard) use for libolm's pkencryption is in key backups, and we're moving away from that to symmetric key backup.  So being consistent with other things is probably less of a concern.

AES-GCM should be fine.

2022-02-16 10:25 UTC, richvdh commented
Just to pick up on an earlier comment by @dbkr

> This does add significant complexity (especially because it means Homeservers now have to do elliptic curve crypto too) 

note that homeservers always had to do EC crypto, for signing events/requests. Admittedly that was all ed25519 *signing* rather than x25519 DH, but the point remains that any HS implementation is already going to be linked against a curve25519 library.

2022-02-17 18:42 UTC, turt2live requested changes

2022-02-17 18:43 UTC, turt2live commented
@mscbot concern Enums vs namespaces
@mscbot concern Algorithm might need further review
@mscbot concern Push data is overloaded currently and should be avoided (use top level keys instead)

2022-04-08 21:44 UTC, turt2live commented
@Sorunome are you able to take a look at updating this to unblock FCP?

2022-04-09 23:39 UTC, deepbluev7 commented
@turt2live I am planning to implement the changes proposed in ~1.5 weeks and try them out, then update the MSC. But I am still a bit busy next week (and was for the last 8).

2022-08-02 06:55 UTC, manuroe commented on proposals/3013-encrypted-push.md
> +and thus e2ee push notifications, is possible on iOS, these modified push frames *have* to result in
An iOS app can bypass the mandatory display of a user notification for each push by using [com.apple.developer.usernotifications.filtering](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering) entitlement.

The app develop must request it to Apple before using it. Element-iOS uses it now.

2023-06-05 22:55 UTC, turt2live commented
@deepbluev7 From the chat in the SCT office room last week it sounds like you're aiming to take this on? It looks like it's stuck in needing an implementation and a text update.

Given it's been over a year since the FCP call was stalled due to concerns, I'm cancelling FCP for now and we can re-start it with modern process/considerations. It sounds like it'll be relatively easy to get back into shape?

@mscbot fcp cancel

Once this is ready for re-review, let us know in the [SCT Office](https://matrix.to/#/#sct-office:matrix.org) please.

2023-08-31 12:13 UTC, BillCarsonFr requested changes

2024-07-12 13:44 UTC, p1gp1g commented on proposals/3013-encrypted-push.md
> +## Alternatives
The advantage of using web push directly:
- This is E2EE, and gives VAPID
- This is a standard:
    - Libraries are already available
    - Has been reviewed and acknowledged
    - Many webpush to APNS/FCM/HMS gateways already exist
- This can provide push notifications without gateway to
    - Web app and desktop app
    - Android apps using UnifiedPush
- This doesn't have a requirement on the path (making https://github.com/matrix-org/matrix-spec-proposals/pull/2970/files obsolete)

2024-07-12 13:59 UTC, p1gp1g commented
Posting here, I commented on a resolved comment..

A (robust IMO) alternative would be to add a _webpush_ pusher kind directly.

The advantage of using web push directly:

- This is E2EE
-  It supports VAPID
- This is a standard:
    - Libraries are already available
    - Has been reviewed and acknowledged by experts
    - Webpush to APNS/FCM/HMS gateways already exist
    - The ecosystem should tend to use this instead of other custom protocols
- This can provide push notifications without gateway to
    - Web app and desktop app
    - Android apps using UnifiedPush
    - Maybe other ? We have seen apple moving a lot into web push support
- This doesn't have a requirement on the path (making https://github.com/matrix-org/matrix-spec-proposals/pull/2970/files obsolete)

2024-08-01 15:56 UTC, p1gp1g commented
Here it is: https://github.com/matrix-org/matrix-spec-proposals/pull/4174

2026-02-05 11:10 UTC, poljar commented on proposals/3013-encrypted-push.md
> +   property of the new payload.
I would rather argue that the whole lot of `PkEncryption` should not be used.

It has a plethora of problems:

1. It is buggy as mentioned in https://github.com/matrix-org/matrix-spec-proposals/pull/3013#discussion_r766517926.
2. It does not provide support for domain separation.
3. No additional data can be authenticated.
4. It's not a well-defined standard outside of Matrix

On the other hand, nowadays we have HPKE, and [HPKE's one-shot API](https://www.rfc-editor.org/rfc/rfc9180.html#name-single-shot-apis) would fit the need here. In fact it would fit well in the asymmetric room key backup case as well.

2026-02-05 11:14 UTC, poljar commented on proposals/3013-encrypted-push.md
> +comptible with libolms PkEncryption / PkDecryption methods.
See my comment about HPKE here: https://github.com/matrix-org/matrix-spec-proposals/pull/3013#discussion_r2768480912.

Which will be used in [MSC4388](https://github.com/matrix-org/matrix-spec-proposals/pull/4388).

2026-03-17 17:03 UTC, richvdh commented
Proposing this for closure, since MSC4174 claims to replace it and is proposed for FCP. If anyone feels like this *shouldn't* be closed once MSC4174 is merged, please say so.

@mscbot fcp close

2026-03-17 17:09 UTC, tulir commented
MSC4174 doesn't replace this properly due to https://github.com/matrix-org/matrix-spec-proposals/pull/4174#discussion_r2766150551. Web push only supports P-256, but if we want to actually send message contents over push, we should use better crypto than that (although I'm not sure if the crypto suggested in this MSC is good either)

2026-03-17 19:03 UTC, p1gp1g commented
> if we want to actually send message contents over push

To clarify a bit: the content of E2EE encrypted messages are E2EE with the protocol supported by matrix (Olm/Megolm/MLS potentially), we are talking about metadata only here

2026-03-17 19:20 UTC, tulir commented
The goal of this MSC appears to be combining with #2782 to send full event content in pushes, not only metadata.

2026-03-17 19:22 UTC, p1gp1g commented
In E2EE communications, the full content send via push notification is encrypted content and we only encrypt its metadata on top of that

2026-03-18 06:48 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +A new pusher data field, `algorithm`, is introduced for pushers of the kind `http`. It is an enum,
```suggestion
A new [`PusherData`](https://spec.matrix.org/v1.17/client-server-api/#post_matrixclientv3pushersset_request_pusherdata) field, `algorithm`, is introduced for pushers of the kind `http`. It is an enum,
```

2026-03-18 06:49 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +be delivered, e.g. FCM (Google) or APNs (Apple) and an app-specific gateway (sygnal). In order to
```suggestion
be delivered, e.g. FCM (Google) or APNs (Apple) and an app-specific gateway (such as [Sygnal](https://github.com/element-hq/sygnal)). In order to
```

2026-03-18 07:00 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +For this, two new pusher data fields are added: `public_key` and `counts_only_type`. Both fields are
It seems like this was resolved [in chat](https://matrix.to/#/!0KNSXYXB_2xtEUkQ9MGBRy5oNIOfAKoq2uIqPZCJbI8/$jaXdgf_FBM7IOhHUWD7bqAIamwxFYRCnRWOZt7y7z7k?via=element.io&via=matrix.org&via=starstruck.systems) yesterday. IIUC, `PusherData` is not exclusively meant for things to pass through to the gateway but also for things that are specific to a particular pusher kind.

I tend to agree that separating these two purposes would probably be better but given that we already have the `url` property in the object, maybe that's a job for another MSC.

2026-03-18 07:07 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +Now, when the homeserver pushes out the message, it is to perform the `notification` dict as with the
Maybe it's just me but "perform" strikes me as slightly confusing here.

```suggestion
Now, when the homeserver pushes out the message, it is to construct the [`notification`](https://spec.matrix.org/v1.17/push-gateway-api/#post_matrixpushv1notify_request_notification) dict as with the
```

2026-03-18 07:09 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +   property of the new payload.
It feels like this should be in the proposal text as otherwise it possibly won't make it into the spec PR?

2026-03-18 07:18 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +## Unstable prefix
I think you also need vendor prefixes for the various new properties such as `public_key`?

2026-03-18 07:22 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +## Potential issues
The maximum payload size on both APNS and FCM seems to be 4096 bytes which might be exceeded based on the size of the event contained in the notification. This is already a problem today when not using `event_id_only` but I assume it's somewhat aggravated here since encryption will increase the overall payload size?

2026-03-18 07:24 UTC, Johennes commented on proposals/3013-encrypted-push.md
> +The field `counts_only_type` is an optional enum which denotes how push frames should handle counts-only
It's possibly just me but I'm finding the term "push frame" slightly irritating and I haven't met this terminology elsewhere yet. Can we not just say "push notification"?

2026-03-24 17:30 UTC, richvdh commented
> Proposing this for closure, since [MSC4174](https://github.com/matrix-org/matrix-doc/pull/4174) claims to replace it and is proposed for FCP. If anyone feels like this _shouldn't_ be closed once [MSC4174](https://github.com/matrix-org/matrix-doc/pull/4174) is merged, please say so.
> 
> @mscbot fcp close

It's unclear that MSC4174 *does* fully replace this MSC; however this MSC appears to be without an owner and has some substantial concerns. So I'm going to leave the FCP close proposal in place.

2026-03-24 19:40 UTC, uhoreg commented
I do not believe that MSC4174 replaces this, as we do not want to use the encryption scheme presented there with other push methods (which we are only accepting in MSC4174 because it comes as part of the Web Push bundle of standards and implementations).  However, we also will want to use a different encryption scheme than what is currently presented here, and at this point, it's probably better to start with a new MSC when we're ready to define how to do that, so I agree with FCP closing at this point.

2026-04-07 16:46 UTC, ara4n commented
I believe that Gematik's TI-Messenger spec may use this (at least in the past): https://www.google.com/search?q=site%3Agematik.de+msc3013

Meanwhile, the actual concept (speed up sync by putting event payloads over APNS/FCM - but encrypt the payload to stop Apple/Google being able to see it) doesn't feel unreasonable.

As others have said, MSC4174 is not a direct replacement for this.

So, instead, I suggest we talk to Gematik first before unintentionally rugpulling stuff they consider important. I suggest we cancel the FCP close meanwhile.

2026-04-07 16:53 UTC, ara4n commented
@mscbot concern does TI-Messenger still depend on this? We don't want to close MSCs without a future plan for direction if folks have been building on them.

2026-04-14 14:08 UTC, richvdh commented
Gematik have confirmed out-of-band that TI-Messenger does not depend on this.

@mscbot resolve does TI-Messenger still depend on this? We don't want to close MSCs without a future plan for direction if folks have been building on them.

2026-04-20 09:48 UTC, closed without merging