MSCXXXX: "busy" presence state
matrix-org/matrix-doc pull request #3026
Opened 2021-02-23 17:57 UTC by babolivier

[Rendered](https://github.com/matrix-org/matrix-doc/blob/babolivier/msc_presence_busy/proposals/xxxx-presence-busy.md)

2021-02-23 19:13 UTC, ShadowJonathan commented
I dont think this proposal is a good idea, the idea is sound (add a "Do not Disturb" status to matrix), but i think this should be implemented on a different level, because the current status "tag" sent via sync is mostly to signal what the *individual* client's online / afk / offline ("dont update state") state is.

How would this exactly change the behaviour of that in such fashion? If a server has 2 clients, one sending "online", another sending "unavailable", the server previously chooses the "best" status, i.e. the "online" state, and sees that as a canonical state.

But what if there are 3 clients with 3 states, "online", "unavailable", and "busy", which state is canonical? Is `busy` "above" `online`, does it mean that one client can keep sending "busy", which changes the presence every time it does a sync, with no way of manually turning off that client's status ("hey, please stop sending busy, i cant set myself to 'just online' again").

I think this clashes with what the idea of presence has always been, this reminds me of early discord, where early on there was only "online", "idle", and "offline", and no way to set your manual status. I think it's a much better idea to have a separate MSC which properly outlines a way for clients to "put" a "overriding" state, which is then visible to every client, and editable to every client. This would make that state canonical, and the server sends it across federation whenever one of the clients sends a sync with non-"offline" client-status.

2021-02-24 07:48 UTC, babolivier commented
Hi @ShadowJonathan, and thanks for your comment. For context, this is meant to be just a small change to the existing presence semantics we want to make to support work we're doing on improving the user experience around VoIP in Matrix (though as the MSC mentions this addition could serve other purposes). What you seem to have in mind is a greater overall of Matrix's presence feature, which is great, but should probably be its own MSC as it doesn't serve the same purpose or the same scope as this MSC.

(also can you use threads for reviews in the future please, to avoid clobbering up the timeline)

2021-02-25 13:04 UTC, dbkr approved these changes
Presence right now is fairly basic, and it's also unclear how it might interact with user profiles, ie. if some of it might move there (the status_msg in particular?) but it certainly seems like the semantics of 'busy' being something that will be auto-set by clients lend it to being in the presence enum. However presence ends up evolving, I think it having a busy state included allows for clients to set it automatically and server to derive a sensible value from the various automatic updates from clients.

2021-02-25 16:45 UTC, ShadowJonathan commented on proposals/3026-presence-busy.md
> +A new presence state is added, `busy`, which describes a state where the user is
I think it should be clarified this'd be added to `/client/r0/presence/{userId}/` apis, but not `set_presence` in `/sync`, due to that confusing the server when prioritising which presence to set, and making it impossible to "unset" it via any client whenever it's set on another client.

2021-02-25 16:51 UTC, babolivier commented on proposals/3026-presence-busy.md
> +A new presence state is added, `busy`, which describes a state where the user is
I'm not sure how setting presence via `/sync` is any different than via `/presence/...`. On top of that I think it'd be even more confusing for the presence enum to be different depending where you use it.

2021-02-25 18:28 UTC, ShadowJonathan commented on proposals/3026-presence-busy.md
> +A new presence state is added, `busy`, which describes a state where the user is
A client adding it via sync would be equivalent to it making a corresponding `PUT /presence` update, and if one client sets it to `busy`, and all other clients set it to `online`, then the server *has* to pick `busy` for the user's presence, and that user cannot "turn it off" from any other client as one client is broadcasting that `busy` presence. It has to be a "customizable" presence per user, or;
- the device will keep broadcasting the `busy` state via `set_presence`, causing a "ping-pong" behaviour if the server blindly picks the last-broadcasted presence
- the user cannot "turn off" their busy state at that point, as one specific client is broadcasting it, and the user has to hunt down that client to manually turn it off there
- there's no implicit coordination with the `set_presence` key between clients, historically, there were some implicit rules as what the server must do when it encountered it's latest announced `set_presence`s (`online` -> put online, all `unavailable` -> put unavailable, `offline` -> do nothing, no client announcing anything (or only `offline`) -> set offline), but with this, it is unclear what a server must do when it encounters multiple clients doing `online` with `set_presence`, and *one* client doing `busy` with `set_presence`, what does it need to do in that case?

2021-02-25 18:36 UTC, ShadowJonathan requested changes
I think the proposal as-is (on commit 69c273cfa67ee9f33288de9d7eca6af6f19ad4f2) will break the presence system as it works today, I think we need a more expansive presence MSC that can incorporate "extra" presence (such as `busy` proposed here), instead of the "cumulative" presence we have today (that this proposal will not fit into, for multiple reasons).

2021-03-01 10:49 UTC, babolivier commented on proposals/3026-presence-busy.md
> +A new presence state is added, `busy`, which describes a state where the user is
Resolving this thread as this has been resolved in #matrix-spec

2021-03-01 11:00 UTC, ShadowJonathan requested changes
As per discussion in `#matrix-spec`, I've realised that this spec *does* indeed try to do (what i called) "cumulative" presence, with 2 important points i think should be clarified in this document;

1. the `busy` presence is more exclusively seen as a "active temporary" state, i.e. it is not seen as analogous to the generic "do not disturb" status we see in many apps today, but it is meant as a marker to presence-receiving users that the user is currently *busy* in specifically-engaging activities such as calls. Important note then; this presence should immidiately be dropped when the user is seen as not actively engaging (not in a call) or not present (then `unavailable`/"idle" should be broadcasted.

2. With the previous, the `busy` state is seen as "above" any `online` state, making it so that only one client has to broadcast it to have it be the defacto "user presence" then, this is similar to `online` with `unavailable`, and `unavailable` with `offline`.

I think clarifying these two things explicitly in this document (if they arent already) would make this MSC non-conflicting with how matrix works today, assuming that clients honor point 1.

2021-03-12 10:53 UTC, erkinalp approved these changes

2021-03-12 18:11 UTC, turt2live approved these changes
Ideally we'd rework the entire presence system so that things like `unavailable` make sense, but this is probably the best we can do for now.

2021-03-15 19:19 UTC, anoadragon453 reviewed
Generally looks fine, just a couple of points really.

2021-03-15 19:19 UTC, anoadragon453 commented on proposals/3026-presence-busy.md
> +call.
Can't you just condition on whether the user is in a call/set to busy through some method?

I think a better reason might be that being idle on one client doesn't mean much if you're active on another.

2021-03-15 19:19 UTC, anoadragon453 commented on proposals/3026-presence-busy.md
> +to `unavailable`, which is the closest state semantically.
An alternative here is to have the client check the `/versions` endpoint for a given version/unstable feature flag. That way you don't end up with a server-side error in the logs.

2021-03-16 12:37 UTC, anoadragon453 commented on proposals/3026-presence-busy.md
> +call.
Sorry, this was a little confusing. I was asking about the recommendation for clients not to set a timer for transitioning to the `unavailable` state. Couldn't an implementation set a timer, but prevent moving into the `unavailable` state if the user is doing something that wouldn't involve interaction, like a call.

2021-03-16 14:13 UTC, babolivier commented on proposals/3026-presence-busy.md
> +call.
One issue I can see with that is that the client that wants to set the `unavailable` status might not be the one handling the action and it might be more difficult to figure out if another client has set it. What I had in mind is:

* the presence is set to busy by a client because of the user either specifically requested it or starting an action that implies a busy state (e.g. joining a call)
* while the presence is busy, the only ways for the user's presence to change is:
  * the user specifically asked their client not to be marked as busy anymore
  * the user stopped the action that implies a busy state if any (e.g. leaving a call)
  * the user hasn't synced for a while in which case the server can automatically set their presence to offline (Synapse seems to be doing that automatically if user hasn't synced for 30s, for context)

Let me know if this makes sense to you and, if so, if you think that bit of the MSC needs rephrasing.

2021-03-16 14:14 UTC, babolivier commented on proposals/3026-presence-busy.md
> +to `unavailable`, which is the closest state semantically.
Ah yeah that's probably a better way to do it, will amend.

2021-03-16 17:05 UTC, anoadragon453 commented on proposals/3026-presence-busy.md
> +call.
Things do seem to get a bit complicated when you bring multiple devices into the fold. Someone may be on a video call and then disappear into a tunnel, leaving them marked as busy until the user manually unsets it, possibly on another device.

From what's written in the MSC I had objections to the recommendation, but after thinking about multi-device complications I'm more dissuaded myself to try and come up with a workable solution. So I think mentioning the difficulties with juggling presence between multiple devices as another reason not to try and do things with timers might be good to include.

2021-03-16 17:09 UTC, babolivier commented on proposals/3026-presence-busy.md
> +call.
> Things do seem to get a bit complicated when you bring multiple devices into the fold. Someone may be on a video call and then disappear into a tunnel, leaving them marked as busy until the user manually unsets it, possibly on another device.

Presumably in this case the server will likely mark them as offline after they've stopped syncing for long enough.

> So I think mentioning the difficulties with juggling presence between multiple devices as another reason not to try and do things with timers might be good to include.

Yeah that sounds good, will amend.

2021-03-18 10:54 UTC, erkinalp approved these changes

2021-03-18 18:09 UTC, anoadragon453 approved these changes
This lgtm on the whole!

2021-03-18 18:09 UTC, anoadragon453 commented on proposals/3026-presence-busy.md
> +If a user's presence is set to `busy`, it is strongly recommended for
Ahaaa, I thought the timer recommendation applied globally, not only when the user's presence was set to busy. This makes more sense.

2022-07-08 14:21 UTC, chagai95 commented
We are testing this and it's working fine for us on productive systems, when will it be "merged"?

2022-07-08 17:21 UTC, anoadragon453 commented
@turt2live was the `needs-implementation` label added due to a lack of an open-source client implementation?

2022-07-08 18:24 UTC, turt2live commented
> @turt2live was the `needs-implementation` label added due to a lack of an open-source client implementation?

that seems believable, yes. Ideally we see the demand from clients for a feature like this to better prioritize it.

> We are testing this and it's working fine for us on productive systems, when will it be "merged"?

updates on MSCs are best asked in the [#sct-office:matrix.org](https://matrix.to/#/#sct-office:matrix.org) room so we can more easily see what people are concerned about.

2022-07-12 09:48 UTC, chagai95 commented
here is the open source implementation on Android:
https://github.com/vector-im/element-android/pull/6047

[add presence indicator busy and awa](https://github.com/vector-im/element-android/pull/6047)

2022-07-12 09:52 UTC, chagai95 commented
Here is web:
https://github.com/matrix-org/matrix-react-sdk/pull/8043

2022-07-12 15:15 UTC, turt2live commented
The author believes this is ready for FCP, and I don't see outstanding blockers for that happening - adding to the pile for the team to consider FCP.

2022-07-19 15:51 UTC, anoadragon453 approved these changes
This still lgtm.

@mscbot fcp merge

2022-07-19 15:52 UTC, anoadragon453 commented
@mscbot fcp merge

2022-07-19 21:51 UTC, uhoreg commented on proposals/3026-presence-busy.md
> +A new presence state is added, `busy`, which describes a state where the user is
While I don't have an objection to adding `busy` in particular, this raises the larger question of what presence states we should have.  Is it sufficient to just add `busy`, or do should we be adding more?  For example, XMPP defines 6 states ([4 states with names](https://xmpp.org/rfcs/rfc3921.html#rfc.section.2.2.2.1), plus a non-specific "online" state when the `show` element is not present, and a state where the [client is offline](https://xmpp.org/rfcs/rfc3921.html#rfc.section.2.2.1).)  Are we eventually going to want equivalents for XMPP's other states that we're missing?  How do we decide where to draw the line?

FWIW, I think that adding a 4th `busy` state is probably OK.  Adding much more than that would be of questionable value.

2022-07-19 21:51 UTC, uhoreg commented on proposals/3026-presence-busy.md
> +
The spec says that the server aggregates presence data across devices, which I assume means that, e.g.  if a user has one device that's `online` and another that's `offline`, then the user is marked as `online`.  How does `busy` fit into this?  If a user has a device that's `online`, and one that's `busy`, what `m.presence` event should be sent to others?  I think that my expectation would be that `busy` would take precedence over `online`.

2022-07-19 21:52 UTC, uhoreg commented on proposals/3026-presence-busy.md
> +The current specification for presence in Matrix describes three states:
```suggestion
The current specification for [presence](https://spec.matrix.org/v1.3/client-server-api/#presence) in Matrix describes three states:
```

2022-07-19 23:02 UTC, chagai95 commented on proposals/3026-presence-busy.md
> +
I'm pretty sure it does in the current implementation. There seems to be one api end point for presence that was overlooked so we disabled it on our forks but when  the online state comes through a sync it is ignored by synapse - https://github.com/matrix-org/synapse/pull/12213

2022-08-16 15:58 UTC, babolivier commented
Thanks for the comments, I'll try to make some time to address them soon.

2022-08-16 16:04 UTC, richvdh commented on proposals/3026-presence-busy.md
> +A new presence state is added, `busy`, which describes a state where the user is
Yeah, this was basically my feeling too. How is `busy` different from `unavailable`? Should we use status messages instead?

2022-09-01 20:55 UTC, turt2live commented
After [talking to the author](https://matrix.to/#/!ewdjhNcPcEmYNKzlWp:t2l.io/$bNr1J7AWlHwkRoWqi4udvOPkX6K4Q3m3zSRBtgf76sk?via=matrix.org&via=element.io&via=beeper.com), this isn't the author's current priority. It's hard to make progress on this from the SCT side in this state, so removing from FCP for now - we can always restart FCP when someone is able to pick this up :)

@mscbot fcp cancel

2022-11-07 15:47 UTC, anoadragon453 commented on proposals/3026-presence-busy.md
> +`online` state). This is because there are some valid use cases for the user not
Even though it's obvious, we may also want to explicitly state that homeserver's shouldn't update a user's presence state to "online" if activity is detected.

2023-03-03 18:58 UTC, turt2live commented on proposals/3026-presence-busy.md
> +semantically.
This sort of backwards compatibility would go in the unstable prefix section - clients (now) can use spec versions to detect support otherwise.

2023-08-08 17:38 UTC, clokep commented on proposals/3026-presence-busy.md
> +multiple devices.
Synapse (at least) also transitions users to `offline` in some situations (e.g. if the user stops syncing and enough time has passed). This still seems somewhat valid (e.g. if a device just disappears forever without transition *off* `busy` then you at some point want to transition the account to something else).

2023-08-15 19:39 UTC, clokep commented on proposals/3026-presence-busy.md
> +joins a call or a Jitsi group call, etc..
https://github.com/matrix-org/synapse/pull/12213 asserts that only the `/presence` API can be used to set busy and that subsequent `/sync` calls after a user is set to `busy` should not revert a user to `online` automatically. I don't think this makes sense and it would be a lot clearer for a client to sync with `set_presence=busy` if it is *still* busy. This would give `/sync?set_presence=?` and `/presence` the same "power" and not different behavior.

I don't think this MSC could be merged without either documenting the Synapse implementation or a clarification of the MSC.

2023-08-16 08:37 UTC, dbkr commented on proposals/3026-presence-busy.md
> +joins a call or a Jitsi group call, etc..
Yeah, I think this probably does make sense - my basic understanding of it was that the presence API is the 'user level' presence and the sync is the 'device level' presence, so previously the user is busy rather than a device, but this would just be switching to say that a device is busy (which perhaps makes more sense: the user is on a call on a specific device).

2026-07-20 13:40 UTC, lveneris commented
Hi @babolivier,

If you'd be open to the idea, we notice this hasn't received attention in quite some time, and we'd like to adopt this proposal under the Presence v2 initiative (see #4495) to carry it over the finish line. Please do let me know your thoughts when you have the time. I believe this added fidelity is instrumental to getting presence towards where it needs to be.

2026-07-20 19:55 UTC, babolivier commented
This MSC was written up in the context of a commercial contract between my then employer Element and another company (which scope and timeframe didn't really account for stabilising the feature). I am no longer employed by Element as of December 2022 (nor a stakeholder in this specific feature), and do not currently have enough time nor interest to pursue Matrix spec contributions. I realise I haven't formally abandoned this MSC (these things end up accumulating), which I'm now doing with this comment.

@lveneris Apologies, I understand this probably isn't the response you were looking for.

2026-07-20 20:15 UTC, turt2live commented
(abandoned MSCs typically get closed - we'll do that now)

2026-07-20 20:15 UTC, closed without merging