MSC3067: Prevent/remove legacy groups from being in the spec
matrix-org/matrix-doc pull request #3067
Opened 2021-03-18 04:29 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/no-groups/proposals/3067-remove-legacy-groups.md)

2021-03-18 08:56 UTC, erkinalp requested changes

2021-03-18 08:56 UTC, erkinalp commented on proposals/3067-remove-legacy-groups.md
> +
```suggestion

## Alternatives considered

Making old-style groups explicitly ill-formed.

```

2021-03-18 11:12 UTC, richvdh commented on proposals/3067-remove-legacy-groups.md
> +structure called a "group" would not be in the spec.
I'm sorry, we seem to have ended up at cross-purposes somewhat.

When we discussed the need for this MSC on MSC1772, I thought you were talking about wanting to remove stuff from the spec. As far as I can see, the only concrete proposal in that direction is the removal of group IDs from the spec, whereas the rest of it covers changes that we are *not* going to make to the spec.  I don't feel that we need an MSC for a decision to not add stuff, and if that's what you thought I wanted, I now understand your reluctance in the MSC1772 thread.

I think all this MSC *needs* to say is "remove the group IDs from the appendix" (with maybe a side-note about the unspecced stuff). On the other hand, now that you've written it, I'm happy if you'd rather keep it as-is. 

Or, if all this fuss is really just about the group IDs, I don't mind sticking that in MSC1772. From what you said over there it sounded like a bigger concern.

Sorry if I caused you wasted work.

2021-03-18 13:50 UTC, turt2live commented on proposals/3067-remove-legacy-groups.md
> +structure called a "group" would not be in the spec.
I honestly thought there was more than just the group IDs in the spec, but it turned out to be the only thing. 

If we don't need an msc to exclude groups, I'd generally prefer that spaces take up the removal of the IDs, otherwise I don't mind this MSC being the chance Groups never had to be formally rejected

2021-03-18 13:51 UTC, turt2live commented on proposals/3067-remove-legacy-groups.md
> +
This suggestion needs a whole lot more words to make sense.

2021-03-18 13:55 UTC, deepbluev7 commented on proposals/3067-remove-legacy-groups.md
> +already made it into the spec documents. This proposal removes that specification.
Is the intention to not reuse the current group identifiers for spaces? I can't find anything in that regard, but it may have just gotten lost in the MSC1772 comments. I guess my question is, will the `+` sigil be reintroduced as a spaces identifier in the future, or will they just be addressed by room aliases or is there no decision/proposal made for that yet?

2021-03-18 13:56 UTC, erkinalp commented on proposals/3067-remove-legacy-groups.md
> +
Clarified on the strategy on how to make them ill-formed.

2021-03-18 13:58 UTC, erkinalp commented on proposals/3067-remove-legacy-groups.md
> +already made it into the spec documents. This proposal removes that specification.
Spaces are rooms of rooms, you do not need another sigil to identify spaces.

2021-03-18 13:58 UTC, erkinalp approved these changes

2021-03-18 14:05 UTC, deepbluev7 commented on proposals/3067-remove-legacy-groups.md
> +already made it into the spec documents. This proposal removes that specification.
While it is true, that adding a sigil for each room type would get messy quickly, I would appreciate knowing, what the link refers to, that I am clicking on. I don't really want to join 20 rooms, when clicking on an alias, I usually expect to join 1 room. But spaces allow joining multiple rooms by just joining the space, which may be surprising. I guess this should be solved by peeking though instead of the alias grammar, since currently nothing prevents you from joining a space by a room alias? Anyway, thank you for the explanation, that wasn't clear to me from reading the proposal!

2021-05-01 01:25 UTC, turt2live commented
The spaces proposal covers what this MSC does quite well, so considering obsolete.

2021-05-01 01:25 UTC, closed without merging