MSC3082: Restricting room membership based on space membership
matrix-org/matrix-doc pull request #3083
Opened 2021-03-31 15:32 UTC by clokep

2021-04-14 17:44 UTC, clokep commented
I pushed a version of this which is experimentally implemented in Synapse and Element Android.

2021-04-15 13:03 UTC, Cadair commented on proposals/3083-restricted-rooms.md
> +server could lie about the space membership and add an `@evil_user:example.org`.
This should be removed as it's no longer relevant?

2021-04-15 13:21 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +to just introduce a a new join rule - `restricted` - as described above.
This is essentially the result of this conversation: https://github.com/matrix-org/matrix-doc/pull/2962/#discussion_r583567946

2021-04-20 12:58 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +server could lie about the space membership and add an `@evil_user:example.org`.
Thanks! I moved this down into the future considerations bit that I hadn't yet filled out.

2021-04-28 12:24 UTC, clokep commented
I should mention that this has an experimental implementation in Synapse.

2021-05-07 23:34 UTC, MadLittleMods commented on proposals/3083-restricted-rooms.md
> +  user leaves SpaceB? Are they exempt from the kick?
I feel like this section is missing some of the good details that used to be part of the original Spaces spec doc, https://github.com/matrix-org/matrix-doc/blob/69897584e1365b8d7c3e57190d064edca55cce9f/proposals/1772-groups-as-rooms.md#kicking-users-out-when-they-leave-the-allowed-space

> (XXX: should users in a space be kicked when that space is removed from the allow list? We think not, by analogy with what happens when you switch the join rules from public to invite.)

Relates to my previous comment, "This part feels weird to me. `m.room.join_rules` seems like it should govern joins, not existing room membership." (https://github.com/matrix-org/matrix-doc/pull/1772#discussion_r553702595).

Maybe we need a different membership value, `m.room.member` -> `membership: "allowed"` which would inherit the permissions from the `m.room.join_rules`. If the user leaves a space or the `m.room.join_rules` change to not include them, they are kicked.

2021-05-10 17:11 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +  user leaves SpaceB? Are they exempt from the kick?
As part of the "future" extensions bit I'm not sure how fleshed out it needs to be? I'd expect a future MSC to make those arguments.

2021-05-12 14:58 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +  user leaves SpaceB? Are they exempt from the kick?
I included some of the above and re-wrote this section to be a bit less prescriptive.

2021-05-12 17:27 UTC, MadLittleMods commented on proposals/3083-restricted-rooms.md
> +  user leaves SpaceB? Are they exempt from the kick?
Looks great @clokep 😃 Thanks for including it!

2021-05-28 13:14 UTC, timokoesters commented on proposals/3083-restricted-rooms.md
> +the room are trusted not to allow invalid users to join.<sup id="a3">[3](#f3)</sup>
My proposal to solve this:

Only servers listed in 'via' are allowed to add the new user to the room. You can think of the servers under 'via' as the trusted servers.

This can be enforced by checking if the member event of the new user contains a valid signature from one of the 'via' servers.

2021-05-29 14:47 UTC, kevincox commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
Isn't this case identical to `invite`? Why not extend the invite mechanism instead of adding a new type. It seems that adding new types will cause issues in the future as we want to mix? For example what if we want to allow knocking in a room that allows space-based invites? I think we should put an end to this and freeze this list at just `public` and `invite` and add other options for allowing joining by knocks, space member ship and similar. This essentially moves the logic to default public or private with extra rules that allow joining.

2021-06-01 12:36 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
For context, this was discussed a bit https://github.com/matrix-org/matrix-doc/pull/2962/#discussion_r583567946 where the original conversation occurred (unfortunately on a different MSC), I'll copy richvdh's thoughts here though since GitHub makes it hard to find that thread:

> I was struggling to remember why we decided it was better to start with `join_rule: public` and lock it down, rather than `join_rule: invite` and open it up.
>
>I think the answer amounts to: from the perspective of the [auth rules](https://matrix.org/docs/spec/rooms/v1#authorization-rules), the expected behaviour is the same as that of `join_rule: public`, because the `allow` restrictions cannot be enforced post-hoc. If we simply used `invite` here, we would have to weaken the auth rules so that you would no longer need to hold an invite to join the room, which I am reluctant to do.
>
>So, from the auth rules' point of view, `public` makes more sense.
>
> However, as well as joepie91's point about failing safely and making redactions work right, I'm a bit worried that this is going to be very confusing for everybody.
>
> I wonder if, for clarity as much as anything else, we should introduce a different `join_rule` - say, `restricted` - to reflect the fact that what we have is a cross between `invite` and `public`? in this world:
> * `public`: anyone can join, subject to `ban` and `server_acls`, as today
> * `invite`: only people with membership `invite` can join, as today
> * `restricted`: the same as `public` from the perspective of the auth rules, but with the additional caveat that servers are expected to check the `allow` rules before generating a `join` event (whether for a local or a remote user).
>
> Since we're talking about needing a new room version for this anyway, it seems like a reasonable thing to do?

In summary, the idea behind using a new join rule was:
* We didn't want to base it on `invite` since it weakens the auth rules for invite.
* Using a new join rule (and not re-using `public`) brings clarity that this is a combination of `invite` and `public` join rules.

> I think we should put an end to this and freeze this list at just `public` and `invite` and add other options for allowing joining by knocks, space member ship and similar. 

Note that knocking was already accepted into the spec, so this isn't the place to discuss that. I also believe that "freezing" something like join rules is a somewhat unrelated discussion to this.

I'm not sure how using other fields vs. the join rule itself moves the logic. Are you suggesting is that the join rule field should only govern the auth rules and additional fields should be used to modify that? I'm unsure if that's clearer than using a new join rule in this case.

2021-06-01 12:52 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +joining spurious users into your rooms, then:
> This has several benefits;
>
> * you can assert, at the time of receiving and in the future, that the user who just joined, at the time of joining, had membership in the other room (as the server can resolve the membership state for the referenced event ID)
> * the server can reject the join (same way as when rejecting an invalid signature) by asserting that the membership in the other room doesn't exist

This makes the assumption that every homeserver in the room has access to the spaces via which users can join from. This might not be true, consider the following:

* A space exists which has the staff of a Acme Corp as members.
* Rooms exist under this space with `restricted` join rules pointing back to the space, each room represents another company that Acme Corp does business with. In this example, consider their relationship with Ajax Corp.
* Users from Ajax Corp are invited to their discussion room with Acme Corp, so you end up with a (`#ajax_support:acme.corp`) which anyone who is a member of `#staff:acme.corp` can join, but also users who were specifically invited (e.g. `@donald:ajax.corp`).
* Acme Corp gets a new employee (`@wile_e:acme.corp`) who joins the room.
* The `ajax.corp` homeserver gets the event, but is unable to verify how they joined since they don't have access to `#staff:acme.corp`.

The opposite is also true, you might want to set it so any user in `#staff:acme.corp` or `#staff:ajax.corp` can join, but they cannot verify each other's membership in that space.

Cross referencing https://github.com/matrix-org/matrix-doc/pull/3083/files#r641539299.

2021-06-02 19:26 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +joining spurious users into your rooms, then:
I'm going to resolve this for now since the comment is a bit confusing (as discussed in #matrix-spec:matrix.org). If you can clarify / simplify the concerns, please feel free to reply!

2021-06-02 19:27 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +the room are trusted not to allow invalid users to join.<sup id="a3">[3](#f3)</sup>
Yeah, I think that would add a bit of security to this, I'm unsure if we do any checking of signatures like that in other places though. I'll have to investigate a bit more.

2021-06-02 22:55 UTC, kevincox commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
I see. I appreciate the reasoning behind that.

> Note that knocking was already accepted into the spec

I did not realize that that had happened 🎉 in that case how would I create a room where anyone can knock, but people in a space can join (without knocking).

---

On a similar note on reducing explosion of `join_rule` types here should we add a `type` field to `allow` such that we can add other ways that someone can join a room without creating another new combination?

2021-06-03 13:29 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
> I see. I appreciate the reasoning behind that.

No problem. :)

> > Note that knocking was already accepted into the spec
> 
> I did not realize that that had happened 🎉 in that case how would I create a room where anyone can knock, but people in a space can join (without knocking).

That would not be possible with this proposal.

> On a similar note on reducing explosion of `join_rule` types here

Please can we avoid using words like "explosion", with this proposal there would only be 4 join rules (`public`, `invite`, `knock`, `restricted`). This doesn't seem like a massive amount and takes away from the rest of the point you're making.

> should we add a `type` field to `allow` such that we can add other ways that someone can join a room without creating another new combination?

What would this type be used for? Without a concrete use-case I do not want to make this more complicated.

2021-06-04 12:53 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +to just introduce a a new join rule - `restricted` - as described above.
I've expanded this a bit so I'm unsure if this comment is useful anymore -- I'm going to resolve this, also see the thread below: https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r641946633

2021-06-04 12:59 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `via`: A list of servers which may be used to peek for membership of the space.
Without depending on MSC2444 (see [below](https://github.com/matrix-org/matrix-doc/blob/clokep/restricted-rooms/proposals/3083-restricted-rooms.md#checking-space-membership-over-federation)) I wonder if we should just remove the `via`?

2021-06-04 23:29 UTC, kevincox commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
> That would not be possible with this proposal.

This seems like something that we should address. 

> Please can we avoid using words like "explosion"

I'm sorry if that seems extreme. But the problem I am referring to is that it looks like we are entering a combinatorial explosion. While this may propose only one more room it seems like it is already clear that we will need one more for `knock-restricted`. If we add a new method such as `password` we will now need `password`, `restricted-password`, `knock-restricted-password`, `knock-restricted`.

My point is that while it is unfortunate that I didn't see this problem with the knock MSC it seems clear to me that we can't continue down this path.

> What would this type be used for?

I'm not claiming that these are the best proposals but some thoughts:

- password-based joins.
- Joins authorized by OpenID Connect.

I'm quite certain that we will have additional ways to join a room in the future.

2021-06-08 16:09 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +the room are trusted not to allow invalid users to join.<sup id="a3">[3](#f3)</sup>
consider that there are two users in a room, `@alice:server1` and `@bob:server2`. Only `server1` is in the `via` property. Now `@charlie:server2` wants to join.

According to this change, that join would have to go via `server1` even though `server2` is already in the room. This is an increase in centralisation I'm not entirely happy with.

As the footnote says: it's not obvious that we're really making things any worse than the current state of play with invite-only rooms. I'm not sure this is a tradeoff worth making.

2021-06-08 16:12 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +Any entries in the list which do not match the expected format are ignored.
maybe we should reject all joins if we don't understand the entries, on the basis that it's presumably a new type of restriction which we don't yet implement?

(Although new restriction types should come with a new room version, so it's pretty moot)

2021-06-08 16:22 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
new restrictions would be implemented with modifications to the `allow` dictionary. I don't think we need to spec those now, and I think that it's overly dramatic to imagine that it will result in `restricted-password` etc.

2021-06-08 16:25 UTC, richvdh commented
I think this is basically ready to go.

@mscbot fcp merge

2021-06-08 17:26 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +Any entries in the list which do not match the expected format are ignored.
I think this is based on [similar text in MSC1772](https://github.com/matrix-org/matrix-doc/blob/matthew/msc1772/proposals/1772-groups-as-rooms.md#relationship-between-rooms-and-spaces):

> Children where `via` is not present or invalid (not an array) are ignored.

But requiring the entire event to be valid seems like a reasonable change to me.

2021-06-08 17:38 UTC, uhoreg commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
What happens in the room in question is not a space?  Could we change it so that it can be any arbitrary room, or does it need to be a space?

2021-06-08 17:38 UTC, uhoreg commented on proposals/3083-restricted-rooms.md
> +A new `join_rule` (`restricted`) will be used to reflect a cross between `invite`
If we just say that an `allow` property allows users from the space to join, then we can apply it to other join rules too.  e.g. if the join rule is `invite` and it has the `allow` property, then it works as described in this MSC.  If the join rule is `knock` and it has the `allow` property, then members of the space can join, and non-members can knock.

2021-06-08 17:53 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
The implementation doesn't currently check this, but we should be specific here. Not restricting it to spaces seems more general at a protocol level (without any downsides that I can see). Clients could decide to only show the UI for spaces?

2021-06-08 17:57 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +A new `join_rule` (`restricted`) will be used to reflect a cross between `invite`
There's some conversation about this around https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r641946633

2021-06-09 11:49 UTC, timokoesters commented on proposals/3083-restricted-rooms.md
> +the room are trusted not to allow invalid users to join.<sup id="a3">[3](#f3)</sup>
I think increased security is the primary reason for this feature to exist in the first place (e.g. companies use it to limit their rooms to members of their space). I think people who want to use this feature, want centralization anyway.

If we do it like the MSC says, companies can't trust other homeservers, so they will probably "Don't let evil servers in your room in the first place" by disabling federation in these rooms entirely.

2021-06-09 17:02 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
Do you have thoughts on whether we should require it to be a space or would membership in the target room ID be enough?

2021-06-09 21:59 UTC, kevincox commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
I like the idea that I think you are proposing but `allow` isn't a dictionary.

I think we would either need to:

1. Make `allow` a dictionary and put the current list in `allow.space_members`.
2. Add `allow[*].type` to be able to tell which items are "space member" rules and which are "password" or "knock" rules.

I think I prefer 2. It makes it clear that people matching any of these rules can join.

(Aside: knock is probably slightly different because we may want to restrict who can knock. (It is a separate ACL rather than a part of the join ACL) but that will be dealt with in the MSC that actually adds support for knocking in `restricted` rooms.)

2021-06-09 22:02 UTC, kevincox commented
I consider https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r641946633 blocking. I think the [last comment](https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r648713108) is a viable solution. But I don't think this can be accepted until we have a plan for how the auth rules can be extended.

2021-06-09 22:06 UTC, uhoreg commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
I don't think we lose anything by making it possible to set it to any room, space or not.  It could possibly open up more use cases.  But, as you say, it may make sense for clients to limit what rooms they show when allowing users to select which room(s) to use.

2021-06-09 22:34 UTC, kevincox commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
I can imagine something simple like "breakout rooms" for a chat. Maybe it is going off topic but some people are interested, so drop the link to the new room and allow anyone from the previous chat to join. This could *probably* be done just by making a "secret" but public room but this is safer. Clients could even add an easy button to do this if they wanted. I agree that clients may want to filter spaces only, or prefer spaces, for the general case.

2021-06-10 13:37 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
I can clarify the text around this, do we think the field name should be changed?

2021-06-10 15:04 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
I guess having a `type` field in the dictionaries in `allow` list would make things cleaner when we want to add other rule types in future. for now that would always be `"type": "room-membership"` or something. @clokep wdyt?

2021-06-10 15:07 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +Any entries in the list which do not match the expected format are ignored.
wait, I think I'm being stupid.

the `allow` list is disjunctive - if *any* of the entries are satisfied, we allow the join; if the list ends up empty, we reject the join.

So, if we ignore entries we do not understand, we are failing in the safe direction - ie, making it *more* secure.

In short, the current text is right imho.

2021-06-10 15:17 UTC, uhoreg commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
Yeah, if it's going to be an arbitrary room, then the field name should match that somehow.

2021-06-10 15:19 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
Having a `type` field there seems fine. An older version of this actually also allowed strings in the `allow` list to directly allow users by MXID, so I think that would make sense.

2021-06-10 15:21 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +Any entries in the list which do not match the expected format are ignored.
Yeah, it fails to ignoring invalid entries. I'll try to make that a bit clearer in the text.

2021-06-10 15:21 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
I think just changing `space` -> `room` will make the most sense. I'll make this change.

2021-06-10 16:16 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `space`: The room ID of the space to check the membership of.
I've made this change.

2021-06-10 16:17 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +following keys, or a string representing the MXID of the user exempted:
I've added a `type` field, hopefully that allows for better extensibilitiy.

> Aside: knock is probably slightly different because we may want to restrict who can knock.

I don't know why you wouldn't just allow users in that case (as defined in this MSC), but yeah I don't plan to adapt this to knocking in this MSC.

2021-06-11 12:32 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +                "type": "room-membership",
I don't think all values inside of these need to be `m.` namespaced, but I'm unsure. (E.g. the join rules don't follow this, but I suppose the `type` is something that people could reasonably want custom ones of.)

Anyone have thoughts on when these need to be namespaced vs. just values?

2021-06-14 23:40 UTC, kevincox commented on proposals/3083-restricted-rooms.md
> +                "type": "room-membership",
My understanding is that they should be so that people can add their own and create temporary names for new MSCs. How will people add custom rules or experiment with new standards if there is no namespace reserved for this?

2021-06-15 11:09 UTC, t3chguy commented on proposals/3083-restricted-rooms.md
> +  `server_acls`. See [MSC2403](https://github.com/matrix-org/matrix-doc/pull/2403).
The way this reads seems to imply `ban` and `server_acls` don't apply to `invite` which I don't think is the intent

2021-06-15 12:20 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +  `server_acls`. See [MSC2403](https://github.com/matrix-org/matrix-doc/pull/2403).
Thanks, I'll clarify it! I should probably add a warning saying this isn't meant to be a replacement for reading the spec too.

2021-06-15 12:27 UTC, neilalexander reviewed
I have some very serious concerns that this will fundamentally change the nature of event auth and it isn't clear that these checks will be repeatable by other servers.

2021-06-15 12:27 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +* `restricted`: the same as `public` from the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
This makes me *incredibly* uneasy as it is changing the fundamental nature of the event auth model, which today relies on *only* state from within the room (i.e. the auth chain).

By adding a dependency on shared state from outside of the room, we are creating a number of new problems about how other servers in the room should auth these events:

* Does each server really need to go and query the listed rooms for memberships?
* What happens if they can't — is this suggesting that we should really just accept the join (because it is otherwise `public`)?
* What happens if a server receives the event late (delayed federation or backfill, for example) and the membership of the remote rooms have since changed — how do we express that we care about the membership at a specific point in time when we don't have a means of knowing any of the event IDs in the remote rooms (or history visibility may prevent us from seeing them)?

2021-06-15 12:27 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
This is an unreliable premise. What if servers were already in the room that turned evil later?

2021-06-15 12:27 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +This MSC recommends rejecting the join in this case and allowing the requesting
This is contradictory to above, where we suggest that the join rule otherwise acts as `public`.

2021-06-15 12:27 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +when you switch the join rules from public to invite. Join rules currently govern
It's worth noting here that there are all sorts of cases where a server may need to auth these joins *later*, e.g. because they were delayed over federation, backfilled or pulled in as an auth event for another future event. This should be a pure operation and shouldn't yield different results if ran at different times — we can't make this guarantee if we depend on mutable external state.

2021-06-15 15:32 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +                "type": "room-membership",
In general, the word `type` indicates that the value should be namespaced. The MSC doesn't need to define how to work with custom types (see also: encryption), but should theoretically support the ability for experimentation down the line.

We've slowly been using more and more namespaced values as it helps with MSCs down the line. Things like join rules are harder to distinguish testing from reality for instance, so we'd have ideally made them namespaced enums long ago, but didn't and here we are.

2021-06-15 15:32 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +                "type": "room-membership",
also underscores are preferred regardless.

2021-06-15 15:55 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +* `restricted`: the same as `public` from the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
I think there's a misunderstanding here. I think I see your concern, and we're very deliberately designing this to *avoid* needing to do cross-room auth operations.

The first point is that from the point of view of the *auth rules*, `restricted` is identical to `public`. That is to say, the only change to `https://spec.matrix.org/unstable/rooms/v1/#authorization-rules` is that item 5.5 changes to:

> If the `join_rule` is `public` _or `restricted`_, allow.

Indeed, when we were first drafting this MSC, we considered not bothering with a new `join_rules` state and just using `allow` (see the first entry under "Alternatives", below), but we decided on balance that was more confusing.

The "additional caveat" ("servers must check the `allow` rules") does *not* apply during event auth - the words "before *generating* a `join` event" were carefully chosen. In other words, those checks are made on the server handling the `/_matrix/client/.../join` request, and/or the `/_matrix/federation/v1/make_join` request, as appropriate, *and not thereafter*.

@clokep I wonder if we can come up with a way of rephrasing this sentence to make it clearer.

2021-06-15 15:57 UTC, timokoesters commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
Also see https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r641539299

2021-06-15 16:03 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
well, let's consider the existing situation. If we wanted to have a room restricted to certain users, we would have an invite-only room, with the expectation that only people who were meant to be there got an invite. We might well have users on multiple servers in that room.

Now suppose one of the servers in the invite-only room turns evil. It can just start dishing out invites to all its shady mates, who can now join with impunity.

So unless I'm missing something, I don't think there is a material difference for servers to be evil. It's a valid concern, but I don't think it's necessary to solve it for this MSC.

2021-06-15 16:09 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +This MSC recommends rejecting the join in this case and allowing the requesting
(That said: this sentence is a bit confusing. We're in the 'Future extensions' section so I assume this isn't a normative part of the MSC, but "This MSC recommends" makes it sound like implementations are expected to carry out this behaviour from day one.)

```suggestion
A future solution to this might be to reject the join in this case and allow the requesting
```

2021-06-15 16:10 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +when you switch the join rules from public to invite. Join rules currently govern
absolutely; this constraint is one of the things that makes this whole area harder to solve than it seems like it should be at first brush.

2021-06-15 16:19 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +                "type": "room-membership",
I think a TL;DR of @turt2live's comments is that [MSC2758](https://github.com/matrix-org/matrix-doc/pull/2758)-style identifiers would be preferred here. He's probably right.

2021-06-15 16:33 UTC, ShadowJonathan commented on proposals/3083-restricted-rooms.md
> +* `restricted`: the same as `public` from the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
What makes this different than than `public` then, genuinely?

What i see here is an emphasis on the local server doing this check, but in my opinion, in matrix, this is the equivalent of front-end validation.

2021-06-15 17:05 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +This MSC recommends rejecting the join in this case and allowing the requesting
This sentence was meant to be a summary of previous behavior already discussed in the MSC (about the `/make_join` case, yes).

2021-06-15 17:19 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `restricted`: the same as `public` from the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
This bit is meant to be a summary, not a full description of what the `restricted` join rule does. Is the section above not clear? It seems the section above doesn't explicitly say that the auth rules should be treated as `public`, but besides that it seems to pretty clearly say that the `allow` rules are checked during `/join` / `/make_join` / `/send_join` requests.

2021-06-15 17:29 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +  `server_acls`. See [MSC2403](https://github.com/matrix-org/matrix-doc/pull/2403).
I've added the additional bits, I think it is all correct now!

2021-06-15 17:29 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +                "type": "room-membership",
I've updated this to be `m.room_membership`.

2021-06-15 17:30 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `restricted`: the same as `public` from the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
I've added a bit more to the section above this that describes the auth rules for `restricted rooms`.

2021-06-15 17:30 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +This MSC recommends rejecting the join in this case and allowing the requesting
I've attempted to clarify that this section is only talking about `/make_join` / `/send_join`, not about receiving events over federation.

2021-06-15 17:31 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +when you switch the join rules from public to invite. Join rules currently govern
I think in the current form this *is* true. A server does not need access to any other state in order to auth those joins later.

2021-06-15 18:38 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
I attempted to expand this section a bit in 39b9a9d582cb8eb9ef9295861202dc676acdd66d to at least ensure these concerns made it into the MSC.

2021-06-15 18:47 UTC, timokoesters commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
@richvdh In your example the server of the invite-only room that turns evil needs to have enough power to invite other users, right? That's not the case with this MSC afaict.

2021-06-15 19:26 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
yeees, that's true, though I'd be very surprised if people were currently routinely doing the manipulation needed with PLs to restrict invite power. If that is a concern, then I guess that brings us back to your suggestion linked to above, where we have a list of servers who are allowed to make join events. My instinct is to omit that for now, and consider it for a future extension.

Even then, my feeling is that once you've got an evil server in your invite-only room, you're basically in a mess. Even if the evil server can't generate join events, they can still copy all the content in the room to people who shouldn't be able to see it, etc.

2021-06-15 19:35 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
Note that matrix-org/synapse#6834 increased the default invite power level to 50. So in new-ish rooms most users won't have the PLs needed to issue invites.

2021-06-16 02:29 UTC, turt2live requested changes

2021-06-16 02:29 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
from reading into more of the MSC, it sounds like this is a false assumption. Can we get words to say something along the lines of whether this is invite-only please?

2021-06-16 02:29 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
Considering the usecases for Spaces, particularly private ones, it's not infeasible for a server to become evil overnight. Private spaces are likely to be used by teams and companies, which means we really should have security by default for when those teams want to remove an employee from their organization, or when employees become malicious prior to leaving the company on their own. Plus, convincing your previous coworker to become evil and quietly bring you in is pretty easy in large enough teams.

I really don't think this is a reasonable expectation to put on room admins to keep in mind.

2021-06-16 02:29 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +   by letting members in other rooms dictate who's allowed into your room.
can this be rephrased? It basically reads as "don't use this feature if you don't like it", which does not leave behind a comforting feeling for this MSC...

2021-06-16 02:30 UTC, turt2live commented
@mscbot resolve Neil's review needs attention: https://github.com/matrix-org/matrix-doc/pull/3083#pullrequestreview-683929716

@mscbot concern The security of the room does not match up to the `restricted` keyword.

2021-06-16 05:25 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
>Plus, convincing your previous coworker to become evil

In this example, is the former coworker still employed (and hence a source of leaks even if not invites) or not (in which case they should be kicked from the room and are therefore irrelevant here)?

2021-06-16 05:44 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
That's a bit of an aside to my point, but yes: they'd still be employed. The protocol shouldn't be making it easier to shuffle things out of the room that were never meant to leave.

2021-06-16 09:59 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
I don't really understand the question. 

Non-space-members can receive an explicit invite to a restricted room and join the room that way, as an alternative to complying with the restrictions.

2021-06-16 10:30 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
> Now suppose one of the servers in the invite-only room turns evil. It can just start dishing out invites to all its shady mates, who can now join with impunity.

To an extent this is true, yes, but the invite PL would at least stop other servers from accepting invites from members who are not empowered to send them. I wonder if that would be enough to limit damage, even if it forks the room.

I suppose what I am envisaging is more some kind of split-brain or collusion where either servers disagree on the join rule for some reason (think federation delay or state reset) or a resident server in the room just turns evil and decides not to perform the checks on `/make_join` and `/send_join`. Someone could then join via that server and then all other servers just have to deal with it and accept the join. 

I assume there are knock-on effects here for encrypted rooms? If this actually happened in an E2EE room, we would presumably just start sharing keys with the newly joined server so we can't even depend on E2EE to prevent leaks?

2021-06-16 10:30 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +* `restricted`: the same as `public` from the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
I'm much happier with the clarification that this only takes place on `/join`, `/make_join` and `/send_join` and doesn't fundamentally change the closed-loop nature of the event auth.

2021-06-16 10:32 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +This MSC recommends rejecting the join in this case and allowing the requesting
I think I'm happy enough to resolve this conversation on the basis that it's the same clarification from above.

2021-06-16 11:49 UTC, ShadowJonathan commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
Yes, because to the clients, it'd look like a legitimate join.

2021-06-16 13:49 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
The spec bases itself off a concept of rooms being invite only or not for simplicity. Just looking for this MSC to pick either invite only or not to automatically pull in all the behaviors

2021-06-16 17:25 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
Having thought a bit more about this and discussing with @richvdh I think we'll want to tighten this up a bit. The only reasonable solution I have is @timokoesters of requiring the joins to be signed by one of the servers listed in the `via` (meaning that they essentially become authorization servers). This has a few outcomes:

1. Increased centralization due to servers potentially being unable to join additional users to the room even when already in the room. It likely makes sense in this case. (E.g. if you have a company space you probably only want your company's server to be able to approve joins.)
2. This makes the edge case of attempting to join via a server which doesn't know if you're in the space a little bitter. (Since now that's just a non-nonsensical configuration if one of the `via` servers isn't in the space.)
3. Limits the impact of "evil" servers unless they're listed in the `via`. (In which case the situation is as above, but you could kick servers off that list.)

Implementation-wise, this is a bit hairy though so we'll need to:

1. Modify the auth rules to assert the proper signature exists.
    * I *think* this will need to compare the signatures of the join to the `via` servers resolved from the state for the join event.
    * I'm unsure if this could cause split-brained rooms (or another flaw with someone purposefully choosing old events to base their join on).
2. Modify the local join logic to do a remote join in more situations. (We might also need to do something the list of servers provided to the `/join` endpoint if they don't align with the servers in `via`.)
	* This has some unknowns in it, but I'm sure those are surmountable. Hopefully it doesn't introduce too many edge-cases.

Is there anything else missing from this? It is rather a big change so I don't want to embark on an epic journey of implementation without a bit of buy-in. @neilalexander / @timokoesters / @turt2live  does this assuage your concerns (or bring up new ones)? (I can attempt to write this up into the MSC before you answer that if you'd prefer.)

2021-06-16 17:32 UTC, timokoesters commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
This looks good to me. I don't think it will lead to split rooms, but if an evil server is in `via` at some point, it can allow joins even after being removed from `via` again by choosing an old event to base the join on (like you said). I think this is acceptable.

2021-06-16 18:13 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
I'm not really sure I understand the differentiation. As far as I understand if you have an invite you're always allowed to join a room. This MSC doesn't attempt to change that.

2021-06-16 18:37 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
just looking for words to say whether this fits the "invite-only" description in the spec or not, as right now it's ambiguous.

2021-06-16 18:40 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
it would probably alleviate a lot of the concerns, though we should consider the client design aspect in this as well. Specifically, how would a user-friendly client expose this information to the user?

2021-06-16 18:42 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
I don't think it does, but I'm not sure what description you're talking about, I see [here](https://spec.matrix.org/unstable/client-server-api/#room-membership):

> Some rooms require that users be invited to it before they can join; others allow anyone to join. Whether a given room is an “invite-only” room is determined by the room config key `m.room.join_rules`. It can have one of the following values:
> 
> `public` This room is free for anyone to join without an invite.
> 
> `invite` This room can only be joined if you were invited.
> 
> `knock` This room can only be joined if you were invited, and allows anyone to request an invite to the room. Note that this join rule is only available to rooms based upon room version 7.

I would see this as something like:

> `restricted` This room can only be joined if you were invited, and allows anyone who is a member of the allowed rooms to join without an invite.

Is this the section you're talking about, or is there something else?

2021-06-16 19:01 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
it's a bit spread over the entire spec, so hard to link to. This thread doesn't matter much if the MSC is about to be rewritten.

2021-06-16 19:38 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
I'm not sure that it necessarily makes sense for the trusted-server list to be defined by those in the `via` list. It feels a bit magical. Why not have separate lists?

2021-06-16 19:40 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
we'll also need to modify the way the join dance works a little. Right now, the resident server signs the join event in `make_join`, but that signature is then invalidated because the joining server modifies the join event (eg, it changes `origin_server_ts`). I don't think any of those modifications are particularly important, so we might be able to ditch them.

2021-06-16 20:38 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
> I'm not sure that it necessarily makes sense for the trusted-server list to be defined by those in the `via` list. It feels a bit magical. Why not have separate lists?

Fair enough, I suppose having them be different might make sense, since the `via` is technically how you could join the space (or whatever room you're delegating access from). `authorised_servers` or something?

2021-06-17 07:26 UTC, ShadowJonathan commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
What about `gatekeepers`? It's a tad shorter.

2021-06-17 08:26 UTC, neilalexander commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
> requiring the joins to be signed by one of the servers listed in the `via`

I like this approach, as it will at least ensure that not just anyone in the room can turn evil.

> Modify the auth rules to assert the proper signature exists.
> ...
> I'm unsure if this could cause split-brained rooms (or another flaw with someone purposefully choosing old events to base their join on).

Since the `join_rules` event should be in the auth chain of the membership event already, we have everything we need to auth the event "as is".

Then we just need to make sure that the same check is done again against the current state in the soft-fail checks, which is the primary mechanism for guarding against state changes when old events are referenced.

2021-06-17 08:33 UTC, erkinalp requested changes
The restriction, as mentioned in the MSC, can be applied to any room, not just a space room, also fix the title to the proposal conventions
Signed-off by: Erkin Alp Güney <erkinalp9035@gmail.com>

2021-06-17 08:33 UTC, erkinalp commented on proposals/3083-restricted-rooms.md
> +# Restricting room membership based on space membership
The restriction, as mentioned in the MSC, can be applied to any room, not just a space room, also fix the title to the proposal conventions:
```suggestion
# MSC3083: Restricting room membership based on membership to another room
```

2021-06-17 08:33 UTC, erkinalp commented on proposals/3083-restricted-rooms.md
> +### Kicking users out when they leave the allowed space
```suggestion
### Kicking users out when they leave the allowed room
```

2021-06-17 10:16 UTC, timokoesters commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
@richvdh

> we'll also need to modify the way the join dance works a little. Right now, the resident server signs the join event in make_join

Can't we sign the event in send_join?

2021-06-17 10:41 UTC, ShadowJonathan commented on proposals/3083-restricted-rooms.md
> +# Restricting room membership based on space membership
"to"? shouldn't it be "in"?

2021-06-17 12:49 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
>>we'll also need to modify the way the join dance works a little. 
> Can't we sign the event in send_join?

yes, that would work too. The joining server needs to get a copy of the signed event back so you'd have to add that to the `send_join` response.

Making sure the event gets signed isn't hard, I'm just reminding people it needs a tweak to make it work right.

2021-06-17 18:25 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +when you switch the join rules from public to invite. Join rules currently govern
I believe I've included a note about this now.

2021-06-17 18:26 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +`!users:example.org` room in order to join without an invite<sup id="a2">[2](#f2)</sup>.
I've pushed an updated version, I'm hoping it is clearer now.

2021-06-17 18:27 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +# Restricting room membership based on space membership
The primary use-case is access via a space, the protocol changes do provide a bit more than that though.

2021-06-17 18:28 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
I've pushed a fairly major update of this, which I think takes into account what people have said above. 👍

2021-06-17 18:36 UTC, ShadowJonathan approved these changes
I'm generally pleased with this MSC, I think the added tradeoff with `via` will help prevent abuse and the like.

Several nits though, but thanks for authoring this MSC!

2021-06-17 18:36 UTC, ShadowJonathan commented on proposals/3083-restricted-rooms.md
> +The above check must also be performed against the current room state to potentially
```suggestion
The above check must also be performed against the then-current room state to potentially
```

nitpick, not sure though

2021-06-17 18:36 UTC, ShadowJonathan commented on proposals/3083-restricted-rooms.md
> +  a member is not yet invited or joined to the room.
```suggestion
  a member was not yet invited or joined into the room.
```

2021-06-18 11:12 UTC, t3chguy commented on proposals/3083-restricted-rooms.md
> +        "authorised_servers": ["example.org"]
Given that this field spans all entries in the allow list that now requires that all servers listed here are in all of the rooms listed above, this isn't very flexible

2021-06-18 12:09 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +The above check must also be performed against the current room state to potentially
I'm not sure what you mean by this, how does "current" differ from "then-current"?

2021-06-18 12:13 UTC, ShadowJonathan commented on proposals/3083-restricted-rooms.md
> +The above check must also be performed against the current room state to potentially
"current" implies 'now', "then-current" implies "'now' from the perspective of the join event", time-relative wording gets weird when room DAGs get involved, yeah

2021-06-18 12:15 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +        "authorised_servers": ["example.org"]
It requires that there's at least one authorized server in each of the rooms.

I assume the alternative is to list authorized servers for each allowed room? The other servers don't know *why* an authorized server is allowing the user into the room so it doesn't make sense to limit them to only allowing for particular room IDs.

E.g. if you have the following allow rules:

* `!abc:foo`
* `!xyz:bar`

With authorised servers of `foo` and `bar`. The `acme` server is also in the room, but not in either `!abc:foo` or `!xyz:bar`.

A new join occurs from `@alice:foo`, it is signed by `foo`. The `acme` server doesn't know whether the user was in `!abc:foo` or `!xyz:bar` (and it doesn't matter since we're trusting the `foo` server to have verified this).

I think decomposing this list into each room isn't technically feasible as the check needs to trust any of them equally anyway, thus it would feel like you're limiting servers to particular rooms, but that isn't possible.

I might be missing something though, so please shout if I am!

2021-06-18 12:27 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +The above check must also be performed against the current room state to potentially
It is implied that the "above" check is against the "then-current", and must be done again at the "now" state. At least I believe that's what @neilalexander was describing with the soft-failure.

2021-06-21 17:46 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
From a few discussions focused on how a user would interact with this feature it seems like it might not be the best solution. A room admin would need to understand quite low-level protocol details in order to understand what the list of "authorised servers" are. (The main confusion is that the servers are being trusted to authorise the joins, while it would be easy to confuse this with limiting to users from a server.)

An alternative solution would be to automatically authorise the servers from users who are able to issue invites. The rationale for tying this to the invite power-level is that those users can already issue invites to get new users into the room, so their servers can already join members to the room (skipping the allow rules checking).

The benefits to this approach is that the room admin would not need to manually manage a list of authorised servers (which could also go out of date).

This does have the same issues that one of the servers must be in the spaces in order to properly authorise the join.

An alternative alternative might be to use "room admins" instead, but that's a harder definition to  pin down.

I would be curious if anyone has thoughts on any major issues this might cause? I think my main concern is that it is a bit magical, but overall I think equating the invite power level to who can authorise users to join the room is reasonable.

2021-06-22 13:14 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +1. Don't let evil servers in your room in the first place
I've made the above change. I'm going to resolve this thread.

2021-06-22 13:14 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +        "authorised_servers": ["example.org"]
This has been removed.

2021-06-22 13:15 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +the room are trusted not to allow invalid users to join.<sup id="a3">[3](#f3)</sup>
I think the current version of the MSC handles this security aspect.

2021-06-24 10:04 UTC, richvdh approved these changes
looks good, modulo a few wording nits.

2021-06-24 10:04 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +event in the room.)
I think I'd rephrase this to make it clear it's just the obvious extension of the existing soft-fail checks:

```suggestion
The above check is also performed against the current room state during
[soft-failure](https://matrix.org/docs/spec/server_server/r0.1.4#soft-failure),
to guard against servers issuing new membership events by referencing old
events in the room.
```

2021-06-24 10:04 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +specification for full details, the summary below is meant to highlight the differences
```suggestion
specification for full details; the summary below is meant to highlight the differences
```

2021-06-24 10:04 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +side-side the restriction by issuing an invite first anyway.
```suggestion
side-step the restriction by issuing an invite first anyway.
```

2021-06-24 12:19 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +  have the power to issue invites.
Yes, I'll clarify!

2021-06-24 12:30 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +event in the room.)
Fair! Thank you for finding the cross-ref!

2021-06-24 13:42 UTC, BillCarsonFr commented on proposals/3083-restricted-rooms.md
> +and `/send_join` is placed in the homeservers whose users can issue invites.
This has an impact on the way via parameter should be computed when adding a room to a space. E.g a m.space.child content should provides a list of home server that would be trusted in order for joins to work when exploring a space directory.
Clients / Admins should maintain the via list to be valid?

2021-06-24 19:29 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +  from a homeserver whose users have the power to issue invites.
This implies that the auth events of the `m.room.member` event needs to include an event which "proves" that the homeserver has the power to invite other users. This pretty much means:

* The power levels event.
* A membership event of any user on the homeserver which is > minimum invite PL.

This should probably be made a bit more explicit here.

2021-06-24 19:41 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +  from a homeserver whose users have the power to issue invites.
It also means that the server who has `/send_join` called on it needs to add their signature to the membership event. This doesn't seem to be required by the spec, but seems like a good idea regardless?

2021-06-25 18:43 UTC, turt2live approved these changes
this is looking better as an approach, and is a lot less scary. It does, as noted in the MSC, increase centralization but I think the balance of security + room purpose + availability for promotion of a server still preserves the ideals of room operation.

As a bit of a closing footnote: it might be worth expanding more on why the `invite` power level was chosen specifically. Other candidates such as the power level required to send join rules (or even the PL required to send PLs) and creatorship could have been applied instead. The downside to a lot of these alternatives is that they strike more strongly on the centralization side of the scale for unequal gain on security due to the inability to more easily promote/trust servers at lower risk (giving more servers "admin" PL in a room isn't necessarily a good thing, whereas giving them moderator or even a level between default and moderator is much less risk for losing control of the room).

2021-06-25 18:43 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +an allowed room its membership cannot be checked (and this is a misconfiguration).
slight clarification: I assume the server should still try to let the user in if it can. For example, if 1/2 of the rooms is unknown (making 1/2 known), and the user is joined to the known room, then the request can go through. 

Or in other words: this sounds like it's making the default assumption that a user is not joined to rooms which are unknown, I think?

2021-06-25 18:43 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +From the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
note for future spec PR writer: update this (and other links) to point at stable versions for historical reasons. It currently redirects to the unstable version due to lack of release.

2021-06-25 18:43 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +* `public`: anyone can join, subject to `ban` and `server_acls`, as today.
can probably hoist "subject to ban and acls" out to the list's intro paragraph to make it a bit easier to parse the list. At the MSC level we're more concerned with the idea, so acknowledging that there are conditions which prevent all join rules from working is more than enough to cover the implicit bases of join rules.

2021-06-25 18:43 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +During development, an unstable room version of `org.matrix.msc3083` will be used.
does this need to be bumped to `org.matrix.msc3083.v2` or `v18` or whatever to denote any potential difference in the algorithm usage? (room versions are meant to be frozen, even development ones, so if `org.matrix.msc3083` had the potential for use in the wild then it'll need a bump to ensure maximum safety of those rooms)

2021-06-25 18:49 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +  from a homeserver whose users have the power to issue invites.
This sounds like a good thing to do indeed. The resident server is implicitly accepting the event on behalf of the joining server anyways, so it might as well stamp that approval on the event it is sending. The signature additionally wouldn't affect the actual state event (due to all signatures being excluded when verifying any particular signature), so is doubly safe.

2021-06-25 18:57 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +During development, an unstable room version of `org.matrix.msc3083` will be used.
We can bump it, but I have no intention of supporting the previous version, so those rooms would become unjoinable. That's probably OK though in this case.

2021-06-25 18:58 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +an allowed room its membership cannot be checked (and this is a misconfiguration).
> this sounds like it's making the default assumption that a user is not joined to rooms which are unknown, I think?

I think this is the gist of it, yes. If the homeserver doesn't know if a user is in a room or not, it assumes the user is not.

Note that the user only has to be in a single allowed room to be able to join, so if the server is in *one* of the rooms it can be useful.

2021-06-25 19:31 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +During development, an unstable room version of `org.matrix.msc3083` will be used.
Dropping the old version is completely acceptable - just avoiding a scenario where one server thinks it's running one kind of unstable and another thinks its running another kind.

2021-06-25 19:33 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +an allowed room its membership cannot be checked (and this is a misconfiguration).
👍 what are the chances that can be clarified a bit in the MSC? 😇

2021-06-28 11:49 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +an allowed room its membership cannot be checked (and this is a misconfiguration).
I'll take a look!

2021-06-28 12:32 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +From the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
It seems that https://matrix.org/docs/spec/#complete-list-of-room-versions links to https://matrix.org/docs/spec/rooms/v1.html which eventually redirects to https://spec.matrix.org/unstable/rooms/v1/#authorization-rules.

So I don't think there's something better to link to?

2021-06-28 12:56 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +an allowed room its membership cannot be checked (and this is a misconfiguration).
I attempted to clarify this a bit, but this paragraph pairs with the one above it which is fairly clear that a user only has to be in a single room to be allowed to join.

2021-07-01 16:54 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +and `/send_join` is placed in the homeservers whose users can issue invites.
I added a note about this.

2021-07-02 19:41 UTC, timokoesters commented on proposals/3083-restricted-rooms.md
> +events in the room.
The security looks good to me now, but soft failure does not guard against state events, let me quote the spec:

> Soft failed events participate in state resolution as normal if further events are received which reference it. It is the job of the state resolution algorithm to ensure that malicious events cannot be injected into the room state via this mechanism.

I think we can just remove this paragraph.

2021-07-05 11:00 UTC, jaywink commented on proposals/3083-restricted-rooms.md
> +* `knock`: the same as `invite`, except anyone can knock. See
Not sure there is anything that can be done about this, but it feels like being able to `knock` a room that is `restricted` would be useful too, at least in one community I'm in. It's a bit of an edge case for sure and relates more to the Knock MSC than this one, just voicing as a pity that these two valuable features cannot be enabled at the same time. Should have voiced a lot earlier, I know :)

2021-07-05 16:39 UTC, giomfo commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
@clokep  I vote for this new `join_rule` option but I disagree about the naming here. 
For me, `restricted` is too strong compared to the actual behavior.
The first time I heard about this feature I believed only the whitelisted people (the "allowed") would be able to join. But the room is still joignable by invite...

Unfortunately, I don't have an obvious suggestion. I would propose "softened_invite", "invite_with_bypass".
For me, this new rule is closer to `invite` than `public` (To argue, "If the `allow` key is an empty list (or not a list at all, , then no users are allowed to join without an invite)

2021-07-05 16:39 UTC, giomfo commented on proposals/3083-restricted-rooms.md
> +the `restricted` join rule has the same behavior as `public`, with the additional
Don't you think possible to describe this new rule has a join rule with the same behavior as `invite` with additional caveat?
You may then remove "The user's previous membership was `invite` or `join`,"  from the additional caveat

2021-07-05 17:04 UTC, giomfo commented on proposals/3083-restricted-rooms.md
> +* `knock`: the same as `invite`, except anyone can knock. See
@clokep  I agree with @jaywink 
don't you think we just need to add the `allow` key to decline the existing `join_rule` values without adding a new one (event if the `allow` key will be useless for `public`).

If we go that way, I already see other keys to add in the `join_rule` content:
- `authorized_servers` to limit the authorized homeservers from which to join the room
- `unauthorized_servers` to prevent the users of some homeservers from joining

2021-07-06 16:55 UTC, uhoreg commented on proposals/3083-restricted-rooms.md
> +    * A join event issued via `/make_join` & `/send_join` is signed by the not
```suggestion
    * A join event issued via `/make_join` & `/send_join` is signed by not
```

2021-07-06 17:03 UTC, uhoreg approved these changes
Looks fairly sane.  I'd be interested in seeing how it works out in practice before giving my FCP :heavy_check_mark: but I'm not seeing any obvious problems.  The new scheme seems like a sensible compromise.

2021-07-07 01:26 UTC, kevincox commented on proposals/3083-restricted-rooms.md
> +* `knock`: the same as `invite`, except anyone can knock. See
I think it is a bit of a shame that we missed fixing this in the knock MSC but I think it can be patched with the changes in this. We can continue using a `restricted` event type but add a `allow_knock` field. Something like this:

```json
{
    "type": "m.room.join_rules",
    "state_key": "",
    "content": {
        "join_rule": "restricted",
        "allow": [{
            "type": "m.room_membership",
            "room_id": "!users:example.org"
        }],
        "allow_knock": [{
            "type": "m.any"
        }]
    }
}
```

You could even compose these to allow members of a (bigger) space to knock.

```json
{
    "type": "m.room.join_rules",
    "state_key": "",
    "content": {
        "join_rule": "restricted",
        "allow": [{
            "type": "m.room_membership",
            "room_id": "!mods:example.org"
        }],
        "allow_knock": [{
            "type": "m.room_membership",
            "room_id": "!users:example.org"
        }]
    }
}
```

I plan on writing an MSC after this is accepted. Hopefully we can then deprecate the `knock` `join_rule`. Maybe even get rid of `public` and `invite` at the same time.

2021-07-07 08:13 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +      the fact, even for current room versions.)
Does `/send_join` return the join event again? As when the joining server calls `/send_join` with the event its hasn't yet been signed by the remote.

2021-07-07 08:41 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
Something that has cropped up during implementation is that its no longer possible to tell a) which state is required to auth an event and b) which servers are required to have signed the event, by only looking at the event itself.

Knowing which state (i.e. type/state key tuples) needed to authenticate an event is used to reduce the amount of state pulled from the DB during authentication (and state res v2) to just three or so events, which really helps performance. The current proposal would require pulling out potentially all membership events in the room for servers that signed the event, which is less than ideal.

When verifying signatures for events the server currently needs to know *which* servers must have signed the event, this proposal complicates that as the server needs to fetch the auth events and then figure out which of those memberships events is the one included for the purposes of allowing the join due to the sender being in a valid space. I *think* this is a well specified lookup (you drop the other membership auth events that are there for other reasons, which for joins are probably just invites), but it complicates things a bit (and means we need to be careful when adding new rules so that this lookup remains well specified).

On top of that, MSC1228 is a thing we want, which removes server signatures from events and replaces them with per-user signatures.

So to make life easier on all those points I propose that we add a `joined_via_users_server: <user_id>` field that specifies *which* user is being added to the auth events, and thus which server needs to sign the event and what state is required to auth the event.

2021-07-07 08:51 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
How do we signal that the joining server should try another server? If it receives a 403 I think it gives up immediately?

2021-07-07 08:51 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
Do we need to be concerned about the case where there is only a couple of servers in a large ish room that can handle a `/send_join`? Currently for public rooms Synapse sets the invite level in the default power levels to 50, so that only admins and mods can invite, which really narrows down the list of servers that can be used to join via.

E.g. say we had an Element internal room which I on jki.re created, but wanted to allow other Element employees to join, so I add the Element employee space to the list of accepted spaces. Since its an Element room I give it an alias on the company HS. After a while lots of people from different servers are joined. How does a new server join the room? Using the server of the canonical alias won't work, and the likelihood of randomly trying jki.re seems small?

2021-07-08 07:41 UTC, BillCarsonFr commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
Most common use case would probably be that Element employees discover the room via the space directory, in this case the m.space.child event contains a list of via servers, they would use that

2021-07-12 17:49 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `knock`: the same as `invite`, except anyone can knock. See
> Not sure there is anything that can be done about this, but it feels like being able to `knock` a room that is `restricted` would be useful too, at least in one community I'm in.

This was discussed a bit amongst the team and we didn't feel there was a real use-case for it. Can you describe a bit further why you think it would be useful?

> don't you think we just need to add the `allow` key to decline the existing `join_rule` values without adding a new one (event if the `allow` key will be useless for `public`).

I think this has been brought up and answered multiple times, see https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r641946633 and the alternative section in the MSC.

2021-07-12 17:51 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
From a user's point of view, the join rule is effectively invite-only, unless your user meets some other parameters.

I think "restricted" encapsulates this nicely, but this isn't really meant to be exposed directly to users and it is up to client UI to describe this accurately.

2021-07-12 17:52 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +the `restricted` join rule has the same behavior as `public`, with the additional
As this paragraph describes it is closer to `public` than `invite`, *from the perspective of the auth rules*.

From a user's perspective it is somewhere in-between.

2021-07-12 18:01 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      the fact, even for current room versions.)
It does not seem to get returned (it seems only the auth events and room state *prior to the join event* are returned).

2021-07-12 18:09 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
So by specifying a user here this let's us quickly know which tuple to pull out of the state when verifying?

A potential issue I see with this is that (I think) it could cause an event to be soft-failed if that particular user is no longer in the room when a new server joins.

Consider:

* `@authorizer:hs1`, a user who can issue invites
* `@joiner:hs2` joins and the event is signed via hs1 since `@authorizer:hs1` can issue invites
* Time passes, `@authorizer:hs1` leaves the room and has their PL demoted
* `@third:hs3` joins the room (doesn't matter how)

Is hs3 able to properly validate the join event of `@joiner:hs2`? It is valid in the context of when the join event happened, but not when hs3 joins.

Maybe this is a case which already works in state-res and I'm missing something!

2021-07-12 18:17 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +events in the room.
@erikjohnston Do you have any opinions on this?

2021-07-12 18:20 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
The common case is that the `m.space.child` event would contain it, or perhaps a matrix.to link with the proper `via` servers setup.

> How do we signal that the joining server should try another server? If it receives a 403 I think it gives up immediately?

This is somewhat unsolved in the server-server spec in general, it is unclear what are transient failures vs. something else. We could add a separate error code for being unable to verify vs. being able to verify you cannot join.

2021-07-12 20:01 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +their room based on the membership of one or more spaces from
We should probably clarify that this isn't just for space membership, but allows "members of room A are allowed to join room B".  Use cases include private spaces, potentially room upgrades for private rooms, potentially letting all users in one private room automatically be able to join a sidebar room (or thread-as-room).

2021-07-12 20:15 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
'restricted' also tripped me up slightly when i first saw it for the same reasons as giom: it sounds as we're restricting who can join in the room in general (even if invited) - rather than who can join without an invite.  It's not a showstopper for me, but I do wonder if we can avoid everyone else in future using the API tripping up over this.

I'm wondering if something like `invite_and_allowed` would be clearer as to what's going on?

2021-07-12 20:42 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +From the perspective of the [auth rules](https://spec.matrix.org/unstable/rooms/v1/#authorization-rules),
sorry, this is effectively a note to self. No action needed on your part.

2021-07-12 20:46 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +to not know if the user is in some of the allowed room (due to not participating
```suggestion
to not know if the user is in some of the allowed rooms (due to not participating
```

2021-07-12 20:46 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
actually `invite_or_allow` might be better.  although neither capture the idea that the allows are based on room IDs.

2021-07-12 20:59 UTC, turt2live commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
This definitely sounds like the unsolved "how do you join a room reliably" problem, which is out of scope for this MSC imo. Currently, spaces do provide the options mentioned by others, but if those fail then you're kinda on your own to get an alternative alias from someone.

2021-07-12 21:00 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
actually, given `knock` implies that `invited` users are allowed in anyway, we don't need the `invite_or` thing.  So `allowed` is a bit better here - given it directly points you towards the `allow` list for who is allowed to join the room.   Not sure the advantage is sufficient to make it worth changing at this point though (especially if we ever added a `deny` list).  So I think we should keep it as `restricted`, after all that.

2021-07-12 21:02 UTC, turt2live commented
@mscbot resolve The security of the room does not match up to the `restricted` keyword.

2021-07-12 21:03 UTC, turt2live approved these changes

2021-07-12 21:05 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +if the user has a valid invite or is in one of the listed rooms. If the user is
```suggestion
if the user has a valid invite or is joined to one of the listed rooms. If the user is
```

pedantry: make it clear that you have to be actively `join`ed in the listed room, not just invited or parted.

2021-07-12 21:25 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +rooms (or some of the rooms cannot be verified) the homeserver should reject the
Perhaps we should use a different error code if the user was rejected but the server couldn't check all the `allowed` rooms? e.g. `M_UNKNOWN_ALLOWED_ROOM` or something?  This could then be used to go try to join via other servers.

2021-07-12 21:32 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +rooms (or some of the rooms cannot be verified) the homeserver should reject the
Presumably we also need an `M_CANT_ALLOW` or something to show if the reason the join failed was because the server doesn't have permission to send the join?

2021-07-12 21:53 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
i think the thought experiment here is the same as if `authorizer` simply invited `joiner` and then left.  This scenario handled by state res fine; later users can still auth `joiner` despite `authorizer` being no more.

That said, I don't understand why @erikjohnston wants to add a `joined_via_users_server` rather than just a `joined_via_server` field. Why do we care which user_id was used to allow the join?  (And doesn't this imply that a single user_id is responsible, whereas there could multiple admins on the server which allows the join)?  Don't we only care about the server?

2021-07-12 21:57 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +events in the room.
yeah, this sounds right. we're protected against servers emitting new membership events by referencing old events in the room... but the protection doesn't come from soft-fails, but by the overall state resolution algorithm.  So i agree that it'd be clearer to just remove this, given it's saying "it's status quo".

2021-07-12 22:03 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
having read through the rest of this, i really think we should switch to `allowed` - it conjures up the idea of expanding the `invite`-only room to also support certain `allowed` users, and matches the `allow` list.

2021-07-12 22:09 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
I think this thread is resolved for the question of "how do I find a server to try to join via?".  I've opened a separate thread for the error codes.

2021-07-12 22:14 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +* `knock`: the same as `invite`, except anyone can knock. See
I assume the use case here is that I have a big set of big private rooms, where access is `allowed` to folks in #members.  It's hard to track which members are valid, so they need a way to knock and get in.  Presumably the solution is to make #members knockable.

Alternatively, if the use case is that people need to be able to knock to get into a single big private room (because we want folks to request access to certain private rooms but not others without having to be explicitly being invited), then this is still a gap.

I agree that it feels like a bad smell that we can't mix knocking and `allowed` rooms, but also agree this can be punted to a later MSC.

2021-07-12 22:16 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +but there are concerns that changing the behaviour of a pre-existing a `public`
```suggestion
but there are concerns that changing the behaviour of a pre-existing `public`
```

2021-07-12 22:21 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +their room based on the membership of one or more spaces from
```suggestion
their room based on the membership of one or more rooms.
```

2021-07-12 22:22 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +[MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772), for example:
```suggestion

```

2021-07-12 22:22 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +> members of the #doglovers space can join this room without an invitation<sup id="a1">[1](#f1)</sup>
```suggestion
> members of the #doglovers:example.com space can join this room without an invitation<sup id="a1">[1](#f1)</sup>
```

2021-07-12 22:28 UTC, ara4n commented
This is an excellent MSC imo, and i would be very glad to approve for FCP once we have resolved the two final concerns, which are I think:

@mscbot concern Need to [define better error codes](https://github.com/matrix-org/matrix-doc/pull/3083#pullrequestreview-704557174) to be clearer what's happening when joins fail, to let users/clients/servers know how to react.
@mscbot concern Need to add the [details of the server (or user?) who granted a given join](https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r665167397), so implementations can auth it more easily.  For a normal invite this would be the inviter, but we need an equivalent for this use case.

I also have a soft-concern that `allowed` would be a better name for the join_rule rather than `restricted`, but not going to block on that.

2021-07-13 08:42 UTC, jaywink commented on proposals/3083-restricted-rooms.md
> +* `knock`: the same as `invite`, except anyone can knock. See
> This was discussed a bit amongst the team and we didn't feel there was a real use-case for it. Can you describe a bit further why you think it would be useful?

We have a community who will mostly be added to one parent space and the plan is for most of the rooms underneath to be then set to `restricted` instead of `invite` (like now). The community then grows down in a tree structure with for example a working group having one or more subgroups underneath it.

```
root (knock)
-- group1 (restricted on root)
---- subgroup1 (restricted on group1)
---- subgroup2 (restricted on group1)
```

This works all fine if members get added to the `root` space (either invitation or knock). But if say someone wants to join the  `subgroup2` room, without being a part of `group1` (or even `root`), then they would not be able to knock themselves in and would need the current "ask for invite" route, which knock aims to solve. `subgroup2` could be made `knock`, but then members of `group1` would not be able to automatically get access.

How would someone know about `subgroup2`? For example by having got an invite to some of the higher level rooms (without being in a space/room granting access) where it is mentioned or the room address being shared outside the community, maybe a call for action for random contributors who want to join this particular one interest group instead of the whole community. Knocking in would then be useful.

I totally agree this should not block this (very very important MSC), but possibly a future MSC could fill this gap somehow.

2021-07-13 09:22 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +      the fact, even for current room versions.)
I guess it would be easy enough to add the newly signed event to the response of `/send_join`. Though it does mean that the local server can't/shouldn't persist the join event until *after* it received the `/send_join` response.

2021-07-13 09:41 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
Yup, that example is basically the same as normal invites, which works fine (when doing state res we pull in the auth chain, and so the hs2 join will pull in the hs1 invite/join correctly).


> That said, I don't understand why @erikjohnston wants to add a `joined_via_users_server` rather than just a `joined_via_server` field. Why do we care which user_id was used to allow the join? (And doesn't this imply that a single user_id is responsible, whereas there could multiple admins on the server which allows the join)? Don't we only care about the server?


Right now we have a function for going from an event to the list of types/state keys required to auth the event (and thus be added as the event's `auth_events`). This MSC breaks that, as we now have a requirement for "a join event for a user that has invite privs" , and adding a `joined_via_server` doesn't help that. This is a problem for two reasons:

1. The amount of state to pull out of the DB to auth the join event is no longer bounded (we'd need to pull out all member events for the server), which is a performance problem for both event auth and state res.
2. Turns out the state res algorithm relies on the existence of a well defined mapping, in particular in the "Iterative auth checks" section:

   > If a `(event_type, state_key)` key that is required for checking the authorization rules is not present in the state, then the appropriate state event from the event’s `auth_events` is used if the auth event is not rejected.

   We could update the algorithm to say something like "if an event doesn't pass auth based on state, shove in any extra auth events and see if it passes then" or something.

---

TBH, if we're serious about MSC1228 then we're going to need to do this on a per user basis anyway, which is a compelling argument for me :shrug:

2021-07-13 09:57 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
I guess this is maybe fine ish so long as:

1. When clients add a room to a space they correctly include the right servers as candidate servers (i.e. the intersection of users with invite power and who are in the space);
2. When clients send a alias/matrix.to link they also include the correct candidate servers; and
3. Servers that responds to alias lookups do their best to filter candidate servers to the right ones (where possible).

I think those things should be mentioned in the MSC and spec, as otherwise I think this feature is going to be *super* flakey if clients don't do the right thing.

-- 

> This definitely sounds like the unsolved "how do you join a room reliably" problem, which is out of scope for this MSC imo. 

I think the difference is that we're potentially making that problem much worse here. For normal rooms there is a really good chance that at least the canonical alias is going to be work fine for a long period of time. My worry is that aliases just won't work reliably for large restricted rooms, which would be a) frustrating for users and b) cause users to lose trust in Matrix as a reliable service. 

However, I *think* the above mitigations might be enough to ensure that links at least reliably, and aliases on servers that are in the room and space?

2021-07-13 10:00 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +events in the room.
Yeah, I think this paragraph is redundant, as we apply the normal auth rules during soft failure.

> The security looks good to me now, but soft failure does not guard against state events

(Ish, it works fine unless another server a) accepts the state event and b) references it when sending a new event.)

2021-07-13 12:28 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +events in the room.
I've gone ahead and removed this paragraph. Thanks for the feedback.

2021-07-13 12:43 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +their room based on the membership of one or more spaces from
I've re-worded this top section to hopefully be clearer!

2021-07-13 12:49 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
Your first point is already included in the section "Interaction with `m.space.child` events", but I can expand that to include the second point.

We should include something about updating the alias lookup to respond with the correct servers though. 👍

2021-07-13 12:51 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* `knock`: the same as `invite`, except anyone can knock. See
Thanks for the clarification! It sounds like you want rooms to be discoverable by members of a space, but not directly joinable. (So in your above example you might want anyone from `root` to be able to knock, but any member of `group1` to be able to join or something.)

I haven't explored this in detail and I think it is best to get this simplified form done first and leave this to a future MSC!

2021-07-13 15:10 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
having slept on this, i'm now worried that `allowed` just seems weird without context. "join_rule is allowed" makes it sound that anyone is allowed to join, rather than it being restricted to a subset of users (+explicitly invited users).

So I've gone full circle again and am back at preferring `restricted`. let's leave it there.

2021-07-13 15:13 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
okay, ack. (and we are serious about #1228, or its successor #2787). hadn't twigged that we needed to know the specific join event for the user with invite privs, but makes sense now.

@clokep: sounds like adding `joined_via_user` or `join_granted_by_user` solves this one?

2021-07-13 15:38 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
Yeah, @erikjohnston and I had a conversation about this and I think that's the way forward. It simplifies a couple of things in the implementation!

2021-07-13 16:52 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +In a future room version a new `join_rule` (`restricted`) will be used to reflect
Thanks for thinking through this. As I mentioned over Matrix I'm not a big fan of the `invite_or` thing since inviting is allowed in all rooms (and e.g. `knock` isn't `knock_or_invite`). I'd be OK with changing it to `allowed`, but I think that does sound too similar to `public`.

Unless someone can come up with a good alternative I think the best bet is to leave it as `restricted`.

It also came up in our conversation that in the future we may want to add different types of rules to `allow`, so I don't want to tie it too closely to the current proposal (e.g. `delegated` was thrown around).

2021-07-13 17:48 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
Taking a look at implementing this, I think the resident server needs to add the additional info to the content during the call to `/make_join` so that it gets signed by the joining server, unfortunately the spec allows the joining server to then using a *different resident server* for the `/send_join` call. So you could end up with `joined_via_user: @alice:hs1`, but the event signed by `hs2`.

I guess we could forbid that behavior here, but I'm unsure if I'm missing something?

2021-07-14 08:41 UTC, novocaine commented on proposals/3083-restricted-rooms.md
> +their room based on the membership of one or more rooms.
If we're changing the summary and suggesting spaces are just one use case, should we also update the title to reflect the generality?

2021-07-14 14:18 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +their room based on the membership of one or more rooms.
I think the title reflects the primary use-case.

2021-07-16 17:04 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +be verified (and this is a misconfiguration).
I've expanded the client considerations section a bit and also mentioned that homeservers should use the authorised servers, not the candidate servers, when joining a room. The Synapse implementation already did this. 😄 

Done in 290f9032f4c4b0d87b3290ab2f0c5d3c24262eb2.

2021-07-16 17:16 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      equal to `join` for a member who could issue invites from that server.
This should be added in 290f9032f4c4b0d87b3290ab2f0c5d3c24262eb2 and ffb9095c82672c49f2a500797cd10a919495ea4a. The Synapse PR was also updated with this information.

2021-07-19 19:07 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +rooms (or some of the rooms cannot be verified) the homeserver should reject the
Hm. Do you think we need different error codes in those situations? I think the joining server's behavior is the same, but I guess for clarity it is best to keep them separate.

2021-07-19 19:11 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +rooms (or some of the rooms cannot be verified) the homeserver should reject the
I think 7caff82b and 55b99d29 capture this. We can bikeshed the names...

2021-07-19 19:11 UTC, clokep commented
I believe that both concerns are now handled in the current proposal!

2021-07-20 11:33 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +resident homeserver.
After sleeping on this, I wonder if it makes more sense to use a generic `M_TRY_ANOTHER_HOMESERVER` error instead. This could then get re-used in the future if necessary. *Why* this is happening could be included in the error message.

Does that sound more useful?

2021-07-20 12:32 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      event will be returned via `/send_join` in the `event` field.
It came up during implementation that it was unclear if this should be done unconditionally or only if the event has extra signatures added, etc.

2021-07-20 15:39 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +`/send_join` request to not know if the user is in some of the allowed rooms (due
```suggestion
`/send_join` request) to not know if the user is in some of the allowed rooms (due
```

2021-07-20 15:40 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +A chosen resident homeserver might also be unable to issue invites, in this case
```suggestion
A chosen resident homeserver might also be unable to issue invites; in this case
```

2021-07-20 15:41 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +A chosen resident homeserver might also be unable to issue invites, in this case
I'm not really following where the idea of issuing invites came from?

2021-07-20 15:46 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +* The `m.room.member` event with a `membership` of `join` has a valid signature
I found this hard to understand. I suggest that you rephrase this to:

> ... with the additional caveat servers must ensure that, for `m.room.member` events with a `membership` of `join`:

... and then just:

```suggestion
* The join event has a valid signature
```

2021-07-20 15:52 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +A chosen resident homeserver might also be unable to issue invites, in this case
oh I get it now.

```suggestion
A chosen resident homeserver might also be unable to issue invites (which, as below, is a pre-requisite
for generating a correctly-signed join event). In this case,
```

2021-07-20 15:52 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +resident homeserver.
I think it's probably best to keep the error code explicit, which allows us more flexibility with how we handle the situation in future. :man_shrugging: though.

2021-07-20 16:13 UTC, erikjohnston commented on proposals/3083-restricted-rooms.md
> +      chosen is arbitrary.
I'd rephrase these two paragraphs, as I think we're mandating that `join_authorised_via_users_server` is set and that user's join event appears in the auth rules?

Actually, do we even need the join event to be added to the auth events? It doesn't really matter if the given user is joined?

2021-07-20 16:32 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +A chosen resident homeserver might also be unable to issue invites, in this case
Would it be clearer to move these two paragraphs below the bit about auth rules?

2021-07-20 16:34 UTC, ara4n commented on proposals/3083-restricted-rooms.md
> +resident homeserver.
It's a close call, but i'd also veer towards being explicit. `M_CANNOT_ALLOW` is awkward and clumsy and doesn't match with `M_UNABLE_TO_AUTHORISE_JOIN` though.  What about `M_UNABLE_TO_GRANT_JOIN`?

2021-07-20 16:35 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      chosen is arbitrary.
> Actually, do we even need the join event to be added to the auth events? It doesn't really matter if the given user is joined?

I'm assuming this is referring to the join event of the authoriser? I think you do want that in the auth chain because you do want them to be joined to the room, otherwise the server in question doesn't actually have the power to issue invites, since their user isn't in the room.

This is the way the implementation works right now at least.

2021-07-20 16:52 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +A chosen resident homeserver might also be unable to issue invites, in this case
errrm there's something to be said for keeping all the words about make_join and send_join together, rather than interrupting them to talk about auth_rules.

2021-07-20 16:56 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +* The `m.room.member` event with a `membership` of `join` has a valid signature
you only did half of this.

2021-07-20 17:22 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      chosen is arbitrary.
We talked through this in #matrix-spec:matrix.org -- https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$f2CkW6bhBkPylYds9nuygEy9jkBL2wi48z4sIEwC-lQ?via=matrix.org&via=libera.chat&via=vector.modular.im

The summary is that you *do* need to include the event in the event auth and you do need to confirm the user is joined, otherwise it could allow any server to issue joins (even those not in the room) if you have funky power-levels, e.g. if the invite and default levels were the same.

2021-07-20 17:23 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +A chosen resident homeserver might also be unable to issue invites, in this case
I moved this down further, it seems more appropriate to defer this to later in the text since it is discussing error handling and we haven't even fully described the happy path yet!

2021-07-20 17:24 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      chosen is arbitrary.
I've tried to clarify this in 88a94049d29179f1a8a1a531ee121389804258af.

2021-07-20 17:26 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +      chosen is arbitrary.
yeah this section is a bit unclear. This is a new requirement for `/make_join` - could it be moved out of the bit describing the auth rules?

2021-07-20 17:26 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +      the call to `/send_join`).
this begs the question of what happens if a server receives a `/send_join` for an event that was `/make_join`ed elsewhere. Does it accept it blindly, or check?

2021-07-20 17:29 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +* The `m.room.member` event with a `membership` of `join` has a valid signature
Sorry, GitHub is making it really difficult to follow comments at this point.

2021-07-20 17:35 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +  `join_authorised_via_users_server`. The actual user chosen is arbitrary.
```suggestion
  When generating a join event for `/join` or `/make_join`, the server should include the MXID of a local user
  who could issue an invite in the content with the key
  `join_authorised_via_users_server`. The actual user chosen is arbitrary.
```

2021-07-20 17:43 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +resident homeserver.
Thanks for the thoughts! I've updated the `M_CANNOT_ALLOW` to `M_UNABLE_TO_GRANT_JOIN`, which sounds an awful lot like `M_UNABLE_AUTHORISE_JOIN`, but... 🤷

2021-07-20 17:43 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      the call to `/send_join`).
I've included that this is a 400 error. I don't think there's anything "better" to do there?

2021-07-20 17:52 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      event will be returned via `/send_join` in the `event` field.
We decided to do this conditionally in the implementation and leave it to another MSC to always sign them.

2021-07-20 18:03 UTC, ara4n commented
@mscbot concern Need to [define better error codes](https://github.com/matrix-org/matrix-doc/pull/3083#pullrequestreview-704557174) to be clearer what's happening when joins fail, to let users/clients/servers know how to react.
@mscbot concern Need to add the [details of the server (or user?) who granted a given join](https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r665167397), so implementations can auth it more easily.  For a normal invite this would be the inviter, but we need an equivalent for this use case.

Thanks for incorporating - from my pov this is good now (although others' feedback may remain).

2021-07-20 18:04 UTC, ara4n commented
@mscbot resolve concern Need to [define better error codes](https://github.com/matrix-org/matrix-doc/pull/3083#pullrequestreview-704557174) to be clearer what's happening when joins fail, to let users/clients/servers know how to react.
@mscbot resolve concern Need to add the [details of the server (or user?) who granted a given join](https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r665167397), so implementations can auth it more easily.  For a normal invite this would be the inviter, but we need an equivalent for this use case.

Thanks for incorporating - from my pov this is good now (although others' feedback may remain).

2021-07-20 18:07 UTC, ara4n commented
@mscbot resolve Need to [define better error codes](https://github.com/matrix-org/matrix-doc/pull/3083#pullrequestreview-704557174) to be clearer what's happening when joins fail, to let users/clients/servers know how to react.
@mscbot resolve Need to add the [details of the server (or user?) who granted a given join](https://github.com/matrix-org/matrix-doc/pull/3083#discussion_r665167397), so implementations can auth it more easily.  For a normal invite this would be the inviter, but we need an equivalent for this use case.

Thanks for incorporating - from my pov this is good now (although others' feedback may remain).

2021-07-20 21:15 UTC, anoadragon453 approved these changes
Makes sense and well-written. I only came out with cosmetic changes in the end (and one tiny nit).

It might be nice to require an AND operator for required rooms in a future MSC (though this could potentially just be done by adding more keys to the `allow` dicts).

2021-07-20 21:15 UTC, anoadragon453 commented on proposals/3083-restricted-rooms.md
> +the peek server significant power. For example, a poorly chosen peek
```suggestion
This would then delegate power out to a (potentially) untrusted server, giving that
peek server significant power. For example, a poorly chosen peek
```

2021-07-20 21:15 UTC, anoadragon453 commented on proposals/3083-restricted-rooms.md
> +when you switch the join rules from public to invite. Join rules currently govern
```suggestion
when you switch the join rules from `public` to `invite`. Join rules currently govern
```

2021-07-20 21:15 UTC, anoadragon453 commented on proposals/3083-restricted-rooms.md
> +help. but it's unclear what the desired semantics are:
```suggestion
help, but it's unclear what the desired semantics are:
```

2021-07-20 21:15 UTC, anoadragon453 commented on proposals/3083-restricted-rooms.md
> +These are just examples are not fully thought through for this MSC, but it should
```suggestion
These are just examples and are not fully thought through for this MSC, but it should
```

2021-07-21 11:36 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +If the `allow` key is an empty list (or not a list at all), then no users are
This is saying that anything other than a list is invalid.

2021-07-21 11:41 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +of 400 with an `errcode` of `M_UNABLE_TO_AUTHORISE_JOIN`. The joining server should
Fair. It is implied from the sentence before it, but isn't clear.

2021-07-21 14:03 UTC, richvdh commented on proposals/3083-restricted-rooms.md
> +      event will be returned via `/send_join` in the `event` field.
I *still* find it odd that this text about changes to `/make_join` and `/send_join` is buried in the bit about auth rules, but :man_shrugging:

2021-07-21 15:05 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +HTTP status code of 400.
> (or are we actually saying that it should check the `join_authorised_via_users_server` is itself?)

This.

2021-07-21 15:05 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      event will be returned via `/send_join` in the `event` field.
Can you recommend a clearer place to put it?

2021-07-21 15:08 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +HTTP status code of 400.
Although thinking on this a bit more, I don't think the `/make_join` and `/send_join` need to necessarily go to the same server, more of that the `/send_join` needs to go to the server which `join_authorised_via_users_server` points to.

I'm unsure if there's any security issues with a resident server having `/make_join` called on it and returning a `join_authorised_via_users_server` from a *different* server. It doesn't really seem like there would be a problem with this?

2021-07-21 15:09 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      event will be returned via `/send_join` in the `event` field.
Would it be better if I de-indented this entire section?

2021-07-22 14:26 UTC, clokep commented on proposals/3083-restricted-rooms.md
> +      event will be returned via `/send_join` in the `event` field.
I de-indented this, which hopefully clarifies it a bit. I tried re-writing this a bit, but wasn't really able to fully decouple it from this section.

2021-07-23 18:05 UTC, KitsuneRal commented on proposals/3083-restricted-rooms.md
> +are known to the homeserver, and the homeserver is not participating in all listed
“…not participating in all allowed rooms” sounds ambiguous.
```suggestion
are known to the homeserver, and the homeserver is not participating in any of the listed
```

2021-07-25 22:41 UTC, merged

2021-07-26 14:00 UTC, clokep commented
Excited to see this land! Thanks all for the feedback on this -- it took a while, but I think we ended up with a better solution than initially proposed! 🎉

2021-09-08 05:14 UTC, turt2live commented
Spec PR: https://github.com/matrix-org/matrix-doc/pull/3387

2021-11-02 13:26 UTC, clokep commented
I've updated the rendered link in the description to the `main`-branch to ensure that the minor change from #3299 is included whew viewing the markdown version. There's nothing we can do if you view the source from this PR, but hopefully the spec PR will be done soon!