[MSC] An error code for spam rejections
matrix-org/matrix-doc pull request #3174
Opened 2021-05-04 10:02 UTC by Yoric

2021-05-04 11:38 UTC, erkinalp commented on proposals/3174-an-error-code-for-spam-rejections.md
> +# MSC3174: An error code for spam rejections
```suggestion
# MSC3174: Error codes for spam rejections
```

2021-05-04 11:39 UTC, erkinalp commented on proposals/3174-an-error-code-for-spam-rejections.md
> +    - `m.reject.server` -- federation with this server has been deactivated (e.g. because server is used to send spam);
```suggestion
    - `m.reject.spam` -- spam has been detected (e.g. message or username is spam);
    - `m.reject.inappropriate` -- unacceptable content has been detected (e.g. a user attempting to register `@deathtojews:...`);
    - `m.reject.investigation` -- account is suspected of being a spambot and is deactivated pending investigation;
    - `m.reject.server` -- federation with this server has been deactivated (e.g. because server is used to send spam);
    - `m.reject.ua` --- disallowed user agent or user agent family (including implicitly detected behavioral patterns)
```

2021-05-04 11:40 UTC, erkinalp requested changes
Add a new error code, and fix the title

2021-05-04 12:45 UTC, MTRNord commented on proposals/3174-an-error-code-for-spam-rejections.md
> +    - `m.reject.server` -- federation with this server has been deactivated (e.g. because server is used to send spam);
Do you mean bots that use specific useragents? That might be dangerous as plenty bots use default User-agents. especially the bad ones do. So I would think that it causes false positives.

2021-05-04 12:55 UTC, erkinalp commented on proposals/3174-an-error-code-for-spam-rejections.md
> +    - `m.reject.server` -- federation with this server has been deactivated (e.g. because server is used to send spam);
> So I would think that it causes false positives.

Indeed it can. But nowhere in the proposed change tells the user agent detection must, or even should, be based on the `User-Agent` strings alone. Instead, the kinds of user agents that act similarly to the suspected user agent may be rejected by this error code.

2021-05-04 21:48 UTC, tulir commented on proposals/3174-an-error-code-for-spam-rejections.md
> +# MSC3174: An error code for spam rejections
There's only one new `errcode`, `M_ANTISPAM_REJECTION`

2021-05-04 21:50 UTC, tulir commented on proposals/3174-an-error-code-for-spam-rejections.md
> +    - `m.reject.server` -- federation with this server has been deactivated (e.g. because server is used to send spam);
If a server doesn't want to tell the user the reason, it shouldn't include a `kind` field at all.

2021-05-05 07:28 UTC, Yoric commented on proposals/3174-an-error-code-for-spam-rejections.md
> +    - `m.reject.server` -- federation with this server has been deactivated (e.g. because server is used to send spam);
1. The idea is that `kind` is optional, so as @tulir mentioned, if we don't want to tell the reason, just don't include a `kind`.
2. For `m.reject.investigation`, it doesn't have to be *illegal* activity. The notion of "illegal" is very complicated in Matrix-land, as each country has different laws. This is about any activity that requires investigation, typically spambots.

2021-05-05 07:54 UTC, Yoric commented on proposals/3174-an-error-code-for-spam-rejections.md
> +    - `m.reject.server` -- federation with this server has been deactivated (e.g. because server is used to send spam);
While I don't think that `m.reject.ua` would cause any issue, I don't see a good use case for it yet. Unless there's a clear and present use case, I would suggest postponing `m.reject.ua` to another MSC.

2021-05-05 19:42 UTC, erkinalp commented on proposals/3174-an-error-code-for-spam-rejections.md
> +# MSC3174: An error code for spam rejections
`kind`s are also error codes

2021-05-05 19:43 UTC, erkinalp commented on proposals/3174-an-error-code-for-spam-rejections.md
> +# MSC3174: An error code for spam rejections
just a separate error code from `errcode`

2021-05-07 18:18 UTC, 0x1a8510f2 commented on proposals/3174-an-error-code-for-spam-rejections.md
> +1. Add a new error code `M_ANTISPAM_REJECTION`;
Seeing as rejections could happen for reasons other than spam (for instance, `m.reject.server` does not explicitly specify spam to be the reason, only a possible reason), perhaps this should just be more generic, like `M_REJECTION`?

2021-05-10 06:58 UTC, Yoric commented on proposals/3174-an-error-code-for-spam-rejections.md
> +1. Add a new error code `M_ANTISPAM_REJECTION`;
The idea to call it `M_ANTISPAM_REJECTION` is due to the fact that the message is rejected by the antispam filter, even if it's not necessarily spam, but you're right, that's a fine nuance that doesn't bring anything to the table.

I'm ok with `M_REJECTION`.

2021-05-10 07:33 UTC, erkinalp requested changes
Required error `kind` for plausible deniability of rejection reasons

2021-05-10 07:33 UTC, erkinalp commented on proposals/3174-an-error-code-for-spam-rejections.md
> +2. Any `M_ANTISPAM_REJECTION` error MAY come with a field `kind`, which may contain any of the following values:
```suggestion
2. Any `M_ANTISPAM_REJECTION` error MUST come with a field `kind`, which may contain any values, with the recommended set with corresponding below:
```

2026-05-14 17:10 UTC, turt2live commented
With my T&S hat: closing in favour of https://github.com/matrix-org/matrix-spec-proposals/pull/4387

2026-05-14 17:10 UTC, closed without merging