Case fold instead of lowercase
matrix-org/matrix-doc pull request #3176
Opened 2021-05-04 15:35 UTC by turt2live

Fixes https://github.com/matrix-org/matrix-doc/issues/3175

2021-05-04 16:29 UTC, richvdh requested changes

2021-05-04 16:29 UTC, richvdh commented on changelogs/identity_service/newsfragments/3167.clarification
> +Clarify that some identifiers may be case-folded to lowercase prior to processing, as per [MSC2265](https://github.com/matrix-org/matrix-doc/pull/2265).
```suggestion
Clarify that some identifiers must be case folded prior to processing, as per [MSC2265](https://github.com/matrix-org/matrix-doc/pull/2265).
```

2021-05-04 16:29 UTC, richvdh commented on content/appendices.md
>  prior to any processing. For example, `Strauß@Example.com` must be
sadly `casefolding.txt` doesn't cover all the bases (in particular, it doesn't cover the ß->ss example you give below :)

```suggestion
prior to any processing, implementations are expected to apply the
unicode case-folding algorithm as described under "Caseless Matching" 
in [chapter 5 of the unicode standard](https://www.unicode.org/versions/Unicode13.0.0/ch05.pdf#G21790).
For example, `Strauß@Example.com` must be
```

2021-05-04 17:19 UTC, turt2live commented on content/appendices.md
>  prior to any processing. For example, `Strauß@Example.com` must be
This sounds like a concern of the MSC, as this was pulled straight out of there :)

Will take a look - we might need to update the MSC.

2021-05-04 18:05 UTC, richvdh commented on content/appendices.md
>  prior to any processing. For example, `Strauß@Example.com` must be
if the MSC doesn't quite define case-folding correctly, I don't think that's a major concern. IMHO MSCs need to clearly convey the intent, rather than being completely watertight.

2021-05-18 15:55 UTC, turt2live commented on content/appendices.md
>  prior to any processing. For example, `Strauß@Example.com` must be
I more meant that per the process we also have to update the MSC to use the right link - that only requires another MSC if it's a drastic change.

2021-05-18 15:56 UTC, turt2live commented on changelogs/identity_service/newsfragments/3167.clarification
> +Clarify that some identifiers may be case-folded to lowercase prior to processing, as per [MSC2265](https://github.com/matrix-org/matrix-doc/pull/2265).
applied manually

2021-05-24 16:04 UTC, richvdh commented on changelogs/identity_service/newsfragments/3167.clarification
> +Clarify that some identifiers may be case-folded to lowercase prior to processing, as per [MSC2265](https://github.com/matrix-org/matrix-doc/pull/2265).
not applied to this file, apparently :/

2021-05-24 16:04 UTC, richvdh approved these changes
lgtm otherwise

2021-05-24 16:05 UTC, turt2live commented on changelogs/identity_service/newsfragments/3167.clarification
> +Clarify that some identifiers may be case-folded to lowercase prior to processing, as per [MSC2265](https://github.com/matrix-org/matrix-doc/pull/2265).
ugh, changelogs are difficult. Will fix before merge.

2021-05-26 17:06 UTC, merged