Clarify that implementations can use stable prefixes once an MSC has merged
matrix-org/matrix-doc pull request #3179
Opened 2021-05-04 16:48 UTC by anoadragon453

This PR changes the Matrix Spec Proposals page to clarify that implementations **do not** need to wait until a spec release to use stable prefixes, but that they can do so after the corresponding MSC has been merged. The justification is that once an MSC has been merged, it's fairly guaranteed that it will land in the spec. Yet it will take time for the spec release process to run its course, and we shouldn't make implementations wait for that.

The exception to this is if implementating a feature in a backwards-compatible way requires a new spec version to indicate to clients/servers that a feature has been added/changed. This situation is rare though, and most implementations won't fall into this category.

There's a couple changes at the top of the diff which were just correcting errors in the document.

2021-05-05 14:58 UTC, richvdh requested changes

2021-05-05 14:58 UTC, richvdh commented on content/proposals.md
> +    (e.g.: for an endpoint, moving from
.: is a bit unwieldy.

```suggestion
    (for example, for an endpoint, moving from
```

2021-05-05 14:58 UTC, richvdh commented on content/proposals.md
> +    been merged. Once an MSC has been accepted and merged, implementations
according to the above, it's not neccesary for an MSC to be merged to the spec. Can we relax this?

2021-05-10 17:40 UTC, anoadragon453 commented on content/proposals.md
> +    been merged. Once an MSC has been accepted and merged, implementations
Ah, by "accepted and merged" I meant just that the MSC proposal document needs to be merged - not that the spec PR needs to be merged.

I'll try to clarify.

2021-05-13 14:06 UTC, anoadragon453 commented on content/proposals.md
> +    document has been merged to the matrix-doc repository. Once that has
Sure, that is less wordy.

2021-05-13 14:23 UTC, merged