MSCXXXX: Aristotle - Moderation in all things
matrix-org/matrix-doc pull request #3215
Opened 2021-05-24 13:35 UTC by Yoric

A step towards decentralized moderation/reputation.

2021-05-24 13:40 UTC, deepbluev7 commented
Please add a sign-off and if you can, also a link to the rendered version (i.e. the proposal file on your branch). <3

2021-05-24 13:57 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +We expect that this enum will be amended by further MSCs.
Suggestion: Prefix these with `m.` and allow custom `nature`s of reporting to exist, not only for IM, but possibly for other applications as well (whatever those may be).

`m.` would fall under the MSCs, but anything outside that is "free game"

2021-05-24 14:06 UTC, Yoric commented
I realized that there is a big hole around "message routing". Closing the MSC until I have a better idea of how to handle that.

2021-05-24 14:07 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- `abuse.*` will be prefixed `org.matrix.msc3215.abuse.nature.*`.
I added `nature` to avoid collision with prefixed `m.abuse.report`.

2021-05-24 17:16 UTC, tulir commented on proposals/3215-towards-decentralized-moderation.md
> +- `abuse.*` will be prefixed `org.matrix.msc3215.abuse.nature.*`.
I mean why is there nature in the unstable version but not in the stable one? Potential collision cases are the exact same for both unstable and stable versions (neither needs to care about collisions of values that are only used in different fields)

2021-05-24 17:57 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +    "state_key": "m.room.moderation.moderator_of.XXX", // XXX is the ID of the Community Room, i.e. the room being moderated.
shouldn't this just be `XXX`, leaving out the prefix?

2021-05-24 17:57 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +Routing Bot. This Routing Bot is part of the server and has access to priviledged information such as room membership.
Again, i think this is a bad idea when the focus of matrix wants to shift away from servers and onto users and rooms, maybe specify that such a bot can either be server-controlled or "self-hosted", and it'll solve a lot of problems down the line (such as the "permissions bot" in #2962 which both needs to be verifiable in a decentralized manner, but also built-into every server it'll touch)

State that the bot can be any valid matrix user, then it only has to follow below behaviour to be "acceptable" as a cog in this MSC.

Note that this is a point of centralisation, though i think this is less of a problem than requiring built-in server bots

2021-05-24 17:57 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +A possible setup would involve two Moderation Bots, both members of a moderation room _MR_.
Note that maybe these can be the same bot, one that both classifies and bans, only that there are two "faces" to it here.

2021-05-24 18:32 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
>  ```jsonc
uhhh, duplication?

2021-05-24 18:44 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +This is BAD. This actually suggests that the problem goes beyond the Routing Bot.
I think this (and directly above case) are always going to stay a problem with servers, but as i said in #spec, i'm confident that "keeping" this problem instead of trading it with other (more complex) ones is worth it, as i'm banking on the fact that matrix P2P will solve this and many other problems more thoroughly.

You'll eradicate most of these (essentially) MITM attacks by avoiding servers, but for now, keeping this as-is with a routing user, would be - imo - the best kind of solution. (unless, ofc, other people suggest better things, i'm not perfect)

2021-05-25 08:56 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- `abuse.*` will be prefixed `org.matrix.msc3215.abuse.nature.*`.
The `m` saved us from collisions :)
But to avoid any ambiguity, I'm adding `nature` in both.

2021-05-25 09:22 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +Routing Bot. This Routing Bot is part of the server and has access to priviledged information such as room membership.
Not sure I follow what you're suggesting.

I've removed the "privileged" part, though.

2021-05-25 10:05 UTC, Yoric commented
Recent changes:

- introducing the Routing Bot to fill the hole around routing;
- analysis of a number of possible attacks and what could be done to improve the situation vs. the attacks that can work.

2021-05-25 10:24 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +A member of a Moderation Room may disconnect the Moderation Room from a Community Room by removing state event `m.room.moderation.moderator_of`, `XXX`. This may serve to reconfigure moderation if a C
```suggestion
A member of a Moderation Room may disconnect the Moderation Room from a Community Room by removing state event `("m.room.moderation.moderator_of", "XXX")`. This may serve to reconfigure moderation if a Community Room is deleted
```

state event "keys" are often displayed as a tuple

2021-05-25 10:24 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +    - If room _M_.`moderated_by_id`  does not contain a state event `m.room.moderation.moderator_of`/`XXX`, where `XXX`
```suggestion
    - If room _M_.`moderated_by_id`  does not contain a state event `("m.room.moderation.moderator_of", "XXX")`, where `XXX`
```

ditto

2021-05-25 10:24 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +- A Classifier Bot consumes `m.abuse.report` messages, discards messages from users who have joined recently or never been active in the room (possible bots/sleeping bots), then collates reports agai
I'd say that this should be up for the bot itself to classify, reword it so that it's a mere suggestion as to display what the bot can do in response to these reports.

2021-05-25 10:24 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +an event and another API to check the certificate.
I'm sceptical of the benefits of this, but i'll keep it to that, no comment right now

Note that adding an endpoint increases complexity on the server, which you may want to avoid in a "on-matrix"-only abuse report system

2021-05-25 10:24 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +If necessary, a hardened Client could make deductions harder/increase deniability by randomly sending bogus abuse reports to the Routing Bot.
I'd say that this is a last resort, and shouldn't be advertised as "okay", as the bot can still retaliate to that user, because this can be seen as spam.

2021-05-25 10:24 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +Variant:
```suggestion
Also consider another variant;
```

2021-05-25 10:24 UTC, ShadowJonathan commented on proposals/3215-towards-decentralized-moderation.md
> +Variant:
```suggestion
Another variant;
```

2021-05-25 12:07 UTC, anoadragon453 reviewed
Thank you for taking the time to write all of this out. It's clear you've thought about a lot of the edge cases.

I think it's a noble goal to try and reduce homeserver admin interference as much as possible, though that can be a difficult goal with our current architecture.

I think the current design is essentially 90% of the way there, though I acknowledge that we're sailing on relatively uncharted waters w.r.t built-in bots and sharing information cleanly between separate rooms.

2021-05-25 12:07 UTC, anoadragon453 commented on proposals/3215-towards-decentralized-moderation.md
> +However, this means that one Routing Bot per homeserver member of the Community Room needs to be invited to each Moderation Room. In particular, this would expose all the content of the Moderation Ro
Why would you need to invite every routing bot of every homeserver in the community room? Why not just 1+ routing bots that belong to the homeservers of the moderator(s)?

2021-05-25 12:16 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +A member of a Moderation Room may disconnect the Moderation Room from a Community Room by removing state event `m.room.moderation.moderator_of`, `XXX`. This may serve to reconfigure moderation if a C
It's connected at one end but not the other, so I'd say no.

2021-05-25 12:17 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- A Classifier Bot consumes `m.abuse.report` messages, discards messages from users who have joined recently or never been active in the room (possible bots/sleeping bots), then collates reports agai
I think it's clear enough that this is an example.

2021-05-25 12:19 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +    rooms may be shared between several rooms and there may be a default moderation room for a homeserver.
That was the initial idea, but I didn't take advantage of it, so removing from the MSC.

2021-05-25 12:21 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +    reporting entire rooms, although it is expected that further MSCs will eventually deprecate this API.
The idea is that, for the time being, we keep the reporting API, reporting only to our homeserver admin and we'll work on improving this in future MSCs.

2021-05-25 12:24 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.room`: report the entire room, e.g. for voluntarily hosting behavior that violates server ToS;
Yes, that's where the current abuse report API comes in play. I'll clarify this.

2021-05-25 12:30 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +2. When the Routing Bot receives a message other than `m.abuse.report`, it ignores the message.
Right, it's a message event with type `m.abuse.report`.

2021-05-25 12:32 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +    - If room _M_.`moderated_by_id`  does not contain a state event `m.room.moderation.moderator_of`/`XXX`, where `XXX`
It's not. Clarifying.

2021-05-25 12:40 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- the Moderation Room is a room in which Alice has a powerlevel sufficient for sending messages;
Actually, I should have written "events" instead of "messages".

1. Alice needs to set (`m.room.moderator_of`, room_id).
2. My intuition tells me that this helps us rely on existing PL mechanisms to allow kicking Alice out of the Moderation Room if they misbehave.

Do you think I'm missing something?

2021-05-25 12:41 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +an event and another API to check the certificate.
There's a discussion below on the risks of having a built-in bot. Does this answer your comment?

2021-05-25 12:42 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +    but cannot witness the contents of the message (assuming encryption);
Actually, it doesn't really have to be part of the homeserver. Truly, I'd probably prefer if it wasn't.

2021-05-25 12:43 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +I cannot find any solution to these problems: as long as an administrator can impersonate a moderator, they can access all moderation data past the date of impersonation.
Should I add a comment to this effect in the MSC?

2021-05-25 12:43 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +One idea could be to somehow make the Routing Bot a priviledged user with *partial* access to the Admin API to all the homeservers involved. This feels like a lost fight, though, a strong risk that h
I meant it as an example. Clarifying.

2021-05-25 13:25 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +However, this means that one Routing Bot per homeserver member of the Community Room needs to be invited to each Moderation Room. In particular, this would expose all the content of the Moderation Ro
I'm assuming that the Routing Bot needs to be on the same homeserver as the user to be able to check that the abuse report is forged. You're probably right that we only need it to be on the same homeserver as a moderator, if we assume that the moderator was a member of the Community Room at the time of the event that is reported. This looks like a complex invariant, though.

2021-05-25 13:53 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +an event and another API to check the certificate.
Anyway, it's not part of the spec, just an illustration of how we could improve things without breaking the MSC.

2021-05-29 14:05 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
Why enforce that there is a bot? This seems to be over-complicated. Why not just provide a list of users that should be invited to a report room? This could be a bot, or it could just be the room admin(s). This way the use of a bot is not mandated. This also has a number of advantages, such as maybe one of the admins is causing the issue, the user could choose to exclude that user (this benefit is lost in the case of a bot, but at least it is allowed in some cases). Furthermore the user can use E2EE if they know the admin's keys. This removes an extra set of keys that need to be dealt with.

It is also much simpler, especially for the case of a small team of admins that manage a room or two. Now they don't need to set up rooms, bots or anything. Yet they are still prepared if a (rare) abuse report comes in. In fact I would even consider that clients recommend reporting to the users of highest power-level in the room if this event is not present, this means that there is some sort of reasonable route for reporting abuse even if the room moderators haven't considered that abuse may concern. (People generally don't think about these issues until they happen)

The process then becomes:
1. Create a room.
2. Invite the users listed in the `m.room.moderated_by` event. If there is no such event invite all of the users at the highest power level in the room.
    a. Optional: The user may instead invite only a subset of this list.
3. Send an `m.abuse.report` as described below.

At that point that report may be handled by the bot listed in the `m.room.moderated_by` event, it may be manually forwarded to another room for internal discussion among the moderators, or it may just be discussed in the reporting room. This approach seems much simpler and much more flexible.

2021-05-30 12:07 UTC, erkinalp commented on proposals/3215-towards-decentralized-moderation.md
> +5. There is no good mechanism to route a report by a user to a moderator, especially if they live on different homeserver.
```suggestion
1. If the abuse report concerns an event in an encrypted room, the homeserver administrator
typically does not have access to that room, while a room moderator would,
hence cannot act upon that report.
2. Many homeserver administrators do not wish to be moderators, especially
in rooms in which they do not participate themselves.
3. As the mechanism does not expose an API for reading the abuse reports,
it is difficult to experiment with bots that could help moderators.
4. As the mechanism is per-homeserver, reports from two users of the same room
that happen to have accounts on distinct homeservers cannot be collated without
manual effort and coordination between server administrators.
5. There is no good mechanism to route a report by a user to a moderator,
especially if they live on different homeserver.
```
Signed-off by: Erkin Alp Güney <erkinalp9035@gmail.com>

2021-05-30 12:07 UTC, erkinalp commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
Probably to couple with ban lists as rooms.

2021-05-30 12:07 UTC, erkinalp commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
```suggestion
- `m.abuse.nature.other`: doesn't fit in any category above.
- `m.filter.copying`: automated screening to account for laws like Directive of Copyright
in the Digital Single Market.
```
Signed-off by: Erkin Alp Güney <erkinalp9035@gmail.com>

2021-05-30 12:12 UTC, erkinalp requested changes

2021-05-30 12:12 UTC, erkinalp commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.*` will be prefixed `org.matrix.msc3215.abuse.nature.*`.
Slightly shorter unstable keys:
```suggestion
- `m.room.moderation.moderated_by` will be prefixed `org.matrix.msc3215.moderated_by`;
- `m.room.moderation.moderator_of` will be prefixed `org.matrix.msc3215.moderator_of`;
- `m.abuse.report` will be prefixed `org.matrix.msc3215.report`;
- `m.abuse.nature.*` will be prefixed `org.matrix.msc3215.nature.*`.
```
Signed-off by: Erkin Alp Güney <erkinalp9035@gmail.com>

2021-05-31 08:03 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
I love the idea of making the list extensible. It definitely makes sense.

On the other hand, if we think tooling, I believe that having a standardized list is the way to go because:
1. it makes internationalization possible;
2. it makes it easier to write bots or other tools to display abuse reports in a human-readable manner for non-technical moderators;
3. it makes it easier to customize clients to handle abuse-specific case

Additionally:
- if we do not have a default list of abuse natures, we increase the difficulty of setting up new rooms;
- my personal experience with e.g. Reddit or Twitter suggests that having a list that is too long makes it harder to pick one abuse nature.

What do you think about the following:
1. having a (possibly long) list of standardized abuse natures, initialized in this MSC and extended in future MSCs;
2. having a mechanism that will let the moderation room and/or the community room define natures from this list **or** non-standard values and that will let the client use natures from this list;
3. having a mechanism that will specify a default list of standardized abuse natures when creating a new community (or perhaps moderation?) room?

While points 2 and 3 don't seem very complicated at first, I feel that they deserve their own MSC. I can rephrase the current MSC to leave room for them.

2021-05-31 08:11 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
> I fail to see the purpose of this room. IIUC users never actually use this room, they likely don't even have access.

The entire room or specifying the room ID in the state event?

If the former, well, we need to send abuse reports _somewhere_. The current abuse API has them sent to a proprietary admin API. We replace this with a standard room. At this stage, it's up to users and tooling to decide what they do with it.

If the latter, the client needs a way to find where to post the abuse reports.

2021-05-31 08:19 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
The main reason for there being a bot is that Matrix does not offer a built-in mechanism for users who are not member of a room (in this case, the Moderation Room) to post events towards that room. The bot is the simplest routing mechanism that I can think of. If I read correctly your counter-proposal, it does not address this (rather fundamental) issue.

> In fact I would even consider that clients recommend reporting to the users of highest power-level in the room if this event is not present, this means that there is some sort of reasonable route for reporting abuse even if the room moderators haven't considered that abuse may concern.

Good idea. We can definitely add this as a suggestion in the MSC if the state events are not setup.

> At that point that report may be handled by the bot listed in the m.room.moderated_by event, it may be manually forwarded to another room for internal discussion among the moderators, or it may just be discussed in the reporting room. This approach seems much simpler and much more flexible.

What's the "reporting room"? If it's what I call the Community Room, receiving abuse reports in the same room as they were sent leads to immediate deanonymization of the reporters.

2021-06-02 22:11 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
Here I am talking about in the state event.

> If the latter, the client needs a way to find where to post the abuse reports.

Please elaborate, I thought they just talked to the bot.

2021-06-02 22:22 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> If I read correctly your counter-proposal, it does not address this (rather fundamental) issue.

It does address it, but it does effectively sidestep it. It allows you to use a bot which forwards to a room, or it lets you just use the room that the user created to send the report. It puts the choice to the moderation team.

> What's the "reporting room"?

I mean the room the reporter created with the bot.

---

Let me summarize the flow you are requiring in this MSC.

1. Create a room with $bot.
2. Send an abuse report.
3. $bot copies report to $modroom.

That is a completely reasonable report flow. However it seems overly specified. There are many other valid moderation workflows that don't need or want this complexity. Especially if you have a smallish community abuse reports will be rare. So having a dedicated mod room for discussion is probably not necessary. And in many communities the mods may want to keep the separate reports in different rooms for organization. Also keep in mind that for many (probably most) communities the "mod team" is one person. So copying the abuse report to $modroom is quite pointless. It just lets that one mod discuss with themselves.

What I am suggesting is that we just drop everything about the bot and the moderation room from this MSC. It can still be implemented, but it leaves each mod team free to implement their own workflow and leaves room for different bots that work differently (and leaves room for no bot at all). In this case the MSC becomes

1. Create a room with $reportusers.
2. Send an abuse report.

This way we have a standardized method for *reporting* abuse. But the actual workflow for handling it is still flexible. It is totally valid to use a bot as suggested in this MSC to copy the report to a moderation room, however that is optional, not required.

This has a number of advantages in my mind.

- Small mod teams don't need to configure a bot.
- Small mod teams don't require *any* configuration.
- Leaves a lot of room for flexibility. Maybe instead of forwarding to the "mod room" it files a ticket in a ticketing system.

TL;DR I don't see the benefit of mandating the bot and its behaviour.

2021-06-02 22:31 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
> it makes internationalization possible

This is a good point. Maybe we can have "well known" types of abuse that can be translated by clients. For example `"nature": ["m.abuse.nature.toxic", "custom.Sent a message that wasn't the phrase \"Cat.\""]`. This way the well-known ones can be auto-translated but the room doesn't need to use all of the well-known types and can add their own. Of course making a consistent UX across well-known and custom categories may be hard.

On the other hand this probably isn't much of an issue. The moderators that create these rules will enter them in the language(s) that their community uses. Just like the moderators will need to translate the ToS at signup, set the room topic or similar.

> it makes it easier to write bots or other tools to display abuse reports in a human-readable manner for non-technical moderators;

I'm not sure that this provides a huge benefit. I think the reason would usually just be shown. If there is any filtering this is probably customized by the mod team anyways. I would be interested in any examples where this would be helpful.

> it makes it easier to customize clients to handle abuse-specific case.

What do you have in mind? I can't think of an example here.

> if we do not have a default list of abuse natures, we increase the difficulty of setting up new rooms;

I think this is a client issue. The client can provide a "quick list" of categories if they think it will be useful. They can also save it to the user account or pull a server default list if required. I don't think the spec is the best place to store a helpful list of abuse types to be honest.

> What do you think about the following?

I think this makes sense. I'm still not sure how much value the well-known list provides but I don't think they hurt much if they are optional to use and you can add custom ones. I agree that future MSCs can extend the list and add mechanisms to help clients suggest good defaults.

2021-06-03 05:34 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
> Please elaborate, I thought they just talked to the bot.

The bot is just a delivery mechanism to send a message to the Moderation Room. The same bot may be used by several Moderation Rooms. So we need both the userID of the bot (to talk to it) and the roomID of the Moderation Room (to tell it where to send the message).

2021-06-03 05:51 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
Where does the reporter send the abuse report in your counter-proposal? To a userID as specified in `moderated_by`?

If I understand correctly, you're splitting the MSC in two. The bot and moderation room are still necessary in many (most?) cases but remain unspecified. Essentially, we're losing the specification for `moderator_of` and how it interacts with possible bots.

---

> - Small mod teams don't need to configure a bot.
> - Small mod teams don't require any configuration.

Two notes on this:

1. Note that a good UX can make this configuration all happen in one-click.
2. In your proposal, a bot is still needed to convert the structured report into something human-readable.

> - Leaves a lot of room for flexibility. Maybe instead of forwarding to the "mod room" it files a ticket in a ticketing system.

Well, that's possible with either variant. The main difference in this specific scenario is that the Moderation Room allows more than one bot to operate.

2021-06-03 06:28 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
> > it makes internationalization possible
> 
> This is a good point. Maybe we can have "well known" types of abuse that can be translated by clients. For example `"nature": ["m.abuse.nature.toxic", "custom.Sent a message that wasn't the phrase \"Cat.\""]`. This way the well-known ones can be auto-translated but the room doesn't need to use all of the well-known types and can add their own. Of course making a consistent UX across well-known and custom categories may be hard.
> 
> On the other hand this probably isn't much of an issue. The moderators that create these rules will enter them in the language(s) that their community uses. Just like the moderators will need to translate the ToS at signup, set the room topic or similar.

Agreed with both points, but I still feel that this deserves its own MSC :)
 
> > it makes it easier to write bots or other tools to display abuse reports in a human-readable manner for non-technical moderators;
> 
> I'm not sure that this provides a huge benefit. I think the reason would usually just be shown. If there is any filtering this is probably customized by the mod team anyways. I would be interested in any examples where this would be helpful.

It's basically the same thing as translation, just for moderators.

> > it makes it easier to customize clients to handle abuse-specific case.
> 
> What do you have in mind? I can't think of an example here.

Actually, I can't think of a good example, either (I was thinking for instance of using the report button to report calls for help in case of suicide threats, but it's not very convincing).

On the other hand, having a standard list would be very useful for bots/tools. We can imagine a bot lurking both in the Moderation Room and in the Community Room and that watches specifically for `m.abuse.nature.spam` reports. Whenever it receives one in the Moderation Room, it checks in the Community Room whether the message truly looks like spam, using whatever heuristics are at hand, and may either take decisions such as auto-kicking or ping a moderator with a human-readable message to suggest kicking the offender. Similarly, a sufficiently smart bot could use libnsfw to discard or deprioritize `m.abuse.nature.porn` reports that don't seem to be porn, etc.

In a very different scenario, we can imagine a bot that files reports on GitLab. In certain cases, the bot should file the abuse report with as much context as it can possibly find - if the bot is present in the Community Room, it can attach the content of messages, copy links to images, etc. **Except** if the abuse is, say `m.abuse.nature.gore` or `m.abuse.nature.rape` or ... the moderators probably don't want to see the image.

> > if we do not have a default list of abuse natures, we increase the difficulty of setting up new rooms;
> 
> I think this is a client issue. The client can provide a "quick list" of categories if they think it will be useful. They can also save it to the user account or pull a server default list if required. I don't think the spec is the best place to store a helpful list of abuse types to be honest.

Agreed. Although I believe that we need a few entries to bootstrap testing.

> > What do you think about the following?
> 
> I think this makes sense. I'm still not sure how much value the well-known list provides but I don't think they hurt much if they are optional to use and you can add custom ones. I agree that future MSCs can extend the list and add mechanisms to help clients suggest good defaults.

Are we in agreement that this MSC can start with a short list and that the customization mechanism can wait for a followup MSC?

2021-06-03 10:42 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
Why doesn't the bot have a mapping from source room to destination.

2021-06-03 10:48 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
Using field `room_id` from the `m.abuse.report` message to know where the room comes from?

Yes, this could work, too, if we require the bot to be stateful. I believe that the best way to do it, though, is to keep rooms themselves the source of truth, rather than some bot memory.

2021-06-03 10:53 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> Where does the reporter send the abuse report in your counter-proposal? To a userID as specified in moderated_by?

Yes. You could have a `moderated_by` which is a list of users. (or a bot)

> If I understand correctly, you're splitting the MSC in two.

Basically. I see a lot of value to specifying how the client reports abuse, but I'm not so convinced that the "report management" workflow that you have proposed is sufficient for all use cases, furthermore I don't see as much value in standardizing it. So I think it makes sense to get the reporting flow through. Then we can consider management workflows later if we find value in standardizing it.

> Note that a good UX can make this configuration all happen in one-click.

But who is expected to run the bot? Is it to be built into every homeserver?

> In your proposal, a bot is still needed to convert the structured report into something human-readable.

Why can't this just be done by the client for the non-bot case?

> In your proposal, what's the scenario/UX for a large Community Room, e.g. MatrixHQ? Since these large public rooms are the ones that attract most abuse and spam, I'm hoping to target them pretty quickly for experimentation, with smaller rooms coming later.

In this case we would probably want a bot because with a lot of reports new rooms for each new report may be undesirable. So set `moderated_by` to the bot address. I don't really know how the mod teams of MatrixHQ work so I don't know if they would want it sent to a mod room like you have described, or they would prefer other options such and filing tickets or sending email.

My point here is that the bot workflow works even without being part of the spec. Each mod team can use a bot that works for them instead of mandating a single bot that implements one workflow.

> If I were to go this way, though, I'd probably come back with a MSC for the bot pretty soon

That sounds fine to me. If you can justify the value of specifying the bot I am all ears :)

2021-06-03 10:59 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
I see. Does this mean that the bot has to peek into the "community room" to see where it should send the report to? Or is the bot expected to be part of that room already?

2021-06-03 11:06 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
> It's basically the same thing as translation

One downside of translation is that it is basically putting words in the moderators mouth. Every client and every translation will interpret the boundaries of each `nature` differently. For a mod team it seems desirable to know exactly what categories you provide and exactly what they mean.

> On the other hand, having a standard list would be very useful for bots/tools

I don't fine these examples too convincing as they can easily be setup when configuring the bot. Even with a custom list the bot is still receiving predictable `nature`s as the list is picked by the moderators. I guess it makes a bot slightly easier to use across mod rooms or policies but this still think it is a minor benefit at best.

> Agreed. Although I believe that we need a few entries to bootstrap testing.

What type of testing do you think you need? I'm confused by this comment.

> Are we in agreement that this MSC can start with a short list and that the customization mechanism can wait for a followup MSC?

I don't think I agree. It sounds like this is a breaking change. I would rather get the customization mechanism specified from the onset so that clients don't need to be changed when it gets added. At the least we would need to explicitly reserve some format for the custom messages.

2021-06-04 05:29 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> > Where does the reporter send the abuse report in your counter-proposal? To a userID as specified in moderated_by?
> 
> Yes. You could have a `moderated_by` which is a list of users. (or a bot)

I believe that it only makes sense if it's a bot (or several), not human users:

1. Many moderators don't want to be annoyed by DMs and won't respond to invites from unknown users.
2. If they did, they'd be opening themselves to spam.
3. There's the problem of displaying the contents of the `m.abuse.report` (see below).

Also, if a bot is indeed a requirement, we need to determine whether your counter-proposal remains simpler.

> > If I understand correctly, you're splitting the MSC in two.
> 
> Basically. I see a lot of value to specifying how the client reports abuse, but I'm not so convinced that the "report management" workflow that you have proposed is sufficient for all use cases, furthermore I don't see as much value in standardizing it. So I think it makes sense to get the reporting flow through. Then we can consider management workflows later if we find value in standardizing it.

That makes sense.

> > Note that a good UX can make this configuration all happen in one-click.
> 
> But who is expected to run the bot? Is it to be built into every homeserver?

Good question. My initial assumption was that we could indeed have one in each homeserver or that e.g. matrix.org could host a reference routing bot.

> > In your proposal, a bot is still needed to convert the structured report into something human-readable.
> 
> Why can't this just be done by the client for the non-bot case?

Well, there's the fact that this is change to many clients, whereas delegating this to a bot is something that can be done once and benefit everyone. I realize it's debatable.

Also, consider the following scenario: case in which clients learn to display `m.abuse.report`. Now consider a case in which we do have a Moderation Room (e.g. for MatrixHQ). If the client displays every `m.abuse.report` in the Moderation Room, it display *every* report in the Moderation Room. We basically lose the ability to filter and only display reports that make sense (e.g. reports that are believed to not be spam). We also lose the ability to use a third-party tool to format the `m.abuse.report` better than what the client can do (e.g. by collating with a list of prior offenses from a database or another room).

From the top of my head, I see three ways to avoid that problem:

- to have a format `m.abuse.report` spoken by the client and another format e.g. `m.abuse.report.forward` with the exact same data for messages forwarded by the bot but that should not be displayed - feels like overkill;
- equivalently, extend `m/abuse/report` with a boolean field `display` to determine whether the client should display the data - feels a bit weird and I have the suspicion that this this would be abusable;
- or having two moderation rooms, one for data that must be displayed and another one for bots - which feels like overkill, too.

Do you see a better way to resolve this problem?

> > In your proposal, what's the scenario/UX for a large Community Room, e.g. MatrixHQ? Since these large public rooms are the ones that attract most abuse and spam, I'm hoping to target them pretty quickly for experimentation, with smaller rooms coming later.
> 
> In this case we would probably want a bot because with a lot of reports new rooms for each new report may be undesirable. So set `moderated_by` to the bot address. I don't really know how the mod teams of MatrixHQ work so I don't know if they would want it sent to a mod room like you have described, or they would prefer other options such and filing tickets or sending email.
> 
> My point here is that the bot workflow works even without being part of the spec. Each mod team can use a bot that works for them instead of mandating a single bot that implements one workflow.

I understand that point. I'm trying to determine whether your counter-version of the spec is sufficient to provide something usable or whether it also needs my half of the spec anyway :)

2021-06-04 05:58 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
> > It's basically the same thing as translation
> 
> One downside of translation is that it is basically putting words in the moderators mouth. Every client and every translation will interpret the boundaries of each `nature` differently. For a mod team it seems desirable to know exactly what categories you provide and exactly what they mean.

I don't think we can escape translation for the end-user.

> > On the other hand, having a standard list would be very useful for bots/tools
> 
> I don't fine these examples too convincing as they can easily be setup when configuring the bot. Even with a custom list the bot is still receiving predictable `nature`s as the list is picked by the moderators. I guess it makes a bot slightly easier to use across mod rooms or policies but this still think it is a minor benefit at best.

I disagree on this point. Making natures non-standard by default feels like a footgun to me.

> > Agreed. Although I believe that we need a few entries to bootstrap testing.
> 
> What type of testing do you think you need? I'm confused by this comment.

Once the MSC feels stable enough, I'm planning to prototype this MSC (probably as part of develop.element.io and matrix.org) to gather feedback from actual moderators and end-users. That's what I meant by "testing".

> > Are we in agreement that this MSC can start with a short list and that the customization mechanism can wait for a followup MSC?
> 
> I don't think I agree. It sounds like this is a breaking change. I would rather get the customization mechanism specified from the onset so that clients don't need to be changed when it gets added. At the least we would need to explicitly reserve some format for the custom messages.

I don't think this is a breaking change if we specify that clients that do not support customization may fallback to the standard list.

2021-06-04 14:01 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
In the current status of the MSC, the user's client copies this value `room_id` as field `moderated_by_id` in the `m.abuse.report`. This lets the bot find out where to route the message without having to peek into the room.

2021-06-04 23:44 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> Also, if a bot is indeed a requirement, we need to determine whether your counter-proposal remains simpler.

While I don't think that a bot is a requirement I agree that it is still interesting to see how much "overhead" would be with a "Report Procedure MSC" + "Report bot MSC" if the latter was necessary at all.

> Many moderators don't want to be annoyed by DMs

Isn't this basically their job, to be contacted by users in the case where a problem arises? What if there was a way to mark the reason of the room so it was clear what this room is about? Note that while many moderators handle large communities many also handle smaller ones and an abuse report is so rare as to not be annoying.

> there's the fact that this is change to many clients, whereas delegating this to a bot is something that can be done once and benefit everyone.

I see your point and agree that it is debatable. This point could be argued about every feature. Each feature needs to be implemented by clients, but by standardizing it we provide the ability for clients to innovate and optimize for their users.

> If the client displays every m.abuse.report in the Moderation Room, it display every report in the Moderation Room. We basically lose the ability to filter and only display reports that make sense

Why is this the case? The users could redact the message, or Matrix could learn a way to mark a comment as "uninteresting" (basically a soft redaction) that hides it. I think this would be required for the mod room anyways because the bot won't catch every case of spam so the users will still want this feature if it is indeed useful.

> We also lose the ability to use a third-party tool to format the m.abuse.report better than what the client can do

I don't see how letting clients format the report can reduce the ability of other tools to do so.

> From the top of my head, I see three ways to avoid that problem:

I don't see the problem you are trying to solve here. In the case the users themselves are listed in the `moderated_by` field there isn't going to be a bot munging the report. It will just be the raw report. For the case where you want "bot enhancement" you just set `moderated_by` to the bot and you don't see the original report, it is handled by the bot (possibly formatted nicely and dumped into a mod room).

2021-06-04 23:48 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
> I don't think we can escape translation for the end-user.

I'm not convinced. If we step away from creating a single moderation policy for the whole world it becomes very reasonable that the acceptable content policy is written in just the languages that the moderators operate. I'm not sure how effective a mod can be if they don't speak the same language as the user anyways.

> I disagree on this point. Making natures non-standard by default feels like a footgun to me.

What is the danger you see in this? 

> I don't think this is a breaking change if we specify that clients that do not support customization may fallback to the standard list.

I meant that clients will still need to know how to display these custom messages. Otherwise these users will no longer be able to report abuse.

2021-06-04 23:49 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "room_id": XXX, // The room picked for moderation.
Ah, I missed that. It still feels weird to me that we need to expose this to the user but I'll consider this resolved until I have a better idea what to do here.

2021-06-06 00:04 UTC, sumnerevans reviewed
I really like this idea. I have just a couple of small suggestions for making it more readable and a couple small questions.

2021-06-07 08:21 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- `m.abuse.nature.other`: doesn't fit in any category above.
> What is the danger you see in this?

Any case in which we'd need two tools to communicate with each other. I don't have specific examples yet, but I'd be really surprised if it didn't show up quickly.

> I meant that clients will still need to know how to display these custom messages. Otherwise these users will no longer be able to report abuse.

Agreed. I still believe that this can be done in a followup MSC, though.

2021-06-07 08:36 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> Isn't this basically their job, to be contacted by users in the case where a problem arises?

We agree that it's their job. My point is that a DM is the wrong way to do this. This is feedback I received from #matrix-spec and moderators when I worked on a previous iteration of this MSC and I am convinced :)

>  What if there was a way to mark the reason of the room so it was clear what this room is about?

Sorry, I don't understand.

> Note that while many moderators handle large communities many also handle smaller ones and an abuse report is so rare as to not be annoying.

Yes, my problem is not real abuse reports, it's spam, bullying, etc. through DMs.

> Why is this the case? The users could redact the message, or Matrix could learn a way to mark a comment as "uninteresting" (basically a soft redaction) that hides it. I think this would be required for the mod room anyways because the bot won't catch every case of spam so the users will still want this feature if it is indeed useful.

"uninteresting" sounds interesting but beyond the scope of this MSC.

Also, I feel that this actually adds an uncessary layer of complexity for a problem that can be solved more naturally by having a third-party tool (bot or issue tracker or...) turn the abuse reports into something human-readable. Remains the question of where such a bot would live, but I'm entirely happy to write and deploy one as a proof of concept.

> I don't see how letting clients format the report can reduce the ability of other tools to do so.

Ah, I realize I wasn't clear :)

My point is that we have the following scenario:

1. User creates abuse report.
2. Abuse report ends up in moderation room (for instance).
3. Moderator's client displays abuse report.
4. Bot reads abuse report and displays it better. Bot doesn't redact the abuse report because another bot might be interested in it and because the room is the source of truth for abuse.
5. => Abuse report is displayed twice, which is a source of confusion.

> For the case where you want "bot enhancement" you just set moderated_by to the bot and you don't see the original report, it is handled by the bot (possibly formatted nicely and dumped into a mod room).

One of the main points of this MSC is to make abuse reports structured data so that they can be treated by e.g. bots. If the bot formats them instead of forwarding them, we lose much of the interest of the MSC.

2021-06-07 19:00 UTC, erkinalp commented on proposals/3215-towards-decentralized-moderation.md
> +    - If _M_.`reporter` is not Alice, reject the event.
*M* = message ?

2021-06-08 06:10 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +    - If _M_.`reporter` is not Alice, reject the event.
Oops, _M_ should have been _E_. Fixing.

2021-06-08 06:16 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +- Each room MAY have a state event `m.room.moderated_by`. If specified, this is the room ID towards which abuse reports MUST be sent. As rooms may be deleted `m.room.moderated_by` MAY be an invalid r
Good question.

I do not see any reason to strip this from the state. I don't think that this is classified in any way if the room is previewable.

2021-06-08 12:59 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> My point is that a DM is the wrong way to do this.

For some mods, especially mod teams of large communities. For me DM is the right way. But more importantly a single "mod room" is not the right way for everyone. Some people will want reports in their ticketing system, some people will want emails, some people will want a web dashboard. This is why I don't want to mandate the receiving half of the workflow. There are so many possible workflows that I don't think it makes sense to standardize one single option.

>>    What if there was a way to mark the reason of the room so it was clear what this room is about?
>
> Sorry, I don't understand.

I mean if the invite to the reporting room included a clear marker that it was an abuse report, so the mod wasn't worried about random spam.

> Yes, my problem is not real abuse reports, it's spam, bullying, etc. through DMs.

How does this proposal make that any worse? Unless the mod has managed to hide their MXID. If they want to hide their MXID they can still use a bot or simpler forwarder with the simplified proposal.

> Abuse report is displayed twice, which is a source of confusion.

I see, so your intention is that the original report is floating around in the mod room, but the clients hide it so that they only see a reformatted version. This seems weird to me. Another option would be using a relation such as "obsoletes" or something that could suggest that the client hides it. (Or maybe provides a link for manual inspection). That would be another MSC but it seems like this MSC would still work fine, the UX can just be improved a bit later.

> One of the main points of this MSC is to make abuse reports structured data so that they can be treated by e.g. bots. If the bot formats them instead of forwarding them, we lose much of the interest of the MSC.

With my proposal the bot could forward both the original report and formatted, it is strictly more flexible than the original as far as I am aware. The customization is left to the report receiver which I find hugely valuable. I'm sure we will see some super powerful ways to handle reports, surely some that don't even involve a Matrix moderation room. This is why I think it is important to keep it flexible.

2021-06-08 13:44 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> > My point is that a DM is the wrong way to do this.
> 
> For some mods, especially mod teams of large communities. For me DM is the right way. But more importantly a single "mod room" is not the right way for everyone. Some people will want reports in their ticketing system, some people will want emails, some people will want a web dashboard. This is why I don't want to mandate the receiving half of the workflow. There are so many possible workflows that I don't think it makes sense to standardize one single option.

The entire point of my proposal is to put the messages in a place where they can be handled by tools. The fact that it's  a room is because in Matrix, a room is the abstraction where several tools (including Matrix clients) can connect, not because it's a place to discuss. The fact that we can discuss there is a nice bonus.

I believe that we agree that our proposals are mostly equivalent - with the notable of exception DM-ing moderators.

> > > What if there was a way to mark the reason of the room so it was clear what this room is about?
> > 
> > 
> > Sorry, I don't understand.
> 
> I mean if the invite to the reporting room included a clear marker that it was an abuse report, so the mod wasn't worried about random spam.

I don't understand. I thought that there was no reporting room in your version?

Also, how do you prove that it's an abuse report without either adding encryption or going through a bot?

> > Yes, my problem is not real abuse reports, it's spam, bullying, etc. through DMs.
> 
> How does this proposal make that any worse? Unless the mod has managed to hide their MXID. If they want to hide their MXID they can still use a bot or simpler forwarder with the simplified proposal.

Let me clarify.

I'm a user on Matrix and also a moderator in some (small rooms). Every so often, I receive a DM. If I'm lucky, that DM is from someone I know or who may have something meaningful to tell me. If I'm unlucky, that DM is spam, random insults, etc. (to be fair, that's not something that has happened to me on Matrix yet, but I've experienced it quite often on IRC).

The default (non-technical) mechanism is to never accept a DM from people I don't know. That's what I do. That's what many users do - I don't know how many, nor will I ever know. Now, with your proposal, as soon as I'm a moderator in one room, I need to accept all DMs, hence expose myself to abuse. That's not something, as a user, I want to do. That's feedback I received on the predecessor of this MSC, which actually sent DMs to moderators, and that feedback was quite convincing.

Do you understand my issue now? While it's not bad enough to be called a security hole, I would qualify this as an "abuse hole".

> > Abuse report is displayed twice, which is a source of confusion.
> 
> I see, so your intention is that the original report is floating around in the mod room, but the clients hide it so that they only see a reformatted version. This seems weird to me. Another option would be using a relation such as "obsoletes" or something that could suggest that the client hides it. (Or maybe provides a link for manual inspection). That would be another MSC but it seems like this MSC would still work fine, the UX can just be improved a bit later.

Well, it's using Matrix as a data communication network, which it is, rather than as a chat network, which it also is :)

> 
> > One of the main points of this MSC is to make abuse reports structured data so that they can be treated by e.g. bots. If the bot formats them instead of forwarding them, we lose much of the interest of the MSC.
> 
> With my proposal the bot could forward both the original report and formatted, it is strictly more flexible than the original as far as I am aware. The customization is left to the report receiver which I find hugely valuable. I'm sure we will see some super powerful ways to handle reports, surely some that don't even involve a Matrix moderation room. This is why I think it is important to keep it flexible.

My point here is that hardcoding the appearance in the client is actually less flexible than letting a bot decide of the appearance.

2021-06-09 21:43 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> a room is the abstraction where several tools (including Matrix clients) can connect, not because it's a place to discuss

I get that. But I think it would be nice if it could also be a place to discuss. Basically allow the mods and users to connect directly and discuss if desired, rather than forcing an intermediary. Again, the intermediary is still allowed, but not required.

This also raises your question about responding to the user. Does the mod team reach out directly? Do we specify a method for the bot to reply? The nice thing about not specifying the bot at all is that it lets different options be tested, multiple people can make bots that work the way they want. If we specify the bot we need to answer all of these questions upfront.

> I believe that we agree that our proposals are mostly equivalent

I agree

> I believe that we agree that our proposals are mostly equivalent - with the notable of exception DM-ing moderators.

Note that my proposal doesn't require the target to be the moderators. It just allows it to be.

> I don't understand. I thought that there was no reporting room in your version?

Let me try to clarify what I understand about your proposal and my proposal.

Yours:

1. Mod Room - This is where the mods live, the users know the ID of this room but can't necessarily join it.
2. Community Room - This is where the users live (and likely the mods too).
3. Reporting Room - This is created to send a report. It contains the reporter and a bot.

Mine:

1 is not specified. It may exist (like when using a forwarding, spam checking, enhancing bot), but the spec doesn't require it.

3 contains the reporter and the list of "targets" which may be one bot, or may be moderator(s) or may be both. This is the key difference in our proposals, I prefer not to specify exactly where reports go and how they are handled to allow various approaches to be evaluated and see which approaches work for which mod teams.

> Well, it's using Matrix as a data communication network, which it is, rather than as a chat network, which it also is :)

That isn't why it is weird to me. It just seems weird to require clients to ignore this data and rely on a bot instead of using this data, but also having the option for a bot to enhance it. But this is a minor point so I think we can ignore it.

> My point here is that hardcoding the appearance in the client is actually less flexible than letting a bot decide of the appearance.

The big difference is how many bots can be used on one mod team. IIUC you can only have one, so the whole team is locked into a style of formatting. If it is done by the client each mod can pick their preferred client. Additional for "small" communities the mods probably wont be bothering to pick their favourite bot so they will just get whatever comes with their homeserver or integration manager (or wherever the bot comes from, it isn't really specified here).

2021-06-11 08:43 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
> > a room is the abstraction where several tools (including Matrix clients) can connect, not because it's a place to discuss
> 
> I get that. But I think it would be nice if it could also be a place to discuss. Basically allow the mods and users to connect directly and discuss if desired, rather than forcing an intermediary. Again, the intermediary is still allowed, but not required.
>
> This also raises your question about responding to the user. Does the mod team reach out directly? Do we specify a method for the bot to reply? The nice thing about not specifying the bot at all is that it lets different options be tested, multiple people can make bots that work the way they want. If we specify the bot we need to answer all of these questions upfront.

I believe that neither proposal solves that scenario, because of the difficulty of trusting DMs. I believe that this deserves its own MSC.

I also believe that both proposal allow for such experimentation (especially since each proposal can easily be extended into the other proposal :) ).

> Let me try to clarify what I understand about your proposal and my proposal.
> 
> Yours:
> 
>     1. Mod Room - This is where the mods live, the users know the ID of this room but can't necessarily join it.
> 
>     2. Community Room - This is where the users live (and likely the mods too).
> 
>     3. Reporting Room - This is created to send a report. It contains the reporter and a bot.
> 
> 
> Mine:
> 
> 1 is not specified. It may exist (like when using a forwarding, spam checking, enhancing bot), but the spec doesn't require it.
> 
> 3 contains the reporter and the list of "targets" which may be one bot, or may be moderator(s) or may be both. This is the key difference in our proposals, I prefer not to specify exactly where reports go and how they are handled to allow various approaches to be evaluated and see which approaches work for which mod teams.

Agreed on the summary.

> > My point here is that hardcoding the appearance in the client is actually less flexible than letting a bot decide of the appearance.
> 
> The big difference is how many bots can be used on one mod team. IIUC you can only have one, so the whole team is locked into a style of formatting. If it is done by the client each mod can pick their preferred client. Additional for "small" communities the mods probably wont be bothering to pick their favourite bot so they will just get whatever comes with their homeserver or integration manager (or wherever the bot comes from, it isn't really specified here).

Good point.

---

1. Unfortunately, I believe that we have reached a stage at which this conversation has stopped progressing. We both have arguments that make sense, we each appreciate the other's arguments, but I feel that continuing this thread will simply block everything.
2. I believe that we agree that both proposals make sense, that both support experimentation and that each proposal may later be amended to essentially become/encompass the other.
3. Specifically, it feels like your proposal may be better suited to small Community Rooms but may need to encompass my proposal to be better suited to large Community Rooms. Conversely, it feels like my proposal may be better suited for large Community Rooms and may need to encompass my proposal to be better suited to small Community Rooms.
4. My first priority is to help deal with the abuse that crops up in large Community Rooms. This is a clear, present and pressing problem.

For these reasons, I believe that continuing work on this MSC more or less as is (i.e. my proposal) does not harm your proposal and should yield clear benefits in terms of both enabling experimentation (including experimentation on your proposal) and aiding the fight against abuse.

Therefore, I'm planning to:
- stop the current conversation (although we may very well continue it on another channel);
- proceed by experimenting on this MSC;
- if experimentation proves successful, remove the "draft" tag and try to move this MSC towards standardization;
- all of this while keeping the door open for a further MSC based on your proposal.

Does this make sense?

2021-06-14 23:37 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
I think the point that you are missing is that I think specing out the "second half" right now of this MSC is (mildly) harmful. I agree that what I am proposing is a subset of yours. But I think that it makes sense to start with that subset.

Most importantly I am still do not see the benefits that you see in specifying the "second half". If there is no benefit of nailing something down in the spec then I think it is best not to specify it to avoid unnecessary restrictions that may come back to bite us down the road.

Would it help if I put forward a stripped down version of this and we can consider deferring this for now?

> each proposal may later be amended to essentially become/encompass the other

It isn't clear that your proposal can be cleanly cut down to the minimal version. Could you clarify roughly the tweaks that you would make? It is just changing the bot name to a MXID or list of MXID?

> My first priority is to help deal with the abuse that crops up in large Community Rooms. This is a clear, present and pressing problem.

Yes, that is why I am suggesting pushing out the "first half". Then you can write the bot and use it for these communities. This looks like the fastest path to me and avoids adding technical debt.

So to be clear this is the plan that I think makes the most sense:

- proceed by pushing the "reporting" half of this MSC.
- Experiment with the bot, solving the problem for these communities.
- If we find reasons why we need to specify the "second half" of this MSC then propose those in another MSC.

Again, if you can specify clear reasons why the MSC would be worse without specifying the behaviour of the bot then I think it can go ahead. But reading back I still don't see any reasons why the bot needs to be specified. I have only see "big communities will need it". That statement may well be true but that doesn't mean that it needs to be specified. My preferred subset allows using a bot, and it may well be the case that all users would use a bot, but unless there is a **downside** to removing the bot from the proposal then I think we should. Simpler is better.

2021-06-18 07:26 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
I'm ok with reducing the MSC to its first half and keeping the second half as an illustration of a possible workflow.

Before experimentation, I'm not ok with specifying that the client must be able to display abuse reports or that we can specify several targets in `moderated_by`.

Does this work for you?

2021-06-18 12:53 UTC, neilmiddleton commented
I have one concern about the reporting process here, mostly around the fact that the reporting process effectively ends up putting the user into a state where we've added them to a room with the bot.  IMHO we should never be changing the state of what the user sees in their own client - that's for them to control.

Thus, one potential alternative is to have the report process via a simple API call which is received by the bot and then posted to the moderation room as per this spec.  A room would already have `m.room.moderated_by`, but we could add `m.room.moderation_endpoint` which defines the domain/path of the reporting service.  This can then be a standardised API.

For instance, room X has `m.room.moderation_endpoint` defined as `moderation.mydomain.org`.  The client receives an abuse report from the user and tries to ping that over to a standard path (for instance, `POST `v1/reports/new`).  Should this service be unavailable the client can retry on an exponential backoff basis until a point where the report is unsuccessful and is killed.

At this point, our API (aka the bot) has a report, and the details listed above so is able to post the report in the correct room.

In theory this also opens us up to being able to support multiple rooms being moderated in one particular room without having the bot join all the moderated rooms, but only the moderation room.

2021-06-18 13:09 UTC, Yoric commented
> I have one concern about the reporting process here, mostly around the fact that the reporting process effectively ends up putting the user into a state where we've added them to a room with the bot. IMHO we should never be changing the state of what the user sees in their own client - that's for them to control.

I agree with the issue.

It may be possible to solve this UX problem through careful client design.

> Thus, one potential alternative is to have the report process via a simple API call which is received by the bot and then posted to the moderation room as per this spec. A room would already have `m.room.moderated_by`, but we could add `m.room.moderation_endpoint` which defines the domain/path of the reporting service. This can then be a standardised API.
> 
> For instance, room X has `m.room.moderation_endpoint` defined as `moderation.mydomain.org`. The client receives an abuse report from the user and tries to ping that over to a standard path (for instance, `POST v1/reports/new`). Should this service be unavailable the client can retry on an exponential backoff basis until a point where the report is unsuccessful and is killed.

Are you assuming that `moderation.mydomain.org` is a Matrix server? If not, authentication becomes a major issue.

Assuming that it is a Matrix server, this still means that we need to rollout yet another federation communication protocol on Matrix. I'm not a big fan of that, as I believe that it tends to increase complexity and reduce reliability.

See [this paragraph](https://github.com/Yoric/matrix-doc/blob/aristotle/proposals/3215-towards-decentralized-moderation.md#alternative-to-the-routing-bot) for a short discussion on a similar idea.

> 
> At this point, our API (aka the bot) has a report, and the details listed above so is able to post the report in the correct room.
> 
> In theory this also opens us up to being able to support multiple rooms being moderated in one particular room without having the bot join all the moderated rooms, but only the moderation room.

FWIW, in the current version of the spec, the bot doesn't need to join the Community Room.

2021-06-18 15:15 UTC, Yoric commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
A few additions:

- I'm currently in the process of experimenting with the current MSC;
- I believe that to make `moderator_of` and `moderated_by` most generic for a MSC v1, their `content` probably shouldn't be specified.

2021-06-18 20:39 UTC, kevincox commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
That sounds good. 

> I'm not ok with specifying that the client must be able to display abuse reports 

Then we can consider things like a fallback with extensible events in the future or mandating the bot. For now we can assume that anyone who ads the metadata has a way to read the reports.

> that we can specify several targets in moderated_by

Can we cut down the middle for now and say that it must be a list of one element? That way we don't need to break the API to allow multiple recipients. What is your objection to allowing multiple? It doesn't seem to cause any issues in my mind.

> I believe that to make moderator_of and moderated_by most generic for a MSC v1, their content probably shouldn't be specified. Rather, it is an agreement between the Community Room, the Moderation Room and the bot and/or client.

That sounds good. We can also consider adding back `moderated_by` as a more opaque attribute if we want that can be a room ID for a bot or whatever else is desired. But for now I think it is fine to prototype without it and see what is actually desired there. Simple is good :)

2021-06-18 20:42 UTC, kevincox commented
I think the room problem is fine. After all not all rooms need to show up in the room list. There are other MSCs that discuss ways to mark the type of rooms such as "abuse report" which could be used to group these rooms away from the regular room list. For now I think we can rely on clients to put these rooms in an appropriate place in the UI.

2021-06-20 15:25 UTC, Yoric commented
> I think the room problem is fine. After all not all rooms need to show up in the room list. There are other MSCs that discuss ways to mark the type of rooms such as "abuse report" which could be used to group these rooms away from the regular room list. For now I think we can rely on clients to put these rooms in an appropriate place in the UI.

Agreed. If we wish for a quick solution, we could drop a state item e.g. (`m.abuse.moderation.request`, "") to mark the room as having been opened to request moderation, then hide such rooms in the UX unless/until there is a response.

2023-03-17 20:24 UTC, Gnuxie commented on proposals/3215-towards-decentralized-moderation.md
> +1. When the Routing Bot is invited to a room, it always accepts invites.
(I'm writing this regardless of the status of the MSC in case it gets picked up again later by someone else, even if that's in another form.)

It would be really useful for the client to give the room a distinct type. Currently in Mjolnir (which has a partial implementation of the routing bot) this behaviour is problematic as it clashes with the `acceptInvitesFromSpace` behaviour and also `protectAllJoinedRooms`. https://github.com/matrix-org/mjolnir/issues/475

2023-06-13 18:06 UTC, heftig commented on proposals/3215-towards-decentralized-moderation.md
> +1. When the Routing Bot is invited to a room, it always accepts invites.
I wouldn't be happy with a solution that requires a bot on my homeserver joining all rooms it's invited into. This seems too abusable. I want my server only participating in rooms that my users explicitly joined.

2024-05-11 19:55 UTC, Kladki commented on proposals/3215-towards-decentralized-moderation.md
> +a higher risk and result in code that is harder to test and trust.
> including message secrecy

From what I can tell this is not currently part of the MSC, but it could be in the future.

On the point against adding another handshake, I am not too sure as to what the problem is, as a certificate is not only not part of the MSC as it currently stands, but arguably isn't that useful, since any bad actor could spam reports for events they can see instead, which doesn't make a big difference to the moderators dealing with it.

Not too sure what the trust and testing part is about though, since there is already a precedent for using handshakes to send state to rooms a server is not a part of, so the code to perform it would likely be not much of a new thing, especially when compared to creating the concept of a routing bot.

2024-05-11 19:57 UTC, Kladki commented on proposals/3215-towards-decentralized-moderation.md
> +        "user_id": XXX, // The bot in charge of forwarding reports to `room_id`.
Having a single bot for routing moderation reports is a clear single point of failure, as if the server running the bot goes down, no moderator from any server will be able to receive reports.

2024-05-20 17:52 UTC, Kladki commented on proposals/3215-towards-decentralized-moderation.md
> +However, this would require implementing yet another new communication protocol based on PDUs/EDUs, including a (small) custom encryption/certificate layer and another retry mechanism. The author bel
The rational for not using a handshake just seems a bit odd:
> this would require implementing yet another new communication protocol based on PDUs/EDUs

The routing bot uses PDUs anyways, since that is what basically all communication is on matrix.

> including a (small) custom encryption/certificate layer

I honestly don't know where this came from, since this was mentioned for mitigating the issues of the routing bot, so it would not be needed otherwise.

> and another retry mechanism.

I would assume that they can just be done in the same way as retries for any other API?

> The author believes that this would entail a higher risk and result in code that is harder to test and trust.

Considering that there is already precedent for handshakes, but none for anything like a routing bot, I would think that the opposite is true.

2024-05-20 19:12 UTC, Gnuxie commented on proposals/3215-towards-decentralized-moderation.md
> +However, this would require implementing yet another new communication protocol based on PDUs/EDUs, including a (small) custom encryption/certificate layer and another retry mechanism. The author bel
The reason for avoiding a handshake can probably be found in the [issues section](https://github.com/matrix-org/matrix-spec-proposals/pull/3215/files#diff-76607abf43ee79fc313922c280513521c80071cd5b68aadf44528dee93844ab5R246-R331) where the author discusses how to avoid deanonymization of reports (against homeservers). 
The PDU templating APIS required by make/send/knock/join will encode the reporter in the PDU.

More context: https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$0fcxVUJT37ZYVDWPuxnYhz8EygbSKEETIDRHlO0m1e0?via=matrix.org&via=envs.net&via=element.io

2024-05-20 19:52 UTC, Kladki commented on proposals/3215-towards-decentralized-moderation.md
> +However, this would require implementing yet another new communication protocol based on PDUs/EDUs, including a (small) custom encryption/certificate layer and another retry mechanism. The author bel
I commented on this part because it was explaining why handshakes were not used over the routing bot. That part more so is about the issues with the routing bot as-is. But yes some upsides of the routing bot are mentioned there as well.

2026-05-13 18:22 UTC, turt2live commented
Taking this over with my T&S hat: we're working on "Reporting v2" which is expected to include many/all of the features of this proposal, but in a different shape. We're closing this in favour of other MSCs in the Reporting v2 area:

* https://github.com/matrix-org/matrix-spec-proposals/pull/4457
* https://github.com/matrix-org/matrix-spec-proposals/pull/4468
* https://github.com/matrix-org/matrix-spec-proposals/pull/4456
* etc

The (believed unused) feature is removed from Element Web in https://github.com/element-hq/element-web/pull/33492

2026-05-13 18:22 UTC, closed without merging