Correct 'once-off' to 'one-off'
matrix-org/matrix-doc pull request #3228
Opened 2021-06-01 10:10 UTC by ilovecommits

2021-06-02 22:47 UTC, kevincox approved these changes

2021-06-16 01:38 UTC, turt2live requested changes
can we get more detail as to why this change is needed? As far as I can tell, this is equivalent and `once-off` may best represent the semi-transient nature of message events.

2021-06-16 08:32 UTC, ilovecommits commented
> can we get more detail as to why this change is needed? As far as I can tell, this is equivalent and `once-off` may best represent the semi-transient nature of message events.

One-off is the intended meaning. I initially thought it's a typo or a grammar mistake, but it turns out that once-off is an actual financial term. However, it doesn't match the context.

Perhaps there are regional differences, but I've never seen 'once-off' being used as an equivalent of 'one-off'. There are 46 million results for 'one-off' and only 3.5 million for 'once-off' on Google.

2021-06-23 01:39 UTC, turt2live approved these changes

2021-06-23 01:39 UTC, merged