Use format: uri
matrix-org/matrix-doc pull request #3236
Opened 2021-06-10 20:02 UTC by lukaslihotzki

Fix #3235

2021-07-30 10:24 UTC, lukaslihotzki commented
@turt2live, @KitsuneRal: Can you review this?

2021-08-05 21:54 UTC, turt2live approved these changes
otherwise looks good - thanks!

2021-08-05 21:54 UTC, turt2live commented on changelogs/client_server/newsfragments/3236.clarification
> +Use uri format in avatar_url, pusher url, wellknown base_url, getUrlPreview, and submit_url.
We don't actually have a changelog for the swagger, so this PR is fine to exclude the entry.

2021-08-07 19:18 UTC, KitsuneRal requested changes
While updating libQuotient to the code generated from this PR I found this place needs `format: uri` too: https://github.com/matrix-org/matrix-doc/pull/3236/files#diff-290a7b6086f893635e8372140dfde8ca9ab1040e07cfa2bc0c50c14e7feb8879R67

2021-08-08 16:20 UTC, lukaslihotzki commented
@KitsuneRal: Which place needs `format: uri` too? The link points to data/api/client-server/definitions/public_rooms_response.yaml, line 67, which is the `guest_can_join` boolean property.

2021-08-09 06:16 UTC, KitsuneRal commented
> @KitsuneRal: Which place needs `format: uri` too? The link points to data/api/client-server/definitions/public_rooms_response.yaml, line 67, which is the `guest_can_join` boolean property.

Huh, that's not what it was supposed to point to. The piece in question is in `data/api/client-server/content-repo.yaml` around line 67 - the `content_uri` field returned by `/upload`.

2021-08-09 15:36 UTC, KitsuneRal approved these changes

2021-08-09 15:41 UTC, merged