Rename assets-hugo directory to assets
matrix-org/matrix-doc pull request #3259
Opened 2021-06-29 17:25 UTC by anoadragon453

Now that we've dropped the old build pipeline (and an `assets` directory does not exist in the repo any longer, we can rename the hugo version of the assets (`assets-hugo`) created during the build tools migration back to simply `assets`.

2021-06-29 17:25 UTC, anoadragon453 commented on config.toml
> -assetDir = "assets-hugo"
The default for `assetDir` is "assets": https://gohugo.io/getting-started/configuration/#all-configuration-settings

2021-08-03 16:20 UTC, richvdh requested changes
looks fine, but we should probably remove `scripts/generate-matrix-org-assets` at the same time?

2021-11-17 12:56 UTC, richvdh commented
@anoadragon453 is this still on your radar?

2021-11-17 12:57 UTC, anoadragon453 commented
Yes, just a tuit.

2021-12-30 17:00 UTC, afranke commented
> looks fine, but we should probably remove `scripts/generate-matrix-org-assets` at the same time?

Just saw this. Already removed as part of b55cc15772c162dd7bcc1c6d59035d89601fb1f8

2022-01-04 17:38 UTC, richvdh commented
@afranke shall we just merge this then?

2022-01-05 08:44 UTC, afranke commented
Actually no, we shan’t. The [build-openapi step makes an archive of the `assets` directory](https://github.com/matrix-org/matrix-doc/blob/dfec7d687ee9e0ae507b9eee4b44af70ffd56d2c/.github/workflows/main.yml#L80) and uploads that as artifact, expecting it to contain only the generated definition. One would need to tweak the workflow first so it uses another directory name for that job.

Considering the branch here does not include these changes to the workflow, and Github does not like rebases, I’ll create another PR to do that and it should be reviewed and merged before this one gets merged.

2022-01-06 08:39 UTC, afranke approved these changes
With #3621 merged, I reckon this is good to go now.

2022-01-06 10:34 UTC, merged