Clarify why a specific hostname is expected in the server certificate
matrix-org/matrix-doc pull request #3322
Opened 2021-08-09 09:20 UTC by nielsbasjes

My proposed clarification for
https://github.com/matrix-org/matrix-doc/issues/3321

2021-08-09 12:29 UTC, richvdh requested changes
Thanks for the contribution! I've made some suggestions for clarification/accuracy below.

@turt2live: I'm afraid I'm unclear as to whether minor background information points like this need a changelog entry. WDYT?

2021-08-09 12:29 UTC, richvdh commented on content/server-server-api.md
> +proves via TLS it is truly a delegate for `<hostname>`.
```suggestion
The reasons we require `<hostname>` rather than `<delegated_hostname>` for SRV
delegation are:
  1. DNS is insecure (not all domains have DNSSEC), so the target of the delegation
      must prove that it is a valid delegate for `<hostname>` via TLS.
  2. Consistency with the recommendations in [RFC6125](https://datatracker.ietf.org/doc/html/rfc6125#section-6.2.1) 
     and other applications using SRV records such [XMPP](https://datatracker.ietf.org/doc/html/rfc6120#section-13.7.2.1).
```

2021-08-09 12:29 UTC, richvdh commented on content/server-server-api.md
> +proves via TLS it is truly a delegate for `<hostname>`.
Also, put the whole thing in a `{{% boxes/note %}}` box, in the same way as is used elsewhere in the document?

2021-08-09 13:23 UTC, nielsbasjes commented on content/server-server-api.md
> +proves via TLS it is truly a delegate for `<hostname>`.
Yes, I'll update it.

2021-08-09 14:28 UTC, richvdh approved these changes
lgtm otherwise!

2021-08-09 14:28 UTC, richvdh commented on .gitignore
> +*.iml
what's an iml?

2021-08-09 14:44 UTC, nielsbasjes commented on .gitignore
> +*.iml
The project file created by intelliJ

2021-08-09 14:51 UTC, nielsbasjes commented on .gitignore
> +*.iml
It is closely related to the .idea directory also in there.

2021-08-09 14:54 UTC, richvdh commented on .gitignore
> +*.iml
right - doesn't intelliJ put all its files under `.idea`? I've never needed a separate `.iml` gitignore.

2021-08-09 14:58 UTC, turt2live commented
(we also need sign-off per the contributing guidelines. Easiest way is to leave a `Signed-off-by: Your Name <email@example.org>` comment here, but the full range of options are described in the guidelines)

2021-08-09 16:23 UTC, penn5 commented on .gitignore
> +*.iml
You don't need a .iml and IntelliJ have said it's not preferable in many cases. But there are specific files that _do_ need to be excluded from .idea.

2021-08-09 17:46 UTC, nielsbasjes commented
Signed-off-by: Niels Basjes <niels@basjes.nl>

2021-08-10 09:08 UTC, nielsbasjes commented on .gitignore
> +*.iml
Ok, I'll remove this from my patch.

2021-08-10 09:40 UTC, richvdh commented on .gitignore
> +*.iml
@penn5 I don't understand. What do you mean by "you don't need a `.iml`"? And given we're excluding the whole `.idea` directory, what do you mean by " there are specific files that do need to be excluded from .idea."

2021-08-10 10:09 UTC, penn5 commented on .gitignore
> +*.iml
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

2021-08-10 11:51 UTC, richvdh approved these changes
thanks very much!

2021-08-10 11:51 UTC, merged