Add m.login.appservice to the spec
matrix-org/matrix-doc pull request #3324
Opened 2021-08-09 21:52 UTC by Half-Shot

[Proposal doc](https://github.com/matrix-org/matrix-doc/blob/master/proposals/2778-appservice-login.md)

2021-08-10 17:02 UTC, richvdh requested changes
I think you've put all this in the wrong section. MSC2778 doesn't specify a UIA authentication type, but rather a modification to the `/login` endpoint (which doesn't use UIA). It should be in this section: https://spec.matrix.org/unstable/client-server-api/#login.

2021-08-16 08:27 UTC, Half-Shot commented
Sorry, my mistake. I homed in on the thing that looked like login types without thinking.

I've moved and reworked the section to hopefully make it fit better with `/login`.

2021-08-16 13:26 UTC, richvdh requested changes
Thanks, looks better now. A few nits.

Would it be helpful to add a link from the appservice spec?

2021-08-16 13:26 UTC, richvdh commented on content/client-server-api/_index.md
> +can perform [Identity Assertion](http://localhost:1313/application-service-api/#identity-assertion)
link looks wrong

2021-08-16 13:26 UTC, richvdh commented on content/client-server-api/_index.md
> +
```suggestion
```

2021-08-16 13:26 UTC, richvdh commented on content/client-server-api/_index.md
> +not exist within it's namespace then the homeserver will respond with an
```suggestion
not exist within its namespace then the homeserver will respond with an
```

2021-08-16 13:26 UTC, richvdh commented on content/client-server-api/_index.md
> +not exist within it's namespace then the homeserver will respond with an
```suggestion
If the access token does correspond to an appservice, but the user id does
not lie within it's namespace then the homeserver will respond with an
```

2021-08-16 13:26 UTC, richvdh commented on changelogs/client_server/newsfragments/3324.feature
> +Add support for m.login.appservice, as per [MSC2778](https://github.com/matrix-org/matrix-doc/pull/2778).
```suggestion
Extend `/_matrix/client/r0/login` to accept a `m.login.appservice`, as per [MSC2778](https://github.com/matrix-org/matrix-doc/pull/2778).
```

2021-11-04 16:08 UTC, turt2live commented
@Half-Shot do you have bandwidth to update this?

2021-11-05 08:18 UTC, Half-Shot commented
My bandwidth is in the negatives atm

2021-11-05 15:14 UTC, turt2live commented
Would you be opposed to this being taken over to get it over the line?

2021-12-28 20:09 UTC, uhoreg commented on content/client-server-api/_index.md
> +A appservice can login by providing a valid appservice token and a user within the appservice's
```suggestion
An appservice can log in by providing a valid appservice token and a user within the appservice's
```

2021-12-28 20:09 UTC, uhoreg commented on content/client-server-api/_index.md
> +can perform [Identity Assertion](http://localhost:1313/application-service-api/#identity-assertion)
```suggestion
can perform [Identity Assertion](../application-service-api#identity-assertion)
```

2021-12-28 20:09 UTC, uhoreg commented on content/client-server-api/_index.md
> +Appservices do not need to login as individual users in all cases, as they
```suggestion
Appservices do not need to log in as individual users in all cases, as they
```

2021-12-28 21:11 UTC, turt2live approved these changes
otherwise lgtm - thanks!

2021-12-28 21:11 UTC, turt2live commented on content/client-server-api/_index.md
> +This request must be authenticated by the [appservice `as_token`](../application-service-api#registration)
```suggestion
This request must be authenticated by the [appservice `as_token`](/application-service-api#registration) 
```

2021-12-28 21:15 UTC, uhoreg commented on content/client-server-api/_index.md
> +can perform [Identity Assertion](../application-service-api#identity-assertion)
```suggestion
can perform [Identity Assertion](/application-service-api#identity-assertion)
```

2021-12-28 21:16 UTC, merged