dump-swagger.py: include untagged operations
matrix-org/matrix-doc pull request #3326
Opened 2021-08-10 08:15 UTC by lukaslihotzki

These operations are untagged and therefore currently not included in scripts/swagger/api-docs.json:
- requestTokenTo3PIDEmail
- requestTokenTo3PIDMSISDN
- requestTokenToResetPasswordEmail
- requestTokenToResetPasswordMSISDN
- getRoomVisibilityOnDirectory
- setRoomVisibilityOnDirectory
- peekEvents
- uploadCrossSigningKeys
- uploadCrossSigningSignatures
- redirectToSSO
- redirectToIdP
- requestTokenToRegisterEmail
- requestTokenToRegisterMSISDN
- deleteRoomKeysKeyRoomId
- getRoomKeysKeyRoomId
- deleteRoomKeysKeyRoomId
- getRoomKeysKeyRoomId
- deleteRoomKeysKeyRoomIdSessionId
- getRoomKeysKeyRoomIdSessionId
- queryLocationByAlias
- queryLocationByProtocol
- getProtocolMetadata
- getProtocols
- queryUserByID
- queryUserByProtocol

Is this intentional? If not, please merge this PR.

2021-08-10 12:47 UTC, KitsuneRal requested changes
I appreciate the direction but it would be even better to see these operations tagged. There's no API intentionally "hidden" from Swagger (at least I never heard of such intentions); and dumping these operations without categories puts things as diverse as 3pid operations and cross-signing in a single `default` group in Swagger viewer.

And once all the operations are tagged, this particular code in `dump-swagger.py` should probably complain about untagged operations, instead of skipping over them.

2021-08-10 17:35 UTC, lukaslihotzki commented
#3329 is the first step suggested.

2021-12-30 15:52 UTC, afranke commented
@lukaslihotzki any chance you implement the second suggested step?

2022-01-04 17:21 UTC, richvdh commented
Is there a reason we shouldn't merge this PR as-is? If not, let's do so. If so, let's close it so someone can make a better solution.

2022-01-04 17:41 UTC, KitsuneRal commented
After #3326 there don't seem to be many untagged operations remaining. I guess it's fine to merge this PR and then tag them whenever someone feels like doing that.

2022-01-04 17:41 UTC, KitsuneRal approved these changes

2022-01-04 18:27 UTC, afranke approved these changes

2022-01-04 18:31 UTC, merged