Port CI to Github Actions
matrix-org/matrix-doc pull request #3363
Opened 2021-08-25 13:22 UTC by afranke

This is intended to replace the existing Buildkite one, but the latter can be removed at a latter point when all the bits are in place. The workflow can be seen working for the gh-actions branch at [the Actions tab](https://github.com/matrix-org/matrix-doc/actions).

2021-08-30 09:52 UTC, afranke commented on .github/workflows/main.yml
> +on: [push, pull_request]
Fixed.

2021-08-30 11:49 UTC, afranke commented on .github/workflows/main.yml
> +    name: "👷 Rebuild matrix.org"
I went ahead and amended the PR with a condition so that it only runs on `main`.

2021-08-31 16:31 UTC, anoadragon453 requested changes

2021-08-31 16:31 UTC, anoadragon453 commented on .github/workflows/main.yml
> +    branches: master
The `master` branch has been renamed to `main` https://github.com/matrix-org/matrix-doc/issues/3367

2021-08-31 16:31 UTC, anoadragon453 commented on .github/workflows/main.yml
> +    branches: master
Also: Does the value of `branches` need to be an array rather than a string?

2021-08-31 16:31 UTC, anoadragon453 commented on .github/workflows/main.yml
> +  build-spec:
As a stylistic choice, I often separate separate jobs from each other through a newline, just for readability. The same goes for putting a newline above the `jobs:` and `rebuild-matrixdotorg` keys.

2021-09-01 10:30 UTC, richvdh commented on .github/workflows/main.yml
> +    branches: master
> Also: Does the value of `branches` need to be an array rather than a string?

It's happy with either, iirc.

2021-09-01 10:34 UTC, richvdh commented on .github/workflows/main.yml
> +  pull_request:
I've noticed it's useful to include a `workflow_dispatch` trigger, to let you run the workflow manually:

```suggestion
  push:
    branches: master
  pull_request:
  workflow_dispatch:
```

(cf https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch)

2021-09-01 10:36 UTC, richvdh commented on .github/workflows/main.yml
> +      - name: "🪄 Triggering rebuild of matrix.org"
probably need a different emoji, this one doesn't render for me

2021-09-01 10:47 UTC, richvdh commented on .github/workflows/main.yml
> +    if: ${{ github.event_name == 'push' && github.ref == 'refs/head/main' }}
it might be worth disabling this until we land https://github.com/matrix-org/matrix.org/pull/1063, so that it completes successfully:

```suggestion
    if: ${{ false && github.event_name == 'push' && github.ref == 'refs/head/main' }}
```

2021-09-01 15:26 UTC, afranke commented on .github/workflows/main.yml
> +    branches: master
[Documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) isn’t explicit about what is expected here, unlike for [`on`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on) where it clearly says it can be “a single event string, array of events, array of event types, or an event configuration map”.

Since the name is plural (branch*es*), and all examples use arrays (even when there is only one item), I switched to an array.

2021-09-01 15:27 UTC, afranke commented on .github/workflows/main.yml
> +  build-spec:
Done.

2021-09-01 15:31 UTC, afranke commented on .github/workflows/main.yml
> +      - name: "🪄 Triggering rebuild of matrix.org"
😞 It’s a magic wand.

Any suggestions?

2021-09-02 08:35 UTC, richvdh commented on .github/workflows/main.yml
> +      - name: "🪄 Triggering rebuild of matrix.org"
:man_shrugging: I don't think it matters. may as well leave it.

2021-09-02 14:53 UTC, afranke commented on .github/workflows/main.yml
> +    if: ${{ github.event_name == 'push' && github.ref == 'refs/head/main' }}
Done in 3beafefbc2aa77364fa9ff30212c50a1063de877

2021-09-02 15:47 UTC, richvdh approved these changes

2021-09-02 15:48 UTC, merged