[WIP] Polls (mk II)
matrix-org/matrix-doc pull request #3381
Opened 2021-09-07 03:54 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-doc/blob/travis/msc/polls/proposals/3381-polls.md)

Implementation: TBD

2021-09-07 04:00 UTC, turt2live commented on proposals/3381-polls.md
> +to react to polls while also aggregating poll responses.
This is probably a blocker for this MSC: while writing this I was increasingly convinced that `m.reference` is wrong and that poll responses should be aggregated by the server. The poll closure should still be a reference though.

2021-09-07 20:26 UTC, kevincox requested changes

2021-09-07 20:26 UTC, kevincox commented on proposals/3381-polls.md
> +truncate the list at no less than 20. Similarly, there is no minimum though a poll of zero or one options
A poll of 1 option is a counter which may be useful. This is basically a yes/no poll but the no option is considered uninteresting. For example.

I am ordering wings at 20:00 tonight. Let me know if you want one before then:
1. I'm in!

Sure, there could be a "No thanks" option but it really isn't necessary. If you haven't responded by 20 you aren't getting wings.

Another use case is extensible polls where you encourage the pollees to add options. you may pose a question with 0 or 1 options and allow users to add their own.

TL;DR I think we should encourage clients to support 1. 0 is likely useful if adding options is supported.

2021-09-07 20:26 UTC, kevincox commented on proposals/3381-polls.md
> +### Secret polls
See also https://github.com/matrix-org/matrix-doc/pull/3184 which proposes making truly secure secret polls. It is honestly simple enough that I think we should implement it. People will be surprised that people can see their responses before they are revealed and we should not leak data that people don't expect.

2021-09-07 20:26 UTC, kevincox commented on proposals/3381-polls.md
> +## Alternatives
I think this is missing two critical features.

1. Support for pollees adding entries. I frequently start a poll with a few options and ask people to add other things that they think of. The proposed index-based choice selection doesn't work well with this use case.
2. Multiple choices. This could likely be retrofitted later, but it would probably be cleaner to make `response` an array now to avoid having the difference in the future.

2021-09-07 20:31 UTC, turt2live commented on proposals/3381-polls.md
> +truncate the list at no less than 20. Similarly, there is no minimum though a poll of zero or one options
This sounds like reactions, not polls.

2021-09-07 20:33 UTC, turt2live commented on proposals/3381-polls.md
> +### Secret polls
The proposal there still doesn't meet the criteria of secret that a user would expect. Will expand upon this in the alternatives in a future edit.

2021-09-07 20:34 UTC, turt2live commented on proposals/3381-polls.md
> +## Alternatives
Both of these are explicitly out of scope of this MSC for inclusion by another.

2021-09-07 21:23 UTC, kevincox commented on proposals/3381-polls.md
> +truncate the list at no less than 20. Similarly, there is no minimum though a poll of zero or one options
You could use a reaction, you could use a poll for the listed use case. But either way I wouldn't want to encourage clients to ignore these. Users will expect it to work.

2021-09-07 21:25 UTC, kevincox commented on proposals/3381-polls.md
> +## Alternatives
I think they should be in-scope because they are easy to add now and would be complex to add later. I would rather make this MSC slightly larger and include these features rather than have 4 poll protocols depending on if you want multiple choices, user-added events or both.

2021-09-07 21:36 UTC, turt2live commented on proposals/3381-polls.md
> +truncate the list at no less than 20. Similarly, there is no minimum though a poll of zero or one options
I'm not convinced, honestly. The user research backing this proposal doesn't have a case for single-option polls. Clients are of course still welcome to render single-option polls, but without strong argument the MSC isn't going to propose that they do.

2021-09-07 21:39 UTC, turt2live commented on proposals/3381-polls.md
> +## Alternatives
Things that are easy to add make MSCs take longer to land and validate. It's much more important to validate the concept of the system with a minimum feature set and expand upon it later. This MSC is just the bare framework for future poll structures, including multi-response (which would have fallback support) and multi-user edits (which is technically a thing under the edits and aggregations MSC, but clients don't render cross-user edits for security reasons). We'd still have 1 poll protocol in the end.

2021-09-07 22:46 UTC, kevincox commented on proposals/3381-polls.md
> +truncate the list at no less than 20. Similarly, there is no minimum though a poll of zero or one options
I also don't remain convinced that it is easy to add later.

For multi-user edits I don't think you would want to allow cross-user edits, instead you would just add a related event that includes a new item. However in this case using indexes isn't a good option because of the concurrency issues for adding items. Therefore this proposal becomes unhelpful since we need a new addressing mechanism. If instead this proposal included IDs for each element and clients referenced that (they could be a simple string integer for now) I would be happy enough that editing the entries would work well in the future.

In fact I even now realize that indexes are not enough to handle owner-edits so this should probably be updated in this MSC anyways, and will likely solve my concern for non-owner edits. I'll open a new thread about this.

As for multiple options I don't think that it gracefully degrades. If my client selects two options and some users only see one that is a significant problem. I would rather spec out multiple responses from the get-go seeing how trivial it is.

2021-09-07 22:47 UTC, kevincox commented on proposals/3381-polls.md
> +      "answer": 2 // index of the answers array selected (zero-indexed)
The index is not a good enough identifier of the element to select in the face of edits. Instead each element in the poll should be assigned an ID. This will allow adding and removing options without changing the meaning of users' votes.

2021-09-07 22:48 UTC, kevincox commented on proposals/3381-polls.md
> +until the poll is closed. In chat, these are typically used for quick questionares such as what to
I assume that not all polls will be closed. It is probably better to indicate that they "may" be closed.

2021-09-07 23:02 UTC, turt2live commented on proposals/3381-polls.md
> +until the poll is closed. In chat, these are typically used for quick questionares such as what to
I think this is implied.

2021-09-07 23:02 UTC, turt2live commented on proposals/3381-polls.md
> +truncate the list at no less than 20. Similarly, there is no minimum though a poll of zero or one options
looks like the above was meant as a reply to https://github.com/matrix-org/matrix-doc/pull/3381#discussion_r703862352 (a different thread).

2021-09-07 23:06 UTC, turt2live commented on proposals/3381-polls.md
> +## Alternatives
re https://github.com/matrix-org/matrix-doc/pull/3381#discussion_r703902809

Indexes are indeed unsafe for editable options: IDs are the way to go. Was hoping to avoid it, but it's just not going to happen.

2021-09-07 23:08 UTC, turt2live commented on proposals/3381-polls.md
> +## Alternatives
As for multiple options: the fallback isn't great, but the MSC is extremely clear that polls aren't for serious usage. Further, we can aim to have MSCs land at roughly the same time to avoid clients having to implement the fallback, though first we need SCT review and proven implementation on the poll structure referenced here to avoid wasting everyone's time.

2021-09-07 23:23 UTC, kevincox commented on proposals/3381-polls.md
> +truncate the list at no less than 20. Similarly, there is no minimum though a poll of zero or one options
You are correct. I'll delete and repost to clean up the thread.

2021-09-07 23:24 UTC, kevincox commented on proposals/3381-polls.md
> +## Alternatives
Even if they aren't for "serious usage" I think it is still important to avoid misrepresenting users as that causes confusion.

2021-09-10 21:25 UTC, 0x1a8510f2 commented on proposals/3381-polls.md
> +poll was closed, but timestamped for when it was open, the server is violating a social contract and likely
While this is obviously a low-security feature, this part almost feels like an invite. I'm worried that such gaps could prompt people to think that Matrix is insecure.

As a simple solution, the end event could contain a list of accepted votes' event IDs. That way, there is a single source of truth as to the results of the poll. Non-existent votes cannot be added because all the same validation would still apply to the linked events. Valid votes can be omitted, but that is a lesser evil in this case, than theoretically allowing anyone to add votes.

The only real problem I can see with this is that the end event grows linearly in size with the amount of voters. This could be solved though, by uploading the list as a file, but I'm not sure I like this solution. Perhaps someone has a better idea.

2021-09-10 22:31 UTC, turt2live commented on proposals/3381-polls.md
> +of whether or not they've voted. This is enforced visually and not by the protocol given the votes
It fixes one of the issues, but not enough of the concerns to be worth the technical effort. If we are going as far as hiding the results, we should go as far as hiding the senders too.

2021-09-10 22:34 UTC, turt2live commented on proposals/3381-polls.md
> +poll was closed, but timestamped for when it was open, the server is violating a social contract and likely
Centralizing the end of the poll is bound to cause problems and trust issues (excluded votes, etc). Instead, I'd very much like to keep social problems out of the spec: people who maliciously affect rooms should not be in those rooms.

2021-09-11 17:08 UTC, kevincox commented on proposals/3381-polls.md
> +
The more I think about it I don't think the "Secret Polls" feature should be added. The Matrix slogan is "An open network for secure, decentralized communication" and I think we should stick to that. We should avoid implementing features which could reasonably be implemented securely insecurely. We can't expect users to understand the actual security of the underlying implementation and something as simple as leaking the vote for a secret poll strikes me as completely unacceptable.

I think the open polls is fine as is, but I think we should refrain from launching the secret polls until we have a properly secure implementation.

2021-09-11 20:28 UTC, 0x1a8510f2 commented on proposals/3381-polls.md
> +of whether or not they've voted. This is enforced visually and not by the protocol given the votes
I thought about this for a while and, to the best of my knowledge, it would be simply impossible to make this anonymous with how Matrix works today. There are the following along with their caveats:

- Votes could be uploaded as files. Files are not mapped to a user so this would be anonymous. However, users could vote an unlimited number of times, fetching votes would be inefficient, and finally, this would require that everyone can find the file without a link to it being sent in chat; this could be achieved by giving Matrix the concept of directories for files where those files could be uploaded, but that would be very far out of the scope of this MSC.
- Users would pass their votes to other users who would send them, a little like TOR. This would be quite inefficient, unreliable and difficult to implement. Also very out of scope of this MSC.

Despite this, I still think we shouldn't compromise every desirable property because we can't achieve them all. As described in the MSC, the UI should inform the user that polls are not anonymous. Meanwhile, in the case of secret polls, the UI is actively misleading which should not be the case IMO.

2021-09-11 23:46 UTC, 0x1a8510f2 commented on proposals/3381-polls.md
> +poll was closed, but timestamped for when it was open, the server is violating a social contract and likely
>I'd very much like to keep social problems out of the spec

I agree, but I don't think this is any more of a social problem than spam is, and the latter is being dealt with within the spec in the form of [relative reputation](https://matrix.org/blog/2020/10/19/combating-abuse-in-matrix-without-backdoors).

Looking out for events with faked timestamps is a lot to expect from moderators, especially in public/open rooms.

My proposed solution is far from ideal, but it reduces the need to trust the entire room into the need to trust a single person.

2021-09-12 00:08 UTC, turt2live commented on proposals/3381-polls.md
> +
This is highly unlikely to end up in the main spec and would more or less fall into some sort of auxiliary, but official, place where features are optional for clients to implement. This sort of thing has no business in the main spec, much like how message pinning doesn't (but is, because 2017 is a different year).

2021-09-12 00:21 UTC, turt2live commented on proposals/3381-polls.md
> +of whether or not they've voted. This is enforced visually and not by the protocol given the votes
It is indeed presently impossible to implement fully, but I do have a strong feeling that the same system that gives us anonymized events will give us anonymized responses to polls too. Waiting for that system isn't completely reasonable given it'll be a while, so to maintain a competitive advantage (and decent bridging experience) the feature is proposed here. 

I'm not entirely sold on the idea that it's misleading (given it still requires fairly technical understanding to bypass the UI), though if there's a relatively easy technical answer then we should do it.

2021-09-12 00:26 UTC, turt2live commented on proposals/3381-polls.md
> +poll was closed, but timestamped for when it was open, the server is violating a social contract and likely
Spam isn't a social issue though, it's a technical one (particularly around how to build mechanics to reduce the chances of spam like rate limiting and size restrictions). The social issue here is that the natural conversation of the room following a poll closure will be around the results, thus validating and solidifying those answers. Modifications after the fact would be extremely obvious given the results would not match the conversation, raising suspicion. 

If we wanted to make it a more technical problem to reduce the load on moderators (which I'm not convinced is very high given the technical difficulty of modifying the timestamp and injecting events) then a moderation bot like Mjolnir could be written to support a more overarching poll state machine to ban bad actors, or redact their responses.

2021-09-14 16:32 UTC, uhoreg commented on proposals/3381-polls.md
> +
There's also an issue with interactions with edits.  e.g. if the poll originally says "What should we order for the party?" and then the poll creator edits it to say "What food should we ban?".  This would also fall under the "don't use polls for serious things" umbrella.

2021-09-14 16:39 UTC, uhoreg commented on proposals/3381-polls.md
> +### Secret polls
It might help if it was called something other than "secret", as I think "secret" implies something that this isn't trying to do.  I don't know if I have a better suggestion, though.  "Hidden" might be a bit better, but still doesn't seem quite right.

2021-09-14 17:07 UTC, 0x1a8510f2 commented on proposals/3381-polls.md
> +poll was closed, but timestamped for when it was open, the server is violating a social contract and likely
Perhaps I misunderstood what you meant by a social issue then.

In any case, I guess this isn't as much of an issue as I initially thought seeing as, even with faked timestamps, everyone would still only get one vote and would still have to follow all the other rules, they would just get to vote after the poll closed.

Overall, you're probably right and this is fine to leave as is. My main concern is simply that someone will notice this and assume it's a security flaw; then label Matrix as insecure.

2021-09-14 17:32 UTC, 0x1a8510f2 commented on proposals/3381-polls.md
> +of whether or not they've voted. This is enforced visually and not by the protocol given the votes
>the same system that gives us anonymized events will give us anonymized responses to polls too

Is that currently being worked on? If so, would you be able to point me towards some more information? It sounds quite interesting.

>I'm not entirely sold on the idea that it's misleading (given it still requires fairly technical understanding to bypass the UI)

I don't think this is particularly technical at all. Element provides a means to show hidden events. All one would need to do is enable that option and inspect votes at any time they like. Not even any client modification would be necessary.

This could be seen as non-misleading if the option is presented well in the UI; for instance, selecting a secret poll would be presented to the user as "hide results until poll is closed (complying clients only)" instead of "make poll secret until closed", but that's up to clients and I'm fairly certain that many clients will present it in a misleading way. Using `m.secret` instead of `m.hidden`, for example, also hints at this being more secure than it is.

>if there's a relatively easy technical answer then we should do it

My original suggestion with attaching a public key to the poll is an easy technical solution. Any solution which prevents the sender of the poll from seeing the replies would require either follow-up events to be sent by voters after the poll closes or support from homeservers, both of which have more downsides than upsides. Meanwhile, the fact that the sender of the poll can see results is not much of a problem since they decide when results are revealed anyway.

As an example of what I mean, based on examples from the MSC:

Poll start:
```
{
  "type": "m.poll",
  "sender": "@alice:example.org",
  "content": {
    "m.poll": {
      "question": {
        "m.text": "What should we order for the party?"
      },
      "kind": "m.secret",
      "secret_pubkey": "<PUBLIC_KEY>", // ADDED
      "answers": [
        { "m.text": "Pizza 🍕" },
        { "m.text": "Poutine 🍟" },
        { "m.text": "Italian 🍝" },
        { "m.text": "Wings 🔥" }
      ],
    },
    "m.message": [
      {
        "mimetype": "text/plain",
        "body": "What should we order for the party?\n1. Pizza 🍕\n2. Poutine 🍟\n3. Italian 🍝\n4. Wings 🔥"
      },
      {
        "mimetype": "text/html",
        "body": "<b>What should we order for the party?</b><ol><li>1. Pizza 🍕</li><li>2. Poutine 🍟</li><li>3. Italian 🍝</li><li>4. Wings 🔥</li></ol>"
      }
    ]
  },
  // other fields that aren't relevant here
}
```

Poll end:
```
{
  "type": "m.poll.end",
  "sender": "@bob:example.org",
  "content": {
    "m.relates_to": {
      "rel_type": "m.reference", // from MSC2675: https://github.com/matrix-org/matrix-doc/pull/2675
      "event_id": "$poll"
    },
    "m.poll.end": {
      "secret_privkey": "<PRIVATE_KEY>" // ADDED
    },
    "m.text": "The poll has ended. Top answer: Poutine 🍟"
  },
  // other fields that aren't relevant here
}
```

2021-09-14 17:33 UTC, dbkr commented on proposals/3381-polls.md
> +A poll can be started by sending an `m.poll` room event, similar to the following:
Should we be worried about polls that started long enough ago that clients haven't scrolled back far enough to see them? This seems like it could be quite a common use case, and also seems like what state events are for?

2021-09-14 17:33 UTC, dbkr commented on proposals/3381-polls.md
> +Only the poll creator can close a poll. It is done as follows:
This feels a bit limiting perhaps? Since this is not a thing intended for high security, I'd be tempted to maybe go the other way and just allow anyone with permission to send the event to end the poll? (Especially if it's a state event).

2021-09-14 17:33 UTC, dbkr commented on proposals/3381-polls.md
> +including from TravisR, Matthew, and Alice" before the user votes.
Honestly I'd probably also suggest clients make the list of who voted for what available to everyone too. If the information is available anyway, hiding it just feels misleading.

2021-09-14 17:33 UTC, dbkr commented on proposals/3381-polls.md
> +## Alternatives
I'm not too sure what would justify these being critical features.

2021-09-14 17:33 UTC, dbkr commented on proposals/3381-polls.md
> +
Is there active demand for the secret poll stuff? It does, again, feel misleading to artificially hide information when it's readily available. Leaving it as a relatively simple thing which effectively just has open polls seems appealing.

2021-09-30 15:45 UTC, TeFiLeDo commented on proposals/3381-polls.md
> +      "answer": 2 // index of the answers array selected (zero-indexed)
I think this should be an array, so users can select multiple answers. An empty array would signal that a user wants to "un-vote", while invalid values would simply be ignored.

The `m.poll` event also should specify wether multiple choice is allowed and, if not, clients should only count the first valid value of the `answers` array.

An example use case of that would be negotiating a restaurant for dinner with a group of friends. Instead of _"What restaurant to you want to go to?"_ one could then ask _"What restaurants are you ok with?"_ and go to the one that most people think is acceptable.

2021-11-04 08:28 UTC, jfowl commented
I don't have deep knowledge about the spec as a whole, so please excuse if this is redundant:

What about lenght limits for the fields? e.g. id and answer? I can imagine, that this could break something clientside.

2021-11-04 17:54 UTC, turt2live commented
@jfowl Opening line comments on the diff are best so feedback can be captured and responded to.

Length limits aren't yet in this MSC, but should be before it's ready for FCP.

2021-11-04 20:06 UTC, jfowl commented on proposals/3381-polls.md
> +
_As pointed out by @turt2live I am leaving the comment here:_

I suggest adding a length limit to the answers. Options might be presented to the voting user as buttons, so it makes sense to limit the length of the text. An initial take on that could look like this:

```suggestion
The `m.text` must not be longer than 256 bytes, but clients should encourage the user to use no
more than 50 bytes, as the voting options might be presented in single lines on mobile clients.
Similarly, the length of an answer's `id must also not exceed 256 bytes.
```

To put this limit into context: The following line  is 256 bytes of `i` which does not fit into my:

iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii

2021-11-04 20:53 UTC, jfowl commented on proposals/3381-polls.md
> +
A friend of mine and I used to run a polling bot for telegram, from the days before they added real polls. Querying the old database, I got the following results for poll texts:

| count | avg length | min length | max length |
| - | - | - | - |
| 490 517 |76.1295 | 1 | 10651 |

and a more fancy analysis brings up this for the poll texts:

![image](https://user-images.githubusercontent.com/15788906/140418332-33d541cb-9439-4ed9-b52b-0a2af32afe84.png)

2021-11-04 22:06 UTC, jfowl commented on proposals/3381-polls.md
> +
For the answer options:

Out of `654 728` single choice options, 90% were no longer than 11, with the most common answer option length being 9.
Only 0.2% of all answer options were longer than 100.

2021-11-11 17:11 UTC, andybalaam commented on proposals/3381-polls.md
> +    "org.matrix.msc1767.message": [
This should be `org.matrix.msc1767.text`, right?  (not "message")

2021-11-11 19:37 UTC, turt2live commented on proposals/3381-polls.md
> +    "org.matrix.msc1767.message": [
`text` is the shorthand for a text-only `message`, so either is fine.

[MSC1767](https://github.com/matrix-org/matrix-doc/pull/1767) has details.

2021-11-11 20:04 UTC, skolmer commented
We are currently implementing a poll widget and are thinking about implementing this spec. There is one additional requirement I want to bring up. It might be out of scope for this spec but I would be interested in your opinion if this is something that can make it into the official spec. 

Time-boxed polls: 
In our proprietary poll events we also store an offset relative to the start time when a poll should close. It allows us to automatically close polls after a certain amount of time. 
The primary use-case for our customer is a voting scenario where different topics are voted on within a defined time-frame. 
So for example there is a meeting set up for one hour and an agenda of 6 different topics that should be voted on. When the user clicks on a button to start the poll the start event is send with an offset set to 10 minutes. When the current date exceeds the event creation time + offset the UI automatically disables user input and filters out all votes that are placed after the poll has ended.

Another difference to this spec is that we have a poll state-event that just describes the poll. This allows a team to prepare a room with topics that should be voted on before the voting even starts.

2021-11-11 20:31 UTC, turt2live commented
@skolmer can we get that posted as threads on the diff please? It's hard to provide feedback from the comments here.

2021-11-11 20:32 UTC, skolmer commented on proposals/3381-polls.md
> +}
We are currently implementing a poll widget and are thinking about implementing this spec. There is one additional requirement I want to bring up. It might be out of scope for this spec but I would be interested in your opinion if this is something that can make it into the official spec. 

Time-boxed polls: 
In our proprietary poll events we also store an offset relative to the start time when a poll should close. It allows us to automatically close polls after a certain amount of time. 
The primary use-case for our customer is a voting scenario where different topics are voted on within a defined time-frame. 
So for example there is a meeting set up for one hour and an agenda of 6 different topics that should be voted on. When the user clicks on a button to start the poll the start event is send with an offset set to 10 minutes. When the current date exceeds the event creation time + offset the UI automatically disables user input and filters out all votes that are placed after the poll has ended. 
The current design has a fundamental flaw though because we compare server time to local time which might lead to users having different UI states if their local time is out of sync.

Another difference to this spec is that we have a poll state-event that just describes the poll. This allows a team to prepare a room with topics that should be voted on before the voting even starts.

2021-11-15 20:27 UTC, turt2live commented on proposals/3381-polls.md
> +}
Time-boxed polls would be a great addition, though likely for a future MSC (possibly once we have scheduled events so one can schedule the close event). For now, bots can probably manage this aspect of the feature.

We avoided state events for this to ensure that anyone can send a poll by default, though the collaboration aspect is interesting. Possibly some rich bots or widgets can offer the collaboration side and the protocol can handle the actual vote.

2021-12-22 15:51 UTC, gnunicorn commented on proposals/3381-polls.md
> +### Disclosed versus undisclosed polls
I'd like to briefly chime in here about visibility. I agree that the terminology "secret" should be avoided as it implies a secrecy that the protocol can't enforce, so switching the terms is good. But if the protocol won't actually enforce these types (the MSC differentiates between the protocol and what clients do visually), why is this embedded into the kind itself?

More over, why does this specific visual distinction get such a prominent position. There's other uses cases, e.g. on twitter people adding "just show results" option to allow people to peek w/o voting or hiding the specific users ("Anonymous"-Votes on Telegram), asking the client to randomize the order (as Telegram allows) or whether the User may be changing their vote after. Why is one case embedded and the others not? More over, how would you allow these to be combined if these are all their own `kind`? Like, allowing to see results without voting but hiding who voted for what exactly. As all these are primarily visual guidance for the clients how to show and allow users to interact with these, I'd vote for making these more explicit ways in which the poll is configured.

In our project, in order to allow for these and combinations of them, we've opted for just a set of boolean flags that can be set individually and indicate to the UI how to behave and which buttons to show when: https://github.com/TeamFranka/affinity/blob/eb09b56afc069befac3e21c15bb61052f10c0250/src/db/schemas/poll.ts#L43-L57 .

So, rather than making distinct types that don't have actual protocol-enforced behaviors, I'd propose to add a "config"-object with a few "client should"-sentences that describe the expected behavior when a configuration is set. This makes it also easy for client to extend the set of agreed upon UI/UX later (like, adding pseudonymous votes - as in, client don't show the exact voters).

2021-12-22 15:58 UTC, gnunicorn commented on proposals/3381-polls.md
> +    "m.text": "The poll has ended. Top answer: Poutine 🍟"
I'd propose to have an optional "outcome"-field here, where the closing user can state the finalised outcome. The second `m.text` already implies such a thing, but it isn't clear that this user generated nor should be shown in any other case as a fallback.

The reason I am proposing for an optional `outcome` is that even though the technical aspects are easy to calculate, the _actual_ outcome might be based on a more complex strategy that isn't ingrained (or not simply "most popular wins"). Simple example: there might be a tie between cases, so the closing party may decide based on other objectives or their digression (e.g. distance to the restaurant). Just allowing for the user to give an optional _final_ outcome allows for this to be easily attached rather than having to send another message stating that after.

2021-12-22 16:04 UTC, gnunicorn commented on proposals/3381-polls.md
> +        "m.text": "What should we order for the party?"
```suggestion
        "m.text": "What should we order for the party?",
        "m.info": "We will have drinks as discussed, but some people will be coming earlier, so we want to order food for them. We plan to eat at 7pm, so if you are there by then (or want some leftovers later), what's your choice of food? We will be splitting the bill between all people, who voted."
```
I'd propose we allow for an optional `m.info`-field allowing a for a secondary longer text with more information to put the question into context. Allowing the user asking to provide further context or other information without having to clutter the question (which most clients will assume to be rather short) and without having to send yet another question.

2021-12-22 16:12 UTC, turt2live commented on proposals/3381-polls.md
> +### Disclosed versus undisclosed polls
It's largely due to how the protocol builds its structures: identifiers are a lot easier to maintain and update than a set of flags, particularly when looking to add a new flag that might conflict with existing ones. An identifier instead provides a sort of bundle of functionality that can be determined by clients as needed.

This MSC's fallback to a certain kind of poll is a bit questionable (as noted by others), though it's how we typically design features like this in the protocol.

2021-12-22 16:13 UTC, turt2live commented on proposals/3381-polls.md
> +    "m.text": "The poll has ended. Top answer: Poutine 🍟"
`m.text` is a fallback representation. The field for an outcome is deliberately not included as it makes the voting process a bit pointless in its current form.

A future MSC may very well add the field.

2021-12-22 16:14 UTC, turt2live commented on proposals/3381-polls.md
> +        "m.text": "What should we order for the party?"
I think this is probably best for a future MSC. `m.info` isn't extensible events compatible here, so would instead be provided next to `question` rather than within it.

2021-12-27 16:02 UTC, tulir commented on proposals/3381-polls.md
> +        "m.text": "What should we order for the party?"
What's the type of `question` exactly? Are they just nested extensible events or do they have some restrictions? Formatting should probably at least be allowed

(same question applies to the items in `answers`)

2021-12-27 16:04 UTC, turt2live commented on proposals/3381-polls.md
> +        "m.text": "What should we order for the party?"
They're like captions from https://github.com/matrix-org/matrix-doc/pull/3552, so will probably turn into `m.message` contents instead of this format.

2021-12-27 16:33 UTC, tulir commented on proposals/3381-polls.md
> +        "m.text": "What should we order for the party?"
Makes sense, so I'll just keep complaining about `m.text` inside `m.message` contents (captions) there and the result of that should eventually be mirrored here? :D

2021-12-27 17:59 UTC, turt2live commented on proposals/3381-polls.md
> +        "m.text": "What should we order for the party?"
in theory, yes. Though as you mentioned on the other MSC it's possible we could represent it differently (more in line with this MSC, which is honestly more likely at the moment).

2022-01-03 17:24 UTC, turt2live commented on proposals/3381-polls.md
> +poll was closed, but timestamped for when it was open, the server is violating a social contract and likely
Resolving due to lack of comment from the wider community. If people have thoughts, please open a new thread.

2022-01-03 17:35 UTC, turt2live commented on proposals/3381-polls.md
> +
I'm not really sure we should put a limit on answer length, honestly. Though the common figure might be <100, that doesn't really mean we should limit it. Clients should already be used to handling lengthy text.

The difference with limiting the *number* of answers is that the number of answers takes vertical space whereas the length of a question/answer is horizontal. Vertical space is a lot harder to represent fairly (options shouldn't be hidden due to the risk of them given an unfair disadvantage of being selected), but horizontal space is a lot easier to counteract. Clients can/should apply their own limits to either limit the number of visible lines, characters, etc such as by making use of an ellipsis.

2022-01-03 17:38 UTC, turt2live commented
The core concepts of this MSC have been implemented in Element Web, iOS, and Android. I've linked the PRs for web and iOS as those are what I have handy.

2022-01-14 21:43 UTC, turt2live commented
putting this back in needs-implementation to ensure the push rules are viable.

2022-02-01 06:22 UTC, turt2live commented on proposals/3381-polls.md
> +nested events themselves. For example, the following can represent the same `question`:
not previously considered, but accidentally supported, is the ability to use non-text questions/answers for polls. Clients would just parse the body as an unknown event type and fall back to whatever they felt was best.

For example:

```json5
"answers": [
  {
    "id": "...",
    "m.text": "Picture of venue A",

    // From MSC3552
    "m.file": { /* ... */ },
    "m.image": { /* ... */ },
    "m.thumbnail": [ /* ... */ ],
    "m.caption": [ /* ... */ ]
  },
  // ...
]
```

2022-02-13 18:06 UTC, peter-scholtens commented
- Once multiple selection is added, I suggest also to implement Ranked Choice Voting. This could be defined by the following order in the GUI, like 1st choice, 2nd choice etc. but it also require an undo option or at least modifying the previous made ones to change the order. This makes the outcome more agreeable for everyone.

- Another wish would be to make a planning option: a group of voters choose for each option if they have time in their agenda or not. If Alice wants to lunch on Mon- / Tues- / Wednesday and Bob wants to lunch on Tues- / Wednes- / Thursday, then they agree on two options, Tuesday and Wednesday. The final option can be set if one of them withdraws an already made vote on a option of the current outcome (optionally only the original poster ca do this?).

2022-05-16 22:24 UTC, turt2live commented on proposals/3381-polls.md
> +### Notifications
TODO: Remove from proposal. See https://github.com/matrix-org/matrix-spec/issues/1065

2022-08-03 12:50 UTC, Johennes commented on proposals/3381-polls.md
> +poll rule and the `m.room.message` rule would be muted as well.
@turt2live: From a client-UI perspective, I think the synchronization between message and polls rules only makes sense if the client has a single toggle for both. That's a fair choice but, I think, not one we should be making for _all_ clients. Being able to change polls notification settings separately from message notification settings seems like a valid use case that is denied by the current proposal.

Maybe we should weaken this a little? Instead of having the server hard-wire the polls and messages rules, we could simply _recommend_ clients to toggle the polls rules together with the messages rules unless they expose fine-grained notification settings.

2022-08-03 12:59 UTC, Johennes commented on proposals/3381-polls.md
> +poll rule and the `m.room.message` rule would be muted as well.
@mnaturel I think this point is also relevant for your upcoming live location sharing push rules MSC.

2022-08-03 13:38 UTC, turt2live commented on proposals/3381-polls.md
> +poll rule and the `m.room.message` rule would be muted as well.
If there's a strong usecase for separating them, sure. Currently the intention is to deliberately treat them as room messages, setting the stage for how future extensible events will work.

2022-08-03 14:50 UTC, Johennes commented on proposals/3381-polls.md
> +poll rule and the `m.room.message` rule would be muted as well.
I'm not sure if maybe that could be too limiting? For instance, it doesn't seem unlikely that somebody would want to _not_ follow messages in a room but still wants to be notified when there's a poll to take part in.

2022-09-04 22:28 UTC, Zocker1999NET commented on proposals/3381-polls.md
> +one, and reminds the reader that polls should not be used for anything important/serious at the moment.
Because of Element's current implementation, I propose that the MSC requires clients to inform users about the security limitations of this poll implementation. E.g. If I try to edit my own poll in Element 1.11.3, Element says "Sorry, you can't edit a poll after votes have been cast.". (If you enable the right click menu in labs, even Element allows editing a poll due to a bug, see vector-im/element-web#22018).

Such a message is really misleading for users as Element nowhere explains that editing a poll after one casted a vote is technically possible. This missing piece of information could lead into normal users expecting that the poll system can be trusted (because editing is "forbidden"). Also because other poll systems from other services without end-to-end encryption can better enforce secrecy & trust (e.g. Telegram), users migrating from those systems could expect that Matrix can enforce these properties as well. Everyone reading the MSC knows about the insecurity of polls, but because normal users will not read the MSC, clients should be forced by the MSC to inform users properly about that:
- Matrix polls (by this MSC) cannot be trusted as editing the poll afterwards is possible
- casted votes can be seen by others

The MSC could also state that if clients want to prohibit editing the poll afterwards that the must not say that "it isn't possible" but could propose a text like "editing afterwards shouldn't be done".

2022-09-05 01:35 UTC, turt2live commented on proposals/3381-polls.md
> +one, and reminds the reader that polls should not be used for anything important/serious at the moment.
The spec isn't really the best place to force limitations like this: it can of course leave warnings, but ultimately it's up to the client to decide what degree of panic to place onto the user. It's just as legal to apply no panic as it is all the panic, for example. Such an existing case is end-to-end encryption: some clients might want to make sure that *every* party is verified before it even tries to send a message, and others might not even expose verification.

2022-11-14 13:14 UTC, mnaturel commented on proposals/3381-polls.md
> +until the poll is closed. In chat, these are typically used for quick questionares such as what to
```suggestion
until the poll is closed. In chat, these are typically used for quick questionnaires such as what to
```

2022-11-14 22:51 UTC, turt2live commented on proposals/3381-polls.md
> +
I'm considering this thread closed due to the rationale above.

2022-11-14 22:52 UTC, turt2live commented on proposals/3381-polls.md
> +nested events themselves. For example, the following can represent the same `question`:
supported in the new version, technically. A future MSC can propose image-based questions/answers.

2022-11-14 23:04 UTC, turt2live commented on proposals/3381-polls.md
> +poll rule and the `m.room.message` rule would be muted as well.
Moved: https://github.com/matrix-org/matrix-spec-proposals/pull/3930/files#r1022150924

2022-11-14 23:05 UTC, turt2live commented on proposals/3381-polls.md
> +one, and reminds the reader that polls should not be used for anything important/serious at the moment.
Considering resolved due to rationale above.

2022-11-15 13:50 UTC, mnaturel commented on proposals/3381-polls.md
> +Clients can rely on the [`/relations`](https://spec.matrix.org/v1.4/client-server-api/#get_matrixclientv1roomsroomidrelationseventidreltype)
@turt2live I have seen you recently removed the reference to the [MSC3523](https://github.com/matrix-org/matrix-spec-proposals/pull/3523) to be able to retrieve related events in a timebox manner. Was it done on purpose? Do you think we could rely on it?

2022-11-15 15:43 UTC, turt2live commented on proposals/3381-polls.md
> +Clients can rely on the [`/relations`](https://spec.matrix.org/v1.4/client-server-api/#get_matrixclientv1roomsroomidrelationseventidreltype)
It was done on purpose - I'm not convinced MSC3523 is the way to solve that particular problem.

2022-11-15 16:07 UTC, Johennes commented on proposals/3381-polls.md
> +Clients can rely on the [`/relations`](https://spec.matrix.org/v1.4/client-server-api/#get_matrixclientv1roomsroomidrelationseventidreltype)
Does that mean clients are supposed to fetch _all_ relations using `/relations` and then filter out votes sent after the poll ended themselves?

2022-11-15 16:18 UTC, turt2live commented on proposals/3381-polls.md
> +Clients can rely on the [`/relations`](https://spec.matrix.org/v1.4/client-server-api/#get_matrixclientv1roomsroomidrelationseventidreltype)
Yes, as they would have to anyways during `/sync` handling. The endpoint proposed by MSC3523 hasn't proven to be useful during development as it was never implemented, and there's still requirements on clients to process late/early votes that come in after the poll was closed.

2022-11-15 20:05 UTC, Johennes commented on proposals/3381-polls.md
> +      "rel_type": "m.reference",
One possible failure case I came to think of is decryption errors. If a device cannot decrypt an `m.poll.response` event, it won't be able to include it in the result. If other devices are able to decrypt said event, this will result in different poll results per device. Clients could add a UI treatment to warn users that some relations failed to decrypt and that the displayed poll result might be inaccurate. However, since we use `m.reference` here, I think, clients couldn't guarantee that the event that failed to decrypt was actually a poll response and not something else sent as a relation. Could it make sense to define a dedicated poll relation type so that clients could know how many poll votes failed to decrypt?

2022-11-15 20:08 UTC, turt2live commented on proposals/3381-polls.md
> +      "rel_type": "m.reference",
A dedicated poll relation type is countered in the alternatives, as it means generally putting polls in the hands of the server rather than the client.

Information loss (due to decryption, missing events, etc) is largely considered acceptable by this MSC, as chat polls are not the driver for more resilient chat. Instead, as the conversation history becomes more resilient, chat polls improve naturally.

2023-01-11 16:00 UTC, anoadragon453 commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
While implementing this MSC in turn with a not-yet-accepted MSC3381, I've had to use unstable prefixes for MSC3381 (`org.matrix.msc3381.poll.*`). The current text of this MSC _technically_ doesn't allow that for an unstable implementation yet.

```suggestion
this older format should review older drafts of this proposal.

While [MSC3381](https://github.com/matrix-org/matrix-spec-proposals/pull/3381) has not
been accepted, `org.matrix.msc3381.poll.*` may be used as a prefix in place of `m.poll.*`
throughout this proposal.
```

2023-01-11 16:44 UTC, turt2live commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
A previous draft does allow for it though, which makes it legal. The unstable prefix section is non-normative for the MSC.

2023-01-11 18:44 UTC, anoadragon453 commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
:facepalm: I meant to write this comment on MSC3930.

2023-04-18 03:35 UTC, turt2live commented on proposals/3381-polls.md
> +      "rel_type": "m.reference",
It's several months later, but to add: when a poll is rendered by a client which doesn't support polls (ie: as a text message instead of a poll), the voter is likely to use reactions or simply post to the chat - these votes are also not picked up by the poll and would need to be manually aggregated. 

Clients could show warnings on decryption errors, though. For example, "this poll may be missing some votes because we couldn't decrypt some messages".

2023-05-31 20:14 UTC, turt2live commented on proposals/3381-polls.md
> +disclosing who voted for what in an undisclosed poll, though this MSC leaves that at just a suggestion.
There is a desire to have clients conditionally show who voted for what along the way, described by a potential `show_participants` field on the poll object [here](https://github.com/matrix-org/matrix-spec-proposals/pull/4022). Currently, the MSC deliberately leaves it as an implementation detail for whether the client shows who voted for what. Element has clearly decided to implement it as *not* showing this information, though given the PR suggestion I do wonder if it should be conditional, changed in this MSC, or still left as an implementation detail.

@arnfriedgriesert did you have suggestions on this as the original PR author?

2023-06-01 12:10 UTC, gnunicorn commented on proposals/3381-polls.md
> +disclosing who voted for what in an undisclosed poll, though this MSC leaves that at just a suggestion.
What makes `show_participants` inherently different from e.g. `randomize_order`, `show_results` or `allow_change` that this should be included, [why the others should not](https://github.com/matrix-org/matrix-spec-proposals/pull/3381#discussion_r774005966)?

2023-06-01 13:55 UTC, turt2live commented on proposals/3381-polls.md
> +disclosing who voted for what in an undisclosed poll, though this MSC leaves that at just a suggestion.
The other flags were already linked in a thread whereas this new one wasn't. The scope difference is subtle: I'm generally leaning towards not adding new flags and instead codifying the behaviour where we can. 

Additional flags to control behavior are certainly possible. The further those flags are from the core of the MSC though, the more ideal it is to have them as dedicated MSCs. `show_participants` is challenging a core component of the MSC.

2023-06-01 20:10 UTC, turt2live commented
This MSC got implementations back before extensible events changed to using content blocks instead of subevent types - I'm counting those implementations as valid because there's no major functional difference between that draft and the latest draft.

Of course, SCT members are welcome to disagree and require implementation anyways. The earlier draft can be seen [here](https://github.com/matrix-org/matrix-spec-proposals/blob/95fdc44b904d2b4d2f227db99050e539e43f3509/proposals/3381-polls.md).

2023-06-01 20:18 UTC, turt2live commented
This MSC has also been open for quite a while, and it's dependencies have all landed. I'm very inclined to push it through the next stages onto FCP, though because it relies on Extensible Events it *cannot* be merged to the spec yet. Clients can use stable prefixes once the MSC passes FCP though.

If folks have objections/concerns, please raise them urgently. It'd be nice to have this collecting checkboxes in the next week or so before we forget to call FCP on it again :)

---

FCP on this also unblocks some dependent MSCs, like https://github.com/matrix-org/matrix-spec-proposals/pull/3930 and https://github.com/matrix-org/matrix-spec-proposals/pull/4013.

2023-06-20 00:36 UTC, turt2live commented
As previously mentioned, this MSC already has its blockers cleared and hasn't received any feedback on some of the outstanding items.

I'm putting this forward for being accepted (but not merged, as per Extensible Events generally):

@mscbot fcp merge

2023-06-20 12:40 UTC, zecakeh commented on proposals/3381-polls.md
> +  vote is spoiled (as if they didn't make a selection).
Just to be clear, is it possible for this list to include several times the same `m.id`? Meaning that a user can vote several times for the same answer, as long as they respect `max_selections`?

2023-06-20 15:05 UTC, Johennes commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
As it happens, we've done the exercise of comparing the events from v1 implement in Element Web against the MSC today:

### Poll start

#### Element Web

```
{
  "type": "org.matrix.msc3381.poll.start",
  "content": {
    "org.matrix.msc1767.text": "What should we order for the party?\n1. Pizza 🍕\n2. Poutine 🍟\n3. Italian 🍝\n4. Wings 🔥",
    "org.matrix.msc3381.poll.start": {
      "kind": "org.matrix.msc3381.poll.disclosed",
      "max_selections": 1,
      "question": {
        "org.matrix.msc1767.text": "What should we order for the party?",
      },
      "answers": [
        {"id": "pizza", "org.matrix.msc1767.text": "Pizza 🍕"},
        {"id": "poutine", "org.matrix.msc1767.text": "Poutine 🍟"},
        {"id": "italian", "org.matrix.msc1767.text": "Italian 🍝"},
        {"id": "wings", "org.matrix.msc1767.text": "Wings 🔥"}
      ]
    }
  }
}
```

#### MSC

```
{
  "type": "m.poll.start",
  "content": {
    "m.text": [{"mimetype": "text/plain", "body": "What should we order for the party?\n1. Pizza 🍕\n2. Poutine 🍟\n3. Italian 🍝\n4. Wings 🔥"}],
    "m.poll": {
      "kind": "m.disclosed",
      "max_selections": 1,
      "question": {
        "m.text": [{"body": "What should we order for the party?"}]
      },
      "answers": [
        {"m.id": "zSE2pXU7DVaXY5pQ", "m.text": [{"body": "Pizza 🍕"}]},
        {"m.id": "4Ps2oqnMV15OwSt9", "m.text": [{"body": "Poutine 🍟"}]},
        {"m.id": "HoTMdIPF6ODLHw42", "m.text": [{"body": "Italian 🍝"}]},
        {"m.id": "IOmAUKKYdEjhAvG7", "m.text": [{"body": "Wings 🔥"}]},
      ]
    }
  }
}
```

### Poll vote

#### Element Web

```
{
  "type": "org.matrix.msc3381.poll.response",
  "content": {
    "m.relates_to": {
      "rel_type": "m.reference",
      "event_id": "$fw8dod4VdLCkakmKiD6XiVj7-RrFir9Jwc9RW6llJhU"
    },
    "org.matrix.msc3381.poll.response": {
      "answers": ["HoTMdIPF6ODLHw42"]
    }
  }
}
```

#### MSC

```
{
  "type": "m.poll.response",
  "content": {
    "m.relates_to": {
      "rel_type": "m.reference",
      "event_id": "$fw8dod4VdLCkakmKiD6XiVj7-RrFir9Jwc9RW6llJhU"
    },
    "m.selections": ["HoTMdIPF6ODLHw42"]
  }
}
```

### Poll end

#### Element Web

```
{
  "type": "org.matrix.msc3381.poll.end",
  "content": {
    "m.relates_to": {
      "rel_type": "m.reference",
      "event_id": "$fw8dod4VdLCkakmKiD6XiVj7-RrFir9Jwc9RW6llJhU"
    },
    "org.matrix.msc1767.text": "The poll has ended. Top answer: Italian 🍝",
    "org.matrix.msc3381.poll.end": {},
  }
}
```

#### MSC

```
{
  "type": "m.poll.end",
  "content": {
    "m.relates_to": {
      "rel_type": "m.reference",
      "event_id": "$fw8dod4VdLCkakmKiD6XiVj7-RrFir9Jwc9RW6llJhU"
    },
  },
  "m.text": [{"body": "The poll has closed. Top answer: Italian 🍝"}],
  "m.poll.results": { // optional
    "zSE2pXU7DVaXY5pQ": 5,
    "4Ps2oqnMV15OwSt9": 7,
    "HoTMdIPF6ODLHw42": 8,
    "IOmAUKKYdEjhAvG7": 6
  }
}
```

2023-06-20 15:53 UTC, zecakeh commented on proposals/3381-polls.md
> +redacted. Votes with timestamps after the poll has closed are ignored, as if they never happened.
If I'm not mistaken, when an event is redacted, it loses the `m.relates_to` field so clients shouldn't be able to tell which poll it applied to.

So redacting an event should revert to the previous response. And unvoting should probably be sending a response with an empty selection, to be sure there are no previous events that will be used instead.

2023-06-20 18:02 UTC, turt2live commented on proposals/3381-polls.md
> +redacted. Votes with timestamps after the poll has closed are ignored, as if they never happened.
Good point, yes. This was originally written with protecting `m.relates_to` in mind, but that hasn't happened.

2023-06-20 18:03 UTC, turt2live commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
In short, it uses the accepted version of extensible events rather than the legacy version. All the same information is communicated.

2023-06-20 18:06 UTC, turt2live commented on proposals/3381-polls.md
> +  vote is spoiled (as if they didn't make a selection).
This is a good question. I imagine the expectation would be that multiple votes for the same option still only counts as a single vote, but will check that assumption out of band.

2023-06-20 22:41 UTC, turt2live commented on proposals/3381-polls.md
> +  vote is spoiled (as if they didn't make a selection).
Said conversations conclude that we should ban the behaviour of voting multiple times for the same thing, at least for now. 

Will update the MSC to clarify that repeatedly voting for the same thing still counts as 1 vote.

2023-06-25 14:11 UTC, KitsuneRal reviewed
One purely textual thing

2023-06-27 14:20 UTC, richvdh commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
ok, but my question is: If we're not going to bother implementing it (and, if it's really just changes in field names, we don't have to), why do we need a new unstable prefix?

Aren't we effectively saying that the unstable prefixes are the `org.matrix.msc3381.poll` currently implemented?

2023-06-27 16:36 UTC, richvdh commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
> it seemed safer to just create a new unstable prefix to mark the version than to rely on the existing one.

But the whole point of unstable prefixes is to allow people to implement things before FCP. What's the point of an unstable prefix nobody is going to use?

> Is this thread blocking FCP?

Well, I'm not going to block FCP if 6 other people think it's fine. But I'm also hesitating to approve it when I don't really understand what's going on.

2023-06-27 17:31 UTC, turt2live commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
Using a different prefix just feels like the right thing to do, given we don't know if there's unreferenced implementations in the wild. 

The unstable prefix section is informative rather than normative (it doesn't affect the spec, instead acting as an implementation guide). My overall concern is that we're spending a bit too much time with the language/approach in the unstable prefix section rather than whether the existing implementation stands to be sufficient. I believe despite the differences above, the implementation still qualifies. If others don't, I urge them to raise it as an explicit FCP concern.

2023-06-27 17:52 UTC, richvdh commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
> Using a different prefix just feels like the right thing to do, given we don't know if there's unreferenced implementations in the wild.

I'm not following. Is anyone ever going to use `org.matrix.msc3381.v2.` prefixes? If not, let's cut that noise out or the MSC.

> My overall concern is that we're spending a bit too much time with the language/approach in the unstable prefix section rather than whether the existing implementation stands to be sufficient. I believe despite the differences above, the implementation still qualifies.

Honestly, the root of the problem is that I'm struggling to grok how close a match to the MSC the actual implementation is. I appreciate @Johennes ' efforts in setting out some examples, but fundamentally I'm still reduced to attempting diffing by eye, which I'm afraid I don't really have time for.

2023-06-27 19:11 UTC, Johennes commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
> I'm not following. Is anyone ever going to use org.matrix.msc3381.v2. prefixes? If not, let's cut that noise out or the MSC.

The Rust SDK had v2 implemented until very recently. We're currently preparing to implement polls in Element X. The current Element apps implement v1 of the proposal though and backwards compatibility would be highly desirable. Support for v2 in the SDK was now removed in https://github.com/ruma/ruma/pull/1589 and support for v1 was reintroduced so that the Element X clients can use it.

If we remove the v2 prefixes now, I think that would just mean that the Rust SDK, like all Element clients, implements an earlier version of this MSC. It's slightly annoying to manage that but I think the underlying issue is that we've had polls implemented in clients for more than 1.5 years without pushing to get it into the spec.

2023-06-27 20:57 UTC, turt2live commented on proposals/3381-polls.md
> +this older format should review older drafts of this proposal.
Discussed out of band, the behavioural change from MSC1767 isn't completely clear through this MSC (and probably others which haven't achieved proposed-FCP yet). Action is to *remove* the v2 prefix and clarify in actual words what the diff between the events is.

A concern is that if we continue with a v2 prefix then folks like the rust-sdk will implement things which have no other implementations, wasting effort, and that we set a precedent where we define prefixes for things with no intention of being implemented. We'd rather have a description of the diff instead of an unused prefix.

2023-07-04 07:34 UTC, zecakeh commented on proposals/3381-polls.md
> +    under `question` and `answers`, and the `org.matrix.msc3381` prefix for `kind` enum values.
```suggestion
    under `question` and `answers`, and the `org.matrix.msc3381.poll` prefix for `kind` enum values.
```

2023-07-04 07:34 UTC, zecakeh commented on proposals/3381-polls.md
> +  * `m.poll` becomes `org.matrix.msc3381.poll.start`, retaining all other fields as described. Note the `m.text`
There should also be a note that `m.id` in `answers` becomes `id`. I believe it is easy to miss.

2023-07-04 13:18 UTC, richvdh approved these changes
lgtm modulo @zecakeh's comments above

2023-07-04 14:01 UTC, turt2live commented on proposals/3381-polls.md
> +    under `question` and `answers`, and the `org.matrix.msc3381` prefix for `kind` enum values.
The prefix is without `.poll` as otherwise the event types would be `poll.poll`.

2023-07-04 14:37 UTC, zecakeh commented on proposals/3381-polls.md
> +    under `question` and `answers`, and the `org.matrix.msc3381` prefix for `kind` enum values.
But this part of the sentence is just for `kind` enum values, and these values are `org.matrix.msc3381.poll.(un)disclosed` compared to the stable values that are `m.(un)disclosed`.

2023-07-04 15:45 UTC, turt2live commented on proposals/3381-polls.md
> +    under `question` and `answers`, and the `org.matrix.msc3381` prefix for `kind` enum values.
ah, yes. Github did a bad job of representing that on mobile, sorry.

2023-07-04 17:57 UTC, KitsuneRal requested changes

2023-07-04 17:57 UTC, KitsuneRal commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
I might be missing something but I don't see in the latest text of MSC1767 that `m.text` is a single string - it's an array there. If there was a follow up MSC it should be referred to, here.

2023-07-04 18:31 UTC, turt2live commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
It's not that MSC1767 says it's a single string, it's that it *used to* say it was a single string.

2023-07-04 18:41 UTC, KitsuneRal commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
Is there some other MSC I forgot that amends MSC1767 to define `m.text` as a single string?

2023-07-04 18:45 UTC, turt2live commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
No, this is the unstable prefix with respect to historical drafts of MSC1767, not the other way around. The section is saying "instead of the `m.text` array, use a single string called `org.matrix.msc1767.text`".

The MSC1767 draft which defined it as a single string has been lost to time at this point, back when it was `m.text` and `m.html`. The MSC then changed to have `m.markup`, which polls never adopted formally, but MSC1767 renamed `m.markup` to `m.text` moments before merging, avoiding an unstable namespace conflict.

2023-07-04 22:36 UTC, KitsuneRal commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
Okay, so if I gather that right, this MSC proposes an unstable version of polls that diverges completely from the (an?) unstable version of extensible events; and client authors that want to implement both unstable versions have to somehow figure out which of the two schemas to use to parse an `org.matrix.msc1767.message` event - perhaps by checking whether its content has the key `m.poll`?

I'm genuinely trying to figure out what an implementation for unstable versions would look like here because _these_ unstable versions will likely to stick in pre-extensible event room versions so more clients will want to implement it. The above is the best I could come up with so far.

2023-07-04 22:56 UTC, turt2live commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
The unstable event types *should* only appear in room versions where extensible events aren't supported, meaning a client should *not* be attempting to parse these as extensible events. Instead, a client which doesn't support (unstable) polls would see an event which can't be parsed - this is the intentionally lossy part of the MSC. 

If a client were to send an unstable event into a room which does support extensible events though, that's largely undefined behaviour. Clients should realistically only be looking at stable identifiers for both polls and extensible events once we get there.

Ultimately though, clients traditionally don't have an interest in maintaining or writing unstable implementations of MSCs. Once this MSC is accepted, they can use stable identifiers and never look at this section. The section is here for historical reference, not future reference.

2023-07-05 08:50 UTC, KitsuneRal commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
Do we allow stable `m.message` events in current (pre-extensible events) room versions? If not, clients will have to implement unstable extensible events for those.

2023-07-05 10:35 UTC, KitsuneRal commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
Here's my concern, distilled: if there are two different extensible event types and a particular client would implement unstable versions of both, they would expect a common piece (described by MSC1767) to be, well, common. This ends up not being the case here: the `org.matrix.msc1767.text` key may correspond either to an array or to a string, depending on the event "subtype" if this text is to be followed. As a client author I would rather just accept either an array or a string with no regard to which sibling keys are present.

2023-07-05 13:01 UTC, turt2live commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
> Do we allow stable `m.message` events in current (pre-extensible events) room versions? If not, clients will have to implement unstable extensible events for those.

Not currently - see MSC1767.

> Here's my concern, distilled: if there are two different extensible event types and a particular client would implement unstable versions of both, they would expect a common piece (described by MSC1767) to be, well, common. This ends up not being the case here: the `org.matrix.msc1767.text` key may correspond either to an array or to a string, depending on the event "subtype" if this text is to be followed. As a client author I would rather just accept either an array or a string with no regard to which sibling keys are present.

I think that's a valid concern, but not one for this MSC. The lack of changed prefix is a concern for the already-accepted MSC1767.

2023-07-07 15:45 UTC, KitsuneRal commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
Well, that's fair. Alright, let's settle on keeping this thread unresolved for sake of documenting (I think we'll see more client authors just as confused as I was) and leave that be. One consequence of it I can figure now is that the unstable version poll events is not actually extensible (i.e. it cannot be extended with, e.g., HTML body or an accompanying image) but that looks like a minor evil.

2023-07-07 15:45 UTC, KitsuneRal approved these changes

2023-07-11 14:32 UTC, erikjohnston commented on proposals/3381-polls.md
> +redacted. Votes with timestamps after the poll has closed are ignored, as if they never happened. Note
But if redactions detach the vote from the poll, how do clients know to ignore earlier votes? Or is the plan to fix redactions?

2023-07-11 14:37 UTC, erikjohnston commented on proposals/3381-polls.md
> +which don't understand how to process these events will hide/ignore them.
Why? It is specifically meaning that users using textual clients can't even read polls? I guess with `undisclosed` polls you probably *do* want to avoid textual output, but I'm not convinced that by itself is enough of a rationale for not having a fallback event?

2023-07-11 16:00 UTC, turt2live commented on proposals/3381-polls.md
> +redacted. Votes with timestamps after the poll has closed are ignored, as if they never happened. Note
err, I fixed this elsewhere in the proposal but not here. Redacting unvotes/reverts the vote - we're not going to fix redactions here, sorry :(

2023-07-11 16:04 UTC, turt2live commented on proposals/3381-polls.md
> +which don't understand how to process these events will hide/ignore them.
I'll put the why in the proposal, but in the meantime: it's the same rationale as reactions not having a text fallback. It's essentially just spam between question and answer - the poll ending will reveal results regardless. 

Worth noting that under Extensible Events the event types specify the default/minimum schema, not the full legal schema. Clients which want to emit these events with a text fallback absolutely can, but for a default behaviour we're interested in not spamming IRC/bridge users. This also makes it fairly trivial to fix later on: we just open an MSC to add the text fallback blocks.

2023-07-12 02:47 UTC, uhoreg reviewed
Seems pretty sensible overall.  Just a couple non-blocking nits.

2023-07-12 02:47 UTC, uhoreg commented on proposals/3381-polls.md
> +* `answers` - Array of options users can select. Each entry is an object with an `m.text` content
Is the array of answers intended to be ordered or unordered?  e.g. can clients reorder options to avoid bias?  Or can poll creators rely on clients maintaining the order so that e.g. a poll option saying "all of the above" won't get placed at the top?

2023-07-12 02:47 UTC, uhoreg commented on proposals/3381-polls.md
> +* **Optional** - An `m.poll.results` block to show the sender's perspective of the vote results.
Is there any guidance for what clients should do if the `m.poll.results` contents differ from the client's own local view?

2023-07-12 06:46 UTC, Johennes commented on proposals/3381-polls.md
> +* **Optional** - An `m.poll.results` block to show the sender's perspective of the vote results.
In reconsidering this, I'm actually wondering if we need this block at all. It will only be helpful on polls that were ended. So clients will need to incorporate `/relations` API calls for poll start events in the timeline anyway and doing the same for poll end events probably isn't a big stretch. But even for ended polls, `m.poll.results` is not actually guaranteed to be accurate (which the proposal also calls out in the paragraph above). So I'm not sure under which circumstances a client would actually use it?

2023-07-13 10:12 UTC, dbkr commented on proposals/3381-polls.md
> +```
Sorry, I'm still trying to unpick what's happened here with regards to existing implementations and how this corresponds to what's out there and previous/current version of extensible events. Documenting the differences here helps a lot, but could we spell out whether, if I implement what's written in this MSC, will my polls impl works with existing versions of Element out there currently?

2023-07-13 17:56 UTC, turt2live commented on proposals/3381-polls.md
> +```
in lieu of having a moment to put it in the MSC itself, unstable implementations of this MSC will need to use the unstable stuff defined here (simply using a different namespace will not work). Element can't have stable implementation of polls yet though, so is a bit of a chicken-and-egg there.

2023-07-21 09:02 UTC, zecakeh commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
It seems that while this field is now required, it used to be **optional**, which should probably be clarified.

The reason I'm pointing that out is that we had exactly that issue with Ruma regarding the current implementations of Element Android and Element iOS, that don't send the field: https://github.com/ruma/ruma/pull/1589#issuecomment-1644569323.

2023-07-21 13:11 UTC, zecakeh commented on proposals/3381-polls.md
> +  * `org.matrix.msc3381.poll.end` is added as an empty object, and is required.
I don't know if it should be discarded as an implementation issue, but Element Android doesn't send this field (see https://github.com/ruma/ruma/pull/1589#issuecomment-1645337448).

I'm guessing it could be put as optional for compatibility because there are events that exist in the wild.

2023-07-30 20:54 UTC, turt2live commented
will update the MSC text with the minor (non-blocking) changes before merge.

2023-07-30 20:55 UTC, turt2live commented on proposals/3381-polls.md
> +  * `org.matrix.msc3381.poll.end` is added as an empty object, and is required.
Android would be "non-compliant" with this, but it sounds like Ruma is overly strict as well. The intention of Extensible Events is that if you know about the event type then the fallback is ignored. In other words, it's required on send, not receive.

2023-07-30 20:55 UTC, turt2live commented on proposals/3381-polls.md
> +  * `m.text` throughout becomes a single string, represented as `org.matrix.msc1767.text`
see https://github.com/matrix-org/matrix-spec-proposals/pull/3381#discussion_r1278617837

2023-07-30 20:56 UTC, turt2live commented on proposals/3381-polls.md
> +* **Optional** - An `m.poll.results` block to show the sender's perspective of the vote results.
If it's not being used by any implementations then, assuming the SCT is okay with it, I'm happy to remove it post-FCP here.

2023-07-30 20:57 UTC, turt2live commented on proposals/3381-polls.md
> +* `answers` - Array of options users can select. Each entry is an object with an `m.text` content
Arrays in JSON are mandatory ordered. Reordering options I think would require another flag of some kind.

2023-07-31 11:59 UTC, anoadragon453 commented on proposals/3381-polls.md
> +* **Optional** - An `m.poll.results` block to show the sender's perspective of the vote results.
Hmm, wouldn't an advantage of having the results stored in the `m.poll.results` event be that everyone sees the same results - even if the poll runner lied about them?

2023-08-06 10:58 UTC, KitsuneRal commented on proposals/3381-polls.md
> +* **Optional** - An `m.poll.results` block to show the sender's perspective of the vote results.
I'd rather stick with the current design, if only for early display of poll results before the client gets a hold of all the votes - with the accompanied wording that lying about them doesn't make sense because the true situation can be easily, if not as quickly, ascertained.

2023-11-27 21:51 UTC, uhoreg commented
> will update the MSC text with the minor (non-blocking) changes before merge.

@turt2live it looks like this got forgotten?

2023-11-27 22:08 UTC, turt2live commented
It's not forgotten, but heavily delayed 😭 I'm hoping to take a look in the short term, or at least before the year ends.

2023-12-05 22:10 UTC, turt2live commented on proposals/3381-polls.md
> +  }
err, yes. Will fix before merge.

2023-12-05 22:14 UTC, turt2live commented on proposals/3381-polls.md
> +* **Optional** - An `m.poll.results` block to show the sender's perspective of the vote results.
ftr, I'm assuming @KitsuneRal's opinion is shared across the SCT here, due to lack of comment. If there's significant disagreement then we can fix it during the remaining process.

2023-12-05 22:25 UTC, turt2live commented
2ff98703398d1cc871147bb26683b573b0ce6a49 addresses the *minor* review feedback which came up during FCP discussions. As it didn't block FCP and the threads appear to have conclusions, I've incorporated those conclusions into the proposal text.

Merging otherwise per https://github.com/matrix-org/matrix-spec-proposals/pull/3381#issuecomment-1657264640

2023-12-05 22:25 UTC, merged

2023-12-05 22:26 UTC, turt2live commented
Like https://github.com/matrix-org/matrix-spec-proposals/pull/3930#issuecomment-1686756885 , this is blocked on the wider system actually landing in the spec itself.

2026-04-10 15:12 UTC, HarHarLinks commented on proposals/3381-polls.md
> +  `m.message` event. The array is truncated to 20 maximum options.
`answers` is probably intended to be REQUIRED, since the poll is useless otherwise. For the same reason, it MUST NOT be empty. It would be possible to also define a relationship between `max_selections` and the array length, but I don't see the necessity - instead it leaves the option open for e.g. selecting the same entry multiple times in the future.

2026-04-13 08:46 UTC, HarHarLinks commented on proposals/3381-polls.md
> +  block, similar to `question`, and an opaque string field `m.id` for use in response events. More
In addition to my [other comment](https://github.com/matrix-org/matrix-spec-proposals/pull/3381/files#r3065127817), it seems reasonable to me to REQUIRE a plain text representation for each answer. This appears also to match the landscape of current implementations.

2026-04-16 13:41 UTC, HarHarLinks commented on proposals/3381-polls.md
> +  block, similar to `question`, and an opaque string field `m.id` for use in response events. More
The `m.id`s need to be unique (within the `answers` array) or otherwise define behavior defining dupes.