Room versions 8 and 9: Restricted rooms
matrix-org/matrix-doc pull request #3387
Opened 2021-09-08 05:12 UTC by turt2live

MSCs:
* https://github.com/matrix-org/matrix-doc/pull/3083
* https://github.com/matrix-org/matrix-doc/pull/3289
* https://github.com/matrix-org/matrix-doc/pull/3375

2021-09-08 11:56 UTC, clokep commented on content/server-server-api.md
> +the resident homeserver then adds its signature to this event and
```suggestion
The resident homeserver then adds its signature to this event and
```

2021-09-08 11:56 UTC, clokep commented on content/server-server-api.md
> +must also send the event to other servers participating in the room.
The resident server also returns the (newly signed) event back to the joining server.

2021-09-08 12:01 UTC, clokep commented on content/server-server-api.md
> +one of the conditions, though the resident server would be unable to
I'm not sure it is implied that the resident server knows whether the joining server satisfies any of the conditions or not here. I think `M_UNABLE_TO_GRANT_JOIN` mostly means "go ask someone else, I can't help you".

It looks like Synapse's implementation works this way, but I don't think that's enforced in any way.

2021-09-08 12:02 UTC, clokep commented on data/api/client-server/joining.yaml
> +            - The room is restricted and the user failed to satisfy any of the conditions.
Should the 400 errors be documented in this file as well?

2021-09-08 12:06 UTC, clokep commented on data/api/server-server/joins-v1.yaml
> +                          Required if the room is [restricted](/client-server-api/#restricted-rooms).
I think this API is also used to accept an invite? In which case this is not required.

2021-09-08 12:08 UTC, clokep commented on data/api/server-server/joins-v1.yaml
> +                "join_authorised_via_users_server": "@anyone:resident.example.org"
The response in here needs to be updated with the `event` field.

2021-09-08 12:14 UTC, clokep commented on content/rooms/v8.md
> +room will be able to support this newly introduced join rule.
I find this a bit confusing. Yes it is primarily intended to be used with spaces, but generally for rooms in a space, so "any v8 capable room will be able to support this newly introduced join rule" -> well, yes. that's what this document is describing!

Since the join rules apply to rooms, not spaces, I think this is a bit confusing?

(Also -- do we usually link to MSCs? Or is that just until there's a spaces section in the spec?)

2021-09-08 12:20 UTC, clokep commented on content/rooms/v9.md
> +Clients which implement a local redaction algorithm are encouraged to read on.
I had no idea this was a thing. Is there a reason clients would want to do? (I don't see any info about this in the client behavior section of redactions.)

2021-09-08 15:38 UTC, turt2live commented on data/api/server-server/joins-v1.yaml
> +                "join_authorised_via_users_server": "@anyone:resident.example.org"
Which `event` field?

2021-09-08 15:40 UTC, turt2live commented on content/rooms/v8.md
> +room will be able to support this newly introduced join rule.
Yea, it's probably a bit too early to start dropping the word "Spaces" into the spec. We can cover this with the blog post.

We do link to MSCs when we don't have a relevant section to link to, or are unsure what the shape of the solution looks like beyond "something like that". For Spaces, we just don't have them in the spec so wanted to link to something that described what a Space is.

2021-09-08 15:44 UTC, turt2live commented on content/rooms/v9.md
> +Clients which implement a local redaction algorithm are encouraged to read on.
The spec technically requires clients to apply the redaction algorithm locally to avoid cases where the server is malicious or the client stores the original event. When the client sees a redaction event, it's meant to go through and apply the redaction algorithm manually to make the stores consistent.

In practice, clients tend to just over-apply the redaction algorithm because they aren't concerned with many protocol features. v9 is no exception: if the client accidentally/intentionally redacts the field, oh well.

This can be seen in the js-sdk: https://github.com/matrix-org/matrix-js-sdk/blob/3790e8abb46b4bd329e29673cfa2560d67552023/src/models/event.ts#L937-L946

2021-09-08 15:44 UTC, clokep commented on data/api/server-server/joins-v1.yaml
> +                "join_authorised_via_users_server": "@anyone:resident.example.org"
This is pretty much what I referenced in https://github.com/matrix-org/matrix-doc/pull/3387#discussion_r704347430

The newly signed event gets returned to the joining server.

2021-09-08 15:45 UTC, clokep commented on content/rooms/v9.md
> +Clients which implement a local redaction algorithm are encouraged to read on.
Neat, thanks for the pointer!

2021-09-10 19:07 UTC, clokep reviewed
Looks good except for a couple of inconsistencies!

2021-09-10 19:07 UTC, clokep commented on data/api/server-server/joins-v1.yaml
> +            attempt another resident server.
I think this paragraph needs to be made consistent with the changes in db2a73803d17478362bb2c2e2a1e6fd08000cdf2.

2021-09-10 19:07 UTC, clokep commented on data/api/server-server/joins-v2.yaml
> +            attempt another resident server.
Also needs to be made consistent with db2a73803d17478362bb2c2e2a1e6fd08000cdf2.

2021-09-27 11:39 UTC, clokep approved these changes
Changes look consistent to me! Thanks for tackling this!

2021-09-27 12:43 UTC, richvdh requested changes
thanks for having a go at this - it looks like a great start.

Is there a way to see the rendered output of the spec without building it locally? Or better yet, an HTML diff?

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/definitions/send_join_response.yaml
> +      Required if the room version is based upon [v8](/rooms/v8). The signed copy of the membership
... or v9.

Indeed, do we want to limit this to particular room versions? Can we just mandate it for all servers complying with this version of the spec?

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/definitions/send_join_response.yaml
> +      Required if the room version is based upon [v8](/rooms/v8). The signed copy of the membership
Either way, we probably want to record which version of the spec added this field?

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/examples/pdu_v4_join_membership.json
> +            "ed25519:key_version:": "these86bytesofbase64signaturecoveressentialfieldsincludinghashessocancheckredactedpdus"
```suggestion
            "ed25519:key_version": "these86bytesofbase64signaturecoveressentialfieldsincludinghashessocancheckredactedpdus"
```

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/examples/pdu_v4_join_membership.json
> +            "ed25519:key_version:": "a different signature"
```suggestion
            "ed25519:other_key_version": "a different signature"
```

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/joins-v1.yaml
there is some text above that is no longer necessarily correct: 

>            The request is invalid or the room the server is attempting
>            to join has a version that is not listed in the `ver`
 >           parameters.

... or the server was unable to validate the restricted rules.

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/joins-v1.yaml
> +                      join_authorised_via_users_server:
we should record the spec version that adds this

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/joins-v1.yaml
> +            event.
we should record the spec version that adds these

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/joins-v1.yaml
> +                  join_authorised_via_users_server:
we should record the spec version that adds this

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/joins-v2.yaml
> +                  join_authorised_via_users_server:
need to record the spec version that adds this

2021-09-27 12:43 UTC, richvdh commented on data/api/server-server/joins-v2.yaml
> +        400:
need to record the spec version that adds this

2021-09-27 12:43 UTC, richvdh commented on data/event-schemas/schema/m.room.join_rules.yaml
> +    available in rooms based on [v7](/rooms/v7).
... or v8, or v9.

2021-09-27 12:43 UTC, richvdh commented on data/event-schemas/schema/m.room.join_rules.yaml
> +    Only available in rooms based on [v8](/rooms/v8).
.. or v9

2021-09-27 16:07 UTC, turt2live commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
We can't use relative wording based on time because room versions are not linear by design (annoyingly).

2021-09-27 16:10 UTC, turt2live commented
@richvdh regarding all the "record spec version which adds this" comments: I don't think this is the PR that will do that. It feels like a good thing to include, but for some other PR to tackle.

2021-09-27 17:17 UTC, richvdh commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
well indeed, but "rooms based on room version 8" isn't what we want, either. Do you have any better suggestions?

2021-09-27 17:17 UTC, richvdh commented on content/rooms/v8.md
> +   1. If membership state is `join`, allow.
I don't think so? which branch?

2021-09-27 17:18 UTC, richvdh commented
> regarding all the "record spec version which adds this" comments: I don't think this is the PR that will do that. It feels like a good thing to include, but for some other PR to tackle.

the trouble is I can't really see us taking the time to go back and do it retrospectively. The best we're going to manage is to stop the bleeding by doing our best going forward.

2021-09-27 17:23 UTC, turt2live commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
"based on" was my best suggestion to cover the nuances, and has been for the last 7 room versions :(

2021-09-27 17:25 UTC, turt2live commented
I'm happy for us to block this PR on a system which can handle it appropriately. I don't feel as though writing it out by hand everywhere is the best approach for maintenance reasons.

2021-09-27 17:35 UTC, richvdh commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
> and has been for the last 7 room versions :(

I'm only seeing it used in relation to knocking? I think v7 was the first time we introduced new features.

2021-09-27 17:42 UTC, turt2live commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
The room versions themselves use a very similar language, as does the server-server spec when needed. It's not an exact quote, but the words could be swapped around to match "based upon vX" easily. 

What is the concern with "based upon" specifically? It implicitly mentions v9, and v8's documentation points at v9 as preferred over v8.

2021-09-27 22:59 UTC, richvdh commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
To me, "a room based upon room version 7" means a v7 room. I think you're trying to make "based upon" do a lot of work that nobody else is going to notice.

I suppose you could say "rooms using room version 8 or room versions based on version 8", but that's a bit of a mouthful.

The room version specs get away with it, because in that case, room version 8 really is based on version 7. The relationship between room v8 and room v7 is different to that between a room using v8 and room version 8 itself, so the fact it works for the first relationship doesn't mean it works for the second. They are different kinds of "based on".

Sorry, but I'm really not happy with the current wording; I just don't think that anyone without an intricate knowledge of the history of the project is going to read it in the way you intend.

Maybe we should seek some other opinions. Perhaps I'm making a fuss about nothing. Or perhaps someone else will be able to suggest better wording.

2021-09-27 23:06 UTC, richvdh commented
> I don't feel as though writing it out by hand everywhere is the best approach for maintenance reasons.

I'm not sure I agree; I'm not convinced there is a massive maintenance overhead for writing it out by hand.

But either way, I'm not happy continuing to layer the debt on, so I'd rather block this and sort it out than land it without that info.

2021-09-28 01:26 UTC, turt2live commented
So part of the issue that comes up right away with a manual system is that we don't really know the next spec version any of this will be introduced in. We can add "run s/vNext/v1.X" to the release process steps, though this is not exactly something that inspires confidence imo (not to mention the tedious bit of it). 

An option would be to introduce a dated variable to the spec engine so we can populate a yaml/json/text file with a map of date stamps to release versions. For example:

```yaml
after-2016-jan-01: v1.0
after-2019-jun-11: unstable  # June 11, 2019 is when 1.0 was released
```

Then at release time, which let's say was September 27th, 2021, we'd make the file look like:
```yaml
after-2016-jan-01: v1.0
after-2019-jun-11: v1.1
after-2021-sep-27: unstable
```

and repeat as needed.

Does that make sense? How does it sound? Ideas?

2021-09-28 01:38 UTC, turt2live commented on content/rooms/v8.md
> +The remaining rules are the same as in [room version 7](/rooms/v7#server-implementation-components).
I was hoping to avoid doing exactly that honestly, by hoping that implementation authors would start at v1 and implement forwards, but I guess the expectation is that authors would start at $latest and move backwards in time? Either way, detailing it out each time is tedious and involves making Find All harder to use in editors.

We could approach this by breaking out the individual branches of each algorithm into templates split by room version, making it somewhat easy to build the rules without having to duplicate too much text.

Effectively, alongside https://github.com/matrix-org/matrix-doc/pull/3387#issuecomment-928571170, this would look something like:

```
{{% auth/v1/m.room.create %}}
{{% auth/v1/m.room.third_party_invite %}}
// other v1 events
{{% auth/v6/m.room.power_levels %}}

If type is `m.room.member`:
{{% auth/v1/m.room.member#ban %}}
{{% auth/v1/m.room.member#invite %}}
{{% auth/v1/m.room.member#leave %}}
{{% auth/v7/m.room.member#knock %}}
{{% new/after-2020-jun-11 %}}{{% auth/v8/m.room.member#join %}}
```

The other algorithms (like redaction) lend themselves quite nicely to this format as well.

A downside is that we'd have to remember to copy/paste the right set of variables in each room version, however this can probably be covered by CI to make sure we didn't miss anything in that copy/paste. Plus, it'd be a simple editorial error rather than something wrong with the spec needing an MSC, though dangerous if we do screw it up.

I'm quite keen to avoid as much text duplication as possible, and we have a templating system at our disposal. Do you have thoughts on how we could better represent this, or should we try using the templating system as outlined above?

2021-09-28 01:40 UTC, turt2live commented
we could also solve the dates with templates rather than a yaml map, but a map is a bit easier to maintain in a central location. Not sure if people have strong feelings about it.

2021-09-28 07:43 UTC, richvdh commented
Let's take discussion of how to solve the "record the spec version" problem to #2692.

2021-09-28 10:30 UTC, richvdh commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
Well, it sounds nice!

An alternative, possibly simpler suggestion: we add a table to https://spec.matrix.org/unstable/#room-versions, with versions (with links to `/rooms/vN`) across the top and features down the side (or possibly vice-versa). Then we link to that: "Note that this join rule is only available in room versions that support restricted rooms: see [feature matrix]".

(Incidentally: can we move the whole https://spec.matrix.org/unstable/#room-versions section to https://spec.matrix.org/unstable/rooms/ ?)

2021-09-28 10:33 UTC, richvdh commented on content/rooms/v8.md
> +   1. If membership state is `join`, allow.
yes.

2021-09-28 10:40 UTC, richvdh commented on content/rooms/v8.md
> +   3. If the event is not validly signed by the server denoted by the user ID in
Yes, it looks like the MSC might be wrong here. I'm not keen on another round of MSCs to change this nit though - can we just get it right here?

The problem is that signatures are necessarily checked before we know the current state in the room.

2021-09-28 10:52 UTC, richvdh commented on content/rooms/v8.md
> +The remaining rules are the same as in [room version 7](/rooms/v7#server-implementation-components).
> I was hoping to avoid doing exactly that honestly, by hoping that implementation authors would start at v1 and implement forwards, but I guess the expectation is that authors would start at $latest and move backwards in time? 

Maybe, but anyway it's now almost impossible to get an idea of what the auth rules are at a given room version, which makes proposing any changes to those auth rules, or debugging problems with them, an order of magnitude harder.

Honestly I feel like you're overengineering the solution; I don't really see why duplicating the list is a problem. I don't think a copy-and-paste from the previous version doc is particularly tedious, and I don't understand what it will make harder about Find All. But sure, if you want to break it down into smaller chunks that can be included as appropriate, that's fine with me.

2021-09-28 21:31 UTC, turt2live commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
I'm slightly worried that the table would become overwhelming, but it's probably okay for now? We can probably combine versions 1 through 6 into one column to cut down on width (given they don't implement "features" per-say).

and yes, we should move the whole section out of the index. It was kinda just thrown there because nowhere else fit.

2021-09-28 21:32 UTC, turt2live commented on content/rooms/v8.md
> +   3. If the event is not validly signed by the server denoted by the user ID in
👍 will engage the "minor edits" part of the process (update existing MSC doc alongside spec)

2021-09-28 21:36 UTC, turt2live commented on content/rooms/v8.md
> +The remaining rules are the same as in [room version 7](/rooms/v7#server-implementation-components).
It's just painful from a spec author perspective generally to try and navigate. Wording clarifications for instance would need to be applied N times instead of once, as an example. It's the same reason why PDUs in the server-server spec are split down to bare components: though not important for the spec given they are only rendered a couple times explicitly, they are a burden to maintain with all the subtle changes around the spec.

in short, it doesn't feel over-engineered, but I'm not exactly happy with the solution either.

2021-10-04 01:22 UTC, turt2live commented on content/client-server-api/_index.md
> +rule is only available to rooms based upon [room version 8](/rooms/v8).
I've moved the room version feature matrix out to https://github.com/matrix-org/matrix-doc/pull/3423 where this PR can wait and make use of it.

2021-10-04 01:25 UTC, turt2live commented
Update on this PR's blocked status:

* https://github.com/matrix-org/matrix-doc/pull/3425 exists for an option of annotating "added in vX"
* https://github.com/matrix-org/matrix-doc/pull/3423 exists for a room version feature matrix

Once those both land, I'll update this PR accordingly to use their new features. If #3425 in particular looks okay to folks, this PR and a new PR will make room versions verbose with the "new in this version" tag to help make it clear what is going on without needing to chase links into infinity.

2021-10-06 20:07 UTC, turt2live commented on content/rooms/v8.md
> +The remaining rules are the same as in [room version 7](/rooms/v7#server-implementation-components).
... but copy/paste feels so very wrong given the amount of unchanged text.

2021-11-18 18:04 UTC, clokep commented on content/server-server-api.md
> +    - If `content.join_authorised_via_users_server` is present,
Not sure the proper spot to have this conversation so kind of choosing an arbitrary line that has `join_authorised_via_users_server` on it:

It was found slightly after deployment that Element Web's `/myroom{nick,avatar}` feature copies the entire `m.room.member` event back to the server after modifying the requested info, this causes it to include the `join_authorised_via_users_server` *but* the event will only be signed by the user's local server (since the user is already in the room and join -> join transitions are allowed for anyone).

Synapse's solution to this was to strip out the `join_authorised_via_users_server` is received over the Client-Server API (matrix-org/synapse#10933). We considered this an implementation detail, but a conversation in matrix-org/complement#224 is making me wonder if this should be specced behavior.

2021-11-18 18:14 UTC, turt2live commented on content/server-server-api.md
> +    - If `content.join_authorised_via_users_server` is present,
We can add this to the spec as a note for implementations to be aware of

2021-12-28 16:47 UTC, turt2live commented on data/api/server-server/definitions/send_join_response.yaml
> +      Required if the room version is based upon [v8](/rooms/v8). The signed copy of the membership
> Can we just mandate it for all servers complying with this version of the spec?

Doing so sounds like a new MSC.

2021-12-28 18:09 UTC, turt2live commented on content/server-server-api.md
> +      always be eligible for inclusion.
I'm sure I had a reason, but agreed that it makes no sense now.

2021-12-28 18:12 UTC, turt2live commented
@richvdh this is ready for re-review. I've broken the commits down since your last review roughly by related review threads, though it's still not the clearest thing (sorry).

This also now adopts all the "fully specify room versions" and "added in vX" stuff.

2022-01-07 17:07 UTC, richvdh commented on changelogs/room_versions/newsfragments/3387.feature.1
> +Add Room Version 8 as per [MSC3289](https://github.com/matrix-org/matrix-doc/pull/3289).
TIL that you can have multiple newsfragments for the same ticket.

2022-01-07 17:11 UTC, turt2live commented on changelogs/room_versions/newsfragments/3387.feature.1
> +Add Room Version 8 as per [MSC3289](https://github.com/matrix-org/matrix-doc/pull/3289).
This is a towncrier feature, and one that seems to have accidentally worked in our hugo template too (we split on `.` and inspect `[1]`, so the `.1` is never inspected)

2022-01-07 17:15 UTC, richvdh commented on content/client-server-api/_index.md
>  ![membership-flow-diagram](/diagrams/membership.png)
we should probably update the `external->join` and `leave->join` edges in the diagram.

2022-01-07 18:42 UTC, richvdh requested changes
thanks for your work on this!

I'm afraid I'd completely paged out where we'd got to previously, so unlucky for you, you get a complete re-review. A few bits and bobs, hopefully nothing major.

2022-01-07 18:42 UTC, richvdh commented on content/rooms/v8.md
> +{{% rver-fragment name="v3-handling-redactions" %}}
Hrrm. Until room v7, this thing was in a separate section called ["Handling redactions"](https://spec.matrix.org/v1.1/rooms/v5/#handling-redactions) (cf ["Redactions"](https://spec.matrix.org/v1.1/rooms/v5/#redactions)). 

Notwithstanding the confusing section titles, I do think it makes sense for them to be separate sections, so I think would be better to follow the model of v3-v6 rather than v7 here, and in v9. (And we should fix v7 too, but that may be outside the scope of this PR.)

2022-01-07 18:42 UTC, richvdh commented on content/rooms/v8.md
> +### Redactions
last time we changed the redaction algorithm (v6), we did this the other way round, and put the "redactions" section under "Client considerations" (https://spec.matrix.org/v1.1/rooms/v6/#redactions), with just a link to it from "Server implementation components" (https://spec.matrix.org/v1.1/rooms/v6/#redactions-1). 

In the interests of consistency, and given more people write clients than servers, maybe we should do the same here (and in v9) ?

2022-01-07 18:42 UTC, richvdh commented on data/api/server-server/definitions/send_join_response.yaml
> +      Required if the room version [supports restricted join rules](/rooms/#feature-matrix). The signed
I think this should be *always* required as of this matrix version.

2022-01-07 18:47 UTC, richvdh commented on content/server-server-api.md
>  new event to a resident homeserver, by using the `PUT /send_join`
I think this needs to change to say *the same* resident homeserver (cf https://github.com/matrix-org/matrix-doc/blob/main/proposals/3083-restricted-rooms.md:

> they must now both go to the same server

2022-01-07 18:49 UTC, turt2live commented on content/rooms/fragments/v8-auth-rules.md
> +    2.  If `content` has `join_authorised_via_users_server`
I'll apply this fix here, but the awkward language persists through the whole list.

2022-01-10 02:37 UTC, turt2live commented on content/client-server-api/_index.md
> +rule is only available in room versions [which support it](/rooms/#feature-matrix).
it's probably best to defer it to #2660 - for now I'll change the wording to "only expected to work in versions" rather than try and figure out the subtleties of #2660

2022-01-10 02:44 UTC, turt2live commented on content/client-server-api/_index.md
> +Restricted rooms are rooms with a `join_rule` of `restricted`. These rooms
applied manually

2022-01-10 02:44 UTC, turt2live commented on content/client-server-api/_index.md
> +checked/evaluated during the join process.
applied manually

2022-01-10 02:45 UTC, turt2live commented on content/rooms/fragments/v8-auth-rules.md
> +    2.  If `content` has `join_authorised_via_users_server`
applied manually

2022-01-10 02:53 UTC, turt2live commented on data/api/server-server/definitions/send_join_response.yaml
> +      Required if the room version [supports restricted join rules](/rooms/#feature-matrix). The signed
The MSC doesn't call for this, and Synapse doesn't appear to check it that way. Source?

2022-01-10 03:13 UTC, turt2live commented on content/server-server-api.md
>  new event to a resident homeserver, by using the `PUT /send_join`
I'm not entirely convinced - brought up internally for now.

2022-01-10 03:16 UTC, turt2live commented
blocked on internal SCT review.

2022-01-10 12:00 UTC, clokep commented on content/server-server-api.md
>  new event to a resident homeserver, by using the `PUT /send_join`
The MSC is written in such a way that the directory/resident servers are the same, but after implementing I realized this isn't actually required, even for restricted joins. The directory server really just needs to add the MXID of a user who can issue invites, then the resident server should be able to appropriately sign the event and add it to the room. This all seemed rather complicated, however.

2022-01-10 21:03 UTC, turt2live commented
conclusion from internally appears to be that these do indeed only affect requests with the given room version - to capture the nuance, we'll probably want to look at adjusting the "Joining Rooms" section of the spec to cover signatures, residents, etc.

The original worry was that suggestions to change the spec implied that the process was changed universally, which is not the case. 

Still blocked on me adapting the notes to the PR though.

2022-01-18 00:33 UTC, turt2live commented
@richvdh this should be ready for re-review.

2022-01-18 15:40 UTC, richvdh commented on content/client-server-api/_index.md
>  ![membership-flow-diagram](/diagrams/membership.png)
do you think it's ok to leave the `leave`->`join` transition as "/join if public join_rules"? I'm not sure, it's maybe fine.

while we're at it, why isn't there a `leave`->`knock` transition?

2022-01-18 15:40 UTC, richvdh commented on content/rooms/v7.md
> +### Handling redactions
it'd be nice if we could figure out what order these things go in (in v5 'Handling redactions' is before 'Event IDs' and 'Event format'), but I guess I'm just nit-picking really.

2022-01-18 15:58 UTC, turt2live commented on content/rooms/v7.md
> +### Handling redactions
they're supposed to be consistent, but that ship sailed when I thought they were consistent last time. Will attempt to fix in a future PR.

2022-01-18 16:54 UTC, turt2live commented on content/client-server-api/_index.md
>  ![membership-flow-diagram](/diagrams/membership.png)
updated, reviewed oob.

2022-01-18 16:55 UTC, turt2live commented on content/rooms/v7.md
> +### Handling redactions
https://github.com/matrix-org/matrix-doc/issues/3656

2022-01-18 16:55 UTC, merged