Explicitly link to geo URI spec
matrix-org/matrix-doc pull request #3492
Opened 2021-11-15 11:11 UTC by Half-Shot

We mention geo uri in the spec, but unhelpfully do not link to any documentation on what those are. This PR explicitly names the RFC and links to it. I am unsure if this needs a MSC, since I believe it doesn't change the spec in a meaningful way and just clarifies which RFC we're talking about.

If this needs a proposal, happy to open one first.

2021-11-15 11:28 UTC, anoadragon453 commented
Seeing as that RFC looks to be what the spec was originally referring to (and matches the example event body), then this is just a clarification - and as such does not need an MSC.

2021-11-15 21:33 UTC, turt2live requested changes
otherwise lgtm. Please add a changelog entry :)

2021-11-15 21:33 UTC, turt2live commented on data/event-schemas/schema/m.room.message$m.location.yaml
> +        description: A [geo URI](https://datatracker.ietf.org/doc/html/rfc5870) (RFC5870) representing this location.
nitpick:
```suggestion
        description: A [geo URI (RFC5870)](https://datatracker.ietf.org/doc/html/rfc5870) representing this location.
```

2021-11-15 22:58 UTC, turt2live approved these changes
Thanks :)

2021-11-15 22:58 UTC, merged

2021-11-24 10:03 UTC, shenanigans77-jpg approved these changes