Move `prev_content` to unsigned
matrix-org/matrix-doc pull request #3524
Opened 2021-11-23 23:03 UTC by richvdh

Per [MSC3442](https://github.com/matrix-org/matrix-doc/pull/3442), `prev_content` should be under unsigned.

I wanted to document its history properly, so ended up adding some magic to the openapi-table-renderer to do so. I think we should probably use this to replace the existing `x-addedInMatrixVersion` annotations, but have left this for a future PR.

2021-11-23 23:29 UTC, turt2live requested changes

2021-11-23 23:29 UTC, turt2live commented on layouts/partials/openapi/render-object-table.html
> +  </td>
annoyingly, this needs to be a single line to avoid breaking the rendering. It will treat a lot of this as block elements, which expands the page length by about 40% (when I last tried).

2021-11-23 23:29 UTC, turt2live commented on changelogs/client_server/newsfragments/3524.breaking
> +The `prev_content` field is now returned inside the `unsigned` property of events, rather than at the top level.
```suggestion
The `prev_content` field is now returned inside the `unsigned` property of events, rather than at the top level, as per [MSC3442](https://github.com/matrix-org/matrix-doc/pull/3442).
```

2021-11-23 23:29 UTC, turt2live commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
The original intent was to make this be `x-addedInMatrixVersion: "1.2"` which automatically adds similar text to a bunch of places. I'm not entirely sure that we need a distinct "changed" state, and the changelog/link to PR should be more than enough for readers to figure out what happened. The MSC link is also intended to serve this purpose.

2021-11-23 23:30 UTC, richvdh commented on layouts/partials/openapi/render-object-table.html
> +  </td>
Are you sure? The rendered output looks ok to me. The `-`s in the `{{ end }}` are strategic.

2021-11-23 23:31 UTC, turt2live commented on layouts/partials/openapi/render-object-table.html
> +  </td>
strategic in what sense? It looks like magic and I didn't even see it at first glance.

2021-11-23 23:33 UTC, richvdh commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
In this particular case, given the upshot is "actually you don't need to care about this", I guess there is an argument that it doesn't need to be here. But in the more general case, I think "here's what changed" is much more useful than "something changed, you can figure it out".

My cue here is Python documentation, which I think gets this right. See for example https://docs.python.org/3/library/functions.html#classmethod, which documents a number of changes in various versions.

2021-11-23 23:36 UTC, richvdh commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
(I'm certainly happy to drop the special-casing for `this` and hardcode `1.2` here though)

2021-11-23 23:37 UTC, turt2live commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
I'm unsure how this is different from a note block though, as these sorts of extensions are really not meant to be normative.

Will spend some time thinking about it this week.

2021-11-23 23:38 UTC, richvdh commented on layouts/partials/openapi/render-object-table.html
> +  </td>
It means "ignore the whitespace after this tag": https://gohugo.io/templates/introduction/#whitespace.

Strategic in the sense that I tested it was in the right place and did the right thing with various combinations.

2021-11-30 16:53 UTC, richvdh commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
the difficulty is that note blocks don't render correctly inside the definition of a parameter (and attempts to do so tend to render *terribly* on the openapi UI.

That said, maybe a better solution is a generic way of adding note blocks to parameter defs?

2021-11-30 17:57 UTC, richvdh commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
> (I'm certainly happy to drop the special-casing for `this` and hardcode `1.2` here though)

this is done.

2021-12-01 17:05 UTC, turt2live commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
right, so having thought about it I don't really see a short term solution for it so might as well land it. I'm not a huge fan of normative text being outside the regular places (`description` or the markdown doc itself), but, again, it's just not feasible to implement a better system in the immediate term.

Possibly something for consideration in the next round of platform improvements. Long term, it'd be great to find a way to have the markdown be legible as an independent document away from the website, with the details of the endpoints and their changes being purely described by the OpenAPI parts. This gets us closer to improved ability to read the spec offline as well as make edits to places. (also, just to note, I am also the same person that advocated that we break the repeatable parts of the room version spec out to multiple templates when possible - still trying to find a good balance of "usable markdown" and "reasonable to author")

The only request at this point is to document it in the OpenAPI Extensions document we have somewhere, and preferably template it out to a similar degree as the added-in variant (so we don't have to do it later).

2021-12-01 17:59 UTC, richvdh commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> +        this.
> The only request at this point is to document it in the OpenAPI Extensions document we have somewhere, and preferably template it out to a similar degree as the added-in variant (so we don't have to do it later).

done, I think?

2021-12-02 17:12 UTC, turt2live approved these changes
thanks, and apologies for the long turnaround on this.

2021-12-02 17:22 UTC, merged