Responses schema fixes
matrix-org/matrix-doc pull request #3650
Opened 2022-01-17 08:01 UTC by afranke

Fixes #2237.

2022-01-17 14:09 UTC, turt2live requested changes
It looks like some of these are introducing response bodies rather than clarifying them - evidence to support that synapse has always done this would be appreciated, otherwise an MSC is likely required.

2022-01-18 09:40 UTC, afranke commented
I have now checked in Synapse and can confirm that all these responses have a `return 200, {}`.

[`PUT /user/{user_id}/account_data/{account_dataType}`](https://github.com/matrix-org/synapse/blob/develop/synapse/rest/client/account_data.py#L59)
[`PUT /user/{user_id}/rooms/{roomId}/account_data/{type}`](https://github.com/matrix-org/synapse/blob/develop/synapse/rest/client/account_data.py#L120)
[`PUT /room_keys/version/{version}`](https://github.com/matrix-org/synapse/blob/develop/synapse/rest/client/room_keys.py#L357)
[`PUT /directory/list/room/{roomId}`](https://github.com/matrix-org/synapse/blob/develop/synapse/rest/client/directory.py#L155)
[`PUT "/sendToDevice/{eventType}/{txnId}`](https://github.com/matrix-org/synapse/blob/develop/synapse/rest/client/sendtodevice.py#L68)

Is that enough for you?

2022-01-18 16:11 UTC, richvdh commented on data/api/client-server/administrative_contact.yaml
> +                example: "https://example.org/path/to/submitToken"
it's not made clear in the PR description, but this seems to be correcting some incorrect indentation as noted in https://github.com/matrix-org/matrix-doc/issues/2237.

It concerns `POST /account/3pid`.

2022-01-18 16:17 UTC, richvdh commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
this is just adding an example for [`PUT /room_keys/version/{version}`](https://spec.matrix.org/v1.1/client-server-api/#put_matrixclientv3room_keysversionversion), afaict.

However, looking at the [preview](https://pr3650--matrix-org-previews.netlify.app/client-server-api/#put_matrixclientv3room_keysversionversion), I don't think it's actually worked.

2022-01-18 16:28 UTC, turt2live commented
for the endpoints we mostly just need evidence that it's always returned these things prior to 1.0 (roughly).

Adjusted links to account for time:
[`PUT /user/{user_id}/account_data/{account_dataType}`](https://github.com/matrix-org/synapse/blame/18a466b84e52b6e8c51a878e612d86410d6af680/synapse/rest/client/v2_alpha/account_data.py#L58)
[`PUT /user/{user_id}/rooms/{roomId}/account_data/{type}`](https://github.com/matrix-org/synapse/blame/18a466b84e52b6e8c51a878e612d86410d6af680/synapse/rest/client/v2_alpha/account_data.py#L115)
[`PUT /room_keys/version/{version}`](https://github.com/matrix-org/synapse/blame/18a466b84e52b6e8c51a878e612d86410d6af680/synapse/rest/client/v2_alpha/room_keys.py#L361) (intent carried from unstable implementation)
[`PUT /directory/list/room/{roomId}`](https://github.com/matrix-org/synapse/blame/18a466b84e52b6e8c51a878e612d86410d6af680/synapse/rest/client/v1/directory.py#L121)
[`PUT /sendToDevice/{eventType}/{txnId}`](https://github.com/matrix-org/synapse/blame/18a466b84e52b6e8c51a878e612d86410d6af680/synapse/rest/client/v2_alpha/sendtodevice.py#L62)

2022-01-18 16:40 UTC, afranke commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
Opening the generated JSON file with a viewer such as https://mrin9.github.io/RapiDoc/examples/petstore-extended.html shows the added example as expected though. :thinking:

2022-01-18 16:41 UTC, afranke commented on data/api/client-server/administrative_contact.yaml
> +                example: "https://example.org/path/to/submitToken"
It is explicited in the commit message for that change.

2022-01-18 17:01 UTC, richvdh requested changes
this is fine except... it doesn't seem to have worked? None of the modified endpoints (with the exception of `/account/3pid`, which has a non-empty body) show a response body in the preview.

2022-01-18 17:02 UTC, afranke commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
That was with a locally generated file BTW. Still investigating, but from what I can see in the artifact, the change is not taken into account.

2022-01-18 17:04 UTC, richvdh commented
also, you might want to merge in main, to pick up https://github.com/matrix-org/matrix-doc/commit/97a8b0bb1376f721604b9c8ba901b2de667967ba, to fix the CI

2022-01-18 17:15 UTC, afranke commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
Nevermind, it looks as expected on line 12736 of the JSON artifact.

2022-01-18 17:20 UTC, afranke commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
`POST /_matrix/client/v3/rooms/{roomId}/receipt/{receiptType}/{eventId}` is an example of another 200 response with the same `examples` content that also doesn’t render in the spec website preview, and I haven’t touched that one. This seems to be a pre-existing bug with the hugo rendering. Out of scope for this PR?

2022-01-18 17:30 UTC, richvdh commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
> Out of scope for this PR?

probably, but I think it would be best to consider fixing it a prerequisite for landing this PR, so that we can check this PR actually does what is expected.

2022-01-19 16:26 UTC, afranke commented
> this is fine except... it doesn't seem to have worked? None of the modified endpoints (with the exception of `/account/3pid`, which has a non-empty body) show a response body in the preview.

As I said in the review-conversation above, it does work: the artifact contains the expected bits and this can be verified by opening the file [with a viewer](https://mrin9.github.io/RapiDoc/examples/petstore-extended.html).

> also, you might want to merge in main, to pick up 97a8b0b, to fix the CI

This goes beyond my understanding of Github Pull Requests and Reviews, in the sense that I don’t know how to do that in a way that I am certain will not break something for someone here. With Gitlab, I know that I could just rebase the branch on top of main and everything would be fine for everyone, but I know doing this with Github makes everyone unhappy.

Since we know for a fact the red thing in CI is fixed in main, has nothing to do with the changes here, and this PR will end up “Squashed and merged” anyway, do we really need to worry about this?

2022-01-19 17:18 UTC, richvdh commented
> do we really need to worry about this?

no, but it's easier just to do it than verify the cause of the CI failure:
```
git fetch
git merge origin/main
git push
```

and yes, please don't rebase!

2022-01-25 18:14 UTC, richvdh commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
#3650 hopefully fixes the hugo rendering bug, so once it has landed, we can double-check that this PR is doing the right thing.

2022-01-25 18:58 UTC, afranke commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
Rich meant #3674 for anyone trying to follow along. 3650 is this one here.

2022-01-26 09:14 UTC, afranke commented
> It looks like some of these are introducing response bodies rather than clarifying them - evidence to support that synapse has always done this would be appreciated, otherwise an MSC is likely required.

Considering this has been confirmed to be synapse’s behaviour, is `clarification` indeed the type I need to add for the changelog?

2022-01-26 10:53 UTC, richvdh commented on data/api/client-server/key_backup.yaml
> +            application/json: {}
:facepalm:

2022-01-26 11:07 UTC, richvdh commented
> Considering this has been confirmed to be synapse’s behaviour, is clarification indeed the type I need to add for the changelog?

Yes I think so. Thanks!

2022-01-26 12:35 UTC, richvdh commented on data/api/client-server/key_backup.yaml
> -            properties: {}
For the record, I think this ends up being pretty much a no-op. An object with *no* `properties` is the same as one with an *empty* `properties`, and the auto-generated example looks the same as the one we are creating here.

2022-01-26 12:42 UTC, richvdh commented
(have updated the PR description to make it clear which endpoints we're fixing here)

2022-01-26 12:45 UTC, richvdh approved these changes
LGTM other than the changelog.

2022-01-26 12:45 UTC, richvdh commented on changelogs/client_server/newsfragments/3650.clarification
> +Make empty 200 responses for puts consistent
It would be good to be clearer here. For one thing, it's not just empty responses, and it's not just `PUT`s which are affected.

How about:

```suggestion
Correct the schema for the responses  for various API endpoints.
```

Normally I'd say that we should say exactly which endpoints we're fixing, but I think that will be a bit verbose and people who care can click through to the PR.
```

2022-01-26 13:03 UTC, afranke commented on data/api/client-server/key_backup.yaml
> -            properties: {}
Maybe, but that wouldn’t be consistent with what we have for other cases. Is there anything to change here or can we mark this resolved?

2022-01-26 13:04 UTC, richvdh commented on data/api/client-server/key_backup.yaml
> -            properties: {}
nope, just calling it out explicitly for future reference.  I'd leave the thread open for future viewers.

2022-01-31 10:31 UTC, merged