Distinguish 'serialised' from 'raw' events
matrix-org/matrix-doc pull request #3658
Opened 2022-01-19 12:11 UTC by richvdh

Fixes #3305
Fixes #3380

The idea here is to better distinguish between a 'raw' event (as we send over the wire), and the 'serialised' format, as sent in responses to the C-S api and in `PUT /_matrix/app/v1/transactions/{txnId}`.

It's made more complicated by the fact that there are *two* serialisation formats, one used by `/sync` and `/notifications`, and one by everything else (the difference being whether `room_id` is included).

In an ideal world, we wouldn't repeat `SerialisedEvent` every time it's used, and instead just link to the first reference, bit that's a job for another day.

2022-01-19 12:14 UTC, richvdh commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
> -    type: object
all this stuff has moved into the definition for `serialised_event`, because it's not sent over the federation API, so IMHO doesn't belong in the core event schema.

2022-01-19 12:16 UTC, richvdh commented
looks like I need to figure out why the validator is failing.

2022-01-25 20:49 UTC, turt2live requested changes
generally the changes seem fine - mostly just relatively minor concerns and taking the opportunity to fix some other small pet peeves while we're in the area.

2022-01-25 20:49 UTC, turt2live commented on changelogs/client_server/newsfragments/3658.clarification
> +Distinguish between "raw" event format as exchanged by the Federation API, and the "serialised" event formats as used in the client-server and AS APIs.
please also include an AS API changelog

2022-01-25 20:49 UTC, turt2live commented on content/client-server-api/_index.md
> +version"](/rooms) in use by the room. See, for example, the defintions
```suggestion
version"](/rooms) in use by the room. See, for example, the definitions
```

2022-01-25 20:49 UTC, turt2live commented on data/api/client-server/definitions/serialised_event.yaml
> +# Copyright 2016-2021 The Matrix.org Foundation C.I.C.
Incorrect copyright?

2022-01-25 20:49 UTC, turt2live commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +# Copyright 2016-2021 The Matrix.org Foundation C.I.C.
incorrect copyright?

2022-01-25 20:49 UTC, turt2live commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +  API endpoints such as `/sync`, where the room_id is implied elsewhere
```suggestion
  API endpoints such as `/sync`, where the `room_id` is implied elsewhere
```

2022-01-25 20:49 UTC, turt2live commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +    example: '$143273582443PhrSn'
If we're going to use the v4 format, then we should use a valid v4-looking identifier (this is very obviously a v1 event with the domain trimmed off)

See also:
* https://github.com/matrix-org/matrix-doc/issues/2018
* https://github.com/matrix-org/matrix-doc/issues/2759

(not expected to fix either in this PR, but ideally we shouldn't make it harder to find the cases that will need fixing down the road)

2022-01-25 20:49 UTC, turt2live commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +      this piece of state unique in the room.
We should note that this might be an empty string

2022-01-25 20:49 UTC, turt2live commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +  - content
isn't `unsigned` required, if only ever empty?

2022-01-25 20:49 UTC, turt2live commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +        title: SerialisedEventWithoutRoomID
this should get an example to highlight the recursive nature of the types

2022-01-25 20:49 UTC, turt2live commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
>    age:
as the now-supposed federation format, is `age` really ever sent? It seems pretty pointless to include over such APIs

2022-01-25 20:49 UTC, turt2live commented on changelogs/client_server/newsfragments/3658.clarification
> +Distinguish between "raw" event format as exchanged by the Federation API, and the "serialised" event formats as used in the client-server and AS APIs.
"raw" and "serialised" feel like the wrong words for the format of the event - can we use the naming used in #3305 instead? ("client" and "federation")

2022-01-26 11:05 UTC, richvdh commented on data/event-schemas/schema/core-event-schema/unsigned_prop.yaml
>    age:
It's certainly sent. Whether or not it is useful is a different question: https://github.com/matrix-org/synapse/issues/8429

2022-01-26 11:32 UTC, richvdh commented on data/api/client-server/definitions/serialised_event.yaml
> +# Copyright 2016-2021 The Matrix.org Foundation C.I.C.
```suggestion
# Copyright 2022 The Matrix.org Foundation C.I.C.
```

2022-01-26 11:32 UTC, richvdh commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +# Copyright 2016-2021 The Matrix.org Foundation C.I.C.
```suggestion
# Copyright 2022 The Matrix.org Foundation C.I.C.
```

2022-01-26 11:32 UTC, richvdh commented on changelogs/client_server/newsfragments/3658.clarification
> +Distinguish between "raw" event format as exchanged by the Federation API, and the "serialised" event formats as used in the client-server and AS APIs.
hrm I guess so. I'm not sure that "client event" is a brilliant name either. 

I take it you'd want me to rename all the yaml files too? `serialised_event.yaml` -> `client_event.yaml` ?

2022-01-26 11:32 UTC, richvdh commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +  - content
hrm, good question.

In practice it always has at least an `age`, so is always there. OTOH, the spec to date has never mandated the presence of either `age` or `unsigned` (https://spec.matrix.org/v1.1/client-server-api/#room-event-fields) so this begins to feel like a spec *change* rather than a clarification.

I could go either way, tbh.

2022-01-26 11:32 UTC, richvdh commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +    example: '$143273582443PhrSn'
```suggestion
    example: '$26RqwJMLw-yds1GAH_QxjHRC1Da9oasK0e5VLnck_45'
```

2022-01-26 11:32 UTC, richvdh commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +      this piece of state unique in the room.
```suggestion
      Present if, and only if, this event is a *state* event. The key making
      this piece of state unique in the room. Note that it is often an empty
      string.
```

2022-01-26 16:36 UTC, turt2live commented on data/api/client-server/definitions/serialised_event_without_room_id.yaml
> +  - content
have opened https://github.com/matrix-org/matrix-doc/issues/3677 to deal with the rabbit hole - we can leave it alone in this PR.

2022-01-26 16:37 UTC, turt2live commented on changelogs/client_server/newsfragments/3658.clarification
> +Distinguish between "raw" event format as exchanged by the Federation API, and the "serialised" event formats as used in the client-server and AS APIs.
preferably, yea. My rationale for calling it "client event" is mostly that appservices should know that they are fundamentally clients so it should be okay (and if it isn't, then we can fix it with guides rather than spec).

2022-01-31 00:27 UTC, richvdh commented on changelogs/client_server/newsfragments/3658.clarification
> +Distinguish between "raw" event format as exchanged by the Federation API, and the "serialised" event formats as used in the client-server and AS APIs.
done, in a7050ccb5134d42c1032d68ce836800c1226b35d

2022-01-31 00:27 UTC, richvdh commented on changelogs/client_server/newsfragments/3658.clarification
> +Distinguish between "raw" event format as exchanged by the Federation API, and the "serialised" event formats as used in the client-server and AS APIs.
done, in a7050ccb5134d42c1032d68ce836800c1226b35d

2022-02-01 02:14 UTC, turt2live approved these changes
thanks!

2022-02-01 15:05 UTC, merged