Remove 'room_id' field from EDU example
matrix-org/matrix-doc pull request #3679
Opened 2022-01-26 18:28 UTC by anoadragon453

It was discovered [here](https://github.com/matrix-org/matrix-doc/pull/2477/files/2f4dd474f3cd314f8637e925b357d7d51ed3e634#r750565554) that the spec had an erroneous `room_id` field in a EDU's `/sync` entry. This change removes the field from both the `m.typing` `/sync` response example and the example in the CS definition of `m.receipt`.

The field was initially introduced in https://github.com/matrix-org/matrix-doc/commit/0f28f8327021c43632678d4d54f5753c7cd021ec#diff-8d917764f05b0823bc6aee1f9a74895d38df32fb1eeb10c18a55d9120cf23cb2R3.

2022-01-26 19:04 UTC, turt2live requested changes
This change feels wrong - a `room_edu` is in a room, so needs a room ID. Not all EDUs use a top-level `room_id` though, so possibly just a badly written example somewhere specific?

2022-01-27 10:23 UTC, richvdh commented
> This change feels wrong - a room_edu is in a room, so needs a room ID. 

I think the confusion here stems from the fact that typing events (and, for that matter, EDUs in general) have a different format when sent over the federation API (where they do have a `room_id`) than when sent in a `/sync` response (where the room is implied by the position in the `/sync` response).

I haven't checked, but I *think* this file is only used when rendering the `/sync` response, so is probably correct?

2022-01-27 14:05 UTC, anoadragon453 commented
@richvdh I believe so, though CI seems to be unhappy.

We should perhaps rename this in some way so that it's explicitly client-specific?

2022-01-27 18:17 UTC, turt2live commented
The CI is failing because the schema and the example don't match - this PR only touches the example, not the schema.

2022-02-08 20:22 UTC, anoadragon453 commented
I have updated the schema, and CI now passes. I also discovered that `m.fully_read` is affected by this. So `room_id` has been removed in the appropriate places as well.

I've only been verifying against Synapse/Element here. I need to check other implementations to see if these fields are being relied upon.

2022-02-08 21:34 UTC, aaronraimist commented
This should fix https://github.com/matrix-org/matrix-doc/issues/3183

2022-02-15 21:20 UTC, turt2live submitted a review, later dismissed
lgtm - just need a changelog to denote the bugfix in the spec prose

2022-03-01 16:16 UTC, richvdh approved these changes
lgtm

2022-03-01 16:18 UTC, merged