Fix missed rst->md numbered list syntax for `m.room.server_acl`
matrix-org/matrix-doc pull request #3681
Opened 2022-01-27 15:03 UTC by anoadragon453

There was some left-over RST syntax which was causing a numbered list to have broken formatting:

![image](https://user-images.githubusercontent.com/1342360/151385183-4e8f1726-97fa-47f8-b4d5-7b71f89dc7a5.png)

This PR applies the equivalent markdown syntax.

2022-01-27 17:38 UTC, uhoreg approved these changes
Looks like it does exactly what it says on the box.

2022-01-27 18:07 UTC, turt2live requested changes
please can we use real numbers and not markdown trickery

2022-01-27 18:36 UTC, anoadragon453 commented
> please can we use real numbers and not markdown trickery

Oh, why do you prefer real numbers? I find the advantage of this is that items can be added to the list without having to reflow the numbers.

2022-01-27 18:46 UTC, turt2live commented
It's so that the raw markdown can theoretically be used as a reference without the HTML rendering, and to make review easier down the line when we say "Rule 4 is changed"

2022-01-28 09:29 UTC, anoadragon453 commented
Thank you, I hadn't considered those points. That sounds like reason enough to change it.

2022-01-28 16:02 UTC, turt2live approved these changes
thanks :)

This should also get a typos changelog (copy/paste from an existing one)

2022-01-28 16:02 UTC, turt2live commented
oh, it has a changelog and I'm blind.

2022-02-06 17:49 UTC, merged