Fix m.login.appservice -> m.login.application_service
matrix-org/matrix-doc pull request #3711
Opened 2022-02-05 22:52 UTC by Half-Shot

Implementations seem to agree with the proposal, so I'd suggest we fix the typo in the spec. I don't *think* this needs a MSC as the original proposal was fine, and this was just a copy error.

2022-02-07 13:20 UTC, anoadragon453 requested changes
I don't see any mention of `m.login.appservice` across GitHub (https://cs.github.com/?scopeName=All+repos&scope=&q=%22m.login.appservice%22) other than matrix-doc (this repo) and matrix.org (the [v1.2 blogpost](https://github.com/matrix-org/matrix.org/blob/98e4134f863de2e2d83a67f3587ffcd2d6839cfc/gatsby/content/blog/2022/02/2022-02-02-matrix-1.2.mdx?q=%22m.login.appservice%22#L70)). Checking [Conduit](https://gitlab.com/famedly/conduit/), [FluffyChat](https://gitlab.com/famedly/fluffychat/) and the [Beeper group](https://gitlab.com/beeper) over on GitLab also yields only results for the correct identifier.

As such, I'm satisfied that implementations look to have done the right thing, and that this typo can just be fixed without an MSC.

2022-02-07 13:20 UTC, anoadragon453 commented on content/client-server-api/_index.md
> +  "type": "m.login.application_service",
This will need a changelog though :) Example: https://github.com/matrix-org/matrix-doc/pull/3681/files#diff-afd89be3d53ef4a01b8c781ff753495342ce21476afe841051066c31b567e6ecR1

2022-02-14 17:15 UTC, turt2live commented on changelogs/3711.clarification
> +Clarify that `m.login.application_service` should be used for appservice logins, rather than `m.login.appservice`.
I think it'd be good to phrase this as a bug:
```suggestion
Fix incorrectly referenced `m.login.appservice` login identifier, instead using `m.login.application_service`.
```

2022-02-14 18:14 UTC, anoadragon453 approved these changes
Thank you!

2022-02-14 18:22 UTC, merged