MSCxxxx: Matrix architecture change to delegate authentication via OIDC
matrix-org/matrix-doc pull request #3861
Opened 2022-08-04 16:50 UTC by hughns

2022-08-09 14:08 UTC, MTRNord commented on proposals/3861-delegated-oidc-architecture.md
> +- 👍 Simpler for Homeservers and clients to implement
I disagree. It is harder for apps and native (as in QT and others) to implement. The user has to be redirected either to a browser where then the app needs to either handle a custom proto or a webserver for the callback, or they need a webview which usually involves compiling a full chromium suite which extremely increases compile times and makes you have to do way more regular updating of the client due to the rapid amount of security issues within chromium. It overall adds a lot of complexity to the update process and especially makes the experience worse for small client devs imho.

2022-08-09 14:08 UTC, MTRNord commented on proposals/3861-delegated-oidc-architecture.md
> +  - logging into multiple clients on the same device without entering the credentials multiple times
Is this actually a thing SSO/OIDC solve? Wouldn't this be a thing WebAuthn solves?

Also who actually uses _THE SAME_ account multiple times on the same device? Aren't you usually using the same client with _DIFFERENT_ accounts? This usecase seems either fabricated to me or customer specific

2022-08-09 14:08 UTC, MTRNord commented on proposals/3861-delegated-oidc-architecture.md
> +  - having the credentials bound to the auth server domain instead of the client (for password managers and WebAuthn)
I would prefer if the server does only know a hash of my password. This is usually the main issue with major security breaches. Matrix should do an best effort to prevent those.

2022-08-09 14:08 UTC, MTRNord commented on proposals/3861-delegated-oidc-architecture.md
> +1. Close all existing MSCs relating to non-OIDC as `obsolete`.
Please make sure to check if those are actually solved by this when doing it. There might be some around that OIDC does not fix but actually complicates, like the Concealed login MSC.

2022-08-09 14:39 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +  - logging into multiple clients on the same device without entering the credentials multiple times
This will become in my opinion a pretty common use case, as we see other non-chat applications built on Matrix. On the same device you might be logged in your chat client, on your [`synapse-admin` panel](https://github.com/Awesome-Technologies/synapse-admin), in [Cactus Comments](https://cactus.chat), in Element Call, etc.

This does not change anything in terms of having multiple accounts on the same chat client.

Regarding WebAuthN, this is impossible to achieve with the current architecture, as WebAuthN credentials are bound the domain. If you create a WebAuthN credential from the `chat.example.com` origin, it won't be available on `another.app.org`. Here, since we're always requesting the credentials from the same origin (let's say, `auth.matrix.org`), we can bind WebAuthN credentials to that domain, and password managers will get a lot more useful.

2022-08-09 14:39 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +  - having the credentials bound to the auth server domain instead of the client (for password managers and WebAuthn)
I'm not sure I understand your concern. Right now, even though it's not enforced by the spec it's the cause.

We would be in the same situation here: the server will most probably store the password as hashed, not in plain text

2022-08-09 14:39 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +- 👍 Simpler for Homeservers and clients to implement
I think the main point here is the abondance of off-the-shelf libraries to handle OAuth/OIDC, which helps with implementation for clients. For example, QT has an official module to handle OAuth2/OIDC logins that you might want to check out: https://doc.qt.io/qt-6/qtnetworkauth-index.html
Your point on custom proto or web server for the callback is valid (it's handled by the QT module with a local web server), although it is already the case with `m.login.sso`, which is used by a large portion of the user base (30% of Matrix.org, IIRC).

2022-08-09 14:39 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 We're training our users to enter their Matrix credentials in random web pages and native apps
It is different in the sense that we would be building trust between the user and their homeserver. Right now, the user does not interact with their HS much. Here, it would make it easier for user to understand that their account is living on their HS, and therefore they should only ever enter their account credentials on a web page controlled by their homeserver, not some random web application which claims to be a secure Matrix client.

2022-08-09 14:39 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +1. Close all existing MSCs relating to non-OIDC as `obsolete`.
That is a good point. We should spend some time identifying those MSCs sooner than later, and see for each MSC if either:

 - it solves the problem solved by the MSC
 - the tradeoffs are acceptable if it is conceptually orthogonal

2022-08-11 16:38 UTC, deepbluev7 commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 We're training our users to enter their Matrix credentials in random web pages and native apps
I don't think this provides any actual protection though, unless you whitelist specific apps to be trusted.

As long as the login page has a somewhat standard layout, unless I am missing something, it is trivial for a native client to replace the login page behind the scenes for the user or just inject code into the website to steal credentials.

You can only somewhat prevent that by not using a password at all and instead requiring a second device to authenticate the login or 2FA, which is orthogonal to OIDC.

Also, it's a bad idea to use an untrusted client for E2EE anyway. Under those circumstances you should rather be distrustful of the server instead of your client.

2022-08-11 17:11 UTC, deepbluev7 commented on proposals/3861-delegated-oidc-architecture.md
> +- 👍 Simpler for Homeservers and clients to implement
Even with the OAuth module in Qt, the implementation is not really trivial and you usually need to test specifically against each OIDC provider to know if it is working properly, which is a lot more work than testing against 3 different homeservers. Google OAuth for example is very well known for changing in incompatible ways quite often (last time I tried it, it couldn't work with Google at all, but I assume they fixed that in the last few years). Here are a few of the potential pitfalls: https://appfluence.com/productivity/how-to-authenticate-qt-google-sso/

(The code in that example is about half as long as the UIA code in Nheko, so the implementation benefits don't seem to be particularly great considering that most of the UIA code is just putting stuff into a pretty UI so that it looks well integrated into the client.)

2022-08-11 17:39 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 We're training our users to enter their Matrix credentials in random web pages and native apps
> I don't think this provides any actual protection though, unless you whitelist specific apps to be trusted.

I'm having a hard time understanding what you mean here. What kind of whitelist are we talking about? The login page would usually be shown in the default browser, even for native apps. Sure, showing a web view embedded in your native app is tempting (and completely possible), but you usually avoid that because:

 - you would not share the cookie jar with the browser, meaning that your user would have to log in again even though they might already be logged in their browser 
 - you would not access whatever passsword manager the system has easily. If you leverage the default browser, the login page would have the right origin associated with the login page, which means it would suggest the right entries instead of having the user manually look for the right entry 
 - the user usually has pretty good trust in their default browser, and know where to look for to know on which origin/website they are on. Sure, it's not fool proof, and phishing attacks are possible, but it is still probably better 

> As long as the login page has a somewhat standard layout, unless I am missing something, it is trivial for a native client to replace the login page behind the scenes for the user or just inject code into the website to steal credentials.

If you do the login in an embedded web view, sure, but not in the system browser. Also note that on both Android and iOS, the system has APIs to open 'browser' views without changing apps. I recommend checking out the GIFs about that on https://areoidcyet.com/

> You can only somewhat prevent that by not using a password at all and instead requiring a second device to authenticate the login or 2FA, which is orthogonal to OIDC.

What do you mean by 'orthogonal'? Getting beyond passwords is very much one goal that would be easier to achieve with OIDC: you can imagine any kind of credentials (TOTP based 2FA, WebAuthN based login/2FA, or even a one-time-code sent via a Matrix DM) without having to add it to the spec. Implement that on your OIDC server, and you have support in every single Matrix client (assuming we manage to migrate those clients to OIDC) without modifying them

> Also, it's a bad idea to use an untrusted client for E2EE anyway. Under those circumstances you should rather be distrustful of the server instead of your client.

That does not change, your server still doesn't have your keys. What changes though, is that a bad client can't take over your account anymore: it can't change your password, logout from other sessions or even deactivate your account.

2022-08-11 18:20 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +- 👍 Simpler for Homeservers and clients to implement
> Even with the OAuth module in Qt, the implementation is not really trivial and you usually need to test specifically against each OIDC provider to know if it is working properly, which is a lot more work than testing against 3 different homeservers. 

There are indeed non-compliant 'OIDC' providers in the wild ('sign in with Apple' is a well-known example of that), as well as a lot of different scenarios to potentially support because of evolving best practices. OIDC is itself an effort to mitigate the lack of compatibility between OAuth2 servers and clients. There are also additional profiles which makes it even stricter for clients and servers for some use cases (the FAPI profiles is a good example of that). The OpenID foundation also provides a bunch of certification tools to help ensuring your server or client implementation is compliant.
In the Matrix spec, we want to be precise on what part of OIDC/OAuth 2.0 clients and servers HAVE to support to ensure compatibility between them.

That being said, the argument of having to test against 3 HS vs. having to test lots of OIDC servers is a practical one, not a spec one: if we had 40 HS implementations in the wild, would you test your client against all 40 of them? Probably only, because that's what the spec is for. The lack of diversity in homeserver implementations can be somewhat useful when implementing a client, but the spec should still be the source of truth when implementing a client or a server. That does not change with OIDC.

Moreover, we, for example, add semantics around dynamic client registration that are not present in any existing OIDC provider as far as I know, that will require specific modules to make those existing providers fully 'Matrix compliant', so don't expect users to be using any random off-the-shelf OIDC provider right away: they will probably use one of the few 'known compliant' provider, so you would probably still be in a situation where you only have to test a few implementations for your client.

> Google OAuth for example is very well known for changing in incompatible ways quite often (last time I tried it, it couldn't work with Google at all, but I assume they fixed that in the last few years). Here are a few of the potential pitfalls: https://appfluence.com/productivity/how-to-authenticate-qt-google-sso/

That is a side effect of the best practices evolving over the years. OIDC/OAuth 2.0 did mature a lot since it was first introduced, so things that were considered 'secure enough' 6 years ago (in this case, using a web view instead of the system browser) are now deprecated. Having watched that space for a few years now, I think that we're in a state where modern OIDC is secure and stable enough to not have to worry about it changing too much.

> (The code in that example is about half as long as the UIA code in Nheko, so the implementation benefits don't seem to be particularly great considering that most of the UIA code is just putting stuff into a pretty UI so that it looks well integrated into the client.)

I am curious about that claim. One thing to keep in mind, is that this is not only about logging in (which can be done with one HTTP request if you're using username+password), but all account management capabilities, like changing your password, 'forgot my password' flows, account registration (which can include a captcha, an email verification and terms of service acceptance), account deactivation, etc.

2022-08-11 18:23 UTC, turt2live reviewed
just a mid-read review. Submitting before I forget about it

2022-08-11 18:51 UTC, deepbluev7 commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 We're training our users to enter their Matrix credentials in random web pages and native apps
> I'm having a hard time understanding what you mean here. What kind of whitelist are we talking about? The login page would usually be shown in the default browser, even for native apps. Sure, showing a web view embedded in your native app is tempting (and completely possible), but you usually avoid that because:

I am saying that for exactly those reasons it isn't really a security benefit. The difference between a webview and a browser is not clear to the user and just making the user only trust the webpage doesn't mean that it isn't still fairly trivial to spoof it.

> If you do the login in an embedded web view, sure, but not in the system browser. Also note that on both Android and iOS, the system has APIs to open 'browser' views without changing apps. I recommend checking out the GIFs about that on https://areweoidcyet.com/

That doesn't prevent usage of a webview so users only trusting specific websites is not a significant benefit. Yes, a trustworthy app will probably use a browser, but the difference between that and a webview is not obvious to a user so you don't solve the problem usually associated with "entering the password into random websites".

> What do you mean by 'orthogonal'?

I am saying that the problem of entering your into specific websites is not solved by using a homeserver provided website, it is solved by authenticating using an already trusted device that provides only the information necessary, which can be 2FA, etc. The other bullet point is completely valid that OIDC already specifies ways to do that, which makes implementation of that easier. But the specific bullet point about training people not to enter their passwords into native apps is not useful as long as any malicious app can use a webview and attack the password/auth that way.

> That does not change, your server still doesn't have your keys. What changes though, is that a bad client can't take over your account anymore: it can't change your password, logout from other sessions or even deactivate your account.

No, the server doesn't know my keys, but I need to trust the client anyway, so I don't see why it can't know my password, since it already handles data that is more important than my password. The argument that you shouldn't trust random clients is simply not applicable, if you want to read your E2EE messages in that client imo.

2022-08-11 19:24 UTC, deepbluev7 commented on proposals/3861-delegated-oidc-architecture.md
> +- 👍 Simpler for Homeservers and clients to implement
> In the Matrix spec, we want to be precise on what part of OIDC/OAuth 2.0 clients and servers HAVE to support to ensure compatibility between them.

I hope you mean, you want to restrict what OIDC/OAuth 2.0 flows are allowed to be advertized by clients? Because if something like "Sign in with Apple" is supported on even one public homeserver, clients usually have to support it no matter if it is compliant to the spec or not. So if "Sign in with Apple" is not compliant with OIDC, clients will have to implement workarounds for it. 

> That being said, the argument of having to test against 3 HS vs. having to test lots of OIDC servers is a practical one, not a spec one: if we had 40 HS implementations in the wild, would you test your client against all 40 of them? Probably only, because that's what the spec is for. The lack of diversity in homeserver implementations can be somewhat useful when implementing a client, but the spec should still be the source of truth when implementing a client or a server. That does not change with OIDC.

I think you will find very few client developers that agree with the statement, that you can follow the spec to implement a functioning Matrix client. You usually need to implement multiple MSCs as well as homeserver and client specific behaviour. For example Element iOS requires you send a thumbnail for a sticker to show it at all, Element Android sends wrong reply fallbacks for edits, Element Web starts the device verification flow in a long deprecated order, the spec didn't include edits for years, Synapse stored timestamps and powerlevels as strings in the past so you can't just parse them as integers if a user is still in an old room, construct sends room state in a weird order, conduit used to duplicate to_device messages for almost a year, dendrite used to store push timestamps in the wrong unit and for a long time one time and fallback keycounts were a mess. You absolutely need to test against as many options you can. I usually try all my test accounts on 4 different homeservers before a release as well as verification and calls between a few clients.

Yes, testing against 40 different homeserver implementations might not be feasible in the future, but the spec shouldn't define the minimum subset of OIDC clients should support, but rather the maximum API a client and server is allowed to support. Otherwise instead of simplifying authentication, this will make it much more complicated and fragile. I know that OIDC tries to make this standardized and interoperable, but in my experience we are still pretty far away from that (considering how much effort it is to integrate with all the different OIDC systems every time).

> I am curious about that claim. One thing to keep in mind, is that this is not only about logging in (which can be done with one HTTP request if you're using username+password), but all account management capabilities, like changing your password, 'forgot my password' flows, account registration (which can include a captcha, an email verification and terms of service acceptance), account deactivation, etc.

The UIA part is implemented in a single file with about 300 lines: https://github.com/Nheko-Reborn/nheko/blob/master/src/ui/UIA.cpp

That is reused for every endpoint (apart from /login since that never switched to UIA) and drives a few hundred lines of dialogs (about 20 lines per stage type). Some pages opt in to integrate the dialogs better, which is additional UI, but I won't count that, since OIDC wouldn't allow that kind of integration. Similarly the implementation could be done in 100 lines if the fallbacks are used everywhere instead of custom dialogs. FluffyChat uses the same pattern, but notably the Element mobile clients do not (and they don't even implement the fallback properly...). Sure, Nheko doesn't implement "changing your password", but it does do registration (including registration tokens), terms of service, device deletion/renaming, device signing key uploads as a few of the endpoints that use UIA.

Adding the UIA handling to any such capability is just one line to pass the UIAHandler to the function (or rather, one extra argument). If any such things would still be handled client side instead of some webpage, they would be the same effort to implement presumably. (I know what UIA is and I have been working together with a few MSC authors to get rid of the "just send your password in plaintext option.)

2022-08-12 08:04 UTC, hughns commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 Requires an MSC for every "new" auth capability such as 2FA and WebAuthn
I think the point I was trying to get across in the 👎  was: As an auth protocol, Matrix is way behind OIDC. To catch-up and keep pace with the state of art this (single) MSC proposes that Matrix adopts OIDC instead.

2022-10-16 23:03 UTC, compgeniuses commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 Requires an MSC for every "new" auth capability such as 2FA and WebAuthn
you are right, outsourcing the authentication component to a more advanced and dedicated provider, makes sense, so that matrix can move with speed to be a communication platform.

2023-01-01 11:40 UTC, greizgh commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3105: Previewing UIA flows](https://github.com/matrix-org/matrix-spec-proposals/pull/3105)<br>[MSC3741: Revealing the useful login flows to clients after a soft logout](https://github.com/matri
Small typo:
```suggestion
| [MSC3105: Previewing UIA flows](https://github.com/matrix-org/matrix-spec-proposals/pull/3105)<br>[MSC3741: Revealing the useful login flows to clients after a soft logout](https://github.com/matrix-org/matrix-spec-proposals/pull/3741) | These become unnecessary as the burden to implement auth flows is moved away from the client to the OP |
```

2023-02-24 16:21 UTC, MTRNord commented on proposals/3861-delegated-oidc-architecture.md
> +Please refer to individual proposals.
I am not sure if there is a better place, but:

How do we protect from ending up in the same situation as email, where big companies (like google/microsoft) end up using OIDC/OAuth2 purely to gatekeep the clients that are allowed to use? As far as I understand, matrix is supposed to be an open protocol where anyone is allowed to bring their own tools and software. So how do we make sure that this is still possible? I am aware of certain enterprise parts of matrix that want to restrict client usage, however imho this isn't something that should leak into spec.

The reasoning behind is that the Matrix Manifesto ( https://matrix.org/foundation/ ) clearly defines that we don't want to be an open communication network and people shall have full control over their communication. If we end up however in a situation where we give HS admins a (too) easy way to restrict the clients that are usable we would break the goals of that manifesto at it's core, since then it's not open anymore for the users and Singular community managers can decide what tools to use with 0 protection for the users.

2023-02-24 16:36 UTC, MTRNord commented on proposals/3861-delegated-oidc-architecture.md
> +Please refer to individual proposals.
For additional source of my email reference, see the comment made by a thunderbird dev in https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat#OAuth2

> Due to a defficiency in the OAuth2 spec, the client is usually required to send a client credential key, which in turn requires the client to be registered and approved by the email provider. Unfortunately, this not only allows email providers to block specific email clients (which is contrary to the idea of Open-Source), but also makes it impossible to support arbitrary OAuth2 servers. That's why Thunderbird is forced to hardcode the servers that it supports and the respecive client keys. That means that you cannot use OAuth2 for your own server. Only the servers listed on [OAuth2Providers.jsm](https://searchfox.org/comm-central/source/mailnews/base/src/OAuth2Providers.jsm) will work.

I am aware of the dynamic registration MSC for OIDC, but that only somewhat solves this, since there a provider still is able to refuse your client at any given time without explanation.

2023-02-28 16:54 UTC, hughns commented
I've added references to the following MSCs that this proposal assumes are generally accepted:

- https://github.com/matrix-org/matrix-spec-proposals/pull/3967
- https://github.com/matrix-org/matrix-spec-proposals/pull/3970

2023-04-11 19:50 UTC, hughns commented on proposals/3861-delegated-oidc-architecture.md
> +1. Close all existing MSCs relating to non-OIDC as `obsolete`.
@MTRNord there is a start of a list at https://github.com/matrix-org/matrix-spec-proposals/blob/hughns/delegated-oidc-architecture/proposals/3861-delegated-oidc-architecture.md#alternatives

2023-05-26 15:03 UTC, clokep commented on proposals/3861-delegated-oidc-architecture.md
> +## Potential issues
From reviewing the Synapse implementation it seems that this MSC is missing information on how application services would register users. matrix-org/synapse#15582 keeps the old `/register` endpoint active for the `m.login.application_service` login type only.

This MSC needs to include *some* information IMO about how this interacts with application services.

2023-11-03 20:48 UTC, MTRNord commented on proposals/3861-delegated-oidc-architecture.md
> +# MSC3861: Matrix architecture change to delegate authentication via OIDC
I might be unable to find the right line in this huge amount of MSCs, but how does this new system translate users to mxids for events There needs to be some mapping right?

2024-04-17 21:15 UTC, mvgorcum commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 We're training our users to enter their Matrix credentials in random web pages and native apps
> It is different in the sense that we would be building trust between the user and their homeserver. Right now, the user does not interact with their HS much. Here, it would make it easier for user to understand that their account is living on their HS, and therefore they should only ever enter their account credentials on a web page controlled by their homeserver, not some random web application which claims to be a secure Matrix client.

I would argue that by implementing OIDC like this we're training users to expect to be sent to a random-ass website that looks vaguely official, and having them input their password there. This sounds like a phishers dream to me.

2024-05-15 00:46 UTC, tranquillity-codes commented
Do I understand right that should this be merged into the spec, every client would have to support viewing or opening arbitrary websites with possibly complex CSS and JavaScript, making implementing a Matrix client essentially impossible on lightweight operating systems that lack support by any major web browser?

2024-05-15 02:10 UTC, programmerjake commented
> Do I understand right that should this be merged into the spec, every client would have to support viewing or opening arbitrary websites with possibly complex CSS and JavaScript, making implementing a Matrix client essentially impossible on lightweight operating systems that lack support by any major web browser?

maybe there's a way to use QR codes to transfer the necessary data so you can authenticate on some other system that supports web browsers

2024-05-15 06:09 UTC, tranquillity-codes commented
> > Do I understand right that should this be merged into the spec, every client would have to support viewing or opening arbitrary websites with possibly complex CSS and JavaScript, making implementing a Matrix client essentially impossible on lightweight operating systems that lack support by any major web browser?
> 
> maybe there's a way to use QR codes to transfer the necessary data so you can authenticate on some other system that supports web browsers

That would be quite a subpar user experience, assuming said users even have access to such a device.

2024-05-15 06:48 UTC, kegsay commented on proposals/3861-delegated-oidc-architecture.md
> +- 👎 We're training our users to enter their Matrix credentials in random web pages and native apps
> No, the server doesn't know my keys, but I need to trust the client anyway, so I don't see why it can't know my password, since it already handles data that is more important than my password. The argument that you shouldn't trust random clients is simply not applicable, if you want to read your E2EE messages in that client imo.

We need to urgently clarify what the trust model is for E2EE clients. Some parts of this MSC are predicated on the fact that trusting the client = bad, trusting the server = good, but this is actually the _opposite_ in an E2EE world, as you've explained. Due to this trust model, [we are asserting things which negatively impact the ecosystem](https://areweoidcyet.com/#faqs):

> What do I do for my device which doesn’t have a web browser?
>
> [...] Use a [Resource Owner Password Credentials Grant](https://oauth.net/2/grant-types/password/) (a.k.a. “password grant” or “direct grant”) where the username and password are entered into the client (i.e. the 3DS) and the client then sends the username and password to the OpenID Provider to get an access token.
>
> It is important to note that the second option (Resource Owner Password Credentials Grant) is considered insecure by the [OAuth 2.0 Security Best Current Practice](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics-20#section-2.4) guide. As such, it is expected that the presence of this capability in an OpenID Provider can not be relied on. For example, we don’t expect that matrix.org will support this flow.

So we are asserting that matrix.org won't support clients which don't have a web browser in an OIDC world, _because_ we don't want to enable password grants _because_ we trust the server more than the client. The best practice guideline states:

> The resource owner password credentials grant MUST NOT be used. This grant type insecurely exposes the credentials of the resource owner to the client. Even if the client is benign, this results in an increased attack surface (credentials can leak in more places than just the AS) and users are trained to enter their credentials in places other than the AS.

But for our ecosystem this is _inevitable_ because we support E2EE so the keys _only exist on the client_ so we _must trust the client_. In fact, we go even further because we need to handle attacks where the server maliciously controls our account, so we need to protect everything worth protecting behind strong crypto (e.g cross-signing) rather than trusting the server.

2024-05-15 07:41 UTC, richvdh commented
@tranquillity-codes, @programmerjake: please leave comments on the [files](https://github.com/matrix-org/matrix-spec-proposals/pull/3861/files) tab rather than the main PR, so that there is some semblance of threading.

2024-05-15 07:41 UTC, kegsay commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3262: aPAKE authentication](https://github.com/matrix-org/matrix-spec-proposals/pull/3262)<br>[MSC2957: Cryptographically Concealed Credentials](https://github.com/matrix-org/matrix-spec-propos
This seems to be a recurring pattern in OIDC land, where client=bad, server=good is the trust model. This is not true for E2EE clients, which in practice is an ever increasing set of Matrix clients, which matrix.org is enabling via rust SDK crypto. As a result, OIDC seems to be making "best practices" and "recommendations" that are simply not relevant for the Matrix ecosystem.

In an ideal world, we would bless the Resource Owner Password Credentials flow as a valid and "best practice" flow for E2EE clients (and hence enable it on matrix.org) and this flow would effectively be equivalent to `m.login.password`, perhaps with a bit more of a back and forth to exchange authentication codes => tokens instead of 1 round trip. This would address several complaints I see on this MSC:

> The user has to be redirected either to a browser where then the app needs to either handle a custom proto or a webserver for the callback, or they need a webview which usually involves compiling a full chromium suite which extremely increases compile times and makes you have to do way more regular updating of the client due to the rapid amount of security issues within chromium. It overall adds a lot of complexity to the update process and especially makes the experience worse for small client devs imho.

> Do I understand right that should this be merged into the spec, every client would have to support viewing or opening arbitrary websites with possibly complex CSS and JavaScript, making implementing a Matrix client essentially impossible on lightweight operating systems that lack support by any major web browser?

No need for a web browser with this flow, but you do need to make HTTP requests.

This will require a bit of a world view shift from the MSC authors, to be constantly reassessing if what they are designing makes sense when client=good, server=bad is the trust model, but this is the right thing to do because we are consistently heading in a "more E2EE not less" direction.

One particular concern I have (with any luck this won't be referenced in X years time when it happens..) is that:
 - OIDC is complicated so,
 - you should use a library which does it all for you but,
 - this adds a complex dependency which,
 - can be pwned to then siphon off your E2EE credentials.

Supply chain attacks are particularly damaging when the trust (private keys) is in the client, and the best way to guard against that is to have fewer dependencies. Whilst this isn't unique to OIDC, this MSC is almost _encouraging_ more dependencies, which, from a client=good server=bad world view, _reduces security_ compared to our existing UIA framework.

2024-05-15 07:49 UTC, richvdh commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3262: aPAKE authentication](https://github.com/matrix-org/matrix-spec-proposals/pull/3262)<br>[MSC2957: Cryptographically Concealed Credentials](https://github.com/matrix-org/matrix-spec-propos
@kegsay there seem to be a lot of different concerns here. It might be better to split them up into separate so that they can be addressed separately? Otherwise we're going to have a single thread which attempts to address all the problems of life, the universe and everything.

2024-05-15 08:43 UTC, tranquillity-codes commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3262: aPAKE authentication](https://github.com/matrix-org/matrix-spec-proposals/pull/3262)<br>[MSC2957: Cryptographically Concealed Credentials](https://github.com/matrix-org/matrix-spec-propos
> @kegsay there seem to be a lot of different concerns here. It might be better to split them up into separate so that they can be addressed separately? Otherwise we're going to have a single thread which attempts to address all the problems of life, the universe and everything.

There seems to be at least 4 concerns:
- Paradigm shift from client=bad,server=good to client=good,server=bad
- Password flow being discouraged
- Flows requiring a web browser
- Encouraging more dependencies

Does that about sum it up?

2024-05-15 09:42 UTC, Ugzuzg commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3262: aPAKE authentication](https://github.com/matrix-org/matrix-spec-proposals/pull/3262)<br>[MSC2957: Cryptographically Concealed Credentials](https://github.com/matrix-org/matrix-spec-propos
The first point phrased as a concern should be the other way around:
- Paradigm shift from client=good,server=bad (E2EE world) to client=bad,server=good (OIDC world)

2024-05-15 12:02 UTC, tranquillity-codes commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3262: aPAKE authentication](https://github.com/matrix-org/matrix-spec-proposals/pull/3262)<br>[MSC2957: Cryptographically Concealed Credentials](https://github.com/matrix-org/matrix-spec-propos
> The first point phrased as a concern should be the other way around:
> 
>     * Paradigm shift from client=good,server=bad (E2EE world) to client=bad,server=good (OIDC world)

How so? We are shifting from `client=bad,server=good` to `client=good,server=bad` so that the proposal makes sense in the context of Matrix

2024-05-15 12:16 UTC, Ugzuzg commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3262: aPAKE authentication](https://github.com/matrix-org/matrix-spec-proposals/pull/3262)<br>[MSC2957: Cryptographically Concealed Credentials](https://github.com/matrix-org/matrix-spec-propos
In the context of Matrix, the client has the ultimate trust, since it has access to decryption keys and decrypted messages and metadata, but the server can't access any of that (`client=good,server=bad` paradigm).

This proposal says that the clients shouldn't be trusted with a password, but the server should. This shifts the paradigm from `client=good,server=bad` to `client=bad,server=good`, which is a concern.

2024-05-16 00:14 UTC, tranquillity-codes commented on proposals/3861-delegated-oidc-architecture.md
> +| [MSC3262: aPAKE authentication](https://github.com/matrix-org/matrix-spec-proposals/pull/3262)<br>[MSC2957: Cryptographically Concealed Credentials](https://github.com/matrix-org/matrix-spec-propos
Ah, yes, with that phrasing it makes sense, I misunderstood ^^

2024-06-02 11:12 UTC, XxSNiPxX commented
Hello guys,  

My current project requires me to authenticate a user on my synapse instance via a signed message from a keplr crypto wallet . I have a wallet signed message used as the password. How would i approach the authentication on matrix? Would i use another server that is openid compatible, whose license is often not gplv3 or would i use the architecture before by contacting the synapse instance directly?  Can someone please share and end to end example of setting up a IAM server between the client and synapse?

Thanks

2024-09-16 17:37 UTC, Xiretza commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
The first three of these points may be relevant for large, open-registration servers like matrix.org, but I'm gonna go out on a limb and say that most servers out there are *not that*. In general, there needs to be extremely solid justification for forcing this increase in complexity onto all the servers that have nothing or very little to gain from it.

2024-09-17 09:01 UTC, sandhose reviewed
The long-awaited big rewrite is here!

I've been working on making this series of MSCs a lot better, and I think I addressed a lot of concerns made on it. I commented on most open threads how I believe they are now addressed and closed them. If you believe those concerns are still not addressed, please reopen them or open new threads on the new MSC text

Happy reading!

2024-09-17 09:03 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +# MSC3861: Matrix architecture change to delegate authentication via OIDC
I'm not sure I understand what you mean here. This proposal doesn't touch on events, and MXIDs are not really a concern throughout the flow. Could you clarify what you're asking here?

2024-09-17 14:58 UTC, Xiretza commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
> I'm not sure I understand the second part of your comment, how is this section talking about increasing the complexity onto all servers?

The rewritten MSC later mentions:

> The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.

This means that in the long term, all homeserver operators have to set up an entire OAuth/OIDC infrastructure, which is significantly more complex than the built-in username+password auth that is entirely sufficient for what I claim to be the vast majority of homeservers out there. Or am I misunderstanding something?

2024-09-17 17:50 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
The change is relatively transparent for server operators, it is an API change, not an architecture change.

It happens that the current implementation with matrix-authentication-service and Synapse is a separate service, but the long term goal is to be integrated just within synapse, so the change will be fairly transparent for server operators

Does that answer your concern?

2024-09-18 16:57 UTC, Xiretza commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
> the long term goal is to be integrated just within synapse, so the change will be fairly transparent for server operators

*Synapse* operators. What about other homeservers?

Actually, putting on my homeserver developer hat, this really only shifts the problem from operators to developers. Right now, a homeserver implementation that can cover most usecases (i.e. except for the "large, open-registration" niche) using a very simple, almost stub-like UIA implementation. I admit I haven't actually looked into it properly yet, but I suspect that OIDC will make even a minimal implementation much more complex.

2024-09-18 19:09 UTC, Tynach commented
> The long-awaited big rewrite is here!

Shouldn't a big rewrite be a separate pull request/proposal? That way it's easier to distinguish between discussion about the old one, and discussion about the new one?

2024-09-19 09:04 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
I suggest reading the rest of the proposal, as this is not about imposing stuff like email verification, CAPTCHA support, etc. on homeservers.

A very lightweight implementation of this can be done only supporting simple login and password. At a very high level, the new API look like this:

 - the client sends its metadata (name, redirect URL, etc.) to the homeserver, gets back a client identifier
 - the client redirects the user to a web page hosted by the homeserver
 - the homeserver does whatever it needs on that homepage to authenticate the user, this can be a very simple HTML form
 - once completed, the homeserver redirect backs to the client with single-use code
 - the client exchanges this code to get back an access token

How does that feel in terms of complexity? I understand that it is substantially higher than just sending 'username and password' to an API and get back an access token, but the bar doesn't seem too high for new implementation, especially considering there are plenty of OAuth/OIDC related libraries in many ecosystems to help implement some of this.

2024-09-20 08:16 UTC, Xiretza commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
One use case I have somewhat frequently is setting up bots. Currently, you can just type in username+password, it does the authentication and stores the access token somewhere. With OIDC, I'd already be stuck at the first step: what is the "redirect URL" for a bot running on a headless server somewhere? Step 2, "redirecting" the user to a login page, is still possible by making them click on a link, but this is then opened on the user's machine, which is totally separate from the machine running the bot. There would need to be a *third* service somewhere that displays the single-use code, which then needs to be copy-pasted back into the bot. Not only is this more annoying to implement, it's also much more complicated to use.

So no, I'm not on board with removing username+password auth, but how about this as a long term plan:
- Strip down UIA to a bare minimum username+password (this removes most of the complexity there and still covers most use cases),
- Optionally let servers force the use of OIDC, which can then include all the captcha/email/whathaveyou bells and whistles for complex installations without having to cover these complexities in the Matrix spec.

2024-12-09 22:11 UTC, marmarek commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
This whole point (and earlier to some degree too) feels like it got the trust levels backwards. In the E2EE scenario it's the client that is the trusted part, and the homeserver is less trusted. After all, it's the client who sees clear text messages, it's the client who can impersonate the user etc. This proposal does not change (nor should change!) any of this. And thus, saying that credentials are now isolated from the client doesn't matter much from the trust perspective - it can still access/decrypt your messages etc.

I realize there is some logic in this reasoning if you consider web client *only* - in that scenario indeed having user authentication on a separate homeserver-controlled page can isolate the client a bit from (potentially compromised!) homeserver by moving that workflow to another domain. And in the web scenario, also attaching credentials to the homeserver domain makes sense. But in the E2EE scenario, the web client is inherently less secure option anyway - the web client provider can _stealthy_ insert any backdoor into your client and steal all the keys. With this change it may not be able to steal your account credentials anymore (at least as long as the user actually verifies the login is performed on a correct domain - which live shows users are really bad at...), but that's only a little consolation at this point. 

But if you care more about your communication security, a much better choice is a local client (be it desktop, mobile etc), where the client code cannot change without your knowledge. In this scenario, requiring full blown web browser to open a homeserver-controlled page is a significant regression in terms of security. Now, not only you have extra attack surface (web browser with all its APIs - the fact that usually login page would be simple doesn't mean a compromised homeserver couldn't serve a login page using all kind of APIs), you now need to expose your credentials to an external application (so, you need to trust not only your local client, but also your web browser). And it gets even worse with containerized applications (flatpak, snap etc), where you either may need a full browser inside the container (wasteful) or you need to share your credentials with something outside of that container. And finally, in the native client case, the extra isolation that OIDC supposedly provide does not apply, as the client (in practice) controls what browser is used for providing credentials - so, if you have a malicious client, it can also give you fake browser that will intercept the credentials anyway.

So, I think at the very least this section needs adjustment to explain the impact on the non-web clients. But also, I would recommend to not only acknowledge it, but also mitigate it in the MSC - for example by still providing (not only in transitional period) a login workflow that doesn't require visiting an arbitrary website from your client (or other device). From a practical standpoint, it's only about logging into an account (and maybe invalidation of other sessions?). All other stuff like registration, deletion etc. can be handled via web interface - there is indeed very little point in requiring all of that to have complex and flexible UI in every client out there.

2024-12-11 04:09 UTC, olivia-fl commented on proposals/3861-delegated-oidc-architecture.md
> +Quoting the [specification](https://spec.matrix.org/latest/#introduction-to-the-matrix-apis):
The specification also currently states that:

> The principles that Matrix attempts to follow are:
> ...
> - Keep It Simple & Stupid
>    - provide a simple architecture with minimal third-party dependencies.

And that

> The functionality that Matrix provides includes:
> ...
>  - Managing user accounts (registration, login, logout)

OAuth2/OIDC is a complex third party dependency. Synapse+MAS is an substantial increase in architectural complexity over the current state. Bundling an OIDC server with non-synapse server implementations would be a similar increase in architectural complexity.

My understanding is that this MSC takes the position that managing user accounts _should not_ be part of the functionality that matrix provides, and that it is worth introducing significant third party dependencies and architectural complexity to make that happen. It's inevitable that the documented principles will sometimes come into conflict, and changes may be made that violate some of them because the tradeoffs are worth it. If this is the intention, I would prefer that the decision to depart from the existing documented principles and core functionality was more explicit in the MSC text.

2024-12-11 14:35 UTC, tranquillity-codes commented
Reposting a comment we made in #matrix-auth:matrix.org here for better visibility

A preliminary analysis of the security impact in various threat models:

# Default Model (Untrusted Server)

## Security

The OIDC uses an untrusted party to provide security against another untrusted party. This means that in the default model, by itself, it is a zero net gain or loss.
Second, the OIDC enforces the use of browsers, massively increasing the attack surface. This makes it result in a net negative in the default model.
Let's also analyze restricted clients and privileged clients. We are failing to find a usecase. Let's list 3 of the permissions in the demo, plus a 4th one moderation events, and a 5th one, destructive client actions:

### Client actions

#### View your existing messages

This is managed by the E2EE. In the default threat model, this is like the wolf protecting the sheep from another wolf. The wolf simply should not have access to the sheep. This is already the case.

#### Send messages on your behalf

In the default threat model, this once again is a net zero because a malicious party (the homeserver) can still do exactly that. Instead, incorporating client keys in the auth DAG of a room would prevent this (and we are working on that, though waiting on the new stateres)

#### See your profile

Same thing as before, net zero, in order to make the profile data secure against malicious parties, you should encrypt any important data and share the keys. Sort of like 4S.

#### Moderation actions

Same thing as before, net zero, in order to secure it, moderation events should be authenticated with signing keys of the moderator (another thing that we are working on)

##### Destructive client actions

Protecting the client's account would once again be better served by having a client (or possibly a user-hosted service, though one which might not be contactable by the homeserver; We work on this in our to-be-drafted Tor proposal) save its state + using pubkeys instead of MXIDs, but roaming accounts is far, far away, so OIDC is an actually realistic solution for this in the short term, as far as we can see. Though for an actually good UX, a secure embedded browser or popup should be utilized, preferably a solution that involves more secure blobs ran in a trusted environment, instead of a full-on browser. Though since platforms lack this, it's more realistic to fall back on a browser, and have the more secure trusted environment stuff experimental.

### Phishing

On the web, using a centralized HS-controlled domain for the HS is more resistant to phishing of the actual credentials. This is good, since malicious phishing clients are much, _MUCH_ easier to operate than malicious homeservers or malicious native apps.
For native apps, if you install a native app it can already hook itself into the system and keylog you. But it's more likely to be vetted, so, for native apps, this doesn't really do anything (we think eg. Flatpak)

## UX

For browser clients, the argument with the password manager scoping is good. We agree, the UX on the web there is superior.
For native clients, it feels incredibly wonky to manage two windows for one application. Thus, an embedded secure surface that's reparented _into_ the surface is necessary (on Wayland). On Android, this is trickier, as they offer no such thing as we can tell.

# Selfhosted model (Trusted server)

It's pretty clearly a huge improvement. Unfortunately most users don't selfhost, and many of those that do are likely to vet their clients (we do that, so we don't have a use). Though there are certainly HS admins out there that would benefit from this for their instances that are trusted (take, a friend group or a corporate environment)

---

We'll analyze the rest later, gonna just leave this here for now.

2024-12-11 16:16 UTC, tranquillity-codes reviewed
Apparently a review is not enough to be a review, thanks GitHub. https://github.com/matrix-org/matrix-spec-proposals/pull/3861/files/dc9d84b89bed53a5f94bea4a04a7b631225fa01d#diff-3476d56bc0a1dfb02175c03068714fe6303c1a04603be87299d0ae21402568ab

2024-12-11 16:25 UTC, tranquillity-codes commented on proposals/3861-delegated-oidc-architecture.md
Reposting as a review to create a thread and allow replies, to work around GitHub limitations. Original comment will be replaced with a link to the review.
Reposting a comment we made in #matrix-auth:matrix.org here for better visibility
A preliminary analysis of the security impact in various threat models:

# Default Model (Untrusted Server)

## Security

The OIDC uses an untrusted party to provide security against another untrusted party. This means that in the default model, by itself, it is a zero net gain or loss.
Second, the OIDC enforces the use of browsers, massively increasing the attack surface. This makes it result in a net negative in the default model.
Let's also analyze restricted clients and privileged clients. We are failing to find a usecase. Let's list 3 of the permissions in the demo, plus a 4th one moderation events, and a 5th one, destructive client actions:

### Client actions

#### View your existing messages

This is managed by the E2EE. In the default threat model, this is like the wolf protecting the sheep from another wolf. The wolf simply should not have access to the sheep. This is already the case.

#### Send messages on your behalf

In the default threat model, this once again is a net zero because a malicious party (the homeserver) can still do exactly that. Instead, incorporating client keys in the auth DAG of a room would prevent this (and we are working on that, though waiting on the new stateres)

#### See your profile

Same thing as before, net zero, in order to make the profile data secure against malicious parties, you should encrypt any important data and share the keys. Sort of like 4S.

#### Moderation actions

Same thing as before, net zero, in order to secure it, moderation events should be authenticated with signing keys of the moderator (another thing that we are working on)

#### Destructive client actions

Protecting the client's account would once again be better served by having a client (or possibly a user-hosted service, though one which might not be contactable by the homeserver; We work on this in our to-be-drafted Tor proposal) save its state + using pubkeys instead of MXIDs, but roaming accounts is far, far away, so OIDC is an actually realistic solution for this in the short term, as far as we can see. Though for an actually good UX, a secure embedded browser or popup should be utilized, preferably a solution that involves more secure blobs ran in a trusted environment, instead of a full-on browser. Though since platforms lack this, it's more realistic to fall back on a browser, and have the more secure trusted environment stuff experimental.

### Phishing

On the web, using a centralized HS-controlled domain for the HS is more resistant to phishing of the actual credentials. This is good, since malicious phishing clients are much, _MUCH_ easier to operate than malicious homeservers or malicious native apps.
For native apps, if you install a native app it can already hook itself into the system and keylog you. But it's more likely to be vetted, so, for native apps, this doesn't really do anything (we think eg. Flatpak)

## UX

For browser clients, the argument with the password manager scoping is good. We agree, the UX on the web there is superior.
For native clients, it feels incredibly wonky to manage two windows for one application. Thus, an embedded secure surface that's reparented _into_ the surface is necessary (on Wayland). On Android, this is trickier, as they offer no such thing as we can tell.

# Selfhosted model (Trusted server)

It's pretty clearly a huge improvement. Unfortunately most users don't selfhost, and many of those that do are likely to vet their clients (we do that, so we don't have a use). Though there are certainly HS admins out there that would benefit from this for their instances that are trusted (take, a friend group or a corporate environment)

---

We'll analyze the rest later, gonna just leave this here for now.

2024-12-11 17:25 UTC, programmerjake commented on proposals/3861-delegated-oidc-architecture.md
one part you haven't considered is unencrypted public channels e.g. because they're bridged to IRC or similar, there trusting the server is required, so you can't just say everything depends on end-to-end encryption and ignore any other attack vectors.

2024-12-11 18:17 UTC, tranquillity-codes commented on proposals/3861-delegated-oidc-architecture.md
> one part you haven't considered is unencrypted public channels e.g. because they're bridged to IRC or similar, there trusting the server is required, so you can't just say everything depends on end-to-end encryption and ignore any other attack vectors.

In what manner have we not considered them ? Exactly what changes ?

If you have any concerns with our assessment *write them down*, please.

2024-12-11 18:34 UTC, programmerjake commented on proposals/3861-delegated-oidc-architecture.md
I guess that basically there should be a different threat model for public unencrypted rooms with an IRC bridge where the server is trusted to not post stuff you didn't actually say (since IRC has a trusted server model afaik).

2024-12-11 19:04 UTC, tranquillity-codes commented on proposals/3861-delegated-oidc-architecture.md
The authenticity of bridged users is a responsibility of the given bridge.

Public unencrypted rooms should still offer ways of ensuring message integrity (such as integrating client-managed keys into the room DAG for events that *have* to be intact), though it shouldn't be necessary to not compromise deniability even more than it already is.

Public unencrypted rooms are not impacted by the ability to read messages because any client can read messages. As for writing messages, this can be handled by introducing an event type a client can send to *require* the usage of client keys for sending events in a room, this cryptographically prevents unauthenticated clients from writing into the room without permission.

2024-12-13 16:07 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +Please refer to individual proposals.
I think it'd be fine to acknowledge the concern in the MSC, but I don't forsee a way to fix it. Homeservers can (and do) already gatekeep their registration and login APIs to particular clients/domains for a variety of reasons, including user safety and security - they might relax these conditions if given a proper authentication interface to use.

2024-12-13 16:10 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
This MSC does not remove anything from the spec. The SCT expects that the existing UIA flows won't go anywhere anytime soon, and that servers will follow suit - the proposal to use OIDC is to facilitate transition away from UIA, not replace it day 1.

As the SCT, we'll block attempts to remove UIA too quickly from the spec (and therefore implementations).

2024-12-13 16:54 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
I'm not sure I'm following the trust model being backwards: in Matrix we always consider the client 'trusted' to decrypt/receive messages, but we also put things in place to limit that - the MSC doesn't read (to me) as conflicting with that. There's a note about *not* changing the E2EE model, which I think is here primarily to reduce confusion from the external audience. 

What this MSC *does* change is the client's ability to make account-level changes on its own. UIA is something which can be driven *almost* entirely by code, and an infected client (either directly or indirectly) could trick the user into making their account inaccessible. For example, injecting code which says "please enter your password to confirm your account", which actually causes a password change in the background - for local clients, this could be injected by a virus on the user's machine, and for web clients it'd potentially be in the build pipeline. By having the authentication moved out of the client's implementation, users are significantly less likely to accidentally change their password without their knowledge.

Of course, the OIDC server could also be compromised and trick the user into changing their password, but the OIDC server will naturally have a higher sense of security given the threat vector.

2024-12-13 17:21 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
Homeservers which implement the minimum interface can also create exceptions for bots as needed. It's a common practice for API tokens to expire and need rotation, and it's equally common that service providers have a way to mint tokens independent of UI flows. Take for example GitHub, which supports OAuth2/OIDC for applications to log in as the user *and* a healthy ecosystem of integrations which run headless - the integrations get a dedicated API token, which may expire, and is created within an OIDC-authenticated client. Something similar would likely be possible for homeserver admins (and from discussions I've seen, very much in the plan for consideration when speaking towards removal of UIA from the spec - bots would be a blocker before we remove UIA).

It's also considered *bad* common practice to store passwords on bots for the purposes of authentication, and we already see bots which implement this behaviour poorly. For example, logging in *every* time they need to make a request. With a specific minted token, they aren't placing burden on their homeservers/federation, and have a higher default security profile. This does add some code to bots/clients though, but may be able to be packaged away into a library or their underlying Matrix SDK of choice. It'd be the specification's role to (if needed) define a standard way to perform that authentication so those Matrix SDKs can consistently implement it.

Overall, OIDC retains the ability for the homeserver admin to choose what authentication mechanisms they want to support, while also giving them even more options. Matrix is naturally slower at adding things like 2FA, Passkeys, API tokens, scoped tokens, etc and we're not experts in it - this MSC acknowledges this gap and suggests we adopt a protocol which specializes in this. Homeserver developers can choose to bundle in a full-blown OIDC server in their install if they like, or they could implement more usecase-specific APIs, or somewhere inbetween. Synapse appears to be going a route closer to a full-blown OIDC server, largely because of the wide variety of usecases they need to support.

2024-12-13 17:41 UTC, marmarek commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
For web client this separation makes some sense. I don't fully agree with the practical security benefit, mostly because I don't believe users indeed not giving password if the client asks for it, just because it's on the client's domain not a separate OIDC domain. And while this is more of a human issue than technical issue, I don't think it should be dismissed - it doesn't really matter _from the user point of view_ how their account got compromised...
But for native clients (which normally provide much stronger E2EE properties, due to not trusting some remote system serving the client code) the situation gets significantly worse. Before, you needed to trust your client integrity (including OS running it) to protect your credentials and encryption keys. With this change, you still need to trust your client for credentials and encryption keys, but you also need to trust some random code fetched from the internet (from the client point of view) and executed on your system to not only handle your account credentials correctly (1), but also to not try to escape browser sandbox and steal your encryption keys (2).
You can argue that (1) is not much of a change since that "random code" is provided by the same service that will receive credentials anyway, but depending on the OIDC server implementation that may not be really true (and indeed it's common to serve static files, including js, separately, sometimes via 3rd-party CDNs). But (2) is a significant attack surface increase for the non-web client case.

2024-12-13 17:47 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +Quoting the [specification](https://spec.matrix.org/latest/#introduction-to-the-matrix-apis):
The dependency can be of varied complexity depending on what the implementation wants to achieve. Discussed in [another thread](https://github.com/matrix-org/matrix-spec-proposals/pull/3861/files#r1761585153), it's possible for a server implementation to expose a pretty small minimal interface and retain the same functionality as today's login flows, though servers like Synapse are intending to elect for higher complexity at the moment.

From a protocol design perspective, we're just not experts in authentication and would really like to outsource that to another protocol, taking on the dependency. Whether that dependency is OIDC or another authentication protocol is an open question though, and thoughts are welcome on that point. Currently, OIDC appears the most viable due to its widespread use, optional heavy complexity, and relative simplicity on the client side. There is different work for server developers to support it, but at its core it is capable of being added to a homeserver at the same complexity as today's UIA. 

Ideally, there would be an implementation of that minimal interface somewhere to either prove it's possible, or prove I'm talking nonsense :p - this is not something the current team driving this proposal will be able to take on, but should hopefully be narrow-scoped enough for a third party implementation to happen, time permitting of course.

2024-12-13 18:08 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
I'm still struggling to follow the concern here, sorry. Using a web browser to "activate" a non-web browser client, even with a busted sandbox, should be no more risk than everyday use of the machine?

2024-12-13 18:24 UTC, marmarek commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
Ah, I see the missing step. Sometimes yes, sometimes no. You may have your client and/or your browser running in additional sandbox / container like Flatpak/Snap/AppImage - in which case you either need to start that browser for login in the same container, or punch some holes in the sandboxes. I believe similar concern applies to Android (and maybe other mobile?) where the client will need to add WebView that runs a code fetched from the OIDC server, in the same sandbox as the client itself.
But you can go further - in Qubes OS it's trivial to have a VM with just your client running and no browser at all. And there is an API for opening links in a different VM (can be even a disposable one), where by design such browser cannot communicate back to the VM with your client (otherwise that extra separation would be useless...). In this scenario, this MSC reduces benefits from this separation, as you'll need to allow running a browser in the same VM, at least for the login time.

2024-12-13 18:31 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
I don't think the client *needs* to talk to the exact same web browser with OIDC to work. There are tons of headless and near-headless applications which poll the server to wait for credentials to appear, after authentication is done elsewhere. For example, logging in on your phone/TV might say "go to login.example.org to complete this login". A similar thing is achieved with the Vault command line if you have SSO set up: it'll poll the server until it gets credentials, having waited for the user to finish clicking buttons elsewhere. 

Web clients, or clients in containers, can leverage this same step. The security model remains unchanged.

2024-12-13 18:53 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
As has been discussed a number of times already on github, in the public rooms, at conferences, and in-person to those who have had the opportunity, OIDC does *not* mandate use of a web browser. There are plenty of ways to log a client in without ever using a web browser on any device. They aren't exactly the smoothest experiences, but they are possible and do exist. Plenty of mobile apps already work within these constraints as well. 

The privacy/security concerns don't appear at all relevant to OIDC and instead are worth discussing on a different MSC. Specifically, the concern that events aren't signed by the sending device is maintained regardless of auth system.

The remainder of the post appears to be rehashing those two points, so I'm not going to spend time addressing them. Please aim for understanding and increased context before generating opinion pieces.

2024-12-13 18:54 UTC, marmarek commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
Okay, if this indeed will be implemented this way, then it should be fine, thanks for clarification.

2024-12-13 18:57 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
Implementation is very much up to the server and client authors. At the protocol level, all we can do is make room for that to happen ;) (we are)

2024-12-13 19:34 UTC, olivia-fl commented on proposals/3861-delegated-oidc-architecture.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
I guess the thing I want to understand is whether this MSC is a commitment to removing all existing UIA mechanisms _at some point in the future_, or whether it's just saying "we plan to do that, but might never do it if it turns out to be a bad decision". You say you'll block attempts to remove UIA too quickly, but is it also a possibility you will also block attempts to remove UIA _at all_ or are you closing off that possibility by merging this MSC? If this statement isn't a commitment to do anything specific, then I don't care nearly as much.

2024-12-13 19:43 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
How I read the current phrasing in the MSC is it's suggesting deprecation, which triggers a process for eventual *consideration* for removal. A different MSC would be required to both make the case for moving from deprecated to removal, and would be reviewed in that context (including counterarguments to say removal is inappropriate). 

or in other words, any implied removal in this MSC is non-normative, meaning we're not bound to it.

2024-12-13 19:58 UTC, olivia-fl commented on proposals/3861-delegated-oidc-architecture.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
Cool, I'm gonna not worry about it until then. Thanks for clarifying :)

2024-12-13 20:13 UTC, olivia-fl commented on proposals/3861-delegated-oidc-architecture.md
> +Quoting the [specification](https://spec.matrix.org/latest/#introduction-to-the-matrix-apis):
> There is different work for server developers to support it, but at its core it is capable of being added to a homeserver at the same complexity as today's UIA.

That seems... rather unlikely to me. `m.login.password` UIA takes maybe 30m reading the spec to understand how to write an implementation. I've done a bit of server-side oauth2 work before and it was _a lot_ more than 30m to learn how things work. I don't really have time or interest in trying to write a minimal implementation myself right now, and think I would be unlikely to persuade anybody by doing so (or by continuing to talk to spec people about it).

> time permitting of course.

Again, unlikely I would attempt this, but out of curiosity what is the time requirement?

---

Mainly what I want is for this reasoning to end up in the actual MSC text, to benefit future readers that don't go reading through all the github comments.

2024-12-14 12:07 UTC, tranquillity-codes commented on proposals/3861-delegated-oidc-architecture.md
You have missed the point we were making, but if you wish to ignore our concerns, we cannot really do anything about it. Our interpretation of you marking this unresolved concern as "resolved" thus is that you will not be addressing our use case, meaning that communication has broken down ? Please do confirm that it is the case, though we will default to that interpretation due to the hostility in the communications so far and lack of any kind of desire to accommodate the use cases of folks that have chosen Matrix because it was advertised as a _secure, private federated messenger_ rather than _an alternative to Microsoft Teams_.

2025-01-21 01:08 UTC, turt2live requested changes
Overall, this looks great to me. Thanks for putting so much time and energy into this project.

My review here is long, but the vast majority are non-blocking concerns for stating FCP. They will ultimately block FCP from finishing, but aren't critical enough to warrant a total block on progress, in my opinion. 

The theme for the blocking concerns is largely confusion for this MSC's purpose: it feels like this proposal is trying to confirm that we want to go down this road for authentication, but promptly puts up dependencies which would make it a net-zero change once they're all accepted. I've left some suggestions on how to change the wording slightly to flip this around: we would use this MSC to confirm the direction, and leave implementation/specification details to the underlying MSCs. The suggestions use "or similar" language to cover a process quirk where we know that we're *most likely* going to put the listed MSCs forward for FCP, but there's a non-zero chance that an alternative shows up, so we escape the pigeon hole early with "or similar".

If the intention is to have the listed MSCs accepted first, I'm not clear on this MSC's intended purpose. Clarification in the MSC body would be appreciated.

2025-01-21 01:08 UTC, turt2live commented on proposals/3861-next-generation-auth.md
> +The following MSCs are part of this proposal:
from earlier: this phrasing makes it sound like the following MSCs are automatically accepted if this MSC is accepted, which feels unintentional. A slight wording change like the following helps clarify that other options are theoretically available, but the author (you) has put in the most work into these ones:

```suggestion
The following MSCs map the aforementioned OAuth 2.0/OIDC requirements to Matrix APIs:
```

2025-01-21 01:08 UTC, turt2live commented on proposals/3861-next-generation-auth.md
> +The following MSCs are not directly part of this proposal but this proposal assumes that these are accepted:
like above, slight wording change:

```suggestion
The following MSCs are not directly needed to achieve this proposal's overall objective, but are nice to have:
```

2025-01-21 01:12 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +Quoting the [specification](https://spec.matrix.org/latest/#introduction-to-the-matrix-apis):
It feels like much of this rationale (if not all) has now made it to the MSC, or in new threads that clarify the situation further. If something still isn't addressed, please raise new dedicated threads as needed.

2025-01-21 01:13 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +**Note**: This does not change the level of trust that the user places in their homeserver. Their E2EE keys are still controlled by the client and never exposed to the homeserver, keeping the content
(considering resolved - if this feels unresolved, please open a new dedicated thread to discuss the concern)

2025-01-21 01:14 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
I've added a new thread somewhere (sorry, github UI is difficult to drive with so many threads) to clarify if this proposal is deprecating the UIA flows *now* or *later*. Critically, *removal* cannot happen at this stage, so the APIs aren't expected to go anywhere.

I'm resolving this thread for now. If there's still something outstanding though, please open a new dedicated thread.

2025-01-21 01:18 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +Please refer to individual proposals.
@sandhose this should be listed in the MSC text (doesn't need a solution, just a "this is possible" blob of text)

2025-01-21 01:19 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
(considering resolved - if there's something not addressed in the MSC, please open a new dedicated thread)

2025-01-21 01:19 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +## Potential issues
@sandhose I think this is missing from the MSC too.

2025-01-21 01:20 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +# MSC3861: Matrix architecture change to delegate authentication via OIDC
This MSC doesn't affect the user ID format.

(considering resolved - if there's something not addressed in the MSC, please open a new dedicated thread)

2025-01-21 01:20 UTC, turt2live commented on proposals/3861-delegated-oidc-architecture.md
> +1. Close all existing MSCs relating to non-OIDC as `obsolete`.
(considering resolved - if there's something not addressed in the MSC, please open a new dedicated thread)

2025-01-21 01:22 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

Checklist:
- [x] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal)
  specified in the MSC’s PR description?
- [ ] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example,
          modifying the set of redacted fields changes how event IDs are calculated,
          thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with
    [the appendices](https://spec.matrix.org/v1.8/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved.
      Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present,
  the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail
  any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.".
  See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about,
  but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-01-22 09:28 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +Moreover, the fact that those stages are displayed on client-driven UI, and not on a homeserver-specific domain, makes them insecure, impossible to design, or behave poorly in terms of user experienc
Is this a hard requirement? I personally prefer using one sentence per line for the reasons outlined here: https://nick.groenen.me/notes/one-sentence-per-line/

2025-01-22 09:36 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +The following MSCs are not directly part of this proposal but this proposal assumes that these are accepted:
We did need those MSCs to happen for the implementation to work correctly. They were both merged in the meantime, so I can probably get rid of this section?

2025-01-22 10:32 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +Please refer to individual proposals.
I have added a paragraph about this in dbede1e7

Resolving this conversation, reopen if anyone feels like it is not properly captured

2025-01-22 10:52 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +The following MSCs are not directly part of this proposal but this proposal assumes that these are accepted:
Did something in 152cd98f

2025-01-22 10:52 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +
Updated this table to stop mentioning OIDC-related stuff in 56a62782

2025-01-22 12:19 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +The Matrix Client-Server API currently has endpoints for authenticating and managing users.
Done in 9ff541cc

2025-01-22 12:20 UTC, sandhose commented on proposals/3861-delegated-oidc-architecture.md
> +## Potential issues
Added words about this in d76b9a29

2025-01-22 12:29 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +Existing APIs like `/_matrix/client/v3/capabilities` help clients understand which account-management API endpoints are unavailable, but they don't offer alternatives to a homeserver-provided user-in
Done in 0a86b697

2025-01-22 12:30 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +How this is intended to work, and let client offer reasonable user-experience is covered by [MSC3824: OIDC-aware clients][MSC3824].
I've clarified that those are not required for acceptance of this MSC in d76b9a29

2025-01-22 12:31 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +This section describes a sample flow, taking together the steps described in more details in the dedicated MSCs.
I've clarified that elsewhere in d76b9a29

2025-01-22 12:34 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +To build this bridge between the client user-interface and the homeserver, [MSC4191: Account management deep-linking][MSC4191] proposes a way to deep-link to the account management capabilities of th
Clarified in d76b9a29

2025-01-22 12:40 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +OpenID Connect is an effort by the OpenID Foundation to standardize on top of OAuth 2.0.
Done in 2acf4387

2025-01-23 22:23 UTC, turt2live commented on proposals/3861-next-generation-auth.md
> +Moreover, the fact that those stages are displayed on client-driven UI, and not on a homeserver-specific domain, makes them insecure, impossible to design, or behave poorly in terms of user experienc
not a hard requirement, provided the lines are somewhat short. It's mostly to avoid weirdness with github diffs when small changes bury conversations.

2025-01-25 21:55 UTC, turt2live commented on proposals/3861-next-generation-auth.md
> +On the contrary, this proposal will provide homeserver operators greater visibility into which clients are being used, helping with decisions to approve third-party clients.
non-blocking: and helps homeserver operators make decisions about their homeservers, like when to roll out features which break in some clients.

2025-01-25 21:58 UTC, turt2live approved these changes
Thanks for continuing to put work into keeping this updated! There's a few open (non-blocking) things which would be good to include in the proposal, but overall the MSC appears ready to go to FCP.

I expect that the underlying MSCs will also go into FCP quickly, but it's important (to me) that we have a document somewhere which explains why next-gen auth over UIA in particular - an MSC is a great way to do that.

2025-01-25 21:58 UTC, turt2live commented
@mscbot fcp merge

2025-01-28 10:24 UTC, erikjohnston reviewed
Looks good! I think the motivation section accidentally ends up focusing on the tangential benefits of the change rather than the core rationale of why we're doing this (see the comment)

2025-01-28 10:24 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
Isn't this a) how some MAS flows work, and b) is a relatively common paradigm?

2025-01-28 10:24 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +- The user could benefit from sharing a single browser session with multiple clients, requiring them to enter their credentials only once per physical device.
Most of these feel like "nice to haves" rather than reasons to move to OAuth2, and as such I think actually hurt the argument. We wouldn't be making such a large change for these sorts of things. Honestly, I think we could either just get rid of these, or replace them with a paragraph at the end of the section, which brings the focus back on the the paragraphs that give the actual rationale for the move.

I think the same is true for the bullet points in the previous section.

Maybe something like:

> We also get other, more minor, benefits from the change to a more common auth mechanism. For example, password managers work out the box, it'd be possible to use webauthm/passkeys, etc.

2025-01-28 10:24 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +### Benefits of authenticating end-users through the system browser
What are the benefits of using the *system* browser, versus any old browser? Do we even need to be emphasising the use of system browser?

2025-01-28 12:50 UTC, dbkr commented on proposals/3861-next-generation-auth.md
> +First step is to discover the homeserver's authorization server metadata.
Struggling a little with the duplication between MSCs here but I see Erik has already asked what I was going to ask at https://github.com/matrix-org/matrix-spec-proposals/pull/2965/files#r1931976488

2025-01-28 12:50 UTC, dbkr commented on proposals/3861-next-generation-auth.md
> +[`/_matrix/client/v3/login`]: https://spec.matrix.org/v1.13/client-server-api/#post_matrixclientv3login
Having an overview like this is incredibly useful and thanks so much for putting it together, although I am struggling to pick out what this MSC is actually intending to change about the spec between the duplicated bits of other MSCs. Is it largely the glue of how they various different MSCs fit together?

2025-01-28 13:55 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
The flow in MAS works by sending a code instead of a link for email verification. This has two advantages:

 - some platforms (like iOS/macOS) can autofill '2FA' codes got by email
 - this makes sure the user doesn't break the context of what they were doing. By making them enter a code, they will keep the browser window where they started the registration flow open while they check their email

2025-01-28 13:56 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +### Benefits of authenticating end-users through the system browser
I'm using 'system browser' here as opposed to 'an embedded web view'. Maybe I should make it clearer by calling it the 'default browser'?

2025-01-28 14:07 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +### Benefits of authenticating end-users through the system browser
Ah right, then: why not an embedded web view?

2025-01-28 15:55 UTC, richvdh commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
> as alternatives to the existing User-Interactive Authentication (UIA) APIs 
>  deprecate the existing UIA APIs

and `/login`, right?

(and `/logout`, maybe?)

2025-01-28 15:55 UTC, richvdh commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
To be honest, the term "UIA APIs" isn't very clear... there are APIs which currently *use* UIA, but I'm not sure if you plan to remove them all, or just stop them using UIA. Would be good to be more explicit here.

2025-01-28 15:55 UTC, richvdh commented on proposals/3861-next-generation-auth.md
> +Existing APIs like `/_matrix/client/v3/capabilities` help clients understand which account-management API endpoints are unavailable, but they don't offer alternatives to a homeserver-provided user-in
still no link here.

2025-01-28 18:40 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +  When this option is disabled, the CAPTCHA service expects the server to verify the domain of the challenge, which is not possible.
Not sure if listing more is useful, but captcha design is specific to certain providers, support for 2FA would require modifications, etc.

2025-01-28 18:40 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +The general idea is simple: to authenticate a user, the client redirects the user to a URL on the homeserver, which completes the authentication flow, and then redirects the user back to the client.
Doesn't it really redirect to the IdP, not necessarily the homeserver?

2025-01-28 18:40 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +- The user can use different clients without worrying about revealing their account credentials to unknown parties. Only their homeserver ever interacts with their credentials.
Again -- isn't this really the IdP? Doesn't this also protect the homeserver ever knowing the user's password?

2025-01-28 18:40 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +It would open up Matrix to a new class of clients with only partial access to the user's account.
It feels like this should be prominent in the proposal.

2025-01-28 18:40 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +In practice, OpenID Connect does not cover continuous exchanges between the application and the identity providers: there is no well-supported standard to signal new sessions, new users, sessions end
I can make some assumption, but why do we care about this in Matrix?

2025-01-28 18:40 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
And `/register`?

2025-01-31 19:27 UTC, Tynach commented on proposals/3861-next-generation-auth.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
> Things like security considerations, protecting client credentials, not re-inventing the wheel, 2FA, etc.

How are those first two achieved more when using OAuth, compared to the old way of doing things?

What if Google is forced by a government agency to keylog specific users' passwords entered into Matrix OAuth pages, as part of a secret operation against those users? Remember, Google Chrome is the most popular browser, and while parts of it are open source, the browser itself *is closed source*.

Relying on the security of a third party application means you have less ability to fix or even react to security holes that are found — or purposefully built into — those third party applications.

Besides, the arguably more important cryptographic keys that protect a user's messages and chat histories *have* to be known to the client *any*way, and *shouldn't* be known by the server. Matrix's whole design is centered around trusting the client more than the server, and requiring OAuth breaks that paradigm.

2025-03-04 13:56 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +### Benefits of authenticating end-users through the system browser
Clarified that in 246ee1e1, closing this; reopen if it's not clear enough

2025-03-04 14:01 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
> What if Google is forced by a government agency to keylog specific users' passwords entered into Matrix OAuth pages, as part of a secret operation against those users? Remember, Google Chrome is the most popular browser, and while parts of it are open source, the browser itself is closed source.

I don't think this argument holds up well, as most Android users are probably using the default Google-provided keyboard, same with the iOS keyboard… and what prevents Windows from keylogging stuff on your screen anyway?

My point is, if we're at a point where we cannot trust the default browser on your computer, there are many other possible attack vectors to consider, with nothing we can realistically do to protect ourselves

2025-03-04 14:43 UTC, marmarek commented on proposals/3861-next-generation-auth.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
It's true that it's a challenging threat model. But maybe lets try to not make things worse... Not every Matrix client is a web app, not every device to access Matrix is a smartphone etc. There are several scenarios where currently a Matrix client doesn't need to use (or trust) a huge 3rd-party application called a web browser. IMO it would be a big mistake to deprecate those scenarios. It's okay to use it for some cases (maybe even for majority cases), as in many (most?) cases it would be part of the Trusted Code Base anyway (as you noted above), but keep it possible to have an alternative.

> Besides, the arguably more important cryptographic keys that protect a user's messages and chat histories _have_ to be known to the client _any_way, and _shouldn't_ be known by the server. Matrix's whole design is centered around trusting the client more than the server, and requiring OAuth breaks that paradigm.

I don't think OAuth necessarily breaks this paradigm. But badly designed/implemented OAuth can.

2025-03-04 15:17 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +  The link sent to the user by email leads to a screen where the user is prompted to return to their client.
The last messages in this thread don't relate to the initial concern; please open a new thread if you want to raise a concern that isn't covered by any of the currently opened thread.


---

Back to the original concern of this thread: I've added an example how the email flow could be better in 60e1d749 (which is how MAS works) and I think this section already explains what it tries to achieve: it takes one example in particular, highlighting what issues there are, noting that some of them *could* be improved with the current UIA paradigm

```md
A few issues can be highlighted from this particular example:

[…the bulletpoint list…–

**Note**: Many of these points could be improved with individual improvements to each of those stages, and multiple MSCs already exist to address some of them.
```

2025-03-04 15:48 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +- The user could benefit from sharing a single browser session with multiple clients, requiring them to enter their credentials only once per physical device.
That's fair. I think what I wanted to point out, is that using the homeserver's domain name as a base for all the auth flows has many small benefits. I've reworded a bit this section in 17244908, lemme know if that matches what you meant

2025-03-04 15:53 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +First step is to discover the homeserver's authorization server metadata.
This part is there to have a full authentication flow described *somewhere*. This is whole MSC does not specify anything, but rather explains what the direction is, and how the sub-MSCs fit together to have a full 'next-gen' authentication flow, if that makes sense?

2025-03-05 08:45 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +[`/_matrix/client/v3/login`]: https://spec.matrix.org/v1.13/client-server-api/#post_matrixclientv3login
This isn't supposed to be an overview, rather linkifying a bunch of MSCs used in the text. This lets me use this markdown syntax to link: `[MSC3824: OIDC-aware clients][MSC3824]`. The overview is in the `Proposal` section of the text

2025-03-05 08:57 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +The general idea is simple: to authenticate a user, the client redirects the user to a URL on the homeserver, which completes the authentication flow, and then redirects the user back to the client.
In this iteration of the MSC, we don't separate the homeserver and the 'IdP'. Your client is logging in against your homeserver, with a different set of APIs than before; the fact that in practice it's a separate piece of software, maybe on a different domain, is an implementation detail?

2025-03-05 08:58 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +  When this option is disabled, the CAPTCHA service expects the server to verify the domain of the challenge, which is not possible.
I've tried to restrict the examples in the list only to this particular example (the matrix.org HS), which is why I haven't touched on those kind of details here

2025-03-05 08:59 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +- The user can use different clients without worrying about revealing their account credentials to unknown parties. Only their homeserver ever interacts with their credentials.
Same [as up there](https://github.com/matrix-org/matrix-spec-proposals/pull/3861/files#r1980966097); the fact that the homeserver and MAS are two pieces of software is an implementation detail

2025-03-05 09:15 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +It would open up Matrix to a new class of clients with only partial access to the user's account.
I agree! I've added a sentence about it in add4799d. wdyt?

2025-03-05 09:25 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +In practice, OpenID Connect does not cover continuous exchanges between the application and the identity providers: there is no well-supported standard to signal new sessions, new users, sessions end
Explained that better in 559762de, please reopen if it's not clear enough

2025-03-05 09:28 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +This won't prevent the homeserver from rejecting clients arbitrarily, but this was already the case with UIA.
Explained that in 6f74515f; reopen if this is not clear enough

2025-03-05 09:30 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +On the contrary, this proposal will provide homeserver operators greater visibility into which clients are being used, helping with decisions to approve third-party clients.
What I was trying to say here is "if you restrict third party clients (which you could definitely already do before), now you have better visibility of what clients people are trying to use, so you can make decisions to open up more your deployment". Does that make sense?

2025-03-05 10:27 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
Clarified what I meant in e797837a. Is that better?

2025-03-05 10:42 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +On the other hand, the previous registration flow was notoriously complex to implement both for clients and homeservers, and this proposal removes a lot of that complexity from the client side.
That's a good point, I've added words about mentions of UIA fallbacks in f48fb925

2025-03-05 10:45 UTC, sandhose commented
I've incorporated most of the comments/concerns, replied to all open threads; this is ready for another round of review

2025-03-11 09:46 UTC, dbkr commented on proposals/3861-next-generation-auth.md
> +First step is to discover the homeserver's authorization server metadata.
OK, I'm not sure about the idea of an MSC that doesn't specify anything (feels like it could just be an ancillary doc of some kind) but it seems okay.

2025-03-11 14:14 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +### Benefits of authenticating end-users through the system browser
Still, why the focus on "default" browser? Why not just say "a browser"?

2025-03-11 14:16 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +This has two important implications:
I'm wondering if this is actually true for a nefarious client? If they want they can embed a browser that the app can read the content of? I don't think anything here stops that?

2025-03-11 16:18 UTC, richvdh requested changes

2025-03-11 16:19 UTC, richvdh commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
> And `/register`?

`/register` *is* a UIA API, so is covered by the existing wording.

2025-03-11 16:20 UTC, richvdh commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
> Clarified what I meant in [e797837](https://github.com/matrix-org/matrix-spec-proposals/commit/e797837a64bf3793e2fc2f109441944718372898). Is that better?

Not really, I'm afraid. I've commented at https://github.com/matrix-org/matrix-spec-proposals/pull/3861#discussion_r1989579374. Will close this thread.

2025-03-11 16:23 UTC, richvdh commented on proposals/3861-next-generation-auth.md
> +On the contrary, this proposal will provide homeserver operators greater visibility into which clients are being used, helping with decisions to approve third-party clients.
If our concern is that admins block out clients they don't like, how does giving them more visibility about which clients people are using help?

I've commented at https://github.com/matrix-org/matrix-spec-proposals/pull/3861#discussion_r1989579374. Resolving this thread in favour of that one.

2025-03-11 16:44 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +- The user could benefit from sharing a single browser session with multiple clients, requiring them to enter their credentials only once per physical device.
I think we are still missing a high level, couple of sentences, proper rationale for moving to OAuth2 at the top. Currently the first concrete improvement mentioned is:

> When setting up a CAPTCHA challenge, CAPTCHA services expect the challenge to be served from a specific domain. Because the client can be on any domain, [Synapse currently advises disabling host verification](https://element-hq.github.io/synapse/latest/CAPTCHA_SETUP.html#getting-api-keys). When this option is disabled, the CAPTCHA service expects the server to verify the domain of the challenge, which is not possible.

which, I mean sure, is right, but feels *far* down the list of why we would want to do this.

To me, it seems like the overarching reason for OAuth2 is: to move to industry standard authentication protocol that supports full customisation by the homeserver.

2025-03-15 16:14 UTC, ara4n commented on proposals/3861-next-generation-auth.md
> +This has two important implications:
in the end, if your client is nefarious, it's game over: with or without OIDC, it could steal your credentials or your conversation history or otherwise phish you. So, perhaps the right fix here is to clarify that non-malicious clients will never get the user's full credentials (but obviously OIDC doesn't protect against malicious clients).

2025-03-15 16:46 UTC, ara4n commented on proposals/3861-next-generation-auth.md
> +## Alternatives
I was a bit surprised that we don't explicitly call out (independently of the reference to MSC3262 and friends below) that MSC3861 explicitly does not try to support using the same password for both login and encryption recovery.

Specifically, it'd be useful to spell out that when OIDC is hooked up to an existing SSO mechanism, there would be no way to link encryption recovery to your SSO credentials - and so separate recovery passphrase would always be needed for those instances.  In other words, this is a trade-off between supporting SSO or other flexible authentication... and having fancy PAKE style auth, and so for now we are consciously trading off in favour of SSO (especially given the need to support enterprise SSO auth envs).

Given SSO is incompatible with PAKE, you'd always have to treat PAKE-style approaches as a distinct auth mechanism anyway, which is why it's acceptable to punt it to a separate custom grant (and so need a new MSC to define a special PAKE-compatible Resource Owner Password Credentials flow).

2025-03-15 16:48 UTC, ara4n commented on proposals/3861-next-generation-auth.md
> +## Alternatives
(n.b. this isn't remotely a blocking concern; i just think it would be useful to capture the full rationale for the design in the overview MSC if poss)

2025-03-17 14:57 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +### Benefits of authenticating end-users through the system browser
You're right, any browser makes sense; did a5386b57

2025-03-17 18:36 UTC, KitsuneRal reviewed
A few non-blocking comments/suggestions.

2025-03-17 18:36 UTC, KitsuneRal commented on proposals/3861-next-generation-auth.md
> +Consistent with [MSC4186], this proposal can also be referred to as 'augmented atomic authentication', abbreviated to 'AAA'.
Please no, it overlaps with ["Authentication, authorization, and accounting" paradigm](https://en.wikipedia.org/wiki/Authentication,_authorization,_and_accounting), security people widely use the same acronym for it.

2025-03-17 18:36 UTC, KitsuneRal commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
Since this MSC explicitly doesn't deprecate anything (see below), I suppose the details of the eventual deprecation don't need to be discussed here any more?

2025-03-18 00:18 UTC, anoadragon453 commented on proposals/3861-next-generation-auth.md
> +[`/_matrix/client/v3/login`]: https://spec.matrix.org/v1.13/client-server-api/#post_matrixclientv3login
@sandhose I think Dave was referring to this MSC as a whole, rather than just this portion of the document (n.b. @dbkr I'd suggest using the "comment on this file" button for this types of questions in future to avoid confusion:)

![image](https://github.com/user-attachments/assets/b731c32b-14ed-481a-b352-2ff97d2dd3b9)

@sandhose simply put, I believe the question is "if I were writing a spec PR for this MSC... what would I write?".

2025-03-18 14:14 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +While this won't prevent a homeserver from arbitrarily rejecting clients (which is already possible with UIA based on the client's user-agent string or redirect URI, for example), this proposal will
> which is already possible with UIA

I meant 'legacy' /login in this case, fixed that in 9df174c7

2025-03-18 14:19 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +While this won't prevent a homeserver from arbitrarily rejecting clients (which is already possible with UIA based on the client's user-agent string or redirect URI, for example), this proposal will
> Sorry, but I still don't think your updated text is clear here. It still seems to be in conflict with the previous paragraph where it says that it is problematic to let server admins decide which clients to allow.

How about 8e114016?

This should be read as:

 - usually people don't like OAuth 2.0/OIDC in open protocols because it requires a contract between the client and the service (e.g. a manual registration in a dev portal)
 - to mitigate this, we define a way to dynamically register the client

2025-03-18 14:20 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +As a first step, it introduces those APIs as alternatives to the existing User-Interactive Authentication (UIA) APIs, both the ones used in authentication and UIA-protected APIs related to account ma
I keep using 'UIA' as '/login', sorry for the confusion 😅

2025-03-18 15:12 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +Consistent with [MSC4186], this proposal can also be referred to as 'augmented atomic authentication', abbreviated to 'AAA'.
That was a joke/easter egg, as MSC4186 has a notoriously bad acronym, SSS for 'simplified sliding sync', but has nothing 'sliding' about

2025-03-18 15:39 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +Consistent with [MSC4186], this proposal can also be referred to as 'augmented atomic authentication', abbreviated to 'AAA'.
Removed in 1706907112fc3fd98b09e79dba91cbc5487451a3

2025-03-18 16:51 UTC, KitsuneRal commented on proposals/3861-next-generation-auth.md
> +Consistent with [MSC4186], this proposal can also be referred to as 'augmented atomic authentication', abbreviated to 'AAA'.
Oh, now I understand. Sorry - my sense of humour is known to be flawed ;(

2025-03-18 17:01 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +In those cases, the host application cannot control or monitor what is happening within the embedded browser view, protecting the user's credentials, but that view shares the same context as the syst
I think it's still important to point out what those API provides, why they are safe to use compared to web views?

2025-03-18 17:03 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +In those cases, the host application cannot control or monitor what is happening within the embedded browser view, protecting the user's credentials, but that view shares the same context as the syst
Prehaps we can just drop the 'protecting the user's credentials' part?

```suggestion
In those cases the host application cannot control or monitor what is happening within the embedded browser view, but that view shares the same context as the system-wide browser.
```

2025-03-18 17:35 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +This has two important implications:
The text is asserting stronger guarantees than you can generally get, and then trying to use that to justify the move to OAuth2. Certainly its nice that in certain cases we can make it harder for bad clients to steal credentials, but we can't really claim too much here.

I think the reason that this (and the other bits) grate for me when reading is that all of these sections are under "Motivation", which starts by saying:

> To understand this proposal, it is important to lay out the reasoning behind it. ... This section explains this reasoning before getting into the detailed proposal.

I think its great that we are documenting why we are doing this, but I don't think these sections are really *why* we want to move to OAuth2, but are instead listing some nice benefits of doing so.

If we are going to give a rationale, then for documentation purposes I think its important that its accurate. Equally, I don't want to bog down this MSC by suggesting lots of changes that don't change the practical proposal.

As such, I propose we add a "Rationale" section before the current "Motivation" section that says something along the lines of (but with better English):

> The goal of this MSC is to propose a new set of authentication APIs for Matrix, based on the OAuth 2.0 and OpenID Connect (OIDC) specifications. To understand this proposal, it is important to lay out the reasoning behind it.
>
> ### Rationale
>
> Matrix currently uses a custom protocol for authentication, one that hasn't been updated in many years. This leads to two main problems:
>   1.  The custom protocol does not follow best practices, nor does it use the collective experience of other authentication protocols.
>   2. While relatively generic, the custom protocol does not currently support many desired features that users and organisations actually want.
>
> These points could be addressed by iterating on the current protocol, however using the industry standard OAuth2 allows us to benefit from their experience without having to build a competing (relatively generic) authentication protocol. We also will benefit more easily from any further enhancements, or best practice recommendations, of OAuth2.
>
> ### Background and motivation
> 
> This section expands on the benefits of moving to OAuth2. It is purely informative and not part of the actual proposal. The proposal itself is high-level, and the technical implications are split into separate, more focused MSCs.
>
> ...


Which I think a) gives a (hopefully) accurate enough summary of the core rationale for moving to OAuth2, and b) allows us to keep the current sections that allow some of the problems of the existing protocol and benefits to moving to OAuth2.

2025-03-18 17:52 UTC, erikjohnston commented on proposals/3861-next-generation-auth.md
> +This has two important implications:
(Otherwise I'm happy with the meat of the proposal)

2025-03-18 20:34 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +- The user can use different clients without worrying about revealing their account credentials to unknown parties. Only their homeserver ever interacts with their credentials.
I think calling it the IdP doesn't imply it is a separate piece of software. 🤷

2025-03-19 11:40 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +In practice, OpenID Connect does not cover continuous exchanges between the application and the identity providers: there is no well-supported standard to signal new sessions, new users, sessions end
Would it be fair to say that the impact for Matrix is mostly only servers and clients will be able to mostly implement "normal" OAuth2?

2025-03-25 09:53 UTC, erikjohnston requested changes
Remaining open concern is: I think we need to make it clear what the rationale is vs what is background information: https://github.com/matrix-org/matrix-spec-proposals/pull/3861#discussion_r2001607299

2025-03-25 13:46 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +This has two important implications:
Thanks a lot for the suggestion. I've incorporated it in 5bb8c579

2025-03-25 16:23 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
I've reworded that a little bit in f398886b

We plan to deprecate the existing account management APIs and UIA-protected endpoints, replacing them as needed. As we don't yet deprecate, there is no exhaustive list of what we deprecate

2025-03-25 16:36 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +While this won't prevent a homeserver from arbitrarily rejecting clients (which is already possible with UIA based on the client's user-agent string or redirect URI, for example), this proposal will
After discussing this internally, I simplified this in a379a33f

2025-03-25 16:38 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +- The user could benefit from sharing a single browser session with multiple clients, requiring them to enter their credentials only once per physical device.
I believe this was covered by 5bb8c579, please reopen if not

2025-03-25 16:40 UTC, sandhose commented on proposals/3861-next-generation-auth.md
> +In practice, OpenID Connect does not cover continuous exchanges between the application and the identity providers: there is no well-supported standard to signal new sessions, new users, sessions end
That is correct; this is why the sentence right before talks about 'off-the-shelf identity providers for Matrix *homeservers*'?

2025-03-25 17:16 UTC, clokep commented on proposals/3861-next-generation-auth.md
> +In practice, OpenID Connect does not cover continuous exchanges between the application and the identity providers: there is no well-supported standard to signal new sessions, new users, sessions end
I think that's a bit subtle, but fair enough!

2025-03-25 17:39 UTC, anoadragon453 commented
@mscbot concern checklist not complete

We're waiting on the dependent MSCs to be accepted before accepting this one, essentially.

2025-03-25 17:39 UTC, anoadragon453 approved these changes

2025-03-25 17:39 UTC, anoadragon453 commented on proposals/3861-next-generation-auth.md
> +The following MSCs are meant to cover less escential parts of the authentication and account management flows.
```suggestion
The following MSCs are meant to cover less essential parts of the authentication and account management flows.
```

2025-03-25 17:49 UTC, richvdh commented on proposals/3861-next-generation-auth.md
> +The long-term goal is to deprecate the existing UIA APIs and replace them with the new OAuth 2.0/OIDC-based APIs.
I'm still not convinced that we actually want to deprecate all the endpoints that are currently protected by UIA, rather than just removing the requirement that they be protected by UIA, but I guess it's not important.

2025-03-31 17:00 UTC, anoadragon453 commented
> We're waiting on the dependent MSCs to be accepted before accepting this one, essentially.

@mscbot resolve checklist not complete

The dependent MSCs aren't accepted yet. But given they're in final-comment-period, I think we can at least put this one into FCP as well without needing to wait for the others to finish.

If we cancel FCP on one of the dependent MSCs, we'll do the same for this one.

2025-04-05 18:40 UTC, merged

2025-06-08 11:09 UTC, zecakeh commented
I guess we can say that https://github.com/matrix-org/matrix-spec/pull/2159 is the most likely candidate to be a spec PR for this.

2025-06-20 14:51 UTC, richvdh commented
> I guess we can say that [matrix-org/matrix-spec#2159](https://github.com/matrix-org/matrix-spec/pull/2159) is the most likely candidate to be a spec PR for this.

And it is now merged.