Proposal for a `M_USER_NOT_APPROVED` error code
matrix-org/matrix-doc pull request #3866
Opened 2022-08-12 16:08 UTC by babolivier

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/babolivier/m_not_approved/proposals/XXXX-user-not-approved-error.md)

2022-08-12 19:36 UTC, uhoreg commented on proposals/3866-user-not-approved-error.md
> +This document proposes the addition of a new `M_USER_NOT_APPROVED` error code to
As a bike-shed-y comment, "not approved" could be interpreted as the user having been rejected.  Maybe "...AWAITING_APPROVAL" or "...APPROVAL_PENDING" would be better.

2022-08-15 10:47 UTC, babolivier commented on proposals/3866-user-not-approved-error.md
> +This document proposes the addition of a new `M_USER_NOT_APPROVED` error code to
Good point. I've updated the error code to `M_USER_AWAITING_APPROVAL`.

2022-08-22 10:11 UTC, anoadragon453 commented
The author of this MSC has indicated that it is ready for review by the SCT.

2022-08-22 10:30 UTC, deepbluev7 commented on proposals/3866-user-not-approved-error.md
> +attempts to log in, `POST /_matrix/client/v3/login` requests are responded to
Is this also supposed to handle, which never uses the register step?

2022-08-22 10:33 UTC, deepbluev7 commented on proposals/3866-user-not-approved-error.md
> +deactivated).
I think I would like to see, how that looks like in practice. If someone registers on my server, they might not know, how they will get contacted about their account request being approved or denied. Which means they basically just end up retrying to login over and over. Some way to respond with a message about how the user can expect to be notified of the approval or some long polling endpoint might be useful?

2022-08-23 04:22 UTC, turt2live requested changes
Per SCT room, and in line with https://github.com/matrix-org/matrix-spec-proposals/pull/3848, I think this needs a client implementation to prove the following facts:

* Existing, unmodified, clients don't explode when they see this error code (this can be done with a manual test for the major platforms)
* At least 2 clients on different major platforms are capable of adopting the change

Once these are proven, it may very well be ready for FCP. I'm always a bit nervous about going from open MSC to FCP this quickly though, especially for error codes which have bitten us badly in the past (hence the ask for more involved client development).

2022-09-28 11:06 UTC, babolivier commented on proposals/3866-user-not-approved-error.md
> +attempts to log in, `POST /_matrix/client/v3/login` requests are responded to
I'm assuming the missing word here is "SSO", in which case the answer is yes, will update.

2022-09-28 11:14 UTC, babolivier commented on proposals/3866-user-not-approved-error.md
> +deactivated).
I'm not sure long-polling makes much sense given approval is manual, which means it could take hours or days/weeks to come through depending on how responsive the admin is.
A field in the response that indicates how the user should be informed of approval is a good idea. Though the issue here is that at this point we might not have a good way to reach out to the user, so if e.g. they didn't register with an email address (either because the server doesn't support it, or made it optional, etc), then we don't have much choice but to fall back to telling the user that their admin might get in touch with them oob or just to try logging in again later.
Will update the MSC with the additional response field and mention this issue in the "Potential issues" section.

2022-09-28 16:00 UTC, babolivier commented on proposals/3866-user-not-approved-error.md
> +attempts to log in, `POST /_matrix/client/v3/login` requests are responded to
Done: https://github.com/matrix-org/matrix-spec-proposals/pull/3866/commits/3df48d3349538081cc015948a0be12ccb783707a

2026-07-20 20:00 UTC, babolivier commented
Heads up I am formally abandoning this proposal since I don't currently have time for Matrix spec contributions (I'm not sure whether I should close it or wait for someone to adopt it).

2026-07-20 20:15 UTC, closed without merging