MSCXXXX: Relation-based redactions
matrix-org/matrix-doc pull request #3912
Opened 2022-10-18 11:58 UTC by babolivier

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/babolivier/relation_redaction/proposals/XXXX-relation-based-redaction.md)

2022-10-18 13:17 UTC, clokep commented on proposals/3912-relation-based-redaction.md
> +## Alternatives
I think another alternative is to define which relation types always get related events redacted. This has the limitation that generic things like `m.reference` can't really be handled well though.

🤷 Not sure it is worth mentioning, but that was what I initially assumed the solution would be upon reading the first few sentenences!

2022-10-19 10:15 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +## Alternatives
Yeah, and also it doesn't allow as much flexibility in terms of UX/UI. For example, a client might want to show a check box to room moderators when deleting a root's thread to allow them to also delete the whole thread. I'll add a note.

2022-10-19 10:43 UTC, clokep commented on proposals/3912-relation-based-redaction.md
> +## Alternatives
Definitely. Thanks for considering! 👍

2022-10-19 20:53 UTC, FSG-Cat commented on proposals/3912-relation-based-redaction.md
> +# MSC3912: Relation-based redaction
I personally think that this MSC could list MSC2244 as a soft dependency. 

What i mean by a soft dependency in this case is that this MSC is enhanced with mass redactions in the spec but is able to function without it.

2022-10-20 09:01 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +# MSC3912: Relation-based redaction
Yeah I wasn't pondering on that, I'll add a note for it.

2022-10-20 09:59 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +# MSC3912: Relation-based redaction
Done in https://github.com/matrix-org/matrix-spec-proposals/pull/3912/commits/85b270a46201475ce006a778324ef82715f702af

2022-10-20 10:42 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +ignore `with_relations` properties in the `unsigned` object of redaction events
Not sure if `unsigned` is the right place for the server to put it, or if it should just go in the event's `content`.

2022-10-21 16:11 UTC, anoadragon453 commented on proposals/3912-relation-based-redaction.md
> +ignore `with_relations` properties in the `unsigned` object of redaction events
If it's only useful to the local homeserver that sent it, then perhaps it shouldn't go in the event at all, but just tracked internally by the homeserver (in a database table, perhaps)?

2022-10-21 16:21 UTC, anoadragon453 commented on proposals/3912-relation-based-redaction.md
> +performing the redaction. The response body of this endpoint does not change.
Are there/could there be a case where the client would like to redact one set of events with relation type X, but not another set of events with relation type X?

Essentially: are we sure that no group of two features or more will use the same relation type?

An alternative may be instead to either only - or additionally - specify event types you'd like to redact.

2022-10-21 16:21 UTC, anoadragon453 commented on proposals/3912-relation-based-redaction.md
> +of the redaction request's sender.
Note that this will mean that anyone that tries to, say, respond to a thread that was redacted long in the past will have that message redacted immediately afterwards.

Also note that since only the homeserver that initially kicked off the redaction of the whole thread is responsible for redacting new related events; if that homeserver leaves the room then those messages will remain unredacted.

Just some edge cases to consider, but they might not warrant trying to fix.

2022-10-21 16:21 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +ignore `with_relations` properties in the `unsigned` object of redaction events
I added this paragraph after I tried implementing it in Synapse, which is quite non-trivial otherwise. The reason is that insertions to the redactions table is done in the event persistence path (where it's not trivial to add extra data which isn't part of the event), and the `/redact` endpoint can be handled by workers, which makes it potentially tricky for it to write into the database. So ideally it wouldn't be in the event at all, but I'm trying to balance that with not making it too difficult on server developers to implement it.

2022-10-21 16:28 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +performing the redaction. The response body of this endpoint does not change.
I did a quick survey of the features using relations while writing the proposal. There are generic relation types (namely `m.reference`), but when it's used the semantics of the related messages can always be inferred by clients by looking at the type of the root event (`m.poll.start` for polls, `m.beacon_info` for live location sharing, etc). If that was not the case I believe there would be other annoying issues like clients not being able to figure out how to render an event. So I don't really see the point of also supporting also specifying event types. And it's something we can always add in a separate MSC if we realise we need it further down the line.

2022-10-21 16:29 UTC, anoadragon453 commented on proposals/3912-relation-based-redaction.md
> +ignore `with_relations` properties in the `unsigned` object of redaction events
With my spec hat on, that sounds quite Synapse specific... I'm not sure if it's a good enough reason on its own to spec an extra field in an event.

2022-10-21 16:30 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +ignore `with_relations` properties in the `unsigned` object of redaction events
My point is that if this is an issue with Synapse it can be an issue with other servers. And this paragraph is more meant to serve as an implementation hint than a field that should be spec'd - I'll reword to make it clearer.

2022-10-21 16:34 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +of the redaction request's sender.
> Note that this will mean that anyone that tries to, say, respond to a thread that was redacted long in the past will have that message redacted immediately afterwards.

Yes, this is by design. When you want to remove a discussion from a room when moderating it, for example, you usually don't want other people to restart it (for the same reason some forums auto-lock threads after it considers the discussion has ended). Or if a client is slow to send an edit and you delete the root message with all of the edits before the slow client sends its edit, you don't want that to re-add data that should be deleted to the room.

> Also note that since only the homeserver that initially kicked off the redaction of the whole thread is responsible for redacting new related events; if that homeserver leaves the room then those messages will remain unredacted.

This is a good point, and I don't think there's a good answer to this, because all redactions are sent on behalf of the user who sent the `/redact` request. Technically it's an issue if the user who sent the redaction leaves the room (not even the whole server). I'll add it to the `Potential issues` section.

2022-10-21 16:40 UTC, anoadragon453 commented on proposals/3912-relation-based-redaction.md
> +ignore `with_relations` properties in the `unsigned` object of redaction events
OK - if you do store it in `unsigned`, be sure to strip it again before returning it to client/sending to other homeservers.

This has bitten Synapse in the past: https://github.com/matrix-org/synapse/pull/14064

2022-10-21 16:41 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +ignore `with_relations` properties in the `unsigned` object of redaction events
Done: https://github.com/matrix-org/matrix-spec-proposals/pull/3912/commits/5823324ae696f13ab37e45b2b4f8ca138110153f

2022-10-21 16:41 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +of the redaction request's sender.
Done: https://github.com/matrix-org/matrix-spec-proposals/pull/3912/commits/5823324ae696f13ab37e45b2b4f8ca138110153f

2022-10-21 16:45 UTC, anoadragon453 commented on proposals/3912-relation-based-redaction.md
> +performing the redaction. The response body of this endpoint does not change.
I assume clients must look at the `type` of the related event, otherwise they wouldn't be able to differentiate between stable and unstable versions of a related event (which may have different schemas).

On the flip side though, only specifying the relation type allows you to redact both the unstable and stable versions of a related event without needing to specify the unstable type (avoiding tech debt!).

You're right in that we can always add a field later if need, so let's just go with that for now.

2022-11-22 16:35 UTC, turt2live commented on proposals/3912-relation-based-redaction.md
> +## Potential issues
`with_relations` also assumes the client is aware of the relation types associated with an event: in the case of moderation, the client might not be aware. This could be solved by allowing `with_relations` to also be a boolean (default `false`, similar to just not being present) - when `true`, *all known child events* are also redacted.

2022-11-23 10:54 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +## Potential issues
That is a very good point, though I'm wondering about the impact making this a flexible type can have on implementations using strictly typed languages. How about introducing a catch-all `"*"` value, which if found in the list means "any relation type"?

2022-11-26 08:59 UTC, jplatte commented on proposals/3912-relation-based-redaction.md
> +## Potential issues
As maintainer of Ruma, I don't have a strong feeling here. We will want to use an enum with the known relation types + fallback variant anyways, whether one of the possible valued is represented as a bool in the serialized format doesn't matter that much.

My initial gut reaction was that the bool is cleaner but since `rel_type`s only have a handful of possible values, I guess `"*"` is perfectly fine too (and I'm pretty sure there's at least one case where that is already a special value).

2022-12-07 10:18 UTC, weeman1337 commented
I am currently working on adding this to the Matrix JS SDK.

This is an extension to an existing endpoint. The same would probably apply to the function call in the SDK: Current plan is to add an option tot he redact call. How do you think the SDK should behave in this case?

- Send the event anyway. Means the caller is responsible to check for server side support before.
- Check for server side support on redaction with `with_relations` and raise an error if no support.

2022-12-07 10:36 UTC, babolivier commented
Hey @weeman1337, this is probably something the Element Web team would be better positioned to answer (since it's an implementation detail), but I would expect clients to check for server support and only show the feature to the user if there is server-side support for it.
Also, please use threads to comment on MSCs (by clicking on a line in the diff), since it makes the timeline more readable :slightly_smiling_face:

2022-12-19 13:03 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +Causes events `$a` and `$b` to both get redacted.
To be explicit, the link only works one way? So in this example, `$some_event_id` will not be redacted, despite `$a` having an `m.replace` relationship to `$some_event_id` ?

2023-03-14 12:52 UTC, babolivier commented on proposals/3912-relation-based-redaction.md
> +Causes events `$a` and `$b` to both get redacted.
Can't update the MSC to clarify because I don't have write access anymore, but that is correct. I'm not sure I clearly remember the reason though (and I can't look it up since that was likely recorded in private documents/threads that I don't have access to anymore - maybe @giomfo can help), but I remember it being an explicit decision.

2023-03-20 09:31 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +Causes events `$a` and `$b` to both get redacted.
@richvdh We didn't consider this use case in our initial discussion. My demand was focused on `m.reference` value of relation. I think your remark should be taken into account to update this MSC

2023-04-07 08:50 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +Causes events `$a` and `$b` to both get redacted.
First the purpose of this MSC is to be able to redact some child events related to the redacted event. We don't target to redact the potential parent event. So here in this example, `$some_event_id` will not be redacted on purpose.

The `m.replace` relation is not the most suitable example to illustrate this change in real life. I consider `m.reference` is the actual targeted relation by this MSC. 
@richvdh: Should I update the MSC with another example, or just mention that `$some_event_id` will not be redacted on purpose?

On another hand, your remark inspired me an extension of this MSC. I consider we should not consider the possibility to spread the redaction in reverse the events tree here, but I think we may want to spread it down. I mean the user may want to redact all the child events which are related to the redacted child events. By considering the example: 
```
PUT /_matrix/client/v3/rooms/!someroom:example.com/redact/$some_event_id/foo
{
    "with_relations": ["m.replace"]
}
```
Causes events `$some_event_id` and `$a` to both get redacted, whereas the end user may want to redact `$b` too.

@richvdh @turt2live: Should I update this MSC to add a new optional `spread` property to the body (`false` by default)? `true` would mean to propagate the redaction through the child events respecting the provided relations. (Any suggestion to name this property is welcome)

2023-04-07 09:07 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +## Potential issues
@turt2live In order to unblock this MSC, I will ignore this suggestion, it should be handled in another MSC if need. For the moment the moderator will have to list all knows relation types.

I let you think about the suggested boolean `spread` mentioned [here](https://github.com/matrix-org/matrix-spec-proposals/pull/3912/files#r1160552838). If we go for it, I plan to specify to ignore it if `with_relations` is missing or empty. But in order to satisfy your demand here, we may consider that the redaction is propagated to all child events whatever is the relation if no relation is provided and `spread` is `true`. wdyt?

2023-04-25 11:58 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +# MSC3912: Relation-based redaction
Though, tbh, every time I read this title, I think it must be some new way of sending a redaction request, that requires the redacting event to have an `m.relates_to` to the original event.

Maybe "Redaction of related events" would be be better?

2023-04-25 12:16 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +Causes events `$a` and `$b` to both get redacted.
It has to be said that the current example is somewhat confusing. As https://spec.matrix.org/v1.6/client-server-api/#validity-of-replacement-events says: "you cannot edit an edit", so `$b` is not actually a valid edit event. (Though we should make sure that we consider this situation and make the behaviour explicit in the MSC.)

> The `m.replace` relation is not the most suitable example to illustrate this change in real life.
> I consider `m.reference` is the actual targeted relation by this MSC.

Why `m.reference`? Because that is used by MSC3489?  To be honest, the `m.replace` relation seems a fairly clear usecase to me - though as above, the example is confusing.

> @richvdh: Should I update the MSC with another example, or just mention that `$some_event_id` will not be redacted on purpose?

My recommendation would be:
 1. Remove the `m.relates_to` section of `$a`.
 2. Keep the example request as-is.
 3. Make an explicit mention that a redaction of `$b` would *not* cause `$a` to be redacted, because we do not consider parent events.
 4. Give an explicit statement on what happens to events that do not meet the [validity requirements](https://spec.matrix.org/v1.6/client-server-api/#validity-of-replacement-events) for edited events (and consider if there are similar issues for other relationship types)

> @richvdh @turt2live: Should I update this MSC to add a new optional `recursive` property to the body

I'm not sure we have a usecase for this?

2023-05-04 15:14 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +Causes events `$a` and `$b` to both get redacted.
@richvdh Hi, I updated this MSC by following your recommendations (see https://github.com/matrix-org/matrix-spec-proposals/pull/3912/commits/7fe8d6f83cda2f89829bd6962336d1a8da977d75). I let you resolve this conversation or add some new comments

2023-05-04 15:15 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +# MSC3912: Relation-based redaction
@richvdh FYI I changed the title (see https://github.com/matrix-org/matrix-spec-proposals/pull/3912/commits/7fe8d6f83cda2f89829bd6962336d1a8da977d75)

2023-05-04 15:32 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +We add a new optional `with_relations` property to the body of the [`PUT
@richvdh If we rename this property, we will have to update all the existing implementations (server and clients). I'm ok to go for this renaming, but can you confirm this is actually relevant. What should we do with the existing `org.matrix.msc3912.with_relations`?

2023-05-04 16:22 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +We add a new optional `with_relations` property to the body of the [`PUT
The existing, unstable, name, can stay: we can just fix this when we switch from unstable names to stable names.

Presumably we are going to have to update all of the implementations anyway when we switch from unstable to stable identifiers?

In general, I think it's going to be quite confusing if introduce a new term ("relations") to refer to event relationships. They are confusing enough as it is.

By the way, looking at this again, I much prefer `with_rel_types`.

2023-05-29 13:00 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +We add a new optional `with_relations` property to the body of the [`PUT
resolved by 55060fc3b4634215d417b4cf280e8cda1bb64613

2023-05-29 13:04 UTC, giomfo commented on proposals/3912-relation-based-redaction.md
> +## Potential issues
@turt2live FYI I added the catch-all `"*"` value in this commit 55060fc3b4634215d417b4cf280e8cda1bb64613

2023-05-29 13:59 UTC, giomfo commented
@richvdh @turt2live FYI I resolved all the pending discussions on this MSC with my 2 last commits.
I filed a new issue on each platform to update the current implementation according to the changes introduced by the [last commit](https://github.com/matrix-org/matrix-spec-proposals/pull/3912/commits/55060fc3b4634215d417b4cf280e8cda1bb64613)
- synapse: https://github.com/matrix-org/synapse/issues/15687
- web: https://github.com/vector-im/element-web/issues/25471
- ios: https://github.com/vector-im/element-ios/issues/7563
- android: https://github.com/vector-im/element-android/issues/8481

2023-05-31 10:37 UTC, richvdh requested changes

2023-05-31 10:37 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +of the redaction request's sender.
The Synapse PR referenced in the PR description (https://github.com/matrix-org/synapse/pull/14260) says:

> This implementation is lacking a way to keep watch for incoming events that match the redaction criteria after the redaction request finishes, that'll come in a separate PR.

Is there any indication that this second part has happened? If not, then I don't think that counts as a complete implementation of the MSC and we should remove those parts from the MSC.

2023-05-31 11:13 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +/_matrix/client/versions` requests.
presumably there is some difference between  `org.matrix.msc3912` and `org.matrix.msc3912.stable`? Please make it explicit what that difference is.

2023-05-31 11:18 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +### Unstable feature in `/version`
```suggestion
### Unstable feature in `/versions`
```

2023-05-31 11:20 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +/_matrix/client/versions` requests.
(I think https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3827-space-explore.md#unstable-prefix does a decent job of this -- in particular it explains what clients should do at each stage)

2023-05-31 11:26 UTC, richvdh commented on proposals/3912-relation-based-redaction.md
> +/_matrix/client/versions` requests.
are we sure we need `org.matrix.msc3912.stable` ? We should only spec a "stable"  `unstable_feature` if we absolutely need to get this feature into widespread use before homeserver implementations support the spec version which includes this.

2026-07-20 20:00 UTC, babolivier commented
Heads up I am formally abandoning this proposal since I don't currently have time for Matrix spec contributions (I'm not sure whether I should close it or wait for someone to adopt it).

2026-07-20 20:15 UTC, closed without merging