MSC: Inhibit profile propagation
matrix-org/matrix-doc pull request #4069
Opened 2023-10-23 04:16 UTC by turt2live

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/travis/msc/inhibit-profile/proposals/0000-inhibit-profile-propagation.md)

2023-10-23 05:28 UTC, tezlm commented on proposals/4069-inhibit-profile-propagation.md
> +## Alternatives
Instead of propagating at `/avatar_url` and `/displayname`, it could be part of `m.room.member`. A `"locked": true` (or similar) in the content would cause the server to not update that member event.

2023-11-14 23:11 UTC, turt2live commented on proposals/4069-inhibit-profile-propagation.md
> +## Alternatives
so, I've been thinking about this a lot. There's some potential privacy concerns with revealing the information. Specifically, it tells other members of the room that the user is *definitely* using a customized, non-default, profile in the room. On the other hand, any malicious party wanting to make use of that information could just GET the user's default profile to find their "real" profile anyways. A separate MSC would be good to add protections/guarantees around the user's [default] profile (who can access it, etc).

Eventually it'd also be good to move the profile *out* of the `m.room.member` event, to give at minimum separation of concerns. Currently the membership event's primary purpose is to denote the user's, well, membership. Profile information is added on as a convenience. While scalable, it feels a bit overloaded to use the event for two things.

The third concern is mostly one of backwards compatibility. Clients may already have UX which says the user's profile changes *everywhere*. If we add `locked: true` to the membership event, that client UX is now a lie. This is relatively minor, but worth noting as an incompatibility. By preventing propagation at the endpoint level, existing clients can maintain their UX and new clients can more obviously add a toggle or similar to "overwrite" the profile in all rooms, or otherwise tailor their UI for their specific use case.

Overall, I think I'm still in favour of using the endpoint-level control, though a counter MSC to discuss the `m.room.member` flagging would be interesting.

2024-12-11 03:02 UTC, olivia-fl commented on proposals/4069-inhibit-profile-propagation.md
> +## Alternatives
A possibly third option: `m.profile_locked` as a per-room account data event. This state would not be visible to other users. I would prefer this to a `locked` property in the membership event, but would prefer endpoint-level control over both.

2025-12-01 03:46 UTC, cloudrac3r requested changes
I think this feature should work on the DELETE endpoints as well as PUT, but right now the MSC only says PUT. Want to change it?

2026-07-23 04:16 UTC, turt2live commented
https://github.com/matrix-org/matrix-spec-proposals/pull/4466 has gotten more traction - closing in favour of that.

2026-07-23 04:16 UTC, closed without merging