MSC4180: Additional Error Codes for submitToken endpoint
matrix-org/matrix-doc pull request #4183
Opened 2024-08-28 16:12 UTC by dbkr

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/dbkr/threepid_submittoken_errors/proposals/4180-submitToken-error-codes.md)

2024-08-28 17:47 UTC, turt2live commented
I don't feel as though implementation is required for this MSC.

@mscbot fcp merge

2024-08-28 19:45 UTC, Johennes commented on proposals/4180-submitToken-error-codes.md
> +# MSC4180: Additional Error Codes for submitToken endpoint
```suggestion
# MSC4183: Additional Error Codes for submitToken endpoint
```

I think it's 4183?

2024-08-29 10:08 UTC, dbkr commented on proposals/4180-submitToken-error-codes.md
> +# MSC4180: Additional Error Codes for submitToken endpoint
thanks, must have been some issues filed this time!

2024-10-01 18:23 UTC, anoadragon453 commented on proposals/4183-submitToken-error-codes.md
> +the new code. We say that this is acceptable in favour of avoiding the complexity of negotiating error
> Once an identity server (or homeserver) switches to use the new error code, they may not recognise the error condition correctly until updated to support the new code.

I'm failing to understand what this means. Is "they" the homeserver?

2024-10-01 18:23 UTC, anoadragon453 commented on proposals/4183-submitToken-error-codes.md
> +None forseen.
```suggestion
None foreseen.

## Alternatives

None considered.

## Security considerations

None foreseen.
```

2024-10-01 18:23 UTC, anoadragon453 commented on proposals/4183-submitToken-error-codes.md
> + * `M_TOKEN_INCORRECT`: Indicates that the token that the user entered to validate the session is incorrect.
Would it be worth re-using/redefining `M_UNKNOWN_TOKEN` from the C-S API?

2024-10-01 18:23 UTC, anoadragon453 commented on proposals/4183-submitToken-error-codes.md
> +uses of this API will not currently be receiving a sensible error code in this situation anyway.
```suggestion
users of this API will not currently receive a sensible error code in this situation anyway.
```

2024-10-02 10:35 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> + * `M_TOKEN_INCORRECT`: Indicates that the token that the user entered to validate the session is incorrect.
Oh, yes, probably

2024-10-02 10:38 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> + * `M_TOKEN_INCORRECT`: Indicates that the token that the user entered to validate the session is incorrect.
On second thoughts... that's talking about an access token whereas this is the user entering a code that's been sent to them, so they're not really the same thing. I think maybe it's clearer if it's a separate code? I can update the MSC to call this out if you agree.

2024-10-02 10:44 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +the new code. We say that this is acceptable in favour of avoiding the complexity of negotiating error
Yeah, that wasn't super clear. Is that better?

2024-10-23 08:59 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +be the same as the Identity API's `submitToken` endpoints. This MSC also affects this.
Done

2024-10-23 11:34 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +to specify that the entire API is the same, including response / error codes, rather than just parameters.
Hopefully clearer?

2024-11-05 17:00 UTC, richvdh requested changes

2024-11-05 17:00 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +to specify that the endpoint is the same as the I/S API version in all ways, including response / error codes, rather than just parameters.
wait, what? this came out of left field.  Why are we suddenly changing `requestToken` in an MSC which purports to be about `submitToken`? 

There doesn't seem to be any justification for this in the proposal, or discussion of it in general.

What exactly would need to change to bring the current definition into line with the I/S API?

2024-11-05 17:01 UTC, richvdh commented
@mscbot concern lack of clarity about changes to requestToken

2024-11-05 17:05 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +to specify that the endpoint is the same as the I/S API version in all ways, including response / error codes, rather than just parameters.
ohhh by "the endpoint" do you mean "the endpoint referenced by the `submit_url` response field"? Could you say so if so?

Still, presumably you don't mean "in all ways" -- for example, it doesn't need an IS access token. Would be good to tighten this up a bit.

2024-11-18 14:52 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> + * `M_TOKEN_INCORRECT`: Indicates that the token that the user entered to validate the session is incorrect.
Noted this in c026da70

2024-11-18 14:59 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +to specify that the endpoint is the same as the I/S API version in all ways, including response / error codes, rather than just parameters.
Yep, indeed, that wasn't very clear, hopefully better now.

2024-11-26 17:31 UTC, richvdh requested changes

2024-11-26 17:31 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +to specify that both request and response parameters / error codes are the same as the I/S API version, rather than just parameters, apart from needing an I/S API token.
```suggestion
Also change the `submit_url` field in the response to [`POST
/_matrix/client/v3/account/3pid/email/requestToken`](https://spec.matrix.org/v1.11/client-server-api/#post_matrixclientv3account3pidemailrequesttoken),
to specify that response parameters and error codes are the same as the I/S API version, as well as request parameters.
```

2024-11-26 17:31 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +to specify that both request and response parameters / error codes are the same as the I/S API version, rather than just parameters, apart from needing an I/S API token.
Are you sure about this, by the way? AFAICT synapse currently returns a bit of HTML here.

2024-11-26 17:33 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +to specify that both request and response parameters / error codes are the same as the I/S API version, rather than just parameters, apart from needing an I/S API token.
I don't think the sample impl (https://github.com/element-hq/synapse/pull/17625) actually changes the email submit-token endpoint.

2024-11-27 14:20 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +to specify that both request and response parameters / error codes are the same as the I/S API version, rather than just parameters, apart from needing an I/S API token.
So the deal here is that the POST endpoint isn't proxied by Synapse: it doesn't need to be as Sydent's email can just link straight to its own version of the GET endpoint. I've tried to clarify this in 63dcbe09.

2024-11-27 15:02 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +Note that the email `submitToken` endpoint ([`POST
it's a bit confusing that we jump from talking about an endpoint in the C-S API to one in the IS API without mentioning that.

Also, if you're talking specifically about the POST variant, you better say that, rather than saying that the entire endpoint is unused.

2024-11-27 15:05 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +to specify that response parameters and error codes are the same as the I/S API version, as well as request parameters.
why does this only apply to `POST /_matrix/client/v3/account/3pid/email/requestToken`, and not also:

* `POST /_matrix/client/v3/account/password/email/requestToken`
* `POST /_matrix/client/v3/account/password/msisdn/requestToken`
* `POST /_matrix/client/v3/register/email/requestToken`
* `POST /_matrix/client/v3/register/msisdn/requestToken`
* `POST /_matrix/client/v3/account/3pid/msisdn/requestToken`

?

2024-11-29 09:36 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +Note that the email `submitToken` endpoint ([`POST
Yes - sort of, I don't think there is a POST variant for email on the C/S API. Hopefully clearer in af1dc860.

2024-11-29 10:54 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +to specify that response parameters and error codes are the same as the I/S API version, as well as request parameters.
Mmm, yeah - I'd done it as only editing what I needed to, but you're right, they should be consistent. Changed in 0f43a510.

2024-11-29 11:35 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +Note that the email `submitToken` endpoint ([`POST
This is still confusing: we still jump from talking about an endpoint in the C-S API to one in the IS API without mentioning that.

2024-11-29 11:44 UTC, richvdh requested changes

2024-11-29 11:44 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +The numerous `requestToken` endpoints (enumerated in the proposal section) in the C/S API also specify a `submit_url`
this makes no sense

2024-11-29 11:44 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +Add the following specific error code as a code that can be returned by the two endpoints given above:
not least because there are now at least three different endpoints given above, I think you should restate which endpoints are changing here.

2024-11-29 11:44 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> + * [`POST /_matrix/client/v3/account/password/msisdn/requestToken`](https://spec.matrix.org/v1.11/client-server-api/#post_matrixclientv3accountpasswordmsisdnrequesttoken)
haven't checked this morning, but I'm pretty sure your synapse implementation PR doesn't change all of these.

(I don't think synapse returns a `submit_url` from the `email/requestToken` endpoints, but it does from the `msisdn/requestToken` endpoints, and you haven't updated all the implementations of those submit_url endpoints.)

2024-11-29 11:44 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +The numerous `requestToken` endpoints (enumerated in the proposal section) in the C/S API also specify a `submit_url`
nit: it would be nice if we could decide whether it's C-S API or C/S API, rather than using both in adjacent paragraphs

2024-11-29 11:44 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +Also apply the same change to all the `submit_url` fields in the various response to the `POST requestToken` endpoints, ie:
seems like you're only talking about the `POST requestToken` endpoints *in the C-S API*

```suggestion
Also apply the same change to all the `submit_url` fields in the various response to the `POST requestToken` endpoints in the client-server API, i.e.:
```

2024-11-29 11:56 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +Add the following specific error code as a code that can be returned by the two endpoints given above:
fixed

2024-11-29 13:11 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> + * [`POST /_matrix/client/v3/account/password/msisdn/requestToken`](https://spec.matrix.org/v1.11/client-server-api/#post_matrixclientv3accountpasswordmsisdnrequesttoken)
It actually does (so it's just as well we included the other endpoints): the various different rest classes use that function in the handler to do the request to the ID server and then the error code is in the exception that it throws.

2024-11-29 15:12 UTC, turt2live approved these changes
re-asserting approval as a read marker

2025-02-19 08:02 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> + * [`POST /_matrix/client/v3/account/password/msisdn/requestToken`](https://spec.matrix.org/v1.11/client-server-api/#post_matrixclientv3accountpasswordmsisdnrequesttoken)
Right, so it does. To be clear:

* Synapse does not return a `submit_url` from any of the `POST /_matrix/client/v3*/email/requestToken` endpoints.
* Synapse does not support `POST /_matrix/client/v3/account/3pid/msisdn/requestToken` (removed in https://github.com/matrix-org/synapse/pull/6101)
* Both `POST /_matrix/client/v3/register/msisdn/requestToken` and `POST /_matrix/client/v3/account/3pid/msisdn/requestToken` use `IdentityHandler.requestMsisdnToken`.

  `requestMsisdnToken` sets `submit_url` to `/_matrix/client/unstable/add_threepid/msisdn/submit_token` (yes, the register endpoint uses the `add_threepid` callback).

  And `/_matrix/client/unstable/add_threepid/msisdn/submit_token` is updated by https://github.com/element-hq/synapse/pull/17625.

2025-02-19 08:03 UTC, richvdh approved these changes
I am now finally up to speed, and other than a few minor editorial nits, this lgtm

2025-02-19 08:03 UTC, richvdh commented
@mscbot resolve lack of clarity about changes to requestToken

2025-02-19 10:20 UTC, dbkr commented on proposals/4183-submitToken-error-codes.md
> +proposal updates both for consistency.
Hopefully clearer

2025-02-24 18:25 UTC, merged

2025-12-19 10:31 UTC, zecakeh commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/2277

2026-01-13 18:28 UTC, richvdh commented on proposals/4183-submitToken-error-codes.md
> +proposal updates both `POST` and `GET` versions for consistency.
> This proposal updates both `POST` and `GET` versions for consistency.

No, it doesn't. The GET version returns an HTML page, not an error with an error code. This was clarified in the body of the MSC in https://github.com/matrix-org/matrix-spec-proposals/pull/4183/changes/9c12f64380306ba9771f54600ff2e4b66abe8bcf, but that change wasn't propagated to the introduction.

We should maybe make an errata PR to this MSC for posterity.

2026-01-16 18:50 UTC, turt2live commented
Merged 🎉

2026-02-19 19:37 UTC, NaixWintage-art reviewed
Widebang dose humain