MSC4186: Simplified Sliding Sync
matrix-org/matrix-doc pull request #4186
Opened 2024-08-30 08:31 UTC by erikjohnston

2024-08-30 12:18 UTC, Gnuxie commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
Are the options in the request and response supposed to be in a union with `null`?

Isn't it the convention in the spec that the property is omitted entirely rather than given the value `null`? 

(For clarity, this is something that jumps out at me since frequently people don't realise omitting a property and giving the value null are distinct things in JSON. Again, I'm not sure what the convention is for the CS-API though.)

2024-08-30 12:39 UTC, Gnuxie commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
Hmm, seems like `limited` is already optional in the timeline portion of sync? https://github.com/matrix-org/matrix-spec/blob/7f2f100420a355cf8ea50d08329e6f98989fc975/data/api/client-server/definitions/timeline_batch.yaml#L15-L36

But this does not imply a union with `null` (it's not explicit). It could if there is another section of the specification that says something to the effect "all optional properties in responses and requests should be treated as though they are in a union with `null`" somewhere.

2024-08-30 15:11 UTC, turt2live commented on proposals/4186-simplified-sliding-sync.md
Implementation requirements:

* [ ] Client (ideally multiple)
* [ ] Server

2024-08-30 15:44 UTC, Gnuxie commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
It might be better to rewrite this section using JSONSchema so that the intent is clearer in either case.

2024-08-30 15:58 UTC, Gnuxie commented on proposals/4186-simplified-sliding-sync.md
> +        "is_invite": true|false|null,
documentation is copied across from `is_encrypted`

2024-08-30 16:25 UTC, Gnuxie commented on proposals/4186-simplified-sliding-sync.md
> +`{"type": .., "state_key": .., content: null}` to indicate that the state entry has been removed.
This is pretty serious and I don't think you can leave it up to clients to figure out somehow. Since that requires client authors to both be extremely knowledgeable about how room state works and also write perfect code. The chances of both of those happening is slim. For example, I tried to write some code to track room state from legacy `/sync` (by also using `/state`) in Draupnir and it seems like I haven't even been able to do that right. https://github.com/Gnuxie/matrix-protection-suite/blob/main/src/StateTracking/StateChangeType.ts#L13-L64,  https://github.com/Gnuxie/matrix-protection-suite/blob/main/src/StateTracking/StateChangeType.ts#L83-L123.  This situation where a state event can be removed entirely isn't even accounted for.

2024-09-03 14:05 UTC, Johennes commented on proposals/4186-simplified-sliding-sync.md
> +- The server initially only sends the most recent N rooms to the client (where N is specified by the lcient), which then
```suggestion
- The server initially only sends the most recent N rooms to the client (where N is specified by the client), which then
```

2024-09-05 17:57 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "name": str|null,
It would be good to call out how all of these fields are optional if `initial: null` and they haven't changed

2024-09-05 18:05 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      ],
Do the `heroes` membership state events need to be included in `required_state` response when requesting `required_state: ["m.room.member", "$LAZY"]` (lazy-loading room members)?

Sync v2 says this:

> When lazy-loading room members is enabled, the membership events for the heroes MUST be included in the `state`, unless they are redundant. When the list of users changes, the server notifies the client by sending a fresh list of heroes. If there are no changes since the last sync, this field may be omitted.

But I think that's because `m.heroes` in Sync v2 is only a list of user ID's. Whereas, in the sliding sync response here, we already have all of the info necessary.

2024-09-05 18:09 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // The room name, if one exists. Only sent initially and when it changes.
Probably worth stating that this is strictly the value from the `m.room.name` event given the previous [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575) was previously trying to do a bunch of room name calculation stuff.

```suggestion
      // The room name (`m.room.name` -> `content.name`), if one exists. Only sent initially and when it changes.
```

2024-09-05 18:09 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "name": str|null,
I guess the comments already state this and I just read past them :white_check_mark: 

> The room name, if one exists. Only sent initially and when it changes.

2024-09-05 18:18 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
On initial sync or the first time the room is send down the connection (when the room indicates `initial: true`), this is the full set of state requested in `required_state`.

On incremental sync (when the room indicates `initial: null`), this will only be the state that has changed since the last time you synced (since the `pos` token in the request).

2024-09-05 18:21 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
We should call out that the `required_state`, `timeline`, `limited`, `num_live`, `prev_batch` fields will be omitted for `invite`/`knock` rooms. Only `invite_state`/`knock_state` is provided.

The reason these can't be included is because we don't have any of that information for remote invites and the user isn't participating in the room yet so we shouldn't leak anything to them. We can only rely on the information in the invite event.

Related previous conversation: https://github.com/matrix-org/matrix-spec-proposals/pull/3575#discussion_r1653045932

2024-09-05 18:31 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      ],
One weird corner with the current spec: If the room doesn't have a name set and the user is invited/knock to the room, we don't have any `heroes` to provide here. This is because `heroes` membership isn't included in the stripped state that the server receives when they are invited/knocked over federation.

Related to https://github.com/matrix-org/matrix-spec/issues/380

This was solved for partial-joins via [MSC3943](https://github.com/matrix-org/matrix-spec-proposals/pull/3943)

Not necessarily a blocker but just calling out something that won't work completely until that spec issue is solved.

2024-09-05 18:34 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
Thanks. I think this could be clearer.

2024-09-09 16:21 UTC, kegsay commented on proposals/4186-simplified-sliding-sync.md
> +- The client can maintain multiple sync loops (with some caveats)
Primarily for iOS which has 2 processes (a push process (NSE) and the main app process).

2024-09-11 20:07 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +limit, etc). The order of rooms is always done based on when the server received the most recent event for the room.
Yes, should [standardize this type of language](https://github.com/matrix-org/matrix-spec/issues/1334#issuecomment-2269948258).

```suggestion
limit, etc). The order of rooms is always done based on the arrival time of the most recent event for the room on the homeserver.
```

2024-09-19 13:12 UTC, deepbluev7 commented on proposals/4186-simplified-sliding-sync.md
> +        "is_invite": true|false|null,
How will knocks and left rooms be handled? Maybe this should be a string and be the current membership of the user?

2024-09-19 16:08 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
Clarify what `limited` means when complicating it with gaps, newly joined, newly joined a room where you can't see the history, etc

Sync v2 in Synapse is a bit crazy with the logic probably because the spec isn't clear.

The existing definition seems accurate "Indicates whether there are more events to fetch than those in the timeline." Could maybe clarify that you can be `limited` if there is timeline gap and you stop at the gap and say `limited: true` so the client paginates over the gap themselves. And maybe also need to say that being newly joined doesn't factor in.

2024-09-19 16:52 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
Clarify when to add `m.relations` in `unsigned` (`bundled_aggregation` logic).

Currently, it's done in Sync v2 and Sliding Sync when `limited: true` but @erikjohnston probably has the right inclination to not do it given that sync is returning new events and any relations to those events would come after it by their nature (and be in the response or the next one).

2024-09-19 19:27 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +response.
This should be expanded to explain what this means.

In terms of state:

 - `join`: Access to all of the room state.
 - `invite`/`knock`: Can only derive state from the stripped state events in the event itself (`invite_room_state`, `knock_room_state`)
 - `leave`/`ban`: Depends on the previous membership.
     - If the previous membership was `join`, access to the state at the time of the `leave`/`ban` (historical state)
     - If the previous membership was `invite`, fallback to the stripped state on the invite event
     - If the previous membership was `leave`/`ban`, repeat this logic
     - If no previous membership, no access to anything.
 
In terms of timeline events, this probably depends solely on `m.room.history_visibility`

2024-09-19 19:51 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
Clarify which rooms should be showing up.

We want to return every room where the user has membership except rooms that the user has left themselves; unless "newly left" (left since the last incremental sync `pos` token) because we want everything that's *still* relevant to the user. We include "newly left" rooms because the last event that the user should see is their own `leave` event.

A `leave` != kick (leave events where the sender is not the same user). Kicks should always be included.

To say it another way, here is a list:

 - `join`
 - `invite`
 - `knock`
 - `ban`
 - Kicks (`leave` where the `sender` doesn't match the `state_key`)
 - Newly left rooms (`leave` membership that happened since the last incremental sync `pos` token)

2024-09-19 20:56 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +    "!foo:example.com": {
*Re-adding [this discussion](https://github.com/matrix-org/matrix-spec-proposals/pull/3575#discussion_r1638988556) from the other MSC3575:*

What should happen if you try to subscribe to a room you are not part of (or not allowed)?

The easy option would be to ignore it but then clients have no feedback about what they did wrong.

Perhaps entries in the `rooms` map could also have an `errcode`/`error` field. We could also just blow up the whole request with an error and point out which `room_id` is wrong although that isn't very machine-readable.

---

Can you subscribe to a public `world_readable` room that you're not part of?

2024-09-20 00:10 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
Should you only include `ban` if there is a previous `join`, `invite`, or `knock`? :) (Maybe scope creep.)

2024-09-20 03:07 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
I also had that in mind but I'm not sure (could go either way). It's kinda the same as an unsolicited invite (optionally followed by a kick/`ban`).

Ideally, we probably wouldn't show those kind of `ban`

2024-09-20 18:49 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
@erikjohnston unearthed some more context in [MSC2675](https://github.com/matrix-org/matrix-spec-proposals/pull/2675) and relevant [Synapse PR](https://github.com/matrix-org/synapse/pull/11478)

2024-09-24 10:20 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +We may want to allow special entries in the `required_state` list of the form
Surely this isn't a nice-to-have but a requirement, otherwise we end up back in https://github.com/matrix-org/matrix-spec/issues/1209

2024-09-25 08:14 UTC, Hywan commented on proposals/4186-simplified-sliding-sync.md
> +      "joined_count": 1,
Should be precised that `joined_count` is given only if the room has been joined. For invite room, this value will be missing.

2024-09-25 12:30 UTC, Hywan commented on proposals/4186-simplified-sliding-sync.md
> +      "timeline_limit": 10,
MSC3575 (at least its implementation inside the sliding sync proxy) allowed `timeline_limit` to be null. This is NOT the case with MSC4186 (as implemented inside Synapse). I believe the MSC should clarify this value is required.

2024-10-01 14:17 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +purposes).
I'll make this clearer, but the idea is that 100 rooms are in scope due to `[0, 99]`, but we've already sent down the first 20 rooms and so they aren't sent down again

2024-10-16 15:03 UTC, jmartinesp commented
I've made a suggestion [in Synapse](https://github.com/element-hq/synapse/issues/17838) to implement a `membership` field for Room objects. This would simplify the logic for the clients a lot, avoiding checks and assumptions, and make sure they'll have consistent behaviours since it'll be the server who explicitly sets this value.

2024-10-17 06:53 UTC, jmartinesp commented on proposals/4186-simplified-sliding-sync.md
> +      "knock_state": [ .. ],
As mentioned [in a comment below](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#issuecomment-2417104725) it would be super useful to have a separate field indicating the user's membership state in a room instead of relying on some rules around `required_state` and `invite_state` and finding the membership event in the client-side.

Also note the current simplified sliding sync version implementation in Synapse uses a single `invite_state` array instead of separate ones for invite and knock. I think it was discussed to rename it to `stripped_state` or something along the lines?

2024-11-02 14:02 UTC, HarHarLinks commented on proposals/4186-simplified-sliding-sync.md
> +The unstable URL for simplified sliding sync is `/org.matrix.simplified_msc3575/sync`. The flag in `/versions` is
```suggestion
The unstable URL for simplified sliding sync is `/_matrix/client/unstable/org.matrix.simplified_msc3575/sync`. The flag in `/_matrix/client/versions` is
```

2024-11-02 14:18 UTC, HarHarLinks commented on proposals/4186-simplified-sliding-sync.md
> +## Request format
which of these are required and which optional?

2024-11-19 21:09 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
Clarify that `$LAZY` loading room members should also include any changed membership events in incremental syncs that are `limited: false` (regardless of whether the people are in the timeline).

Reference: https://github.com/element-hq/synapse/issues/17929

2024-11-27 10:03 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
Current implementations to my knowledge:

* Client implementation: [matrix-rust-sdk](https://github.com/matrix-org/matrix-rust-sdk/) ([PR](https://github.com/matrix-org/matrix-rust-sdk/pull/3676))
* Server implementation: has been implemented in [Synapse](https://github.com/element-hq/synapse/) across 10s of PRs. (Perhaps @MadLittleMods, the implementer, can give better link(s) here.)

2024-11-27 17:58 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
#### Synapse server implementation


Maybe it's easiest to point to the main directories where the code lives:

 - [`element-hq/synapse` -> `synapse/rest/client/sync.py#L782`](https://github.com/element-hq/synapse/blob/59ad4b18fc81f373c57a7c7d09a2f340a129de76/synapse/rest/client/sync.py#L782)
 - [`element-hq/synapse` -> `synapse/handlers/sliding_sync/`](https://github.com/element-hq/synapse/tree/59ad4b18fc81f373c57a7c7d09a2f340a129de76/synapse/handlers/sliding_sync)
  - [`element-hq/synapse` -> `tests/rest/client/sliding_sync/`](https://github.com/element-hq/synapse/tree/59ad4b18fc81f373c57a7c7d09a2f340a129de76/tests/rest/client/sliding_sync)

The PRs between @MadLittleMods and @erikjohnston with the ~A-Sync label are also a pretty good encapsulation:

 - https://github.com/element-hq/synapse/pulls?q=+is%3Apr+author%3AMadLittleMods+label%3AA-Sync
 - https://github.com/element-hq/synapse/pulls?q=+is%3Apr+author%3Aerikjohnston+label%3AA-Sync

2024-11-28 18:43 UTC, turt2live commented on proposals/4186-simplified-sliding-sync.md
> +      "knock_state": [ .. ],
There should also be a `knock_servers` field, copying https://github.com/matrix-org/matrix-spec-proposals/pull/4233

2024-11-30 03:40 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // event _except_ for @alice:example.com, and include every other state event.
This behavior comes from the prior art in [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575).

Proposed alternative in https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1742194906 which is a lot more straight-forward :+1:

2024-12-16 23:43 UTC, olivia-fl commented on proposals/4186-simplified-sliding-sync.md
> +offline, and clients cannot opt-out of a large amount of extraneous data such as receipts. On large accounts with
Specifically, I believe you can opt-out of receipts with `RoomFilter.ephemeral.not_types = [ "m.read.*" ]` or similar. When I was working on filtering support in grapevine, we had a fast path for filters like this that would skip reading any of the receipt data from the db server-side. That work hasn't been finished yet, and I have no idea if synapse has a similar fast-path.

One of the difficulties with v3 sync filtering in general is that performance can vary wildly wildly depending on server implementation details. The spec doesn't indicate which fast-paths should exist, and whether or not you hit a fast-path can also affect how many events are returned in the sync window (https://github.com/matrix-org/matrix-spec/issues/1887).

2024-12-16 23:55 UTC, olivia-fl commented on proposals/4186-simplified-sliding-sync.md
> +## Extensions
My understanding is that this MSC doesn't have any support for timeline filtering. The SS MSC [called this out explicitly](https://github.com/matrix-org/matrix-spec-proposals/pull/3575/files#diff-1f7276cbbee4eeaaca06b07d2fe58312eab735259f2490e28e04710dde77fdccR1188), and it would probably be good to do that here as well. Timeline filtering on /v3/sync is used heavily by some bot and tool clients.

2024-12-16 23:55 UTC, olivia-fl commented on proposals/4186-simplified-sliding-sync.md
> +# Proposal
How does SSS interact with the ignored user list? In /v3/sync, the server omits events sent by ignored users, requiring the client to perform a second initial sync if they want to retroactively see messages when unignoring. The choice to do server-side ignored user filtering in sync also doesn't really simplify client implementation, because you still need client-side filtering for events received before the user was ignored.

My preference would be to drop this requirement entirely for SSS, now that we have a chance to do it in a backwards-compatible way.

2025-01-08 14:42 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +- Time from login on existing accounts to usability should be as low as possible.
Yes, difference between opening the app when already logged in vs logging in. Will clarify

2025-01-08 15:19 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +purposes).
Will add a note

2025-01-24 20:53 UTC, morguldir commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
If they want to go with sticky params then null makes sense as a value, since clients will then leave it out on subsequent requests, and then the only way to unstick it is by explicitly sending null

2025-01-24 20:59 UTC, morguldir commented on proposals/4186-simplified-sliding-sync.md
> +algorithm.
https://github.com/element-hq/synapse/blob/9c5d08fff8d66a7cc0e2ecfeeb783f933a778c2f/synapse/rest/client/sync.py#L951-L955

Sticky lists can replace them yes, but I don't think that's been decided yet

2025-01-24 21:05 UTC, morguldir commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
That seems like a good idea, i've heard concerns of preemptive bans notifying the banned target that the room exists

2025-02-06 14:41 UTC, Gnuxie commented on proposals/4186-simplified-sliding-sync.md
> +      // In addition, ["*", "*"], ["m.space.child", "*"] is an error, the m.space.child filter is not
Wait what? So it's not possible to filter out all events from one type without giving a state key? e.g. `[["*", "*"], ["m.room.member", "*"]]`couldn't be used filter out all membership events?

2025-02-13 15:01 UTC, dbkr commented on proposals/4186-simplified-sliding-sync.md
> +may sort the rooms differently than they are returned by the server (e.g. they may ignore reactions for sorting
Was one of these 'server's meant to be 'client'?

2025-02-17 18:57 UTC, Johennes commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
How will [forgotten](https://spec.matrix.org/v1.13/client-server-api/#post_matrixclientv3roomsroomidforget) rooms be dealt with here? The old `/sync` doesn't seem to have a way to synchronize forgotten rooms across clients. It'd be nice if SSS could address this.

2025-02-20 11:58 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +        {"user_id":"@alice:example.com","displayname":"Alice","avatar_url":"mxc://..."},
could you define the datatype for `heroes` a bit more explicitly? which fields are required, which optional?

2025-02-21 08:59 UTC, Hywan commented on proposals/4186-simplified-sliding-sync.md
> +        {"user_id":"@alice:example.com","displayname":"Alice","avatar_url":"mxc://..."},
for the record, the `user_id` is mandatory, all other fields are optional ([see the type in Ruma](https://docs.rs/ruma/latest/ruma/api/client/sync/sync_events/v5/response/struct.Hero.html))

2025-02-21 10:13 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +        {"user_id":"@alice:example.com","displayname":"Alice","avatar_url":"mxc://..."},
That seems sensible to me, though I'm not sure that Ruma is authoritative here!

2025-02-24 09:59 UTC, Hywan commented on proposals/4186-simplified-sliding-sync.md
> +        {"user_id":"@alice:example.com","displayname":"Alice","avatar_url":"mxc://..."},
Absolutely not, but it matches the implementation inside Synapse at least ^^

2025-03-12 12:02 UTC, Hywan commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
The spec should tell that all `required_states` from all lists and from all room subscriptions are unioned.

cc @erikjohnston
reference in Synapse: https://github.com/element-hq/synapse/blob/caa2012154899688237b2b48fb2c02d78d2fff41/synapse/types/handlers/sliding_sync.py#L506

2025-03-12 12:02 UTC, Hywan commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
Same as https://github.com/matrix-org/matrix-spec-proposals/pull/4186/files#r1991345065.

2025-03-22 22:49 UTC, Xiretza commented on proposals/4186-simplified-sliding-sync.md
> +In particular, a client must use the returned `pos` value in a response as the `since` param in exactly one request that
What is "the `since` param"? MSC3575 uses a [`pos` query parameter](https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/sync-v3/proposals/3575-sync.md#core), not `since`; this MSC does not define it as part of any API at all.

2025-04-01 08:27 UTC, Half-Shot commented on proposals/4186-simplified-sliding-sync.md
> +
It's not clear here whether this endpoint updates presence in the same way sync v3 does. Currently this is relied upon for accurate presence display, but clients using this mechanism won't be sending presence which is going to cause a bit of a split.

I feel like this was just omitted by accident, can we update the proposal?

2025-04-04 19:10 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "highlight_count": 1,
Should unread and highlight count even be here? Notification/highlight count can't even be done correctly for encrypted rooms and it's just extra work for us to calculate if clients ignore our flawed values anyway.

2025-04-07 09:48 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
In implementations we have `pos` as a query param, same as sync v2 (and v3 proposals). We might want to allow this to be in the request body, which would allow web clients to cache the preflight requests.

Currently, since `pos` changes for every request, every time the client does a sync request the browser will send a preflight request (as different query params mean that the browser consider it different resources). This means that we can't cache the preflight requests (via `Access-Control-Max-Age`)

2025-05-15 14:26 UTC, kegsay commented on proposals/4186-simplified-sliding-sync.md
> +      "highlight_count": 1,
But they can be done in unencrypted rooms so would save a bunch of processing time?

2025-05-15 14:27 UTC, kegsay commented on proposals/4186-simplified-sliding-sync.md
> +      "highlight_count": 1,
Yes

2025-05-23 00:59 UTC, dead-claudia commented
Has SSE support been considered? In [this comment elsewhere](https://github.com/matrix-org/matrix-spec-proposals/issues/3798#issuecomment-2902864408), I noted that bandwidth can be further reduced through stateful compression. And just having a persistent connection in general reduces load on the server, as 1. the server no longer has to parse HTTP header data after every message broadcast and 2. servers can avoid issuing additional database requests without having to rely on caching.

Persistent connections are particularly useful for networks with very high bandwidth-delay products, like satellite and mobile internet. Satellite in particular suffers a lot from delay: it takes a full quarter second for light just to go from surface to geostationary orbit, and you need two of those to communicate with a different terrestrial server, for a minimum of half a second one-way latency. And in practice, geosync satellite internet one-way latency can be as much as a full second due to older hardware (one doesn't just replace a satellite or a connected base station). Mobile internet sees typical latencies of half to 2/3 that, mostly due to various sources of interference. For a response-to-request cycle, you need two of those hops: one for response receipt and one for request receipt. Being able to just send events right away halves that delay.

2025-05-23 14:58 UTC, MadLittleMods commented
@dead-claudia Comment on the diff to thread the discussion. Explain/link to what SSE is.

2025-05-23 15:51 UTC, reivilibre commented on proposals/4186-simplified-sliding-sync.md
> +      // An opaque integer that can be used to sort the rooms by "Bump Stamp"
This appears to be the only place in the document where the 'bump stamp' is mentioned. A definition would be beneficial.

There should at a minimum be an explanation of the semantics of this integer and its ordering.

as a nit: I'm not convinced it makes sense to call it 'opaque' on one hand and then claim it can be used for sorting on the other. I'd typically say something is 'opaque' if you never have to inspect its actual value, but for sorting this seems to be by definition not the case.

2025-05-23 15:52 UTC, reivilibre commented on proposals/4186-simplified-sliding-sync.md
> +      // An opaque integer that can be used to sort the rooms by "Bump Stamp"
u64 would be a problem, or at least an inconvenience, for JavaScript clients. Should this be an unsigned 53-bit integer instead?

2025-05-23 19:36 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +sent down in the first request, or b) have updates since the first request.
We should also clarify that the rooms in the lists are sorted by the latest event in the room (`stream_ordering` in Synapse). This way clients receive all new events.

The `bump_stamp` (`stream_ordering` of certain bump event types) is simply for the client's convenience and doesn't affect the server-side sorting.

2025-05-23 21:40 UTC, dead-claudia commented on proposals/4186-simplified-sliding-sync.md
> +the API supplying the token returned in the previous response in the subsequent “incremental” request.
Have you considered using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format) to expose this instead?

- An option (like `"persist": false` or similar) could be accepted to tell the server to only send the initial sync, for the few clients who don't want to watch for more events.
- Clients don't need multiple sync loops, just multiple persistent connections they're watching.
- Event IDs and restarting is built into the protocol. You don't need to design for it yourself. And you also don't need to store the event IDs any longer than it takes to send them.
- The streaming nature of the protocol makes it naturally adaptive to client bandwidth. If necessary, the server can handle database pagination.
- [Response compression can drive down bandwidth significantly for messages, provided you flush the stream after sending each batch of messages.](https://github.com/matrix-org/matrix-spec-proposals/issues/3798#issuecomment-2902864408)
- Fewer requests means much less compute load on the server. And HTTP state can be discarded after receiving the full request. This lets it support more connections. And given filters can get quite large, this is significant.
- Database requests need to occur only for initial sync. Once the initial sync occurs, all subsequent events can just be directly broadcast via message passing, reducing database load and especially cache load.
- High-latency networks like geosync satellite (500ms-800ms one-way) would see message receipt latency cut in half by not having to send a request to receive subsequent events. Note that geosync satellite physically can't get below about 500ms of latency due to the speed of light.

You can still use `POST` for the request, since while native browser APIs don't support it, [userland libraries do](https://www.npmjs.com/package/@microsoft/fetch-event-source).

2025-05-27 11:34 UTC, reivilibre commented on proposals/4186-simplified-sliding-sync.md
> +      // An opaque integer that can be used to sort the rooms by "Bump Stamp"
> I think it's just described as "opaque" to mean it should not be interpreted to derive some other info like if someone were to use a timestamp (simply a number to compare against other numbers). You can see the word "opaque" being thrown around in https://github.com/element-hq/synapse/pull/17395#discussion_r1666662697.

probably would be good to just say as much in clear words (I still think the word 'opaque' is a little abused here) — e.g. 'The bump stamp can be used to order rooms by their latest bumpable* activity, but the bump stamp has no other semantic meaning and must not be interpreted by the client for any purpose other than sorting.'

2025-05-30 15:03 UTC, Xiretza commented on proposals/4186-simplified-sliding-sync.md
> +The format of returned state in `required_state` is a list of events. This does now allow the server to indicate if a
```suggestion
The format of returned state in `required_state` is a list of events. This does not allow the server to indicate if a
```

2025-05-30 15:03 UTC, Xiretza commented on proposals/4186-simplified-sliding-sync.md
> +"state reset" has happened which removed an entry from the state entirely (rather than it being replaced with another
Isn't one option to send a room back with `initial: true` when the server detects a state reset? This forces the client to discard any state events it has previously received.

2025-07-15 15:56 UTC, reivilibre commented on proposals/4186-simplified-sliding-sync.md
> +client in a dedicated extensions block.
how should a client be aware of whether a given extension is supported by the server or not?

It seems Synapse currently omits extensions in the response object, if there is no new data for that extension.

But this makes it impossible for a client to distinguish between no data and an unsupported extension.

2025-08-26 04:28 UTC, jevolk commented
This MSC is due for FCP and should be finalized without further delay. The following justifications apply:

1. The total time for this project and its predecessor is approaching **four years** which will be nearly one third of Matrix's entire existence.
2. It is the second evolution of the concept incorporating corrections; refining from experience with the first and no longer purely exploratory.
3. It is widely implemented with support in the notable servers, major language SDKs and popular clients. It may even be difficult to make substantive changes to the proposal at this point without significant disruption.
4. It only voluntarily deprecates legacy sync which remains specified and otherwise implemented as a cushion, rather than forcing any immediate obsolescence.
6. **It is the sole method used by mobile clients like Element X** due to matrix-rust-sdk not providing any fallback to legacy sync in its Kotlin bindings (et al). **This already forces its implementation in existing production systems.**

This MSC is already widely deployed in the production systems of business and government customers. Its status is approaching that of a de facto standard.

The actual Matrix specification _must_ remain relevant, lest it become a set of open XEP's for everyone to pick and choose from. That's not what anybody wants to see.

2025-08-26 04:38 UTC, foresto commented
> This MSC is due for FCP and should be finalized without further delay.

What would be the point of a comment period on a spec that gets finalized without addressing the comments?

2025-09-07 01:26 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +  "conn_id":  "<conn_id>",  // Client chosen ID of the connection, c.f. "Connections"
[MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575/files#diff-1f7276cbbee4eeaaca06b07d2fe58312eab735259f2490e28e04710dde77fdccR69) limits the `conn_id` to 16 chars. Does that restriction still apply? If the omission was intentional it should be noted. As a preference I favor the limitation, or at least some limitation, or simply using an integer for this.

2025-09-07 01:44 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +- Presence \- presence in sync v2: spec
There is currently no re-specification of the [Presence Ping](https://spec.matrix.org/v1.15/client-server-api/#get_matrixclientv3sync) functionality in this MSC. I suppose there could be an argument for encapsulating any such flag within the related extension, but as of right now the server does not refresh presence for these clients. This issue affects remote user UX; not limited to those implementing this MSC with the understanding of its current status.

2025-09-09 09:54 UTC, erikjohnston commented
I've reworked the MSC (fairly substantially) to a) include full API schemas, and b) clarify exact behaviour.

Currently, this MSC describes the Synapse implementation. I wanted to start from there so its easier to track any changes we make going forwards.

2025-09-12 09:14 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
Mmm, though the parameter is called `pos` in the API.

2025-09-12 09:16 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +      "highlight_count": 1,
This should be in the threads extension.

2025-09-12 09:38 UTC, erikjohnston commented
I've made a bunch of minor breaking changes, see the changelog at the bottom of hte MSC. I have tried to address most of the open comments in them.

2025-09-12 09:40 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
I think this question is the big remaining thing we should sort out, i.e. how do we make it so that clients don't need to send the full request body each time?

I think perhaps the simplest answer is to allow `lists` to be omitted on incremental syncs to indicate that no changes have been made to the `lists`

2025-09-12 16:13 UTC, foresto commented on proposals/4186-simplified-sliding-sync.md
> +| `is_encrypted` | `[string]` | No | Flag which only returns rooms which have an `m.room.encryption` state event. <br/><br/> If unset, both encrypted and unencrypted rooms are returned. If `False`, o
Shouldn't `is_encrypted` be a `bool`, rather than `[string]`?

2025-09-12 16:17 UTC, foresto commented on proposals/4186-simplified-sliding-sync.md
> +| `is_invite` | `bool` | No | Flag which only returns rooms the user is currently invited to. <br/><br/> If unset, both invited and joined rooms are returned. If `False`, no invited rooms are returne
I think this field should be named `is_invited`. Calling it `is_invite` implies that the room is (or is not) an invitation, which is confusing.

2025-09-12 16:29 UTC, foresto commented on proposals/4186-simplified-sliding-sync.md
> +| `is_invite` | `bool` | No | Flag which only returns rooms the user is currently invited to. <br/><br/> If unset, both invited and joined rooms are returned. If `False`, no invited rooms are returne
Maybe calling it `am_invited` or just `invited` would be even better, since we're talking about the user's relationship to the room rather than an attribute of the room itself.

2025-09-14 16:44 UTC, dead-claudia commented on proposals/4186-simplified-sliding-sync.md
> +the API supplying the token returned in the previous response in the subsequent “incremental” request.
I plan to follow up with this in a later proposal, to not block this MSC (as it's already de-facto standard).

2025-09-15 15:32 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `pos` | `string` | Yes | The next position token in the sliding window to request. |
We should document/consider `pos` token compatibility with other endpoints.

Currently, Synapse uses a [similar but incompatible token](https://github.com/element-hq/synapse/blob/769d30a247926dd90d9afe7f6afd65bdc605d465/synapse/types/__init__.py#L1287-L1301) format for Sliding Sync compared to any other endpoint. If compatibility is desired, we can always still work with this format and accept it on other endpoints and strip off the extra field.

### Motivating use case

@bnjbvr brings up an interesting use case: When the `timeline` is `limited`, it would be nice to have the option to query `/messages?dir=b&from=<prev_batch>&to=<pos>` for seamless pagination and avoid needing any deduplication heuristics/logic on the client.

Similarly, [MSC4308](https://github.com/matrix-org/matrix-spec-proposals/pull/4308) already proposes that the `pos` token should be compatible with the `/thread_subscriptions` endpoint being proposed there for the same reason.

2025-09-16 13:49 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
Maybe we should spell it out there too? 😄  See thread @ https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1742221179 though.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
This doesn't seem to match the goals above:

> If a since token has been discarded we should gracefully degrade to initial sync.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +`conn_id` set in the request.
A small quibble: it is confusing to use "connection" here when it doesn't refer to an HTTP connection. It would probably be more confusing to use "sync loop" everywhere though, so I don't have a better idea.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +This MSC specifies two types of rule: a "list" and a "subscription".
```suggestion
This MSC specifies two types of rules: a "list" and a "subscription".
```

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +`[0,19]`, which would cause the server to return the top 20 rooms (by activity).
~~What's the use-case / rationale for not just a limit of 20?~~

This is explained a bit below, but seems like it could fit better in this section.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
Just to double check -- this treats all events the same?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +client always wants to get the latest data for that room.
```suggestion
Subscriptions are a rule that matches against a specified room ID, i.e. they allow the client to specify that a
given room should always be returned (if there are updates). This is useful if e.g. the user has opened the room and the
client always wants to get the latest data for that room.
```

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently does not support subscribing to rooms that the user is not part of.
⚠️ This is missing an implementation. ⚠️

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +number of events to return in the timeline section of a room, and the "required state" specifies what state to return.
This would be clearer directly under the "Lists and subscriptions", right now it is confusing to know what this applies to.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +## Room results
Is there any new information in this section? Maybe the last paragraph-only?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +  config it is returned by the combined room config.
```suggestion
- Required state — take the union of the required state fields, i.e. if a state event would be returned by any room
  config it is returned by the combined room config.
```

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently does not return rooms with expanded state immediately, instead waits for the next update.
⚠️ No implementation for this. ⚠️

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +Examples of extensions, which will be specified elsewhere, are:
```suggestion
Examples of extensions, which will be specified in future MSCs, are:
```

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). Max lists: 100. The list keys should be arbitrary strings which the client
bytes or characters?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `ranges` | `[[int, int]]` | No | Sliding window ranges. If this field is missing, no sliding window is used and all rooms are returned in this list. Integers are *inclusive*. (This is a list of 2-t
This should note this is 0-indexed.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +      "ranges": [[0, 10]],
@erikjohnston This is still waiting a response.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `filters` | `RoomFilter` | No | Filters to apply to the list before sorting. |
Is this `RoomFilter` from the current spec? Answer is no, this is defined much further below.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `include` | `[RequiredStateElement]` | Yes | The set of state to return (unless filtered out by `exclude`). |
`include` is required, but I assume it can be empty? Why have it required then?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `type` | `string` | No | The event type to match. If omitted then matches all types. |
Is it useful to match all types? `{"state_key": "foo"}` seems like a weird thing to filter on?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +retrieve all state events except for m.room.member events which you want to lazily load. To get this behaviour, clients
```suggestion
retrieve all state events except for `m.room.member` events which you want to lazily load. To get this behaviour, clients
```

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +events for:
Link to v2?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `is_encrypted` | `[string]` | No | Flag which only returns rooms which have an `m.room.encryption` state event. <br/><br/> If unset, both encrypted and unencrypted rooms are returned. If `False`, o
```suggestion
| `is_encrypted` | `bool` | No | Flag which only returns rooms which have an `m.room.encryption` state event. <br/><br/> If unset, both encrypted and unencrypted rooms are returned. If `False`, only unencrypted rooms are returned. If `True`, only encrypted rooms are returned. |
```

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
How are multiple terms handled?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `not_tags` | `[string]` | No | Filter the room based on its room tags.<br/><br/> Takes priority over `tags`. For example, a room with tags A and B with filters `tags: [A]` `not_tags: [B]` would NOT
I assume this refers to https://spec.matrix.org/v1.15/client-server-api/#room-tagging? Can we add a link?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +All fields in this section may be omitted. When `initial` is set to `false` then an omitted filed means that the field
```suggestion
All fields in this section may be omitted. When `initial` is set to `false` then an omitted field means that the field
```

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `count` | `int` | Yes | The total number of entries in the list. |
I assume this is an object for future extensibility?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
I still find the `bump_stamp` name to be incoherent. I don't have a good feel for what a client would use it for.

I don't think `m.poll.start` or `m.beacon_info` is in the spec yet?

Should room upgrades be in here? Were other events considered and rejected?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
⚠️ Notifications have no implementation. ⚠️

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `is_dm` | `bool` | No | Flag to specify whether the room is a direct-message room (according to account data). |
If this is not included does that mean we don't know or it is not?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `num_live` | `int` | No | The number of timeline events which have just occurred and are not historical. The last `N` events are 'live' and should be treated as such.<br/><br/> This is mostly usefu
What does "just occurred" mean?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `invited_count` | `int` | No |  The number of users with membership of invite. (same as sync v2 `m.invited_member_count`) |
I'm surprised there's no `knocked_count`, but looks like v2 doesn't have it either.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `highlight_count` | `int` | No | The number of unread notifications for this room with the highlight flag set. (same as sync v2) |
But not including the threaded versions?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +For rooms the user is invited to or has knocked on, the client also gets the stripped state event:
```suggestion
For rooms the user is invited to or has knocked on, the client also gets the stripped state events:
```

Does this change with MSC4311?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently may inadvertently return extra fields from the previous section.
Is this true after MSC4311?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Knock support hasn't been implemented in Synapse.
⚠️ More unimplemented bits. ⚠️

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +previous request.
This doesn't match above where it says the `top 100` rooms would be sent down.

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
This sounds a lot simpler. Why do clients want to backfill multiple rooms at once?

Would adding a flag to `/mesages` to *not* backfill be useful?

2025-09-16 16:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +# Security considerations
Are there are potential resource exhaustion attacks a client can perform? Lots of connections or something else? Are there no other security concerns? This is a pretty large API.

2025-09-16 19:36 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
@clokep I found [a test for this](https://github.com/matrix-org/matrix-rust-sdk/blob/681863423c56a6a10c03747c1dce1520751037b8/testing/matrix-sdk-integration-testing/src/tests/sliding_sync/room.rs#L398) in the matrix-rust-sdk, leading me to believe it's implemented now. It's difficult for me to navigate Synapse due to complexity-wise and things. Should we call this a wrap 😇

2025-09-16 20:26 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
No, if it is implemented then the text should be removed from here.

2025-09-19 16:38 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // An opaque integer that can be used to sort the rooms by "Bump Stamp"
Also see https://github.com/matrix-org/matrix-spec-proposals/pull/4308 for similar conversations ironing out what exactly `bump_stamp` means

2025-09-22 13:33 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
How this works in practice is that the client will see `M_UNKNOWN_POS`, clear any relevant data, and retry without a `pos` parameter.

The main advantage in doing it likes this is that it ensures that clients understand what has happened and has invalidated any caches it needs to. For example, it should clear the old rooms out of the room list so that users can tell that its out of date (i.e. after the first initial sync the room list would only contain the top 20 rooms while it goes and fetches more in the background).

The most obvious disadvantage is the wasted round-trip, which is potentially significant on high-latency connections. Though we do expect it to be relatively rare for a server to return a `M_UNKNOWN_POS` so this hopefully shouldn't matter much in practice.

The alternative is to annotate the responses to indicate that the `pos` was ignored. We already do have some capability of doing so by e.g. annotating `room` responses with `initial: true`. The main concern is that there is potentially a lot of subtlety to making it all work correctly, especially with lists and extensions.

2025-09-22 13:35 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +`conn_id` set in the request.
Mmm, true. I'd use session but that is already overloaded.

2025-09-22 13:37 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +## Room results
I think its useful to tie it all together in one place maybe? Rather than having to bounce around to figure out what is included.

2025-09-22 13:43 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). Max lists: 100. The list keys should be arbitrary strings which the client
Bytes, I don't think it makes sense to limit based on code points or graphemes?

2025-09-22 13:45 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `type` | `string` | No | The event type to match. If omitted then matches all types. |
I think we currently support it. I think the only time you'd ever want it is if you were looking for all state events with your own user ID as a state key, but I don't think we have a proper use case for it.

2025-09-22 13:46 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
What do you mean by multiple terms? As in for multiple keywords in `room_name_like`?

2025-09-22 13:47 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `count` | `int` | Yes | The total number of entries in the list. |
It used to have more stuff in it, but yes I think we probably do want to keep it for extensibility.

2025-09-22 13:51 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
I am fairly sure that Synapse always returns 0 here:

https://github.com/element-hq/synapse/blob/d80f515622a678289aad7068751a26c6bb256dcd/synapse/handlers/sliding_sync/__init__.py#L1368-L1369

I think the rust SDK calculates things client side?

2025-09-22 13:53 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +previous request.
I'm afraid I don't follow. Where does it say that? The way it works is that the lists match the top 100 rooms, but that doesn't mean all 100 rooms are returned in that sync if they have been previously sent down and there have been no changes?

2025-09-22 13:57 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
I think this is a UX perf thing: when a user opens the app they will *likely* click one of the top 10 or 20 rooms and so having those 10 or 20 rooms have pre-fetched history as quickly as possible reduces the number of times that a user will see a blank room when opened.

It's hard for e.g. web to do multiple concurrent `/messages` requests due to max in-flight request limits. Though certainly adding a flag to `/messages` to make it return quicker would help a bunch (and I think is being proposed in an MSC somewhere already)

2025-09-23 09:27 UTC, bnjbvr commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
Indeed, because of e2ee rooms the SDK will calculate the unread counts client-side at the moment (to be fair, it's rather computing an unread state boolean at the moment, rather than a precise count, but precise counts are being worked on at this very moment).

2025-09-23 18:11 UTC, foresto commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
> precise counts are being worked on at this very moment

Are you referring to #2654? (That would be good news, since computing unread state based on read markers and notifications is somewhat unreliable in practice and an annoying source of complexity in my client code.)

2025-09-24 08:20 UTC, bnjbvr commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
No, I was indeed referring to work being on the Rust SDK, sorry. It's a discussion for another place and another time, but I think that clients are _bound_ to computing unread counts locally, because of e2ee rooms (and because users might have different expectations of what an "interesting" unread event is: member event? edit event? etc.).

2025-09-24 11:36 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +`conn_id` set in the request.
Yeah, I don't have a good suggestion unfortunately.

2025-09-24 11:39 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
Yeah, is that possible? Is it implementation specific or just not supported.

2025-09-24 11:40 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
I understand why synapse returns 0 and why Element X doesn't care, but the MSC needs an update then. Unresolving.

2025-09-24 11:45 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +previous request.
Above it says:

> may change the range to `[0,99]`, at which point the server will respond with the top 100 rooms that either a) weren’t sent down in the first request, or b) have updates since the first request.

That sounds like it will always return 100 rooms, some might duplicate the first request (if they have updates), while others might be new.

It sounds completely at odds with the description here.

Maybe some diagrams would help!?

2025-09-24 11:55 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +previous request.
How about:

> may change the range to `[0,99]`, at which point the server will look at the top 100 rooms and respond with those that either a) weren’t sent down in the first request, or b) have updates since the first request.

A practical example: we have two rooms `R1` and `R2`, with `R1` have the most recent event:

1. Client requests `[0,0]`. The server fetches the top 1 room, `R1` and notes it hasn't sent it down before. The server therefore responds with `R1`.
2. Client next requests `[0, 1]`. The server fetches the top 2 rooms, `R1` and `R2`, and notes it has sent down `R1` before but not `R2`. It responds with `R2` only.
3. An event happens in `R1`.
4. Client next requests `[0, 1]`. The server fetches the top 2 rooms, `R1` and `R2`, and notes it has sent down both rooms before but that `R1` has an update. The server responds with `R1` only.

2025-09-24 13:14 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
Yup!

2025-09-24 13:16 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `filters` | `RoomFilter` | No | Filters to apply to the list before sorting. |
Have renamed to make clearer

2025-09-24 13:19 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `include` | `[RequiredStateElement]` | Yes | The set of state to return (unless filtered out by `exclude`). |
Fair, I think I was assuming that it wouldn't make sense for it to be empty but that's not true.

2025-09-24 13:21 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
Mmm, I guess we could say that it is implementation defined? Much like we do for search?

2025-09-24 13:30 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `is_dm` | `bool` | No | Flag to specify whether the room is a direct-message room (according to account data). |
Hmm, in Synapse its only included if its set to `true`. Which makes sense, except it doesn't capture if it changes during a sync connection. My gut is that we leave it as is and require clients to look at account data to see the changes? Not entirely sure what is the right thing to do

2025-09-24 13:32 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `num_live` | `int` | No | The number of timeline events which have just occurred and are not historical. The last `N` events are 'live' and should be treated as such.<br/><br/> This is mostly usefu
Have added:

> ..., i.e. that have happened since the previous sync request

2025-09-24 13:34 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently may inadvertently return extra fields from the previous section.
Yeah, its not so much about that sort of MSC but more about the fact that we sometimes included other bits of state in that section in Synapse.

2025-09-24 13:42 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +# Security considerations
Have added a not about limiting number of connections, and that a server may expire a connection if the response is too large or expensive to compute.

I'm not really sure what else there is really. Certainly the main risk is data leakage of stuff the user shouldn't be able to see

2025-09-24 19:08 UTC, foresto commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
Wouldn't a multi-term filter syntax that could vary between server implementations be useless unless clients maintained special-case code for each implementation? As a client developer, that kind of complexity would put me off.

If multi-term filters are to be supported, I would think it worthwhile to come up with a well-defined syntax for them. Or if support for them is to be postponed until after Matrix 2.0 is released, at least choose a single-term syntax for now that would be compatible with a future multi-term syntax.

Hm...

LIKE doesn't support multiple terms. SQL programmers get that effect by using multiple LIKE clauses, or syntactic sugar (e.g. LIKE IN) that expands to the same.

I suppose the room name filter could be an array of terms instead of a string.

Would multiple terms imply OR logic, or AND logic? I would expect OR to be most useful, for clients wishing to sync a specific set of named rooms first. On the other hand, AND logic might be useful where the words in room names are used like global topic tags (as distinct from user-specific tags, which have their own filter). For example, filtering on `["London", "fashion"]` to get rooms named "London events: fashion" and "London shopping: fashion".

Would regular expressions be better here? I suspect not, as their syntax is complex, and attempting to wrap regex in a more user-friendly syntax would invite a tar pit of edge cases.

Would glob be more useful than LIKE? A single glob pattern uses AND logic internally. If we supported an array of glob patterns with OR logic between them, it would give clients a limited form of AND/OR filtering. For example, `["London*fashion", "Bristol*music"]` to get rooms named  "London events: fashion", "London shopping: fashion", and "Bristol events: music".

2025-09-24 20:23 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +previous request.
I think it might be the other section that's "wrong" then. I'll try to make a suggestion.

2025-09-24 20:28 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +sent down in the first request, or b) have updates since the first request.
```suggestion
For example an initial request might have a list called `all_rooms` specifying a range of `[0,19]` in the initial
request, and the server will respond with the top 20 rooms (by most recently updated). On the second request the client
may change the range to `[0,99]`, at which point the server will use the top 100 rooms and respond with the ones that either a) weren’t
sent down in the first request, or b) have updates since the first request.
```

Maybe this is clearer?

2025-09-24 20:28 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
Connection exhaustion makes sense, and I guess having a separate API that is bulk /messages is essentially this API so...

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
This works but do we want to standardize the language? -> https://github.com/matrix-org/matrix-spec/issues/1334#issuecomment-2269948258

Previous discussion: https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1742162694

```suggestion
The order of rooms is always done based on the arrival time of the most recent event for the room on the homeserver.
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
> The exact ordering is determined by the server implementation.

What does this mean? I'm struggling to come up with how servers would put their own spin on things

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +purposes). Note: the range here matches 100 rooms, however we only send the 80 rooms that we didn't send down in the
> The server may sort the rooms differently than they are returned by the server (e.g. they may ignore reactions for sorting purposes)

How/why is this allowed? (also the sentence seems weird) Perhaps this whole sentence should just be removed.

This sounds like more of a `bump_stamp` detail where only some event types are considered.

But the ordering of rooms returned should always be `stream_ordering` ("arrival time of the event on the homeserver")

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "ranges": [[0, 10]],
> Is a list of lists really helpful here?

The standard use case (and only pattern I know of to get a sound/stable list without missing any data) would be for clients to use `[0, N]` and expand `N` over time until the full list of rooms is covered. See the example usage section for more info: https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L541-L569

I would say that we haven't found a use case that benefits from a list of ranges. So it could be a candidate to remove in favor of a single range. It's also been brought up to possibly be a single `page_size` number since we start at `0` all the time (see alternatives section) but I wouldn't discount creative clients utilizing a sliding window range or even multiple ranges as it is today. Since none of the creative use cases have been articulated, could be pragmatic to simplify (I would lean to a single sliding range).

One related use case is the following but this uses multiple `lists` with their own range. So overall, I think the creative multi-range use cases can be emulated with multiple `lists` anyway.

> For example, a client may specify a list with range `[0,99]` and a timeline limit of 10, plus a list with range `[100, <MAX>]` and timeline limit `1`. This would cause the server to return the most recent 10 events for rooms with recent activity, but only 1 event for older rooms (that the user is unlikely to visit).

---

> Are these numbers inclusive?

Yes, inclusive:

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L246

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +`[0,99]` and a timeline limit of 10, plus a list with range `[100, <MAX>]` and timeline limit `1`. This would cause the
```suggestion
`[0,99]` and a `timeline_limit` of 10, plus a list with range `[100, <MAX>]` and `timeline_limit` of `1`. This would cause the
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +   trickling" section.</del>
The problem wasn't the name so renaming doesn't solve anything -> https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1767500062

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We can also add a flag to disable attempting to backfill over pagination (to match the behaviour of the sync timeline).
> We can also add a flag to disable attempting to backfill over pagination (to match the behaviour of the sync timeline).

👍 This also plays nicely with other ideas being explored in MSC3871 (gaps) and MSC4282 (conditional backfill in `/messages`), see https://github.com/matrix-org/matrix-spec-proposals/pull/4282#discussion_r2376478043

---

Related conversation: https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2353065483

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // The room name, if one exists. Only sent initially and when it changes.
Still relevant, the MSC says this at the moment:

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L422

Previous conversation: https://github.com/matrix-org/matrix-spec-proposals/pull/3575#discussion_r1671260153

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "knock_state": [ .. ],
Relevant Synapse issue: https://github.com/element-hq/synapse/issues/17838

It looks like `membership` was added to the MSC :white_check_mark: 

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L413

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
It looks like this is resolved now :white_check_mark:  The MSC defines `RoomResult` with "Common fields" and fields for "Joined/left/banned" vs "Invite/knock"

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +#### Invite/knock
I think it would be nice to add a little bit of an explanation here to explain the reasoning why we don't have more fields here as this one area I found confusing while implementing since we do have more info for invites in rooms that the server is already participating in,

> The reason these can't be included is because we don't have any of that information for remote invites and the user isn't participating in the room yet so we shouldn't leak anything to them. We can only rely on the information in the invite event.
>
> *-- @MadLittleMods, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1745980679*

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
This is now resolved :white_check_mark: 

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L431

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
This still seems relevant (I don't have access to unresolve this thread)

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
This still seems relevant (I don't have access to unresolve this thread)

There is a little bit of information in the MSC but not enough as I how I explained above. And @Johennes's point on forgotten rooms.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
This was added to the MSC :white_check_mark: 

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L276-L289

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +   cache the membership list without requiring the server to send all membership updates for large gaps.
I guess this already covers state resets (or when room state changes from under it, due to state resolution) but we should consider explaining this more clearly. As otherwise, this point can appear a little redundant and could be interpreted as 'If the `timeline_events` is `limited: false`, then the first point will already covers this: "All the senders of events in `timeline_events` unless previously returned. This ensures that the client can render all the timeline events without having to fetch more events from the server."'

Related Synapse issues:

 - https://github.com/element-hq/synapse/issues/18782
 - https://github.com/element-hq/synapse/issues/17929

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +   cache the membership list without requiring the server to send all membership updates for large gaps.
> without requiring the server to send all membership updates for large gaps.

We should explain why that's useful. 'because it could be costly', 'because clients should just do x instead', etc

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +   `heroes` if we are returning membership events?
See https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1745962353

I would suggest this:

> One alternative is to match Sync v2 and only list the user ID's in `heroes` and include the membership events in `required_state`.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +
A `set_presence` was added to the MSC :white_check_mark: 

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L234

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
Previous conversation: https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2029311692

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
This still seems relevant (I don't have access to unresolve this thread)

We should at-least call this out in the alternatives and why/if we don't think it's a problem.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // An opaque integer that can be used to sort the rooms by "Bump Stamp"
Added to the MSC :white_check_mark: 

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L412

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
We should explain why:

> This way clients receive all new events.
>
> *-- @MadLittleMods, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2105301689*

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // An opaque integer that can be used to sort the rooms by "Bump Stamp"
This still seems relevant (I don't have access to unresolve this thread), at-least slightly.

Other `bump_stamp` thread: https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2104882482

It's currently described as the following

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L412

But I agree that it would be nice to lay it out a bit more clearly for people to implement. For example with Synapse, we just have `stream_ordering` and this is just the `stream_ordering` of the relevant event types.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +"state reset" has happened which removed an entry from the state entirely (rather than it being replaced with another
The current MSC addresses this with a `StateStub` that is returned in `required_state`

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L471-L478

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +- Presence \- presence in sync v2: spec
A `set_presence` parameter was added :white_check_mark: 

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L234

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
Yes

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
Is `room_name_like` actually useful? I think maybe not

People can subscribe to specific rooms as needed.

We [never implemented it in Synapse](https://github.com/element-hq/synapse/blob/dee6ba57a6ab3daaea90fee34f9c824688e38577/synapse/handlers/sliding_sync/room_lists.py#L1874-L1887) for reference.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
Needs clarification on whether this is just `m.room.name` or calculated room name, etc

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
> I still find the bump_stamp name to be incoherent.

For my own reference, here is the [conversation](https://matrix.to/#/!cnVVNLKqgUzNTOFQkz:matrix.org/$7uBBjZ4qCy9w1rX-9fCZgacYrgd2xzGwcAxnaW4dLh4?via=element.io&via=matrix.org&via=one.ems.host) (Element internal) where we came up with the name.

We basically evolved from these: `stream_ordering`, `bump_position`, `bump_counter`, `timestamp`, `version`, `generation`

I thought it would be nice to have `bump` in the name so it's obvious how it relates. Previously, this kind of field was called [`timestamp` in the Sliding Sync Proxy](https://github.com/matrix-org/sliding-sync/pull/247) because it was previously based on `origin_server_ts` but this was pretty non-obvious and flawed. And then @Hywan came up with `bump_stamp` which I thought was decent compared to the other options.

> I don't have a good feel for what a client would use it for.

:+1: The MSC should outline what a client would use this for; sorting the room list.... as it helps clients sort more readily without them needing to pull in a bunch of the timeline to determine the last relevant activity.

The idea here is that in a client, only certain event types should bump the room up to the top of the room list. I.e. Someone updating their display name shouldn't bump it to the top of the room list and mark it unread.

The reason why we don't sort by `bump_stamp` on the server is that we want clients receive all new events so we need to sort the server rooms by any new event activity.



> Should room upgrades be in here? Were other events considered and rejected?

More scrutiny and reasoning welcome to add more event types. I don't think there was a comprehensive breakdown of all types and why/why not we would include something. Probably best explored as new individual discussion threads.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
:+1: 

Previous discussion: https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1767500062

---

> Would adding a flag to `/messages` to *not* backfill be useful?

Yes, although may be slightly unrelated to Sliding Sync itself. I think the original point of this comment is just trying to hint at being able to get more messages without delay (from backfilling events over federation).

> 👍 This also plays nicely with other ideas being explored in [MSC3871](https://github.com/matrix-org/matrix-spec-proposals/pull/3871) (gaps) and [MSC4282](https://github.com/matrix-org/matrix-spec-proposals/pull/4282) (conditional backfill in `/messages`), see https://github.com/matrix-org/matrix-spec-proposals/pull/4282#discussion_r2376478043
>
> *-- @MadLittleMods, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2376498704*

which points to this idea ->

> For the hack day, I'll be tackling the backfill problem with this strategy:
> 
>  - **Default to fast responses with gaps**: As a default, we can always respond quickly and indicate gaps ([MSC3871](https://github.com/matrix-org/matrix-spec-proposals/pull/3871)) for clients to paginate at their leisure.
>  - **Fast back-pagination**: Clients back-paginate with `/messages?dir=b&backfill=false`, and Synapse skips backfilling entirely, returning only local history with gaps as necessary.
>  - **Explicit gap filling**: To fill in gaps, clients use `/messages?dir=b&backfill=true` which works just like today to do a best effort backfill.
> 
> This allows the client to back-paginate the history we already have without delay. And can fill in the gaps as they see fit.
> 
> Gaps can be represented in the UI with a message like "We failed to get some messages in this gap, try again 🗘.", giving users clear feedback. Regardless of clients trying to fill in gaps automatically, I would still suggest to display gaps so people can tell what's happening.
> 
> This is basically a simplified version of [MSC4282](https://github.com/matrix-org/matrix-spec-proposals/pull/4282) leveraging [MSC3871: Gappy timelines](https://github.com/matrix-org/matrix-spec-proposals/pull/3871) to get proper client feedback to indicate where the gaps are so we can skip backfill without worrying. For reference, skipping backfill without letting clients know where the gaps are just means they won't ever know that they are missing messages.
>
> *-- @MadLittleMods, https://github.com/element-hq/how-hard-can-it-be-2025/issues/47#issuecomment-3234339497*

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +- Support lazy-loading of things like read receipts (and avoid sending unnecessary data to the client)
```suggestion
- Support lazy-loading of things like membership and read receipts (and avoid sending unnecessary data to the client)
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +left to save bandwidth and general efficiency (as the user knows they've left), but we still include kicked and banned
```suggestion
connection. Rooms the user has been kicked or banned from will always be included. We do not include rooms the user has
left themselves to save bandwidth and general efficiency (as the user knows they've left), but we still include kicked and banned
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +    "!foo:example.com": {
Related language added to the MSC:

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L123-L124

This doesn't completely address the other questions though.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +number of events to return in the timeline section of a room, and the "required state" specifies what state to return.
```suggestion
Each rule also specifies a "room config", used to configure what data to return for a room that matches the rule. The
"room config" has two fields: the `timeline_limit` and `required_state`. The `timeline_limit` specifies the maximum
number of events to return in the timeline section of a room, and the `required_state` specifies what state to return.
```

Doesn't change readability and makes it easy to `Ctrl + F`

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `conn_id` | `string` | No | An optional string to identify this connection to the server. Only one sliding sync connection is allowed per given conn_id (empty or not). |
```suggestion
| `conn_id` | `string` | No | An optional string to identify this connection to the server. Only one sliding sync connection is allowed per given `conn_id` (empty or not). |
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `pos` | string | No | Omitted if this is the first request of a connection. Otherwise, the `pos` token from the previous call to `/sync` |
```suggestion
| `pos` | string | No | Omitted if this is the first request of a connection (initial sync). Otherwise, the `pos` token from the previous call to `/sync` |
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `filters` | `SlidingRoomFilter` | No | Filters to apply to the list before sorting. |
```suggestion
| `filters` | `SlidingRoomFilter` | No | Filters to apply to the list. |
```

It doesn't matter whether we filter before or after sorting.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `lazy_members` | `bool` | No | Whether to enable lazy loaded membership behaviour. Defaults to false. |
```suggestion
| `lazy_members` | `bool` | No | Whether to enable lazy loaded membership behaviour. Defaults to `false`. |
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +1. All the senders of events in `timeline_events` unless previously returned. This ensures that the client can render
```suggestion
1. All the `senders` of events in `timeline_events` unless previously returned. This ensures that the client can render
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +Memberships returned to the client due to `lazy_members` are *not* filtered by `exclude`.
Why?

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `is_encrypted` | `bool` | No | Flag which only returns rooms which have an `m.room.encryption` state event. <br/><br/> If unset, both encrypted and unencrypted rooms are returned. If `False`, only
```suggestion
| `is_encrypted` | `bool` | No | Flag which only returns rooms which have an `m.room.encryption` state event. <br/><br/> If unset, both encrypted and unencrypted rooms are returned. If `false`, only unencrypted rooms are returned. If `True`, only encrypted rooms are returned. |
```

Applies to other bools

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +not set, e.g. if `initial` is true and `name` is not set then the room has no name. Care must be taken by clients to
```suggestion
not set, e.g. if `initial` is `true` and `name` is not set then the room has no name. Care must be taken by clients to
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ensure that if they previously saw that the room had a name, then it MUST be cleared if it receives a room response with
```suggestion
ensure that if they previously saw that the room had a `name`, then it MUST be cleared if it receives a room response with
```

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +#### Joined/left/banned
```suggestion
#### Joined/left/banned (assuming previously joined)
```

A user could have been `invite` -> `ban` in which case we wouldn't have these fields and should act like an invited room.

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
We should include more details behind this. We could copy `RoomSummary` -> `m.heroes`

> This should be the first 5 members of the room, ordered by stream ordering, which are joined or invited. The list must never include the client’s own user ID. When no joined or invited members are available, this should consist of the banned and left users. More than 5 members may be provided, however less than 5 should only be provided when there are less than 5 members to represent.
> 
> When lazy-loading room members is enabled, the membership events for the heroes MUST be included in the state, unless they are redundant. When the list of users changes, the server notifies the client by sending a fresh list of heroes. If there are no changes since the last sync, this field may be omitted.
>
> *-- https://spec.matrix.org/v1.14/client-server-api/#get_matrixclientv3sync_response-200_roomsummary*

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +
Related info added to the MSC:

https://github.com/matrix-org/matrix-spec-proposals/blob/985e71f8d4ccc38d90ddf3bfed0be9e8ba35610a/proposals/4186-simplified-sliding-sync.md?plain=1#L560-L561

2025-09-24 20:39 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +If the `timeline_limit` is increased then the server will send down historic data (c.f. "Changing room configs"), which
This should mention that we're talking about `expanded_timeline` here

2025-09-24 22:47 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
What does bump mean though? That's the part I don't get.

2025-09-25 12:03 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
You're not wrong, though almost every app will just display a text box for the filter. The app *could* then have custom rules to tokenize the filter and then send *that* to the server, but frankly I think almost every app would just send the raw string to the server. At that point, the options I think are basically: a) define how the server interprets the string, or b) leave it up to the implementation (as we do for event search).

2025-09-25 12:43 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
It is probably ok to be left to implementations.

2025-09-25 12:45 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +      "ranges": [[0, 10]],
I think I'd be in favor of simplifying then. Especially with the workaround you mention.

2025-09-25 13:48 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +  "pos": "<opaque string>",
Currently SCT is leaning towards: `from` and `next_batch` instead of `pos` everywhere.

2025-09-25 14:21 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
We need to take a little bit of care here, as "arrival time" correlates but isn't exactly the ordering we use in Synapse for example. In more distributed HS implementations this may also depend on the order in which a particular instance or whatever saw the events.

2025-09-25 14:22 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +purposes). Note: the range here matches 100 rooms, however we only send the 80 rooms that we didn't send down in the
Oops, that was me forgetting when writing it initially that we no longer ordered by bump stamp. Have removed the sentence.

2025-09-25 14:33 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +#### Joined/left/banned
Oooh, good point. What do we send down in the transition from `invite` -> `leave`?

2025-09-25 14:57 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
Oh! I saw that we checked for them but missed that we threw an error if it was used :facepalm: 

Burn it with fire!! :fire:

2025-09-25 15:15 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
Ah, good point. Have just linked to it.

2025-09-25 15:18 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
Activity that should *bump* the room up to the top of the room list.

It looks like this originates from the original Sliding Sync [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575)

> ```
> // Sticky. Allowlist of event types which should be considered recent activity
> // when sorting `by_recency`. By omitting event types from this field, clients
> // can ensure that uninteresting events (e.g. a profile rename) do not cause a
> // room to jump to the top of its list(s). Empty or omitted `bump_event_types`
> // have no effect—all events in a room will be considered recent activity.
> //
> // NB. Changes to bump_event_types will NOT cause the room list to be reordered;
> // it will only affect the ordering of rooms due to future updates.
> "bump_event_types": [ "m.room.message", "m.room.encrypted" ],
> ```

2025-09-25 15:21 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +#### Joined/left/banned
See https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1767493967

We should include that information ^

2025-09-25 15:30 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +    "!foo:example.com": {
This part of the MSC was [just removed as well](https://github.com/matrix-org/matrix-spec-proposals/pull/4186/commits/492db052d3e34449ee703dae31949ec887ad761e)

Everything needs clarification again.

2025-09-25 15:33 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "ranges": [[0, 10]],
MSC has been updated to a single `range` per list -> https://github.com/matrix-org/matrix-spec-proposals/pull/4186/commits/1058ad7653dc5dc5b3ac25d47eeed0d32e2d72f1

2025-09-25 15:54 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +Memberships returned to the client due to `lazy_members` are *not* filtered by `exclude`.
I think it's the option that makes the most sense? TBH I don't think it matters and you just have to make a call one way or the other on how they interact. In my head the include/exclude is one filter, and the lazy members is a different one.

I can't think of a use-case either way

2025-09-25 16:00 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently does not return rooms with expanded state immediately, instead waits for the next update.
FTR I think this is mainly an implementation bug, I don't think it is too bad to implement, as the underlying mechanics are the same as to handle changes in `timeline_limit`.

2025-09-25 16:07 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +Memberships returned to the client due to `lazy_members` are *not* filtered by `exclude`.
I was probing if there was a reason. Sounds like there isn't a reason which is fine. Feels like we should write that down at-least.

I could also see how `lazy_members` feels like another `include` filter which is filtered out with `exclude`. This was my first inclination so they feel the same and probably prompted my questioning.

2025-09-25 16:09 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently does not return rooms with expanded state immediately, instead waits for the next update.
Synapse issue -> https://github.com/element-hq/synapse/issues/18844

2025-09-25 16:26 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
Isn't that what it already says?

2025-09-25 16:41 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
I don't think so (just re-read it again).

It says that events are ordered by last activity but not why.

This is an important distinction as indicated by the call out that it's not by `bump_stamp` as one might think.

2025-09-25 20:40 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
So "activity rank" or something like that?

2025-09-25 21:23 UTC, foresto commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
Okay. In that case, since the syntax would be server-defined, wouldn't it make sense to give the field a name that doesn't suggest SQL LIKE syntax?

2025-09-26 16:19 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
As described in https://github.com/element-hq/synapse/pull/17579#discussion_r1722579007, another alternative would be to just use another initial sync request with an increased `timeline_limit`. The linked comment describes more details for client implementations as well.

Cross-link to the main discussion about moving away from `expanded_timeline` -> https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1767500062

2025-09-26 16:22 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
Is the request body so large that it is causing issues? Can you expand upon why this complication is necessary?

2025-09-26 16:23 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `pos` | `string` | Yes | The next position token in the sliding window to request. |
> Currently, Synapse uses a [similar but incompatible token](https://github.com/element-hq/synapse/blob/769d30a247926dd90d9afe7f6afd65bdc605d465/synapse/types/__init__.py#L1287-L1301) format for Sliding Sync compared to any other endpoint. If compatibility is desired, we can always still work with this format and accept it on other endpoints and strip off the extra field.

I think it is desired, it will be pretty confusing if it can't be re-used. @erikjohnston told me it _can_ be used on `/messages` though? Doesn't that mean it would work for other endpoints too?

2025-09-26 16:25 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We can also add a flag to disable attempting to backfill over pagination (to match the behaviour of the sync timeline).
Cross-link to another alternative about using another initial sync request with an increased `timeline_limit` -> https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2382872147

2025-09-26 17:41 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
It looks like a new **"Sticky `lists` field"** was added to the MSC.

I'm not in favor of adding this :x:

When we started on all of this, we purposely avoided doing any sort of complicated sticky params in this "Simplified" version of Sliding Sync compared to the [original Sliding Sync](https://github.com/matrix-org/matrix-spec-proposals/pull/3575). It's nice to have the request side stateless.

This also seems like a half-measure in terms of trying to save request bandwidth. Why aren't we doing the same with `room_subscriptions`, etc? **A bandwidth optimized version seems like a future thing.**

Since we've [discussed this internally](https://matrix.to/#/!cnVVNLKqgUzNTOFQkz:matrix.org/$krEtYn-Nk1LesccUgpbVp5l5Qy71cj6MgnKGw-Bp8vw?via=element.io&via=matrix.org&via=one.ems.host), the reasoning being thrown around is that `room_subscriptions` are supposed to be short-lived which seems like a false situation. I could have a long-running `room_subscriptions` for any reason including multi-room grid views. Creative client use cases are endless.


---

Additionally, this forces servers to start tracking things on a per-connection level. Previously, you could have a simple, naive, and stateless Simplified Sliding Sync implementation that doesn't track per-connection state at all. You will just get duplicate data in the response which is even how we did things in Synapse before we started tracking per-connection state.

The claim against this is that isn't a useful implementation but it's plenty good to work.


### Any good alternatives?

I don't have a good alternative to solve this bulky bandwidth problem in this iteration of the MSC. I think this requires way more holistic thought and is why I think it's a future thing to address. If there is some simple good idea we can think of to address the request bandwidth problem to include in this MSC, happy to ferry it further (I don't think we have that yet).

For a point of reference, we've been using the Simplified Sliding Sync API for a year now as-is with the request bulk (even [response bulk](https://github.com/element-hq/synapse/issues/18517)).

Possible future solutions may include websockets, [server-sent events (SSE)](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2105196853), or even using some similar tricks from the [original Sliding Sync MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575).

2025-09-29 08:53 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +response.
I think this information is in "Room results" section.

2025-09-29 08:54 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +#### Joined/left/banned
Have updated to make clearer how to handle each case.

2025-09-29 09:06 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +#### Joined/left/banned
Have updated the sections

2025-09-29 09:12 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +  "pos": "<opaque string>",
Having thought about it a little more, I'm not sure that `next_batch` as a name really fits with how the API works. It does match pagination APIs, which is a plus, but not totally convinced about it.

2025-09-29 09:16 UTC, erikjohnston commented
I think this is ready for the SCT to read and weigh in on. In particular, attention should be paid to the changelog at the bottom that lists all the things that I propose we change from the current implementation (there are also some notes in the body of the text where things haven't been implemented by synapse).

I think the "controversial/open" questions that should get SCT agreement are the following, including my votes on the subjects (which reflect the current MSC): 

1. Should we implement "sticky" lists? My vote is: yes. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2383054381)
2. Should we rename the `pos` parameters? My vote is: no. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1742221179)
3. Should we implement the notification counts? My vote is: yes. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2353016460)
4. Should we deduplicate heroes between `heroes` and `required_state`? My vote is: no. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2376680495)
5. Should we replace `timeline_limit` expansion with a bulk `/messages` API? My vote is: no. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2353065483)

@mscbot fcp merge

2025-09-29 09:33 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
A couple of points from internal discussions:

1. We have experience where websockets and SSE don't work in all environments (especially corporate networks with silly http proxies), so at the very least we want to have the ability to not require websockets/SSE. Moving to websockets/SSE is also not a small change, losing the request/response in particular will require careful thought.
2. Adding this feature isn't trivial later on, as you need to add negotiations for clients to know they can use it. Though I guess that can just be a standard version check.

2025-09-29 09:40 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
> Additionally, this forces servers to start tracking things on a per-connection level. Previously, you could have a simple, naive, and stateless Simplified Sliding Sync implementation that doesn't track per-connection state at all. You will just get duplicate data in the response which is even how we did things in Synapse before we started tracking per-connection state.
>
> The claim against this is that isn't a useful implementation but it's plenty good to work.

I just don't really see how useful that is in practice TBH. Yes, it was a nice stepping stone while implementing SSS in Synapse, but I am unconvinced that that is a good rationale for avoiding adding further per-connection state.

2025-09-29 10:09 UTC, erikjohnston commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

MSC authors: feel free to ask *in a thread* on your MSC or in the[#matrix-spec:matrix.org](https://matrix.to/#/#matrix-spec:matrix.org) room for clarification of any of these points.

- [ ] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal) specified in the MSC’s PR description?
- [ ] Are all MSCs that this MSC depends on already accepted?
- [ ] For each new endpoint that is introduced:
  - [ ] Have authentication requirements been specified?
  - [ ] Have rate-limiting requirements been specified?
  - [ ] Have guest access requirements been specified?
  - [ ] Are error responses specified?
    - [ ] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [ ] If a new `errcode` is introduced, is it clear that it is new?
- [ ] Will the MSC require a new room version, and if so, has that been made clear?
  - [ ] Is the reason for a new room version clearly stated? For example, modifying the set of redacted fields changes how event IDs are calculated, thus requiring a new room version.
- [ ] Are backwards-compatibility concerns appropriately addressed?
- [ ] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [ ] Do HTTP endpoints `use_underscores_like_this`?
  - [ ] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [ ] If the endpoint utilises pagination, is it consistent with [the appendices](https://spec.matrix.org/latest/appendices/#pagination)?
- [ ] An introduction exists and clearly outlines the problem being solved. Ideally, the first paragraph should be understandable by a non-technical audience.
- [ ] All outstanding threads are resolved
  - [ ] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [ ] While the exact sections do not need to be present, the details implied by the proposal template are covered. Namely:
  - [ ] Introduction
  - [ ] Proposal text
  - [ ] Potential issues
  - [ ] Alternatives
  - [ ] Dependencies
- [ ] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [ ] Unstable prefixes [consider](https://github.com/matrix-org/matrix-spec-proposals/blob/main/README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [ ] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [ ] Changes have applicable [Sign Off](https://github.com/matrix-org/matrix-spec-proposals/blob/main/CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [ ] There is a dedicated "Security Considerations" section which detail any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.". See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about, but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-09-29 14:50 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
Also see https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2382872147 that describes another alternative for removing `expanded_timeline`. We don't even need to add a new bulk `/messages` endpoint. The client can just do another initial Sliding Sync request with the increased `timeline_limit` to get all of the messages that they want.

2025-09-29 15:34 UTC, turt2live approved these changes
overall lgtm. I'm aligned with @erikjohnston's votes at https://github.com/matrix-org/matrix-spec-proposals/pull/4186#issuecomment-3345882516

2025-09-30 12:18 UTC, Hywan commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
My voice represents the Matrix Rust SDK, which has been the first SDK to provide a client implementation of SS and then SSS. The Matrix Rust SDK has played a significant role in the design of MSC3575 and this MSC.

We believe this is **not** a good idea to introduce stickiness under any form for the moment. We believe it must be done but in another MSC.

About the size of the payload:

1. Synapse has been returning the famous `response.lists.*.ops` since a long time, which was a heritage of the MSC3575, but wasn't part of this MSC. It adds a **lot** of data for no value, because the Matrix Rust SDK, so Element X iOS/Android for example, [doesn't use it since July 2024](https://github.com/matrix-org/matrix-rust-sdk/pull/3664/). It means Synapse is returning useless data for more than a year, with no concrete impact for daily regular usages (note: it has an impact, and removing it will have an impact, but it wasn't so much impactful to trigger alarms).
2. We believe two (actually three) candidates for stickiness are `request.lists` and `request.room_subscriptions`, if we want to be complete. Doing one and not the other has a taste of “incompleteness”. Also, note that _extensions_ might also be interested by providing stickiness, something that has not been mentioned yet.

So far, there is no sign that providing `request.lists` and `request.room_subscriptions` every time constitute a performance problem in the current client (Matrix Rust SDK) or current server (Synapse/conduwuit) implementations. Hence, we are asking the MSC authors to postpone this subject with another MSC (MSC we are willing to write and drive). We acknowledge it must be done, as **reducing the bandwidth has always been the motivation behind this new sync mechanism**, and we want to push it to its limit. However, we don't want to rush it and find ourselves in a situation where everyone is unhappy and to support a hybrid design. Our approach here is rather: let's do the basis correctly, then iterate.

2025-09-30 12:25 UTC, bnjbvr commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
Strongly seconding Hywan's comment.

2025-09-30 16:48 UTC, dbkr commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
FTR I tried to implement this in https://github.com/element-hq/synapse/pull/18290 as Element Web needs this.

2025-09-30 16:57 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "highlight_count": 1,
Conversation also continued at https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2353016460

2025-09-30 18:26 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
This sounds like it needs to be incorporated into the MSC? What are the downsides of this? It seems fairly elegant.

2025-09-30 20:08 UTC, clokep commented
> I think the "controversial/open" questions that should get SCT agreement are the following, including my votes on the subjects (which reflect the current MSC):

I've already given a bunch of reviews on here, so I thought highlighting my stance on these questions might be the most useful thing.

> 1. Should we implement "sticky" lists? My vote is: yes. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2383054381)

This feels like a thing we can add in later easily by having clients opt into a list being sticky. I'm not seeing a great cost savings by doing this right now (at further complexity to the API).

> 2. Should we rename the `pos` parameters? My vote is: no. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1742221179)

Yes. It is completely inconsistent with our current APIs. See matrix-org/matrix-spec#125, matrix-org/matrix-spec#1280.

> 3. Should we implement the notification counts? My vote is: yes. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2353016460)

I don't see why not? Is the concern performance?

> 4. Should we deduplicate heroes between `heroes` and `required_state`? My vote is: no. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2376680495)

I don't have a strong opinion, but I think no -- that's pushing complexity onto the client.

> 5. Should we replace `timeline_limit` expansion with a bulk `/messages` API? My vote is: no. [Thread](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2353065483)

I'm not sure, it feels like it would simplify this API a lot and there's a bunch of good alternatives that don't have their pros/cons explored in the MSC. I think there's something missing here.

2025-09-30 21:41 UTC, turt2live commented
@mscbot concern Pending complete implementation (action: remove needs-implementation label)

Note: anyone on the SCT should be able to `@mscbot resolve` this concern. Just highlighting that implementation isn't *quite* there yet.

2025-10-01 10:42 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
I have removed sticky lists from this proposal. @Hywan elsewhere said that this is non-trivial for clients to implement and should be tested, and I'm happy to take that on faith. It was also brought up that we may also want a similar mechanism for some extensions.

@Hywan has kindly volunteered to create an MSC for tackling these issues.

2025-10-03 09:33 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
I've added it as an alternative. I think the main downsides are: a) duplication of data (e.g state), and b) only supports the one use case.

2025-10-03 14:47 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
> a) duplication of data (e.g state)

The goal is to get `timeline` events so you would just make an initial Sliding Sync request without any `required_state`:

<details>
<summary>Example initial sync request</summary>

Request body:
```jsonc
{
    "conn_id": "fetch_timeline",

    "lists": {
        "foo-list": {
            "range": [0, 99],
            "required_state": {},
            "timeline_limit": 20,
            "filters": {
                "is_dm": true
            },
        }
    },
    "room_subscriptions": {
        "!sub1:bar": {
            "required_state": {},
            "timeline_limit": 20,
        }
    }
}
```

</details>

2025-10-03 14:49 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
> only supports the one use case.

What are the other use cases not covered?

`expanded_timeline`'s goal is to get more `timeline` messages

2025-10-03 14:52 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
Looks like this is the use case (from the https://github.com/matrix-org/matrix-spec-proposals/pull/4186/commits/ef197a4c32b5c9131a27f41b0a984ab59878d4da):

> The approach also doesn't support the use case for having two lists so that rooms that bubble to the
top of the room list automatically get expanded timelines.

You would just make another initial Sliding Sync request to get the messages again.

If it's only a few rooms, then it would be fine to use `/messages` as normal to fetch more timeline individually. But the whole point is that this use case covers fetching timeline for a bulk number of rooms so if you see a whole bunch of rooms bubble up, doing another initial Sliding Sync request covers this perfectly.

2025-10-06 05:11 UTC, TheArcaneBrony commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
How would sending null here work with languages that don't distinguish between null/undefined?
ie. with Rory&::LibMatrix, I don't see a feasible way to use this, as either null is omitted, or null is always serialised where the value is well... null. There is no runtime way to change this behavior, unless you resort to hacks, which can incur quite a painful performance penalty.
Maybe we could consider using a magic value like `"$null"`, or a boolean field (`include_untyped_rooms` and `exclude_untyped_rooms`)?

2025-10-06 07:01 UTC, Xiretza commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
I don't think the spec has to concern itself with implementations that don't implement JSON completely. Unlike e.g. large integers and floats, JSON null values are very well-defined, there's no reason the spec should avoid them (and anyway, I'm pretty sure it already defines semantics for null values in other places).

2025-10-06 08:20 UTC, bnjbvr commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
+1, any modern language should offer the semantics to implement sum types, aka enums, aka tagged unions (heck, even these can be emulated in C/C++), and this would be the way to support the distinction between null, a non-null value, and undefined.

2025-10-06 08:55 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
I don't think its really feasible to do initial syncs once the app has fully started up. Doing a double initial sync at the start makes sense, you do one with minimal data (although still with a lot of state as you need room info and member events to actually render the room lists and timelines) and then you do a second with a larger timeline_limit and completely replace the data from the first request with the second.

But doing an initial sync *later* means having to try and tie timelines together, e.g. if you do an initial sync for a room at the same time as another events comes down your sync loop, you need to make sure that that event does appear in the timeline and doesn't get "overwritten" by the initial sync (which may not include it). This doesn't feel particularly feasible to do reliably.

2025-10-06 08:56 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +We can also add a flag to disable attempting to backfill over pagination (to match the behaviour of the sync timeline).
> And the proxy behavior was a [bug not a feature](https://github.com/element-hq/synapse/pull/17503#discussion_r1718416282) (self-described)

Worth noting that the timeline trickling was a desired feature, albeit one that was regretted. The "bug" there was that the proxy set `initial: true` when it shouldn't have.

2025-10-06 09:02 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
There are two questions here really:

1. Do we think `timeline_limit` expansion is good enough to meet the needs that clients have today?
2. If not, should we block this MSC from landing while we try and land something better?

Personally, I think its in the interest of the ecosystem to land this API sooner rather than later. Its been demonstrated by EX clients that it is a vast improvement over previous APIs.  

Are there any major downsides to timeline expansion? There is a lot of talk about how you could get nearly the same sort of effect via other mechanisms, but I don't see much concrete arguments *against*. Certainly it does complicate servers, but clients can entirely opt-out of using the mechanism.

2025-10-06 11:20 UTC, TheArcaneBrony commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
Sadly, no such thing as a tagged union in C# - enums can only represent integer types too. Besides, to the best of my knowledge, the stance of the spec is that null == undefined anyways?

2025-10-06 11:27 UTC, TheArcaneBrony commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
Just realised that these are arrays and this is fine - more worried about fields that expect explicit null, which doesnt appear to be the case in this MSC, and I failed to catch this last night.
For those I'd need to do multiple serialise/deserialise calls, which is the part that concerned me.

2025-10-06 11:30 UTC, tulir commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
In general I agree that the spec shouldn't limit itself because of incomplete JSON implementations, but in this case I don't see why we couldn't just use an empty string to represent untyped rooms. Doing that wouldn't require hacks like `"$null"` nor any new fields. I'd assume everything already treats `"type": ""` and no type as the same thing in `m.room.create`. There's certainly no sensible way to assign any other meaning to an empty string room type.

2025-10-06 11:42 UTC, TheArcaneBrony commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
In this case i can jut type it as `string?` and send ie. `[null, "m.room.space"]`, but the same wouldn't apply if it were a singular property rather than an array (ie. `"room_type": null` isnt possible, i just dont serialise null values outside of arrays in the first place)

2025-10-06 11:45 UTC, bnjbvr commented on proposals/4186-simplified-sliding-sync.md
> +| `not_room_types` | `[string \| null]` | No | Same as `room_types` but inverted.<br/><br/> This can be used to filter out spaces from the room list. If a type is in both `room_types` and `not_room_t
`null` and `undefined` have different semantics throughout this spec. For instance, the room name or room avatar updates are sent by the server. The server _needs_ a way to let the client know that a room name has been *removed*; so it does send `null` in the room's response part to indicate that, as far as I recall. But if the room name hasn't changed since the previous time, it may not send the field, aka it's `undefined`. This is one place where `null` and `undefined` have different semantics.

2025-10-06 21:35 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
### Seamless timeline

> But doing an initial sync _later_ means having to try and tie timelines together, e.g. if you do an initial sync for a room at the same time as another events comes down your sync loop, you need to make sure that that event does appear in the timeline and doesn't get "overwritten" by the initial sync (which may not include it). This doesn't feel particularly feasible to do reliably.

I already have notes about how to do this in https://github.com/element-hq/synapse/pull/17579#discussion_r1722579007 ->

While this describes a potential implementation for Element X which doesn't have offline support and throws away events, I think the same thing works generally.

> For the timeline stitching logic, the client can store the latest event in timeline before our initial sync, then find that event in the initial sync `timeline` events and spread backwards from that point. That way, the ongoing sync loop can still append to the end of the timeline and continue seamlessly.
> 
> So if we have a timeline `[103]` already on the client, we store `latest_event_id = 103`, do our initial sync which returns `[100, 101, 102, 103, 104]` and we splice/spread in only `[100, 101, 102, 103]` accordingly (drop any new events after the `latest_event_id` from the initial sync response). This makes it so that even if the ongoing sync loop sends `104` before or after our initial sync does, it still appends like normal and everything is in seamless order.
> 
> If there are so many new messages sent in the time between us storing the `latest_event_id` and the initial sync responding that we now have a gap, we can just throw away our initial sync events because we have enough events to fill up the timeline just from our normal ongoing sync loop.
> 
> ---
> 
> To be clear, the client doesn't need to be fancy about stitching:
> 
> If the client had more timeline like `[98, 99, 100, 101, 102, 103]`, we store `latest_event_id = 103`, we start the initial sync, our ongoing sync loop races us and returns `104` which makes our timeline look like `[98, 99, 100, 101, 102, 103, 104]`. Then our initial sync responds with `[100, 101, 102, 103, 104]`, we find the `103` spot in the response to slice at and place it at the `103` spot in the client timeline leaving us with `[100, 101, 102, 103, 104]`
> 
> Pseudo code (maybe off-by-one errors):
> 
> ```py
> latest_event_id = 103
> 
> # do initial sync request
> 
> initial_sync_timeline = [100, 101, 102, 103, 104]
> event_index_in_response = initial_sync_timeline.index(latest_event_id)
> # Skip if we can't find the `latest_event_id` in the response.
> # This means there have been so many messages sent between the time we initially
> # made the initial sync and the response that this is no longer relevant.
> # We already have enough events to fill up the timeline from the normal
> # ongoing sync loop
> if event_index_in_response is None:
> 	return
> 
> event_index_in_client_timeline = client_timeline.index(latest_event_id)
> # Update the timeline
> client_timeline = initial_sync_timeline[0:event_index_in_response] + client_timeline[event_index_in_client_timeline:-1]
> ```
>
> *-- @MadLittleMods, https://github.com/element-hq/synapse/pull/17579#discussion_r1722579007*


By the nature of how `expanded_timeline` works ("send down the latest `N` events, even if some of those events have previously been sent"), duplicate events are an expected scenario for clients to handle. So handling seamless timeline is a pre-requisite for clients either way.

If you're referring to the problems that come from differing orders from `/sync` (`stream_ordering`) and `/messages (topological ordering), this is the exact same problem regardless of how we accomplish things (especially for offline-first clients that persist events).

2025-10-06 21:36 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
Please update this alternative with a more accurate description. I don't think these downsides are accurate, see https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2382872147

2025-10-06 21:56 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
### `expanded_timeline` complication

> Are there any major downsides to timeline expansion? There is a lot of talk about how you could get nearly the same sort of effect via other mechanisms, but I don't see much concrete arguments _against_. Certainly it does complicate servers, but clients can entirely opt-out of using the mechanism.

Basically, these same arguments were made in favor of timeline trickling when it was twice as bad trying to overload the `limited` and `initial` fields. We now have a dedicated `expanded_timeline` field to turn this behavior from evil to baseline acceptable.

But we also have alternatives to avoid the complication altogether.

---

Clients can't opt out. With `expanded_timeline`, a client who wants to increase `timeline_limit` *for whatever reason* must take into account `expanded_timeline` to know whether they are seeing historical messages (no longer possible to be a dumb naive client).

2025-10-06 22:04 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
Clarify sort (descending, latest events first)

2025-10-06 22:04 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
Clarify event order:

> 1. The first time a room is sent down `/sync` we use `paginate_room_events` to get a chunk of history for the client, this basically results in the same as if no history was sent down `/messages` was used.
> 2. We use `get_room_events_stream_for_rooms` to get all updates for rooms since the last `/sync`, which is in stream ordering.
>
> *-- @erikjohnston, https://github.com/element-hq/synapse/pull/17510#discussion_r1704155477*

More context: https://github.com/element-hq/synapse/pull/17510

2025-10-07 09:31 UTC, bnjbvr commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
Random question:

> The first time a room is sent down /sync we use paginate_room_events to get a chunk of history for the client, this basically results in the same as if no history was sent down /messages was used.

Does it mean that a sync response can now be waiting on a pagination which may backfill events from other servers, binding the response time to the federation request? or does it wait for a pagination response for a very small time, and in case the response didn't come, it will instead send a SSS response sooner, and include the backfill results in a subsequent SSS response?

2025-10-07 09:38 UTC, bnjbvr commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
Even after re-reading the text of the MSC a few times, I don't understand the goal of the `expanded_timeline` flag; does it mean that there *might* be duplicates? As noted in a previous comment in this thread, clients have to handle duplicates anyways (b/o the `timeline_limit` increasing use case to start with, and then to deduplicate results from /messages which used previously persisted pagination tokens). Maybe the `expanded_timeline` flag is a hint?

Overall, I'd love to see more guidance for clients, with respect to when is it better to expand the `timeline_limit`, or when is it better to use `room/ROOM_ID/messages` for back-paginations. For instance, if a client wants to compute the unread status of a room, then, because of e2ee rooms, they may have to back-paginate up to the previous read receipt target event (if there's a gap in the timeline). In this case: should we rather use `room/ROOM_ID/messages` (and send one request for *each* room), or use custom lists with an expanded `timeline_limit` (the naivest way being increasing the `timeline_limit` for *all* rooms)?

(I want to note the cross-room `/messages` endpoints, which could take multiple per-room pagination tokens, would be a nice addition, but I do understand it's a big change and would rather see it become its own MSC.)

2025-10-07 11:42 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
I think at least some articulation of what is difficult about sticky state is owed here. If this issue is to be inevitably revisited in a future MSC it will just have to be then. More pressing though is to address the growing chasm between the original goals for this endeavor and the swan dive into the abyss it just took. The fact is these requests are larger than legacy sync. This is a problem because it's mobile transmit bandwidth straight from the battery. If these issues are trivial, why do we need this at all? If not, this MSC was supposed to be that "future thing." I don't feel like I'm alone in questioning what the point of all this is now. The issues opened by M say it loudly.

2025-10-07 13:53 UTC, zecakeh commented on proposals/4186-simplified-sliding-sync.md
> +The endpoint is a `POST` request with a JSON body to `/_matrix/client/unstable/org.matrix.simplified_msc3575/sync`.
The stable version of the endpoint is not documented anymore? It should be `/_matrix/client/v4/sync` I guess?

2025-10-07 14:14 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
@MadLittleMods:

> For the timeline stitching logic, the client can store the latest event in timeline before our initial sync, then find that event in the initial sync `timeline` events and spread backwards from that point. That way, the ongoing sync loop can still append to the end of the timeline and continue seamlessly.

That's not safe though, given that sync orderings can be different depending on which worker you hit.

> If you're referring to the problems that come from differing orders from `/sync` (`stream_ordering`) and `/messages` (topological ordering), this is the exact same problem regardless of how we accomplish things (especially for offline-first clients that persist events).

That's why we have tokens and clients *should* be using both `from` and `to` tokens in `/messages` to ensure that they get all the events within gaps. Once you start trying to overlay different orderings (via multiple `/sync`) you're vulnerable to subtle races and missing events.

Though there is a flaw here in that we don't have a good way of handling clients that cache events from previous sync connections. Ideally they'd deduplicate any events and always call `/messages` even if the timelines overlapped.

The expanded timeline and double initial sync both work as solutions because the timelines get fully replaced and future syncs will always return deltas based on what you got. Doing an initial sync after means you have a chunk of timeline but future syncs are not getting deltas from.


> Clients can't opt out. With `expanded_timeline`, a client who wants to increase `timeline_limit` _for whatever reason_ must take into account `expanded_timeline` to know whether they are seeing historical messages (no longer possible to be a dumb naive client).

That's fair for clients that use multiple timeline limits, though if we don't expand the timeline limit then it is also a bit odd: the client isn't getting the data it might expect in all cases. Either way, if clients don't want to deal with the "complexity" of `expanded_timeline` flag then it can avoid using multiple different timeline limits. They can either do the double initial sync, or wait for potential future MSCs to allow bulk `/messages`.

> Basically, these [same arguments](https://github.com/element-hq/synapse/pull/17503#discussion_r1697697828) were made in favor of timeline trickling even when it was twice as bad trying to overload the `limited` and `initial` fields. We now have a dedicated `expanded_timeline` field to turn this behavior from evil to baseline acceptable.
> 
> But we also have alternatives to avoid the complication altogether.

That linked thread is about the fact the proxy set `initial=True` and Synapse used `limited=True`, and was resolved by introducing `expanded_timeline` flag. Yes, the fact that the proxy used `initial=True` (which we think was a bug?) was pretty bad, but I wouldn't accidentally used the phrase "evil". 

Still, as I see it there are two main issues with the current proposal:
1. You duplicate some of the events. This is annoying, and it'd be nice if we could instead change the API shape so that sync could say "these events go at the back of this timeline chunk". This is still a problem with using multiple initial syncs.
2. Potential complexity for clients. This is a valid concern, though conceptually it's relatively straightforwards: if you see `expanded_timeline` set you *replace* (rather than add to) the current timeline chunk with what is returned. However this obviously may not be as straightforwards in practice depending on how the clients are designed.

But as you say, we have a baseline acceptable solution that is implemented and tested. We have some alternatives, though all with some downsides (e.g. doesn't support all use cases, is racy, or isn't specced/implemented yet). From my PoV it feels like the right thing to do is accept what we have and land it, the alternatives are stripping out the feature we have or further indefinitely delaying the MSC.

2025-10-07 14:16 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +The endpoint is a `POST` request with a JSON body to `/_matrix/client/unstable/org.matrix.simplified_msc3575/sync`.
Oops :facepalm:

2025-10-07 14:17 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +The endpoint is a `POST` request with a JSON body to `/_matrix/client/unstable/org.matrix.simplified_msc3575/sync`.
Fixed

2025-10-07 14:18 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
Can you be more specific about what downsides should be?

2025-10-07 14:33 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
@bnjbvr 

> Even after re-reading the text of the MSC a few times, I don't understand the goal of the `expanded_timeline` flag; does it mean that there _might_ be duplicates? As noted in a previous comment in this thread, clients have to handle duplicates anyways (b/o the `timeline_limit` increasing use case to start with, and then to deduplicate results from /messages which used previously persisted pagination tokens). Maybe the `expanded_timeline` flag is a hint?

The idea is that you can tell the server to (try and) ensure the client has an appropriate amount of history automatically. The main example use is to have it so that the top 20 rooms automatically have more history, so that when users open the room they'll always have a screenful of messages, while only fetching one or two messages for the older rooms which are less likely to be opened. This behaviour can be mimicked by doing `/messages`, though this has generally  been slower to call (especially if you try and do 20 rooms at once), so the main advantage is speed.

The `expanded_timeline` is there to tell clients they should *replace* the current timeline chunk with what has come down sync, essentially. For example, if a room has three events `[A, B, C]` and initially the room is in a list with `timeline_limit=1` then the client would receive just `[C]`, if a new vent `D` came in and caused it to enter a list with `timeline_limit=20` then the server would return the room with `expanded_timeline=true` and events `[A, B, C, D]`.


> Overall, I'd love to see more guidance for clients, with respect to when is it better to expand the `timeline_limit`, or when is it better to use `room/ROOM_ID/messages` for back-paginations. For instance, if a client wants to compute the unread status of a room, then, because of e2ee rooms, they may have to back-paginate up to the previous read receipt target event (if there's a gap in the timeline). In this case: should we rather use `room/ROOM_ID/messages` (and send one request for _each_ room), or use custom lists with an expanded `timeline_limit` (the naivest way being increasing the `timeline_limit` for _all_ rooms)?

Yeah, I think the guidance would be basically to use different `timeline_limit` with different lists, but otherwise if you want to paginate you should be using `/messages`. While you *could* keep increasing the `timeline_limit`, you'd repeatedly get the same events down after each increase.

2025-10-07 14:46 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
@bnjbvr no, sync will never wait to backfill from other servers. Instead it may return fewer than the requested number of events (and have `limited=True`).

2025-10-07 14:46 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
@MadLittleMods I think the exact ordering of events is an implementation detail for the server?

2025-10-07 14:49 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +1. Add `set_presence` URL param.
While the sync v2 clause combined with this line both seem to imply that `set_presence` is a query parameter, only body parameters seem to be specified in the MSC, and observation from ElementX is that `set_presence` is a body parameter.

As a corollary, the same version of EX sends me `timeout` and `pos` as query parameters rather than in the body.

Is it safe to say **all** query parameters are eliminated and all implementations should be brought in line with that going forward?

2025-10-07 15:22 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. Add `set_presence` URL param.
Ah yup, all query params have moved. This changelog entry was from before we moved everything to query params

2025-10-07 15:43 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
:shrug: Feels like there is something missing.

When `initial: true` or `expanded_timeline: true`, the timeline events should be a linearized version of the DAG (partial ordering in the event graph) (like `/messages`).

Otherwise "in the order they were received by the server"

Related spec issue: https://github.com/matrix-org/matrix-spec/issues/1917

2025-10-07 16:26 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `[string]` | No | The name of the lists that match this room. The field is omitted if it doesn't match any list and is included only due to a subscription. |
This is already listed above in the common fields

2025-10-07 16:40 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
@jevolk Simplified Sliding Sync still addresses massive pains (see the MSC introduction) and is great improvement over the normal `/sync`.

As originally proposed, Simplified Sliding Sync never had bandwidth optimizations like the previous [MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575) Sliding Sync. Some bandwidth optimizations (sticky `lists` in requests) were just *recently* proposed which I think are a half-baked attempt at addressing the general concern.

As mentioned earlier, a bandwidth optimized version is relevant. The biggest concern isn't with sticky state itself but that it was being applied with a shotgun to one field while missing others that have just as much bulk. If the goal is to land the MSC soon, best to leave that for the future so we can actually address the problem holistically instead of a few shotgun optimizations that may make it harder to address in the future and more complex in the mean-time.

The specific issue about [response bulk](https://github.com/element-hq/synapse/issues/18517) is not relevant with this iteration of the MSC. The previous version (the current implementation in Synapse) has an ever present list of *all* matching room ID's which can be quite bulky. I was using that issue as a example point of comparison for why request/response bulk isn't the end of the world (we *have* been operating with it for the past year). The MSC has now switched to specifying which `lists` a particular room has matched individually (which was also [suggested in the issue](https://github.com/element-hq/synapse/issues/18517#issuecomment-2949520461)).

2025-10-07 16:56 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
I think it could simply be changed to the following since I don't think those downsides are true.

```suggestion
Another alternative is for the client to simply use another initial sync
request with a higher `timeline_limit`. This approach naturally handles
multiple rooms in a single request and, like the sync timeline, avoids
backfilling over federation. The client should not request any state
(`"required_state": {}`) as we only care about getting timeline events with
this request.
```

2025-10-08 12:19 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
> When `initial: true` or `expanded_timeline: true`, the timeline events should be a linearized version of the DAG (partial ordering in the event graph) (like `/messages`).
> 
> Otherwise "in the order they were received by the server"

Neither of these actually defines a single ordering. For DAG ordering you can have multiple different topological orderings, and for "received by server" can depend on what you mean by "server". If you have full active HA, then ordering can depend on which instance you hit, as each instance may receive events from other instances in different orders.

2025-10-08 14:49 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
I understand but whatever the distinction is and how we want to describe it. Historical order vs stream order.

2025-10-10 02:11 UTC, uhoreg commented on proposals/4186-simplified-sliding-sync.md
> +received" the last event in the room, however the preside definition depends on the server architecture, especially for
nit:

```suggestion
received" the last event in the room, however the precise definition depends on the server architecture, especially for
```

2025-10-10 02:11 UTC, uhoreg commented on proposals/4186-simplified-sliding-sync.md
> +Room members can be lazily-loaded by using the `lazy_members` flag is set. Typically, when you view a room, you want to
nit:

```suggestion
Room members can be lazily-loaded by using the `lazy_members` flag. Typically, when you view a room, you want to
```

2025-10-10 02:11 UTC, uhoreg commented on proposals/4186-simplified-sliding-sync.md
> +1. All the `senders` of events in `timeline_events` unless previously returned. This ensures that the client can render
Should it send a member event if the a member event was already sent, but has changed? (e.g. if the member changed their avatar)  The wording is unclear whether it should do so or not.

2025-10-10 09:12 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. All the `senders` of events in `timeline_events` unless previously returned. This ensures that the client can render
Yes it should, I'll clarify.

2025-10-10 09:16 UTC, erikjohnston commented
While not everything has been implemented, the vast majority of it has been. I believe that the stuff not implemented are either a) sufficiently minor to not worry about, or b) features that we have in sync v2 and so know are implementable server-side.

@mscbot resolve Pending complete implementation (action: remove needs-implementation label)

2025-10-10 09:21 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
I don't believe the spec currently differentiates between those orders, and it is somewhat a Synapse thing that we do it that way. I don't think mandating an event ordering here is going to be helpful.

This is certainly something that would be good to try and better spec/explain more generally

2025-10-10 09:23 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
You can't use empty state, as you need to a) get the member state for all timeline events so you can render them, and b) you want to continue syncing based on the second request, which means you need to specify the `required_state` you want

2025-10-10 18:04 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
> a) get the member state for all timeline events so you can render them

Not necessary for all clients (up to the client).

> b) you want to continue syncing based on the second request, which means you need to specify the `required_state` you want

I can do a one-shot initial sync request to get timeline events.

2025-10-10 18:08 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
(discussion should be unresolved)

The spec does have words about this (see the linked issues).

For example:

> Events are ordered in this API according to the **arrival time of the event on the homeserver**. This can conflict with other APIs which order events based on their **partial ordering in the event graph**. This can result in duplicate events being received (once per distinct API called). Clients SHOULD de-duplicate events based on the event ID when this happens.
>
> *-- 7.6 Syncing, https://spec.matrix.org/v1.14/client-server-api/#syncing*

2025-10-10 18:22 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
I guess this sorta already has this :white_check_mark: :

> The last event in the list is the most recent.

2025-10-10 18:44 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
There is something in the MSC about this:

> If `limited` is true then we include bundle aggregations for the event, as per sync v2.

But I think there are a few more details to figure out here.

MSC2675 says we should only do this for `limited` **initial** syncs (when events are returned in topological order, see other [discussion for clarifying message order](https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2408805237)):

>   - `GET /sync`, only for room sections in the response where `limited` field
>     is `true`; this amounts to all rooms in the response if 
>     the `since` request parameter was not passed, also known as an initial sync.

We should clarify to only bundle aggregations when `initial: true` and `limited: true`. This also aligns with the "inclination to not [bundle aggregations] given that sync is returning new events and any relations to those events would come after it by their nature (and already be in the response or the next one)."

2025-10-10 18:51 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // event _except_ for @alice:example.com, and include every other state event.
To give this an update, `required_state` was simplified to have `include`/`exclude` fields (see `RequiredStateRequest` in the MSC).

2025-10-10 18:52 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      // In addition, ["*", "*"], ["m.space.child", "*"] is an error, the m.space.child filter is not
To give this an update, `required_state` was simplified to have `include`/`exclude` fields (see `RequiredStateRequest` in the MSC).

2025-10-10 18:54 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
The `pos` query parameter was moved to the request body :white_check_mark:

2025-10-10 18:56 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      "required_state": [ ... ],
`$ME` and `$LAZY` have been removed from the MSC :white_check_mark: 

Lazy-loading membership is now simply controlled by `required_state` -> `lazy_members: true`

2025-10-10 18:59 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `is_encrypted` | `[string]` | No | Flag which only returns rooms which have an `m.room.encryption` state event. <br/><br/> If unset, both encrypted and unencrypted rooms are returned. If `False`, o
This was updated :white_check_mark:

2025-10-10 19:02 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `room_name_like` | `string` | No | Filter the room name. <br/><br/>Case-insensitive partial matching e.g 'foo' matches 'abFooab'. The term 'like' is inspired by SQL 'LIKE', and the text here is sim
As an update here, `room_name_like` was removed from the MSC.

Dubious usefulness and was never implemented in Synapse.

2025-10-10 19:09 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
This was updated to the following:

> Rooms are ordered by last activity, based on when the last event in the room was received by the server. The exact ordering is determined by the server implementation. (Typically, this would be essentially based on when the "server received" the last event in the room, however the precise definition depends on the server architecture, especially for servers that are "distributed").

2025-10-10 19:14 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
This now has a clarification about not using `bump_stamp`:

> [!Important]
> Rooms are ***not*** ordered by "`bump_stamp`", a field returned in the room response.

But we could still explain *why* "Rooms are ordered by last activity", see the first reply in this discussion.

2025-10-10 19:19 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +response.
I think the information is there now for the most part :white_check_mark: 

We have to assume that timeline events adhere to normal history visibility rules.

2025-10-10 19:23 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +#### Joined/left/banned
This section was updated to `Currently or previously joined rooms` :white_check_mark:

2025-10-14 14:56 UTC, turt2live commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
> Would adding a flag to `/mesages` to _not_ backfill be useful?

https://github.com/matrix-org/matrix-spec-proposals/pull/4282 discusses this idea, fwiw.

2025-10-14 15:27 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +offline, and clients cannot opt-out of a large amount of extraneous data such as receipts. On large accounts with
I guess this doesn't need to block the MSC, but indeed, "clients cannot opt-out of ... receipts" appears to be factually incorrect.

2025-10-14 19:51 UTC, richvdh requested changes
A partial review up to the end of "request body".

Sorry, a collection of nits and things that I'd really like discussion on.

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +- Don’t incremental sync rooms you don’t care about.
there's a jarring transition from "should" to imperative voice here

```suggestion
- The API should support lazy-loading of things like membership and read receipts (and avoid sending unnecessary data to the client).
- The API should support informing the client when room state changes from under it, due to state resolution.
- Clients should be able to work correctly without ever syncing in the full set of rooms they’re in.
- Incremental sync responses should only include rooms that the user cares about.
```

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +# Proposal
[This thread needs resolution]

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +  "pos": "<opaque string>",
For reference, the relevant section of the spec is [here](https://spec.matrix.org/v1.14/appendices/#pagination). It's worth noting that the same section of the spec mandates that `next_batch` be a query-parameter, whilst apparently we have deliberately made `pos` be a body parameter, for CORS reasons.

More generally, I feel that this is sufficiently different from regular pagination that the arguments for using the same terminology are weak. In essence: with "pagination" the expectation is that the client is working through a relatively *static* set of data; here the reason that the server did not return more data was not that there was too much of it, but rather that the data *did not exist yet*.

Considering a change to `from` and `next_batch`: I am -0. I'd not block such a change, but I don't think it's necessary.

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +Specifically, a room matches a given list if after filtering the server maintained list of rooms by the list's filters,
```suggestion
Specifically, a room matches a given list if after filtering the server-maintained list of rooms by the list's filters,
```

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +received" the last event in the room, however the precise definition depends on the server architecture, especially for
the quotes here seem confusing?

```suggestion
ordering is determined by the server implementation. (Typically, this would be essentially based on when the server
received the last event in the room, however the precise definition depends on the server architecture, especially for
```

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +Subscriptions are a rule that matches against a specified room ID, i.e. they allow the client to specify that a
```suggestion
A subscription is a rule that matches against a specified room ID, i.e. they allow the client to specify that a
```

(or "Subscriptions are rules that...")

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +previously been sent to the client).
```suggestion
A room is returned in the response if it matches at least one rule, and either there is new data to return, or the room has
not previously been sent to the client.
```

I think?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +The server MUST not send any room information down that the user does not have permission to see. Specifically, the
```suggestion
The server MUST NOT send any room information down that the user does not have permission to see. Specifically, the
```

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +handles the config differently.
Presumably the new config doesn't have to be a strict superset for this logic to apply? For example, timeline limit might increase while required state decreases?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +ignore this behaviour if the server knows it has previously sent down all of the latest `N` events.
> SHOULD ... send down the latest `N` events, even if some of those events have previously been sent.

vs

>  MAY ignore this behaviour if the server knows it has previously sent down all of the latest `N` events.

These feel somewhat contradictory. Is the point that if, say, N=10 and the server has sent events 0-4 and 6-9, then it must still send all 10 events?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +ignore this behaviour if the server knows it has previously sent down all of the latest `N` events.
Given it's the server doing this behaviour, it seems hard for it to ignore the behaviour.

```suggestion
ignore this requirement if the server knows it has previously sent down all of the latest `N` events.
```

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +the latest one.
> the server MAY remember that it has already sent the previous 10 events and only return
the latest one.

To clarify: this is not part of the `expanded_timeline` behaviour, right? `expanded_timeline` does not apply in this case, because the timeline limit is *reducing*. So the server doesn't *need* to remember that it has already sent the previous 10 events: the only event that matters is the last 1 (which it has not yet sent).

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `set_presence` | string | No | Same as in sync v2, controls whether the client is automatically marked as online by polling this API. <br/><br/> If this parameter is omitted then the client is auto
other values are treated the same as an omission? Cause a 400?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). The list keys should be arbitrary strings which the client is using to refe
> arbitrary strings

are NUL characters (`\u0000`) allowed?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `state_key` | `string` | No | The event state key to match. If omitted then matches all state keys. |
I see that the meaning of a `state_key` without a `type` has already been discussed, but I came here with the same question. I think it would be good to clarify that it *is* a thing that is supported, even if we don't have a meaningful usecase for it.


```suggestion
| Name | Type | Required | Comment |
| - | - | - | - |
| `type` | `string` | No | The event type to match. If omitted then matches all types. |
| `state_key` | `string` | No | The event state key to match. If omitted then matches all state keys. |

Note: it is possible to match a specific state key, for all event types, by specifying `state_key` but leaving `type` unset.
It is unclear if there is any particular usecase for this, but servers must support it.
```


(alternatively, let's clarify that they don't have to support it and clients should not rely on it. I don't have a particularly strong opinion, but let's do one or the other.)

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +can send the following:
some text missing here?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +1. All membership updates since the last sync when `limited` is false (i.e. non-gappy syncs). This allows the client to
> All membership updates since the last sync when `limited` is false

I don't entirely understand this. If `limited` is false, won't all the state transitions be included as part of the timeline anyway?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +1. All membership updates since the last sync when `limited` is false (i.e. non-gappy syncs). This allows the client to
It's worth mentioning that synapse currently does the *opposite* for /v3/sync: it sends all membership updates when `limited` is *true*, and that Element-Web relies on that behaviour (https://github.com/element-hq/element-web/issues/27285). It would be good to be explicit that we consider Element Web's behaviour faulty in this case.

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +waiting for a change (aka long-polling, like sync v2).
Please can we avoid referring to "sync v2"? "Sync v2" is not a term that exists in the Matrix spec: it is `/v3/sync`, and most current users of the API (including, for example, [Ruma](https://docs.rs/ruma/latest/ruma/api/client/sync/sync_events/index.html)) know it as that, not having been here in 2016 when we were designing it.

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +memberships](https://spec.matrix.org/v1.16/client-server-api/#lazy-loading-room-members) in sync v2. When specified, the
`/v3/sync` has some [special behaviour](https://spec.matrix.org/v1.14/client-server-api/#get_matrixclientv3sync) regarding the syncing user's own membership event: 

> servers MUST include the syncing user’s own membership event when they join a room, or when the full state of rooms is requested

(though, per https://github.com/matrix-org/matrix-spec/issues/942#issuecomment-1339798503, there is lack of clarity around that.)

Anyway: could you clarify whether or not this special behaviour for the syncing user's own membership is carried across to SSS?

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `is_dm` | `bool` | No | Flag which only returns rooms present (or not) in the DM section of account data.<br/><br/> If unset, both DM rooms and non-DM rooms are returned. If False, only non-DM room
```suggestion
| `is_dm` | `bool` | No | Flag which only returns rooms present (or not) in the `m.direct` entry in account data.<br/><br/> If unset, both DM rooms and non-DM rooms are returned. If False, only non-DM rooms are returned. If True, only DM rooms are returned. |
```

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `is_invite` | `bool` | No | Flag which only returns rooms the user is currently invited to. <br/><br/> If unset, both invited and joined rooms are returned. If `False`, no invited rooms are returne
I don't disagree, but it's not the world's biggest problem, and I'd like to see this MSC get merged before the heat-death of the universe.

+0.5 to renaming it to `is_invited`

2025-10-14 19:51 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `is_invite` | `bool` | No | Flag which only returns rooms the user is currently invited to. <br/><br/> If unset, both invited and joined rooms are returned. If `False`, no invited rooms are returne
```suggestion
| `is_invite` | `bool` | No | Flag which only returns rooms the user is currently invited to. <br/><br/> If unset, both invited and joined rooms are returned. If `false`, no invited rooms are returned. If `true`, only invited rooms are returned. |
```

2025-10-14 19:52 UTC, richvdh commented
@mscbot concern unresolved threads

2025-10-20 16:25 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      ],
Cross-link https://github.com/matrix-org/matrix-spec-proposals/pull/4319#discussion_r2445511924

2025-10-24 21:24 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +A server may decide to "expire" connections, either to free resources or because the server thinks it would be faster
Synapse folks, I tried to have a look and I couldn't find an implementation of this clause. I don't know my way around that well so forgive me if so, but if not can this be marked for needing implementation?

2025-10-25 14:06 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
When a user is invited to a room and joins sometime later from a another client, that room gets lost in the rooms list. It has the appearance the app failed to sync the join until something is said.

Therefor my bump types now include `(m.room.member,$ME)`.

To be clear, the spec should explicitly state a bump type is all `m.room.member` events with yourself as the `state_key`

2025-10-28 14:22 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +| `timeout` | int | No | How long to wait for new events in milliseconds. If omitted the response is always returned immediately, even if there are no changes. Ignored when no `pos` is set. |
Non-blocking behavior is a very worthy addition, but it should be achieved through a sentinel value, not by omission. Let's really take a moment on this one...

2025-11-04 13:46 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +offline, and clients cannot opt-out of a large amount of extraneous data such as receipts. On large accounts with
It doesn't block FCP, but it does make the premise weaker that this MSC is needed.

(I'm not arguing the MSC isn't an improvement, but we should make it clear what aspects it is improving instead of false claims.)

2025-11-04 13:49 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +## Extensions
This thread needs resolving.

2025-11-27 13:58 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +ignore this behaviour if the server knows it has previously sent down all of the latest `N` events.
Yup, that's what it means. When a timeline limit increases then it should send down the latest N events, but as a performance optimisation we say the server doesn't need to do so if it knows the client has seen all N events.

Have tried updating the wording and adding an example.

2025-11-27 14:05 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +the latest one.
That is confusingly written, have clarified. 

Basically when room receives a new event it goes to the top of the list, and the timeline limit expands back to 10.

2025-11-27 14:10 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `set_presence` | string | No | Same as in sync v2, controls whether the client is automatically marked as online by polling this API. <br/><br/> If this parameter is omitted then the client is auto
They cause a 400 like in `/v3/sync`. Have updated.

2025-11-27 14:12 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). The list keys should be arbitrary strings which the client is using to refe
Bleurgh, no I suppose we don't want to allow null bytes. How do we normally specify such strings?

2025-11-27 14:22 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. All membership updates since the last sync when `limited` is false (i.e. non-gappy syncs). This allows the client to
> > All membership updates since the last sync when `limited` is false
> 
> I don't entirely understand this. If `limited` is false, won't all the state transitions be included as part of the timeline anyway?

State resets are a thing, so technically you can have a membership change without it appearing in the timeline section.

---

> It's worth mentioning that synapse currently does the _opposite_ for /v3/sync: it sends all membership updates when `limited` is _true_, and that Element-Web relies on that behaviour ([element-hq/element-web#27285](https://github.com/element-hq/element-web/issues/27285)). It would be good to be explicit that we consider Element Web's behaviour faulty in this case.

We decided that we didn't want to have to send *all* membership updates (as there may be *many*) on gappy syncs. The easiest way of doing that is by saying "if limited is true then clients must invalidate their membership cache". Alternatively, we could have a separate `lazy_membership_limited` flag to indicate if there were memberships changes that have happened that we didn't send down, which has the benefit that it makes it much less common that clients need to invalidate their membership caches.

2025-11-27 14:36 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +memberships](https://spec.matrix.org/v1.16/client-server-api/#lazy-loading-room-members) in sync v2. When specified, the
It currently doesn't always include one's own membership. Not sure if we want to keep that behaviour or not?

2025-11-27 14:39 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `state_key` | `string` | No | The event state key to match. If omitted then matches all state keys. |
Have added.

2025-11-27 14:41 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +can send the following:
Oops, there was a missing example there.

2025-11-28 10:30 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +offline, and clients cannot opt-out of a large amount of extraneous data such as receipts. On large accounts with
Have removed

2025-11-28 10:46 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +# Proposal
Current the Synapse implementation will strip out ignored users.

I think if we want to move away from stripping ignored users out then we would also need to do so in things like `/messages` to be useful. If we do want to do that change, I think it'd be better done in a separate MSC where we can figure things out properly. We can always do the change in a backwards compatible way by adding query params to indicate the API endpoints should return events from ignored users.

2025-11-28 10:47 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +A server may decide to "expire" connections, either to free resources or because the server thinks it would be faster
We now expire connections in Synapse https://github.com/element-hq/synapse/pull/19211

2025-11-28 11:11 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `timeout` | int | No | How long to wait for new events in milliseconds. If omitted the response is always returned immediately, even if there are no changes. Ignored when no `pos` is set. |
The behaviour tracks what happens in `/v3/sync`, which I'm not aware of having caused issues.

2025-12-03 09:32 UTC, richvdh requested changes
A few more comments, nothing terribly dramatic

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +server handles the config differently.
I feel like it's unclear what we mean for a field to be a superset of the previous config.

```suggestion
eligible to be returned. If any of the fields have been changed in a way that would cause an expansion
in the events to be returned, then the server handles the change specially, as follows.
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). The list keys should be arbitrary strings which the client is using to refe
https://spec.matrix.org/v1.14/appendices/#opaque-identifiers. Occasionally the length limit is varied (eg [here](https://spec.matrix.org/v1.15/client-server-api/#token-authenticated-registration)), so if you want to stick to 64 bytes (or characters?) you could do so, though I'm not sure there is any need in this case.

Obviously in some cases there's no real harm in having a smiley poo or a ctrl character in your identifier, but there is merit in just having a single grammar that gets used for lots of things, and limiting it to ascii sidesteps the whole "bytes or characters?" thing.

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +```
TODO: check

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +1. All membership updates since the last sync when `limited` is false (i.e. non-gappy syncs). This allows the client to
todo: double-check

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +1. All membership updates since the last sync when `limited` is false (i.e. non-gappy syncs). This allows the client to
> State resets are a thing, so technically you can have a membership change without it appearing in the timeline section. 

Uh, duh, of course they are. I don't know what I was thinking here.

> The easiest way of doing that is by saying "if limited is true then clients must invalidate their membership cache"

Yup, seems to make sense. Do we know if that is what EX does today?

Anyway, my point in raising it is mostly that I think we should probably say this in the text.

```
Note that the fact that membership updates are *not* necessarily sent when `limited` is true means that clients must flush any "membership" cache when `limited` is true. This is in contrast to Synapse's implementation of lazy-loading in `/v3/sync`.
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +memberships](https://spec.matrix.org/v1.16/client-server-api/#lazy-loading-room-members) in sync v2. When specified, the
If we've got this far without including it, let's stick with that, since it makes the API more consistent.

Again though, I think it's worth calling out as a difference to /v3/sync.

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `is_invite` | `bool` | No | Flag which only returns rooms the user is currently invited to. <br/><br/> If unset, both invited and joined rooms are returned. If `False`, no invited rooms are returne
it's been renamed; resolving this thread.

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +requests, see below for the semantics.
```suggestion
requests: see ["Combining room configs"](#combining-room-configs) below for the semantics.
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +- Required state — take the union of the required state fields, i.e. if a state event would be returned by any room
Since these refer to specific fields in `SyncListConfig` (I believe?), let's use those names:


```suggestion
- `timeline_limit` — take the maximum timeline limit across all room configs.
- `required_state` — take the union of the required state fields, i.e. if a state event would be returned by any room
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +#### Timeline events
```suggestion
#### Changes to `timeline_limit`
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +#### Required state
```suggestion
#### Changes to `required_state`
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently does not return rooms with expanded state immediately, instead waits for the next update.
```suggestion
> Synapse currently does not return rooms with expanded state immediately; instead it waits for the next update.
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +the server SHOULD return `A`, `B`, `C` and `D`, but if the client increases it instead to 3 then server does not need to
```suggestion
the server SHOULD return `A`, `B`, `C` and `D`. If the client instead increased `timeline_limit` to 3, then the server would not need to
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +If the server does send down extra events, it MUST set the `expanded_timeline` to `true`.
I'm struggling to grok what we mean by "extra" here. I think it's this?


```suggestion
If the server does return events that predate the last time the room was sent to the client, it MUST set the `expanded_timeline` to `true`.
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +These fields are always included no matter the membership.
except for `membership`, which is omitted if the membership is `leave`?

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +All fields in this section may be omitted. When `initial` is set to `false` then an omitted field means that the field
>  All fields in this section may be omitted.

The table below claims that `bump_stamp` is required.

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
It's not the same, because the format is different. Maybe you mean "the same users"?


```suggestion
| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left users: the same users as the `m.heroes` section in the [`/v3/sync` specification](https://spec.matrix.org/v1.16/client-server-api/#get_matrixclientv3sync_response-200_roomsummary) |
```

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `num_live` | `int` | No | The number of timeline events which have "just occurred" and are not historical, i.e. that have happened since the previous sync request. The last `N` events are 'live' an
Doesn't this make `expanded_timeline` redundant?

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +      // An opaque integer that can be used to sort the rooms by "Bump Stamp"
I don't think we need to specify this here. The current spec has references to integers: it is generally understood that you need to stay within `[-(2**53)+1, (2**53)-1]` in case the impl on the other end uses an IEEE754 float to represent the number. 

There's an argument that clarifying words should be added to the spec appendix (PRs welcome), but I don't think it should be part of this MSC.

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
is it legit for two events (in the same room? in different rooms?) to have the same `bump_stamp`?

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
Hrm. In that case, it feels like we should leave it out of the spec, and only spec it once we know it can be implemented.

[I see this is listed as one of the "Open questions".]

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +### `StrippedHero` type
why is this a `StrippedHero` rather than just a `Hero`, ooi?

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +> Knock support hasn't been implemented in Synapse.
I'm pretty sure it has.

Is this talking specifically about knock support in SSS?

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
With the exception of "should we remove `highlight_count` and `notification_count`", I feel like the anser to most of these is just "let's just spec what we have".

2025-12-03 09:32 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +1. We should add `knock_servers` as per MSC4233, if that lands.
It has not, so let's not.

2025-12-03 09:34 UTC, richvdh commented
There are still lots of open threads on this MSC.

2025-12-03 20:32 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
It might be nice to delegate `heroes` to an extension so we can evolve this logic as we wish.

While "heroes" and [calculating a room display name](https://spec.matrix.org/v1.16/client-server-api/#calculating-the-display-name-for-a-room) are pretty established part of the spec, it's a very specific/narrow way to do things.

Just as an example of something up for interpretation that's mentioned in the spec:

> Clients SHOULD use minimum 5 heroes to calculate room names where possible, but may use more or less to fit better with their user experience.

And as an example of evolving things, a future MSC could expand the hero extension to have an option to specify the number of heroes. Currently, Synapse will only ever return up to 5.

Or a client might not care about `heroes` at all, in which case, they don't need to enable the hero extension at all.

2026-01-27 16:33 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +These fields are always included no matter the membership.
Have clarified in 2b969b0a

2026-01-27 16:37 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +All fields in this section may be omitted. When `initial` is set to `false` then an omitted field means that the field
ec5a5405

2026-01-28 11:43 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). The list keys should be arbitrary strings which the client is using to refe
d34d7d69

2026-01-28 11:45 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. All membership updates since the last sync when `limited` is false (i.e. non-gappy syncs). This allows the client to
fea5bf82

2026-01-28 11:51 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +Memberships returned to the client due to `lazy_members` are *not* filtered by `exclude`.
Have noted its fairly arbitrary in 1fade2f1

2026-01-28 20:32 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +1. All membership updates since the last sync when `limited` is false (i.e. non-gappy syncs). This allows the client to
Related conversation, https://github.com/element-hq/synapse/pull/19206#discussion_r2550944612

2026-02-04 14:15 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +## Extensions
Given this should be easy to add later, I've added a note to say we don't currently support it. 68f16e86

2026-02-04 14:19 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +### `StrippedHero` type
Ermh, not sure there is any reason thinking about it. I guess it comes from the fact that it isn't an actual member event maybe?

2026-02-04 14:21 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +   trickling" section.</del>
We shouldn't have `unstable_` prefixed fields in the stable API, they should either be stabilised or removed. The current state of the MSC is that gets stabilised

2026-02-04 14:33 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +> Knock support hasn't been implemented in Synapse.
Hmm, yeah I think it *is* implemented, we just don't currently correctly return the correct state in Synapse as previously we only returned `invite_state`.

Removing.

2026-02-04 14:37 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
Given this seems to be needed for EW support and there is an open PR, I'm minded to keep it *unless* we decide that EW should instead calculate all notifications client side. Otherwise we block EW support on doing another MSC

2026-02-04 14:43 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `num_live` | `int` | No | The number of timeline events which have "just occurred" and are not historical, i.e. that have happened since the previous sync request. The last `N` events are 'live' an
Hmhmhmhmh, I guess it'd probably though I'm slightly wary of overloading `num_live`.  `expanded_timeline` explicitly means that the returned block of events should replace the current timeline chunk, whereas `num_live` is more geared towards "which of these events should you notify for". In practice though `num_live` should only indicate if there are non-live events if either a) `initial` is true or, b) `expanded_timeline` is true.

2026-02-04 15:01 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `pos` | `string` | Yes | The next position token in the sliding window to request. |
Yeah, we should make `pos` be usable for other endpoints (if its not already). Added it in 40855ba1

2026-02-04 15:07 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
> > a) get the member state for all timeline events so you can render them
> 
> Not necessary for all clients (up to the client).

But the vast majority of clients in use do render display names rather than user IDs. That makes the one-shot proposal unusable by most clients?


> > b) you want to continue syncing based on the second request, which means you need to specify the `required_state` you want
> 
> I can do a one-shot initial sync request to get timeline events.

Again, I feel like doing a separate one-shot initial sync request that is divorced from your ongoing sync is going to risk all sorts of race conditions.

2026-02-05 14:20 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +memberships](https://spec.matrix.org/v1.16/client-server-api/#lazy-loading-room-members) in sync v2. When specified, the
8c9ae995

2026-02-05 14:28 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
16b4852c

2026-02-10 00:00 UTC, frebib commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
An issue found in the wild that I think would be good to explicitly address here https://github.com/element-hq/synapse/issues/19447

2026-02-10 14:37 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +`conn_id` set in the request.
@erikjohnston This is up to you, it would likely be a big churn though and I'm not sure I have any better ideas. 🤷

2026-02-10 14:37 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +`conn_id` set in the request.
@erikjohnston This is up to you, it would likely be a big churn though and I'm not sure I have any better ideas. 🤷

2026-02-10 16:25 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
In reality, clients can't do [historical profiles](https://spec.matrix.org/v1.16/client-server-api/#displaying-membership-information-with-messages) correctly with the information we give them. That would require the resolved current state after each event in the timeline. Right now with `required_state`, rooms only get the resolved current state at the end of the timeline chunk.

Clients can do just as good as job as they do today with this alternative.

A client may also choose to use the `/profile` information instead.

2026-02-10 20:48 UTC, cloudrac3r commented on proposals/4186-simplified-sliding-sync.md
> +`conn_id` set in the request.
Must conn_ids be unique across all of a user's devices? If so, how can clients make sure they use a conn_id that does not conflict with another device?

2026-02-18 14:00 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +`conn_id` set in the request.
The `conn_id` is scoped to that user/device. Have clarified in 1ce0bc13

2026-02-18 14:07 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
Good point, have clarified by linking to the spec section in 36bb63c9

2026-02-18 14:11 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
I'm not a fan of punting this to an extension, given that it is very fundamental to how one actually displays the room in the room list. Different clients really all should be showing the same name for a given room, otherwise it will cause a lot of confusion.

2026-02-18 14:25 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
> In reality, clients can't do [historical profiles](https://spec.matrix.org/v1.16/client-server-api/#displaying-membership-information-with-messages) correctly with the information we give them. That would require the resolved current state after each event in the timeline. Right now with `required_state`, rooms only get the resolved current state at the end of the timeline chunk.

This isn't to do with historical profiles, but lazy membership. The initial SSS with state won't necessarily include the memberships required to render the timeline events returned in the oneshot initial sync. I guess one could do lots of `/profile` requests but that will be relatively slow if (in the common case) a lot would need to be done.

2026-02-18 16:55 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
> The initial SSS with state won't necessarily include the memberships required to render the timeline events returned in the oneshot initial sync.

It seems like this would work: `"required_state": { "lazy_members": true }`

2026-02-26 16:44 UTC, reivilibre commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
Are we happy with this condition being 'if the room name is not set'
and not 'if both the room name and canonical alias are not set'

This question was also on MSC3575 at https://github.com/matrix-org/matrix-spec-proposals/pull/3575#discussion_r1671260153

and rightfully raised again in https://github.com/element-hq/synapse/pull/19468/changes#diff-c0aad0e609657962388a061f32f125ce5a28e8fa5b43be3b6aca679b68a1e76cR907

2026-03-05 20:33 UTC, gingershaped reviewed
A few clarifying questions.

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +A `pos` token can be used in `/messages` and `/relations` APIs.
The `prev_batch` is described further down for use with `/messages`. Is `pos` supposed to supplement `prev_batch`? Is `prev_batch` supposed to work with `/relations` as well?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +| `timeout` | int | No | How long to wait for new events in milliseconds. If omitted the response is always returned immediately, even if there are no changes. Ignored when no `pos` is set. |
Is the behavior of `timeout=0` the same as not specifying `timeout`?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +and banned rooms as a) this should be uncommon, and b) the user may not have seen that they've been kicked/banned from
If a user is banned or kicked from a room, does this mean that the room will be repeatedly synchronized until activity in other rooms pushes it out of the `range` window?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +A "list" is then a set of filters (e.g. only match invites, or DM rooms, etc) plus a "range" that indexes into the
Do filters apply to banned/kicked rooms?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +| `range` | `[int, int]` | No | Sliding window range. If this field is missing, no sliding window is used and all rooms are returned in this list. Integers are *inclusive*, and are 0-indexed. (This i
Does "all rooms" mean "all rooms where the syncing user has a membership event"? Also, presumably filters are still applied even if `range` isn't specified?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +matches any of them, or b) merge the fields together, however care must be taken to correctly account for wildcards.
Does "wildcards" mean in the glob sense, or in the sense of `RequiredStateElement` objects without a `type` or `state_key` property?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +| `count` | `int` | Yes | The total number of entries in the list. |
Does this refer to the length of the list before filters and the sliding range are applied?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +| `name` | `[string \| null]` | No | Room name or calculated room name. `null` if room name has been removed c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname |
What does "calculated room name" mean? I thought clients were supposed to calculate the room name using `heroes`.

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +| `avatar` | `string` | No | Room avatar |
Does an empty string indicate that the avatar has been removed? If so, should this also accept `null`, as `name` does?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +| `is_dm` | `bool` | No | Flag to specify whether the room is a direct-message room (according to account data). If absent the room is not a DM room. |
Presumably this should be sent in non-`initial` syncs if the corresponding account data field changes?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +The reason the full fields from the previous section can't be included is because we don't have any of that information
Is including those fields explicitly forbidden? Presumably some of them (like `is_dm` for invites, possibly `initial`) should be included.

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +The server MUST NOT send any room information down that the user does not have permission to see. Specifically, the
This sounds equivalent to the user having a membership state event in the room. Is that correct?

2026-03-05 20:33 UTC, gingershaped commented on proposals/4186-simplified-sliding-sync.md
> +- `required_state` — take the union of the required state fields, i.e. if a state event would be returned by any room
Presumably this means that `include` and `exclude` are merged together, and `lazy_members` is `true` if any of them are `true`?

2026-03-05 21:02 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +A `pos` token can be used in `/messages` and `/relations` APIs.
Previous discussion, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2349391981

2026-03-05 21:09 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `name` | `[string \| null]` | No | Room name or calculated room name. `null` if room name has been removed c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname |
Previous discussion that was prematurely marked as resolved, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1745966838

2026-03-31 12:27 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +The reason the full fields from the previous section can't be included is because we don't have any of that information
Generally servers can return more fields, though clients will likely ignore them (because they can't be relied on).

2026-03-31 12:27 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +The server MUST NOT send any room information down that the user does not have permission to see. Specifically, the
The exception is that we may want to support explicitly subscribing to "world readable" rooms that the user isn't in (to support peeking)

2026-03-31 12:32 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `timeout` | int | No | How long to wait for new events in milliseconds. If omitted the response is always returned immediately, even if there are no changes. Ignored when no `pos` is set. |
Thanks, clarified in 7282c1a

2026-03-31 12:34 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +and banned rooms as a) this should be uncommon, and b) the user may not have seen that they've been kicked/banned from
Thanks, clarified in 75504c7 and 4cfcefe.

The phrase "..will always be included" is not helpful there. The intention is to say that they are included in the aforementioned server list, which then gets filtered etc. So no, the room will only be included once (or if there are any further changes that need to be synced).

2026-03-31 12:34 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +A "list" is then a set of filters (e.g. only match invites, or DM rooms, etc) plus a "range" that indexes into the
Thanks, clarified in 75504c7 and 4cfcefe.

2026-03-31 12:34 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `range` | `[int, int]` | No | Sliding window range. If this field is missing, no sliding window is used and all rooms are returned in this list. Integers are *inclusive*, and are 0-indexed. (This i
Thanks, clarified in 75504c7 and 4cfcefe.

By "all rooms" we mean "don't apply a range filter to the set of rooms".

2026-03-31 12:35 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +matches any of them, or b) merge the fields together, however care must be taken to correctly account for wildcards.
Ah, the term "wildcards" comes from when we actually used `*` etc. Have updated in 91aefbd to indicate it means without `type` or `state_key`

2026-03-31 12:35 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `count` | `int` | Yes | The total number of entries in the list. |
a8af38a

2026-03-31 12:36 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +- `required_state` — take the union of the required state fields, i.e. if a state event would be returned by any room
Yup, clarified in 67e22a8

2026-03-31 16:54 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `is_dm` | `bool` | No | Flag to specify whether the room is a direct-message room (according to account data). If absent the room is not a DM room. |
Yup, 4445f164

2026-03-31 16:58 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `avatar` | `string` | No | Room avatar |
99084dfa clarifies that it can be null if the avatar was removed

2026-04-01 13:16 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +      // The room name, if one exists. Only sent initially and when it changes.
Removed the mention of calculated room name 66f84026baa47acb4713432a9a5b9868da72713d

2026-04-01 13:17 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
Clarify that users should not see rooms they're banned from but were never in 49808783dc51717a3cdfc018a1c3e4ff87bfbd6c

2026-04-01 13:22 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +    "!foo:example.com": {
Clarified how the server should deal with rooms that the user isn't subscribed to and don't exist: a425676ddd0079b056303b2b0d8bf360fc949721

2026-04-01 13:34 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +      "limited:" true|null,
Having bundled aggregation in sync seems odd. However, both Synapse and the [spec](https://spec.matrix.org/v1.18/client-server-api/#aggregations-of-child-events) say to include bundled aggregations when `limited=true`. I think we should be consistent with sync v2, and clean things up in a different MSC if we want to do so.

2026-04-01 15:28 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `name` | `[string \| null]` | No | Room name. `null` if room name has been removed c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname |
We should be more explicit about where this information comes from `m.room.name` (same with `avatar`)

Previous discussion, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1745966838

2026-04-01 16:14 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +Note that for rooms the user has been banned from, but never joined, should not be part of the list.
*Lifting this out of a resolved discussion:*

> How will [forgotten](https://spec.matrix.org/v1.13/client-server-api/#post_matrixclientv3roomsroomidforget) rooms be dealt with here? The old `/sync` doesn't seem to have a way to synchronize forgotten rooms across clients. It'd be nice if SSS could address this.
>
> *-- @Johennes, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1958686158*

2026-04-01 16:16 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +  "rooms": {
Separated @Johennes point on forgotten rooms to https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r3023128340

2026-04-01 16:26 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
I don't think that's accurate. See https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1767493967 / https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1767516414 for a better breakdown

I don't think it's exactly the same as the `lists` either. If you subscribe to a room that you left, it should probably show up.

2026-04-01 16:38 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). The list keys are used by the client to refer to the lists.  <br/><br/> Max
Which error code when we run into `Max lists: 100.`?

2026-04-01 16:38 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +large or expensive to compute.
We should probably specify some limits on the number of `room_subscriptions`. Or at-least some error code that the homeserver can return when it decides it's too much.

`lists` already has a "Max lists: 100.". Related discussion: https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r3023253916

2026-04-01 16:41 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +    "!foo:example.com": {
It looks like the MSC was updated to ignore. We should at-least discuss what we expect a client to show when it tries to subscribe but nothing shows up.

For example, if we take a use case from the MSC, "following a permalink", the client kinda has to flail around and try other endpoints to get some heuristics. The client could show, "Unable to sync information for this room, [try joining]" which could have a spinner and change once the full room list is fetched and we actually know whether the person is joined.

2026-04-01 16:44 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
```suggestion
| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><br/> If `limited` is true then we include bundled aggregations for the event, as per `/v3/sync`. <br/><br/> The last event in the list is the most recent. |
```

Source of truth:

>  This process is referred to as "bundling", and the aggregated relations included via this mechanism are called "bundled aggregations".
>
> *-- [MSC2675](https://github.com/matrix-org/matrix-spec-proposals/pull/2675)*

The spec also mentions "bundled aggregations", https://spec.matrix.org/v1.17/client-server-api

2026-04-01 18:27 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
Created *MSC4445: Clarify `/sync` timeline order* to explore cleaning this up area more explicitly

I think we can still make a decision here based on the spec evidence I've found so far.

2026-04-01 20:27 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
See https://github.com/matrix-org/matrix-spec-proposals/pull/4354#discussion_r3022301207 for some related thoughts on avoiding patch-work bandwidth optimizations.

2026-04-02 22:29 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
likewise, i'd expect that if you subscribe to a room you're not in, you'd try to peek into it (which i think is the current synapse behaviour)?

2026-04-02 22:40 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
yup, it would make sense to only include heroes if we have no alternative to referring to a room than its room_id. So if it has a name or a canonical_alias, clients should use that instead.

The only exception I can think is if a room had no avatar and we wanted to synthesize one from the heroes' avatars. But that hasn't come up in practice, and i would ignore it for now; it can be another MSC.

2026-04-02 22:45 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +that if the user clicks on one of the top rooms the app can immediately display a screens worth of history. (An
```suggestion
that if the user clicks on one of the top rooms the app can immediately display a screen's worth of history. (An
```

2026-04-02 22:46 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +The client *may* decided to reduce the range back to `[0, 19]` (and then subsequently incrementally expand the range),
```suggestion
The client *may* decide to reduce the range back to `[0, 19]` (and then subsequently incrementally expand the range):
```

2026-04-08 10:55 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `name` | `[string \| null]` | No | Room name. `null` if room name has been removed c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname |
I mean, for room name we literally link to the spec? I don't think its anything but noise to say how room names and avatars work, they're not SSS specific and are general matrix concept?

2026-04-08 10:56 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
Peeking has been explicitly descoped from this MSC, given its not been implemented.

2026-04-08 10:59 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +large or expensive to compute.
8b6a6212

2026-04-08 12:42 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListConfig}` | No | Sliding window API. A map of list key to list information (`SyncListConfig`). The list keys are used by the client to refer to the lists.  <br/><br/> Max
ecfc6946

2026-04-08 12:46 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
75f22d77 mentions that the this also can include rooms the user was historically in.

2026-04-08 16:02 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
Feels like we may need an unstable namespaced version of `M_UNKNOWN_POS`

It's only being returned by unstable endpoints but also feels wrong to use an identifier that could mean something else in the future.

2026-04-08 16:07 UTC, richvdh reviewed
I've been through the open threads that are more than a week old, and noted what appears to be outstanding.

I still want to take another look at the changes since my previous review (in December), but I need to take a break.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +      ],
This thread hasn't been resolved.

My impression is that the answer to the question ("Do the `heroes` membership state events need to be included in `required_state` response") is "no", but I'm not certain of that.

In fact... it seems to be one of the "open questions" at the end of the proposal?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +
This thread doesn't appear to have been addressed.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +[MSC3575](https://github.com/matrix-org/matrix-spec-proposals/pull/3575)
Since the extensions are in a different MSC, I think this comment is out of scope. 

I'm going to mark it resolved.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +client in a dedicated extensions block.
I think this is a matter that should be handled in the MSCs for the specific extensions. I think that, if we have a need to tell clients whether a given extension is available, we'll be able come up with some way to do it. AFAIK we don't have that need yet.

@reivilibre are you happy for us to resolve this thread?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently does not return rooms with expanded state immediately, instead waits for the next update.
@clokep are you happy for us to resolve this thread?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
Seems like we've stuck with `bump_stamp`. @clokep are you happy to resolve this thread?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
@clokep are you happy to resolve this thread?

I don't love that we're speccing stuff that isn't implemented (shouldn't it be removed from the MSC?), and the existence of an unmerged, bitrotting MSC is doing little to encourage me. But I'm not going to block the MSC about it.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `is_dm` | `bool` | No | Flag to specify whether the room is a direct-message room (according to account data). |
It looks like this has been clarified now. Will mark as resolved.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
@clokep are you happy to resolve this comment?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +   `heroes` if we are returning membership events?
@MadLittleMods this seems to duplicate an existing thread (https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r1745962353). Can we resolve this one?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +      ],
@MadLittleMods Looks like this thread is informational and doesn't need further action?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `invited_count` | `int` | No |  The number of users with membership of invite. (same as sync v2 `m.invited_member_count`) |
@clokep looks like this thread is informational and doesn't need further action?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
I don't think that explaining *why* we have used a particular ordering is essential.

@MadLittleMods are you happy to resolve this thread?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
> From my PoV it feels like the right thing to do is accept what we have and land it, the alternatives are stripping out the feature we have or further indefinitely delaying the MSC.

I won't pretend to have understood everything in this thread, but this seems fair to me. I'm going to mark this thread resolved. /cc @MadLittleMods .

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
@erikjohnston / @MadLittleMods can you, between you, update the state of this thread?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
@erikjohnston do you intend to address this?

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `avatar` | `[string \| null]` | No | Room avatar, `null` if avatar has been removed. |
```suggestion
| `avatar` | `[string \| null]` | No | Room avatar. `null` if avatar has been removed. |
```

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `num_live` | `int` | No | The number of timeline events which have "just occurred" and are not historical, i.e. that have happened since the previous sync request. The last `N` events are 'live' an
Ok. I wonder if it might be worth noting this in the text, but I don't feel strongly.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
I don't love this at all. But I won't die on this hill.

In any case we have another thread about it (https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2353016460) and I'll resolve this duplicate.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +### `StrippedHero` type
I'd be in favour of renaming the type, otherwise it will get carried into the spec and confuse us forever, but 🤷

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
I think we can resolve this thread.

2026-04-08 16:07 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +A `pos` token can be used in `/messages` and `/relations` APIs.
@erikjohnston can we clarify this?

2026-04-08 16:19 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +   `heroes` if we are returning membership events?
It was to point out the existing conversation on the topic. We can resolve this one and continue there :+1:

2026-04-08 16:24 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +      ],
Correct :+1: 

Created https://github.com/matrix-org/matrix-spec/issues/2353 so this idea isn't lost

2026-04-08 16:31 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
(don't want to resolve yet)

I think the reasoning is important so we can easily understand the factors as future decisions need to be made (not to make it reconstructible with enough archaeology).

2026-04-08 16:49 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +We could implement a bulk `/messages` endpoint, where the client would specify multiple rooms and `prev_batch` tokens.
At the very-least, the alternative needs to be accurately described. Tracked by https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2408702270

2026-04-08 16:53 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `name` | `[string \| null]` | No | Room name. `null` if room name has been removed c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname |
I was more thinking that the "c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname" was referring to the removed behavior as that's how this description evolved and is part of that sentence.

Could be considered good enough but a bit askew :fast_forward:

2026-04-08 16:56 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
@erikjohnston Looks sufficient :fast_forward: 

You kinda have to pull a lot out of those phrases compared to the more clear breakdowns linked above but good enough.

2026-04-14 14:30 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
@MadLittleMods can you mark this thread resolved if you are satisfied?

2026-04-14 14:53 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
I think it is fine, I'm just still cranky about the name. Names are hard.

2026-04-14 14:54 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
I'm a bit confused at why we're deferring threaded notifications to an extension, but not this... if we're not planning to use it.

2026-04-14 14:55 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +| `invited_count` | `int` | No |  The number of users with membership of invite. (same as sync v2 `m.invited_member_count`) |
I was hoping for some insight into why we don't need that. 😄 Definitely not a blocker for this MSC though.

2026-04-14 14:55 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +to preload history for multiple rooms at once, and 2) `/messages` can be slow if it tries to backfill over federation.
I think these ideas have been added to the MSC at this point.

2026-04-14 15:11 UTC, clokep commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently does not return rooms with expanded state immediately, instead waits for the next update.
I think it would be nice to include the ticket to the issue, but not a requirement.

2026-04-14 15:26 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
I'm unable to mark anything resolved or unresolved :crying_cat_face:

2026-04-14 17:35 UTC, richvdh requested changes
A few minor things I'd like us to clarify.

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +  any of the configs have `lazy_members` set to true.
shouldn't this be "*all* of the configs have `lazy_members` set to true", given we are trying to derive the superset, and setting `lazy_members` means we return less data?

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +either be in the room, or be invited/knocked to the room. Otherwise, the room will not be returned in the response.
huh, sadness. Thanks, will resolve.

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `name` | `[string \| null]` | No | Room name. `null` if room name has been removed c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname |
@MadLittleMods could you either make a concrete suggestion, or confirm that you are happy for this thread to be resolved?

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +matches any of them, or b) merge the fields together, however care must be taken to correctly account for configs that
```suggestion
matches any of them, or b) merge the fields together, taking care to correctly account for configs that
```

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `num_live` | `int` | No | The number of timeline events which have "just occurred" and are not historical, i.e. that have happened since the previous sync request. The last `N` events are 'live' an
[not a blocking comment, feel free to resolve]

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +### `StrippedHero` type
[not a blocking comment, feel free to resolve]

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
I really feel like we ought to clarify the state of these "open questions" before we merge the MSC. I don't think that's very hard: maybe give each of the un-`<del>`-eted entries a quick bullet point saying something like "not supporting this for now, maybe in a future MSC".

2026-04-14 17:35 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +Changes from the initial implementation of simplified sliding sync.
I kinda misunderstood what this actually meant, so:

```suggestion
Differences from the experimental implementation of simplified sliding sync in Synapse v1.151.0.
```

(Or pick some alternative release or wording).

2026-04-14 17:47 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `name` | `[string \| null]` | No | Room name. `null` if room name has been removed c.f. https://spec.matrix.org/v1.17/client-server-api/#mroomname |
"good enough" to resolve but there is room for improvement based on author appetite.

(I can't resolve/unresolve any threads)

2026-04-15 07:41 UTC, kegsay commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
Originally, MSC3575 allowed you to sort by notification count, and so this was intended to be a commonly used sort option. As a result, notification counts had to be included in the core protocol so clients could patchup E2EE rooms with correct notification counts which may reorder a subset of rooms.

We have since gone away entirely from the idea of servers providing notification counts (as seen by rust SDK calculating them client-side) which makes the rationale for them being in the core protocol much weaker.

----

That's the "why it is this way", but not the "should it be this way". From a bandwidth perspective, sending 0 counts for every room is awful. From a only-use-the-data-you-need perspective, if clients can happily calculate the count on their own then we shouldn't force server calculated counts down client's throats. As a result, I'm of the opinion that we should move the notification counts out to the same extension as threaded notifications. Given this MSC has diverged from Synapse anyway, this should be a trivial change?

2026-04-15 09:20 UTC, kegsay commented on proposals/4186-simplified-sliding-sync.md
> +Note that for rooms the user has been banned from, but never joined, should not be part of the list.
That could be an extension I think. It's fairly uncommon for clients to want to know about forgotten rooms.

2026-04-28 18:05 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +invites or knocks, but can also be for when the user has rejected an invite.
> but can also be for when the user has rejected an invite.

Do we send [stripped state](https://spec.matrix.org/v1.17/client-server-api/#stripped-state) in this case? I just tried this on element.io's Synapse (Element Web, legacy sync) and received the following upon rejecting an invite:

```json
    "rooms": {
        "leave": {
            "!WXeXzNuPzRWBdIFAEu:matrix.org": {
                "timeline": {
                    "events": [
                        {
                            "content": {
                                "membership": "leave"
                            },
                            "origin_server_ts": 1777399279402,
                            "sender": "@andrewm:element.io",
                            "state_key": "@andrewm:element.io",
                            "type": "m.room.member",
                            "unsigned": {
                                "membership": "leave",
                                "age": 482
                            },
                            "event_id": "$xFTj0wmffLtLTIsi95NsnN63C6ZXauyvozHmcbwl-a4"
                        }
                    ],
                    "prev_batch": "s30728648_1_1715_39292835_10382632_11164603_19362092_55065974_0_4013_2_1",
                    "limited": false
                },
                "org.matrix.msc4222.state_after": {
                    "events": []
                },
                "account_data": {
                    "events": []
                }
            }
        }
    }
```

and on the inviter's side:

```json
  "rooms": {
    "join": {
      "!WXeXzNuPzRWBdIFAEu:matrix.org": {
        "timeline": {
          "events": [
            {
              "content": {
                "membership": "leave"
              },
              "origin_server_ts": 1777399279402,
              "sender": "@andrewm:element.io",
              "state_key": "@andrewm:element.io",
              "type": "m.room.member",
              "unsigned": {
                "age": 0,
                "replaces_state": "$ZrBf3a9-Nk3XvojmAdINjArznS9cgHhF52WxQwozeno",
                "prev_content": {
                  "avatar_url": "mxc://element.io/6130836e26b462a6fe63d4e080dd9d2037490f2b",
                  "displayname": "Andrew Morgan (anoa) {he/him}",
                  "membership": "invite"
                },
                "prev_sender": "@anoa_test:matrix.org",
                "membership": "join"
              },
              "event_id": "$xFTj0wmffLtLTIsi95NsnN63C6ZXauyvozHmcbwl-a4"
            }
          ],
          "prev_batch": "s6917238234_757284974_34742186_4643209905_5404976888_269234723_1609866364_11294605636_0_677600_34_1",
          "limited": false
        },
        "state": {
          "events": [
            {
              "content": {
                "membership": "leave"
              },
              "origin_server_ts": 1777399279402,
              "sender": "@andrewm:element.io",
              "state_key": "@andrewm:element.io",
              "type": "m.room.member",
              "unsigned": {
                "age": 0,
                "replaces_state": "$ZrBf3a9-Nk3XvojmAdINjArznS9cgHhF52WxQwozeno",
                "prev_content": {
                  "avatar_url": "mxc://element.io/6130836e26b462a6fe63d4e080dd9d2037490f2b",
                  "displayname": "Andrew Morgan (anoa) {he/him}",
                  "membership": "invite"
                },
                "prev_sender": "@anoa_test:matrix.org"
              },
              "event_id": "$xFTj0wmffLtLTIsi95NsnN63C6ZXauyvozHmcbwl-a4"
            }
          ]
        },
        "account_data": {
          "events": []
        },
        "ephemeral": {
          "events": []
        },
        "unread_notifications": {
          "notification_count": 0,
          "highlight_count": 0
        },
        "summary": {
          "m.joined_member_count": 1,
          "m.invited_member_count": 0
        }
      }
    }
  }
```

both of which appear to be full state. In this an intentional change in (simplified) sliding sync?

This question spawned from me reading [MSC4319: Room member events for invite and knock rooms in the `/sync` response](https://github.com/matrix-org/matrix-spec-proposals/pull/4319), which has [a line](https://github.com/zecakeh/matrix-spec-proposals/blob/0c0d7311c1874cd7e7f93ec002ba2af16a5690c0/proposals/4319-room-member-events-for-invite-knock-sync-response.md#:~:text=Although%20it%20is%20not%20considered%20a%20dependency%20of%20this%20MSC) asking for Simplified Sliding Sync to include stripped state for invites and knocks (but not rejections of either).

2026-04-29 15:11 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +  any of the configs have `lazy_members` set to true.
Argh, hmm. I think we want:
1. If any room config requests all member events without lazy, i.e. `include: {type: "m.room.member"}` then we include all room members regardless of whether `lazy` is specified anywhere.
2. Otherwise, if any lazy is set, then we'll always include lazy members.
3. Otherwise, no members are returned.

Maybe the right way forwards is `lazy_members` always implies adding memberships. To better support the common case (where you want lazy members and all other state), we say that setting `lazy` implicitly adds an `exclude: {type: "m.room.member"}` ?

2026-04-29 15:55 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
I don't follow the concern. We could add an unstable `M_UKNOWN_POS`... but then we'd still stabilise to `M_UNKNOWN_POS`?

We shouldn't have been using an un-namespaced error code in the implementation, but that ship has sailed.

2026-04-29 16:47 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
> We shouldn't have been using an un-namespaced error code in the implementation

Exactly. We should have an unstable namespaced version of this error in the MSC *Unstable prefix* section

2026-04-29 16:51 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `num_live` | `int` | No | The number of timeline events which have "just occurred" and are not historical, i.e. that have happened since the previous sync request. The last `N` events are 'live' an
This was noted in the MSC via https://github.com/matrix-org/matrix-spec-proposals/commit/5255f81f3e08522913d20e5ed4a323cbbc73c987

2026-05-12 16:02 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse always returns 0 for `notification_count` and `highlight_count`
Seems like we have removed notifications from the MSC, in https://github.com/matrix-org/matrix-spec-proposals/pull/4186/changes/c3111990a759cd54e8a8076aab355468852db5bd

2026-05-12 16:05 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +### `StrippedHero` type
Resolved in https://github.com/matrix-org/matrix-spec-proposals/pull/4186/changes/2fcc60c39c8d36769db91e3b96ef66942489f216

2026-05-12 16:14 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +  any of the configs have `lazy_members` set to true.
> To better support the common case (where you want lazy members and all other state), we say that setting `lazy` implicitly adds an `exclude: {type: "m.room.member"}` ?

I don't really understand what you're suggesting. `exclude: {type: "m.room.member"}` would mean we don't get any memberships at all. Did you mean `include`?

2026-05-20 09:46 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +invites or knocks, but can also be for when the user has rejected an invite.
For the case the user rejects an invite, that user should see the room come down sliding sync as stripped state. The other participants of the room will see the full leave event (as they're in the room).

We need the room to be in the "stripped" state case as the local server may be participating in the room and so doesn't have access to all the data anyway (and likely shouldn't leak it even if it did).

It also means if we send down an invite rejection down a sync that hadn't previously seen the room, we can correctly show the leave with the stripped state.

2026-05-20 09:56 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +      ],
Hero memberships may or may not also appear in `required_state` when using lazy loaded filters. It's a known issue that there is some duplication here, but the decision was made that it was good enough to leave it as is.

98ac3679

2026-05-20 10:00 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | Yes | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an even
We don't want to include your own membership as bump events as we specifically want to avoid display name changes from re-ordering the bump stamp. Ideally we'd want to be able to bump rooms that the user has explicitly joined (or left), but that is not something that can be easily done today.

We can revisit this when we find a better way of doing display name changes.

2026-05-20 10:01 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +1. How do we make it so that the clients don't have to send up the same body each time?
These were stale and I think captured in various discussion threads. They were mostly a way of me to remember where I had got up to with finalising the MSC.

Have removed the section in c2b465a8a3d0e114a709665265438a38fa506245

2026-05-20 10:14 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
How strongly do we feel like we should change the behaviour to not send heroes if there is a canonical alias?

2026-05-20 10:20 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +A `pos` token can be used in `/messages` and `/relations` APIs.
I've clarified that `pos` can be used in the same way as `next_batch` from `/v3/sync`.  The spec PR https://github.com/matrix-org/matrix-spec/pull/2357 tries to clarify this further in the spec itself.

2026-05-20 10:22 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +Note that for rooms the user has been banned from, but never joined, should not be part of the list.
Yeah, I think if we didn't have this for `/v3/sync` then we can leave this for a future MSC.

2026-05-20 10:24 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
But that ship has sailed, and I see little reason to add one now given a) we're so close to landing this MSC, and b) no client or server will ever use it.

2026-05-20 10:48 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +  any of the configs have `lazy_members` set to true.
Yeah, I don't think the thing about an implicit `exclude` makes much sense.

I've tried to clarify the behaviour in a854b1fe.

But fundamentally I think we need to handle two typical cases where we combine a lazy members config with one without:
1. Combining with a config that includes all state should combine to return all state (i.e. no lazy loading behaviour)
2. Combining with a config that does not return any membership should combine to one with lazy loading behaviour.

2026-05-20 10:57 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +
The example in question shows that the client quickly expands the list to include all rooms, and so this question isn't an issue.

If the client doesn't expand rooms and sets a range of `0..20`, then the only way to know if activity has happened outside that range is if we return exactly 20 rooms for that list. (Note that we order rooms by activity and not `bump_stamp` here)

2026-05-21 20:38 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
Another example of why heroes as an extension could be useful:

> [...] if a room had no avatar and we wanted to synthesize one from the heroes' avatars. But that hasn't come up in practice, and i would ignore it for now; it can be another MSC.
>
> *-- @ara4n, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r3030690707*

2026-05-21 21:09 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +
If someone just cares about updates, they don't necessarily want to paginate the entire list. Explaining what to look for could be useful even for understanding.

2026-06-11 13:18 UTC, weeman1337 commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
The description states that this is a server decision and most likely not a client error. This can be somehow misleading as a consumer. See https://httpwg.org/specs/rfc9110.html#status.400

If the server needs to free resources, it could return 429 for example. As a client developer, if I can't distinguish the error case, I would just start over when receiving a 400 with `M_UNKNOWN_POS`. That does maybe not help to free resources.

Also  `M_UNKNOWN_POS` indicates that there is most likely a logic error in the client implementation (position is unknown to the server). Using it as a „catch all“ is probably too broad.

At least I would like to have a differentiation between „the client did something wrong“ and „sever thinks that the client should start from the beginning“.

2026-06-16 10:54 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +a 400 HTTP status and an error code of `M_UNKNOWN_POS`.
It perhaps would be nice to inform the client if they had a logic error, but in practice its hard for the server to know without keeping information about all old positions around.

The only scenario of a client logic error that seems likely is if a client reuses an old position (e.g. due to restoring from a backup). 

Either way, restarting the sync connection is probably the right way to recover from this situation.

2026-06-16 11:42 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +top of the room list automatically get expanded timelines.
@MadLittleMods:

> > The initial SSS with state won't necessarily include the memberships required to render the timeline events returned in the oneshot initial sync.
> 
> It seems like this would work: `"required_state": { "lazy_members": true }`

Which won't include the all the memberships needed for subsequent syncs, and so you also need to have lazy memberships on for the second initial sync, and you're now back to duplicating a bunch of state. I really do think it's fair to say there is no race-free way of doing two initial syncs that both a) doesn't have race conditions, and b) doesn't duplicate a bunch of state.

Take a some other state, e.g. pinned events. You want to include that in the initial sync so that you can render the room. If you don't include that in the second initial sync you risk missing updates to it (especially if, due to network conditions, there is a substantial lag between the first and second). If you do include it in the second initial sync you're now duplicating the state.

I.e. I think you either run into data races OR duplicating a lot of state.

---

@richvdh:

> @erikjohnston / @MadLittleMods can you, between you, update the state of this thread?

Given this is talking about potential downsides of an alternative, I don't think resolving this thread is a particular blocker.

2026-06-16 11:48 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +
52eec8f3

2026-06-16 11:56 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
782a7458

2026-06-23 15:14 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +client in a dedicated extensions block.
Taking an executive decision and resolving this.

2026-06-23 15:23 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[StrippedHero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left user
I think we should get on with speccing what we have. If someone feels strongly about this, it can be changed later.

2026-06-23 15:55 UTC, richvdh commented on proposals/4186-simplified-sliding-sync.md
> +matches any of them, orb) merge the fields together, taking care to correctly account for configs that match against all
```suggestion
matches any of them, or b) merge the fields together, taking care to correctly account for configs that match against all
```

2026-06-23 16:11 UTC, richvdh approved these changes

2026-06-23 16:12 UTC, richvdh commented
@mscbot resolve unresolved threads

2026-06-24 21:13 UTC, anoadragon453 approved these changes
All seems sane to me, other than some clarifying questions.

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +request before receiving a response to an in-flight request (e.g. for retries or to change parameters) the client *must*
```suggestion
request before receiving a response to an in-flight request (e.g. for retries or to change parameters) the client MUST
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +cancel the in-flight request (at the HTTP level) and *not* process any response it receives for it. Clients MAY change
```suggestion
cancel the in-flight request (at the HTTP level) and MUST NOT process any response it receives for it. Clients MAY change
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +In particular, a client must use the returned `pos` value from the last *processed* response as the `pos` parameter in
```suggestion
In particular, a client MUST use the returned `pos` value from the last *processed* response as the `pos` parameter in
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +response.
In light of MSC4492, it would be worth specifying now that `pos` tokens are intended to be directionless.

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +Note that for rooms the user has been banned from, but never joined, should not be part of the list.
```suggestion
Note that rooms the user has been banned from, but never joined, should not be part of the list.
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +rooms the user has left themselves to save bandwidth and general efficiency (as the user knows they've left), but we
> We do not include rooms the user has left themselves to save bandwidth and general efficiency (as the user knows they've left)

Only if they left the room via this specific device, right? Otherwise how would your other devices know you'd left a room?

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +Specifically, a room matches a given list if after filtering the server-maintained list of rooms by the list's filters,
```suggestion
Specifically, a room matches a given list if, after filtering the server-maintained list of rooms by the list's filters,
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +  disabled return all membership events.
nit: I'm struggling to parse "no config which have `lazy_members` disabled return all membership events."

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +the room.
```suggestion
> the room.
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +This can be used to always include the user's own `membership event.
```suggestion
This can be used to always include the user's own membership event.
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +| `not_tags` | `[string]` | No | Filter the room based on its [room tags](https://spec.matrix.org/v1.16/client-server-api/#room-tagging).<br/><br/> Takes priority over `tags`. For example, a room wit
```suggestion
| `not_tags` | `[string]` | No | Filter the room based on its [room tags](https://spec.matrix.org/v1.16/client-server-api/#room-tagging).<br/><br/> Takes priority over `tags`. For example, a room with tags A and B with filters `tags: [A]` `not_tags: [B]` would NOT be included because `not_tags` takes priority over `tags`. This filter is useful so a client's general room list does NOT include the list of favourite rooms again. |
```

2026-06-24 21:13 UTC, anoadragon453 commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently may inadvertently return extra fields from the previous section.
Should this be removed? Has Synapse been fixed?
This won't make it into the spec PR anyhow.

2026-06-25 08:00 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
| Implementation | timeline array | invited-room state field | stripped-state element type |
|---|---|---|---|
| MSC4186 schema | [`timeline_events`](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L492) | [`stripped_state`](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L507) | [`StrippedState`](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L507), never defined |
| Synapse | [`timeline`](https://github.com/element-hq/synapse/blob/4e9f7757f17ba81b8747b7f8f9646d17df145aa3/synapse/rest/client/sync.py#L1012) | [`invite_state`](https://github.com/element-hq/synapse/blob/4e9f7757f17ba81b8747b7f8f9646d17df145aa3/synapse/rest/client/sync.py#L1043) | stripped events via [`strip_event`](https://github.com/element-hq/synapse/blob/4e9f7757f17ba81b8747b7f8f9646d17df145aa3/synapse/events/utils.py#L853) |
| Zendrite | [`timeline`](https://codefloe.com/pat-s/zendrite/src/commit/0878db55543ec51cad4b23c70bb8990e68fc9e56/syncapi/types/v4types.go#L281) | [both `invite_state` and `stripped_state`](https://codefloe.com/pat-s/zendrite/src/commit/0878db55543ec51cad4b23c70bb8990e68fc9e56/syncapi/types/v4types.go#L301-L302) | [`ClientEvent`](https://codefloe.com/pat-s/zendrite/src/commit/0878db55543ec51cad4b23c70bb8990e68fc9e56/syncapi/synctypes/clientevent.go#L63) |
| ruma (Tuwunel, Conduit, Continuwuity) | [`timeline`](https://github.com/ruma/ruma/blob/d82e91b17620ccc47a419eaef9376ba94144500c/crates/ruma-client-api/src/sync/sync_events/v5.rs#L614) | [`invite_state`](https://github.com/ruma/ruma/blob/d82e91b17620ccc47a419eaef9376ba94144500c/crates/ruma-client-api/src/sync/sync_events/v5.rs#L606) | [`AnyStrippedStateEvent`](https://github.com/ruma/ruma/blob/d82e91b17620ccc47a419eaef9376ba94144500c/crates/ruma-client-api/src/sync/sync_events/v5.rs#L606) |
| matrix-rust-sdk | consumes [`timeline`](https://github.com/matrix-org/matrix-rust-sdk/blob/4bd5e819302ac5fd0cce86e2ec602a7540247dd5/crates/matrix-sdk-base/src/response_processors/timeline.rs#L185) | reads [`invite_state`](https://github.com/matrix-org/matrix-rust-sdk/blob/4bd5e819302ac5fd0cce86e2ec602a7540247dd5/crates/matrix-sdk-base/src/response_processors/room/msc4186/mod.rs#L86) | `AnyStrippedStateEvent` via ruma |
| matrix-js-sdk | [`timeline`](https://github.com/matrix-org/matrix-js-sdk/blob/25c6171cb6a88ec7450472f8cf1a2d98823f2211/src/sliding-sync.ts#L100) | [`invite_state`](https://github.com/matrix-org/matrix-js-sdk/blob/25c6171cb6a88ec7450472f8cf1a2d98823f2211/src/sliding-sync.ts#L106) | [`IStrippedState`](https://github.com/matrix-org/matrix-js-sdk/blob/25c6171cb6a88ec7450472f8cf1a2d98823f2211/src/sync-accumulator.ts#L111) |

The schema names the timeline array `timeline_events`, but the [example](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L562) and every implementation use `timeline`; and `stripped_state` is typed `StrippedState`, a type the document never defines (only `StateStub` is). Aligning the schema with the example on the first, and defining `StrippedState` (or pointing to the `/v3/sync` stripped-state shape) on the second, would resolve both.

Separately, on the `invite_state` to `stripped_state` rename ([changelog #2](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L693)): Synapse and Element X still use `invite_state`, so Zendrite emits both (above) and notes in-source that the spec and the deployed clients disagree. Deciding which name servers should emit during the unstable period would let implementations converge instead of dual-emitting.

2026-06-25 08:36 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +Care must be taken, as with `/v3/sync`, to ensure that only the data that the user is authorized to see is returned in
Thanks for getting this across the line; we have been implementing the core of this on the server side and the proposal has been clear to follow.

One gap we noticed while doing it: the [Connections section](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L48) establishes that `pos` is server-issued and [scoped to a `(user, device, conn_id)` connection](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L55), but neither that section nor Security considerations says what a server should do with a `pos` that was issued to a *different* user or device. The persisted per-connection state this API introduces is what makes that matter. With `/v3/sync` a [`next_batch`](https://github.com/matrix-org/matrix-spec/blob/68ffc62de3da55353cc9fd52cb0e775ee453c15c/data/api/client-server/sync.yaml#L159) is a stateless cursor, but here a `pos` selects a stored server-side connection, so a server that keys that lookup on the token alone, rather than on the authenticated user and device, could return another user's view.

Synapse already [guards against this](https://github.com/element-hq/synapse/blob/4e9f7757f17ba81b8747b7f8f9646d17df145aa3/synapse/storage/databases/main/sliding_sync.py#L418-L431): it keys the stored-connection lookup on the requester's user, device, and `conn_id`, and a `pos` that does not match returns `M_UNKNOWN_POS`, on the stated basis that the `pos` is a user-supplied value that has to be confirmed as actually theirs. So this is a request to write the existing behavior into the spec rather than a report of a live bug. The proposal already defines [`M_UNKNOWN_POS`](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L74) for an unrecognized `pos`, so the same error covers the not-yours case. Would it be worth Security considerations stating something like:

> Servers MUST reject a `pos` that was not issued to the requesting user and device, responding with `M_UNKNOWN_POS`.

That keeps a from-scratch implementation from treating the token as a bearer capability. Clarifying ask, not a blocker on the FCP.

2026-06-26 11:24 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +response.
I think MSC4492 is a good illustration as to why I'm slightly nervous to spell out the exact properties. The intent here is that it works in the same as `/v3/sync`, and MSC4492 changes(/clarifies) the `/v3/sync` behaviour when/if it lands. Alternatively, we might decide MSC4492 isn't the right way forwards and tokens *should* encode direction, at which point we'd still want this MSC to align with `/v3/sync` behaviour.

Fundamentally, this MSC is not trying to change any behaviour around usages of tokens. We could add non-normative sections to remind people what the properties are at time of writing, but :shrug:

2026-06-26 11:28 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +rooms the user has left themselves to save bandwidth and general efficiency (as the user knows they've left), but we
No, we don't track this per-device. If the other devices are doing incremental syncs they will see the leave, as per the previous sentence:

> Rooms that the user has been in but left are only included if the room was previously sent to the client in that connection.

This does have an edge case where if a client resets their connection, they won't know if the user has left a room until they sync the entire room list and see that it is missing. I'm not really sure what we can do about that in this API shape TBH

2026-06-26 11:29 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +> Synapse currently may inadvertently return extra fields from the previous section.
I think as a non-normative flag about where the current Synapse implementation diverges from the MSC is helpful here. We're not fixing up the Synapse implementation until after this MSC lands.

2026-06-26 11:34 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +  disabled return all membership events.
Hopefully ba83167a should clarify if:

> if and only if a) any of the configs have `lazy_members` set to true AND b) there are no configs that return all membership events (and don't have `lazy_members` set).

2026-06-26 11:43 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +Care must be taken, as with `/v3/sync`, to ensure that only the data that the user is authorized to see is returned in
Yes, that's a good point. Technically the MSC requires that the server only send down information the user is allowed to see, but there is definitely a potential footgun here.

I've made checking ownership of `pos` mandatory, and update the security considerations in 06bbf14b

2026-06-26 11:50 UTC, erikjohnston commented on proposals/4186-simplified-sliding-sync.md
> +| `timeline_events` | `[Event]` | No | The latest events in the room. May not include all events if e.g. there were more events than the configured `timeline_limit`, c.f. the `limited` field. <br/><b
> The schema names the timeline array `timeline_events`, but the [example](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L562) and every implementation use `timeline`

Oh good catch. This has come from confused naming internally in Synapse. 3695caad

> `StrippedState`, a type the document never defines (only `StateStub` is).

Ah yes, that is relying on the existing definition in the spec. We already point to `/v3/sync` in the comment for that field.


> Separately, on the `invite_state` to `stripped_state` rename ([changelog #2](https://github.com/matrix-org/matrix-spec-proposals/blob/c94e5681750b5ee3dd055ab5ad035bb5226bee4b/proposals/4186-simplified-sliding-sync.md?plain=1#L693)): Synapse and Element X still use `invite_state`, so Zendrite emits both (above) and notes in-source that the spec and the deployed clients disagree. Deciding which name servers should emit during the unstable period would let implementations converge instead of dual-emitting.

We've basically taken the view that we're not going to update the unstable implementations, as the majority of the changes are cosmetic and accept that the request/response shapes differ depending on if you're using the unstable vs stable prefix.

2026-06-26 23:07 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +   flush any "membership" cache when `limited` is true. This is in contrast to Synapse's implementation of lazy-loading
Thanks for adding the [`pos`-ownership requirement](https://github.com/matrix-org/matrix-spec-proposals/blob/3695caadd9d7e6b93f2ab4087c0bf6bf1ed16544/proposals/4186-simplified-sliding-sync.md?plain=1#L675-L679). One more for Security considerations, on the membership-cache flush in the [lazy-loading section](https://github.com/matrix-org/matrix-spec-proposals/blob/3695caadd9d7e6b93f2ab4087c0bf6bf1ed16544/proposals/4186-simplified-sliding-sync.md?plain=1#L306).

The text says that because [membership updates are not necessarily sent when `limited` is true](https://github.com/matrix-org/matrix-spec-proposals/blob/3695caadd9d7e6b93f2ab4087c0bf6bf1ed16544/proposals/4186-simplified-sliding-sync.md?plain=1#L332-L333), clients must flush any membership cache on a `limited` response, and it gives the reason that cache exists: a client needs the membership list ["to send an encrypted message to the room"](https://github.com/matrix-org/matrix-spec-proposals/blob/3695caadd9d7e6b93f2ab4087c0bf6bf1ed16544/proposals/4186-simplified-sliding-sync.md?plain=1#L329). Putting those together, the flush has an E2EE consequence the Security section does not call out. After a gappy sync a client has dropped its membership list, and if it sends an encrypted message before refetching it (or if the refetch races the send), it computes the recipient set over a stale member set and can miss a member who joined during the gap, so that member's devices cannot decrypt.

This is the room-membership axis, which this MSC mandates, and it is distinct from device-list change delivery (handled by the e2ee extension[^e2ee-ext]): a client with perfectly tracked device lists can still miss a recipient if its membership list is stale, and neither this section nor the e2ee extension analyzes that interaction. It seems worth Security considerations noting that after a `limited` response a client must refetch the membership list (not merely invalidate it) before using it as an encryption recipient set.

[^e2ee-ext]: MSC3884 (Sliding Sync Extension: E2EE); its Security considerations section adds nothing beyond `/sync`: https://github.com/matrix-org/matrix-spec-proposals/blob/5ff5682b114354577dad775dd2d9b653cf531f0f/proposals/3884-sliding-sync-e2ee.md?plain=1#L81-L83

2026-06-29 22:04 UTC, merged

2026-07-02 02:40 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +ordering is determined by the server implementation.
Still missing the root of the reason:

> This way clients receive all new events.
>
> *-- @MadLittleMods, https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2105301689*

2026-07-13 18:31 UTC, gamesguru commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | No | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an event
To avoid clients and servers disagreeing on tie-breaks and possibly duplicating events on the boundary (or missing them entirely), it seems a deterministic tie breaker, i.e., lexicographically by `room_id`, is needed.

Also, `bump_stamp` never exceeds `2^53 - 1` (which could happen if they use nanoseconds).

2026-07-13 18:31 UTC, gamesguru commented on proposals/4186-simplified-sliding-sync.md
> +connection. Rooms the user has been kicked or banned from will always be included in the server list. We do not include
This seems a potential performance bottleneck -- if an account's been `banned/kicked` from hundreds or thousands of rooms, the server still has to load and sort all of them? Just to figure out the active window, on every single long-polling request.

If top-level `membership` becomes required and authoritative for returned rooms, that at least removes one reason to keep dragging archived rooms back into active list calculations just to recover missed leaves/bans after a disconnect.

I'd still be curious in follow-up work to see if `SlidingRoomFilter` could grow a `memberships` array (`filters: { memberships: ["join", "invite"] }`) so clients can opt out of `banned/kicked` rooms unless they explicitly open an archived view.

2026-07-13 18:31 UTC, gamesguru commented on proposals/4186-simplified-sliding-sync.md
> +remains unchanged from its previous value. When `initial` is set to `true` then an omitted field means that the field is
Line 465 seems to have a delta-sync disconnect with line 479.

If `initial: false`, then any *omitted* field can be assumed unchanged (line 465). But line 479 says omitting `lists` means the room dropped out of all lists (and is only in the payload due to a subscription).

A single JSON omission *can't* mean "unchanged" and "empty" at once. If a room legitimately drops out, the server MUST return an explicit empty array (`"lists": []`). We need strict key omission to universally signify a lack of change across the board.

2026-07-13 18:31 UTC, gamesguru commented on proposals/4186-simplified-sliding-sync.md
> +`expanded_timeline` to `true`. (Note that one could infer this from `num_live`, however it is better to be explicit).
This seems difficult for the server to accurately maintain and track.

To detect a `timeline_limit` *increase*, the server is forced to heavily cache previous configs for each client request. If the server loses track, the client receives no historic events.

Given the removal of "sticky" lists (per Changelog item 10), **clients** should pass an explicit flag (e.g., `expand_timeline: true`) to intentionally grow the window. Otherwise, we're forcing the server to memorize past requests and run a precarious diff... just to figure out if the limit went up.

2026-07-13 18:31 UTC, gamesguru commented on proposals/4186-simplified-sliding-sync.md
> +| `heroes` | `[Hero]` | No | A truncated list of users in the room that can be used to calculate the room name. Will first include joined users, then invited users, and then finally left users: the s
To handle deleted state, the MSC adds a `StateStub` object that only has `type` / `state_key` (no `content`). Parsing `[Event | StateStub]` in strongly-typed languages (Rust, or `mypy`-strict Python) is tedious/error-prone. Could we explore alternatives here?

Matrix already has a way to represent cleared state: an event with an empty `content: {}`; could we drop `StateStub` and use that instead, so client parsers don't need a special case?

2026-07-13 18:31 UTC, gamesguru commented on proposals/4186-simplified-sliding-sync.md
> +| `membership` | `string` | No | The current membership of the user, or omitted if the does not a have a membership event in the room (for peeking). |
I noticed Erik's comment above about clients dropping connections and missing "Left" rooms (*"I'm not really sure what we can do about that in this API shape TBH"*).

This ties into a data-retention issue recently reported. If a server purges old `m.room.member` events (`banned` / `left` rooms), it can't populate the user in the `required_state`. Since the top-level membership field is optional, clients (like `matrix-rust-sdk`) might guess and default to `join`. That can resurrect dead rooms.

Could `membership` just be REQUIRED and authoritative for every returned room where the server knows the user's current or historical membership (`join/leave/invite/ban`)? It seems like this should only be omitted for true peeking / no-membership cases. Servers can populate it from internal membership tables instead of digging up potentially-purged events.

That'd also fix Erik's edge case above: on a connection reset, a client passes its known rooms into `room_subscriptions`, and if they were `banned/kicked` elsewhere, the subscription comes back with an authoritative `membership` instead of relying on `required_state` inference or full list pagination to rediscover it.

2026-07-13 22:47 UTC, Malix-Labs commented
@gamesguru late to comment

2026-07-29 19:59 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +client in a dedicated extensions block.
Continued in https://github.com/matrix-org/matrix-spec-proposals/pull/4508#discussion_r3677651482

2026-08-06 12:40 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +will cause the room to bubble to the top of the list. If it was based on e.g. `bump_stamp` then clients would need to
While playing with tuning EX's sync perf, i'm hit this and i'm not convinced it's the right behaviour.

Some apps will indeed want the proposed roomlist to be ordered based on whatever had most recent activity (whether that activity was visible or not) - e.g. a bot.

Others (like EX) i suspect really *do* want the roomlist to be ordered based on bumpstamp - i.e. the server's best guess as to a room list ordering based on the rooms' most recent visible events.  This is because the client will then reorder the rooms once it knows the actual most recent visible event, and we want the jumping around when that happens to be minimised.

Therefore, in a future MSC, I really suggest we allow the client to give a hint on how it wants the room list to be ordered - be that by activity (most recent event timestamp), or bumpstamp (i.e. visible activity: approximate most-recently-visible-event timestamps), or even alphabetically.

2026-08-06 12:44 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +| `bump_stamp` | `int` | No | An integer that can be used to sort rooms based on the last "proper" activity in the room. Greater means more recent. <br/><br/> "Proper" activity is defined as an event
I still find it hard to wrap my head around bumpstamp.  Perhaps a better description (when we come to actually spec it) would be "An order key which reflects the server's best guess of visible activity in a room, useful as a first pass for ordering rooms in the client for rooms where the client has yet to calculate an accurate most-recent-visible-event".

And perhaps a better name would be approximate_visible_activity_order_key - although honestly weird jargon like bump_stamp is probably good enough assuming it is sufficiently well defined.

2026-08-06 12:48 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +> Rooms are ***not*** ordered by "`bump_stamp`", a field returned in the room response.
why? stating this unilaterally without justification feels very strange, especially when bump_stamp exists for the purposes of... ordering rooms.

2026-08-06 13:09 UTC, ara4n commented on proposals/4186-simplified-sliding-sync.md
> +this can be done.
"this can be done?" @erikjohnston is this a truncated sentence fragment or just redundant wording or...?

2026-08-06 14:44 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +> Rooms are ***not*** ordered by "`bump_stamp`", a field returned in the room response.
Agreed. I tried to get this clarified earlier in https://github.com/matrix-org/matrix-spec-proposals/pull/4186#discussion_r2376696659 but nothing came of it.

2026-08-06 16:58 UTC, MadLittleMods commented on proposals/4186-simplified-sliding-sync.md
> +will cause the room to bubble to the top of the list. If it was based on e.g. `bump_stamp` then clients would need to
This is a bit of [deja-vu](https://matrix.to/#/!cnVVNLKqgUzNTOFQkz:matrix.org/$67tPYJyarhZF0aesrx9KeutEhi_Fr4S8PU3o5uPZgBo?via=element.io&via=matrix.org&via=one.ems.host) as we had a similar internal discussion from 2024-07-03 and then a slightly more clear [discussion](https://matrix.to/#/!cnVVNLKqgUzNTOFQkz:matrix.org/$1pIuczy8owjGbWfA3GY6vEvtWOiwKwVhLXzMWb2kYfk?via=element.io&via=matrix.org&via=one.ems.host) on 2024-07-04.

My conclusion back then was that it makes sense to keep sorting the room list by most recent activity so clients receive all new events. But @ara4n had the same thoughts being presented now about the room list jumping around. The conclusion at the time was that we needed to just try it out and could iterate based on that.

There are trade-offs to both sides. Thinking about it more now:

A room's `bump_stamp` is always the same or lower than its most recent activity position, never higher. And the rooms where those two positions differ most are big public rooms with lots of join/leave churn but few messages (exactly the rooms a user has a lot of and cares least about). Encrypted rooms barely diverge, since the server can't tell an encrypted reaction from an encrypted message and counts both as bump events.

If we're using the growing pagination strategy suggested in the MSC:

### Most recent activity ordering

You ask for `[0,19]`. The server gives you the 20 rooms with the most recent anything. Several slots go to Matrix HQ and similar, which are at the top only because people joined and left, and whose last actual message was three days ago. You sort those 20 rooms by `bump_stamp` and draw them. Matrix HQ lands at 14. Fine so far.

You ask for `[0,39]`. Twenty more rooms arrive. One of them is a book club room where someone posted a message twenty minutes ago but which had no other traffic, so it wasn't in the first page. It inserts at position 2, and everything below shifts down a row. This can continue until you grow to paginate the entire list.

The benefit of this strategy is that if something happened in a room, the client knows about it. Someone redacts a message in an old project room you last used a month ago, that room jumps to position 0 and gets sent to you. You're never showing stale data.

### `bump_stamp` ordering

You ask for `[0,19]`. You get the 20 rooms with the most recent bump events which is already correct for the room list.

You ask for `[0,39]`. The next 20 rooms all have older `bump_stamp` events than everything you already have, so they all land below the existing list. The top doesn't move. Keep expanding and the top still doesn't move. The list grows downward and never reshuffles (mostly).

There's still some jitter for end-to-end encrypted rooms, because the client re-sorts once it decrypts and finds that the opaque bump event was actually a reaction. But that only ever pushes a room further down. Even more jitter, if the client has to keep paginating the timeline further to find a relevant bump event.

The downside of this strategy is that the old project room where someone just redacted a message sits at bump position 4000 and stays there. It never enters your window, so the server never sends you the redaction, so you keep displaying a message that no longer exists. Same for a room being renamed, getting a new avatar, being tombstoned, or someone joining. Rooms outside your window quietly rot, and you have no way to know it happened.


### Perhaps both?

If we allowed setting which order you want on a per-list basis, you could have a list for updates and a list for room-list ordering.

But even better:

Perhaps for any new room ("first time the server is sending this [room] on this connection") returned down sync, we use `bump_stamp` but otherwise sort by most recent activity.

In the context of the examples I gave above, the book club room now arrives in the first page, because it's ranked by `bump_stamp`. Matrix HQ doesn't squat a slot. And the redaction in the month-old project room still arrives, because that room has been sent and is therefore ranked by most recent activity.

For example with Synapse, we would implement the sort by checking for `HaveSentRoomFlag.NEVER` for each room and use `bump_stamp` otherwise `stream_ordering` of the room's most recent event.

2026-10-23 14:13 UTC, jevolk commented on proposals/4186-simplified-sliding-sync.md
> +| `lists` | `{string: SyncListResult}` | No | A map of list key to list results. |
Suggested wording for this row: "A map of list key to list results. Contains an entry for every list in the request's `lists`, on every response, including lists that currently match no rooms."

Synapse sends every requested list each time ([room_lists.py](https://github.com/element-hq/synapse/blob/v1.163.1/synapse/handlers/sliding_sync/room_lists.py#L485-L592), [sync.py](https://github.com/element-hq/synapse/blob/v1.163.1/synapse/rest/client/sync.py#L935-L940)), and matrix-rust-sdk depends on that: a list absent from the response is [left untouched](https://github.com/matrix-org/matrix-rust-sdk/blob/matrix-sdk-0.19.1/crates/matrix-sdk/src/sliding_sync/mod.rs#L423-L435), so a growing list never becomes fully loaded and the room list service [keeps sending `timeout=0`](https://github.com/matrix-org/matrix-rust-sdk/blob/matrix-sdk-ui-0.19.1/crates/matrix-sdk-ui/src/room_list_service/mod.rs#L252-L259). We hit this in Tuwunel with a fresh account that had no rooms: our responses were `{"pos": "..."}` with no `lists` at all, and the SDK, set up the way Element X uses it, infinite loops. [matrix-rust-sdk#6361](https://github.com/matrix-org/matrix-rust-sdk/pull/6361) is the same loop from another server. The example usage section already assumes the client [uses the returned `count` to stop expanding](https://github.com/matrix-org/matrix-spec-proposals/blob/ffc54bc05c827edfb9791cfd7c154837c8487204/proposals/4186-simplified-sliding-sync.md?plain=1#L619-L620); the schema just never says the count is always returned.