MSC4191: Account management for OAuth 2.0 API
matrix-org/matrix-doc pull request #4191
Opened 2024-09-12 15:49 UTC by sandhose

[Rendered](https://github.com/matrix-org/matrix-spec-proposals/blob/quenting/account-deeplink/proposals/4191-account-deeplink.md)

Implementions:

- Server
  - Synapse via [matrix-authentication-service](https://github.com/element-hq/matrix-authentication-service)
    - [x] Exposes `account_management_uri` and `account_management_actions_supported` values in metadata. e.g. https://matrix-client.matrix.org/_matrix/client/v1/auth_metadata
    - [x] Provides a UX at the advertised URIs with support for the `action` and `device_id` parameters
- Clients
  - [x] Element Web
    - Supported actions include: `org.matrix.session_end`
  - [x] Element X
    - Supported actions include: `org.matrix.profile`, `org.matrix.sessions_list`

To do:

- [x] Update references to MSC3861 as it has been accepted
- [x] Add clarification about being the replacement for delete devices API endpoints when using OAuth 2.0 API
- [x] Check for consistency with MSC3824

---

In line with https://github.com/matrix-org/matrix-spec/issues/1700, the following disclosure applies:

I am a Software Engineer at Element. This proposal was written and published as an Element employee.

----

SCT Stuff:

[FCP tickyboxes](https://github.com/matrix-org/matrix-spec-proposals/pull/4191#issuecomment-3330262419)

[MSC checklist](https://github.com/matrix-org/matrix-spec-proposals/pull/4191#issuecomment-3330263076)

2025-03-18 16:34 UTC, t3chguy commented on proposals/4191-account-deeplink.md
> +- `id_token_hint` - An ID Token that was previously issued to the client; the issuer uses it as a hint for which user is requesting to manage their account.
This doesn't work for OIDC-Aware (Compat) sessions, unlike MSC4198

Just encountered the issue where I had Account_A logged into Element, but Account_B logged into MAS. Tried to manage a session to log it out, and got an awful error and then saw most of my sessions were missing. Took me a few minutes to figure out the accounts were not the same. Informing the IdP which account the user expects is crucial IMO.

![image](https://github.com/user-attachments/assets/b5f79bb3-c839-4d99-a225-4d635286343e)

2025-03-18 17:29 UTC, tonkku107 commented on proposals/4191-account-deeplink.md
> +- `id_token_hint` - An ID Token that was previously issued to the client; the issuer uses it as a hint for which user is requesting to manage their account.
That parameter also won't be very helpful with OIDC-native (or should we call them Next Gen Auth -native now?) clients that don't request the `openid` scope since that's no longer necessary

2025-09-15 14:44 UTC, hughns commented on proposals/4191-account-deeplink.md
> +- `id_token_hint` - An ID Token that was previously issued to the client; the issuer uses it as a hint for which user is requesting to manage their account.
> OIDC-native (or should we call them Next Gen Auth -native now?)

I suggest calling them OAuth 2.0 native clients.

2025-09-17 13:06 UTC, hughns commented on proposals/4191-account-deeplink.md
> +- `id_token_hint` - An ID Token that was previously issued to the client; the issuer uses it as a hint for which user is requesting to manage their account.
I was discussing with @sandhose and thoughts are that MSC4198 would be a better way to do this. So, I am going to remove `id_token_hint` from this MSC.

2025-09-17 14:27 UTC, tonkku107 commented on proposals/4191-account-deeplink.md
> +- `id_token_hint` - An ID Token that was previously issued to the client; the issuer uses it as a hint for which user is requesting to manage their account.
Regarding the comment on MSC4198:
> Propose that the `login_hint` can also be added to the MSC4191 account management URL query parameters

Wouldn't the best place for that be in this proposal with a dependency to MSC4198?

2025-09-23 11:38 UTC, hughns commented on proposals/4191-account-deeplink.md
> +OAuth 2.0 API (becuase the API endpoints to delete devices are not supported when using the OAuth 2.0 API).
```suggestion
OAuth 2.0 API (because the API endpoints to delete devices are not supported when using the OAuth 2.0 API).
```

2025-09-24 19:00 UTC, turt2live commented
@mscbot fcp merge
@mscbot concern Pending preliminary approval from oauth-ext-review to use the new names - https://mailarchive.ietf.org/arch/msg/oauth-ext-review/6RQXusbqFTy-XZCGwLSW-RIa9Dg/

2025-09-24 19:00 UTC, turt2live commented
MSCs proposed for Final Comment Period (FCP) should meet the requirements outlined in the [checklist](https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md) prior to being accepted into the spec. This checklist is a bit long, but aims to reduce the number of follow-on MSCs after a feature lands. 

SCT members: please check off things you check for, and raise a concern against FCP if the checklist is incomplete. If an item doesn't apply, prefer to check it rather than remove it. Unchecking items is encouraged where applicable.

MSC authors: feel free to ask *in a thread* on your MSC or in the[#matrix-spec:matrix.org](https://matrix.to/#/#matrix-spec:matrix.org) room for clarification of any of these points.

- [x] Are [appropriate implementation(s)](https://spec.matrix.org/proposals/#implementing-a-proposal) specified in the MSC’s PR description?
- [x] Are all MSCs that this MSC depends on already accepted?
- [x] For each new endpoint that is introduced:
  - [x] Have authentication requirements been specified?
  - [x] Have rate-limiting requirements been specified?
  - [x] Have guest access requirements been specified?
  - [x] Are error responses specified?
    - [x] Does each error case have a specified `errcode` (e.g. `M_FORBIDDEN`) and HTTP status code?
      - [x] If a new `errcode` is introduced, is it clear that it is new?
- [x] Will the MSC require a new room version, and if so, has that been made clear?
  - [x] Is the reason for a new room version clearly stated? For example, modifying the set of redacted fields changes how event IDs are calculated, thus requiring a new room version.
- [x] Are backwards-compatibility concerns appropriately addressed?
- [x] Are the [endpoint conventions](https://spec.matrix.org/latest/appendices/#conventions-for-matrix-apis) honoured?
  - [x] Do HTTP endpoints `use_underscores_like_this`?
  - [x] Will the endpoint return unbounded data? If so, has pagination been considered?
  - [x] If the endpoint utilises pagination, is it consistent with [the appendices](https://spec.matrix.org/latest/appendices/#pagination)?
- [x] An introduction exists and clearly outlines the problem being solved. Ideally, the first paragraph should be understandable by a non-technical audience.
- [x] All outstanding threads are resolved
  - [x] All feedback is incorporated into the proposal text itself, either as a fix or noted as an alternative
- [x] While the exact sections do not need to be present, the details implied by the proposal template are covered. Namely:
  - [x] Introduction
  - [x] Proposal text
  - [x] Potential issues
  - [x] Alternatives
  - [x] Dependencies
- [x] Stable identifiers are used throughout the proposal, except for the unstable prefix section
  - [x] Unstable prefixes [consider](https://github.com/matrix-org/matrix-spec-proposals/blob/main/README.md#unstable-prefixes) the awkward accepted-but-not-merged state
  - [x] Chosen unstable prefixes do not pollute any global namespace (use “org.matrix.mscXXXX”, not “org.matrix”).
- [x] Changes have applicable [Sign Off](https://github.com/matrix-org/matrix-spec-proposals/blob/main/CONTRIBUTING.md#sign-off) from all authors/editors/contributors
- [x] There is a dedicated "Security Considerations" section which detail any possible attacks/vulnerabilities this proposal may introduce, even if this is "None.". See [RFC3552](https://datatracker.ietf.org/doc/html/rfc3552) for things to think about, but in particular pay attention to the [OWASP Top Ten](https://owasp.org/www-project-top-ten/).

2025-09-24 19:58 UTC, clokep commented on proposals/4191-account-deeplink.md
> +- `org.matrix.session_end` - The user wishes to end/logout a specific session.
Why session and not device to match current terminology?

2025-09-24 19:58 UTC, clokep commented on proposals/4191-account-deeplink.md
> +`https://account.example.com/myaccount?action=org.matrix.session_end&device_id=ABCDEFGH`.
Maybe it is covered in security sections already but this feels like potential for phishing or malicious users creating links? Device IDs, the homeserver URL are public, so one can easily craft links to have someone log out devices.

The security section mentions needing to reauthenticate, but maybe also some user action needs to be required to avoid a user authenticating without really knowing why?

2025-09-25 09:10 UTC, hughns commented on proposals/4191-account-deeplink.md
> +`https://account.example.com/myaccount?action=org.matrix.session_end&device_id=ABCDEFGH`.
I agree this should be explicit and is in 0b27bdd2124cdc1e1fe5f7db9d298f103246b7aa

The implementation of this in MAS does indeed require confirmation of the action 👍

2025-09-25 09:12 UTC, hughns commented on proposals/4191-account-deeplink.md
> +- `org.matrix.session_end` - The user wishes to end/logout a specific session.
I believe the original rationale for this is that OAuth 2.0 refers to sessions, whereas devices is a Matrix concept.

@sandhose can you provide any other context on this?

2025-09-25 13:56 UTC, hughns commented on proposals/4191-account-deeplink.md
> +- `org.matrix.session_end` - The user wishes to end/logout a specific session.
@sandhose has said that originally these values didn't have a `org.matrix` prefix and it felt right to use the OAuth terminology of sessions.

However, now that these values are prefixed it does seem entirely reasonable to revisit them and give them names that make sense for Matrix.

How about:

- `org.matrix.devices_list`
- `org.matrix.device_view`
- `org.matrix.device_delete` (`delete` doesn't feel quite right, but I can't think of anything better right now)

Given that these are just value renames rather than anything semantic, could they be adjusted later in the spec process rather than requiring the implementations to be updated prior to FCP?

2025-09-25 15:28 UTC, clokep commented on proposals/4191-account-deeplink.md
> +- `org.matrix.session_end` - The user wishes to end/logout a specific session.
That would be fine, yes.

2025-09-25 22:43 UTC, uhoreg commented on proposals/4191-account-deeplink.md
> +In doing so, this proposal also resolves the issue that the is currently no specced way to delete devices using the
nit:

```suggestion
In doing so, this proposal also resolves the issue that there is currently no specced way to delete devices using the
```

2025-09-25 22:43 UTC, uhoreg commented on proposals/4191-account-deeplink.md
> +This is why the metadata fields are not prefixed with `org.matrix.`, but the actions themselves are.
I assume this is also the reason why the actions are using `org.matrix.` rather than the `m.` that is normally used in the Matrix spec?

2025-09-25 22:43 UTC, uhoreg commented on proposals/4191-account-deeplink.md
> +The account management URL (as provided above) may accept the following additional query parameters:
Do clients need a way to determine whether the management URL does accept the query parameters?

2025-09-25 22:43 UTC, uhoreg commented on proposals/4191-account-deeplink.md
> +n.b. This isn't a complete alternative to this full MSC and is instead just considers an alternative way for device
nit:

```suggestion
n.b. This isn't a complete alternative to this full MSC and instead just considers an alternative way for device
```

2025-09-29 15:25 UTC, hughns commented on proposals/4191-account-deeplink.md
> +The account management URL (as provided above) may accept the following additional query parameters:
It already does for the `action` (via the `account_management_actions_supported`). I've added a note to say that the server *should* support `device_id` for `org.matrix.device_view` and `org.matrix.device_delete`

2025-09-29 15:26 UTC, hughns commented on proposals/4191-account-deeplink.md
> +- `org.matrix.session_end` - The user wishes to end/logout a specific session.
I've updated the values in 9e1fbf5ac22720efcf65fc8e60c9128ea389b08d and left this thread unresolved to reflect that the implementation in MAS is using the non-stable values.

2025-09-29 15:27 UTC, hughns commented on proposals/4191-account-deeplink.md
> +This is why the metadata fields are not prefixed with `org.matrix.`, but the actions themselves are.
Yes. I've added a further comment about this in https://github.com/matrix-org/matrix-spec-proposals/commit/9e1fbf5ac22720efcf65fc8e60c9128ea389b08d#diff-a71172f1154cf40383ff506bd6a10e6bd97689fd5d60af1a5ad2e2cd9b6676c6R61-R63

2025-09-29 17:59 UTC, uhoreg commented on proposals/4191-account-deeplink.md
> +The account management URL (as provided above) may accept the following additional query parameters:
Ah, OK.  I missed that the actions given in there were the actions that were accepted by the query param.  I was thinking that it was just a generic "The system supports doing these things somehow".

2025-09-30 17:01 UTC, richvdh commented on proposals/4191-account-deeplink.md
> +- `DELETE /_matrix/client/v3/devices/{deviceId}`
links are always helpful

```suggestion
- [`POST /_matrix/client/v3/delete_devices`](https://spec.matrix.org/v1.16/client-server-api/#post_matrixclientv3delete_devices)
- [`DELETE /_matrix/client/v3/devices/{deviceId}`](https://spec.matrix.org/v1.16/client-server-api/#delete_matrixclientv3devicesdeviceid)
```

2025-10-17 12:49 UTC, Johennes commented on proposals/4191-account-deeplink.md
> +- `org.matrix.account_deactivate` - The user wishes to deactivate their account.
Since https://github.com/matrix-org/matrix-spec-proposals/pull/4312 has already landed and is being spec'ed in https://github.com/matrix-org/matrix-spec/pull/2234, we might want to add the contained action type here.

```suggestion
- `org.matrix.account_deactivate` - The user wishes to deactivate their account.
- `org.matrix.cross_signing_reset` - The user wishes to reset their cross-signing identity.
```

2025-10-20 09:56 UTC, hughns commented on proposals/4191-account-deeplink.md
> +- `org.matrix.account_deactivate` - The user wishes to deactivate their account.
Yes, this makes sense. I will add a reference to https://github.com/matrix-org/matrix-spec-proposals/blob/ea0aef0aa32ee979b4db14bb869938a597777346/proposals/4312-x-signing-reset-with-nextgen-auth.md?plain=1#L55-L58 too so that we don't forget the detail when writing the spec PR.

2025-10-29 11:40 UTC, tonkku107 requested changes
`org.matrix.session_end` was renamed to `org.matrix.device_delete` but the rest of the proposal didn't follow

2025-10-29 11:40 UTC, tonkku107 commented on proposals/4191-account-deeplink.md
> +`https://account.example.com/myaccount?action=org.matrix.session_end&device_id=ABCDEFGH`.
```suggestion
`https://account.example.com/myaccount?action=org.matrix.device_delete&device_id=ABCDEFGH`.
```

2025-10-29 11:40 UTC, tonkku107 commented on proposals/4191-account-deeplink.md
> +As an alternative to the proposed `org.matrix.session_end` action the above device deletion endpoints could be instead
```suggestion
As an alternative to the proposed `org.matrix.device_delete` action the above device deletion endpoints could be instead
```

2025-10-29 11:40 UTC, tonkku107 commented on proposals/4191-account-deeplink.md
> +For the `org.matrix.session_end` action the
```suggestion
For the `org.matrix.device_delete` action the
```

2025-10-29 11:40 UTC, tonkku107 commented on proposals/4191-account-deeplink.md
> +Consequently for the destructive `org.matrix.session_end` and `org.matrix.account_deactivate` actions the server SHOULD
```suggestion
Consequently for the destructive `org.matrix.device_delete` and `org.matrix.account_deactivate` actions the server SHOULD
```

2025-10-29 11:40 UTC, tonkku107 commented on proposals/4191-account-deeplink.md
> +actions (`org.matrix.session_end` and `org.matrix.account_deactivate`) the server MUST inform the user of what the
```suggestion
actions (`org.matrix.device_delete` and `org.matrix.account_deactivate`) the server MUST inform the user of what the
```

2025-11-18 03:09 UTC, turt2live commented
Per recent emails sent to oauth-ext-review on our thread, it seems possible to allow this MSC to go through without formal registration. When we get to the spec PR, we should verbosely describe the fields so we can point to them in a more complete registration application. 

@mscbot resolve Pending preliminary approval from oauth-ext-review to use the new names - https://mailarchive.ietf.org/arch/msg/oauth-ext-review/6RQXusbqFTy-XZCGwLSW-RIa9Dg/

2025-11-24 03:18 UTC, merged

2025-12-16 19:42 UTC, zecakeh commented
Spec PR: https://github.com/matrix-org/matrix-spec/pull/2270

2026-01-20 18:07 UTC, turt2live commented
Merged 🎉